### ISSUE TITLE
Treating legitimate tabs as popups. 

### ISSUE THREAD

**Issue by oMarethyu** [gorhill/uBlock#3418] opened 2018-01-08 15:06 UTC
If you choose to block all popups on a site, then select a piece of text and try to google it with the right click drop down, it will treat the new tab as a popup and immediately close it. 

You can easily replicate this by simply enabling all popups blocked, and then selecting some text, right click and select search google. It will open a new tab, then close it.

**Comment by Hrxn** [comment] 2018-01-08 15:08
Probably a limitation by the browser?

**Comment by gorhill** [comment] 2018-01-08 15:18
Duplicate of #3282.

**Closed by gorhill** 2018-01-08 15:18 UTC
Labels: duplicate
