### ISSUE TITLE
"Restore from file..." button does not work on Android

### ISSUE THREAD

**Issue by Poonkraft** [gorhill/uBlock#3161] opened 2017-10-22 14:01 UTC
### Describe the issue
uBO 1.14.16 + Waterfox 52.2 + Android 7.0
"Restore from file..." button does nothing, the other two buttons ("Back up to file", "Reset to default settings..." work fine.

### One or more specific URLs where the issue occurs
URL n/a

### Screenshot in which the issue can be seen
Screenshot n/a

### Steps for anyone to reproduce the issue
1. Go to dashboard
2. Tap Restore from file...
3. Nothing happens

### Your settings
Default settings

##### Your filter lists
Default filter list

##### Your custom filters (if any)
No custom filters

**Comment by gorhill** [comment] 2017-10-22 15:08
I don't explicitly support "Waterfox 52.2". I tested on Tor browser, which is based on Firefox 52 ESR, and restoring worked fine.

So you will have to investigate on your side the cause of the issue. I will address it if and only if you make the case is with uBO itself.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-10-22 15:08 UTC
Labels: invalid

**Comment by gorhill** [comment] 2017-10-22 15:14
By the way, permissions to access storage must be given to Firefox 56 for uBO to be able to read backup file. Could be something similar on your side.
