### ISSUE TITLE
Element picker & zapper mode not working

### ISSUE THREAD

**Issue by pepablock** [gorhill/uBlock#3265] opened 2017-11-22 15:24 UTC
### Describe the issue

If I try to use either of these I just get a blank overlay all over the page and nothing happens. And I have to refresh the page to see the content again. I made a short gif to show what I mean, see below. Also, I think I'm not the only one experiencing this problem, see:
https://www.reddit.com/r/uBlockOrigin/comments/7cy3rv/element_blocker_doesnt_work_in_firefox_57/
https://www.reddit.com/r/uBlockOrigin/comments/7ehtdc/element_picker_doesnt_work_anymore/

### One or more specific URLs where the issue occurs

Everywhere

### Screenshot in which the issue can be seen

![2017-11-22 4 14 10 pm](https://user-images.githubusercontent.com/29940017/33134920-4a6bcd9a-cfa1-11e7-9f96-bb658ccc2f97.gif)

### Steps for anyone to reproduce the issue

–

### Your settings

- OS/version: **macOS High Sierra/10.13.1**
- Browser/version: **Firefox Quantum 57.0 (64-bit)**
- uBlock Origin version: **1.14.18**

##### Your filter lists

Default filter lists + CZE, SVK: EasyList Czech and Slovak

##### Your custom filters (if any)

–

**Comment by gorhill** [comment] 2017-11-22 15:32
Unable to reproduce. Try in a new profile with uBO alone -- no other extension.

**Comment by gorhill** [comment] 2017-11-22 15:33
Also, you seem to have a modified version of uBO, the power button color does not match the color used in the original version.

**Comment by f4grx** [comment] 2017-11-24 11:50
confirmed to be broken in win10 too, and ublock origin is the only installed extension.

**Comment by f4grx** [comment] 2017-11-24 11:50
confirmed to be broken in win10 too, and ublock origin is the only installed extension.

**Comment by gorhill** [comment] 2017-11-24 11:59
> I dont even have an overlay.

Did you inspect the DOM?

**Comment by slorquet** [comment] 2017-11-24 12:16
I dont know what to search for in the DOM.

it still works with a new profile, but not in my current profile. I have no idea what has broken my profile but it's not an extension.

Maybe a "migration process" from firefox 56 to 57 has broken it...

Now the only option to make ublock work again is too loose all by bookmarks and history

**Comment by gorhill** [comment] 2017-11-24 12:36
I am pretty sure you have user styles overriding uBO's own styles. You will have to look into this. See if you have a userContent.css file in your profile, and its content if so: <http://kb.mozillazine.org/index.php?title=UserChrome.css>.

**Comment by f4grx** [comment] 2017-11-24 12:43
I dont have a single css file anywhere in my firefox profile.
I am using firefox with default settings, not pretty customization at all.

**Comment by gorhill** [comment] 2017-11-24 12:46
> I dont know what to search for in the DOM.

Look for a `iframe` at the bottom of the document, uBO inserts its `iframe` before the closing `html` tag. If it's there, then select the `iframe` and see what rule is being applied to it in the CSS styles inspector.

**Comment by f4grx** [comment] 2017-11-24 12:49
I got it working again, that is strange.

I had other tabs with contents not reloaded yet after a crash. opening these tabs so that their DOM was loaded seem to have fixed the issue.

This is very weird for me. Does it make sense to you?

**Comment by gorhill** [comment] 2017-11-24 12:51
> Does it make sense to you?

No. Seems to be a Firefox specific quirk possibly due to the tab being in the same content process as some other tabs which were suspended? I can only speculate.

**Comment by pepablock** [comment] 2017-11-24 15:52
Sorry for a late response.
>See if you have a userContent.css file in your profile, and its content if so: http://kb.mozillazine.org/index.php?title=UserChrome.css.

That was the case for me, I had this code inside of my userContent.css file causing the problem. I used this to get a blank page after opening a new tab. I guess from now I will use an add-on for that instead.
```
@-moz-document url(about:blank), url(about:newtab) {
	* {
		display: none !important;
	}
}
```

>Also, you seem to have a modified version of uBO, the power button color does not match the color used in the original version.

What color is default? I don't remember modifying it at all.

**Closed** 2017-11-24 15:52 UTC
Labels: unable to reproduce
