### ISSUE TITLE
ublock is not working in firefox private browsing

### ISSUE THREAD

**Issue by sasatefa2009** [gorhill/uBlock#2927] opened 2017-08-30 01:05 UTC
As the title says, uBlock origin is not working in Firefox private window
windows 7 sp1 x64
Firefox version 55.0.3 64 bit

**Comment by LawrencevR** [comment] 2017-08-30 04:24
W10 64 with Firefox version 55.0.3 64 bit and latest off the firefox add-ons does work.......................... but only if you install it every time. Soon as you close Firefox uBlock is listed as installed in the Firefox Add-ons but its inactive and the little icon showing its presence is missing.................... thus tons of garbage is again thrown at me. Please have a look again gorhill?

**Comment by sasatefa2009** [comment] 2017-08-30 04:51
@gorhill please have a look instead of throwing it at garbage

**Comment by durffy** [comment] 2017-08-30 05:02
I'm experiencing this issue as well. Issue may be permissions which seems new to add-ons. I too have windows 10, running in firefox(normal mode).
![image](https://user-images.githubusercontent.com/20616426/29856101-89eea12e-8d05-11e7-83cc-8593567eeb00.png)

**Comment by sasatefa2009** [comment] 2017-08-30 05:26
@durffy @LawrencevR  okay guys i think i've found the solution. you need to navigate to the ublock origin extension webpageon firefox while on private browsing and install it again.

**Comment by LawrencevR** [comment] 2017-08-30 05:51
Glad it worked for you - didn’t for me. Soon as I close Firefox its awol again

**Comment by shevegen** [comment] 2017-08-30 06:30
sasatefa2009, gorhill has to reproduce the bug so the more information you can provide, the better.

**Comment by flolilo** [comment] 2017-08-30 09:56
I too have this problem. µBlock Origin/webext hybrid 1.13.10 Firefox 55.0.3 (x64), Windows 10 Pro (1703) x64.  I did not change anything in the configuration. It does happen both in private mode and regular instances of Firefox.

Disabling and re-enabling µBlock does not make a difference, but if I uninstall and re-install it, the µBlock-logo (and its function) is restored.

**Comment by Schokolader** [comment] 2017-08-30 13:24
same issue here. I have Firefox 55.03 and Windows 7. Ublock is not working. Even the button disappeared. I installed it new and it worked. Closed Firefox. Start Firefox. And it stopped working. Button disappeared.

**Comment by flolilo** [comment] 2017-08-30 14:37
On a sidenote: Isn't this a duplicate of #2909 ?

**Comment by gorhill** [comment] 2017-08-30 17:54
Report to `https://bugzilla.mozilla.org/`.

**Closed by gorhill** 2017-08-30 17:54 UTC
Labels: browser bug, unable to reproduce
