### ISSUE TITLE
 uBlock doesn't inject/work on homepages that start with browser launch

### ISSUE THREAD

**Issue by ceribik** [gorhill/uBlock#3253] opened 2017-11-20 22:48 UTC
### Describe the issue
When starting the browser, uBlock origin does not work/inject on the homepages that load when you first start the browser (I have around 10 homepages). You can this tell because: a) there are placeholder ads boxes, b) the element zapper and element picker tools don't work on those pages. If I reload the pages, uBlock starts working again.

This only started happening when I migrated to firefox 57. However, I was also using the webextension version of uBlock origin on Firefox 56 and I did not have this issue. 

### One or more specific URLs where the issue occurs
https://www.inoreader.com/

### Screenshot in which the issue can be seen
https://i.imgur.com/F97ydSv.jpg

### Steps for anyone to reproduce the issue

1. Install firefox 57
2. Set a reasonable amount of homepages e.g. 10 (N.B. I have not tested with fewer homepages)
3. Start the browser
4. Watch that uBlock origin does not work or load on the homepages until you refresh them.

### Your settings

- OS/version: Arch Linux latest
- Browser/version: Firefox 57
- uBlock Origin version: 1.14.18 on "medium mode"

##### Your filter lists

Default filter lists

##### Your custom filters (if any)

N/A

**Comment by ceribik** [comment] 2017-11-20 22:52
Shortly after writing this, I investigated the browser console and saw a lot of spam on browser launch from another addon called CanvasBlocker. By disabling and reenabling CanvasBlocker, it allowed uBlock to start working again on browser launch.

I left this here for future reference in case someone else encounters the same issue.

**Comment by uBlock-user** [comment] 2017-11-21 04:23
Use ScriptSafe instead of CanvasBlocker, it a collection of FingerPrinting settings and doesn't break other extensions.

**Comment by TonyTough** [comment] 2017-11-21 10:49
I have the same problem with pages like focus.de or bild.de when loaded as first page at browser start.

I think the problem started with Firefox 56 or 56.02 and with 57 it's the same. So it seems it's a bug in Firefox.
Deactivation of all other Add-Ons doesn't change anything.

**Comment by ceribik** [comment] 2017-11-22 23:24
I'll look into it thanks.

I'm still getting this issue after disabling CanvasBlocker so I've reopened this.

**Comment by gorhill** [comment] 2017-11-22 23:49
Duplicate of #1327.

**Closed by gorhill** 2017-11-22 23:49 UTC
