### ISSUE TITLE
Unusable after showing list of blocked resources

### ISSUE THREAD

**Issue by ygoe** [gorhill/uBlock#3288] opened 2017-11-27 20:38 UTC
### Describe the issue

After showing the list of blocked resources, only this list is ever visible. I never get to see the main page of the add-on again, the one with the big "turn off" button. The "back" arrow in the top left corner brings me back to the Firefox "overflow menu" but not the uBlock main view.

### One or more specific URLs where the issue occurs

Everywhere

### Screenshot in which the issue can be seen

![grafik](https://user-images.githubusercontent.com/868315/33288008-fc828498-d3ba-11e7-881a-9ed127dba844.png)

### Steps for anyone to reproduce the issue

1. Open any website
2. Open the uBlock addon panel from the toolbar
3. Show the list of blocked resources

### Your settings

- OS/version: Firefox 57
- Browser/version: Windows 10
- uBlock Origin version: 1.14.18

##### Your filter lists

Default + German

##### Your custom filters (if any)

Block 3rd party Facebook, Twitter etc. (should not apply to this issue)

**Comment by gorhill** [comment] 2017-11-27 21:32
Duplicate of #2809.

Please search the issue tracker before opening a new issue:
https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+overflow+menu

**Closed by gorhill** 2017-11-27 21:32 UTC
Labels: duplicate
