### ISSUE TITLE
uBo stopped working on FF 55/Android 6.0

### ISSUE THREAD

**Issue by Rezmate** [gorhill/uBlock#2917] opened 2017-08-29 14:19 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
2 days ago ubo stopped displaying the dashboard, now it no longer works

### One or more specific URLs where the issue occurs
any webpage

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
the dashboard doesn't open at all, so no need for screenshot
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version:  Android 6.0.1
- Browser/version: Firefox 55.0.2 (latest)
- uBlock Origin version: 1.13.10

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment] 2017-08-29 14:46
Duplicate of #2909.

**Closed by gorhill** 2017-08-29 14:46 UTC
Labels: duplicate
