### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by Mapwritingcentral** [gorhill/uBlock#2587] opened 2017-05-06 23:56 UTC
I have Windows 10.
I'm receiving an Extension Error on Google Chrome Browser Version 58.0.3029.96 (64-bit)
Google Chrome is up to date.
 Superblock Extended Superblock Extended - Adblocker 1.0.1.1
Newest version of our popular base Adblocker. Extended Features.

The warning is listed below.  Please note, I've been receiving similar extension errors on a continual basis from my Ghostery extension.  The issue was recently resolved, as you can see from my extension list: 

Ghostery 7.2.0.25
Protect your privacy. See who's tracking your web browsing with Ghostery.
Details  Options

Allow in incognito
 
Enabled

  

Superblock Extended - Adblocker 1.0.1.1
Newest version of our popular base Adblocker. Extended Features.
Details  Options
Warning:
This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZlbG9wZXJzLmdvb2dsZS5jb20vYW5hbHl0aWNzL2Rldmd1aWRlcy9jb2xsZWN0aW9uL2FuYWx5dGljc2pzLwoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07Cgl2YXIgbm9vcG51bGxmbiA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiBudWxsOwoJfTsKCS8vCgl2YXIgVHJhY2tlciA9IGZ1bmN0aW9uKCkgewoJCTsKCX07Cgl2YXIgcCA9IFRyYWNrZXIucHJvdG90eXBlOwoJcC5nZXQgPSBub29wZm47CglwLnNldCA9IG5vb3BmbjsKCXAuc2VuZCA9IG5vb3BmbjsKCS8vCgl2YXIgZ2FOYW1lID0gd2luZG93Lkdvb2dsZUFuYWx5dGljc09iamVjdCB8fCAnZ2EnOwoJdmFyIGdhID0gZnVuY3Rpb24oKSB7CgkJdmFyIGxlbiA9IGFyZ3VtZW50cy5sZW5ndGg7CgkJaWYgKCBsZW4gPT09IDAgKSB7CgkJCXJldHVybjsKCQl9CgkJdmFyIGYgPSBhcmd1bWVudHNbbGVuLTFdOwoJCWlmICggdHlwZW9mIGYgIT09ICdvYmplY3QnIHx8IGYgPT09IG51bGwgfHwgdHlwZW9mIGYuaGl0Q2FsbGJhY2sgIT09ICdmdW5jdGlvbicgKSB7CgkJCXJldHVybjsKCQl9CgkJdHJ5IHsKCQkJZi5oaXRDYWxsYmFjaygpOwoJCX0gY2F0Y2ggKGV4KSB7CgkJfQoJfTsKCWdhLmNyZWF0ZSA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiBuZXcgVHJhY2tlcigpOwoJfTsKCWdhLmdldEJ5TmFtZSA9IG5vb3BudWxsZm47CglnYS5nZXRBbGwgPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gW107Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs= because another extension (Ghostery) redirected it to data:application/javascript;base64,dmFyIHVyY2hpblRyYWNrZXI9ZnVuY3Rpb24oKXt9LF9nYXE9e3B1c2g6ZnVuY3Rpb24oKXt0cnkge2lmKGFyZ3VtZW50c1swXVswXT09J19saW5rJyl3aW5kb3cubG9jYXRpb24uaHJlZj1hcmd1bWVudHNbMF1bMV19Y2F0Y2goZXIpe319fSxfZ2F0PXtfY3JlYXRlVHJhY2tlcjpmdW5jdGlvbigpe30sIF9nZXRUcmFja2VyOmZ1bmN0aW9uKCl7cmV0dXJue19fbm9TdWNoTWV0aG9kX186ZnVuY3Rpb24oKXt9LF9saW5rOmZ1bmN0aW9uKG8pe2lmKG8pbG9jYXRpb24uaHJlZj1vO30sX2xpbmtCeVBvc3Q6ZnVuY3Rpb24oKXtyZXR1cm4gdHJ1ZTt9LF9nZXRMaW5rZXJVcmw6ZnVuY3Rpb24obyl7cmV0dXJuIG87fSxfdHJhY2tFdmVudDpmdW5jdGlvbigpe319fX07.

Allow in incognito
 
Enabled

  

Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by bershan2** [comment] 2017-05-07 01:41
@Mapwritingcentral this is the GitHub repository of the uBlock Origin ([Chrome store](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en)) developed and maintained by Raymond Hill, but you are using [Superblock Extended Superblock Extended - Adblocker](https://chrome.google.com/webstore/detail/superblock-extended-adblo/kmljjoddjjkoidiahlgbgjjgodcajhgf/support?hl=en). **They are completely different extensions.** That extension support is on Chrome Web Store [here](https://chrome.google.com/webstore/detail/superblock-extended-adblo/kmljjoddjjkoidiahlgbgjjgodcajhgf/support?hl=en).

Your issue is probably due to the authors of that extension sloppily combining two other extensions in one package. If you got here by clicking the link on the "Settings -> About", that is because they forgot to change the links. Try to guess how much work they invested into the code...

For reference:
* uBlock Origin (source code) is free to copy (under [GPL GPL 3](https://github.com/gorhill/uBlock/blob/master/LICENSE.txt) and many unrelated people made lots of clones ([677](https://github.com/gorhill/uBlock/network) to be exact). This extension is maintained by the original creator Raymond Hill and sees the most rapid development and therefore viewed as the "reference". But [Superblock Extended - Adblocker](https://chrome.google.com/webstore/detail/superblock-extended-adblo/kmljjoddjjkoidiahlgbgjjgodcajhgf?hl=en) is not related to this repository aside from copying the code. It specifies in the description:
> This is a fork of the Adblock Pro & uBlock Origin. We use this code under GPL and removed some code.
> This extension is not affiliated or related in any way with: Adblock, Adblock Plus, Adblock Premium, Adguard AdBlocker, Adblock for Youtube, AdRemover for Google Chrome, Ad Block - AdFilter, YouTube AdBlock,  Adblock Pro, Adblock Super, Simply Block Ads, Adblock for Facebook, uBlock Ultimate Adblocker, Adblock Fast, **uBlock Origin**, uBlock Plus, uBlock Pro, Anti-Adblock Popup Blocker.
* Superblock Extended - Adblocker actually violates GNU GPL because it does not provide link to the source code.
* That extension code is out of date -- it's based on 1.7.2.0, [released](https://github.com/gorhill/uBlock/releases/tag/1.7.2) back in May 2016.
* There is no point in "SuperAdBlocks" that combine two or more blockers -- they all do the same thing and running two at once just consumes resources. Instead, add the appropriate filter lists.

Lastly, (biased) advice: **get rid of a rip-off and install the real thing.**

**Comment by gorhill** [comment] 2017-05-07 10:31
@Mapwritingcentral What @bershan2 said

 At the end of the day, users are the one responsible to be careful to install legit extensions, not the ones that are out to get fool you. Not performing due diligence when installing something that "can read and change your data on all sites" is you working against you.

In any case, if you had the real uBlock Origin installed, you would still have the warning from the browser -- it's by browser design. Duplicate of #1170.

**Closed by gorhill** 2017-05-07 10:31 UTC
