### ISSUE TITLE
Crashes on Inox-Patchset (Chromium fork/build)

### ISSUE THREAD

**Issue by RomanSC** [gorhill/uBlock#853] opened 2015-10-22 00:51 UTC
Heyya

I've installed uBlock Origin on Inox (See here: https://github.com/gcarq/inox-patchset) Not sure whether to call this a fork or just a different build of chromium, it's essentially the same as Chromium, here's the description: "Inox patchset tries to provide a minimal Chromium based browser with focus on privacy by disabling data transmission to Google."

I posted the issue on the Inox github too:
https://github.com/gcarq/inox-patchset/issues/4

The issue is simply that uBlock Origin crashes as soon as it starts on Inox, all other installed extensions are working.

Any troubleshooting help is greatly appreciated

Thanks

**Comment by gorhill** [comment] 2015-10-22 04:27
Probably duplicate of #533.

**Comment by RomanSC** [comment] 2015-10-22 04:32
Yeah, it looks like it's the same issue

**Comment by gorhill** [comment] 2015-10-23 13:34
Closing as duplicate of #533.

**Closed by gorhill** 2015-10-23 13:34 UTC
