### ISSUE TITLE
RFE: cosmetic filtering integration with the firefox web-inspector

### ISSUE THREAD

**Issue by bagodoosh** [gorhill/uBlock#771] opened 2015-10-01 19:10 UTC
it would be nice to merge the changes from chrisaljoudi branch, regarding the integration with firefox's web-inspector.

added in chrisaljoudi  0.9.3.5, apr 19, 2015.
if i'm not mistaken: chrisaljoudi/uBlock#1211 + chrisaljoudi/uBlock#1324

**Comment by harshanvn** [comment] 2015-10-01 19:17
See <a href="https://github.com/gorhill/uBlock/wiki/DOM-inspector">DOM Inspector</a>. gorhill implemented in browser independent way, unlike the other one.

**Comment by bagodoosh** [comment] 2015-10-01 19:46
i understand. i thought this browser-specific feature would be a nice addition, if it does not cause a conflict.

**Comment by AlexVallat** [comment] 2015-10-02 07:22
If you don't mind building the xpi from source, I've got a branch that does exactly that: https://github.com/AlexVallat/uBlock/tree/gorhil-master

**Comment by gorhill** [comment] 2015-12-30 20:56
Duplicate of #119.

**Closed by gorhill** 2015-12-30 20:56 UTC
