### ISSUE TITLE
uBlock Origin ignores changed tld

### ISSUE THREAD

**Issue by maycontainnuts** [gorhill/uBlock#1514] opened 2016-03-28 10:17 UTC
ublock version: 1.6.6
browser: firefox 45.0.1 on debian linux and also on windows 7 

i'm using advanced mode with "block all" and some whitelisted domains. after update to latest ublock version there's some strange behavior: 

- open a whitelisted domain in a browser tab.
- change to another whitelisted domain. 
- ublock seems to ignore changed context.

in this example i used tagesspiegel.de and golem.de, but it "works" also with different domains.
![screenshot_small](https://cloud.githubusercontent.com/assets/10872215/14075807/a3fa99aa-f4dc-11e5-87e7-4c761d94e61b.jpg)

problem doesn't appear after each domain change. 
restarting the browser or ubock "will solve" the problem for some time but it will reappear.

**Comment by gorhill** [comment] 2016-03-28 12:56
I can't reproduce.

When this occurs, can you look if there is anything related to uBO in the browser console?

Similar issue: #1512.

**Comment by gorhill** [comment] 2016-03-28 13:06
@AlexVallat I did some changes in [frameScript.js](https://github.com/gorhill/uBlock/blob/master/platform/firefox/frameScript.js), would you mind looking to see if there is something wrong in the code? My goal was to get rid of the run-at-boot-time-only code, and keep the content of frameScript.js only for code needed after boot time.

**Comment by gorhill** [comment] 2016-03-28 14:04
@maycontainnuts Do you have any other extensions installed?

**Comment by AlexVallat** [comment] 2016-03-28 14:12
I haven't tried reproducing it yet, but looking at the code, I'm not clear on how the ```shutdown``` listener is supposed to work. Quite possibly I'm missing something cunning, but if the problem is that the block owning locationChangeListener is dropping out of scope, then are you sure the shutdown listener would stop that happening?

**Comment by AlexVallat** [comment] 2016-03-28 14:28
Oh, never mind, I see you've added ```locationChangeListener``` to the closure in a later commit, my mistake. In that case I'll have a go at reproducing the issue and see if I can spot anything.

**Comment by gorhill** [comment] 2016-03-28 15:13
I don't know if this is of interest: the previous code was testing `nsIWebProgress.DOMWindow.top`, while the new code tests `nsIWebProgress.isTopLevel`.

**Comment by AlexVallat** [comment] 2016-03-28 19:31
Hmm. I've had a poke through dxr to investigate these - DOMWindow.top just walks up a chain of window.parents, but .isTopLevel I'm not so sure about. I did find [.isTopLevel](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/window/utils.js#156) exported by utils.js which uses [nsIDocShellTreeItem.rootTreeItem](https://dxr.mozilla.org/mozilla-central/source/addon-sdk/source/lib/sdk/window/utils.js#135). A little further research dug up this interesting bit of info: [Limitations of frame scripts](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Message_Manager/_Limitations_of_frame_scripts#QI_from_content_window_to_chrome_window) which sounds suspiciously like it won't work.

But, on the other hand, I'm not convinced that that is the actual code being used by ```nsIWebProgress.isTopLevel```, as it seems to be in the addon-sdk path.

It seems more likely that it would be using the [nsDocLoader](https://dxr.mozilla.org/mozilla-central/source/uriloader/base/nsDocLoader.cpp#901) implementation directly, in which case it is using the exact same ```DOMWindow.top``` property internally anyway.

So, I don't know, if for whatever reason uBlock might end up using that utils.js version then I guess that could cause a problem. It's all pretty much guesswork without being able to repro it, though.

**Comment by gorhill** [comment] 2016-03-29 15:43
This has been reported by a few people now, but it seems a rare occurrence.

Since such issue was non-existent with 1.6.4, I have modified the code to be closer to what was in 1.6.4 -- build available on AMO as dev version 1.6.7b0. For those who can reproduce at will, it would be nice if you could try the latest dev build to see if this solves the issue.

**Comment by ThurahT** [comment] 2016-03-29 17:48
Ah, sorry for duplicate, I should have looked closer. Yes I can reproduce it with the sites in my screen shot. Testing 1.6.7b and the bug is still there. I can actually populate the list if I continue to surf to different sites. The blocked sites just adds up. It doesn't matter if the sites are white listed or not.

**Comment by gorhill** [comment] 2016-03-29 19:02
@ThurahT Do you mind installing a non-signed version? I made some code changes and it would be best if you could try it directly rather than me having to push it to AMO dev channel.

**Comment by ThurahT** [comment] 2016-03-29 19:23
Sure, I'll gladly test the new builds. As mentioned in bug 1515 the 1.6.7b0 version still suffered the bug. Restating twice to be sure.

**Comment by AlexVallat** [comment] 2016-03-29 19:25
Just had a look through that old code of mine. Yep, can't see any good reason for having ```this.docShell``` assigned. I don't remember doing it deliberately, and if it was something hacky then I would have added a comment explaining it. Absent any better explanation, I'm going to assume it was debugging assistance that I missed stripping.

**Comment by gorhill** [comment] 2016-03-29 19:52
@ThurahT I posted a non-signed version at <https://github.com/gorhill/uBlock/releases/tag/1.6.7b1>. If this does not work, would you mind installing 1.6.4 and verifying that the issue did not occur with that version?

**Comment by ThurahT** [comment] 2016-03-29 20:22
OMG... I am so stupid... : (  I Totally forgot I ran chatZilla... So, no.. I never really closed the process since chatZilla runs in a SeaMonkey process.. I can't believe I missed that.

Um.. 1.6.7b1 runs as a dream.. I experienced no issues at all. Might as well got fixed in 1.6.7b0 since I was stupid. 

So issue fixed!  : ) I can confirm though, that the bug did not exist in 1.6.4.

Thanks for being a great developer!

**Comment by gorhill** [comment] 2016-03-29 20:34
> I never really closed the process since chatZilla runs in a SeaMonkey process

That is interesting, so is it possible 1.6.6 was running well after all as long as FF process was restarted? That would explain the why it was difficult to reproduce. In any case I would keep the changes made for b1, but I would no longer consider this to be an emergency fix if you can confirm 1.6.6 release worked well too after cleanly restarting FF/SM. (Normally not required, but in 1.6.6 changes were made to `frameModule.js`).

**Comment by ThurahT** [comment] 2016-03-29 20:40
I had a six day uptime on that irc server and 1.6.6 got installed after.. So yeah, it is possible.. But that wouldn't explain the author of this bug thread  though, since he is on FF and chatZilla (if he uses it) runs in its own process then I think?

**Comment by cnnrhill** [comment] 2016-03-30 18:13
I also experienced this problem with 1.6.6 (Firefox 43, Ubuntu 14.04) on Monday after running FF for a couple days. Restarting the browser seems to have fixed the issue for now.

**Comment by ezeenova** [comment] 2016-03-31 09:18
Can confirm issue with 1.6.6, Iceweasel/Firefox 38.6.1 on Debian 7. Browser has only been running a few hours.

**Closed** 2016-04-08 16:05 UTC
