### ISSUE TITLE
Clicking eBay links requires a page refresh to load the new page (again..)

### ISSUE THREAD

**Issue by patrickdrd** [gorhill/uBlock#3285] opened 2017-11-27 13:26 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Similar as this one: "[Firefox] Clicking eBay links requires a page refresh to load the new page #2947"
I'm using firefox esr 52.5.0 (32bit) and ublock origin 1.14.18 and 
whatever I click on ebay page I have to do a refresh for it to continue...
With previous ublock origin version (1.13.8) it works fine, but I don't want to use that,
because I saw the 3rd-party filters are enhanced in the latest version..
Anyway, I have noscript addon, but it is disabled, but it still doesn't work,
any suggestions?

### One or more specific URLs where the issue occurs
ebay.com/*

[URL(s) for issue on a specific site are **mandatory**]
ebay.com/*

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7
- Browser/version: Firefox ESR 52.5.0 (32bit)
- uBlock Origin version: 1.14.18 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
all minus experimental

##### Your custom filters (if any)
not a problem with these

**Comment by gorhill** [comment] 2017-11-27 13:44
Browser bug, fixed in FF57.

Duplicate of #2947.

Please search issue tracker before opening new issue next time: <https://github.com/gorhill/uBlock/issues?q=is%3Aissue+ebay+is%3Aclosed>.

**Closed by gorhill** 2017-11-27 13:44 UTC
Labels: browser bug, duplicate

**Comment by patrickdrd** [comment] 2017-11-27 13:52
I know, I searched and my myself posted the #2947,
but where's the solution because I can't seen to find one and 2947 is closed!!!
