### ISSUE TITLE
Not blocking malicious content?

### ISSUE THREAD

**Issue by Salsa74** [gorhill/uBlock#258] opened 2015-05-29 14:31 UTC
First off all sorry for my bad english, not my native language.
And since im not a tech savvy guy, this is the best i can explain.
I came across uBlock by reading the lifehacker site ( i was using NoScript prior to try ublock)
the thing is, when i click in a shrinked link ( adfly ) , the web page tries to acess my router configuration... and that didnt happen when i was using NoScript.
I can provide the link that triger that behavior. ( h t t p : // a d f . l y / 1 3 5 r s s )
best regards.

**Comment by gorhill** [comment] 2015-05-29 14:48
Your issue suffers a lot from lack of details (Please read [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include)), and this is especially bad given your claim _"web page tries to acess my router configuration"_. Here is what I got using default settings (another thing you do not disclose):

![c](https://cloud.githubusercontent.com/assets/585534/7885127/32c4cc28-05f0-11e5-98e2-9927f6eebe95.png)

**Comment by gorhill** [comment] 2015-05-29 14:48
Marked as unable to reproduce, and worst, itś not even clear what is to be reproduced.

**Comment by Salsa74** [comment] 2015-05-29 17:38
sorry for the lack of information, i have unistalled and reistalled ublock and cant reproduce what was wrong annymore. fell free to delete the topic
Just trying to help

**Comment by gorhill** [comment] 2015-05-29 17:55
If you think there is something wrong, your best first move is to make use of the logger, it tells you everything uBlock is doing with the network requests. If you think the logger confirms that there is something wrong, use it in your report next time -- could be a screenshot of it even.

**Closed as completed by gorhill** 2015-05-29 17:55 UTC
Labels: unable to reproduce
