### ISSUE TITLE
Question about the chrome store update

### ISSUE THREAD

**Issue by Redshift91** [gorhill/uBlock#1042] opened 2015-12-10 10:49 UTC
I am wondering why is the latest ublock origin is out 3 weeks but the chrome store still doesnt updated to the 1.3.6 version?Thanks.

**Comment by tauxeta** [comment] 2015-12-10 11:02
https://github.com/gorhill/uBlock/issues/1019

**Comment by Redshift91** [comment] 2015-12-10 11:45
Thanks Tauxeta the info!

**Comment by gorhill** [comment] 2015-12-11 11:01
Duplicate of #1019.

**Closed by gorhill** 2015-12-11 11:01 UTC
