### ISSUE TITLE
[Firefox 40 nightly only] Popup window UI broken in last commit 

### ISSUE THREAD

**Issue by Betsy25** [gorhill/uBlock#108] opened 2015-04-22 19:45 UTC
Firefox v40 (nightly)
Win7
Using commit d141af71ffc496f1dfdb923c6926de77bbfd5d19

This is what the popup looks like when on any youtube page : 
![Screenshot on Youtube pages](http://i.imgur.com/ImeARYp.png)

On the "for current site only" there is a clickable colon missing.
Weird thing is, this only seems to happen on like 50% of sites.

For example, all is fine on github, but on youtube- and other sites it's broken.

Broken for me on these : 
- http://fileforum.betanews.com/
- https://www.youtube.com/feed/subscriptions
- http://www.majorgeeks.com/

**Comment by gorhill** [comment] 2015-04-22 19:58
I am not seeing this on FF37.

**Comment by Betsy25** [comment] 2015-04-22 20:01
Indeed, all is fine in FF37...

**Comment by gorhill** [comment] 2015-04-22 20:03
The added rule should have no effect whatsoever on the width of the pane. If this happens only because of that rule, this is a browser bug.

**Comment by Betsy25** [comment] 2015-04-22 20:13
@gorhill Yep, I reverted to Ublocko 0.9.4.2 and it still occurs, must be a browser bug.
Close at will.

**Comment by gorhill** [comment] 2015-04-22 20:13
Does it also happen with uBlock 0.9.3.5?

**Comment by Betsy25** [comment] 2015-04-22 20:15
I only see 0.9.4.0 and 0.9.3.0 on the releases page, you want me to checkout 0.9.3.0 ?

**Comment by Betsy25** [comment] 2015-04-22 20:20
Using Chris' uBlock 0.9.3.5 , same thing although there is a white band, but also only 2 selectable columns.
![Chris' uBlock 0.9.3.5](http://i.imgur.com/mfZvAo9.png)

**Comment by gorhill** [comment] 2015-04-22 20:54
It looks to me the vertical white band is where a scroll bar would go, so FF40 improperly rendering vertical scrollbars might be the bug. The peculiarity in there is that uBlock uses `rtl` for the dynamic filtering pane, in order to force teh scrollbar to render on the left side. This should probably be reported as a big to FF dev.

**Comment by Betsy25** [comment] 2015-04-22 20:56
I reverted FF to the 2015-04-21 nightly and all is fine.
So, bug/change introduced in todays FF nightly.

**Comment by WyohKnott** [comment] 2015-04-22 22:24
> It looks to me the vertical white band is where a scroll bar would go, so FF40 improperly rendering vertical scrollbars might be the bug. The peculiarity in there is that uBlock uses rtl for the dynamic filtering pane, in order to force the scrollbar to render on the left side

It seems that the space of the scrollbar is pushing the content to the right. Interestingly changing to ```ltr``` does not produce the bug, the rules are displayed correctly with the scrollbar on the right.

**Comment by WyohKnott** [comment] 2015-04-22 22:35
This is probably the relevant commit: http://hg.mozilla.org/mozilla-central/rev/3c3337ed60a1

And the relevant bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1139306

**Comment by alice0775** [comment] 2015-04-23 04:41
No

This was caused by https://hg.mozilla.org/mozilla-central/rev/17aad8f83237
And fixed by backed out https://hg.mozilla.org/mozilla-central/rev/570bb53a3e7b

I 've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1157560

**Comment by Betsy25** [comment] 2015-04-23 04:53
Thanks a lot @alice0775 :+1:

**Closed as completed** 2015-04-23 22:54 UTC
Labels: browser bug
