### ISSUE TITLE
No Text on Settings-Buttons

### ISSUE THREAD

**Issue by allo-** [gorhill/uBlock#243] opened 2015-05-25 17:28 UTC
On the about:addons page of the addon there are two buttons (dashboard, and devtools), which are both blank (no text on them at all).

Version: 0.9.1.0, german locale

**Comment by gorhill** [comment] 2015-05-25 19:31
Browser version please.

**Comment by allo-** [comment] 2015-05-25 19:33
34.0.5

**Comment by Betsy25** [comment] 2015-05-26 01:11
All show fine here.

[Firefox 38.0.1](http://i.imgur.com/c9VfhBI.png)
[Firefox 41nightly](http://i.imgur.com/QtorUKZ.png)

**Comment by allo-** [comment] 2015-05-26 06:41
Inspektor says:

    <setting xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" type="control" desc="" first-row="true">
    <vbox>
    <button id="showDashboardButton" label=""/>
    <button id="showNetworkLogButton" label=""/>
    </vbox>
    </setting>

**Comment by EchoDev** [comment] 2015-05-29 18:04
Can you try switching to English locale and see if the problem is fixed?

FF39 with English locale here and it looks fine.

**Comment by gorhill** [comment] 2015-05-29 18:41
Those strings are also in German: <https://github.com/gorhill/uBlock/blob/master/src/_locales/de/messages.json#L494>.

**Comment by allo-** [comment] 2015-05-31 15:47
Happens on 38.0.1, too.

**Comment by gorhill** [comment] 2015-12-11 16:31
If the issue was still there, possibly fixed with 9ce6f9eb23196b4b8b6617299c82385589d92983. Re-open if it still occurs.

**Closed as completed by gorhill** 2015-12-11 16:31 UTC
Labels: unable to reproduce

**Comment by allo-** [comment] 2015-12-11 16:33
Works for me.
