### ISSUE TITLE
[Chrome] Crashing Chrome when visiting my.livechatinc.com

### ISSUE THREAD

**Issue by ZiggyKraus** [gorhill/uBlock#3340] opened 2017-12-12 17:16 UTC
Hi guys!

My name is Krzysztof and I work for LiveChat Inc. Recently we are being approached by our customers using both LiveChat web application (https://my.livechatinc.com/) and your uBlock Origin plugin.

When the uBlock is enabled, our https://my.livechatinc.com/chats/ (Chats is where you are automatically redirected to after login) is rendered frozen, being completely useless to our customers. Additionally, the plugin can also crash the Chrome itself and/or prevent it from closing.

I can also see that, before the Chrome and/or our web application are no longer responding, the following requests are blocked (as checked in uBlock logger):

`17:50:21		/amplitude-*.js$script	--	script	https://cloudfront.net/libs/amplitude-2.9.1-min.gz.js`

`17:50:21		googletagmanager.com/gtm.js	<<	script	https://www.googletagmanager.com/gtm.js?id=GTM-T6S3KZ`

`17:50:21		||googletagmanager.com/gtm.js?$third-party	--	script	https://www.googletagmanager.com/gtm.js?id=GTM-T6S3KZ`

`17:50:21		google-analytics.com/analytics.js	<<	script	https://www.google-analytics.com/analytics.js`

`17:50:21		||google-analytics.com^	--	script	https://www.google-analytics.com/analytics.js`

I have tried to recreate the same issue in Firefox for example but, despite the requests being blocked, everything was working fine (I will attach some additional screenshots below).

**Here are some links that will allow you to reproduce this issue**

https://my.livechatinc.com/ – link to our web app where you can log into your LiveChat account (to log in, you can create a free trial here: https://www.livechatinc.com/signup/).

**Here are some additional screenshots that I have taken for you:**

uBlock Origin logger, right after login into my LiveChat account: http://take.ms/cSljn2
And here's the screenshot that I took when the Chrome itself has crashed: http://take.ms/poRa9

**You can reproduce the issue by following the steps below:**

1. Enable uBlock Origins
2. Go to https://my.livechatinc.com/
3. Log into LiveChat with your email and password (you can create a free trial here: https://www.livechatinc.com/signup/)
4. That's it – our web application will either not load at all or the Chrome web browser will be rendered **unresponsive.** One time I was also not able to close the affected tab at all (the tab with https://my.livechatinc.com/chats/) or close Chrome itself.

**My settings represent as follows:** 

- OS/version: MacOS Sierra 10.12.4 (16E195)
- Browser/version: Google Chrome 63.0.3239.84 (Official Build) (64-bit)
- uBlock Origin version: 1.14.20

**As to the list of my filters:**

I'm using default filter lists with **no custom filters.**

Thank you in advance for checking that out!

**Comment by gorhill** [comment] 2017-12-12 17:20
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-12-12 17:20 UTC
Labels: filter issue, invalid

**Comment by gorhill** [comment] 2017-12-12 17:22
This is a filter list issue.

Also, personally I won't signup for a free trial, if you want me to look at this issue, you will need to provide a temporary account name/password which I can use to help you debug your site.

**Comment by ZiggyKraus** [comment] 2017-12-12 17:22
I know that this issue no longer applies when adding https://my.livechatinc.com/ to the list of filters but don't you think that it's not just that when the issue is non-existent when trying to reproduce it on Firefox?

**Comment by gorhill** [comment] 2017-12-12 17:23
> the issue is non-existent when trying to reproduce it on Firefox

I can't speculate about why this is the case, it could be that the code on your site mind the user agent and take different code paths according to UA.

**Comment by gorhill** [comment] 2017-12-12 17:25
Try on quick thing, disable cosmetic filtering for your site and see if this makes a difference.

**Comment by ZiggyKraus** [comment] 2017-12-12 17:27
If you'd like to recreate the issue on a test account, you can use this one:

ublockorigintest@fakeemailaddress.com.pl
test123

Also, thanks for the suggestion – I'll try disabling the cosmetic filtering in a moment.

**Comment by gorhill** [comment] 2017-12-12 17:29
The site loaded all fine for me, using default filter lists and settings. The URL where I am at is:

    https://my.livechatinc.com/install-code

**Comment by gorhill** [comment] 2017-12-12 17:32
Never mind, I was testing with the dev build of uBO.

I can reproduce with 1.14.20.

**Comment by ZiggyKraus** [comment] 2017-12-12 17:33
Unfortunately, disabling the cosmetic filtering did not help

**Comment by gorhill** [comment] 2017-12-12 17:36
Ok, this is a duplicate of #3321.

Your site removes uBO's injected `style` tag and uBO tries to re-inject its `style` tags. There is no end to this, causing the behavior you see.

Disabling cosmetic filtering for `my.livechatinc.com` works for me -- this causes uBO to not longer try to inject a `style` tag.

**Comment by ZiggyKraus** [comment] 2017-12-12 17:39
Thank you for checking that out! I will try disabling the cosmetic filtering once again and get back to you.

**Comment by gorhill** [comment] 2017-12-12 17:40
I added pic above to show how to disable cosmetic filtering.

**Comment by mapx-** [comment] 2017-12-12 17:40
or try this filter
`@@||livechatinc.com^$generichide`

**Comment by gorhill** [comment] 2017-12-12 17:41
@mapx- yes, I think we should add it at least until 1.14.22 is out and widespread.

**Comment by ZiggyKraus** [comment] 2017-12-12 17:48
Sorry for a delay.

I have once again enabled the cosmetic filtering  but this time I have restarted the browser as well. Now it is working fine.

**Comment by gorhill** [comment] 2017-12-12 17:50
Filters were added to prevent the breakage until the next version of uBO is out, force an update of _"uBlock filters -- Unbreak"_.

**Comment by ZiggyKraus** [comment] 2017-12-12 17:56
Guys, thank you very much for checking that out and adding our domain to the list of filters. Truly appreciate it!
