### ISSUE TITLE
Popup user interface - "almost empty" (regression bug) (Chromium 35)

### ISSUE THREAD

**Issue by BilBg** [gorhill/uBlock#2110] opened 2016-10-31 11:22 UTC
### Describe the issue
Elements in Popup user interface are missing
in uBlock Origin 1.9.16 & 1.9.17.0
(uBlock Origin 1.9.10 is OK)

### One or more specific URLs where the issue occurs
https://github.com/gorhill/uBlock/releases
- Any page, e.g. This page

### Screenshot in which the issue can be seen
uBlock Origin 1.9.17.0 in "normal" and "incognito":

![Image of uBlock Origin 1.9.17.0](https://s15.postimg.org/fpfq2aycb/u_Block_Origin_1_9_17_0_a.png) ![Image of uBlock Origin 1.9.17.0 incognito](https://s13.postimg.org/bv3wmqgw7/u_Block_Origin_1_9_17_0_b_incognito.png)

### Steps for anyone to reproduce the issue

1. Use Chromium 35 (on Windows XP (? may matter or not))
2. Use uBlock Origin 1.9.16 or 1.9.17.0
3. Open any page, e.g.: https://www.google.com/
4. Click uBlock Origin icon
5. Observe Popup user interface

### Your settings

- Browser/version: IronPortable 35 (Chromium 35)
- uBlock Origin version: 1.9.16 & 1.9.17.0
- OS: Windows XP

All on "Default" in uBlock Origin 1.9.17.0
In "incognito" mode only uBlock Origin 1.9.17.0 enabled (no other extensions)
(more filter lists and custom filters in uBlock Origin 1.9.16 but it seems to not matter)

**Comment by gorhill** [comment] 2016-10-31 11:27
Did you check _"Enable Experimental Javascript"_ in `about:flags`?

**Comment by BilBg** [comment] 2016-10-31 11:49
Yes, "Experimental JavaScript" is Enabled (~ month ago)

**Comment by gorhill** [comment] 2016-10-31 11:56
You need to disable it -- turns out the Set/Map implementation for experimental javascript is too different than actual ES6 Set/Map.

Duplicate of #2104.

**Closed** 2016-10-31 11:56 UTC
Labels: duplicate

**Comment by BilBg** [comment] 2016-10-31 13:40
To confirm - in the above conditions, with "Experimental JavaScript" Disabled - uBlock Origin 1.9.16 / Popup user interface is OK
