### ISSUE TITLE
uBO's dashboard does not refresh custom filters in real-time

### ISSUE THREAD

**Issue by KonoromiHimaries** [gorhill/uBlock#3704] opened 2018-04-12 04:47 UTC
### Describe the issue
 
example. i create new rule with injector
![2018-04-12-test 2](https://user-images.githubusercontent.com/5884000/38656690-714a934e-3e1c-11e8-9598-0bcf8548f4ba.png)

then i move to my filters panel and i doesn't see any change
![2018-04-12-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/38656721-b1b9fa50-3e1c-11e8-93b3-c18f9ac2b2cb.png)

i still must use refresh button or `f5` to see any change
![2018-04-12-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/38656841-62a495fa-3e1d-11e8-8ab5-06ff0995dde5.png)

### One or more specific URLs where the issue occurs
`http://docelowtestowych.cba.pl/index.php/test-2/`

### Your settings

- OS/version: win10
- Browser/version: chrome 65.0.3325.181
- uBlock Origin version: 1.15.24

**Comment by uBlock-user** [comment] 2018-04-12 05:03
By design. The real time update was never added in the first place.

**Comment by gorhill** [comment] 2018-04-12 10:47
The complication is that the user could have changes not yet applied -- so you cannot replace the current list with the modified one.

I do agree this is an issue though, I did lose filters created with the element picker in the past because of this. I think it's solvable now that uBO is equipped with a proper differ (used in the _My rules_ pane). 
Cases:

- No changes => just reload the modified list.
- Un-committed changes => use the differ to add/remove incrementally.

In all cases, as much as possible preserve scroll and cursor position.

**Comment by gwarser** [comment] 2021-07-18 07:53
Fixed.

**Closed** 2021-07-18 11:43 UTC
Labels: something to fix

**Comment by uBlock-user** [comment] 2021-07-18 12:28
Label should be changed.
