### ISSUE TITLE
uBlock on Chrome wrongly using 3p-script block for 1st-p-scripts on facebook.com

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [gorhill/uBlock#2866] opened 2017-08-13 11:43 UTC
I am seeing this issue on facebook.com. 

ublock seems to be blocking first party scripts. This doesn't seem to happen on Firefox. 

I am using Windows 8.1 32-bit and Chome 60.0.3112.90

Screenshot:
![untitled picture](https://user-images.githubusercontent.com/13736892/29249297-761317ba-804a-11e7-8065-dd33e8d52d48.png)

**Comment by gorhill** [comment] 2017-08-13 11:58
Unable to reproduce.

What version of uBlock is this?

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 12:30
Version 1.13.8.

**Comment by gorhill** [comment] 2017-08-13 12:45
I won't be able to do anything if you are not more forthcoming.

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 12:53
I understand. 

I have the default "3rd party filters" plus the "uBlock filters – Experimental" chosen. 

I also have "I am an advanced user" chosen. 

Then I have this in filters: 

![untitled picture](https://user-images.githubusercontent.com/13736892/29249797-516cd7f2-8054-11e7-9f9d-f386310f7a3a.png)

This problem occurs even if I change facebook.com local filters. 
`

**Comment by gorhill** [comment] 2017-08-13 12:58
How did you navigate to `facebook.com` in your 1st pic?

In the logger, please click in the cell with `--`, a filtering modal dialog will open. From there select "Static filtering" pane and make a screenshot of the dialog, I want to see what the value is for "which originate from".

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 13:03
Thanks. 

Attaching the screenshot. 

![untitled picture](https://user-images.githubusercontent.com/13736892/29249883-dd93abba-8055-11e7-9017-7e23179e4f28.png)

**Comment by gorhill** [comment] 2017-08-13 13:12
It says the network requests were made in the context of `local-ntp.chrome-search-scheme`, which really means from `chrome-search://local-ntp/`. Do you have an extension overriding the "New Tab" page?

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 13:31
No. Just uBlock Origin and the default extensions. 

I did experiments with Chrome Canary and this problem doesn't seem to happen there. 

You think I should try a clean uninstall-reinstall of Chrome and try again?

**Comment by gorhill** [comment] 2017-08-13 13:34
I am still trying to understand what I see in your screenshots -- so far I can't make sense of this. I will need to scrutinize the source code to find out if what I see in your screenshot can occur at all. I tried various Chrome settings, like enabling pre-fetching and I can't find a way to reproduce yet.

**Comment by gorhill** [comment] 2017-08-13 13:43
It seems your `facebook.com` page is using a service worker (`/sw?s=push`), which is not the case on my side.

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 14:32
Just this. 
![untitled picture](https://user-images.githubusercontent.com/13736892/29250504-0455e0e6-8061-11e7-8b1e-5a6074f7b9d3.png)

Yes, can see the page using service worker via development tools.

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 15:50
Or maybe because my new tab doesn't have Apps but has pages visited the most. Which has Facebook and which also uses the service worker and is also a search page?

This is what it looks like: 

![untitled picture 1](https://user-images.githubusercontent.com/13736892/29251102-10c6ba1a-806d-11e7-8f9f-43b5cddb076c.png)

![untitled picture 2](https://user-images.githubusercontent.com/13736892/29251103-1495cdac-806d-11e7-8945-e6e8d94b2700.png)

Which also contains that "local-ntp"

**Comment by vijayaraghavanramanan** [comment] 2017-08-13 15:52
On Chrome Canary on the other hand, the new tab is called different, as you can see from the top of the screenshot: 

![untitled picture](https://user-images.githubusercontent.com/13736892/29251124-7df99418-806d-11e7-8dff-12f97763d849.png)

And I don't face this issue on Canary.

**Comment by gorhill** [comment] 2019-07-25 12:54
Closing as obsolete.

**Closed by gorhill** 2019-07-25 12:54 UTC
Labels: unable to reproduce
