### ISSUE TITLE
uBlock interferes with DeviantArt Notification Cards

### ISSUE THREAD

**Issue by zauberparacelsus** [gorhill/uBlock#2012] opened 2016-09-21 00:17 UTC
### Describe the issue

On DeviantArt's notifications page, uBlock has for quite some time been interfering with the notification cards for DeviantArt, preventing you from clicking on the two buttons in the top corner.  When this happens, only the first four cards are affected.  Usually, a forced page refresh will correct the issue, but not always.  The issue occurs on both Windows 8 and Ubuntu 16.04, but a forced page refresh will not correct the issue on Windows 8.
### One or more specific URLs where the issue occurs

http://www.deviantart.com/notifications/
### Steps for anyone to reproduce the issue
1. Register an account at DeviantArt and follow a bunch of artists or groups.  Skip this step if you already have a DeviantArt account.
2. Bring up the notifications page, and then try to click the two buttons on the top right.
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
- Browser/version: Chrome 52.0.2743.116, built for 64bit Ubuntu 16.04
- uBlock Origin version: 1.9.4
##### Your filter lists

Default filter lists
##### Your custom filters (if any)

None

**Comment by gorhill** [comment] 2016-09-21 03:18
Did you rule out a filter list issue?

**Comment by zauberparacelsus** [comment] 2016-09-21 03:38
The issue occurs inconsistently, and unfortunately this makes it difficult to impossible to test.  When I tried testing it just now, it worked correctly when I tried doing the control test.

**Comment by gorhill** [comment] 2016-09-21 03:49
Ok I will look into this.

**Comment by GuardianMajor** [comment] 2016-10-13 05:16
I can tell you what the problem is. I use dA extensively and I am going to assume from your problem that you have the free account (meaning not the dumb CORE membership) right?

There are several elements they use to shove ads in your face. The rules that block them leave these containers behind that are randomly placed on the screen, so at any given time it blocks a different part.

These containers can be eliminated by using cosmetic filtering, this is how I am getting rid of this annoyance, hope it helps you:

`www.deviantart.com##div.mc-ad-chrome`

Put this under your filters, and your problem will go away. In the future, something like this happen, keep this in mind. So use inspect item to click on the area that "won't" let you click, and then inspect the DOM, guaranteed you will see the shadow the invisible item that is blocking your clicks.

Good luck.

**Comment by gorhill** [comment] 2017-03-22 13:06
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-03-22 13:06 UTC
Labels: filter list issue, invalid
