### ISSUE TITLE
Uncaught TypeError: Cannot read property 'messaging' of null

### ISSUE THREAD

**Issue by limonte** [gorhill/uBlock#1315] opened 2016-01-29 12:34 UTC
![wywmeov](https://cloud.githubusercontent.com/assets/6059356/12675789/0ac06a94-c68d-11e5-83f1-16fc5d16810c.png)

**Comment by gorhill** [comment] 2016-01-29 14:06
You restarted uBO?

**Comment by limonte** [comment] 2016-01-29 14:26
@gorhill after uBlock reinstallation and Chrome restart, this bug is gone. Have no idea what was the reasin, but anyway tnx for support!

**Comment by gorhill** [comment] 2016-01-29 14:33
This can happen when uBO is restarted while its content scripts were already injected in web pages -- these web pages can report such errors until they are themselves reloaded. Restarting uBO in the middle of a session is a rather rare occurrence, but ideally the error should not happen, I haven't dug further to find exactly why it happens -- the content scripts are supposed to flush themselves out when they lose contact with uBO's main process.

I will re-open to remind me to look further into this.

**Comment by Christoph-Wagner** [comment] 2016-12-08 09:07
I keep getting this error on every site. Uninstalling and reinstalling uBlock doesn't help, resetting to default doesn't help. 

Latest Chrome version (but happens with everyone I used for many months), both 32 and 64bit. Windows 10 x64.   
uMatrix is also installed.

Error in vapi-client.js:142

    this.channels[channelName] = {
            channelName: channelName,
            listener: typeof callback === 'function' ? callback : null,
            send: function(message, callback) {
                if ( vAPI.messaging.port === null ) { // The error happens here

**Comment by TrejGun** [comment] 2017-01-29 06:12
same here
https://github.com/gorhill/uMatrix/issues/701

**Comment by gorhill** [comment] 2017-02-09 13:31
Duplicate of #701.

**Closed by gorhill** 2017-02-09 13:31 UTC
