### ISSUE TITLE
Initial Firefox load not using uBlock

### ISSUE THREAD

**Issue by MegaManSec** [gorhill/uBlock#3258] opened 2017-11-21 15:44 UTC
I'm not sure whether this is a ublock issue or a firefox issue, but I thought I'd report it here.
I am using Firefox 58 with "When Firefox starts: show your windows and tabs from last time" enabled, on FreeBSD 12 -CURRENT.

If I have, say, https://www.reddit.com/r/news/ open in my browser, and restart firefox, it loads the reddit page as intended; however, ads appear on the page. Reloading the page gets rid of the ads, as expected. One would expect the ads not to be there when the browser starts.

**Comment by gorhill** [comment] 2017-11-21 16:05
Duplicate of #1327.

**Closed by gorhill** 2017-11-21 16:05 UTC
Labels: duplicate
