### ISSUE TITLE
[Bug] Clicking on github link in the dasboard opens in the frame and not in a new tab.

### ISSUE THREAD

**Issue by typhoon71** [gorhill/uBlock#600] opened 2015-08-15 13:01 UTC
Clicking on github link in the dasboard opens in the frame and not in a new tab.
Last ublock origin 1.1.0.0b2 and firefox 40.0.2

**Comment by typhoon71** [comment] 2015-08-15 13:04
nevermind.

**Comment by gorhill** [comment] 2015-08-15 13:07
> I now get a popup when I go on any github page.

How do you navigate to GitHub? This warning occurs because you are trying to open a GitHub page from within a frame object, which GitHub forbids through the use of a [`X-Frame-Options` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options), hence the warning.

**Comment by typhoon71** [comment] 2015-08-15 13:07
sorry, I was fixing the post

**Comment by gorhill** [comment] 2015-08-15 13:08
Ok, no problem.

**Comment by typhoon71** [comment] 2015-08-15 13:08
Shouldn't new pages get opened in new tabs since it's the browser default?

**Comment by gorhill** [comment] 2015-08-15 13:09
Yes, this was fixed in #599.

**Comment by gorhill** [comment] 2015-08-15 13:10
Actually, I should ask, which link in the dashboard caused the issue on your side?

**Comment by typhoon71** [comment] 2015-08-15 13:11
so the dev build on mozilla is outdated already?

**Comment by typhoon71** [comment] 2015-08-15 13:12
link causing it was the github one: "https://github.com/gorhill/uBlock/graphs/contributors"

**Comment by gorhill** [comment] 2015-08-15 13:13
> the dev build on mozilla is outdated already?

Yes, but I can't update it for every single change I make, I try to update when its worth it.

**Comment by typhoon71** [comment] 2015-08-15 13:15
OK, I got it.

**Comment by gorhill** [comment] 2015-08-15 13:17
Duh... I looked deeper into this, and all was working fine before, and I should have looked more carefully at the original issue, which is actually a regression bug -- the fix to #599 was not the proper one.

**Comment by typhoon71** [comment] 2015-08-15 13:19
well, at least it wasn't lost time now, too bad it is a regression.

**Comment by typhoon71** [comment] 2015-08-15 17:34
It does indeed fix the one I knew of. Well done. 
Already avail on AMO. You are fast!

**Closed** 2015-08-17 21:31 UTC
