### ISSUE TITLE
Popups closing behaviour in Firefox

### ISSUE THREAD

**Issue by mowanotm** [gorhill/uBlock#2040] opened 2016-10-01 10:00 UTC
Issue: In multi-tabs browsing, triggering popups blocking will jump to another tabs.
Details: There are two factors in the situation, how Firefox open new tab (popup), as an immediate right tab or a rightmost tab. And which tab Firefox will display after tab closing, the immediate left tab or the last viewing tab. In situation where Firefox was configured to open new tab as rightmost and display the immediate left tab upon closing, triggering popups blocking in any non-rightmost tabs will jump to the rightmost tab.

**Comment by gorhill** [comment] 2016-10-01 11:15
Duplicate of #1924.

**Closed by gorhill** 2016-10-01 11:15 UTC
