### ISSUE TITLE
[BUG] Conflict with ScriptSafe

### ISSUE THREAD

**Issue by Enigma0** [gorhill/uBlock#1707] opened 2016-06-10 18:02 UTC
### Describe the issue

See screenshot - it's all the info I have.

### One or more specific URLs where the issue occurs

I honestly have no idea but I see it all the time so probably most sites.

### Screenshot in which the issue can be seen

https://imgur.com/gWyK3Uh

### Steps for anyone to reproduce the issue

1. Install ScriptSafe: https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf?hl=en
2. Visit sites until you get the exception (I don't know what triggers it)

### Your settings

- Browser/version: Chrome latest stable [Windows]
- uBlock Origin version: latest

##### Your filter lists

Default

**Comment by gorhill** [comment] 2016-06-10 18:22
Duplicate of #1170.

**Closed by gorhill** 2016-06-10 18:22 UTC
