### ISSUE TITLE
Image sliders not working after enabled this extension!

### ISSUE THREAD

**Issue by prkeshri** [gorhill/uBlock#1664] opened 2016-05-27 12:08 UTC
Hello, I have installed this extension (as unpacked after downloading from Pre-release 1.7.5b2 : https://github.com/gorhill/uBlock/releases/tag/1.7.5b2). The problem is that once you visit any of the below urls, after the 1st click on '>' (Next) button, the slider moves one step forward, but then, it hangs! i.e. You cannot navigate either forwards or even backwards. Tdoes not work while the 

URLs where the issue occurs:
[http://bollywood.bhaskar.com/news-bf4/ENT-BOL-most-popular-son-in-law-of-famous-bollywood-families-5332236-PHO.html](http://bollywood.bhaskar.com/news-bf4/ENT-BOL-most-popular-son-in-law-of-famous-bollywood-families-5332236-PHO.html)

For other urls, goto [http://bollywood.bhaskar.com/](http://bollywood.bhaskar.com/) and click on any link.

### Screenshot in which the issue can be seen

![bhaskar-ublock-issue](https://cloud.githubusercontent.com/assets/6885298/15607538/4adbc162-2431-11e6-86f6-137951ae93ef.png)

### Steps for anyone to reproduce the issue

1. Open chrome.
2. Goto the specified url.
3. Wait for page Load.
4. Click on the '>' next button (On the slider).
5. Click again on the '>' next button.

When inspected using the chrome console, the following error occurs:
The page tries to load from 'http://js-agent.newrelic.com/nr-686.min.js' which gets blocked by the extension, so an exception gets raised.

I think the slider must have saved some settings in order to avoid multiple user clicks while the image is being slided. Since the slider functionality could not get resumed, the settings to allow the user again to navigate forward also could not get executed. Also, as a result, the move back button ('<') does not get enabled after the 1st sliding!

### Your settings

Default Settings.

- Browser/version: Google Chrome  43.0.2357.81
- uBlock Origin version: Prerelease 1.7.5b2.

**Comment by gorhill** [comment] 2016-05-27 12:58
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed** 2016-05-27 12:58 UTC
Labels: filter list issue

**Comment by gorhill** [comment] 2016-05-27 13:08
Report to EasyPrivacy maintainers please: <https://forums.lanik.us/viewforum.php?f=64> -- this is a filter list issue, not a uBO issue. The issue is the filter `||googletagmanager.com/gtm.js?$third-party` in EasyPrivacy causes the slideshow to break (report this detail to EasyPrivacy maintainers).
