### ISSUE TITLE
Redirection Error of data:application/javascript;base64

### ISSUE THREAD

**Issue by Nyquis** [gorhill/uBlock#3105] opened 2017-10-07 12:38 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

There seems to be in incompatibility recently between uBlock origin and Privacy badger that generates consistently an Error. It seems like some of the redirection is not working correctly

### One or more specific URLs where the issue occurs

https://forum.xda-developers.com

### Screenshot in which the issue can be seen

Here is an example of the generated Error.

[https://imgur.com/a/shNnl](Imgur link)

### Steps for anyone to reproduce the issue

1. Currently just normaly browsing will introduce this issue randomly at certain sites. It seems like there is some overlapping towards some redirected elements.

### Your settings

- I am advanced user checked.

- OS/version: Windows 8.1
- Browser/version: Google Chrome 61.0.3163.100
- uBlock Origin version:  1.14.8

##### Your filter lists

Default filter list + dynamic filtering + DEU + FRA + Fannboys annoyance list

**Comment by gwarser** [comment] 2017-10-07 13:09
A duplicate of countless issues
https://github.com/gorhill/uBlock/search?q=This+extension+failed+to+redirect+a+network+request&type=Issues&utf8=%E2%9C%93

https://github.com/gorhill/uBlock/issues/1170

**Closed** 2017-10-07 13:19 UTC
Labels: duplicate, invalid
