### ISSUE TITLE
network requests being re-addressed

### ISSUE THREAD

**Issue by ferrvittorio** [gorhill/uBlock#1336] opened 2016-02-03 08:26 UTC
On Chrome, network requests of extension Ghostery are being readdressed by Ublock

**Comment by gwarser** [comment] 2016-02-03 09:13
Like this https://github.com/gorhill/uBlock/issues/1170 ?

**Comment by ferrvittorio** [comment] 2016-02-03 11:35
Yes, but not in Polish.

--
Vittorio Ferrando
Il 03/feb/2016 10:14, "gwarser" <notifications@github.com> ha scritto:

**Comment by gorhill** [comment] 2016-02-03 12:37
Duplicate of #1170.

**Closed by gorhill** 2016-02-03 12:37 UTC
