### ISSUE TITLE
How do I make Ublock use Fanboy's site not Easylist.to?

### ISSUE THREAD

**Issue by thinkpad4** [gorhill/uBlock#3537] opened 2018-02-22 01:34 UTC
### Describe the issue
I wanna use the easylist at fanboy.co.nz NOT the one at easylist.to but when I uncheck the built in easylist listing and add the fanboy one to custom lists it rechecks the builtin one.  I want it to ONLY pull from fanboy.co.nz and not to ever pull from easylist.to, how can I make this happen?  Thanks

### Your settings

- OS/version: 
- Browser/version: 
- uBlock Origin version:

**Comment by LimboSlam** [comment] 2018-02-22 06:26
:)

**Comment by gorhill** [comment] 2018-02-22 11:40
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by jspenguin2017** [comment] 2018-02-22 16:08
It's hard coded into `assets.json`, so it's currently not possible. You'll have to fork.

**Comment by thinkpad4** [comment] 2018-02-23 04:23
@jspenguin2017 Is it possible to edit that file for personal use?  If so how?  Thanks.

**Comment by jspenguin2017** [comment] 2018-02-23 05:25
You can either fork and build yourself or download and patch a pre-build. 

To build yourself, you need Git and Python3. Although the build scripts says you need a Linux distro, they do work on Windows with Ubuntu, you can download it here: https://www.microsoft.com/store/productId/9NBLGGH4MSV6
Note that the Windows version of Ubuntu might not come with Python3. 
Use Git to close the required repos, make necessary change and build with build scripts. 

If you want the easy route, just download a build that you like from https://github.com/gorhill/uBlock/releases and change the file.

**Comment by thinkpad4** [comment] 2018-02-23 06:52
Thanks

**Comment by ryanbr** [comment] 2018-02-23 08:06
Not sure why its closed so quickly, but I use [Cloudflare CDN](https://www.cloudflare.com/network/) mirrors to make it faster/more reliable to supply the user with the selected lists.

Clearly a bug, especially if its hardcoded.

**Comment by Ravizz** [comment] 2018-02-23 08:32
> @ryanbr : Not sure why its closed so quickly

Because the author didn't provde all the required info like:

> 
>     OS/version:
>     Browser/version:
>     uBlock Origin version:

That's why @gorhill closed it, and as for your issue I've not meant to close your issue as a duplicate, I've just put info about https://github.com/gorhill/uBlock/issues/3537 for informational purposes only, I would like to keep your issue open, as https://github.com/gorhill/uBlock/issues/3537 is closed as invalid, and I also would like to @gorhill explain also some issues I've been talking about :  https://github.com/gorhill/uBlock/issues/3540#issuecomment-367935403. Can You reopen your issue please?

**Comment by ryanbr** [comment] 2018-02-23 08:38
Okay, I've made a quick and dirty fix on my side. It should now work.

**Comment by gorhill** [comment] 2018-02-23 11:12
> Not sure why its closed so quickly

When I see missing basic information and clear steps to reproduce, I will spend less time on a reported issue -- and in the current case I concluded the user merely had to import the list. But as @jspenguin2017 pointed out, that didn't work because the URL is already used in a stock list.

The solution is to add a dummy query at the end of the URL:

    https://secure.fanboy.co.nz/easylist.txt?a=0

**Closed by gorhill** 2018-02-23 11:12 UTC

**Comment by Ravizz** [comment] 2018-02-23 12:33
Ok, and what about (3_): https://github.com/gorhill/uBlock/issues/3540#issuecomment-367935403

**Comment by jspenguin2017** [comment] 2018-02-23 15:31
@Ravizz If you are side loading my resource file, then it will fire an XHR every time you touch the dashboard.

**Comment by Ravizz** [comment] 2018-02-23 16:46
@jspenguin2017 : In the nano resources it says: `# Expires: 2 days` I didn't know that the resources are fetched also additionally by uBO, at some actions, and I don't know why, since the resource list is just like filter list, why to fetch it additionaly at actions, perhaps there are some reasons?

**Comment by jspenguin2017** [comment] 2018-02-23 16:59
That expires header is not parsed. 
The user resources is mostly intended for debugging, so it is updated on every action, but the new code undoes that, which is kind of weird.

**Comment by Ravizz** [comment] 2018-02-23 19:32
Debug options should be switchable on/off (and by default at off), because most of the users don't need to debug uBO all the time / fetch the resources additionaly at acitons, just like the logger is mainly  for debugging/testing purposes, so it is switchable on/off and by default at off. So for me it was a bit odd to leave debugging options enabled for end-users, which doesn't mean that debug options should be removed, because developers (like you) still might need it so I understand it might be weird for you.

**Comment by thinkpad4** [comment] 2018-02-23 21:19
Thank you @gorhill that worked perfect, sorry about filling out the issue form wrong
