### ISSUE TITLE
Info panel broken on Firefox Android

### ISSUE THREAD

**Issue by neroux** [gorhill/uBlock#2400] opened 2017-02-21 09:35 UTC
### Describe the issue

_I cannot say with absolute certainty that it is a uBlock issue and not possibly rather a general Firefox one on Android but here it goes ...._

Upon opening uBlock's application/configuration panel after a fresh start of Firefox the two configuration buttons are not displayed, only a manual disabling and re-enabling will display them again.

### Screenshot in which the issue can be seen

![image](https://cloud.githubusercontent.com/assets/24754773/23158900/13ef122a-f821-11e6-9202-6ac4c0150a1a.png)

### Steps for anyone to reproduce the issue

* Start Firefox on Android from scratch (after a reboot or after exiting it - not simply reopening it)
* Open the application menu and choose Tools - Add-ons
* Open the info/config panel of uBlock

Now the two buttons for the dashboard and the logger are not displayed. To get them displayed again it is necessary to disable and re-enable the extension.

### Your settings

Most recently verified with Firefox 52b on Android with uBlock 1.11.0 but the issue dates back a long time  and most likely shows up on Firefox 51 as well.

**Comment by gorhill** [comment] 2017-02-21 12:27
Duplicate of #1379.

Please search existing issues before opeing a new one.

**Closed by gorhill** 2017-02-21 12:27 UTC
