### ISSUE TITLE
Cannot update/install Firefox uBlock Origin v.1.6.2 through addons.mozilla.org

### ISSUE THREAD

**Issue by Jadelor** [gorhill/uBlock#1414] opened 2016-02-22 22:29 UTC
### Describe the issue
uBlock Origin extension 1.6.2 won't install (or update from earlier) on Mozilla's Firefox addon repo (addons.mozilla.org). Possibly signed wrong.

### One or more specific URLs where the issue occurs
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

### Screenshot in which the issue can be seen
![2016-02-23_00-24-07](https://cloud.githubusercontent.com/assets/3034619/13234983/35aa75a2-d9c4-11e5-94ad-40e9bebd9586.png)

### Steps for anyone to reproduce the issue
1. Attempt install/update
2. Fail said install/update

### Your settings
- Browser/version: Firefox 44.0.2/win32
- uBlock Origin version: n/a

**Comment by gwarser** [comment] 2016-02-22 22:51
https://github.com/gorhill/uBlock/issues/1413

**Comment by gorhill** [comment] 2016-02-22 23:02
Duplicate of #1373.

**Closed by gorhill** 2016-02-22 23:02 UTC

**Comment by gorhill** [comment] 2016-02-23 13:14
_Maybe_ related bugzilla entry: https://bugzilla.mozilla.org/show_bug.cgi?id=1249402#c2
