### ISSUE TITLE
Speedometer benchmark score reduced by uBO

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#2831] opened 2017-07-29 19:29 UTC
Benchmark is at ...  http://browserbench.org/Speedometer/
Running Fx 56 64 bit Nightly on Windows 10 Pro 64 bit with all updates.
My setting are attached.

With all my add-ons disabled I get a score of 97.1.  When only uBO is enabled my score is 69, a drop of about 28%.  If I disable uBO only for the benchmark site the score is not affected at all.  I'm concerned that it isn't just the benchmark being affected but potentially all pages.

[my-ublock-backup_2017-07-29_15.22.13.txt](https://github.com/gorhill/uBlock/files/1185173/my-ublock-backup_2017-07-29_15.22.13.txt)

There is a bug report about Speedometer located at https://bugzilla.mozilla.org/show_bug.cgi?id=1245279

**Comment by gwarser** [comment] 2017-07-29 20:11
https://github.com/gorhill/uBlock/issues/2552#issuecomment-296267008

**Comment by gorhill** [comment] 2017-07-29 20:57
Duplicate of #2552.

**Closed by gorhill** 2017-07-29 20:57 UTC
