### ISSUE TITLE
zapper and picker mode dont work on firefox 55/56

### ISSUE THREAD

**Issue by f4grx** [gorhill/uBlock#3090] opened 2017-10-04 10:12 UTC
### Describe the issue

When selecting the zapper or the picker in the ublock window, the current page become unresponsive

### One or more specific URLs where the issue occurs

This happens with any web page.

### Screenshot in which the issue can be seen

The page display is unaffected, it does not become dark, no element can be selected, the element selection window does not show, and no hyperlink can be clicked. Page reloading is required to get back to normal.

### Steps for anyone to reproduce the issue

1. install ublock origin
2. click on the ublock origin red icon
3. select picker or zapper mode, the display does not change
4. click anywhere in the page, nothing happens, links are not clickable anymore

Note: ublock origin still works since some URLs are reported blocked.

### Your settings

- OS/version: windows 10 64-bit
- OS/version: linux mint 18.2 64-bit also has the same problem
- Browser/version: Firefox 56.0 64 bits
- Browser/version: Firefox 55.0.3 32 bits (same behaviour as Fx 56)
- uBlock Origin version: v1.14.11rc10 (last release has the same problem)

- ublock origin settings are unchanged from defaults

##### Your filter lists

Unchanged default selections

##### Your custom filters (if any)

None

**Comment by gorhill** [comment] 2017-10-04 12:12
Unable to reproduce. You will have to investigate on your side. Given that such a basic feature has not been reported as broken for anyone else, marking as invalid unless you make the case the issue is with uBO. Try with a blank profile -- as repeatedly noted, legacy extensions can interfere negatively. Also, mind your custom settings in Firefox, it goes without saying that I expect that a blank profile must be tried when making the case there is an issue with uBO itself..

**Comment by f4grx** [comment] 2017-10-04 14:12
Okay... ublock origin is incompatible with "Make Trump tweets eight again"

:(

Probably because this extension messes with the DOM.

Thanks for the debugging ideas. Do you have a list of imcompatible extensions?

**Comment by gorhill** [comment] 2017-10-04 14:44
Thanks for investigating and narrowing the issue.

Both uBO and "Make Trump tweets eight again" assign a listener to uBO's `onload` property, this is what is causing the issue, the other extension is overwritting uBO's own `onload` handler. I will fix by using `addEventListener('load', ...)` instead. The other extension should do the same thing.

Since uBO "owns" the element picker `iframe`, I am guessing it's the reason it was using directly `onload` property. However since the DOM is shared between all extensions (and the web page), using `addEventListener` is the correct way to assign a handler to any event.

**Comment by f4grx** [comment] 2017-10-04 14:59
LOL, I guess it wont be easy to contact the developers of this (absolutely essential) extension
http://maketrumptweetseightagain.com/

**Closed** 2017-10-04 15:15 UTC

**Comment by f4grx** [comment] 2017-10-04 15:18
Excellent, thanks. When will that be available for installation?
