### ISSUE TITLE
1.13.10 does not execute Javascript

### ISSUE THREAD

**Issue by VersloB** [gorhill/uBlock#2915] opened 2017-08-29 12:37 UTC
1.13.10 does not execute Javascript on a bank website. 

Logon and verification is fine, but resulting page is then populated non-functional links. This appears to be a uBlock version issue. Tested on the same box with 2 separate Firefox profiles.

https://ib.swedbank.lt/private

Once logged on, the following script does not function using v1.13.10
javascript:navigateTo('private.d2d.accounts.accountStatement','account','10134714764','send','action')
uBlock icon is 'greyed out' 
'Inspect Element' produces a blank box
Disable Ublock v1.13.10 ~ no issue ~ script executes.

Same logon and script using uBlock v1.13.8 functions just fine ~ uBlock enabled or disabled.
Installed uBlock v1.13.8 on the defective profile and all is well.
Updates disabled until resolution.

Win7 Pro X 64
Firefox v54.0.1
uBlock v1.13.10

**Comment by gorhill** [comment] 2017-08-29 13:00
Duplicate of #2909. Search existing issues before opening a new one please.

**Closed by gorhill** 2017-08-29 13:00 UTC
Labels: duplicate
