### ISSUE TITLE
[Nightly]"Block Element" is missing, uBO icon is grey after dragging a tab from one window to the other

### ISSUE THREAD

**Issue by SXZ1** [gorhill/uBlock#2437] opened 2017-03-09 06:34 UTC
Hello!
"Block Element" in rmb menu is missing, uBO icon is grey after dragging a tab from one window to the other. Nightly 08-03-17, uBO 1.11.3b0 (latest beta). Default settings everywhere. STR:
Launch Nightly, open new window, go to https://github.com. Icon is red, click on rmb - "Block Element" is there. Now drag github tab to the first window. Icon turned grey, click on rmb - "Block Element" is gone. 

Screenshot:
![example_screenshot](https://cloud.githubusercontent.com/assets/26294581/23738691/8ced1078-04ab-11e7-8319-f748d732ff66.png)

Also, I don't know if it's a bug or not: open any image in a new tab, for example: https://www.google.ru/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png
Click on it with rmb - Block Element. Nothing happens. Nightly 07-03-17, uBlock 1.11.3b0
I tried to google but didn't find anything.

**Comment by ripdog** [comment] 2017-05-02 05:26
Does anything appear in the browser console after dragging the tab? Ctrl+Shift+J

**Comment by SXZ1** [comment] 2017-05-02 08:44
As far as I can tell, nothing related to uBlock:
![image](https://cloud.githubusercontent.com/assets/26294581/25610643/b6c2a02e-2f2c-11e7-865e-ee5772b3c76d.png)

**Comment by gorhill** [comment] 2017-05-02 10:05
Duplicate of #1120.

**Comment by gorhill** [comment] 2017-05-02 10:09
Actually, not a duplicate, as I can reproduce #1120, but I cannot reproduce this one here.

**Comment by gorhill** [comment] 2017-05-02 10:14
> Also, I don't know if it's a bug or not: open any image in a new tab

By design, the content type for the document cannot be an image or plain text. See #1124.

**Comment by gorhill** [comment] 2018-07-22 12:39
Unable to reproduce in latest Firefox stable.

**Closed by gorhill** 2018-07-22 12:39 UTC
Labels: unable to reproduce
