### ISSUE TITLE
Since two days, Youtube video stopped working on Facebook

### ISSUE THREAD

**Issue by onigetoc** [gorhill/uBlock#1926] opened 2016-08-22 13:27 UTC
Since two days, Youtube video stopped working on Facebook.

I stopped U-Block and Youtube videos worked again.

**Comment by lewisje** [comment] 2016-08-22 14:55
Please check the logger to see what is getting blocked when you try to watch YouTube videos on Facebook.

**Comment by onigetoc** [comment] 2016-08-22 15:09
I just saw this in my Google inspector Console.
With U-block or not.
We can't share image anymore here???

STOP.
Il s’agit d’une fonctionnalité de navigateur conçue pour les développeurs. Si vous avez été invité(e) à copier-coller quelque chose ici pour activer une fonctionnalité ou pirater le compte d’un tiers, c’est une escroquerie et cela donnera accès à votre compte Facebook.

Voir https://www.facebook.com/selfxss pour plus d’informations

**Comment by lewisje** [comment] 2016-08-22 15:39
You should be able to upload screenshots to Imgur and then post them here, but anyway, that's a standard message from Facebook against opening the console to paste code in from untrusted sources, because there are bad actors who ask people to do that so they can take over their accounts.

Anyway, I was saying you should check the uBlock Origin logger, which is not the same as the browser console: https://github.com/gorhill/uBlock/wiki/The-logger

**Comment by onigetoc** [comment] 2016-08-22 15:50
Hi, finally, i think i had a virus and find a way with a software to get rid of it with a Facebook Software or a software recommended by them with a scan.

**Comment by gorhill** [comment] 2016-08-22 21:36
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-08-22 21:36 UTC
Labels: invalid

**Comment by lewisje** [comment] 2016-08-24 02:00
Okay, I just reproduced this; it happens because of the following two rules in EasyPrivacy:

* `/referer_frame.`
* `||pixel.facebook.com^`
