### ISSUE TITLE
Sort "My Rules" by domains

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uBlock#571] opened 2015-08-06 01:25 UTC
From

```
test.google.com
test.youtube.com
www.google.com
www.youtube.com
```

to

```
test.google.com
www.google.com
test.youtube.com
www.youtube.com
```

**Comment by 5t3f4n** [comment] 2015-08-06 13:53
Dupe of #514 ?
Your own issue even…

**Comment by vzjrz** [comment] 2015-08-12 19:36
Or how about allowing My Rules to be editable like My Filters so that we could add comments and manually sort similar rules together for better readability.

**Comment by gorhill** [comment] 2018-05-02 12:39
I no longer consider to be needed given that rules can now be filtered out with keywords since 6871d9aed432.

**Closed by gorhill** 2018-05-02 12:39 UTC
