### ISSUE TITLE
Safari Plugin?

### ISSUE THREAD

**Issue by ChrisChiera** [gorhill/uBlock#782] opened 2015-10-04 19:15 UTC
Most left AdBlock Plus for AdBlock because of ADP bad business practices. Now it seems AdBlock has been bought by ADP, meaning many will switch to UBlock. However, then they have to decide between UBlock or UBlock Origin. From quick researching Origin appears to be the better option however UBlock Origin doesn't have a Safari extension. 

Will this be available soon? As many may end up going to UBlock (not origin) Safari extension not realizing it's a different company, especially now that El Capitan is out which major improvements to Safari.

**Comment by zonetuke** [comment] 2015-10-04 19:46
I would like to know if a Safari  browser plug-in for iOS9 will be developed?

**Comment by publicarray** [comment] 2015-10-05 06:24
Duplicate of https://github.com/gorhill/uBlock/issues/64

**Comment by gorhill** [comment] 2015-10-05 12:54
> Anyone is welcome fork and make a PR to add safari support (if this is ok with @gorhill)

For a Safari version, this time I would prefer a fork which pulls code from here (pull requests *if and only if* unavoidable). If this happens, I would be happy to link to that fork for installation -- in retrospect it should have been better if done this way originally.

Closing as duplicate of #64.

**Closed by gorhill** 2015-10-05 12:54 UTC
Labels: duplicate

**Comment by Zearin** [comment] 2015-11-06 15:05
:+1:
