### ISSUE TITLE
uBO  1.14.0 &  1.13.11rc2 causing severe lag, page loading time increased

### ISSUE THREAD

**Issue by hapibukipa** [gorhill/uBlock#2934] opened 2017-08-30 16:11 UTC
1.13.11rc2 & 1.14.0
Guessing the issue is this

https://github.com/gorhill/uBlock/issues/2925

Switched to a new filter storage & after migration uBo performance took a severe hit.

Created a new profile and started fresh,
Page take a lot longer to load upto 5x, opening 3-4tabs the loading of these pages take a very very long time.
if i open two tabs with bugzilla & cnn.com
typing in bugzilla is lagging and page scroll "janks"
At random if i open ublock dash board Firefox says a page might be slowing it down.

Have only easylist & easyprivacy as filters.
rest of the settings of uBo & Firefox 57 are defaults.

Reverting to previous version fixes all the above issues.

Windows 10 RS2 Firefox 57

**Comment by gorhill** [comment] 2017-08-30 16:14
Please don't guess.

Use the [Gecko profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) and profile the launching of uBO.

All worked fine here, and launch time have been markedly improved with indexedDB -- thus marking as unreproducable. Whoever feels like adding something here, do it with something relevant only, and profiling data for uBO launch time is what is relevant.

**Comment by hapibukipa** [comment] 2017-08-30 16:19
okay didn't know about it,
so profiling it with loading a few tabs and attaching here.
And the guess was that uBo was the problem.

**Comment by gorhill** [comment] 2017-08-30 16:21
Here is what it looks on my side -- that is the result of enabling/disabling uBO three times:

![a](https://user-images.githubusercontent.com/585534/29883200-7e069754-8d7d-11e7-8230-95e6028d74b7.png)

Keep in mind this is the result of **three** launch of uBO, so it's quite fast clearly.

Now I have to ask: why didn't you rush to test this in the dev build yesterday when I asked for feedback?

**Comment by hapibukipa** [comment] 2017-08-30 16:33
@gorhill

New to this

http://bit.ly/2wiIAWS

Started it as soon as Firefox started,
Then started loading pages,
The whole time pages were loading.
Doing one more .

**Comment by hapibukipa** [comment] 2017-08-30 16:40
http://bit.ly/2wixEs9

Enabled uBo and opened 3 tabs,
look at the slowdowns.

**Comment by hapibukipa** [comment] 2017-08-30 16:44
If you want can do one with Rc0 which works fine BTW
And this profiling idk so if you want me to do something to your liking just ask.

**Comment by gorhill** [comment] 2017-08-30 17:00
uBO launch time looks fine to me, I see ~540 ms, which is expected. Keep in mind you are running uBO out-of-process:

![a](https://user-images.githubusercontent.com/585534/29884396-5f00b11a-8d81-11e7-8d7a-216c5bd03e33.png)

In your second profiling results, uBO is doing even better, ~210 ms load time:

![a](https://user-images.githubusercontent.com/585534/29884553-e1ed6316-8d81-11e7-9b45-16ee9dd61237.png)

Note that I isolate uBO's CPU contribution by filtering using `moz-`, because webext extensions reside in `moz-extension://`. It does not seem you have other webext installed, so I am attributing all the CPU samples to uBO, and the stack trace matches this anyways.

I have no clue was is causing your slowdown in there, there are no debug symbols in your profiling data, I suggest you report to Firefox devs.

**Comment by crssi** [comment] 2017-08-30 17:00
I can see the same symptoms and when FF is launched it is "frozen" for about 5 to 10 seconds.

**Comment by gorhill** [comment] 2017-08-30 17:16
This is with 1.13.10, .i.e. using the webext storage only, in which I get ~1750 ms for three enable/disable, i.e. roughly 583 ms per launch:

![a](https://user-images.githubusercontent.com/585534/29885419-c7740bfe-8d84-11e7-9358-f9623a110acc.png)

So aside Firefox devs suggesting that indexedDB should be used for large chunks of data, the profiling of 1.13.10 confirms this.

Again, please just report to Firefox devs, I can't reproduce your issue, and if there is an issue on your side, this is outside uBO realm, I just followed the recommendations of Firefox devs, and the profiling I get confirm this was the right thing to do. Your issue need to be looked into by Firefox devs.

**Comment by hapibukipa** [comment] 2017-08-30 17:17
@gorhill 

> no debug symbols in your profiling data

How do i do that?

Okay profiling with old uBo
see if you can see the difference?

The problem is mainly "Page loading slow downs"
Not the starting of uBo etc

**Comment by gorhill** [comment] 2017-08-30 17:20
> How do i do that?

I don't know, I have none either.

It's up to Firefox devs to accept your profiling data or not. I have seen a case on bugzilla where it seemed to me like the Activity Streamer was causing performance issue, but the Mozilla person didn't pick this and rather just pointed out that the symbols were missing.

**Comment by gorhill** [comment] 2017-08-30 17:22
> The problem is mainly "Page loading slow downs"
> Not the starting of uBo etc

Ok, let me look again then. Just understand that the changes about indexedDB are completely uninvolved in page load -- the indexedDB is used strictly to save/load filter lists et al., nothing else.

**Comment by hapibukipa** [comment] 2017-08-30 17:26
@gorhill

http://bit.ly/2wiLFGi


Same thing did as with RC2 but with RC0
with enabling uBo and loading the same 3 tabs
& they loaded & stopped profiling.

It didn't even with RC2

**Comment by hapibukipa** [comment] 2017-08-30 17:28
@gorhill 

> understand that the changes about indexedDB are completely uninvolved in page load -- the indexedDB is used strictly to save/load filter lists et al., nothing else.

So did something else chage which could have caused this?

Using RC2 is nearly impossible .
Pages are loading way to slowly.

**Comment by gomoku** [comment] 2017-08-30 17:30
The same issue here on FF 53.0.3 32bit + e10s enabled, as my uBlock Origin has recently autoupdated from 1.13.8 to 1.13.10, I've decided to switch from 1.13.10 to 1.13.11rc0, because as everybody know - 1.13.10 is broken due to a Firefox's bug, but I've switched back to 1.13.8 right now, because I've noticed that on 1.13.11rc0 the performance of the uBlock and the whole browser is very bad, everything is laggy, both FF UI & uBlock UI are lagging, the UI actions takes 2-3sec, for example: in uBlock switching between tabs or clicking "apply settings" button takes 2-3sec, also webpages loading slowly. After switched back to 1.13.8, everything is fast. Sorry for not giving some performance profiling data, because I don't know if I want to switch back to 1.13.11rc0 to test it, if I decide I'll add some profiling data. Also another issue is that some of filters were not working for example: `@@||*.dcs.redcdn.pl^$domain=dcs.redcdn.pl|www.tvn24.pl` was not working in 1.13.11rc0, after  switching back to 1.13.8 the filter works.

**Comment by hapibukipa** [comment] 2017-08-30 17:38
@gorhill

the comment above is similar to mine

> the performance of uBlock and the whole browser is very bad, everything is laggy, both FF UI & uBlock UI are lagging, the UI actions takes 2-3sec, for example: in uBlock switching between tabs or clicking "apply settings" button takes 2-3sec, also webpages loading slowly.

Something is wrong here,
Trying a new profile again and profiling loading 3 tabs again, please compare rc0 results with rc2 in term of the above quote.

**Comment by gorhill** [comment] 2017-08-30 17:40
Mostly what I see happening in your profile is, by reddit's own code hogging the CPU. uBO's code itself is below 4% in the content thread (where the pages are loaded). I see an overhead from webextensions javascript code from `resource://gre/modules/Schemas.jsm`.

So as said, report to Firefox devs if you think there are performance issues.

I will close this issue now because of the comments which adds no data to make teh case there is an issue with uBO proper. So far, my profile and yours do not support this.

**Closed by gorhill** 2017-08-30 17:40 UTC
Labels: unable to reproduce

**Comment by hapibukipa** [comment] 2017-08-30 18:05
http://bit.ly/2vFsAvi

Since I did the profiling when you wrote the above comment.
Please check it and see the page loading times etc, I don't know what to make out of it,
Glad this time i did with different websites
Also please do consider _**win10 & 32 bit firefox.**_

If you still feel that it's not uBo then no problem,
let the update push be complete, keep this thread open.

**Comment by crssi** [comment] 2017-08-30 18:13
OK. FF 55.0.3, uBO 1.13.11rc2

Throw in 3rd party filters additional filters... see list at the end.
Open any of your desired web page.
Additionally open also about:profiles and click restart normally. When FF restarts click on a your desired web page tab.
In the previous version (non WE/hybrid) this worked instantly.
I guess indexDB doesn't like too many entries.

```
https://cybercrime-tracker.net/all.php
https://hosts-file.net/wrz.txt
https://hosts-file.net/psh.txt
https://hosts-file.net/pha.txt
https://hosts-file.net/hphosts-partial.txt
https://hosts-file.net/hjk.txt
https://hosts-file.net/hfs.txt
https://hosts-file.net/grm.txt
https://hosts-file.net/fsa.txt
https://hosts-file.net/exp.txt
https://hosts-file.net/emd.txt
https://malc0de.com/bl/IP_Blacklist.txt
https://openphish.com/feed.txt
https://raw.githubusercontent.com/quidsup/notrack/master/trackers.txt
https://filters.adtidy.org/extension/chromium/filters/14.txt
https://ssl.bblck.me/blacklists/ublock-origin.txt
https://filters.adtidy.org/extension/chromium/filters/2.txt
https://hexxiumcreations.github.io/threat-list/hexxiumthreatlist.txt
https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/
https://easylist-downloads.adblockplus.org/message_seen_remover_for_facebook.txt
https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist
https://filters.adtidy.org/extension/chromium/filters/3.txt
https://filters.adtidy.org/extension/chromium/filters/4.txt
https://filters.adtidy.org/extension/chromium/filters/15.txt
https://raw.githubusercontent.com/metaphoricgiraffe/tracking-filters/master/trackingfilters.txt
https://raw.githubusercontent.com/byaka/ublock-antiskimming-list/master/build/data.txt
https://easylist-downloads.adblockplus.org/yt_annoyances_other.txt
https://easylist-downloads.adblockplus.org/yt_annoyances_suggestions.txt
```

**Comment by gorhill** [comment] 2017-08-30 18:15
@hapibukipa http://bit.ly/2vFsAvi

Stop abusing the repo please, as said above, you could have found in one second that uBO has nothing to do with your issue. Top pic is your CPU usage, bottom pick is uBO's own CPU usage:

![a](https://user-images.githubusercontent.com/585534/29888076-8ed08aa8-8d8d-11e7-97d3-e7387d38cde8.png)

**Comment by gorhill** [comment] 2017-08-30 18:16
@crssi This is not the place for pure speculations, there are places were pure speculations are welcomed and where people like to wallow in them.

As predicted, locking this thread.
