### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1935] opened 2016-08-26 16:56 UTC
||data.*.com^$document,popunder,popup can be added. popunder when clicking in search box:

http://1337x.to/torrent/964309/The-Sims-4-RELOADED/

**Comment by gorhill** [comment] 2016-08-26 22:14
The popups/popunders are closed properly on my side.

**Comment by Tmp341** [comment] 2016-08-27 04:29
I've tried that and a new tab opened and closed. (I remember, this is ublock's way of closing popups/popunders)

**Comment by monolifed** [comment] 2016-08-27 10:54
Is there a way to disable data:text/html popups. or disable all data:text/html elements?

`data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD52YXIgZXBvY2g9bmV3IERhdGUoKS5nZXRUaW1lKCk7dmFyIF9lcG9jaEZyb21XaW5kb3dOYW1lPXdpbmRvdy5uYW1lLnNwbGl0KCdfJylbM107aWYoZXBvY2gtX2Vwb2NoRnJvbVdpbmRvd05hbWU8MjUwKXt3aW5kb3cubG9jYXRpb249Jyc7fTwvc2NyaXB0PjwvYm9keT48L2h0bWw+`

This opens from a site and somehow leads to http://bridge.sf.admarketplace.net/ct?version=16.0.0&...
It is blocked by strict blocking but the strict blocking page stays

**Comment by hant0508** [comment] 2016-09-02 12:17
`1337x.to##body > div:not(.wrapper)` works fine for me

**Comment by crash123** [comment] 2016-09-07 13:40
This is a problem I am also experiencing. Clicking the "magnet download" link sometimes a pop under will appear which does not get caught by ublock.

**Comment by gorhill** [comment] 2016-09-07 13:42
> a pop under will appear which does not get caught by ublock.

Use the logger, find out what is the hostname of that popunder which is not caught, report the evidence and a filter will be created to take care of the issue. It's all about filters.

**Comment by crash123** [comment] 2016-09-07 13:50
Great will do the next time it happens is "issues" in github the place to report? Sorry I can't find any documentation on how to report.

**Comment by gorhill** [comment] 2016-09-07 14:02
For filter-related issues, report to <https://github.com/uBlockOrigin/uAssets/issues>.

When investgating popup/popunder issues, use the _All_ entry in the dropdown list of the logger, this will show you all requests from everywhere rather than just one specific tab.

**Comment by IDKwhattoputhere** [comment] 2016-09-25 19:06
This is the popunder I'm getting here:
![](https://cloud.githubusercontent.com/assets/16030872/18817557/842034da-8363-11e6-9dcb-7648ed8a669e.png)
It can also be found in `https://1337x.to/assets/js/script.js`.
`||adxite-ads.com^$popup`

**Comment by gorhill** [comment] 2016-09-25 20:05
What version of uBO? What browser?

**Comment by gorhill** [comment] 2016-09-25 20:07
I got this on my side:

![a](https://cloud.githubusercontent.com/assets/585534/18817914/31ca061c-833a-11e6-810e-0d8cdf6477bf.png)

**Comment by IDKwhattoputhere** [comment] 2016-09-25 20:20
uBO 1.9.10 + Chrome 53.0.2785.116
Looks the same for me most of the time. Just sometimes it looks like in my second screenshot where it's blocked as an alleged popup. I'd say the first request which goes to `adxite-ads.com` could be blocked although the popunder is closed on my side after that when going to `adrunnr.com` anyways.

**Comment by gorhill** [comment] 2016-09-25 20:38
In your screenshot, `adxlite-ads.com` can't be closed as a popunder, because the filter is generic. You could ask EasyList to add `||adxite-ads.com^$popup`?

**Comment by IDKwhattoputhere** [comment] 2016-09-25 20:56
> In your screenshot, adxlite-ads.com can't be closed as a popunder, because the filter is generic.

That's what confuses me. I see it opening like a popunder but it gets closed and the logger sometimes shows what you can see in the second screenshot. But I can't reproduce it anymore or at least not at the moment.

https://forums.lanik.us/viewtopic.php?p=103850#p103850

**Comment by culinko** [comment] 2016-11-21 15:51
I recently switched to uBlock and I am having the same issue. I added ||adxite-ads.com^$popup to my filters but the redirect still goes through. The redirect happens on new torrents and only happens once or twice per the same torrent. Today it happened on http://www.1337x.to/torrent/1903503/The-Walking-Dead-S07E05-INTERNAL-720p-HDTV-x264-KILLERS-ettv/ and the logger looks like this:

![torrent-redirect](https://cloud.githubusercontent.com/assets/11700272/20488672/2fbea364-b008-11e6-9ca8-e6a02d663ffb.png)

Please tell me if there is anything I can do (I am new to uBlock) or if I can provide more info. Thanks a lot!

**Comment by gorhill** [comment] 2016-11-21 16:28
The site creates popunders on my side, and they are properly closed.

**Closed** 2017-09-11 22:38 UTC
Labels: filter issue, unable to reproduce
