### ISSUE TITLE
Pietsmiet.de ads blocked by Adguard but with same filters not by uBlockO

### ISSUE THREAD

**Issue by sdfasdfgawe456h4356** [gorhill/uBlock#3067] opened 2017-09-29 13:35 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
When visiting pietsmiet.de ads are not blocked by uBlockO.
Im not adapt enough to tell wheter its a bug in UBO or wheter its bcos this particular Filter Syntax is not supported by uBlockO but by Adguard.

### One or more specific URLs where the issue occurs
www.pietsmiet.de
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
UBO:
![screenshot-2017-9-29 home - pietsmiet - videos news und spiele](https://user-images.githubusercontent.com/23087597/31018021-d772bb3c-a52a-11e7-90fe-52f92831fdc9.png)
Adguard - same filters:
<img width="816" alt="adguard" src="https://user-images.githubusercontent.com/23087597/31018440-634ebe3e-a52c-11e7-964a-6484aab08a50.png">

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. install ublock origin on one browser profile and adguard on another
2. enable the adguard german and english filters in both and disable other filters
3. visit www.pietsmiet.de

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: Firefox 56.0
- uBlock Origin version: 1.14.10

##### Your filter lists

adguard english + adguard german

**Comment by mapx-** [comment] 2017-09-29 13:42
it's like ad_bomb, should be added:
`||de/*/ad_banner/*$image,redirect=2x2-transparent.png`

**Comment by sdfasdfgawe456h4356** [comment] 2017-09-29 13:48
but clearly there already is a filter that blocks it in adguard.
so instead of making another filter that blocks it wouldnt it be better to find out why the adguard filter isnt working first of all. i mean most probably its an unsupported syntax (which maybe gorhill will consider adding) but it might be a bug in UBO. unfortunately i have no idea :)

**Comment by gorhill** [comment] 2017-09-29 14:03
> Pietsmiet.de ads blocked by Adguard but with same filters not by uBlockO

False. I get the ads with Adguard as well with Adguard English + Adguard German:

![a](https://user-images.githubusercontent.com/585534/31019343-640de72a-a4fd-11e7-9e76-08a75c615af9.png)

It's just a filter issue, thus closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by kasper93** [comment] 2017-09-29 14:04
```pietsmiet.de##script:inject(uabinject-defuser.js)```

> but clearly there already is a filter that blocks it in adguard.

Yes, but script injection syntax used in Adguard is not allowed in uBO. Only scriptlets from `resources.txt` can be used. And this is by design.

**Closed by gorhill** 2017-09-29 14:03 UTC
Labels: filter issue, invalid

**Comment by gorhill** [comment] 2017-09-29 14:23
> script injection syntax used in Adguard is not allowed in uBO

Adguard was not using scriptlet injection for this site, it just uses an exception filter `@@/ad_bomb/*$image` for the site. It just so happens that the site changed from `/ad_bomb/` to `/ad_banner/`.

Also, Adguard/Firefox is not allowed to inject external scriptlets from external sources, just like with uBO. They also have to use only the packaged ones. See <https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/filters/firefox/local_script_rules.json>. An advantage of uBO though is that the existing scriplets are referenced by tokens in filter lists, which means I can add new filters to inject existing scriptlets.

**Comment by kasper93** [comment] 2017-09-29 20:21
> Adguard was not using scriptlet injection for this site

They have generic rule that inject scriptlet https://github.com/AdguardTeam/AdguardFilters/blob/master/GermanFilter/sections/antiadblock.txt#L6 I don't know about Adguard restrictions, but unless it is not forbidden they are using scriptlet injection for this (and any other) site.
