### ISSUE TITLE
uBlock does not detect all <browser> loads

### ISSUE THREAD

**Issue by alta88** [gorhill/uBlock#3326] opened 2017-12-07 18:59 UTC
I have a custom Firefox v57 build, with a 'system' extension that loads a chrome:// xul page in a tab. The xul page is a &lt;window&gt; and contains a  &lt;browser type="content"&gt; element. uBlock is not activated on this xul page and doesn't detect any url loads in the  &lt;browser&gt;. Should/can it?

I would note that AdBlock Plus and NoScript both work.

**Comment by gorhill** [comment] 2017-12-07 19:14
Without a reproducable case, not much I can do.

Webextensions are not allowed to run on priviledged pages, and `chrome:` is a priviledge pages. I doubt ABP or NoScript work on these -- make a convincing case please by providing all the technical details -- since you build your own FF, I assume you have the competence to make the case about why you think uBO should work, and make the case that webext versions of ABP and NoScript work.

**Comment by gorhill** [comment] 2017-12-07 19:15
Marking as _invalid_ until the case is made -- i.e. provide evidences that uBO should work on your priviledge page, and provide evidence that webext version of ABP and NoScript work on that page.

**Closed** 2017-12-07 19:20 UTC
Labels: invalid

**Comment by alta88** [comment] 2017-12-07 21:29
Not sure how to prove uBO *should* do anything, bit of a logical fallacy there; the question was whether it is technically possible, given your knowledge in the space. It's possible uBO is architected in a way that it can't work.

However, I can state with certainty that ABP does work in this use case. A simple filter, gravatar.* eg, with all other filters turned off, will not appear as a GET in the console xhr log when loading a url with a gravatar image . With ABP disabled, the GET is there.  ABP blocking (log evidence) works the same whether the url is loaded in a tab, or loaded in the browser element of the chrome xul page in a tab. Build is Fx57 based with ABP 3.0.1, unlikely any build flag has anything to do with it. So there is a way to do this for a chrome page browser.

**Comment by gorhill** [comment] 2017-12-07 22:07
uBO uses the same webRequest API as any other webext blocker, so there is no reason that it shouldn't work if another one work. Investigate on your side since you are the only one who can reproduce your specific case.

**Comment by alta88** [comment] 2017-12-08 15:35
After several hours in a debugger and learning your internals, I can now state with certainty that the browser loads are handled and the problem was entirely local ;)

The issue now is stats; since the root chrome url doesn't change, stats cumulate for each browser page load. Perhaps if the root is chrome-scheme, entry items should be evicted if the load url changes? Would you entertain such a patch?

I really don't want to use ABP. One reason is that accept exceptions in a filter list can't be overridden. Easylist has one for secure.gravatar.com and apparently one of your lists overrides that, since those images don't get loaded. Kudos.
