### ISSUE TITLE
What's the utility to enable by default the Peter Lowe's Ad server list ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#436] opened 2015-07-03 11:40 UTC
The Peter Lowe's Ad server list is a Lightview ad list (host files) but in uBlock Origin It's enable by default WITH the easylist and the ultra majority of the Peter Lowe's Ad server list is in the easylist, I think that it's a duplicate. 

Sorry for my bad english and if I have say Something stupid.

**Comment by gorhill** [comment] 2015-07-03 12:28
> the ultra majority of the Peter Lowe's Ad server list is in the easylist

I don't think so, because here is what the filter stats say with and without Peter Lowe's:

- With: 48,492 network filters
- Without: 46,147 network filters

So Peter Lowe's brings in 48,492 - 46,147 = 2,345 network filters, meaning  out of the 2,411 total network filters in the list, only 66 filters were effectively duplicates.

I have seen this claims on ABP forums that Peter Lowe's mostly intersect completely with EasyList, but that is just not true. I did try [to correct that claim](https://adblockplus.org/forum/viewtopic.php?f=2&t=26220&p=110885#p110885), but ABP's people are [still leading people to believe Peter Lowe's is duplicate of EasyList](https://adblockplus.org/forum/viewtopic.php?f=2&t=29379&p=121165#p121133).

**Closed as completed by gorhill** 2015-07-03 12:28 UTC

**Comment by gorhill** [comment] 2015-07-03 12:40
By the way, I have been way to nice in [this benchmark](https://github.com/gorhill/uBlock/wiki/uBlock-and-others:-Blocking-ads,-trackers,-malwares) with regards to ABP: I did include _Peter Lowe's_ for ABP, which I really should not have given that ABP's people are telling people they should not use _Peter Lowe's_. Whenever I run this benchmark again, I won't have _Peter Lowe's_ used in ABP. You will defintitely see a difference, as can be seen in [older benchmarks](https://github.com/gorhill/uBlock/tree/master/doc/benchmarks) (the `privex-...ods spreadsheets).

**Comment by g3939434** [comment] 2015-07-03 15:59
>So Peter Lowe's brings in 48,492 - 46,147 = 2,345 network filters, meaning out of the 2,411 total network filters in the list, only 66 filters were effectively duplicates.

I think that is not technically correct. ublock only treats filters as duplicates if they are identical.

For example
`127.0.0.1 yieldmanager.net` in Peter Lowe and `||yieldmanager.net^$third-party` in EasyList will count as 2 filters.

And `127.0.0.1 example.com` and `||example.com/ad/` will count as 2 filters.

Subdomain and domain will count as 2 filters as well.

Just my **guess**, ABP's people telling users not to use Peter Lowe may because it may breaks some websites if directly blocking the whole domain. It's not so specific when comparing Easylist. An ad domain may not add to Easylist if it is *already blocked* by general advert blocking filters and *not so popular* around the world. It may due to performance and/or memory issue as well as minimized the whole list.

**Comment by gorhill** [comment] 2015-07-03 17:26
> 127.0.0.1 yieldmanager.net in Peter Lowe and ||yieldmanager.net^$third-party in EasyList will count as 2 filters.

This made me curious, and just for the sake of curiosity I forced all hostname-based filters to all load as `third-party`. Results came out as:

- With: 47,942
- Without: 46,130

So 1,812 extra hostnames -- but as you say, it becomes difficult to figure intersect surface.

**Comment by LifeIsStrange** [comment] 2015-07-07 20:26
Oh sorry for the late ! 
If you want I can analyse all the duplicates of the list and hiver you the list of duplicates and an other without duplicates  :)  
Also you can speak to the Peter Lowe's creator and retry to include this on easylist ? 
Also I can try, but I speak bad english.

**Comment by gorhill** [comment] 2015-07-07 20:38
There is no issue. The list can be used or not. I chose to enable it by default, users can disabled if they want. That's just about it.

**Comment by LifeIsStrange** [comment] 2015-07-07 20:47
Ok I understund, but I will ask to the easylist to merge the Peter Lowe's Ad server list in their list for better blocking et destroy duplicates for better perf. Thanks.
