### ISSUE TITLE
Syncing my settings, custom filters onto different machines (and browsers)

### ISSUE THREAD

**Issue by czardoz** [gorhill/uBlock#3572] opened 2018-03-05 06:54 UTC
### Describe the issue
It would be great to sync customizations across different devices, through Dropbox/Google Drive. I could contribute this myself, if the core team thinks it's a good idea!

### Your settings

- OS/version: All
- Browser/version: All  
- uBlock Origin version: All

**Comment by gorhill** [comment] 2018-03-05 11:03
Duplicate of #2468.

**Closed by gorhill** 2018-03-05 11:03 UTC
Labels: duplicate

**Comment by jspenguin2017** [comment] 2018-03-05 13:43
How would you store the access token? It feels dangerous to just put it in extension storage. I think Dropbox API is intended to be handled on server side.

**Comment by jspenguin2017** [comment] 2018-03-05 15:35
Violentmonkey can sync to Google Drive, so it's definitely possible. With a few quirks though: https://github.com/violentmonkey/violentmonkey/issues/278

**Comment by ivysrono** [comment] 2018-03-17 14:25
Violentmonkey support OneDrive too.
Support onedrive, please.

**Comment by xianghongai** [comment] 2018-04-13 02:06
I use Firefox and Chrome browsers, Both are installed uBlock, The current synchronization operation is a bit inconvenient.

I recommend adopting third-party mature cloud storage solutions like Tampermonkey.

![storage script  and settings](https://user-images.githubusercontent.com/2075006/38713103-17c3e7bc-3f02-11e8-94d4-b6b5ef1f3171.png)
