### ISSUE TITLE
Create hotkey shortcuts

### ISSUE THREAD

**Issue by WillPittenger** [gorhill/uBlock#2224] opened 2016-12-07 18:22 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

I'm a PaleMoon user in the process of converting from AdBlock Latitude.  I had CTRL-SHIFT-?, CTRL-SHIFT->, CTRL-SHIFT-< set to Blockable Items, Element Hiding Helper, and ABL Preferences respectively.  But uBlock seems to have no way to bring those (or something comparable) up with the keyboard.

### Your settings

Browser/version: Palemoon 27.0.2 64-bit Windows 10
uBlock Origin version: 1.10.0

**Comment by gorhill** [comment] 2017-03-22 13:07
Duplicate of #113.

**Closed by gorhill** 2017-03-22 13:07 UTC
Labels: duplicate
