### ISSUE TITLE
Safari Version for ublock/gorhill

### ISSUE THREAD

**Issue by phone8588** [gorhill/uBlock#547] opened 2015-07-30 20:24 UTC
With gorhill not contributing code to chrisaljoudi/uBlock  - can we now expect there will be a Safari version for gorhill/ublock - especially with Apple's upcoming blocking API in Safari on El Capitan? It is a pity to not get the latest features being added to the Chrome/Firefox versions on Safari.

**Comment by gorhill** [comment] 2015-07-30 20:58
Duplicate of #64.

**Closed by gorhill** 2015-07-30 20:58 UTC

**Comment by Zearin** [comment] 2015-11-06 15:05
> With gorhill not contributing code to chrisaljoudi/uBlock - can we now expect there will be a Safari version for gorhill/ublock - especially with Apple's upcoming blocking API in Safari on El Capitan? It is a pity to not get the latest features being added to the Chrome/Firefox versions on Safari.

:+1:
