### ISSUE TITLE
Support exporting interface

### ISSUE THREAD

**Issue by agilob** [gorhill/uBlock#122] opened 2015-04-25 13:07 UTC
I made this issue before in [chris repo](https://github.com/chrisaljoudi/uBlock/issues/1247), but this was complete ignored, now I know why. I'm opening it here, because I find this feature important.

I'm sure @dhowe left a comment in his repo, but it's not there anymore(?)

https://adblockplus.org/en/IAdblockPlus
> This interface can be used from extensions that wish to integrate with Adblock Plus. It allows among other things getting some information from Adblock Plus or adding "special" subscriptions that will be updated by another extension. 

https://github.com/dhowe/AdNauseam/issues/234

**Comment by alejandrolemus** [comment] 2015-04-25 13:16
Related to [this](https://github.com/gorhill/uBlock/issues/67)?

**Comment by agilob** [comment] 2015-04-25 13:31
Yes, that's the same issue. Sorry for duplicate.

**Comment by gorhill** [comment] 2015-04-25 13:51
Duplicate of #67.

**Closed by gorhill** 2015-04-25 13:51 UTC

**Comment by agilob** [comment] 2015-04-25 14:11
Why did you close both?

**Comment by gorhill** [comment] 2015-04-25 14:22
This one is a duplicate of #67, and the reason #67 was closed is [explained here](https://github.com/gorhill/uBlock/issues/67#issuecomment-93776540).
