### ISSUE TITLE
ublock origin extension ui broken on firefox for android

### ISSUE THREAD

**Issue by peterxiyong** [gorhill/uBlock#2341] opened 2017-01-26 13:21 UTC
### Describe the issue
I can't access options of ublock origin in Firefox for Android...it seems option button inside of ublock origin is missing....so no access to 3rparty filters and other submenus(bcoz main `options` menu is missing

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

![screenshot_2017-01-25-19-42-36](https://cloud.githubusercontent.com/assets/25366549/22332753/93526f18-e3f8-11e6-8cf4-046be2efd841.png)

### Steps for anyone to reproduce the issue

1. Open Firefox Android
2.navigate to tools-add on then ublock origin
3.you can't see options menu as was in previous version
### Your settings

default settings

- Browser/version: Firefox for Android 50.1 
Also Firefox Aurora developer version for Android beta 52.0a2
- uBlock Origin version: 
1.10.4
##### Your filter lists

Default filter lists 

##### Notes-
Can't test this new ublock origin 1.10.6 /1.10.7rc0 as Firefox don't allow unsigned add-on to install

Like these options of ublock origin Firefox Windows
"Show dashboard and show logger"
![screenshot 114](https://cloud.githubusercontent.com/assets/25366549/22333346/c87f089c-e3fb-11e6-9fe0-0e5a21de87cc.png)

**Comment by gorhill** [comment] 2017-01-26 15:22
Duplicate of #1379.

**Closed** 2017-01-26 15:22 UTC
Labels: duplicate
