### ISSUE TITLE
Please tell me what Yellow and Red rows in the Logger mean?

### ISSUE THREAD

**Issue by waynebloss** [gorhill/uBlock#1729] opened 2016-06-18 15:27 UTC
Can someone please tell me what a yellow row in the logger means? 

Also, I am assuming that a red row means that all requests to that resource were blocked. Can you confirm this?

I found a comment on reddit saying that "yellow means that **some** requests were blocked." However this concerns me since every time I look at the logger, the rows with "google-analytics.com/anything.js" are yellow. Even after I added a specific filter to block everything from google-analytics.com, it was still showing yellow.

I was going to submit an issue similar to #1192 at first, but now I just really want to know what those colors mean. Thanks.

**Comment by gorhill** [comment] 2016-06-18 16:38
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by waynebloss** [comment] 2016-06-18 17:47
Seems like it would have been just as easy to type one sentence telling me what *yellow rows* mean instead of typing out "Closing and marking as *invalid*...".

Thanks anyway? lol

**Comment by IDKwhattoputhere** [comment] 2016-06-18 18:06
Seems like it would have been much easier for you to ask this question in the right place to begin with.

**Comment by waynebloss** [comment] 2016-06-18 18:13
Yeah and still nobody has mentioned in this thread where this request actually "belongs". lol

Is this a support/discussion? I have no clue, nobody actually said that to me.

Is this a reproducable issue that I didn't provide steps for? No, clearly it is not. It's a simple request for a one sentence explanation of what your program does. 

Obviously, you'd all rather be assholes than provide a simple answer. Well, enjoy that behavior I'm sure you'll get real far in life with it. But damn it's entertaining and it's making me chuckle quite a bit at you so keep it coming I guess?

Thanks again xD

**Comment by waynebloss** [comment] 2016-06-18 18:17
Let me check that document again.

Hmmmm.. it's not a filter issue. Nope.

It is an issue that I have with the program - I want to know what yellow rows mean and the UI isn't telling me. So yeah, it's kind of an issue. lol

It hasn't already been fixed. Nope. If it were, I wouldn't be here.

So, once you all figure out where the correct place for this is why don't you just let me know?

Mmmkay. Thanks again - really.

**Comment by IDKwhattoputhere** [comment] 2016-06-18 18:27
Only one ridiculing himself is you. Right at the top of CONTRIBUTING.md it says:

> For **support/discussions**, there is Mozilla Discourse.

**Comment by waynebloss** [comment] 2016-06-18 18:38
Did you not read the part where I said that I did not know if this was a **support/discussion**??

*Perhaps you need some help with your reading comprehension.*

It's an issue to me. Of course different people have different opinions. I guess it's easier to be a rude asshole than to clearly direct people though. Probably because it comes naturally to both of you. It's OK though - I forgive you because the hilarity of this exchange has provided me with great laughter.

Anyway, you don't have to bother about it anymore. If I want to make this project better I'll just fork it and fix it myself. Thanks for your source code! Although, ABP is better in just about every way anyway though, so I'll probably just remember my time with Ublock Origin as a entertaining experiment.

Good day to you!

**Comment by Hrxn** [comment] 2016-06-18 18:46
> ABP is better in just about every way anyway though [..]

On which planet?

> Seems like it would have been just as easy to type one sentence [..]

I guess he has this on his 'saved replies' list. So it's only one click. Or two maybe.

**Comment by IDKwhattoputhere** [comment] 2016-06-18 18:47
@waynebloss This is obviously a support request. Nothing to do with opinion. How could you not know?

There's clear directions in CONTRIBUTING.md. Not sure how you managed to fail here.

We weren't going to bother about an invalid issue. And who cares if you switch to another adblocker? Gorhill doesn't profit off the users like some other devs. I bet they're happy to have yet another help vampire though.

@Hrxn
> I guess he has this on his 'saved replies' list. So it's only one click. Or two maybe.

https://chrome.google.com/webstore/detail/github-canned-responses/lhehmppafakahahobaibfcomknkhoina

**Comment by Hrxn** [comment] 2016-06-18 18:54
No, I didn't know this one, actually..

But it's built-in now, since maybe three months or so :wink: 

https://github.com/blog/2135-saved-replies
https://github.com/settings/replies?return_to=1

**Comment by gorhill** [comment] 2016-06-18 19:16
> Seems like it would have been just as easy to type one sentence 

Instead of opening invalid issues, you could read the wiki doc (_"Required reading"_  link aside _"I am an advanced user"_ in the _Settings_ pane) rather than behave as a [help vampire](http://slash7.com/2006/12/22/vampires/) in an issue tracker which is **expressly** reserved for code issues only.

**Comment by waynebloss** [comment] 2016-06-18 23:12
> @waynebloss This is obviously a support request.

@IDKwhattoputhere Nope. Not obvious at all. Of course obviousness is totally subjective.

> There're clear directions in CONTRIBUTING.md.

No, there are not. It absolutely does not say anything about how to identify the difference between an "issue" and a "support request".

Anyway - blah, blah, blah. ROFL - @gorhill  and @IDKwhattoputhere you guys would **obviously** rather spew vitriol at someone posting an issue than to answer a simple question.

I guess fighting with me was a better use of your time than just giving me the one piece of info I asked for? LOL. Well, at least it was fun for one of us. I'm not the one who's all mad because someone posted a question in my precious repo.

Yeah I'm a help vampire because I asked a question. You're obviously using the [asshole driven development](http://scottberkun.com/2007/asshole-driven-development/) method here.

Hey, congrats though on spending *way more time* than you had to on this issue.

> On which planet?

@Hrxn Perhaps uBlock is slightly faster than ABP. Big whoop. All my computers are fast. The user interface and the documentation are shit though and that's what matters to me. So yeah, ABP is better in just about every way. Besides that ABP blocks more ads. As soon as I started using uBlock, I started seeing more ads even though I subscribed to every single list.

**Comment by IDKwhattoputhere** [comment] 2016-06-18 23:45
You're requesting the explanation of the extension's design. How could it not be a support request?

>  someone posting an issue

You didn't post an issue though.
I was going to answer your question at first but wanted to see your reaction about the issue being closed first and it seems to have been worth it. You're apparently nothing more than a troll.
But the joke's on you since you spend the most time on this. You also seem pretty mad or is it normal for you to escalate situations by starting to insult people?

I also don't get your accusation of ADD. Mind expanding on this? Gorhill is the sole owner of this repo and knows more about this project than anyone else and therefore can make the best decisions.

ABP has much less features than uBO...

> I subscribed to every single list

...but I don't think you're on the level to discuss this.

**Comment by waynebloss** [comment] 2016-06-19 01:11
@IDKwhattoputhere Well, I didn't read your last reply and I'm not sure what your goal is here at this point, but maybe you should write a blog post next time? I probably won't read that either, but it seems like you enjoy writing since you're putting out paragraphs of replies here instead of just answering the question. 

LOL. Seriously. Every response makes me laugh and laugh and laugh. Thanks again for that!

Glad your policy of keeping non-coding issues off of here is working out so well for you, it seems to be a real time-saver. ;)

*(Not really. Fail harder. Buh-bye now. I unsubscribed from this absurd and hilarious thread for fear of busting my ribs.)*

**Comment by gorhill** [comment] 2016-06-19 12:56
> You're obviously using the asshole driven development method here.

The ability of GitHub to support [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) exists for a reason.

Creating **any exception** to [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) sends the message out there that the rules stated in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) can be disregarded since one can have his trivial support questions answered anyways.

Me not answering your trivial support question<sup>[1]</sup> (which answer is already in the wiki) is to ensure no such message is sent -- **to make sure people take [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) seriously**.

This is to prevent the project here from being flooded by invalid issues, these invalid issues are just noise on a tracker dedicated to code issue, they are detrimental to those following/forking the project, and a burden on other contributors.

[1] [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md): "You will have to make the case that the issue is really with uBlock Origin and not something else on your side"

**Comment by gorhill** [comment] 2016-06-19 14:08
Sorry about all this, the whole time I thought the question was about the color in the dynamic filtering pane (I have no explanation of why I came to think this), while the issue is clearly referring to the logger. I will fix the documentation.

**Comment by gorhill** [comment] 2016-06-19 14:27
I added this text to the wiki:

> The color of a row hints at how a how the resource was filtered:
> - No color: The resource was untouched, i.e. allowed to go through.
> - Red: The remote resource was blocked.
> - Green: The remote resource was allowed to go through as a result of an explicit bypass of existing > block filters/rules.
> - Yellow:
>     - A DOM element which was blocked by a cosmetic filter; OR
>     - A blocked network resource which was redirected to a local replacement resource.

Sorry about my reading comprehension, this is what caused this whole unfortunate thread.

**Closed by gorhill** 2016-06-19 14:27 UTC
Labels: invalid
