### ISSUE TITLE
NSFW porntube.com - Trackers using behind-the-scene whitelisting ?

### ISSUE THREAD

**Issue by YetAnotherGuestAccount** [gorhill/uBlock#1730] opened 2016-06-18 16:05 UTC
Open uBO logger to display behind-the-scene requests, open on this NSFW site for instance the URL

`http://www.porntube.com/videos/rachel-starr-fucking-husbands-hot-suited-boss_7204765`

then close the tab, then just after closing in the logger an unblocked behind-the-scene xhr request appears to an URL looking like

`http://northstar.porntube.com/tracker.php?uuid=1234567&time=0&user=anonymous&site=porntube`

(parameters values may vary).

In fact before one closes the tab, there is a similar request originating from the tab and blocked by Fanboy's ultimate list's filter

/tracker.php?

but this filter can't block the similar request when it originates from behind-the-scene because behind-the-scene is whitelisted by default by uBO. Now I am not sure that this is a tracker or another nuisance and I am not a very advanced user but I suspect it is and more importantly, that it may be using some not yet widely known trick to avoid blockers which whitelist behind-the-scene requests. If I'm not totally wrong maybe the trick could be looked at and the behind-the-scene default whitelisting could be reconsidered ? I realize that to handle this case an advanced user can remove the behind-the-scene whitelisting and replace the default dynamic filtering rules with something like

behind-the-scene \* \* allow
behind-the-scene porntube.com \* noop

to let the static filters block what needs to be, but what about other users and sites if that sort of trick becomes common ? I am not sure what could be done to solve the problem but my purpose here is only to report it.
### Versions
- Browser/version: Firefox 47.0
- uBlock Origin version: 1.7.0
### Settings
- I added a bunch of static filter lists from the proposed ones or made by myself, I won't give them all unless it becomes relevant to know

**Comment by jo2dan23** [comment] 2016-06-19 13:04
subscribe to easyprivacy it is blocked in that list

**Comment by gorhill** [comment] 2016-06-19 13:17
> subscribe to easyprivacy it is blocked in that list

The issue can be reproduced with default settings, which include _EasyPrivacy_.

Observations so far:

`shouldLoad` is not called for that XHR sent at page's `beforeunload` time. This means uBO's HTTP observer is not able to find that XHR event in its queue, hence it has to assemble as best can be the missing information, and since the tab was closed, it cannot associate a tab with that XHR network request, hence it is marked as behind-the-scene.

The question now is: why this (`beforeunload`) XHR not passed to `shouldLoad`? Need to investigate further.

**Comment by gorhill** [comment] 2016-06-19 13:30
> The question now is: why is this (`beforeunload`) XHR not passed to `shouldLoad`? Need to investigate further.

Actually `shouldLoad` is called, the problem is that the message sent process never arrive on uBO's core side, probably because the tab associated with that message manager no longer exist (because tab was closed).

**Closed** 2017-09-11 12:02 UTC
Labels: filter issue
