### ISSUE TITLE
Ask confirmation to save the 4 per-site "toggle" options too

### ISSUE THREAD

**Issue by andya9** [gorhill/uBlock#2102] opened 2016-10-27 12:41 UTC
Using ublock in advanced mode. Firefox beta 50b10, ublock 1.9.16.

When I change per-site permissions about third-party providers I have to manually lock the changes to make them persistent.

This isn't so when toggling web fonts, large file media, cosmetic changes and popups: if I toggle them the change will still be there next time I visit the site. IMO it would be great if these 4 options needed locking too (especially large file blocking).

**Comment by gorhill** [comment] 2016-10-27 12:47
Duplicate of #941.

**Closed by gorhill** 2016-10-27 12:47 UTC
