### ISSUE TITLE
uBlock and peacekeeper.futuremark scenario bug

### ISSUE THREAD

**Issue by zvitalikus** [gorhill/uBlock#406] opened 2015-06-25 20:00 UTC
After the passage of version 0.9.5.0, at the end of the test http://peacekeeper.futuremark.com DOM objects,  browser freezes and displayed a script error.

browser firefox 39.

**Comment by gorhill** [comment] 2015-06-25 20:16
Unable to reproduce using default settings and provided steps.

Closing as "invalid". Will reopen if more details are provided for me to reproduce.

**Closed as completed by gorhill** 2015-06-25 20:16 UTC
Labels: invalid, unable to reproduce

**Comment by zvitalikus** [comment] 2015-06-26 08:59
The error displayed only then enabling the option parse and enforce cosmetic filters.
eror in chrome://ublock0/content/js/contentscript-end.js:662
http://postimg.org/image/b48tgekpj/

Bad that when you turn off this option stops working my own filters.

**Comment by zvitalikus** [comment] 2015-06-26 09:14
upd.
Testing on Nigtly firefox-41.0a1 all passed. Maybe browser java bug..

**Comment by gorhill** [comment] 2015-06-26 11:06
> chrome://ublock0/content/js/contentscript-end.js:662

What version of uBlock were you using when this error showed up?

**Comment by zvitalikus** [comment] 2015-06-26 11:10
0.9.9.2 release
0.9.9.3-dev.0

**Comment by gorhill** [comment] 2015-06-26 11:28
> 0.9.9.2 release
> chrome://ublock0/content/js/contentscript-end.js:662

That's [the line `contentscript-end.js`](https://github.com/gorhill/uBlock/blob/4a563538b0eb8372312d1704b5e6e9d1fd2e6a56/src/js/contentscript-end.js#L662) in v0.9.9.2: I can't make sense that this would fail there.

> http://postimg.org/image/b48tgekpj/

What's the picture for?

**Comment by zvitalikus** [comment] 2015-06-26 12:10
0.9.9.2 https://github.com/gorhill/uBlock/blob/4a563538b0eb8372312d1704b5e6e9d1fd2e6a56/src/js/contentscript-end.js#L662

0.9.5.0 in version https://github.com/chrisaljoudi/uBlock
https://github.com/chrisaljoudi/uBlock/blob/master/src/js/contentscript-end.js#L662

For fun I replaced contentscript-end.js 0.9.9.2 version 0.9.5.0 and all it worked!

**Comment by gorhill** [comment] 2015-06-26 12:16
You did not answer: what's the whole exact error message?

**Comment by zvitalikus** [comment] 2015-06-26 12:19
http://postimg.org/image/6rqb478kr/
http://postimg.org/image/wc2f7y8wt/

**Comment by gorhill** [comment] 2015-06-26 13:11
> http://postimg.org/image/6rqb478kr/

Ok it's not a javascript error, it's the browser notifying you that the script is taking long to execute. Given that you are using uBlock with a browser performance test, it's not totally unexpected. There is nothing really to change in uBlock, I can't make code design decisions based on browser pages which are meant to create/execute stressful scenarios which purpose is to push your browser to its limits performance-wise.

![c](https://cloud.githubusercontent.com/assets/585534/8377779/3032c6ec-1be2-11e5-87f9-bdf9dea9d9f4.png)

**Comment by zvitalikus** [comment] 2015-06-26 13:26
Clearly, thanks for the reply and sorry for the trouble.
