### ISSUE TITLE
[SeaMonkey] Tab selector list error

### ISSUE THREAD

**Issue by LeafG** [gorhill/uBlock#218] opened 2015-05-20 05:26 UTC
Windows 7/ SeaMonkey 2.33.1/ uB0 0.9.7.5

This one is similar to [#212](https://github.com/gorhill/uBlock/issues/212), and I didn't know if I should add it there or open a new one, because it's another browser:

When opening SeaMonkey, without any site at all, only a single empty tab, the list on the logger's tab selector includes 4 "about:blank" lines.

The list does not get shorter if I close tabs that were opened on that first window. Instead, for every tab I close (and its name disappears), another "about:blank" line is added.

Opening a new browser window, adds additional 4 "about:blank" lines.

Closing that window, does not delete the 4 "about:blank" lines. It also does not remove names of tabs that were open when the windows was closed.

The list on the tab selector only got shorter after about 10 minutes from the time of closing the 2nd browser window.

On Pale Moon 25.4.1 (x64):

The tab selector does update immediately as expected , but the case of the 2nd browser window is the same.

**Comment by gorhill** [comment] 2015-05-20 10:55
Duplicate of #212.

**Closed as completed by gorhill** 2015-05-20 10:55 UTC
