### ISSUE TITLE
Layout in element picker mode is broken

### ISSUE THREAD

**Issue by ialexsilva** [gorhill/uBlock#3333] opened 2017-12-09 12:14 UTC
### Describe the issue

Layout in element picker mode is broken

### One or more specific URLs where the issue occurs

http://utubedownload.me/

### Screenshot in which the issue can be seen
![vfp7mxe](https://user-images.githubusercontent.com/6363160/33795432-40241232-dcc8-11e7-8d2e-fc144beb58cc.png)

### Steps for anyone to reproduce the issue

1. Navigate to site http://utubedownload.me/
2. Right click
3. Click on Block Element

or

1. Navigate to site http://utubedownload.me/
2. Click on uBlock icon
3. Click on "Enter element picker mode"

### Your settings

- OS/version: Windows 10 x64
- Browser/version: Firefox 57.0.2 (64-bit)
- uBlock Origin version: uBlock Origin 1.14.20

##### Your filter lists

**Default filter lists**

##### Your custom filters (if any)

N/A

**Comment by gorhill** [comment] 2017-12-09 12:40
Duplicate of #2240.

**Closed by gorhill** 2017-12-09 12:40 UTC
Labels: duplicate
