### ISSUE TITLE
[NSFW] PornHub vids won't play

### ISSUE THREAD

**Issue by LoreJon** [gorhill/uBlock#1780] opened 2016-07-05 15:43 UTC
http://www.pornhub.com/

After the last uBlock filters update the ads are blocked but the videos won't play.

Thanks.

**Comment by gorhill** [comment] 2016-07-05 15:48
I just committed a fix prior to see the issue here. Can you try with updated filters?

**Comment by gorhill** [comment] 2016-07-05 15:50
Also, are you using the Flash-based player or HTML5 one?

**Comment by gorhill** [comment] 2016-07-05 15:55
The Flash-based videos were blocked -- the HTML5 ones worked. Fixed.

**Closed** 2016-07-05 15:54 UTC

**Comment by LoreJon** [comment] 2016-07-05 16:18
Flash-based videos are still locked.
Thanks.

**Comment by aggat** [comment] 2016-07-05 16:19
Add `$object` also here
`@||phncdn.com^$media,stylesheet,domain=gaytube.com|pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|xtube.com|youjizz.com|youporn.com|youporngay.com`

**Comment by LoreJon** [comment] 2016-07-05 16:21
Still blocked.

**Comment by aggat** [comment] 2016-07-05 16:30
LoreJon try add to `My filters`
`@@||phncdn.com^$object,media,stylesheet,domain=gaytube.com|pornhub.com|redtube.com|tube8.com|tube8.es|tube8.fr|xtube.com|youjizz.com|youporn.com|youporngay.com`

**Comment by LoreJon** [comment] 2016-07-05 18:43
@aggat ,
That works.

@gorhill ,
Souldn't this rule be addaed to uBlock filters – Unbreak?

Thanks

**Comment by IDKwhattoputhere** [comment] 2016-07-05 22:08
It's caused by `uBlock filters‎` so the fix should be in there‎ too.
