### ISSUE TITLE
[Firefox] Settings reset bug

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#96] opened 2015-04-19 18:19 UTC
'Reset to default settings...' button in the uBlock Dashboard triggers a popup, which says that all settings will be removed and uBlock will restart.
1. Expected behaviour:
   uBlock resets it's settings and restarts silently
2. What happened
   Firefox suddenly closed and user has to restart it himself

Test machine was an old Asus Eee PC running Xubuntu 14.04.02 LTS, Firefox 37.0.1, uBlock Origin 0.9.4.4. However, I can't reproduce it. Before the bug happened (resetting settings) I deleted old uBlock (IIRC it was from Mozilla addon market), installed the new one from Github and played with it's settings.

**Comment by my-password-is-password** [comment] 2015-04-19 19:03
I tried to reproduce the closing of Firefox but couldn't.  Do you mean the Dashboard closes and the user has to restart it themself after a restore to default?

**Comment by lcrts** [comment] 2015-04-19 19:09
I know that should happen but for me whole Firefox closed and didn't start automatically afterwards. I opened Firefox manually and uBlock had resetted it's settings. I can't reproduce the bug but I thouht I might report it anyway. Sorry if it's too obscure, it might not even be caused by uBlock because before the bug happened I deleted the old version and installed the new version from Github. Maybe that messed Firefox up because I didn't close it at any point.

**Closed as completed** 2015-04-21 21:07 UTC
