### ISSUE TITLE
Can't block div and video

### ISSUE THREAD

**Issue by BratSinot** [gorhill/uBlock#2328] opened 2017-01-22 20:29 UTC
On some [site](http://www.кингисепп-сегодня.рф/) we have HTML5 video-player with ads.
P.S. For example this [video](http://www.xn----etbbecbrbp5ahkja1ae7v.xn--p1ai/news/video-375/).
If we block **www.xn----etbbecbrbp5ahkja1ae7v.xn--p1ai/videoreklama** advertising will not be displayed.
But in code we have 2 tags div and video with **elite_vp_videoPlayerAD** class.
Then i try block they, like this "**##.elite_vp_videoPlayerAD**", or this "**##div[class="elite_vp_videoPlayerAD"]**" uBlock just didn't seem them.

I use Chromium 58.0.2988.0 and latest uBlock Origin.
![scr](https://cloud.githubusercontent.com/assets/3810015/22185639/80f464e4-e0fa-11e6-93ae-988eaffbb798.png)

**Comment by gorhill** [comment] 2017-01-22 21:10
It's inside an iframe, the picker works only on top document, not embedded document.

Duplicate of #1744.

If you know the hostname of the iframe which contains `.elite_vp_videoPlayerAD`, then just manually add the filter in _"My filters"_ pane: `example.com##.elite_vp_videoPlayerAD`.

**Closed by gorhill** 2017-01-22 21:10 UTC

**Comment by gorhill** [comment] 2017-01-22 21:12
Looking at your screenshot, you might have been looking for `kingisepp-today.ry##.elite_vp_videoPlayerAD`.
