### ISSUE TITLE
Extension error when using with Disconnect

### ISSUE THREAD

**Issue by Mottie** [gorhill/uBlock#1699] opened 2016-06-08 17:41 UTC
### Describe the issue
In Chrome 51.0.2704.84 m, on a Windows 10 64bit OS, if I install the [disconnect](https://github.com/disconnectme/disconnect) extension along with uBlock, I consistently get an extension error when visiting certain sites. The error does not show up in the development panel, but it does change the color of the menu and shows the error on the chrome://extensions/ page.

![2016-06-08 11_54_10-](https://cloud.githubusercontent.com/assets/136959/15902903/ded50b66-2d6f-11e6-835d-40cecf2bc521.png)

### One or more specific URLs where the issue occurs
http://stackoverflow.com/

### Screenshot in which the issue can be seen

![2016-06-08 11_46_33-extensions](https://cloud.githubusercontent.com/assets/136959/15902806/70dfa328-2d6f-11e6-9c18-ba374f1eac30.png)

### Steps for anyone to reproduce the issue

1. Have Disconnect & uBlock extensions enabled.
2. Go to http://stackoverflow.com/
3. Notice the Chrome menu icon change to an orange color.
4. Open the chrome extensions page.
5. Look at the uBlock extension displayed error.
6. Here is an animated gif:

  ![ublock](https://cloud.githubusercontent.com/assets/136959/15903585/0ad2d9ca-2d73-11e6-84a2-9e95a8768e38.gif)

### Your settings

* Browser/version: Chrome 51.0.2704.84 m
* uBlock Origin version: 1.7.2

##### Your filter lists

* Using Default filter lists.
* The error occurs even after I use "Reset to default settings...".

##### Your custom filters (if any)

* None

I wasn't sure how to copy/paste the logger info and keep the colors, so here are some screenshots

![2016-06-08 12_30_01-ublock logger](https://cloud.githubusercontent.com/assets/136959/15904324/3297b248-2d76-11e6-95aa-0338e19dd1a9.png)
![2016-06-08 12_30_42-ublock logger](https://cloud.githubusercontent.com/assets/136959/15904329/358e380a-2d76-11e6-9f44-755ff5354d1d.png)

**Comment by IDKwhattoputhere** [comment] 2016-06-08 17:43
https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068

**Comment by gorhill** [comment] 2016-06-08 17:57
Duplicate of #1170.

**Closed by gorhill** 2016-06-08 17:57 UTC
