### ISSUE TITLE
All custom filters disappeared

### ISSUE THREAD

**Issue by IgitBuh** [gorhill/uBlock#2991] opened 2017-09-09 08:46 UTC
### Describe the issue
Suddenly all my custom filters are gone. The tab "My Filters" is now empty. I've been using uBlock Origin for about one year now and I've been adding custom filters piece by piece whenever I noticed something annoying on a website. Now all this work is gone.

### Steps for anyone to reproduce the issue
Well, I don't know the reason or the exact moment they disappeared. Maybe it was with an update (I'm now at uBlock Origin v1.14.4), maybe after a Firefox crash. I probably didn't notice it right away, because the changes are subtle and not on all websites I frequently use. I definitely didn't enter any new custom filter in the last weeks, so it can't be due to a new filter.

### Your settings
- OS/version: Windows 7, x64
- Browser/version: Firefox ESR 52.3.0 x86
- uBlock Origin version: v1.14.4

###
Id didn't find any topic with the same problem, so I decided to describe the problem I encountered.
At the same time I'd like to ask for help, in case there's something I could try to get my filters back. In which file are the custom filters stored? I could try to analyze that file or to see if I can get it back from a system backup.

**Comment by FatOrangutan** [comment] 2017-09-09 09:14
Read the 'To recover your lost settings' part on [this page](https://github.com/gorhill/uBlock/releases/tag/1.14.0).

**Comment by gomoku** [comment] 2017-09-09 14:00
@IgitBuh: Poorly searched then:
1) A duplicate of https://github.com/gorhill/uBlock/issues/2960
2) Also the same can be found at uBlock's addon webpage:
 https://addons.mozilla.org/firefox/addon/ublock-origin/ 
scroll to the bottom >> Information about version >> see release notes

**Comment by gorhill** [comment] 2017-09-09 14:14
It's all explained in the [release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.0) and the [front page of uBO on AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/).

**Closed by gorhill** 2017-09-09 14:14 UTC
Labels: invalid
