### ISSUE TITLE
Logger feature: ability to toggle visibility of cosmetic hiding activity 

### ISSUE THREAD

**Issue by joey04** [gorhill/uBlock#2876] opened 2017-08-15 22:38 UTC
Requesting what would be a nice-to-have feature: ability to toggle visibility of cosmetic hiding in the Logger.

Rationale: some sites have lots of hiding rules from EasyList + Fanboy Annoyances. Plus I've gone hog wild with :style on a few sites (which is a truly great feature - thanks much for adding it!). So on these sites there can be lists of "dom" items in the logger more than a screen long, even on my big monitor. This becomes visual clutter when troubleshooting site breakage.

I suggest adding a new Logger button between the eraser and filter toggle buttons with same UI behavior as the filter toggle button.

(general FYI -- For the opposite behavior of only showing hiders, that's already easy to do in the Logger filter bar with "##". It's better than "dom" which also picks up "domain" in resource requests.)

**Comment by gwarser** [comment] 2017-08-16 12:19
If its easy, then do `!##` :)

**Comment by gorhill** [comment] 2017-08-16 13:00
Marking as duplicate of #787.

**Closed by gorhill** 2017-08-16 13:00 UTC
Labels: duplicate

**Comment by joey04** [comment] 2017-08-16 18:12
Wow, didn't know about the `!##` inverse ability! Thanks @gwarser! And thanks @gorhill for implementing so many useful details like that.

**Comment by joey04** [comment] 2017-08-16 21:31
@gorhill -- just a small follow-up suggestion: could you add a link to the Logger wiki in the Logger window? Probably best to use the same little circle "i" icon that's in the Dashboard for several wiki links.

I'm not sure the best place to put it -- perhaps in upper-left just before the dropdown tab list? Or maybe all the way in the far upper-right on its own would be better? Either way, it'd be helpful to have the link on the page, similar to the times I've clicked the info icon on the "My filters" panel to reference the static syntax wiki page.

**Comment by joey04** [comment] 2017-08-16 21:47
And while I'm here, I'll add that the Logger wiki page has 2 items missing:
1) Please add a brief statement for Color blind mode. Something like, "When Color-blind friendly mode is enabled, the Red and Yellow are both changed to Blue." (Being red-green blind myself, I'm not even sure what the allow color is -- cream?)
2) There's no mention of the </> button or its functionality. (I realize that's a DOM tree view, which may be covered in another wiki page. I personally haven't used it and don't know much about it, but it would be good to mention it for completeness.)
