### ISSUE TITLE
Add custom rules in question ，And automatic updates will not update the list of issues

### ISSUE THREAD

**Issue by potkeys2** [gorhill/uBlock#692] opened 2015-09-07 15:38 UTC
Still can not add your own custom https://easylist-downloads.adblockplus.org/fanboy-social.txt regulatory issues, and some rules are not added, not listed. There is even a built-in rules subscription, empty the cache point update, the update also less than the latest rules. I am in China, there are less than circumvention tools also update the current list, a list of rules 0

**Comment by gorhill** [comment] 2015-09-07 15:46
> Still can not add your own custom

The fix was not to let one add a duplicate of a stock filter list, the fix was to properly select an exisiting stock filter list when it matched a custom filter list.

Just select the stock filter list Fanboy's Social, it does **exactly** what a custom <https://easylist-downloads.adblockplus.org/fanboy-social.txt> would do.

**Comment by potkeys2** [comment] 2015-09-08 00:17
You say out of the box, then why not a list of rules like ABP ABP as a direct default subscription list that several official address?We must use forums.lanik.us these escrow and then update the user's local it? Not as a direct subscription ABP official address, it is not superfluous it? I do not understand what you are thinking
![default](https://cloud.githubusercontent.com/assets/14056326/9724002/dcadaaa0-5601-11e5-9931-b93970c810aa.PNG)

**Comment by potkeys2** [comment] 2015-09-08 00:50
http://bbs.kafan.cn/thread-1848601-1-1.html
In a forum, some people question your rules, I copied it to you。

The following remarks are difficult because uBlock streamline high and black, good girls who do not look at the paper yo!


The same unpleasant features, Adblock Plus suffered condemned, uBlock Origin everyone sing in unison.


After a long discussion, let us now summarize the relative uBlock Adblock exactly what disadvantages:
1) individuals who worked hard to update the rules / organization than uBlock Origin authors also implausible because they use a wide variety of managed servers, and uBlock selected Github trustworthy.
2) uBlock can automatically filter against himself remarks with screenshots. You said what, produce evidence to die, I do not see it?
3) uBlock for the sake of users, whether you need not, have to download all the rules down again. When you want to switch the rules do not have to re-download, so convenient!
4) In order to prevent user errors cause uBlock modify subscription rules fail, the average user can not directly view and modify subscription rules uBlock of. Hackers, you are not destroy my uBlock rules? Tucson drawings broken, oh!
5) Adblock acceptable advertising unpopular, so we have to resist, uBlock "reasonable" design is the public mind as to, so we have to respected. what? Do you think the rules update mechanism uBlock bad? Even low levels can not understand, and I communicate with you disdain Lie Lie, oh!
By 6) by default, we will direct the user to "push" a number of rules that are very credible (at least this stage), no need to completely rule out the list of identification does not require allowing users to directly see What content. What, you are not satisfied? Since you're using my extension is equivalent to consent to my user license, then you shut up and accept my change set!
7?) UBlock built-in rules have been tempered, all sorts of research, so we produced a MD5 hash values ​​of these lists for automatic updates. Deliberate destruction of an updated list of those hackers will be nowhere to hide in the hash value of the test! Checksum Adblock Plus is used with the rule expires label already out of date, only uBlock latest idea is the best.

Then in order to prevent people do not see, I was put in front of the important come?
![1](https://cloud.githubusercontent.com/assets/14056326/9724119/09203a6e-5605-11e5-8af4-33882b84d4ba.png)
![2](https://cloud.githubusercontent.com/assets/14056326/9724120/094d13f4-5605-11e5-80b9-1bf5d6f09fb5.png)
The following is the old post content ================== ==================
Duplicate content is not necessary, it is the friends you want to know visit http://bbs.kafan.cn/forum.php?mod=viewthread&tid=1848278&page=4#pid35671960

Why does the author at Github Release Channel extend down the inside is 1MB, while in Release Note was submitted to the extended audit Mozilla down really 3MB, and the version number is not it a bit? ʱ?? ʱ?? Well, I have come to alarmist.
![3](https://cloud.githubusercontent.com/assets/14056326/9724146/58f00b0a-5605-11e5-8828-43cf38efc208.png)
![4](https://cloud.githubusercontent.com/assets/14056326/9724145/58efc3d4-5605-11e5-9fe8-28d23f814d3c.png)
Digression: Then uBlock, still engaged in stealth list, is still read from Github.
![5](https://cloud.githubusercontent.com/assets/14056326/9724178/be264872-5605-11e5-9d94-a69a07468d13.png)
![6 1](https://cloud.githubusercontent.com/assets/14056326/9724179/be5d826a-5605-11e5-9829-0770e358fb6a.png)
Then, look at me spell it?
![6](https://cloud.githubusercontent.com/assets/14056326/9724192/e57a6bb0-5605-11e5-96ae-3dd44d6ad628.jpg)
What I'm not sure now update mechanism? Why still publicsuffix.org following PSY rules? But RepoOnly? ʱ?? While others are RepoCopy? ʱ?? ʱ?? And why this document is compiled? ʱ?? While others are not? ʱ??
![7](https://cloud.githubusercontent.com/assets/14056326/9724212/283983aa-5606-11e5-97b6-7855cd7edd81.jpg)
Or Origin, in manually remove assets \ after thirdparties. First, open the rule preview content blank, as before.
![8](https://cloud.githubusercontent.com/assets/14056326/9724217/3dc1adc4-5606-11e5-85b9-c93dfe57460a.png)
Why do still check metadata updates to Repo Repo why go?
![9](https://cloud.githubusercontent.com/assets/14056326/9724222/5b77e360-5606-11e5-8fd5-2e12421cbe33.png)
Why after all cache cleared URL rule as well as 88 with 54 elements filtering rules? ʱ??
![10](https://cloud.githubusercontent.com/assets/14056326/9724229/72a03a92-5606-11e5-85a2-ce9195cbddbb.jpg)
A lot of other problems, caring people to find their own right. I'm too lazy to Tucao, the biggest problem remains 6MB + ublock0.sqlite cleared when the cache capacity, Tanshou. Regardless of other people in the end I think this thing is how, at least I do not think it is very good, is completed. Call a look sentiment was also annoying.


The finale is the most natural thing in the final. I just smiled in silence.
![11](https://cloud.githubusercontent.com/assets/14056326/9724235/85494684-5606-11e5-80d4-6132f413c20f.jpg)

**Comment by gorhill** [comment] 2015-09-08 04:25
I completely miss the issue here.

Using a custom filter  list <https://easylist-downloads.adblockplus.org/fanboy-social.txt> or selecting _Fanboy's Social Blocking List_ accomplishes the **exact same thing**: the filter list will be downloaded from <https://easylist-downloads.adblockplus.org/fanboy-social.txt>. Making an issue out of this is nonsense.

**Closed** 2015-09-08 08:07 UTC
