### ISSUE TITLE
[SUGGESTION] Add Horizontal Scrollbars on Panel

### ISSUE THREAD

**Issue by NoEscape** [gorhill/uBlock#3267] opened 2017-11-22 22:46 UTC
### Describe the issue
When uBlock Origin toolbar icon is pinned to overflow menu on Firefox 57 (Quantum) left side of panel gets cutoff if you expand the panel to show domains connected and you can't collapse the panel since "domains connected" is cutoff the screen.

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
Not pinned
[https://www.flickr.com/gp/not_a_number/vpea6K](url)
Pinned
[https://www.flickr.com/gp/not_a_number/Y5Es6v](url)

### Steps for anyone to reproduce the issue
1. Pin uBlock Origin toolbar icon/button to overflow menu on Firefox 57 (Quantum)
2. Click on overflow menu arrows
3. Click on uBlock Origin icon
4. Click on "domains connected"

### Your settings
All settings default

- OS/version:  Windows 7 Pro 32bit
- Browser/version: Firefox 57.0
- uBlock Origin version: 1.14.18

##### Your filter lists
Default Filter Lists
##### Your custom filters (if any)
None

**Comment by gorhill** [comment] 2017-11-22 23:53
Duplicate of #2809.

**Closed by gorhill** 2017-11-22 23:53 UTC
