### ISSUE TITLE
Can't block banners with !important css tag in Chrome 47.0.2526.73

### ISSUE THREAD

**Issue by PekaFat** [gorhill/uBlock#1011] opened 2015-12-05 16:13 UTC
uBlock 1.3.3 can't block banners in Chrome 47.0.2526.73 with !important css tag, example:

https://e.mail.ru/messages/inbox/ (registration requred)

![123](https://cloud.githubusercontent.com/assets/13280748/11608716/64d3b9e0-9b82-11e5-9273-abeedc5be942.png)

![asdasd](https://cloud.githubusercontent.com/assets/13280748/11608776/404216b0-9b84-11e5-9b17-54ffe32945d0.png)

After refresh page with this banner - it's appears again.

**Comment by gorhill** [comment] 2015-12-05 16:42
Duplicate of #963.

**Closed by gorhill** 2015-12-05 16:42 UTC
