### ISSUE TITLE
Enterprise Deployment

### ISSUE THREAD

**Issue by kousu** [gorhill/uBlock#3531] opened 2018-02-20 22:25 UTC
### Describe the issue

I would like to deploy uBlock as part of our organization-wide configuration.

I've learned that I can deploy it as part of firefox by placing the Firefox .xpi in `/usr/lib/firefox/browser/extensions/uBlock0@raymondhill.net.xpi` (or `/usr/lib/firefox-esr/browser/extensions/uBlock0@raymondhill.net.xpi` if you're running [Firefox Enterprise](https://www.mozilla.org/en-US/firefox/organizations/)).

I can also distribute `about:config` settings in `/usr/lib/firefox/browser/defaults/preferences/*.js`

Where I'm stuck is in defining uBlock's settings. It doesn't seem to use `about:config`; instead there's `~/.mozilla/*.default/browser-extension-data/uBlock0@raymondhill.net/storage.js` which contains a big JSON struct with all the filter lists and other settings. I've experimented with trying to put this file under `browser/defaults/`, or `browser/distribution` which is supposed to be extensions and other settings that Firefox copies at profile creation time (like a Firefox `/etc/skel`), and I've asked [enterprise@mozilla.org](https://mail.mozilla.org/listinfo/enterprise) their only advice was to distribute one of those `about:config` files, which I don't think uBlock uses.

So, is there some `about:config` tweak I can make to point uBlock at a specific `storage.js`? Or is there some other system-wide place that uBlock checks for its settings?

Alternately, does anyone know how to ship `browser-extension-data/` with Firefox? Because the Firefox people don't seem to.

### Your settings

- OS/version: Debian 9
- Browser/version: Firefox 52 ESR
- uBlock Origin version: 1.15.6

I haven't customized any settings, because the whole point is to customize those settings.

**Comment by gwarser** [comment] 2018-02-21 08:35
https://github.com/gorhill/uBlock/wiki/Deploying-uBlock-Origin

**Comment by gorhill** [comment] 2018-02-21 12:29
Duplicate of #2986, for solution see <https://github.com/gorhill/uBlock/issues/2986#issuecomment-364035002>.

**Closed by gorhill** 2018-02-21 12:29 UTC
Labels: duplicate
