### ISSUE TITLE
Kill Google Analytics on Firefox's "Get Add-ons" page

### ISSUE THREAD

**Issue by ub23** [gorhill/uBlock#2784] opened 2017-07-12 12:11 UTC
### Describe the issue
Firefox uses Google Analytics on their "Get Add-ons" page.

### One or more specific URLs where the issue occurs
about:addons and then go to "Get Add-ons"

### Screenshot in which the issue can be seen
See [here](https://twitter.com/NicolasPetton/status/884694176515936256) and [here](http://i.imgur.com/IgDka0U.png).

### Steps for anyone to reproduce the issue
1. Go to about:addons.
2. Click on the "Get Add-ons" entry in the left menu.
3. Observe that uBlock is disabled by default on that page and requests to google-analytics.com have been made.

### Your settings
- OS/version: Microsoft Windows 10 15063.413
- Browser/version: 54.0.1 (64-bit)
- uBlock Origin version: 1.13.4

##### Your filter lists
Default filter lists.

##### Your custom filters (if any)
None.

**Comment by gorhill** [comment] 2017-07-12 12:13
Duplicate of #2772.

**Closed by gorhill** 2017-07-12 12:13 UTC

**Comment by ub23** [comment] 2017-07-12 12:25
Thank you gorhill, whitelisting the about pages does seem reasonable, as they might indeed cause spurious breakage of other features.

The ball is clearly with Mozilla on this one. If someone finds this issue and is looking for more information, there is an issue open with Mozilla, available [here](https://github.com/mozilla/addons-frontend/issues/1107)

**Comment by ub23** [comment] 2017-07-12 12:31
By the way, if someone is using uMatrix, one can easily just block the about:addons page (and not the other about:* pages) by using the following rules:

```
matrix-off: about-scheme true
matrix-off: addons.about-scheme false
```

**Comment by gorhill** [comment] 2017-07-12 12:42
> using uMatrix, one can easily just block the about:addons page (and not the other about:* pages)

Yes, that is the problem with whitelisting directives in uBO, there is no precedence logic -- a precedence logic can't be implemented in uBO because the rules can use wildcards or be entirely regex-based.
