### ISSUE TITLE
Element picker works incorrectly on mail.com

### ISSUE THREAD

**Issue by hant0508-zz** [gorhill/uBlock#1744] opened 2016-06-21 15:53 UTC
### Describe the issue

uBlock can't pick many elements in your mail.com account (in sent, inbox etc). It work's correctly in header (`div id="navigator"`) but doesn't see elements in main body (`div id="application-canvas"`).
### Screenshot in which the issue can be seen

![2016-06-21 18-31-55](https://cloud.githubusercontent.com/assets/12861787/16235807/2d90336c-37e7-11e6-8e26-469beb9db45a.png)
### Steps for anyone to reproduce the issue
1. Visit [mail.com](https://www.mail.com/init)
2. Login with your e-mail/password or use this:  `ublock_element_picker@mail.com`;`ublock_element_p`
3. Try to pick any element with uBlock (e.g. blue animated smile)
### Your settings
- Browser/version: Mozilla Firefox 48.0a2 / Chromium 51.0.2704.79 on Debian GNU/Linux
- uBlock Origin version: 1.7.5rc7
### Your filter lists

It actually doesn't matter. You can test with your usual filter lists or with default lists and settings.

**Comment by gorhill** [comment] 2016-06-22 01:49
This is caused by the fact that the element picker does not "drill" into embedded frames. I am pretty sure an issue was opened about this a while ago, but I can't find it for now.

**Comment by hant0508** [comment] 2016-07-04 17:43
I don't sure that should open a new issue, however I've noticed it's sometimes impossible to select active (clickable) element to block with uBO element picker. If you click on the banner you want to pick you'll be redirected to advertiser page, so you can create neither blocking filter nor cosmetic one. This issue takes place only in Firefox, there's no such problem in Chromium-based browsers.

To reproduce the issue visit [ucheba-otziv.ru](http://ucheba-otziv.ru/) and try to pick flash-banner on the top (or right) of the page. Settings: uBlock Origin 1.7.7b10 with all defaults + RUS: RU AdList and Mozilla Firefox 49.0a2 (or latest release). 

![2016-07-04 20-11-01](https://cloud.githubusercontent.com/assets/12861787/16567427/c920963a-422f-11e6-8db9-731d203a8ba0.png)

**Comment by gorhill** [comment] 2016-07-04 17:50
Don't open a new issue for this, this is an issue specific to Flash elements with FF. Thta would be a duplicate of an issue I closed as "won't fix". I will let you find it.

**Comment by gorhill** [comment] 2016-07-04 18:03
Also, a good habit is to use click-to-play for Flash. This way the disabled Flash placeholder can be picked by uBO. Also, for the specific site you mention, I got the same exact ads, but gif-based instead of Flash-based -- so I could pick it with uBO.

**Comment by hant0508** [comment] 2016-07-04 21:17
You said about [this answer](https://github.com/gorhill/uBlock/issues/1310#issuecomment-176765845), I suppose. I understand your opinion about Flash and I completely agree with it, so I use click-to-play too. On that site I've click on it to ensure it's a banner and hide/block (I'm working on filter list in addition to RU AdList). Thanks for your answers:)

And one more strange issue I've noticed just now: logger doesn't provide information about filter `||et-code.ru^` from RU AdList. It reproduces specifically on this filter, I didn't see such behavior before with other filters. Moreover, if you subscribe from RU AdList, purge cache and add this filter in "My filters", it will be shown correctly in logger.

You can reproduce it [here](http://tivix.net/61-rossiya-1.html) with uBO default filter lists + RUS: RU AdList in both Firefox and Chrome. 

![2016-07-04 23-36-08](https://cloud.githubusercontent.com/assets/12861787/16569949/0b9c6f48-424e-11e6-8d9d-c503d17105d7.png)

**Comment by gorhill** [comment] 2016-07-04 22:55
> logger doesn't provide information about filter ||et-code.ru^ from RU AdList

I could reproduce. After investigation, I confirm this is a bug in the code. Can you open a new issue for this?

**Comment by hant0508** [comment] 2016-07-04 23:23
Ready: https://github.com/gorhill/uBlock/issues/1779

**Comment by gwarser** [comment] 2017-10-05 12:44
Duplicate https://github.com/chrisaljoudi/uBlock/issues/88

>This is caused by the fact that the element picker does not "drill" into embedded frames. I am pretty sure an issue was opened about this a while ago, but I can't find it for now.

**Closed** 2020-12-06 13:21 UTC
