### ISSUE TITLE
Mechanism to stub out third-party tracking JavaScript APIs

### ISSUE THREAD

**Issue by micolous** [gorhill/uBlock#3591] opened 2018-03-10 07:59 UTC
### Describe the issue

Some filters block out third-party tracking JavaScript.  Some websites have critical dependencies on these tracking systems, and return errors whenever they are blocked.  While this is not a good practise for reliability reasons, website operators will say "disable your blocker".

To work around this, uBlock Origin ships an "unbreak" list which only whitelists those sites:

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt

However, this is a case of whack-a-mole, at the expense of the users' preferences, as this results in the execution of tracking JavaScript, which is sub-optimal.

The filters are also inconsistent, some unblocking entire domains, some unblocking specific paths.  There's no standard mechanism applied for each tracker vendor.

It would be nice if there was a way a filter list could provide its own replacement for certain content.  This would allow it to serve up a different JavaScript, that implements stubs for the tracking JavaScript methods, and then pages wouldn't need to be whitelisted anymore.

I think this is possible with the [chrome.webRequest APIs](https://developer.chrome.com/extensions/webRequest).

This may also help with the anti-blocker scripts present on some sites, as it will be possible to make it look like the resource had loaded.

### One or more specific URLs where the issue occurs

Anything listed in: https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt

### Steps for anyone to reproduce the issue

1. Open a website listed in the "uBlock Unbreak" list.
2. Observe that third-party tracking JavaScript gets loaded.

### Your settings

- OS/version: Linux x86_64
- Browser/version: Chrome R65
- uBlock Origin version: v1.15.2

##### Your filter lists

Default + EasyPrivacy

**Comment by jspenguin2017** [comment] 2018-03-10 15:13
`$redirect=` does that, but to prevent people from shipping malware through filter lists, redirect target is restricted to the resource file. 

The problem is that it's quite hard to make a surrogate for every tracking script, uBO does replace big ones like Google Analytics.

**Comment by gorhill** [comment] 2018-03-10 20:44
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed** 2018-03-10 20:45 UTC
Labels: invalid
