### ISSUE TITLE
Unlock Origin Safari for Mac and IOS

### ISSUE THREAD

**Issue by Masterj2700** [gorhill/uBlock#1946] opened 2016-08-30 05:36 UTC
Are there any plans to allow Ublock Origin to work with safari for Mac and IOS?

**Comment by anewuser** [comment] 2016-08-30 05:44
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment] 2016-08-30 11:27
Duplicate of #1596

**Closed by gorhill** 2016-08-30 11:27 UTC
