### ISSUE TITLE
All filter subscriptions report "out of date" after browser restart

### ISSUE THREAD

**Issue by hubbathegit** [gorhill/uBlock#3699] opened 2018-04-10 19:14 UTC
### Describe the issue
1 - Filter update is manually performed, all subscriptions report successfully updated;
2 - Close and re-open browser, just seconds later;
3 - All filter subscriptions report "out of date";
4 - Repeat, same.

### Your settings

- OS/version: Windows 7 64-bit
- Browser/version: Firefox ESR 52.7.3 (same issue occurred in previous couple versions)
- uBlock Origin version: 1.15.24 (same issue occurred at least since previous version)

### Your filter lists

Default filter lists (tested with and without a couple of customs, the issue affects ALL subscriptions regardless)

**Comment by hubbathegit** [comment] 2018-04-10 23:41
No TOR; cookies and local storage disabled by default (although I don't see the connection, and if there is one, then it shouldn't be ?). Thanks.

**Comment by hubbathegit** [comment] 2018-04-11 15:59
Thanks for the info. 

Something definitely must have changed at some point, because I've used the same browser with cookies and local storage disabled by default for years, and have been using uBlock ever since (and ABP before it), and the issue I've reported here only began a few weeks ago - previously the filter update system worked just fine in all regards.

**Comment by gorhill** [comment] 2018-04-11 16:08
> same browser with both cookies and local storage disabled by default for years

The issue is with the webext version of uBO, not the legacy version. The webext version was first officially published in AMO in Fall of 2017, i.e. less than a year ago.

**Comment by hubbathegit** [comment] 2018-04-11 16:24
@gorhill - thank you for the extra info, that does shed more light into it. And renewed thanks for this little great extension. :+1:

**Comment by Thorin-Oakenpants** [comment] 2018-04-11 18:01
> thank you for the extra info

Didn't I already state that?
> This is a web extension. Web extensions require...

**Comment by gorhill** [comment] 2018-04-11 21:35
It's fixed in FF59: <https://bugzilla.mozilla.org/show_bug.cgi?id=1406675>.

**Comment by Thorin-Oakenpants** [comment] 2018-04-12 07:43
> But if I keep cookies disabled and add an exception for moz-extension://UUID as per Thorin's post (acceptable), the issue persists

Then you must be blocking IDB (I can't think of any other reason). Cookies control first party localStorage and IndexedDB. If you deny all cookies by default and use site exceptions then **there is no need** to disable the following two prefs in about:config

- `dom.indexedDB.enabled` - reset it to default true (besides, IDB is used internally by FF itself, and blocking this will throw console errors)
- `dom.storage.enabled` - reset it to default true

localStorage and IDB can be cleared on close - it is under the term OWD (Offline Website Data), which you can also do manually with Ctrl-Shift-Del (clear recent history). note: clearing OWD does not clear uBO's IDB data

**Closed** 2018-04-16 10:45 UTC
Labels: browser bug
