### ISSUE TITLE
Inconsistent messaging: uBO presented primarily as ad blocker in about:addons

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2451] opened 2017-03-13 17:17 UTC
### Describe the issue
@gorhill you've been careful in all messaging I had seen to describe uBO as a network filter / content blocker, not just an ad blocker. Since I'm sure this is deliberate I wanted to bring an inconsistency to your attention in case you wish to address it.

In Firefox `about:addons`, the addon is presented as primarily an adblocker
 
Title:
> Block Ads w/ uBlock Origin by Raymond Hill

Text:
> A lightweight and effective ad blocker. uBlock Origin enforces thousands of content filters without chewing up a bunch of memory.

### One or more specific URLs where the issue occurs
`about:addons` in Firefox

### Screenshot in which the issue can be seen
![8](https://cloud.githubusercontent.com/assets/12346501/23866398/1223e348-07ef-11e7-80a3-21548f06ef4d.png)

**Comment by gorhill** [comment] 2017-03-13 19:01
Duplicate of #2298.

**Closed by gorhill** 2017-03-13 19:01 UTC
