### ISSUE TITLE
Issues when migrating from 1.13.8 to 1.14.4 on Firefox 52.3ESR

### ISSUE THREAD

**Issue by dvdbane** [gorhill/uBlock#2992] opened 2017-09-09 10:13 UTC
### Describe the issue

1 - ublock logger doesn't show ff addon update connection (behind the scene)

Step to reproduce
1. Open logger > Behind the scene
2. Check for addon update using about:addons page
3. Nothing shown on logger

2 - by default, installing ublock 1.14.4 on ff 52.3esr, option for "Prevent WebRTC" not selected and disabled
when restore backup from 1.13.8 which the option can be selected and not disable, the option for "Prevent WebRTC" is selected but still disabled
based on issues #2853, ff 52.3esr does not support that option
is there any effect for enabling that option for ff52.3esr?

3 - Name for custom 3rd party filters not backup
can it be implemented

4 - Storage used: ? bytes
shown ? bytes even after restore backup from 1.13.8

### Your settings

- OS/version: Windows 8.1 x64
- Browser/version: FF52.3ESR x64
- uBlock Origin version: 1.14.4

already tested on new ff profile without addon

**Comment by gomoku** [comment] 2017-09-09 13:38
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)

Anyway: 
as for 3) a duplicate of https://github.com/gorhill/uBlock/issues/2501
as for 4) a duplicate of https://github.com/gorhill/uBlock/issues/2812

**Closed** 2017-09-09 14:11 UTC
Labels: duplicate, invalid
