### ISSUE TITLE
dynamic URL filtering + type matching

### ISSUE THREAD

**Issue by wavexx** [gorhill/uBlock#1280] opened 2016-01-22 21:45 UTC
youtube.com tries to connect to several googlevideo.com subdomains.
The following rule:

    www.youtube.com googlevideo.com * noop

would do, but I'd like to restrict requests only for certain types, such as images.
If I add the following rule though:

    www.youtube.com googlevideo.com image noop

the rule is simply removed from the temporary set (any type has the same effect).
Using an URL instead works as expected:

    www.youtube.com https://something.googlevideo.com image noop

except that it's useless in this case, as I would need to add an explicit rule for each pseudo-random googlevideo domain.

**Comment by gorhill** [comment] 2016-01-22 22:11
Duplicate of #1039.

**Closed** 2016-01-22 22:13 UTC

**Comment by wavexx** [comment] 2016-01-23 14:27
I was aware of #1039 but not #320. It's limiting that I can block on type using an URL pattern, but not using a domain destination (and the reason I filed both issues).

Allowing patterns in URLs would actually remove the need for this. Incidentally, with both being absent I'm forced to allow more than what I would using a domain destination, and then block specific requests (which is the exact opposite of what I'd like to do).

I see the argument for uMatrix, but I actually find the uBlock logger interface much easier to see what's going on, as I can preview some requests, so I've been using it almost exclusively to define rules lately.
