### ISSUE TITLE
Ajax Error 0

### ISSUE THREAD

**Issue by ibtrey** [gorhill/uBlock#2780] opened 2017-07-11 13:01 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

## Describe the issue
With this extension enabled in Firefox where the server is hosted on a Linux machine, 8/10 ajax requests return an error with the error message of 'error' and the statusCode of 0. Windows is fine.

## One or more specific URLs where the issue occurs
localhost website

### Steps for anyone to reproduce the issue

1. Create an ajax request
2. Enable the extension in your Firefox
3. Go to a CentOS-based server and try the ajax function

### Your settings

- OS/version: Windows 7 - local CentOS 7 - server
- Browser/version: Firefox Developer Edition/55.0b7
- uBlock Origin version: latest

**Comment by gorhill** [comment] 2017-07-11 13:11
Did you look at the logger to find out what uBO is doing with the network requests?

**Comment by gorhill** [comment] 2017-07-11 13:18
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

There is no hint you investigated first using the logger as requested in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md), so I will assume the issue is a filter one, until you make a better case that the issue is not a filter one.

**Closed by gorhill** 2017-07-11 13:18 UTC

**Comment by ibtrey** [comment] 2017-07-12 10:40
Hey sorry for delayed issue, and it blocks them. It treats the url like an ad, so it stops the post request
