### ISSUE TITLE
NSFW PornHub Thumbnails Issue: RESOLVED

### ISSUE THREAD

**Issue by jputting** [gorhill/uBlock#1902] opened 2016-08-15 20:18 UTC
Hi,
I just updated all my uBlock Filters and went to this PornHub webpage:
http://www.pornhub.com/

To my surprise NONE of the video thumbnails show the video duration anymore, They have always had the video duration placed at the bottom right hand corner of the video thumbnail.

I immediately thought of disabling all of My Filters, but that made no difference.

I checked the uBlock Pop Up domains and unblocked everything which could have caused this, but still no luck.

I then used the uBlock  Logger and reloaded that webpage, I created exception rules for everything that was clearly blocked and the problem persisted.

I then tried disabling the 3rd- Party Filters one at a time and reloading this webpage.

I discovered that when the uBlock Filters list is deactivated this issue vanished. When this list is activated this problem appears again.

I have tried everything I know to solve this, But I can not pin down what it is in that list which is causing this issue with the PornHub video thumbnails.

Any help solving this would be greatly appreciated.

**Comment by gorhill** [comment] 2016-08-15 21:25
Filter issues => uAssets -- as said at the top of CONTRIBUTING. Also, can't reproduce, tried with default settings on both Chrome 54 or Nightly.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment] 2016-08-15 21:38
Ok, never mind, I could reproduce, reverting bad "fix" in filter list.

**Comment by jputting** [comment] 2016-08-15 21:47
Hi gorhill,

 I can confirm that this issue is now resolved and will be editing the title of my post to reflect that.

Many, many thanks for looking into this and resolving this uBlock Filter issue so very rapidly.

**Closed** 2016-08-15 21:49 UTC
