### ISSUE TITLE
the extension is disabled in chrome

### ISSUE THREAD

**Issue by alphatr** [gorhill/uBlock#2722] opened 2017-06-21 07:14 UTC
### the extension is disabled in chrome

in chrome, For some reason the extension is disabled with a message "This extension may have been corrupted."

I reinstall the extension and still see it.

### Steps for anyone to reproduce the issue

I doesn't do anything, just update it to 1.13.0, in extension store other people is same.

### Your settings

- OS/version: Mac OS/10.12.5
- Browser/version: Chrome/ 59.0.3071.109
- uBlock Origin version: 1.13.0

**Comment by shinycake** [comment] 2017-06-21 07:20
I am experiencing the exact same issue.
I'd like to add that reinstalling Chrome did not solve it.

**Comment by SamaelQliphoth** [comment] 2017-06-21 07:28
I am also experiencing this issue since relaunching Chrome today. Repair did nothing, and clicking the "View in Store" option gave me this:

![ubo issue ss](https://user-images.githubusercontent.com/29592939/27372090-5d4c770a-5631-11e7-9838-2304519d82bc.png)

I clicked "Enable This Item" but it did nothing either. 

I've since re-enabled ABP for the tie bein until the issue is resolved.

OS: Windows 8.1
Browser: Chrome v59.0.3071.109
uBlock Origin Version: 1.130

**Comment by bershan2** [comment] 2017-06-21 07:31
I believe this exact issue was filed a bit earlier as #2720 _uBlock Origin 1.13.0 is disabled by Chrome_.

**Comment by CesarAxe** [comment] 2017-06-21 08:10
I have the same problem.
-Windows 10, Chrome 59.0.3071.104.

**Comment by uBlock-user** [comment] 2017-06-21 08:15
Yes lots of people seem to be having this issue on the stable and beta builds, so post here - #2720

**Comment by bershan2** [comment] 2017-06-21 08:16
@CesarAxe we should move discussion to issue 2720 linked above.
@alphatr Please close this issue, @michaelhood already figured out the problem in issue 2720.

**Closed** 2017-06-21 08:57 UTC
