### ISSUE TITLE
Installing uBlock Origin breaks Performance tool

### ISSUE THREAD

**Issue by derpyherp** [gorhill/uBlock#603] opened 2015-08-17 02:27 UTC
In a new Firefox 40.0.2 profile, pressed Shift+F5, "Start Recording Performance", browsed around a random website for ~15 seconds, pressed "Stop Recording Performance" - results show up pretty much instantly.

Installed uBlock Origin 1.0.0.1 and unchecked all 3rd-party filters just in case, did the same thing as before with the Performance tool. After pressing  "Stop Recording Performance" it gets stuck saying "Loading", and "X" to close the tool pane doesn't work.

If I disable uBlock Origin (grey icon) for the site I'm recording on that doesn't seem to help.

**Comment by gorhill** [comment] 2015-08-18 19:07
Not all the time, but I could reproduce, with these JS errors in the browser console:

    error occurred while processing 'getProfile: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    Stack: ProfilerActor.prototype.onGetProfile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/profiler.js:182:19
    DSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1456:15
    LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11
    makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
    makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
    Line: 182, column: 18 main.js:1328:0
    
    onPacket threw an exception: Error: Server did not specify an actor, dropping packet: {"error":"unknownError","message":"error occurred while processing 'getProfile: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data\nStack: ProfilerActor.prototype.onGetProfile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/actors/profiler.js:182:19\nDSC_onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/server/main.js:1456:15\nLocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11\nmakeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14\nmakeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14\nLine: 182, column: 18"}
    Stack: DebuggerClient.prototype.onPacket@resource://gre/modules/devtools/dbg-client.jsm:944:1
    LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:561:11
    makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
    makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:82:14
    Line: 944, column: 0

**Comment by gorhill** [comment] 2015-08-18 19:40
There is [bugzilla 1172157](https://bugzilla.mozilla.org/show_bug.cgi?id=1172157) which has the exact same output at the browser console. [Comment #5](https://bugzilla.mozilla.org/show_bug.cgi?id=1172157#c5) says:

> I wonder if it's bug 1167895.

[Bug 1167895](https://bugzilla.mozilla.org/show_bug.cgi?id=1167895) is about the profiler failing when there are functions with non-ASCII characters, and which actually uses uBlock as test case. That bug is marked `status-firefox41: fixed`.

I tried to reproduce using Nightly, and I could not reproduce. So I think it is safe to assume the underlying issue is [bugzilla 1167895](https://bugzilla.mozilla.org/show_bug.cgi?id=1167895), and it will be fixed in Firefox 41.

**Closed by gorhill** 2015-08-18 19:40 UTC
Labels: accepted

**Comment by gorhill** [comment] 2015-08-18 19:42
By the way, the test case I use was:

1. Go to <https://news.ycombinator.com/news>
1. Open dev console for that page
1. Click _Performance_ tool in dev console
1. Start profiling
1. Click the top link on <https://news.ycombinator.com/news>, let the page load completely, than go back to <https://news.ycombinator.com/news>
1. Repeat for the next 9 links
1. Stop the profiler

Results:

Profiling get stuck, and the above error messages in the browser console.
