### ISSUE TITLE
Please don't throw an Error when vAPI is not available

### ISSUE THREAD

**Issue by herrernst** [gorhill/uBlock#2565] opened 2017-04-27 07:29 UTC
### Describe the issue

I use Chrome for developing and debugging websites and thus always have developer tools open and breakpoint on exceptions enabled. If I am debugging websites with SVGs embedded as `<object>` I always get an exception at https://github.com/gorhill/uBlock/blob/64c92a96a3c56ffc2e8b263325e6ac85fe45ab96/src/js/contentscript.js#L90 which is very annoying and forces me to disable uBlock origin.
Please could you just log with `console.error()` instead or something like that? Thank you.

### One or more specific URLs where the issue occurs

https://rawgit.com/herrernst/cbe60ad2a20e539e266a05d9b64b26f1/raw/7fb184d1bcaf5fea8d39c49f5fe8605d8a28087b/svg-object.html

### Screenshot in which the issue can be seen

![screen shot 2017-04-27 at 09 10 46](https://cloud.githubusercontent.com/assets/20795/25472435/865fff4e-2b2b-11e7-81db-74cccd554f14.png)

### Steps for anyone to reproduce the issue

1. Open webpage with svg embedded as `<object>` with debugger enabled

### Your settings

- OS/version: macOS 10.12
- Browser/version: Chrome 58
- uBlock Origin version:  1.12.1

##### Your filter lists

default/unchanged

##### Your custom filters (if any)

none

**Comment by gorhill** [comment] 2017-04-27 11:09
Duplicate of #2029.

**Closed by gorhill** 2017-04-27 11:09 UTC
Labels: duplicate

**Comment by herrernst** [comment] 2017-04-27 12:47
Would it at least be possible to not throw the error when uBlock Origin is disabled for a site? Thanks

**Comment by gorhill** [comment] 2017-04-27 13:06
Content scripts are declared in the manifest and injected unconditionally by the browser. What would be nice is the chrome API allowing to declare document type filter options in the manifest.

**Comment by herrernst** [comment] 2017-04-27 13:47
OK, thanks nonetheless.

**Comment by gorhill** [comment] 2017-04-27 13:51
I do plan to do something about this, it's just a question of free time and I do not consider this an issue which is at the top of the list.

**Comment by herrernst** [comment] 2017-05-18 07:50
I found an obvious solution to not cause the debugger halt on this error: simply blackbox the content script!
