### ISSUE TITLE
HTTPS Everywhere 2018.2.26

### ISSUE THREAD

**Issue by Vidarius** [gorhill/uBlock#3639] opened 2018-03-24 17:56 UTC
HTTPS Everywhere 2018.2.26 dont work longer on chrome - uBlock, block it > options?

**Comment by Coverlin** [comment] 2018-03-24 18:47
For me it seems it's working as intended , both extensions
try force reloading the page Ctrl+Shift+R

**Comment by igormartimiano** [comment] 2018-03-24 18:49
Got a problem with them as well.
HTTPS Everywhere is currently trying to redirect https://www.google-analytics.com/analytics.js and I suppose uBlock does the same. Does anyone know what filter takes care of that on uBlock?
Error is as it follows: 
**Warning:**
This extension failed to redirect a network request to https://www.google-analytics.com/analytics.js because another extension (uBlock Origin) redirected it to chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/59fb24a2d12455d15bea20980e8a6801.javascript?secret=k3w31pnoge0l.

**Comment by zaphodbeebblebrox** [comment] 2018-03-24 20:43
This is an expected result. uBlock redirects google analytics to a stub script that stops some sites from breaking. Gorhill talks more about it in [this comment.](https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068)

**Comment by bluz71** [comment] 2018-03-25 03:34
This clash results in a highly visible `!` error indicator in the top right corner of Chrome.

In practicals land, for those of us who use both uBlock Origin and HTTPS Everywhere, what can we do to silence this error?

**Comment by bluz71** [comment] 2018-03-25 03:40
I suppose the order of installation matters, this is the case where HTTPS Everywhere is installed before uBlock Origin:

```
This extension failed to redirect a network request to 
chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/d363525161c56887ceebe5e72ed4ef31.javascript?secret=ggd92ckr1pfj 
because another extension (HTTPS Everywhere) redirected it to 
https://c.amazon-adsystem.com/aax2/amzn_ads.js.
```

**Comment by uBlock-user** [comment] 2018-03-25 09:11
> In practicals land, for those of us who use both uBlock Origin and HTTPS Everywhere, what can we do to silence this error?

Disable the redirect feature in either HTTPS Everywhere or uBlock Origin, otherwise this will not stop.

**Comment by gorhill** [comment] 2018-03-25 11:32
[Redirect conflict with uBlock Origin](https://github.com/EFForg/https-everywhere/issues/14961)

**Comment by bluz71** [comment] 2018-03-26 01:39
@gorhill,

Do you recommend I and others stop using HTTP Everywhere? 

Back in the day it served a real purpose, for example YouTube used to prefer plain over SSL. But here in 2018 that probably is not the case? Is it more hinderance than benefit?

**Comment by Hrxn** [comment] 2018-03-26 09:52
I, for one, would definitely recommend against using this extension.

You already stated the reason. HTTP/HTTPS "dual mode" is hardly a thing nowadays. And, again, if the server does not provide a secure connection the extension is pointless in any way.
And all of this for exposing user privacy by storing per URL settings in plain text? No, thanks.

**Comment by gorhill** [comment] 2018-03-26 10:49
I won't tell people what to do. I will tell what is happening, and from this people can decide for themselves. One of two cases can happens:

### uBO redirects first

Benign.

Typically the error message _"This extension failed to redirect a network request..."_ will be with HTTPS-Everywhere in the Extensions page (as reported in opening comment).

This won't affect the purpose of HTTPS-Everywhere -- because no network requests is fired to the outside world.

### HTTPS-Everywhere

Serious.

Typically the error message _"This extension failed to redirect a network request..."_ will be with uBlock Origin in the Extensions page.

This will prevent uBO from redirecting the network request to a local neutered resource, meaning a network request which was meant meant to be blocked by uBO would no longer be blocked.

### Considerations

The order in which the extensions were installed is what decide which extension will redirect first (I can't remember the order) -- so this means by re-installing one or the other you could more from the "serious" to the "benign" case.

Why is this error more widely reported now? I have no clue, uBO has been redirecting to neutered resources since a very long time now (see #1170). Somebody on HTTPS-Everywhere's issue tracker [pointed out](https://github.com/EFForg/https-everywhere/issues/14961#issuecomment-376106816) that something related to extension error was fixed in Chrome 65.

**Comment by Bisaloo** [comment] 2018-03-26 10:58
About the order in which you need to install extensions to choose which one redirects first:

> Only one extension is allowed to redirect a request or modify a header at a time. If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored. An extension is not notified if its instruction to modify or redirect has been ignored.

Source: https://developer.chrome.com/extensions/webRequest

**Comment by grenzor** [comment] 2018-03-26 11:05
I'm assuming this affects Firefox too, is there a Chrome extensions page equivalent to see which redirects first?

**Comment by gorhill** [comment] 2018-03-26 14:31
I corrected my assessment above. TL;DR: it's benign either way -- uBO will properly redirect to the local neutered resource. This may happen before or after HTTPS-Everywhere translate to `https:`, either way the end result is that the network request will be handled by uBO as expected.

**Comment by noblepirate** [comment] 2018-03-29 03:14
I have exactly the same problem as Igor described in https://github.com/gorhill/uBlock/issues/3639#issuecomment-375915949

uBlock conflicts with HTTPS everywhere to redirect https://www.google-analytics.com/analytics.js

**Comment by noblepirate** [comment] 2018-03-29 03:48
hmm.... https://bugs.chromium.org/p/chromium/issues/detail?id=800773

**Comment by pjc123** [comment] 2018-04-04 13:10
Same problem.  This didn't occur until recently.  I am getting an extension error for ublock.  Details:

`
This extension failed to redirect a network request to chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/web_accessible_resources/f6f25816c1c5ce3d465f4cd083539931.javascript?secret=sxbickgppwm9 because another extension (HTTPS Everywhere) redirected it to https://widgets.outbrain.com/outbrain.js.
`

**Comment by gorhill** [comment] 2018-04-04 13:16
Locking due to pointless "me too" noise.

Consider starring <https://bugs.chromium.org/p/chromium/issues/detail?id=111700#c31> if you want this to be fixed.

**Closed** 2018-04-24 09:48 UTC
