### ISSUE TITLE
Chrome background Gmail memory balloon

### ISSUE THREAD

**Issue by TinoDidriksen** [gorhill/uBlock#2147] opened 2016-11-12 11:50 UTC
### Steps
- Have multiple GMail tabs with separate accounts in the same Chrome window, but keep one in the background for several hours - never select this tab for hours.
- After a few hours, switch to the background tab.
- Note that it takes seconds for the page to respond to interactions or render any changes.
- Note that after those seconds, it goes back to being fully responsive, until the next wakeup.

### Description
I have Chrome open 24/7 with 7 separate Google Mail tabs open, one of which is in front and the rest are in the background. After hours of idleness, if I switch to one of the background tabs, it'll take several seconds to render any changes in the page since last it was in front. Once that delay is done, the page is otherwise fine, until the next time it's been in the background for a while. With uBlock disabled for the mail.google.com domain, the issue completely goes away.

I just woke up, so the tabs had been backgrounded for ~8 hours, and this is what task manager showed for their memory use: ![gmail-idles](https://cloud.githubusercontent.com/assets/5411013/20237442/ccf1ce50-a8d2-11e6-97c2-11d520016ca3.png)

Without uBlock, the tabs hover around 160MB RAM. The active tab is not affected. It's as if uBlock prevents background GMail tabs from reducing their memory and thus they get swapped out. When I do activate the tabs, they reduce their memory usage to the expected amount within a few minutes.

I thought it had to do with dynamic updates, but I also have background Facebook and Google Analytics tabs, and those are not affected, so something in how GMail works is just incompatible with uBlock.

Also only in Chrome - I tried the same in Firefox (without electrolysis, so single process), and I could not reproduce the issue. But in Chrome, I can 100% reproduce it.

### Sysinfo
- Windows 10 Enterprise 64bit (quad-core i7, 16 GB RAM, 1 TB SSD)
- Chrome 54.0.2840.71
- uBlock Origin v1.9.16
- Default uBlock settings used.

### Chrome extensions
- Application Launcher for Drive (by Google)
- Go Back with Backspace
- Google Docs Offline
- Mailvelope
- uBlock Origin

**Comment by gorhill** [comment] 2016-11-12 12:07
Do you receive a lot of emails in these accounts? If so, I won't be able to reproduce to investigate as I have only a throwaway account with no activity in it.

The content script for Chrome and Firefox is the same, this suggests more of a different behavior internally with Chrome vs. Firefox.

Of interest, you say that bringing up the tab causes the memory to be apparently garbage collected. There is no code in the content script which care about whether the tab is active or not. But this makes me wonder... uBO's content script does use [`window.requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), and I am wondering if with Chrome, the firing of animation frames is suspended when a tab is inactive. If so, this could cause the behavior your are seeing.

**Comment by TinoDidriksen** [comment] 2016-11-12 12:53
The background accounts are not very active. They're just forwards to my main account, and kept open on the Spam folder just to check that things aren't held there. I see 0-4 mails in each spam folder after a night, and the same issue whether there were 0 or 4 mails, so number of mails seems to not matter.

But if it was about `requestAnimationFrame`, I'd expect that to affect Facebook and Analytics much harder.

I'll try a binary search with my other extensions disabled, just to rule out some interaction with them.

**Comment by gorhill** [comment] 2016-11-12 12:54
Given that it is my best guest as to what could be happening, I will modify slightly the content script code and assume that the callback passed to `window.requestFrameAnimation` may happen to take very long to be called -- at the browser's discretion.

Would you be willing to try the dev version of uBO to see if the changes help with this issue?

**Comment by gorhill** [comment] 2016-11-12 12:57
> I see 0-4 mails in each spam folder after a night, and the same issue whether there were 0 or 4 mails, so number of mails seems to not matter.

Ok, I open this throwaway account in one tab and opened another tab and I will wait a while to see what happens. Currently the tab is sitting at 240 MB.

**Comment by gorhill** [comment] 2016-11-12 14:21
This is the [documentation on MDN re `requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) (my emphasis):

> The number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation. **The callback rate may be reduced to a lower rate when running in background tabs or in hidden `<iframe>`s** in order to improve performance and battery life.

This is what made me pick `requestAnimationFrame` for callback purpose over `setTimeout` originally -- this makes uBO's content script run more efficiently, i.e. doing work ASAP when running in currently active tab, while working in a CPU-friendly falshion for non-visible tabs.

Now, I found this Chromium issue -- the issue you observe could be related to that issue: [empty requestAnimationFrame() callback leaks memory](https://bugs.chromium.org/p/chromium/issues/detail?id=640578).

**Comment by gorhill** [comment] 2016-11-12 18:08
Ok, I confirm that `requestAnimationFrame` callbacks are not triggered when a tab is not active (or maybe just not visible) with Chromium and _maybe_ also Firefox, this is true for at least 15 minutes -- I won't really bother trying to figure is the suspend time is forever. For Firefox, I say "maybe" because I saw a progression in the suspend time, which make me suspect they do end up executing the callback, but at an ever increasing delay, possibly up to a max.

I didn't expect this given `requestAnimationFrame`'s documentation. I will provide a fix for this asap, which will consist to just have a fallback timer for when the callback to `requestAnimationFrame` has not been processed for a very long time (I picked 15 minutes currently). So uBO still benefit from the `requestAnimationFrame`'s virtuous behavior of being gentle with saving CPU cycles (and battery life), but will ensure that uBO's content script is not growing unduly its content script queues by never processing their content.

**Closed** 2016-11-12 18:38 UTC

**Comment by TinoDidriksen** [comment] 2016-11-13 08:50
After another night of idleness, but this time with Mailvelope disabled, the issue did not appear. I've looked at the timeline debugger, and Mailvelope inspects the DOM every 2 seconds, I presume to look for texts it can encrypt/decrypt.

So, Mailvelope + uBlock is the bad combination. I'll see if it still happens with the new version.

**Comment by gorhill** [comment] 2016-11-13 13:38
> So, Mailvelope + uBlock is the bad combination. I'll see if it still happens with the new version.

I left my Gmail account opened overnight as a background tab, with the fixes above, and all is fine on my side. It could be that Mailvelope causes the DOM to be modified much more often, causing uBO's internal queues to fill up much more faster. I am assuming this is a Chrome store extension -- I will download it and try to find out what it does to the DOM.
