### ISSUE TITLE
Firefox Menu Bar Problem OSX

### ISSUE THREAD

**Issue by mtothefckngs** [gorhill/uBlock#944] opened 2015-11-16 13:58 UTC
Dear Mr. Hill,
I noticed that when uBlock Origin is activated, after some time the **Firefox** entry in the menu bar stops working. For example, I can't use neither the cmd + , shortcut for accessing preferences nor access the preferences by clicking. This concerns only the **Firefox** entry in the menu bar. Other entries are not affected. This problem stops when i deactivate uBlock.
System: Firefox 42 on OSX 10.10.5, no other addons active.
Kind regards!

**Comment by gorhill** [comment] 2015-11-16 14:06
Quite probably duplicate of <https://github.com/gorhill/uBlock/issues/737#issuecomment-149257652>.

**Closed by gorhill** 2015-11-16 14:06 UTC
