### ISSUE TITLE
Add by default 3rd-party filter lists: NoCoin adblock list

### ISSUE THREAD

**Issue by MS-PC** [gorhill/uBlock#3680] opened 2018-04-06 05:16 UTC
They could add the anti-mining cryptocurrency filter by default in the "3rd-party filter" list. Please thanks.
Reference: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://github.com/hoshsadiq/adblock-nocoin-list

**Comment by WowDude** [comment] 2018-04-06 06:13
Duplicate of https://github.com/gorhill/uBlock/issues/3511.  Also can check these as well: https://github.com/gorhill/uBlock/issues/3407, https://github.com/gorhill/uBlock/issues/3600

**Comment by KonoromiHimaries** [comment] 2018-04-07 03:13
it is worth adding this list because it is very popular

instead of a CoinBlockerLists
https://github.com/gorhill/uBlock/issues/3600

**Comment by okiehsch** [comment] 2018-04-07 03:31
And basically nobody knows that `EasyPrivacy` also includes a ton of anti-mining filters.

**Closed as completed** 2018-04-07 22:18 UTC
