### ISSUE TITLE
Groupon loads slowly "waiting for uBlock Origin"

### ISSUE THREAD

**Issue by Royal2000H** [gorhill/uBlock#2462] opened 2017-03-19 23:15 UTC
### Describe the issue
Groupon.com loads very slowly. The barebones site loads then hangs then slowly gets filled with pictures. One time Chrome's status bar showed something like "waiting for uBlock Origin" (paraphrasing because I don't remember - unable to reliably reproduce the status message). Loading in incognito loads quickly.

Opening the logger shows a ton of `||groupon.*/tracky$xmlhttprequest`, as seen in this screenshot:
![image](https://cloud.githubusercontent.com/assets/822546/24085672/4f769740-0cd6-11e7-88d4-6352a7af2c40.png)
Which may be why I get such a slowdown. There's so many lines of it. I found this specific line comes from EasyPrivacy

So I tried adding the following:
`@@||groupon.*/tracky$xmlhttprequest`
but now I just get the same logger with a ton of green `@@||groupon.*/tracky$xmlhttprequest` instead of a ton of red `||groupon.*/tracky$xmlhttprequest` and still loads slowly.

### One or more specific URLs where the issue occurs

https://www.groupon.com/

### Steps for anyone to reproduce the issue

Open https://www.groupon.com/
Wait and wait
(Optionally open Logger)

### Your settings

- Browser/version: Chrome Version 56.0.2924.87
- uBlock Origin version: 1.11.4

##### Your filter lists

uBlock filters, uBlock filters - Badware risks, uBlock filters - Privacy, uBlock filters - Unbreak, Anti-Adblock Killer | Reek, EasyList, EasyPrivacy, Malware Domains List, Malware domans, Malware filter list by Diconnect, Peter Lowe's Ad and tracking server list

##### Your custom filters (if any)
ebates and topcashback unblocking filter subscriptions

**Comment by okiehsch** [comment] 2017-03-19 23:50
Delete cookies then reload `https://www.groupon.com`, is it still loading slowly?

**Comment by gorhill** [comment] 2017-03-20 11:06
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-03-20 11:06 UTC
Labels: filter list issue, invalid

**Comment by joshka** [comment] 2017-06-18 23:50
Hi @gorhill,

I'm not the OP, but the description match my observations. Commenting here rather than duplicating.

I deleted my cookies and reloaded. Problem persists.

Chrome 58
ublock 1.12.4.
All default setup, nothing custom

**Comment by joshka** [comment] 2017-06-18 23:58
OS: macOS Sierra
URL: https://www.groupon.com/deals/lunchbox-laboratory-seattle-2/
Symptoms: non-responsive page, high CPU usage locking up other pages in chrome

**Comment by marco-c** [comment] 2017-07-11 23:10
I can reproduce in Firefox too. Here's a profile: https://perfht.ml/2sNCoC2.

**Comment by marco-c** [comment] 2017-07-11 23:12
Could it be related to local storage?

**Comment by gorhill** [comment] 2017-07-12 13:02
I can't reproduce the issue, and from, the logger output in OP, this is a filter list issue, not a uBO issue: some sites may end up misbehaving as a result of blocking some of their stuff. If the issue is same as in OP, try this custom filter and see if the issue goes away:

    @@||groupon.com/tracky$first-party,xmlhttprequest

**Comment by marco-c** [comment] 2017-07-12 13:22
> try this custom filter and see if the issue goes away

No, I can still reproduce.

**Comment by gorhill** [comment] 2017-07-12 13:26
Fomr your <https://perfht.ml/2sNCoC2>, I see a lot of time is in some `set`, `getAll` javascript functions in the <https://www2.grouponcdn.com/layout/assets/ls-core-v6.0-ef6a851a75.js>. This appears to be related to localStorage and/or cookies.

**Comment by gorhill** [comment] 2017-07-12 13:29
What happens if you disable _"Accept cookies from sites"_ in Firefox? (just curious). Not sure if this would require a restart. Are you logged in on that site? Is this a requirement to reproduce the issue?

**Comment by gorhill** [comment] 2017-07-12 13:32
> I see a lot of time is in some `set`, `getAll` javascript functions in the `https://www2.grouponcdn.com/layout/assets/ls-core-v6.0-ef6a851a75.js` script

![a](https://user-images.githubusercontent.com/585534/28120067-fb802d5e-66e4-11e7-9c9b-f5cce7b6aa60.png)

**Comment by marco-c** [comment] 2017-07-12 13:33
> This appears to be related to localStorage and/or cookies.

The C++ part of the profile definitely does seem to spend a lot of time with localStorage-related activity.

**Comment by marco-c** [comment] 2017-07-12 13:37
> What happens if you disable "Accept cookies from sites" in Firefox?

It fixes the issue. I guess it's actually cookies then and not localstorage.

> Are you logged in on that site? Is this a requirement to reproduce the issue?

No, I'm not logged-in.

**Comment by marco-c** [comment] 2017-07-12 13:38
> It fixes the issue. I guess it's actually cookies then and not localstorage.

Or disabling cookies also disables localstorage.

**Comment by gorhill** [comment] 2017-07-12 13:45
> Or disabling cookies also disables localstorage.

Pretty it does, I remember there was an issue on bugzilla (now fixed) to also forbid with 3rd-party localStorage when 3rd-party cookies where forbidden.

**Comment by gorhill** [comment] 2017-07-12 13:51
I still can't reproduce on my side. If the issue can occurs with uBO only, presumably something is being blocked which affect a code path in a `groupon.com` script.

I do have a burst of blocked network requests to `https://www.groupon.com/tracky` (~10) when I open the page, but nothing like the logger output in OP. If I could reproduce I would start to whitelist some domains one by one until the issue stops manifesting. First to try is to whitelist `groupon.com` itself -- using an "allow" rule for `groupon.com` in the dynamic filtering makes this easy.

**Comment by marco-c** [comment] 2017-07-12 13:56
Actually, I've just noticed that I can reproduce the issue even if I disable the addon... I can't reproduce in a clean Firefox profile, but I can reproduce in my daily profile even if uBlock is disabled.

**Comment by gorhill** [comment] 2017-07-12 14:02
I have Firefox/Nightly set to remove all cookies when I quit. Is this your case?

**Comment by marco-c** [comment] 2017-07-12 14:06
> I have Firefox/Nightly set to remove all cookies when I quit. Is this your case? I also forbid 3rd-party cookies.

I forbid 3rd-party cookies, but I don't remove the cookies when I quit.
