### ISSUE TITLE
This extension failed to redirect a network request

### ISSUE THREAD

**Issue by Jimbazuka** [gorhill/uBlock#3521] opened 2018-02-16 11:24 UTC
### Describe the issue

Latest Chrome Browser (Version 64.0.3282.167 (Official Build) (64-bit) Windows 7 SP1 x64

Warning:
This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIHA7CgkvLyBodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlLmNvbS9kb3VibGVjbGljay1ncHQvcmVmZXJlbmNlCgl2YXIgbm9vcGZuID0gZnVuY3Rpb24oKSB7CgkJOwoJfS5iaW5kKCk7Cgl2YXIgbm9vcHRoaXNmbiA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiB0aGlzOwoJfTsKCXZhciBub29wbnVsbGZuID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIG51bGw7Cgl9OwoJdmFyIG5vb3BhcnJheWZuID0gZnVuY3Rpb24oKSB7CgkJcmV0dXJuIFtdOwoJfTsKCXZhciBub29wc3RyZm4gPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gJyc7Cgl9OwoJLy8KCXZhciBjb21wYW5pb25BZHNTZXJ2aWNlID0gewoJCWFkZEV2ZW50TGlzdGVuZXI6IG5vb3B0aGlzZm4sCgkJZW5hYmxlU3luY0xvYWRpbmc6IG5vb3BmbiwKCQlzZXRSZWZyZXNoVW5maWxsZWRTbG90czogbm9vcGZuCgl9OwoJdmFyIGNvbnRlbnRTZXJ2aWNlID0gewoJCWFkZEV2ZW50TGlzdGVuZXI6IG5vb3B0aGlzZm4sCgkJc2V0Q29udGVudDogbm9vcGZuCgl9OwoJdmFyIFBhc3NiYWNrU2xvdCA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglwID0gUGFzc2JhY2tTbG90LnByb3RvdHlwZTsKCXAuZGlzcGxheSA9IG5vb3BmbjsKCXAuZ2V0ID0gbm9vcG51bGxmbjsKCXAuc2V0ID0gbm9vcHRoaXNmbjsKCXAuc2V0Q2xpY2tVcmwgPSBub29wdGhpc2ZuOwoJcC5zZXRUYWdGb3JDaGlsZERpcmVjdGVkVHJlYXRtZW50ID0gbm9vcHRoaXNmbjsKCXAuc2V0VGFyZ2V0aW5nID0gbm9vcHRoaXNmbjsKCXAudXBkYXRlVGFyZ2V0aW5nRnJvbU1hcCA9IG5vb3B0aGlzZm47Cgl2YXIgcHViQWRzU2VydmljZSA9IHsKCQlhZGRFdmVudExpc3RlbmVyOiBub29wdGhpc2ZuLAoJCWNsZWFyOiBub29wZm4sCgkJY2xlYXJDYXRlZ29yeUV4Y2x1c2lvbnM6IG5vb3B0aGlzZm4sCgkJY2xlYXJUYWdGb3JDaGlsZERpcmVjdGVkVHJlYXRtZW50OiBub29wdGhpc2ZuLAoJCWNsZWFyVGFyZ2V0aW5nOiBub29wdGhpc2ZuLAoJCWNvbGxhcHNlRW1wdHlEaXZzOiBub29wZm4sCgkJZGVmaW5lT3V0T2ZQYWdlUGFzc2JhY2s6IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFBhc3NiYWNrU2xvdCgpOyB9LAoJCWRlZmluZVBhc3NiYWNrOiBmdW5jdGlvbigpIHsgcmV0dXJuIG5ldyBQYXNzYmFja1Nsb3QoKTsgfSwKCQlkaXNhYmxlSW5pdGlhbExvYWQ6IG5vb3BmbiwKCQlkaXNwbGF5OiBub29wZm4sCgkJZW5hYmxlQXN5bmNSZW5kZXJpbmc6IG5vb3BmbiwKCQllbmFibGVTaW5nbGVSZXF1ZXN0OiBub29wZm4sCgkJZW5hYmxlU3luY1JlbmRlcmluZzogbm9vcGZuLAoJCWVuYWJsZVZpZGVvQWRzOiBub29wZm4sCgkJZ2V0OiBub29wbnVsbGZuLAoJCWdldEF0dHJpYnV0ZUtleXM6IG5vb3BhcnJheWZuLAoJCWdldFRhcmdldGluZzogbm9vcGZuLAoJCWdldFRhcmdldGluZ0tleXM6IG5vb3BhcnJheWZuLAoJCWdldFNsb3RzOiBub29wYXJyYXlmbiwKCQlyZWZyZXNoOiBub29wZm4sCgkJc2V0OiBub29wdGhpc2ZuLAoJCXNldENhdGVnb3J5RXhjbHVzaW9uOiBub29wdGhpc2ZuLAoJCXNldENlbnRlcmluZzogbm9vcGZuLAoJCXNldENvb2tpZU9wdGlvbnM6IG5vb3B0aGlzZm4sCgkJc2V0Rm9yY2VTYWZlRnJhbWU6IG5vb3B0aGlzZm4sCgkJc2V0TG9jYXRpb246IG5vb3B0aGlzZm4sCgkJc2V0UHVibGlzaGVyUHJvdmlkZWRJZDogbm9vcHRoaXNmbiwKCQlzZXRTYWZlRnJhbWVDb25maWc6IG5vb3B0aGlzZm4sCgkJc2V0VGFnRm9yQ2hpbGREaXJlY3RlZFRyZWF0bWVudDogbm9vcHRoaXNmbiwKCQlzZXRUYXJnZXRpbmc6IG5vb3B0aGlzZm4sCgkJc2V0VmlkZW9Db250ZW50OiBub29wdGhpc2ZuLAoJCXVwZGF0ZUNvcnJlbGF0b3I6IG5vb3BmbgoJfTsKCXZhciBTaXplTWFwcGluZ0J1aWxkZXIgPSBmdW5jdGlvbigpIHsKCQk7Cgl9OwoJcCA9IFNpemVNYXBwaW5nQnVpbGRlci5wcm90b3R5cGU7CglwLmFkZFNpemUgPSBub29wdGhpc2ZuOwoJcC5idWlsZCA9IG5vb3BudWxsZm47Cgl2YXIgU2xvdCA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglwID0gU2xvdC5wcm90b3R5cGU7CglwLmFkZFNlcnZpY2UgPSBub29wdGhpc2ZuOwoJcC5jbGVhckNhdGVnb3J5RXhjbHVzaW9ucyA9IG5vb3B0aGlzZm47CglwLmNsZWFyVGFyZ2V0aW5nID0gbm9vcHRoaXNmbjsKCXAuZGVmaW5lU2l6ZU1hcHBpbmcgPSBub29wdGhpc2ZuOwoJcC5nZXQgPSBub29wbnVsbGZuOwoJcC5nZXRBZFVuaXRQYXRoID0gbm9vcGFycmF5Zm47CglwLmdldEF0dHJpYnV0ZUtleXMgPSBub29wYXJyYXlmbjsKCXAuZ2V0Q2F0ZWdvcnlFeGNsdXNpb25zID0gbm9vcGFycmF5Zm47CglwLmdldERvbUlkID0gbm9vcHN0cmZuOwoJcC5nZXRTbG90RWxlbWVudElkID0gbm9vcHN0cmZuOwoJcC5nZXRTbG90SWQgPSBub29wdGhpc2ZuOwoJcC5nZXRUYXJnZXRpbmcgPSBub29wYXJyYXlmbjsKCXAuZ2V0VGFyZ2V0aW5nS2V5cyA9IG5vb3BhcnJheWZuOwoJcC5zZXQgPSBub29wdGhpc2ZuOwoJcC5zZXRDYXRlZ29yeUV4Y2x1c2lvbiA9IG5vb3B0aGlzZm47CglwLnNldENsaWNrVXJsID0gbm9vcHRoaXNmbjsKCXAuc2V0Q29sbGFwc2VFbXB0eURpdiA9IG5vb3B0aGlzZm47CglwLnNldFRhcmdldGluZyA9IG5vb3B0aGlzZm47CgkvLwoJdmFyIGdwdCA9IHdpbmRvdy5nb29nbGV0YWcgfHwge307Cgl2YXIgY21kID0gZ3B0LmNtZCB8fCBbXTsKCWdwdC5hcGlSZWFkeSA9IHRydWU7CglncHQuY21kID0gW107CglncHQuY21kLnB1c2ggPSBmdW5jdGlvbihhKSB7CgkJdHJ5IHsKCQkJYSgpOwoJCX0gY2F0Y2ggKGV4KSB7CgkJfQoJCXJldHVybiAxOwoJfTsKCWdwdC5jb21wYW5pb25BZHMgPSBmdW5jdGlvbigpIHsgcmV0dXJuIGNvbXBhbmlvbkFkc1NlcnZpY2U7IH07CglncHQuY29udGVudCA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gY29udGVudFNlcnZpY2U7IH07CglncHQuZGVmaW5lT3V0T2ZQYWdlU2xvdCA9IGZ1bmN0aW9uKCkgeyByZXR1cm4gbmV3IFNsb3QoKTsgfTsKCWdwdC5kZWZpbmVTbG90ID0gZnVuY3Rpb24oKSB7IHJldHVybiBuZXcgU2xvdCgpOyB9OwoJZ3B0LmRlc3Ryb3lTbG90cyA9IG5vb3BmbjsKCWdwdC5kaXNhYmxlUHVibGlzaGVyQ29uc29sZSA9IG5vb3BmbjsKCWdwdC5kaXNwbGF5ID0gbm9vcGZuOwoJZ3B0LmVuYWJsZVNlcnZpY2VzID0gbm9vcGZuOwoJZ3B0LmdldFZlcnNpb24gPSBub29wc3RyZm47CglncHQucHViYWRzID0gZnVuY3Rpb24oKSB7IHJldHVybiBwdWJBZHNTZXJ2aWNlOyB9OwoJZ3B0LnB1YmFkc1JlYWR5ID0gdHJ1ZTsKCWdwdC5zZXRBZElmcmFtZVRpdGxlID0gbm9vcGZuOwoJZ3B0LnNpemVNYXBwaW5nID0gZnVuY3Rpb24oKSB7IHJldHVybiBuZXcgU2l6ZU1hcHBpbmdCdWlsZGVyKCk7IH07Cgl3aW5kb3cuZ29vZ2xldGFnID0gZ3B0OwoJd2hpbGUgKCBjbWQubGVuZ3RoICE9PSAwICkgewoJCWdwdC5jbWQucHVzaChjbWQuc2hpZnQoKSk7Cgl9Cn0pKCk7 because another extension (Ghostery – Privacy Ad Blocker) redirected it to data:application/javascript;base64,dmFyIGdvb2dsZXRhZz17fTtnb29nbGV0YWcuYWRzUmVuZGVyZWRJbmZvPXtnZXQ6ZnVuY3Rpb24oKXt9LHNldDpmdW5jdGlvbigpe319O2dvb2dsZXRhZy5jbWQ9e307Z29vZ2xldGFnLmNtZC5wdXNoPWZ1bmN0aW9uKCl7fTtnb29nbGV0YWcuZW5hYmxlU2VydmljZXM9ZnVuY3Rpb24oKXt9O2dvb2dsZXRhZy5kZWZpbmVTbG90PWZ1bmN0aW9uKCl7cmV0dXJuIGdvb2dsZXRhZ307Z29vZ2xldGFnLmFkZFNlcnZpY2U9ZnVuY3Rpb24oKXtyZXR1cm4gZ29vZ2xldGFnfTtnb29nbGV0YWcuY29tcGFuaW9uQWRzPWZ1bmN0aW9uKCl7cmV0dXJuIGdvb2dsZXRhZ307Z29vZ2xldGFnLnB1YmFkcz1mdW5jdGlvbigpe3JldHVybiBnb29nbGV0YWd9O2dvb2dsZXRhZy5yZWZyZXNoPWZ1bmN0aW9uKCl7fTtnb29nbGV0YWcuZGVmaW5lT3V0T2ZQYWdlU2xvdD1mdW5jdGlvbigpe307Z29vZ2xldGFnLnNldFRhcmdldGluZz1mdW5jdGlvbigpe307Z29vZ2xldGFnLmRpc3BsYXk9ZnVuY3Rpb24oKXt9O2dvb2dsZXRhZy5zZXRSZWZyZXNoVW5maWxsZWRTbG90cz1mdW5jdGlvbigpe307Z29vZ2xldGFnLmVuYWJsZUFzeW5jUmVuZGVyaW5nPWZ1bmN0aW9uKCl7fTtnb29nbGV0YWcuZW5hYmxlU3luY1JlbmRlcmluZz1mdW5jdGlvbigpe307Z29vZ2xldGFnLmVuYWJsZVNpbmdsZVJlcXVlc3Q9ZnVuY3Rpb24oKXt9O2dvb2dsZXRhZy5jb2xsYXBzZUVtcHR5RGl2cz1mdW5jdGlvbigpe307.

### Screenshot in which the issue can be seen
![2018-02-16 03_13_32-extensions](https://user-images.githubusercontent.com/7934633/36305437-6e07881a-12c8-11e8-9998-190a81ef3f8b.jpg)

### Steps for anyone to reproduce the issue

Not sure. Warning appeared while normal surfing web.

### Your settings

- OS/version:  Windows 7 SP1 x64
- Browser/version:  Latest Chrome Browser (Version 64.0.3282.167 (Official Build) (64-bit) 
- uBlock Origin version:  1.15.2

##### Your filter lists
NONE

##### Your custom filters (if any)
NONE

**Comment by Jimbazuka** [comment] 2018-02-16 11:30
I realize Ghostery interfered with Ublock Origin. The reason I have BOTH installed is based on Consumer Reports recommendation https://www.consumerreports.org/digital-security/to-protect-against-websites-that-spy-on-you-get-an-adblocker/ which is basedon SBA Research recommendation....

**Comment by gorhill** [comment] 2018-02-16 11:52
Duplicate of #1170.

**Closed by gorhill** 2018-02-16 11:52 UTC
Labels: duplicate

**Comment by Hrxn** [comment] 2018-02-16 12:31
Just ditch Ghostery, I'm serious..

**Comment by uBlock-user** [comment] 2018-02-16 16:18
Ghostery collects data and sells to advertizers, so it's not worth it. The recommendation is misleading and incorrect.
