### ISSUE TITLE
Advace setting don't presist from update to update

### ISSUE THREAD

**Issue by troysjanda** [gorhill/uBlock#3327] opened 2017-12-08 02:39 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
I noticed that the advance settings do not presist from update to update. I use a custom userResourcesLocation and I have to reapply the url after each update. not sure if this is by design or not

### One or more specific URLs where the issue occurs
non site specific
[URL(s) for issue on a specific site are **mandatory**]
non site specific
### Screenshot in which the issue can be seen
not able to take screen
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible: set userResourcesLocation and update ublock 
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
default
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: FF 57
- uBlock Origin version: v1.14.21rc2

##### Your filter lists
default
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none

**Comment by gorhill** [comment] 2017-12-08 02:49
Duplicate of #3085.

**Closed** 2017-12-08 02:50 UTC

**Comment by uBlock-user** [comment] 2017-12-11 19:29
@gorhill I'm having the same issue with `Block CSP reports` on Chromium. It was activated on dev build and as soon as the the build got updated from web store, the setting was lost and I had to activate again.

**Comment by gorhill** [comment] 2017-12-11 21:28
Unable to reproduce: I changed the setting, forced a restart of the extension (equivalent to an update) and the setting was still in its last changed state.

**Comment by uBlock-user** [comment] 2017-12-12 05:04
Try to reproduce it when another update comes off from web store, I will report back if it still happens on the next update.

**Comment by gorhill** [comment] 2017-12-12 13:12
> Try to reproduce it when another update comes off from web store

If this really causes an issue, then it is a browser bug, uBO's job is to merely use the API to save its settings, which it does. If the browser does not flush to disk afterward when an update occur, this is a browser issue.

**Comment by uBlock-user** [comment] 2017-12-12 16:14
But it only happened for that single setting, I doubt that to be browser bug otherwise it would have affected all other settings.
