### ISSUE TITLE
Dynamic thumbnails inside products list aren't shown in Allegro.pl 

### ISSUE THREAD

**Issue by Mati365** [gorhill/uBlock#785] opened 2015-10-05 10:24 UTC
![9a5fee74-674f-11e5-907a-1ecac2663df8](https://cloud.githubusercontent.com/assets/3949262/10278243/05b55708-6b5c-11e5-88e0-b7eba18fdc21.png)
Without "ublock" everything is working correctly:
![ebcb4f42-674f-11e5-827a-dfb2972ac57f](https://cloud.githubusercontent.com/assets/3949262/10278246/08658b08-6b5c-11e5-947f-1681f7d7ab29.png)

**Comment by harshanvn** [comment] 2015-10-05 12:12
its always better to put the direct url in question in the post...for the sake of convenience, i am adding it here..

http://allegro.pl/osobowe-renault-4047?proce_to=7000&state=16

I am not able to reproduce the issue. Please show what filter lists has been selected? And version?

**Comment by zummuz** [comment] 2015-10-05 12:26
@Mati365 
Have you tried @@||staticpics2.allegrostatic.pl/adverts/otomoto_pl$image,domain=allegro.pl like I suggested in https://github.com/chrisaljoudi/uBlock/issues/1552?

**Comment by gorhill** [comment] 2015-10-05 12:35
Marked as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by zummuz** [comment] 2015-10-05 14:40
firefox 34.0.5 (portable)
uBlock 1.1.1 all standard filter lists except regional (no regional at all), no dynamic filtering, no user rules
Half of car previews are not loaded
![blocked](https://cloud.githubusercontent.com/assets/13698274/10283081/a00302d6-6b86-11e5-8012-e9b40b7364ba.png)
After @@||staticpics2.allegrostatic.pl/adverts/otomoto_pl$image,domain=allegro.pl there are few car previews still not loaded (one have no photo, three others on click lead to different site than the others which are loaded). No blocked images left in logger, so I think that the 3 pics do load by some script.
I cant recollect properly but few hours age there were almost every car preview blocked (not half like now). So i guess its Easylist issue

**Comment by MajkiIT** [comment] 2015-10-06 09:32
I just add rule (@@||staticpics2.allegrostatic.pl/adverts/otomoto_pl/*128x96$image,domain=allegro.pl) to polish filters (https://www.certyficate.it/adblock/adblock.txt) . It will be faster than add issue to Easylist. Of corse you report it to Easlist.

**Closed** 2015-10-20 13:37 UTC
Labels: 3rd-party filter list issue
