### ISSUE TITLE
Element picker fails to load on dropbox.com

### ISSUE THREAD

**Issue by yourduskquibbles** [gorhill/uBlock#3536] opened 2018-02-21 21:54 UTC
Element picker tool fails to load entirely on [the dropbox news site](https://www.dropbox.com/news/company/announcing-the-dropbox-foundation)

Errors are also reported in the chrome console.

### One or more specific URLs where the issue occurs

https://www.dropbox.com/news/company/announcing-the-dropbox-foundation

### Screenshot in which the issue can be seen

Chrome Console log after trying to launch the element picker.
![error01](https://user-images.githubusercontent.com/22258847/36507078-8c688d04-1750-11e8-9c69-c54e941255fc.PNG)

Specific error message in Chrome Console Sources

![error02](https://user-images.githubusercontent.com/22258847/36507417-897dddc8-1751-11e8-971b-2421ffc3d359.png)

### Steps for anyone to reproduce the issue

1. Go to https://www.dropbox.com/news/company/announcing-the-dropbox-foundation
2. Attempt to launch element picker tool
3. Observe no element picker tool launch and errors in console

### Your settings

- OS/version: Windows 10 64-bit
- Browser/version: Tested on Chrome stable v64.0.3282.167 and Firefox v58.0.2 64-bit
- uBlock Origin version:  1.15.7.3 (chrome dev build) 1.15.11b0 (firefox dev build)

##### Your filter lists

Tested with uBO default filters on new test installation,

##### Your custom filters (if any)

NO custom filters or other extensions installed

**Comment by gorhill** [comment] 2018-02-22 11:56
A more severe manifestation of the same issue reported in #2240: the site uses a content security policy directive `sandbox`, which prevents uBO from injecting it's element picker `iframe`.

**Comment by uBlock-user** [comment] 2018-02-22 12:44
Is it related to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=749236) Chromium bug ?

**Comment by gorhill** [comment] 2018-02-22 12:48
Close but no. uBO injects an `about:blank` `iframe` into the page for element picking purpose, this is being denied because of the page's CSP -- webRequest is not involved in this case.

**Comment by uBlock-user** [comment] 2019-07-23 21:47
Can't reproduce on Firefox or Chromium, is this still an issue ?

**Comment by gorhill** [comment] 2019-07-23 22:34
The site changed its design, we need a new repro case.

**Comment by gorhill** [comment] 2020-10-17 18:06
Since we lost ability to reproduce, I am going to close this issue. A new issue should be opened should there be a new case of element picker failing to inject -- especially given that the picker's injection mechanism has changed significantly lately.

**Closed by gorhill** 2020-10-17 18:06 UTC
