### ISSUE TITLE
Firefox disabled uBlock in a new update.

### ISSUE THREAD

**Issue by sommmen** [gorhill/uBlock#2923] opened 2017-08-29 21:06 UTC
As the title saids, firefox had a new update and it broke - I believe  - all apps.
![afbeelding](https://user-images.githubusercontent.com/8641495/29844049-48ebcee6-8d0e-11e7-927c-b15e21efe7c9.png)

Is this just me, or?

**Comment by galvao** [comment] 2017-08-29 21:11
Same thing here.

**Comment by JDBar** [comment] 2017-08-29 21:16
Same. Re-installing works, but it will disappear the next time the browser is opened.

**Comment by sommmen** [comment] 2017-08-29 21:17
On the release notes the latest update was https://www.mozilla.org/en-US/firefox/55.0.3/releasenotes/ 25 august, although i have only just now or maybe yestday have everything break.

**Comment by sommmen** [comment] 2017-08-29 21:18
@JDBar So this does not fix it then?

**Comment by galvao** [comment] 2017-08-29 21:33
If you click the legacy tag it's all explained there: According to it the developer *might* be working on the transition, so I guess we'll have to wait or cross to another blocker.

**Comment by gorhill** [comment] 2017-08-29 21:36
Duplicate of #2909.

**Closed by gorhill** 2017-08-29 21:36 UTC

**Comment by MrKlatuu** [comment] 2017-08-29 21:39
It appears they are slowly changing the requirements for Add-On's in Firefox.  As of the latest update, (55.0.3) Ublock will not load.  As stated above it will appear if you re-install, but next time you load Firefox it's gone again.  As of Firefox ver. 57 (soon to come), all add-ons will have to meet the new requirements if they are currently marked 'Legacy".  Hopefully, a lot of authors will update.  I don't use a lot of add-ons, but there are a few I consider 'must have'.

**Comment by sommmen** [comment] 2017-08-30 06:35
Ah thanks. 

Not acceptable though, I want this adblocker! it has just the right balance between advanced control and ease of use. I fell completely in love with it a year ago.

anyways thanks, ill look forward to a fix, also perhaps put up a banner in the read-me to inform people like myself that ware completly unaware/blind?

**Comment by gorhill** [comment] 2017-08-30 12:14
> perhaps put up a banner in the read-me to inform people like myself that ware completly unaware/blind?

Read carefully the [Release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.10), that's the _only_ thing asked from you. I can't read these for you.
