### ISSUE TITLE
Links stop working in Firefox

### ISSUE THREAD

**Issue by Fuj-** [gorhill/uBlock#3012] opened 2017-09-13 08:51 UTC
With the latest uBO version, on certain sites, functionality of links is broken on my system. After page load, only the first click has consequence; after that, clicking anywhere in the page does nothing until refresh. Disabling uBO solves the problem (extension needs to be disabled; if I just turn off filtering, the problem persists). Example: ebay.com.

uBO v1.14.4
FF v55.0.3
Win7 SP1 x64

**Comment by gomoku** [comment] 2017-09-13 09:23
Another duplicate of https://github.com/gorhill/uBlock/issues/2947
Have you ever used a search function in your life?: 
https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=ebay
You're expecting a quick easy response without your own contribution.
You've wasted my time, which I could spend on something else.
Egoist. See my thumbs dwon emoji. "duplicate" label + close request.

**Comment by Fuj-** [comment] 2017-09-13 10:46
I didn't search for a keyword, I just skimmed through the first page of issues because I figured it would have to be there if it was already reported, being a new issue. I hadn't noticed anything that describes my problem but in hindsight, yes, I should have dug a little deeper. However, taking my time to file a bug report in no way makes me "egoist & lazy-bones & leech" but quite the opposite. You obviously don't realize that users who actually bother with bug reports are a tiny minority. They don't expect "a quick easy response", they are trying to help and should be appreciated for it, not subjected to insolent rants. You clearly have impaired emotional health coupled with a lack of manners and if you care at all about this extension's public image, you really should let someone else handle these things.

**Comment by gorhill** [comment] 2017-09-13 11:10
@gomoku 

> Another trash duplicate of #2947 from another egoist & lazy-bones & leech.

Please don't do this.

Duplicate of #2982.

**Closed by gorhill** 2017-09-13 11:10 UTC
Labels: duplicate

**Comment by gomoku** [comment] 2017-09-13 12:00
> @Fuj-: I didn't search for a keyword, I just skimmed through the first page of issues because I figured it would have to be there if it was already reported, being a new issue. I hadn't noticed anything that describes my problem but in hindsight, yes, I should have dug a little deeper. 

That's good You've agreed and understood your mistake.

> @Fuj-: However, taking my time to file a bug report in no way makes me "egoist & lazy-bones & leech" but quite the opposite. You obviously don't realize that users who actually bother with bug reports are a tiny minority. They don't expect "a quick easy response", they are trying to help and should be appreciated for it

You've misunderstood the context, the context was about reporting an issue without using a search function earlier (which often translates into littering repos by trash-duplicates), and not about generally reporting an issue, everyone is welcome to report an issue, I've not written anywhere that reporting an issue is bad at general.

> @Fuj-: not subjected to insolent rants. You clearly have impaired emotional health coupled with a lack of manners and if you care at all about this extension's public image, you really should let someone else handle these things.

Completely neither insolet rants nor emotional health nor lack of manners on my part, it was just a calm constructive criticism, a reprimand, I did not have any bad intentions, and if You take a calm constructive criticism as an attack, it's your emotional problem. If anyone here has impaired emotional health coupled with a lack of manners it's You, not me.

> @Fuj-: and if you care at all about this extension's public image, you really should let someone else handle these things.

I do care, that's why I try to learn such peole like You to use  a search function before reporting an issue, and if there is anyone here who spoils uBO's image, then these are spammers like You. So if you care at all about this extension's public image, and can't use such basic function like a search, before reporting an issue, you really should let someone else handle these things (reporting issues).

> @gorhill: Please don't do this.

Don't do what? 
Don't call spammers spammers?
Don't criticize constructively?
Don't teach people to use a search function?
Why don't You tell "Please don't do this." to @Fuj- ?
Why don't You tell "use a search function before reporting an issue" to @Fuj- ?
Why are You defending spammers, and not me?
Do You like spammers more than me?
Do You like them to spam Your repo?
I thought I was helping out here  and protecting the repo against spammers.
I can't understand why my help is not welcome here, and spammers are welcome here instead.
Hold with spammers if You want.

**Comment by Fuj-** [comment] 2017-09-13 12:18
@gomoku 
https://en.wikipedia.org/wiki/Narcissistic_personality_disorder
