### ISSUE TITLE
Paying with Paypal on eBay is blocked by uBlock

### ISSUE THREAD

**Issue by flexd** [gorhill/uBlock#2093] opened 2016-10-22 09:05 UTC
### Describe the issue
When trying to pay for an item on eBay with Paypal, I get the following error, which halts the purchase process.

### One or more specific URLs where the issue occurs
http://www.ebay.com/itm/Pololu-5V-1A-Step-Down-Spannungsregler-D24V10F5-2831-/281994691118?hash=item41a831822e:g:npAAAOSwAvJXBSJZ
Try to purchase the item above using Paypal.

```
gprzg3njm33dcet4cdq1uhbzmb.js:5 Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://mbuy.ebay.com/xo?action=view&sessionid=XXXXXXXX&redirect=mobile' from frame with URL 'https://fedsignin.ebay.com/fedauth/ReceptorDispatcherV2?state=<state here>'. The frame attempting navigation is targeting its top-level window, but is neither same-origin with its target nor is it processing a user gesture. See https://www.chromestatus.com/features/5851021045661696.

refreshParentWindow @ pgprzg3njm33dcet4cdq1uhbzmb.js:5
handleSuccessResponse @ pgprzg3njm33dcet4cdq1uhbzmb.js:9
processReceptorResponse @ pgprzg3njm33dcet4cdq1uhbzmb.js:4
n @ ecfz4y2a0e1thokpgc3cgev00ab.js:2
fireWith @ ecfz4y2a0e1thokpgc3cgev00ab.js:2
w @ ecfz4y2a0e1thokpgc3cgev00ab.js:4
d @ ecfz4y2a0e1thokpgc3cgev00ab.js:4
contentscript.js:77 Uncaught Error: uBlock Origin: aborting content scripts for https://fedsignin.ebay.com/fedauth/ReceptorDispatcherV2?state=<state here>
    at contentscript.js:77
(anonymous) @ contentscript.js:77
```

### Screenshot in which the issue can be seen

After logging in to Paypal, it just never redirects/allows me to continue, and the error above is visible in Console.

![2016-10-22-110356_1261x1333_scrot](https://cloud.githubusercontent.com/assets/2317/19618328/71f6a53e-9847-11e6-9009-805594da7f63.png)

### Steps for anyone to reproduce the issue

Try to purchase an item from eBay and pay using Paypal. Do not have "remember me" checked, so you need to login to make the purchase.
Once logged in, the user&password box disappears, and we are left with just a grayed out shopping cart screen.

### Your settings

- Browser/version: 
Chrome Version 55.0.2882.0 dev (64-bit) on Debian Jessie
- uBlock Origin version: 
uBlock Origin v1.9.10

##### Your filter lists

Default filters minus uBlock - Experimental, EasyLift, Peter Lowe's Ad server list, Easy Privacy, Malware Domain List, Malware domains, Aaklist (anti-adblock killer)

##### Your custom filters (if any)

None that relate to this domain

**Comment by gorhill** [comment] 2016-10-22 12:12
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-10-22 12:12 UTC

**Comment by timwhite** [comment] 2016-10-26 10:02
I can confirm this isn't a uBlock issue. It's an Ebay/Paypal Chrome issue due to an upcoming change in Chrome to make frames more secure.
