### ISSUE TITLE
Firefox 55 toolbar icon

### ISSUE THREAD

**Issue by mezorba** [gorhill/uBlock#2504] opened 2017-04-02 09:32 UTC
Hello,

I'am using firefox nightly 55.0a1 at Windows 10. Before the last upgrade ublock perfectly works and display the icon at the toolbar but at the moment doesn't appear icon at the toolbar also not working.

I removed and re installed also i refreshed firefox nigtly but still doesn't working.

Btw icon doesn't seems customise screen to (ofcourse ublock activated)

**Comment by gorhill** [comment] 2017-04-02 11:14
What the reason for not providing the requested info in the template?

**Comment by li0nsar3c00l** [comment] 2017-04-02 11:32
same here, eventho it's working in the most recent pre-release (1.11.5rc6)

**Comment by gorhill** [comment] 2017-04-02 11:45
Duplicate of #2505.

**Closed by gorhill** 2017-04-02 11:45 UTC
