### ISSUE TITLE
The image/frame placeholders (when shown) are not too useful.

### ISSUE THREAD

**Issue by gitut2007** [gorhill/uBlock#2822] opened 2017-07-25 20:19 UTC
Hi. Related to https://github.com/gorhill/uBlock/issues/2688 ; 
for not having to go to the log, (or have to exit fullscreen to click the uBO icon...), it would be very useful to have right-click options in the placeholder (like in 'Policeman' Addon -which worked in FireFox 47 but not now in FF 54-; it has a 'shield' icon in the placeholder to hint it's right-clickeable) : 'load this image', 'load all images in this tab', 'load temporarily all images from xxx.com', 'load permanently all images from xxx.com' (this 'permanently' applies only to current page domain)  OR  'load this frame', 'load all frames in this tab', 'load temporarily all frames from xxx.com', 'load permanently all frames from xxx.com'. 
In case it's e.g. a Youtube frame, one can then copy the URL and open the video in whatever program other tan in the browser. In case of images one chooses exactly which ones to see.

Other than this, great ergonomy in both this and uBMatrix, (I'm using both because some security options are only available in one or the other). 
Thanks.

**Comment by gorhill** [comment] 2017-07-25 20:52
Duplicate of #2688.

**Closed by gorhill** 2017-07-25 20:52 UTC
