### ISSUE TITLE
ublock orgin kills go daddy's email compose window

### ISSUE THREAD

**Issue by ToddAndMargo** [gorhill/uBlock#3010] opened 2017-09-12 18:47 UTC
uBlock Origin v1.14.4
Firefox 55.0.3 x64 for Windows
Windows 7 Pro SP1
https://email12.godaddy.com/pcompose.php   (workspace email)

When you press "compose" (or reply) you get a never ending "loading" circle.  UBlock Orgin must be removed.  Disabling does not work.  White listing does not help either.

**Comment by gorhill** [comment] 2017-09-12 19:25
Duplicate of #2982.

**Closed by gorhill** 2017-09-12 19:25 UTC
Labels: duplicate
