### ISSUE TITLE
Some pages close after a major delay

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#1613] opened 2016-05-05 20:35 UTC
STR:

Open some links in the following sites:
http://www.nrg.co.il/online/HP_1.html#after_maavaron
http://www.israelhayom.co.il/
Close the tab(s).

Result:

Some pages close after three/four seconds with uBO.
The issue started in Firefox 45 and exists also in FF 46.
No problem with ABP.

Win 7 32-bit.

**Comment by gorhill** [comment] 2016-05-06 17:49
Can you use the logger to find out whether it's really uBO closing the tab, and if so, what filter caused it to do so? A tab closed by uBO would be reported as a `popup` or  `popunder` event in the logger.

**Comment by IDKwhattoputhere** [comment] 2016-05-06 17:57
I think they meant that the tabs take longer to close when you press the `x`. Correct me if I'm wrong.

**Comment by Yaron10** [comment] 2016-05-06 18:30
Hello gorhill and IDKwhattoputhere,

IDKwhattoputhere has understood the issue correctly. Thanks. :)
When pressing the the Close button in some pages on those sites it may take a few seconds for the tab to close.

Thank you.

Best regards.

**Comment by gorhill** [comment] 2016-05-07 05:12
> Some pages close after three/four seconds with uBO

I need exact URLs.

**Comment by Yaron10** [comment] 2016-05-07 13:26
I've just tried the following link. It took some 5 seconds to close.
http://www.israelhayom.co.il/article/379153

Any URL opened from the sites I've mentioned above *might* close after a significant delay.
It may not happen each and every time, but in a regular surf-flow it occurs quite often.

http://www.nrg.co.il/online/1/ART2/775/603.html?hp=1&cat=666
http://www.nrg.co.il/online/1/ART2/775/568.html?hp=1&cat=666
***
Another minor issue:
http://www.news1.co.il/

The banner at the top is displayed for half a second and then blocked.
With ABP I don't see it at all.
***
I prefer uBO over ABP.
I'd be glad if you could reproduce and fix those issues.

Thank you.

**Comment by gwarser** [comment] 2016-05-07 13:57
It's caused by POST request to `https://fxeukilgm5.execute-api.us-east-1.amazonaws.com/production/track`

Weird thing - it's not always visible in UBO log:

![zrzut1](https://cloud.githubusercontent.com/assets/886325/15092491/dbb7909c-146b-11e6-924f-e83dad5b9777.png)

And not visible at all when blocked by for example `||amazonaws.com$xmlhttprequest` or dynamic filtering. Maybe something is blocked earlier by the same filter, but I cannot confirm - page is very slow on my PC.

Fx 48, UBO 1.7.5b0 on Mint.

**Comment by Yaron10** [comment] 2016-05-07 14:07
@gwarser,
Thanks. I appreciate it.

**Comment by gorhill** [comment] 2016-05-07 14:25
Findings (thanks to @gwarser for pointing out the `POST` request):

- As opposed to what is stated in first comment, I do experience the delay with ABP.
- The delay is caused by the page sending a **synchronous** XMLHttpRequest to `https://fxeukilgm5.execute-api.us-east-1.amazonaws.com/production/track
` when the page unloads.
    - Synchronous XMLHttpRequest are strongly discouraged everywhere because they are blocking UI. Worst in current case, this occurs when the page unload event is fired.
- The script responsible for the synchronous XHR is from `spot.im`, which is apparently related to the commenting system on that site.

**Comment by gorhill** [comment] 2016-05-07 14:29
> And not visible at all when blocked by for example

I experience the same thing. Using `||fxeukilgm5.execute-api.us-east-1.amazonaws.com/production/track$xmlhttprequest,domain=israelhayom.co.il` seems to make the issue go away, but somehow now the blocked network request is no longer reported in the logger. I suspect it has to do with the fact that the network request is synchronous.

This does not happen with Chromium: the page uses a beacon to ping home, which is rightly blocked by uBO's _"Disable hyperlink auditing/beacon"_.

**Comment by Yaron10** [comment] 2016-05-07 14:34
@gorhill,

Thank you very much. I appreciate your work.

I do **not** experience any delay with ABP. This is consistent.
Anyway, is there anything you can do about it?

**Comment by gorhill** [comment] 2016-05-07 14:37
> I do not experience any delay with ABP. This is consistent.

This makes no sense. The page fires exactly the same synchronous network request when the page unloads with ABP. Verify that you have the same filter lists and custom filters in both extensions.

> Anyway, is there anything you can do about it?

Ask the site to fix its issue, this is not uBO issue.

**Comment by Yaron10** [comment] 2016-05-07 14:44
I've disabled some uBO's filters and I now have the same lists in both extensions:
EasyList + EasyList Hebrew.

There must be something else.
It's not only that site.

Thanks.

**Comment by gorhill** [comment] 2016-05-07 14:45
> There must be something else.

I do experience the delay in ABP. I invite whoever else to try.

**Comment by IDKwhattoputhere** [comment] 2016-05-07 14:51
> I do experience the delay in ABP.
Same. Sometimes shorter but always there.

**Comment by Yaron10** [comment] 2016-05-07 14:53
Thank you all. I do appreciate it.

**Comment by gorhill** [comment] 2016-05-07 14:58
> shorter but always there

The delay from synchronous, blocking network request is arbitrary, it always depends on how fast the remote server returns an answer.

![a](https://cloud.githubusercontent.com/assets/585534/15092792/f401f914-1441-11e6-867d-63e59ed19560.png)

Dugged a bit more, and I get why this may not be happening with ABP: turns out I have the config `beacon.enabled` set to false. This causes the page to fall back on a synchronous XMLHttpRequest. If `beacon.enabled` is set to `true` (which is default), there should be no delay.

**Comment by Yaron10** [comment] 2016-05-07 15:02
Great.

Allow me to ask again: is there anything you can do about it?
I'd love to return to uBO. :)

Thanks.

**Comment by gorhill** [comment] 2016-05-07 15:04
>  is there anything you can do about it?

Use the suggested filter?

The root issue though is the page using synchronous XMLHttpRequest. That delay issue will be experienced even by users not using any blocker, but disabling `beacon.enabled`.

**Comment by Yaron10** [comment] 2016-05-07 15:08
I don't understand it. Which filter?
`beacon.enabled` is set to true.

**Comment by gorhill** [comment] 2016-05-07 15:09
Disabling uBO's setting _"Disable hyperlink auditing/beacon"_  should solve that one issue, at the cost of no longer foiling that sort of tracking attempts everywhere else. But then you do not benefit that option anyways with ABP.

> `beacon.enabled` is set to true.

That's why you do not experience the issue with ABP. uBO's _"Disable hyperlink auditing/beacon"_ set it to false.

**Comment by Yaron10** [comment] 2016-05-07 15:15
That does solve the problem. :+1: 

Thank you very much. uBO is great and I'm really glad I can now return to using it.

Best regards.

**Comment by gorhill** [comment] 2016-05-07 15:17
@gwarser The blocked request is not added to the logger [because of this test](https://github.com/gorhill/uBlock/blob/62b087ef880316f783f6c3a864bdd74f145975e8/src/js/logger-ui.js#L573). By the time the logger receives the information, the tab has disappeared. So I need to re-work the code in there to not discard the information even when the associated tab no longer exist.

**Comment by Yaron10** [comment] 2016-05-07 15:20
@gorhill,

Anything can be done regarding the minor issue I've mentioned above?

http://www.news1.co.il/

The banner at the top is displayed for half a second and then blocked.
With ABP I don't see it at all.

Thanks.

**Comment by gwarser** [comment] 2016-05-07 15:22
@Yaron10 https://github.com/gorhill/uBlock/wiki/Does-uBlock-block-ads-or-just-hide-them%3F#cosmetic-filters it's how uBlock work.

**Comment by Yaron10** [comment] 2016-05-07 15:26
@gwarser,

Thank you. And thanks again for your important help in solving the other issue.

BR

**Comment by gorhill** [comment] 2016-05-07 15:26
@Yaron10 

![a](https://cloud.githubusercontent.com/assets/585534/15092939/840d18f0-1446-11e6-98e3-f8103ae4a7f8.png)

=

    ! 2016-05-07, 11:26:01 AM http://www.news1.co.il/
    www.news1.co.il###TopBanner

**Comment by Yaron10** [comment] 2016-05-07 15:29
Perfect.

You are the best. :)
Thanks again for your great work.

BR

**Comment by gorhill** [comment] 2017-09-10 18:00
uBO has been treating beacons differently than hyperlink auditing since quite a while now, this makes the issue here obsolete.

**Closed by gorhill** 2017-09-10 18:00 UTC
Labels: external
