### ISSUE TITLE
No toolbar icon in Pale Moon

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#238] opened 2015-05-24 05:24 UTC
uBlock works fine in that browser, apart from a slight problem with the icon in the toolbar that does not appear. It is also not available either in the editing options of the toolbar.

```
Windows 7 Ultimate Edition (x64)
Pale Moon Version: 25.4.1 (x64)
Other in-browser extensions: LiveReload
```

**Comment by tenkuu** [comment] 2015-05-24 06:40
Pale Moon isn't supported.

**Comment by lucasbenard** [comment] 2015-05-24 08:34
OK no worries. It is simply to point out that uBlock operated at least at minimum on Pale Moon
The absence of the button on the toolbar is not more trouble than that, it's just less convenient to handle exceptions.
I guess it's not much to do to add the missing button, but I do not know how to do this =)

**Comment by Havokdan** [comment] 2015-05-24 09:48
Ublock version with support for pale moon: https://github.com/chrisaljoudi/uBlock

**Comment by gorhill** [comment] 2015-05-24 11:26
Duplicate of #40.

**Closed as completed by gorhill** 2015-05-24 11:26 UTC
