### ISSUE TITLE
[Firefox] Clicking eBay links requires a page refresh to load the new page

### ISSUE THREAD

**Issue by vahhadbe** [gorhill/uBlock#2947] opened 2017-09-02 02:47 UTC
### Describe the issue

Sometimes, after clicking links on eBay (any link to new pages), the URL in the URL bar changes to the new link, but the page content doesn't change - You need to refresh or (or in my case, I select the new URL in the URL bar and press enter at which point it loads the page correctly). This can happen on any part of the site, searching, clicking a listing, or clicking the print postage button.

I found the correlation to uBlock after reading [this thread](https://www.reddit.com/r/Ebay/comments/6xht3p/firefox_55_on_windows_7_ebay_is_super_slow_and/) and found 2 people (3 since the OP is referencing another post which matches his issue) having the same issue. One person suggests downgrading uBlock to a previous version which fixed it for him.

Aside from this linux machine which I am writing the report from, I also have the same issue on my Windows 8 machine which is also running the newest version of Firefox and uBlock origin for Windows.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

http://www.ebay.com/itm/HP-19-All-in-One-PC-Celeron-J3355-4GB-RAM-1TB-HDD-Windows-10-20-C10/311904401794?_trkparms=aid%3D555018%26algo%3DPL.SIM%26ao%3D2%26asc%3D41375%26meid%3Dc16ef2f32e604476abf07c92fda67bef%26pid%3D100005%26rk%3D2%26rkt%3D6%26mehot%3Dpp%26sd%3D352129727269&_trksid=p2047675.c100005.m1851

NOTE: The issue doesn't happen on a specific URL, but on any ebay page after clicking a link - And not 100% of the time either. I only added the link above as adding a link is a requirement to post

### Screenshot in which the issue can be seen

https://imgur.com/a/iBKg0

I clicked the first listing for the basketball, and the URL in the bar updated to reflect that - But the page won't change to show the content of that URL unless I reload it, it's still on the search page.

### Steps for anyone to reproduce the issue

Click any link on eBay. Doesn't happen 100% of the time, it actually took me a while to reproduce for the screenshot. But when I went to try and print postage for something a few hours ago, it happened there right away.

### Your settings

- OS/version: Debian Stretch Linux 64 bit (newest)
- Browser/version: Firefox 55.0.2
- uBlock Origin version: uBlock Origin 1.14.0

##### Your filter lists

Nothing changed from default install

**Comment by zerogott** [comment] 2017-09-02 09:08
Can confirm.
Same is happening for me since 1.13.10.
If im on Twitter and go to Facebook the page will remain twitter until is reload it/make a new tab and go to facebook.
Also have a problem that direct links to pics(.png for example) stay grey until i change back to 1.13.8 there is no problem at all.


    OS/version: Windows 8.1 Professional 64 bit (newest)
    Browser/version: Firefox 55.0.3 32bit
    uBlock Origin version: uBlock Origin 1.14.0 (no Problems at all with 1.13.8)

**Comment by gorhill** [comment] 2017-09-02 10:19
Disable all your legacy extensions and try again. Numerous report of web pages loading improperly as a result of uBO being used along legacy extensions. If this solves the issue, then re-enable the disabled legacy extensions one by on to find out which one is causing the issue.

**Comment by zerogott** [comment] 2017-09-02 13:11
Had to disable every addon+the theme i use to get 1.3.10+ running without a problem,so its a problem that is caused by ublock because the other addons work like a charm only uBlock is bugging out.

**Comment by gorhill** [comment] 2017-09-02 13:22
Problem is not uBO, otherwise you would have the same issue with the legacy version of uBO. Consider legacy add-ons to be incompatible with running webext extensions. Try to pinpoint exactly which legacy extension is causing you the issue, and share your findings with others. In any case, there is nothing to change in uBO, which is compatible with FF57, which itself will cease to support legacy extensions, and which will be released in a few weeks.

**Comment by gorhill** [comment] 2017-09-02 13:26
For instance:

http://forums.mozillazine.org/viewtopic.php?p=14764530#p14764530

> The behaviour I mentioned on eBay isn't present on a clean profile with uBO 1.14.0 either. Of Mark's list of possible culprits I only have here, on W10:
> 
> Add Bookmark Here ² 55.0.20170705
> Add to Search Bar 2.9

uBO is maintained and updated to work with modern Firefox. Some of the legacy extensions haven't been updated in years and all of them will no longer load with Firefox 57.

**Closed by gorhill** 2017-09-02 13:26 UTC

**Comment by gomoku** [comment] 2017-09-02 13:33
> @zerogott so its a problem that is caused by ublock 

It might be, but not necessarily, it still can be caused by a browser / a website / a plugin / an built-in mozilla's addon / a mistake at reporter's side , even if it turns out to be so, declaring it in advance is lame and offensive for author of uBO.

**Comment by Photon89** [comment] 2017-09-09 11:01
Thanks for the hint, I could solve the issue by deactivating the "Old Default Image Style" and "Dictionary Switcher" add-ons.

**Comment by weweilep** [comment] 2017-09-18 14:06
I still have this issue with FF 55.0.3 and uBlock Origin 1.14.8.  I have disabled all other extensions, and the issue still remains.  Only by disabling the uBlock Origin extension does the site function correctly again (simply disabling blocking on the single page does not work).

**Comment by gorhill** [comment] 2017-09-18 14:13
You still have the issue because this is a browser bug, as spelled out in the [Release notes](https://github.com/gorhill/uBlock/releases/tag/1.14.8).

**Comment by gorhill** [comment] 2017-09-18 14:24
https://bugzilla.mozilla.org/show_bug.cgi?id=1348497#c27
