### ISSUE TITLE
Ublock origin and popup blocker giving annoying popup in chrome

### ISSUE THREAD

**Issue by ashishb122** [gorhill/uBlock#2342] opened 2017-01-27 06:42 UTC
I have chrome 56.0.2924.76 (64-bit) stable and ublock origin 1.10.6 stable with default filter lists.
Installed a popper blocker pro extension in it.
Whenever I visit `www.300mbfilms.com` I get this type of popup whenever my popup blocker blocks a popup. Also it closes automatically after a few seconds.
I have never seen this issue with adblock or adblock plus.
I think I have cleared myself, if not plz let me know what more information do you need.

![popup](https://cloud.githubusercontent.com/assets/25156726/22362589/acd7c0d2-e489-11e6-97a4-77a3b8d25541.jpg)

**Comment by toshiya44** [comment] 2017-01-27 07:06
Use uBO's nonpop switch to block popups.

**Comment by ashishb122** [comment] 2017-01-27 07:52
If I do that then all popups are blocked including download links popup which opens in new tab

**Comment by toshiya44** [comment] 2017-01-27 09:15
There's a per site switch too. https://github.com/gorhill/uBlock/wiki/Per-site-switches

**Comment by uBlock-user** [comment] 2017-01-27 10:56
I cannot reproduce that popup alert.

try this - `300mbfilms.com##script:inject(popads.net.js)`

**Comment by gorhill** [comment] 2017-01-27 13:13
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-01-27 13:13 UTC
Labels: filter list issue, invalid
