### ISSUE TITLE
site functionality broken even disabling ubo for the site

### ISSUE THREAD

**Issue by viraladmin** [gorhill/uBlock#2345] opened 2017-01-29 07:16 UTC
issue only in chrome, ubo 1.10.4

site:
marketers.coop

steps to reproduce the issue:
https://issues.adblockplus.org/ticket/4808

the site is broken in ABP too (as the issue above)

the site is working only disabling the extension in the extensions page.
still broken disabling ubo for the site or disabling all the lists in ubo.

(no issue in firefox at least in ABP)

Same with Adguard.

This is not a browser issue as disabling the plugins from the browser, makes the site (and script) in question work.

**Comment by gorhill** [comment] 2017-01-29 15:30
Duplicate of #2317.

I saw your [comment on ABP issue tracker](https://issues.adblockplus.org/ticket/4808#comment:16):

> I will keep reopening the tickets, and then I will have everyone that uses the software come and start posting tickets

I suggest you spend your energy fixing your issue and refrain from hunting for free labor here -- we already have narrowed the issue for you, and you were even given a good advice by @kzar, you should be grateful.

If you keep abusing the issue tracker here as you threaten to do so in your comment on ABP issue tracker, I will report you to GitHub.

**Closed by gorhill** 2017-01-29 15:30 UTC

**Comment by viraladmin** [comment] 2017-01-30 20:34
You can report me wherever you like. Email accounts are a dime a dozen, as are IP's. 

I am actually contacting the 6 companies who have sued ABP parent already. Because unlike the lawsuits they lost, this isn't about the plugins blocking ads, they are blocking site functionality. My code has no errors so I am not "looking for free labor to fix my code" The problem is on the end of the plugins and I can't fix those. There are no errors what so ever in my code. 

So if you believe I am abusig the ticket system reporting an error that can clearly be tracked to the plugin (as without the plugin installed there are no errors, and the site works just great) you do what you feel is right. In the meantime I have companies to reach out to so they can setup the software and ile suits for site functionality that doesn't relate to ads being blocked.

You have a good day. I now see what all you guys mean by "user choice" what a joke you mean "we want to control other peoples websites even if it doesn't relate to blocking ads"
