### ISSUE TITLE
Feature request: Enable/disable uBlock via Icon

### ISSUE THREAD

**Issue by rolandbeck** [gorhill/uBlock#3311] opened 2017-12-03 10:28 UTC
Sometimes I need to disable uBlock for a few minutes to buy things via shoop, iGraal, ...
I think there are several forwards until I reach the final domain so disabling it just for the actual domain (shoop, iGraal, ...) and the target domain (groupon for example) won't be enough.

Up to now the only possibility I know is:
1. Go to the extensions (in Chrome "chrome://extensions/")
2. Do the shopping with disabled uBlock extension
3. Go to the extensions and re-enable

It would be nice to be able to turn the extension completely on or off in that menu:
![ublock](https://user-images.githubusercontent.com/20404789/33524423-76856fce-d81d-11e7-81df-c8b3e8264ce1.jpg)

**Comment by Hrxn** [comment] 2017-12-03 11:35
?
That big blue button?

**Comment by rolandbeck** [comment] 2017-12-03 11:39
That big blue button disables/enables uBlock only on the actual domain.
I want a button to disable/enable uBlock completely (on all domains).

**Comment by gorhill** [comment] 2017-12-03 12:21
Duplicate of #167.

**Closed by gorhill** 2017-12-03 12:21 UTC
Labels: duplicate
