### ISSUE TITLE
Element Picker Mode Button Hidden by website

### ISSUE THREAD

**Issue by wakkabakkamakka** [gorhill/uBlock#1721] opened 2016-06-14 16:28 UTC
Website hides the Element-Picker-Mode button.

>     mega.nz

<img width="397" alt="unbenannt" src="https://cloud.githubusercontent.com/assets/18357085/16050839/77f80018-325d-11e6-9cb0-e22d66bdee1a.png">

### Steps for anyone to reproduce the issue

Go to mega.nz
Click the ublock origin symbol.
See the disappeared element picker button.

### Your settings

- Browser/version: firefox 47.0 x64
- uBlock Origin version: 1.7.0

##### Your filter lists

standard

##### Your custom filters (if any)

no relevant ones

**Comment by wakkabakkamakka** [comment] 2016-06-14 16:36
Sorry i just realised right now that i forgot to mention that i installed the MEGA extension. (which is necessary to download large files)

Without the MEGA-extension the issue does not occur.

**Comment by gorhill** [comment] 2016-06-14 16:39
> MEGA-extension

Link?

**Comment by wakkabakkamakka** [comment] 2016-06-14 16:42
mega:///#firefox

**Comment by gorhill** [comment] 2016-06-14 17:44
I was asking for a link to the MEGA extension on Mozilla's site, but anyways your response has the answer: cosmetic filtering is not enabled for anything else than http/https protocols. This makes the issue here a duplicate of #1601.

**Closed by gorhill** 2016-06-14 17:44 UTC
Labels: unable to reproduce
