### ISSUE TITLE
ublock sometimes does not load site completely

### ISSUE THREAD

**Issue by Juschi1** [gorhill/uBlock#3526] opened 2018-02-19 13:27 UTC
### Describe the issue
I have the following issue: Since two weeks or so, I have the problem, that sometimes firefox loads webpages not completely, when ublock active. It's about every 30. loading. Then, sometimes, elements of the webpage are missing or the webpage fails to load completely (white page) oder I see a mixup of the webpage and the sourcecode. I use firefox with no other add-ons installed with a fresh profile. If I deactivate ublock, the problem is gone. I have reinstalled ublock several times, resetted firefox and used a new profile. With "Adblock Plus" I don't have this issue but i want to use ublock.

### One or more specific URLs where the issue occurs

It can happen on every webpage.

### Screenshot in which the issue can be seen

http://fs1.directupload.net/images/180219/a4kelr3z.png
http://fs1.directupload.net/images/180219/l5cuxsnh.png

### Your settings

- OS/version: Win 7 64 Bit
- Browser/version: Firefox 58.02 with new profile
- uBlock Origin version: 1.15.6, default settings

##### Your filter lists

Everything default.

**Comment by gorhill** [comment] 2018-02-19 13:53
You failed to provide URLs where you see the issue (read carefully [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md)).

**Comment by gorhill** [comment] 2018-02-19 13:58
Labelling "available" = somebody who can reproduce will have to investigate -- it's unactionable otherwise.

**Comment by gorhill** [comment] 2018-02-19 14:20
Ok, I've reproduced the case of "mixup of the webpage and the sourcecode" at `https://www.heise.de/forum/startseite/`:

![a](https://user-images.githubusercontent.com/585534/36382191-1f29dc08-1556-11e8-98af-86c051eb0a9f.png)

So now I have something I can investigate.

**Comment by gorhill** [comment] 2018-02-19 19:36
It's **extremely** difficult to reproduce -- but I did reproduce, though sometimes I reload the page 100+ times before I can see the issue happening.

I am going to need help in finding better repro steps. My guess is that it is related to response data filtering, but a specific code path: when only scriptlets need to be injected, which is the case on `heise.de`.

I try to stick to a "small" page, `https://www.heise.de/forum/heise-online/Roboter/forum-371826/`, and keep reloading the page until it occurs. But as said, extremely rare, it could be a timing issue. I looked at uBO's code, and nothing stands out as wrong, so it could be an obscure Firefox issue related to the stream filtering code.

I looked at the DOM when it finally happened again, and it is as if a chunk of response data was missing.

I did find another unrelated issue with that part of the code in uBO, which was a missing cleanup after injecting the scriptlet, but fixing this does not resolve the issue, I could make it happen again. It happens so rarely at this point that it's impossible to narrow the cause -- for all I know it could maybe also happen without uBO or with another blocker, it could be the server, it could be Firefox, etc.

An observation, but this would need to be confirmed, which is difficult given how rare the issue occurs on my side: it seems when the issue occurs, Firefox starts to severely leak memory, I see a lot of strings in `about:memory` which appears to be HTML source code strings.

**Comment by Juschi1** [comment] 2018-02-19 21:20
Cool. The Intend of coming back here was only to tell you that I can fully understand, that you can't give me any help due to the fact that I can't provide an exact way to reproduce my problem. I only wanted to make sure that I have reported the Issue because I have worked since a week to provide a reproducible way and, after eleminating all other causes, are now absolute sure that it's a problem with adblock. I love as well my firefox and ublock and can't image to renounce any of them. 
But now I see that you relly was able to reproduce this problem. First of all: **Many Thanks!!!**

Second: I now trying the ublock version from december 17. As you now know that the problem does not happen very often, I will see in the next 24-48 hours if it happens again. I am now using the old version since about 3 hours and my feeling is that the problem should have occurede since.

If I can provide you with any other informations you need, please let me know. 
And don'd forget that this problem occued on several other websites also. I remember in particular chip.de (was today) for example but I have had this problem on many pages.

**Comment by h1z1** [comment] 2018-02-20 03:31
Can confirm this, and yeah it's not only rare it's quite weird like the elements are being rendered out of order or something.  No doubt a browser problem but I certainly have NFI where.  @Juschi1 do you run into things like seeing images render for half a second then disappear?

uM 1.1.21.3
uBO 1.14.23.1
Chromium 61.0.3163.100

**Comment by Hrxn** [comment] 2018-02-20 03:36
Well, if this is indeed the same phenomenon on Chromium we'll have a new problem here. The suspicion so far has been that this is related to the response data filtering, right? That would be Firefox only, at the moment.

> Chromium 61.0.3163.100

BTW, what version is this? Current stable is at 64.0.3282.167/168..
Why test with an old version?

**Comment by uBlock-user** [comment] 2018-02-20 04:33
> Well, if this is indeed the same phenomenon on Chromium we'll have a new problem here.

It's not. I'm on Chromium 66 and have used 64 in the past few months, nothing of this sort ever happened.

**Comment by h1z1** [comment] 2018-02-20 04:58
What? Do you even know what repo I'm talking about?

**Comment by h1z1** [comment] 2018-02-20 05:03
Removed my original reply as I misread what you said.  Still have no idea why you gave a thumbs down but whatever.

**Comment by gorhill** [comment] 2018-02-20 13:30
What I need help with at this point is with narrowing. If this is a timing issue, some of you may have better chance at reproducing the issue, and thus are better placed to help narrowing. At this point, my best guess is a very specific code path used when **all** the following conditions are met

- there are scriptlets to be injected (which is the case on `heise.de`)
- the charset used is explicitly declared in the response header and is supported by uBO (which is the case on `heise.de` -- `utf-8`)
- there is no HTML filtering for the site (which is the case for `heise.de` unless you have custom HTML filters, those using `##^`)

To narrow should be simple enough:

1. Confirm that you can reproduce the issue regularly by repeatedly loading pages from `heise.de`.

Narrowing:

1. Create a local `allow` rule for `heise.de` using dynamic filtering:
  ![a](https://user-images.githubusercontent.com/585534/36426227-6acabe5e-1617-11e8-932f-903e01e7bed6.png)
1. This disables scriptlets injection -- so now see if you can reproduce the issue with scriptlet injection disabled.

**Comment by h1z1** [comment] 2018-02-20 13:37
Something I was playing with that may or may not be related but exhibits similar behavior is simply blocking images.   If you block all requests to raw.githubusercontent.com on https://github.com/lenosisnickerboa/csgosl/wiki for example, on first load you'll see the placeholder.  If you then allow images the first reload will not show anything.  It takes one or more refresh attempts.  You'll have to wait a bit between retries or force a cache flush.

Does that jive with anything here or is it  completely different?   I have had entire pages load as if it were blank as per above, wondering if these are related.

**Comment by mapx-** [comment] 2018-02-20 13:57
probably related:
https://github.com/uBlockOrigin/uAssets/issues/1492

When an inject filter is used the page becomes blank on firefox

disabling the existing filter and adding other 1
```
mako.co.il#@#script:inject(abort-on-property-write.js, upManager)
mako.co.il##script:inject(set-constant.js, canRunAds, true)
```

- adding only the exception one the page is loaded

**Comment by gorhill** [comment] 2018-02-20 14:17
> probably related:
> uBlockOrigin/uAssets#1492

No, I looked at it. The issue is more likely that with Firefox the scriptlet is guaranteed to be injected at the top of the document, which is not the case for Chromium.  If you `view-source:` the page, you will find that there is not much HTML code in there, the page is wholly generated using javascript. Defusing upManager breaks the javascript, hence breaks the page rendering.

**Comment by gorhill** [comment] 2018-02-20 14:25
@mapx- Hmm, actually let me investigate more, not sure what the issue is. The page does not declare a `<!DOCTYPE>` so it can't be the same code path as the issue here.

**Comment by gorhill** [comment] 2018-02-21 18:22
Try 1.15.11b0 on AMO, this version no longer use stream filtering to inject scriptlets. My best guess at this point is that there is an issue somewhere in Firefox's StreamFilter API.

**Comment by Juschi1** [comment] 2018-02-22 10:32
on AMO I only see 1.15.10

**Comment by uBlock-user** [comment] 2018-02-22 10:47
He meant the BETA version from here - https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta

**Comment by Juschi1** [comment] 2018-02-23 12:37
I have the same problems in the beta. For example:

http://fs5.directupload.net/images/180223/jkaoqtv4.png

https://www.tichyseinblick.de/kolumnen/oswald-metzger-zur-ordnung/fluechtlinge-merkels-erpressungsversuch/

**Comment by gorhill** [comment] 2018-02-23 14:47
> I have the same problems in the beta

Yes, 1.15.11b0 is a dud -- I made a stupid mistake in the code in my haste to push a beta version before the Feb 22 deadline (the date at which AMO no longer allow beta versions to be uploaded).

**Comment by gorhill** [comment] 2018-02-23 15:18
@Juschi1 You can use 1.15.10, this version does not rely on stream filtering for scriptlets injection. I don't know why I told you to use the beta version when 1.15.10 should work fine.

**Comment by jejo86** [comment] 2018-02-24 13:09
i had the same problem **every single time** on loading the page of [RARBG](https://rarbg.to/). you could see the page being loaded for a millisecond or so and then most of it was hidden, even though i allowed every ressource in uBlock. disabling uBlock helped, but i just found out that simply deactivating the "cosmetic filter" also solves my issue.

![2018-02-24_135934](https://user-images.githubusercontent.com/28619134/36630754-d1f6ee34-196b-11e8-8564-7351e0b81dc4.png)
![2018-02-24_140006](https://user-images.githubusercontent.com/28619134/36630755-d2201d5e-196b-11e8-8314-a975ed2a5cf2.png)

luckily this filter is only disabled on that page and not globally. well i guess luckily, i don't really know what it does.
i hope this could be related and of use to anyone having a similar problem.

**Comment by gorhill** [comment] 2020-12-06 12:53
Closing as no longer an issue, I won't bring back injection scriptlets into the response data.

**Closed by gorhill** 2020-12-06 12:53 UTC
