### ISSUE TITLE
Messy domain and subdomain ordering in the popup

### ISSUE THREAD

**Issue by Mikey1993** [gorhill/uBlock#283] opened 2015-06-02 18:52 UTC
URL: http://www.bbc.com/future/story/20150601-nasas-fleet-of-fighter-planes

A picture is worth a thousand words:
![Messy ordering](https://i.imgur.com/Ie0QSuj.png)

Tested with uBlock 0.9.8.2 and 0.9.8.4

**Comment by gorhill** [comment] 2015-06-02 19:24
It looks messy if you do not know that `s3.amazonaws.com` is not supposed to be a valid root domain, and it appears a network request to `s3.amazonaws.com` were made despite this.

`net.s3.amazonaws.com` is a valid root domain, so it's listed on its own. This would be similar to a web site making a request to `co.uk` (not a valid root domain) and also making a request to `example.co.uk` (a valid domain).

As I often pointed out in the past, the [Public Suffix List](https://publicsuffix.org/) dictates everything, so there is nothing uBlock can do, last thing I want is to quicksand myself by introducing arbitrary exceptions to the PSL.

**Comment by gorhill** [comment] 2015-06-03 13:32
Closing as "by design".

**Closed as completed by gorhill** 2015-06-03 13:32 UTC
