### ISSUE TITLE
Websocket logging?

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#2760] opened 2017-07-05 23:45 UTC
### Describe the issue

I opened the logger, and didn't see any websockets anywhere.

### One or more specific URLs where the issue occurs

Mastodon.

### Screenshot in which the issue can be seen

*TODO insert screenshot of empty logger page here*

### Steps for anyone to reproduce the issue

1. Log in to a mastodon instance.
2. Open logger.

### Your settings

- [x] Hide placeholders of blocked elements
- [x] Show the number of blocked requests on the icon
- [x] Make use of context menu where appropriate
- [ ] Disable tooltips
- [ ] Color-blind friendly
- [ ] Enable cloud storage support
- [x] I am an advanced user

- [x] Disable pre-fetching (to prevent any connection for blocked network requests)
- [x] Disable hyperlink auditing
- [ ] Prevent WebRTC from leaking local IP addresses

- [ ] Disable cosmetic filtering
- [ ] Block media elements larger than 50 kB
- [ ] Block remote fonts

- OS/version: Arch Linux
- Browser/version: Firefox 54.0
- uBlock Origin version: 1.13.7b1

##### Your filter lists

Not relevant.

##### Your custom filters (if any)

Not relevant.

**Comment by gorhill** [comment] 2017-07-06 00:13
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-07-06 00:13 UTC

**Comment by SoniEx2** [comment] 2017-07-06 00:14
What do you mean this isn't a bug? The logger is supposed to log all connections, including websockets, no?

**Comment by gorhill** [comment] 2017-07-06 00:21
You did not provide a URL, there is no way for me to investigate. Also remember that the logger is forward-looking, **as stated in the documentation**.

**Comment by SoniEx2** [comment] 2017-07-06 00:25
I don't see websocket ping packets in the logger. I don't see websocket data in the logger. Those things happen after opening the logger.

Also, do you have a mastodon account? Because there are many mastodon instances, I can't really link mine if yours is not the same as mine. (mastodon is an app, not a protocol, so there isn't much difference between the instances. they all use websockets.)

**Comment by gorhill** [comment] 2017-07-06 00:30
> I don't see websocket ping packets in the logger.

uBO handles a websocket connection attempt, not the subsequent packets -- that would just make no sense.

> Also, do you have a mastodon account?

No clue what is "mastodon".

**Comment by SoniEx2** [comment] 2017-07-06 00:48
Aw no DPI?

**Comment by bershan2** [comment] 2017-07-06 00:57
@SoniEx2 Fist of all, are you talking about a [social network](https://joinmastodon.org/)? (I just Googled it.) If so, then it is a it is a distributed system with 1493 nodes, it seems. Would be nice if you could provide a link to test or verify that this issue occurs on multiple servers.
Secondly, what is the problem? Do you login (load a page) and only then open the logger? If so, then maybe there is nothing to display: the page had already loaded. Or do you load a page while the logger is open?

**Comment by SoniEx2** [comment] 2017-07-06 01:00
The social network uses websockets for realtime feeds and stuff. Anyway, this is getting off-topic.

**Comment by uBlock-user** [comment] 2017-07-06 08:54
Test link - https://mastodon.xyz/web/getting-started

![](https://i.gyazo.com/b37d4f518f9695a3cb1c1246a0a00f4f.png)

Works fine, you will need an account.

**Comment by bershan2** [comment] 2017-07-06 16:19
I joined https://mstdn2017.club specifically to test this issue (it took them a while to send me the activation email). All pages I tested were logging plenty of requests: 
 - https://mstdn2017.club/web/timelines/public/local
 - https://mstdn2017.club/web/timelines/public
 - https://mstdn2017.club/about/more
 - https://mstdn2017.club/settings/preferences

I do not understand what the issue is. Possibly, the resources are served from cache, then they would not generate network requests. That is very likely, considering how small the instance I'm using is (only 2 users total). If instance has small amount of content or you are opening the same pages with the same posts, there would be no items in the logger.

Once again, to test your problem we need your URL.

**Comment by SoniEx2** [comment] 2017-07-06 16:45
Well ok, I'm on https://witches.town/, but you're not supposed to click anything, you're supposed to wait for background refresh. But from what I gathered here WS data isn't logged and can't be filtered so the best way to run ads and tracking is to WS traffic through your server (using the same WS as for user content).

**Comment by uBlock-user** [comment] 2017-07-07 19:24
@SoniEx2 I'm on Chromium, so the issue is is related to webextensions or isolated to your end only.
