### ISSUE TITLE
Malware Domain List​​​​​ - Network error..... it's normal ?

### ISSUE THREAD

**Issue by DjDiabolik** [gorhill/uBlock#3182] opened 2017-10-30 18:52 UTC
### Describe the issue
I have eliminated all cache..... refresh all but i obtain an errors on this filter.......

It's possibly a double filter ? I have also a malware domain...... 
### One or more specific URLs where the issue occurs
http://www.malwaredomainlist.com

- OS/version: Windows 10 x64
- Browser/version: Firefox 56.0.2
- uBlock Origin version:  Latest 1.14.16

##### Your filter lists

Default

##### Your custom filters (if any)
Nothigs

**Comment by gorhill** [comment] 2017-10-30 19:05
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-10-30 19:05 UTC
Labels: invalid

**Comment by gwarser** [comment] 2017-10-30 19:30
This is problem on your side. Your ISP, connection, anti virus, another extension - check them.

**Comment by uBlock-user** [comment] 2017-10-30 19:35
The problem is on MDL's end, I also am not able to update MDL list, although nothing to do with uBO itself.

**Comment by DjDiabolik** [comment] 2017-10-31 10:01
mmmmmmmm.. i have also installed uBO on a portable chrome.... and here apparently all works.
If i click on it i see this:
moz-extension://5eaa0ce4-d3ae-464f-b327-33207123735f/asset-viewer.html?url=malware-0

Report this:
# MalwareDomainList.com Hosts List # 
# http://www.malwaredomainlist.com/hostslist/hosts.txt # 
# Last updated: Thu, 26 Oct 17 13:51:30 +0000 # 

Apparently it's same filter active on chrome but i don't understand because on firefox i have a little symbol say "Networks problems"....

**Comment by gorhill** [comment] 2017-10-31 10:18
uBO is not responsible for remote servers not responding.

**Comment by DjDiabolik** [comment] 2017-10-31 16:21
^^ yeah... i understand this right now. At this point i need only other people feedback as it confirms that the problem is not just mine.....

**Comment by gwarser** [comment] 2017-10-31 17:31
https://www.reddit.com/r/uBlockOrigin/comments/728m5i/unable_to_update_filters/dnmcmcy/

**Comment by DjDiabolik** [comment] 2017-11-01 18:29
@gwarser it's not released to all filters..... apparently only MDL report this....... only on firefox. 
I have also ublock on chrome and here all it's update correctly..........

**Comment by stonecrusher** [comment] 2018-03-17 15:56
Same problem here. It's a problem of MDL servers.
Tested with both german biggest ISPs (marketshare >60%) which don't have a "broadband shield" blocking setting.
Sometimes it works, most of the time it doesn't. The whole domain `malwaredomainlist.com` is either very slow or unresponsive from here.
Worth considering to remove MDL from the default activated lists.

**Comment by HateAds** [comment] 2018-03-19 22:15
@DjDiabolik @gorhill @gwarser @uBlock-user @stonecrusher 
I have the same problem. 
I constantly have problems with just this filter list. I just keep clicking "Update Now", sometimes it takes 10+ tries.

**Comment by uBlock-user** [comment] 2018-03-20 05:19
It's MDN's server issue, I tried opening the list page and the same issue occurs on the first connection. Their server's having issues.

**Comment by DjDiabolik** [comment] 2018-03-21 10:50
@HateAds mmmmmmmmmm... thanks for info.
