### ISSUE TITLE
Change in 1.14.18 that affected visibility of forms in iframes?

### ISSUE THREAD

**Issue by thauk-copperleaf** [gorhill/uBlock#3262] opened 2017-11-22 01:36 UTC
I am experiencing an issue on Windows 7 with Chrome 61 (and Chrome Canary 64). I have a form inside an iframe, and the form's visibility is `visible` when the page loads with 1.14.16 (and .14, .10, and .6), but the attribute is set to `hidden` when I load the page with 1.14.18 (and the latest prerelease version 1.14.19b10). I don't see any obvious change here https://github.com/gorhill/uBlock/compare/1.14.16...1.14.18 that would hint at how/why this happened. Can anyone enlighten me?

**Comment by gorhill** [comment] 2017-11-22 02:05
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-11-22 02:05 UTC
Labels: invalid

**Comment by thauk-copperleaf** [comment] 2017-11-22 23:09
@gorhill Sorry about that, please tell me what I did wrong and I'll fix it.

I just cloned the repo, and ran `git-bisect`. It looks like https://github.com/gorhill/uBlock/commit/6112a68faf46d89c58defdd9e14d4342747c9523 was the first commit where my issue is reproducible.

**Comment by gorhill** [comment] 2017-11-22 23:52
Exact repro steps -- I can't investigate what I can't reproduce. Also I do not understand your reported issue.

**Comment by thauk-copperleaf** [comment] 2017-11-23 01:35
I'll see if I can come up with something; the system I am reproducing the bug on is not publicly accessible.

**Comment by gorhill** [comment] 2017-11-23 02:15
Are you sure your issue is not a cosmetic filter one?

**Comment by gorhill** [comment] 2017-11-23 02:56
I just checked to be sure and uBO does not touch the `visibility` style property.

**Comment by thauk-copperleaf** [comment] 2017-11-23 03:55
@gorhill I'm not sure what the issue is yet. Just that when I checkout 7f2ee32 and build, the resulting unpacked extension is fine. But with the next commit, 6112a68, I can repro.

**Comment by gorhill** [comment] 2017-11-23 04:43
> I can repro.

This is the problem, I have no idea what you can repro, I still don't know what is the issue you are trying to report.
