### ISSUE TITLE
Cannot Open uBlock Origin on Firefox Android

### ISSUE THREAD

**Issue by christantoan** [gorhill/uBlock#2999] opened 2017-09-10 19:23 UTC
### Describe the issue
Before last update, I could open the dashboard by tapping the uBlock Origin listing in overflow menu. Now when I do the same, it doesn't open anything.

### One or more specific URLs where the issue occurs
None

### Screenshot in which the issue can be seen
Cannot screenshot the issue

### Steps for anyone to reproduce the issue
1. Tap overflow menu in Firefox Android
2. Tap uBlock Origin listing in the list

### Your settings
Should be all defaults. Have tried reinstalling the addon.

- OS/version: Android 6.0.1
- Browser/version: Firefox 55.0.2
- uBlock Origin version: 1.14.4

##### Your filter lists
Default filter lists

##### Your custom filters (if any)
None

**Comment by BilBg** [comment] 2017-09-10 20:13
Read note `Firefox for Android` here:
https://github.com/gorhill/uBlock/releases/tag/1.14.6

**Comment by gorhill** [comment] 2017-09-10 20:25
Duplicate of #2958.

**Closed by gorhill** 2017-09-10 20:25 UTC
Labels: duplicate
