### ISSUE TITLE
Closes all data uri popups in Firefox

### ISSUE THREAD

**Issue by PaulBGD** [gorhill/uBlock#2465] opened 2017-03-20 21:49 UTC
### Describe the issue
When opening a popup with a data URI uBlock Origin closes it immediately, even if "Toggle blocking of all popups on this site" is off.

### One or more specific URLs where the issue occurs

I created a minimal reproduction case: http://codepen.io/PaulBGD/pen/zZRLqR

### Screenshot in which the issue can be seen

Not super visual.

### Steps for anyone to reproduce the issue

1. Have a webpage that opens up a window using `window.open` that has a data URI like data:text/html;base64,

### Your settings

I set up a new Firefox installation with uBlock (so completely defaults) and this occurs. Didn't occur with me in Chrome however.

- Browser/version: 52.0b9 (64-bit)
- uBlock Origin version: 1.11.4

##### Your filter lists

All defaults.

**Comment by gorhill** [comment] 2017-03-20 21:56
What did you do to rule out of filter issue?

**Comment by mapx-** [comment] 2017-03-20 21:57
due to an easylist filter
`|data:text$popup`

add
`@@|data:text$popup,domain=codepen.io`

**Comment by gorhill** [comment] 2017-03-20 21:58
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by mapx-** [comment] 2017-03-20 21:59
however, it seems to be an issue:
`	|data:text$popup	--	popup`

clicking on the -- (to create an exception) does not work

**Closed by gorhill** 2017-03-20 21:58 UTC
Labels: filter list issue, invalid

**Comment by PaulBGD** [comment] 2017-03-20 22:00
Turns out I had uBlock disabled in Chrome, happens there too. I don't know why this is a default filter.

**Comment by gorhill** [comment] 2017-03-20 22:03
> I don't know why this is a default filter.

I do not agree with this filter either, too broad, and worse it often breaks uBO's `popunder` filters for a site. With 1.11.5b2+, you should be able to mark it as bad filter with:

    |data:text$popup,badfilter

**Comment by gorhill** [comment] 2017-03-20 22:05
> clicking on the -- (to create an exception) does not work

I can reproduce. This should be a separate issue though, I can open one if you prefer.

**Comment by mapx-** [comment] 2017-03-20 22:19
does not matter as long as we can have a solution. thanks.

**Comment by uBlock-user** [comment] 2017-03-21 08:35
> I can reproduce. This should be a separate issue though, I can open one if you prefer.

FYI that happens for `about:blank` popups too, clicking on the -- does nothing.

**Comment by gorhill** [comment] 2017-03-21 13:04
@mapx- 

Just for the record, about [this comment](https://issues.adblockplus.org/ticket/5015#comment:21):

> As for uBlock (Origin), it uses a whole different approach, instead of injecting CSS (in batches), they hide each element individually, so that **a single invalid selector doesn't have any implications on other filters**.

This is inaccurate, this is not why uBO did not fail. You described accurately the reason why it did not fail in [your comment](https://issues.adblockplus.org/ticket/5015#comment:20). The filter lists are compiled by uBO, and invalid filters are thrown out at compile time. The parsing/validating is performed once only when a filter list is updated, afterward the compiled version is used to load filters with zero parsing/validating overhead.

**Comment by mapx-** [comment] 2017-03-21 13:37
thanks @gorhill
