### ISSUE TITLE
Youtube not working properly on Safari

### ISSUE THREAD

**Issue by mihainb** [gorhill/uBlock#2474] opened 2017-03-23 21:06 UTC
Only the video can be seen, the rest of the page is blank.

https://www.youtube.com/watch?v=DLm0stV6Oas
--Same thing happens on every video page.

### Screenshot in which the issue can be seen
http://i67.tinypic.com/153vbpd.png

### Steps for anyone to reproduce the issue
1.Go on the youtube homepage.
2.Select any video.
3.Get redirected to the video page. Only the video works, the rest of the page is blank.

### Your settings
Default settings.

- Browser/version: 
- uBlock Origin version: 1.11.3.1

##### Your filter lists
No personal filter lists.

**Comment by gorhill** [comment] 2017-03-23 21:26
Invalid: wrong project.

Submit Safari-specific issue to <https://github.com/el1t/uBlock-Safari>. If you did so, this owuld be a duplicate of <https://github.com/el1t/uBlock-Safari/issues/35>.

**Closed by gorhill** 2017-03-23 21:26 UTC
Labels: invalid
