### ISSUE TITLE
No UBlock icon

### ISSUE THREAD

**Issue by smithjk52** [gorhill/uBlock#236] opened 2015-05-23 19:53 UTC
Just installed uBlock Origin in my Pale Moon browser, setup using the dashboard, but there is no icon to move to the taskbar?  Without it, I can't disable or whitelist or see what is blacked?

**Comment by gorhill** [comment] 2015-05-23 19:56
Duplicate of #40.

**Closed by gorhill** 2015-05-23 19:56 UTC
