### ISSUE TITLE
Polish keyboard ••• need to create "alt + l" ••• uBlock gets open, how to disable hot keys?

### ISSUE THREAD

**Issue by stefek99** [gorhill/uBlock#3031] opened 2017-09-18 06:33 UTC
This character: https://en.wikipedia.org/wiki/%C5%81

<img width="556" alt="screen shot 2017-09-18 at 08 31 02" src="https://user-images.githubusercontent.com/249703/30531026-c8ed0e42-9c4b-11e7-9e37-7ab30d2b1e00.png">

Do not seem to find setting to disable hotkeys in the screenshot above?

**Comment by gwarser** [comment] 2017-09-18 09:08
https://github.com/gorhill/uBlock/search?q=keyboard&type=Issues&utf8=%E2%9C%93

**Comment by gorhill** [comment] 2017-09-18 11:41
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-09-18 11:41 UTC
Labels: invalid

**Comment by stefek99** [comment] 2017-09-20 20:00
So what is the solution then?

Tell me how to disable / remap the shortcuts please.

**Comment by stefek99** [comment] 2017-09-20 20:03
chrome://extensions/

<img width="573" alt="screen shot 2017-09-20 at 21 02 39" src="https://user-images.githubusercontent.com/249703/30664884-1aa079ac-9e47-11e7-8b11-ea08f1181ab4.png">


# OK, got it

Would be nice to allow this directly in uBlock settings.

**Comment by gorhill** [comment] 2017-09-20 21:47
Duplicate of #2723.
