### ISSUE TITLE
After update first party pop up dont work in UO 1.14.12 and high

### ISSUE THREAD

**Issue by dinodinodino** [gorhill/uBlock#3164] opened 2017-10-23 19:56 UTC
In any site before update 1.4.12 the filter option as:
^$popup,first-party
||$popup,domain=example.com
don't work 

In the follow site UO dont Work after update :
 www.guardaserie.online
speedvideo.net

for example this phishing page pop up:
http://www.guardaserie.online/4k/watch.php?u=Y3JhenktZXgtZ2lybGZyaWVuZA==

**Comment by gwarser** [comment] 2017-10-23 20:08
I only see:
22:05:37 |   | /^http:\/\/(?!youtube)[a-zA-Z0-9]{5,20}\.com\/watch\?/$popup | -- | popup | `http://b6roqgi.com/watch?key=16ed117abc23c975869eafd96a7ce309&kw=%5B%22lista%22%2C%22di%22%2C%22tutte%22%2C%22le%22%2C%22serie%22%2C%22tv%22%2C%22guardaserie%22%5D&refer=http%3A%2F%2Fwww.guardaserie.online%2Flista-serie-tv&scrWidth=1280&scrHeight=1024&tz=2`
-- | -- | -- | -- | -- | --

on guardaserie.

**Comment by dinodinodino** [comment] 2017-10-23 20:13
no ,the other pop up are third part, you  must select a series and click  on a episode for example  the magicans  1x01  and after you are redirect in fake page !

**Comment by dinodinodino** [comment] 2017-10-23 20:15
http://www.guardaserie.online/the-magicians-f/ and click an episode

**Comment by gorhill** [comment] 2017-10-23 20:56
Please provide legible, clear step-by-step of what you want me to reproduce. I can barely make sense of what you wrote. I loaded `www.guardaserie.online`, and a movie started to play, and when I clicked, there was no popups.

**Comment by gorhill** [comment] 2017-10-23 20:57
Marking as _invalid_ pending you provide me with clear step to reproduce.

**Comment by dinodinodino** [comment] 2017-10-23 20:58
Ok sorry , i post a video on youtube to show exactly the problem?

**Comment by dinodinodino** [comment] 2017-10-23 21:26
i am not very good to write issue but try  the steps are:

1)go on http://www.guardaserie.online/lista-serie-tv
2) click on  Lucifer now you are in http://www.guardaserie.online/lucifer-cj/
3) click in 3X01 and reclick if no new windows open 
4) now pop up will open in new windows  
![image](https://user-images.githubusercontent.com/33039703/31913984-4f48303e-b849-11e7-9115-b214d5104886.png)

**Comment by dinodinodino** [comment] 2017-10-23 21:26
testing with chrome last versione ublock last version with and without other extension

**Comment by gorhill** [comment] 2017-10-23 21:33
When I enable the [no-popups switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups) on that site, the popups are properly blocked:

![a](https://user-images.githubusercontent.com/585534/31914296-1fc531ee-b818-11e7-9c17-1f7c4d24f493.png)

So what is the issue?

**Comment by gwarser** [comment] 2017-10-23 21:34
This filter will not close this popup:
`|http://www.guardaserie.online/4k/watch.php?u=bHVjaWZlci1jag==$popup`

**Comment by gwarser** [comment] 2017-10-23 21:41
@gorhill this is not about `b6roqgi.com`! This is about `http://www.guardaserie.online/4k/watch.php?u=bHVjaWZlci1jag==` - you will see only short COLUMBIA intro, and then:

![ad](https://user-images.githubusercontent.com/33039703/31913984-4f48303e-b849-11e7-9115-b214d5104886.png)

**Comment by dinodinodino** [comment] 2017-10-23 21:42
perfect  exactly |http://www.guardaserie.online/4k/...  in this case UO don't work
![image](https://user-images.githubusercontent.com/33039703/31914630-b5488044-b84b-11e7-96ef-10c38883a609.png)
before update filter works now no !
@gorhill

**Comment by gorhill** [comment] 2017-10-23 21:57
Well the link clicked in really `http://www.guardaserie.online/4k/watch.php?u=bHVjaWZlci1jag==`, so as per fix to many complaints out there, if the popup is that of the link clicked, and if the click is marked as trusted, uBO won't block the popup.

**Comment by dinodinodino** [comment] 2017-10-23 22:01
i use  the filter with important  option 
http://www.guardaserie.online/4k/^$popup,first-party,important
and don't work , what is the solution ?

@gorhill

**Comment by gorhill** [comment] 2017-10-23 22:07
> what is the solution ?

I don't know. Consider that the bug I fixed was to prevent "false positives" such as:

- Go to `http://www.guardaserie.online/lista-serie-tv`
- Right-click on "Soy Luna" and select "Open link in new tab"
- Before the fix: the new tab was automatically closed by uBO. After the fix: it opens correctly.

You want the previous behavior. Many others wanted the new ones.

**Comment by okiehsch** [comment] 2017-10-23 22:15
I think the current behaviour is preferrable, because it prevents false positives.
For this specific case I do not see any solution preventing the popup, but ou can add something like
`||guardaserie.online/4k/watch.php$first-party,document` to prevent the popup from loading.

**Comment by dinodinodino** [comment] 2017-10-23 22:22
Uou can insert a switch(use old oer new implamentation for example?) , a keyword to block first part pop up ?
In this way i cannot block  first party  pop up in never site, the software is bugged , because  i use this menu 
![image](https://user-images.githubusercontent.com/33039703/31915913-a328d4fe-b850-11e7-870b-f14a9dcc1f39.png)
 and not work !

In my opinion thi  is a bug!  
You cannot search  to implement a keyword for block first party menu and one to allow open in new tab?

There are a lot of site with this problem and before ublock was  perfect

**Comment by dinodinodino** [comment] 2017-10-23 22:48
Never work , the are too site that use auto pop up , for example speedvideo.net
![image](https://user-images.githubusercontent.com/33039703/31916848-ef89a810-b854-11e7-9a88-1d07e664399b.png)

**Comment by gorhill** [comment] 2017-10-23 22:53
@dinodinodino I don't even know what to say. I was happy to finally fix that recurring complaints about false positives such #2919, and now you are asking me to revert #2919, and dismiss all other users who where not happy with these false positives. To make things more unpleasant, I am at the end point for these complaints, not you.

**Comment by gorhill** [comment] 2017-10-23 23:01
Example of false positives: <https://adblockplus.org/forum/viewtopic.php?p=141887#p141887>. Try to middle click any of the links in there. This was reported also on ABP's issue tracker: <https://issues.adblockplus.org/ticket/3249>. This is what #2919 fixed.

**Comment by okiehsch** [comment] 2017-10-23 23:08
@dinodinodino for speedvideo.net
`speedvideo.net##a[href^="http://speedvideo.net/fhud/"]` works on my end
Example: `http://speedvideo.net/4q1q8u5kbxmo`

**Comment by dinodinodino** [comment] 2017-10-23 23:09
@gorhill  

I'm sorry to look unpleasant, and I thank you very much for your commitment, but the false positives I could fix them somehow in consoles, but I can not block these pop ups in any way.

I just wonder if you can, add an option that somehow allows you to block those pop ups!
for example a checkbox that allows the user to choose which of the 2 versions to choose!
and thanks for your  courtesy

I believe so much in UO, and I would like it to be perfect even from this point of view!

@gorhill

**Comment by gorhill** [comment] 2017-10-24 10:45
Duplicate of #3133.

**Closed by gorhill** 2017-10-24 10:45 UTC
Labels: duplicate, invalid

**Comment by dinodinodino** [comment] 2017-10-24 11:35
Ok Thnaks , for now i use pop strict as pop up blocker for firsty party pop up !

I hope a day to improve UO  , thanks for supports  @gorhill

**Comment by gorhill** [comment] 2017-10-24 12:05
I looked into a special advanced setting for this, but it turns out this is not trivial at all. The setting itself is easy to implement, but adding many code paths to deal with that one setting is too risky, I am pretty sure I would end up pretty something else given how the code dealing with popups has grown complicated to take care of all already existing special cases.

**Comment by dinodinodino** [comment] 2017-10-24 20:31
@gorhill 
could not you leave a betatester version with a warning of possible bugs?
Io sarei felice di fare il beta tester !

I'm a programmer, but I'm not expert about web languages, I can still learn

Anyway, I would like to help to perfect ublock origin, the best adblocker in the world!

**Comment by mapx-** [comment] 2017-10-24 21:12
dev builds:
Firefox:
https://addons.mozilla.org/it/firefox/addon/ublock-origin/versions/beta

Chrome:
https://chrome.google.com/webstore/detail/ublock-origin-dev-build/cgbcahbpdhpcegmbfconppldiemgcoii

**Comment by dinodinodino** [comment] 2017-10-24 21:29
@mapx-   thanks , I try last version of ubo and wait update that allow  first party pop up and resolve a bug new tab in the same time

**Comment by gwarser** [comment] 2017-10-24 22:24
@gorhill I now have repro case where this filter `/\.com\/.*[0-9]{6,9}\/\?/$popup` from "Fanboy’s Enhanced Tracking List" blocks Facebook new tabs when browsing photos on Facebook Group. 
Still cannot make filter to block guardaserie.online popups. 

???
