### ISSUE TITLE
no-remote-fonts should block connections to fonts.googleapis.com and typekit.net

### ISSUE THREAD

**Issue by anewuser** [gorhill/uBlock#663] opened 2015-08-29 19:12 UTC
I have this rule and it does block the direct download of web fonts:

```
no-remote-fonts: geektv.me true
```

However, connections to fonts.googleapis.com are still made to download its CSS containers for the fonts. Example page: http://geektv.me/watch-online/the-simpsons

![Example screenshot](https://cloud.githubusercontent.com/assets/6733770/9563786/e6dcf9f2-4e65-11e5-902d-be6ad4d4de56.png)

Here's the contents of https://fonts.googleapis.com/css?family=Maven+Pro:400,700,500,900 , as an example:

```
@font-face {
  font-family: 'Maven Pro';
  font-style: normal;
  font-weight: 400;
  src: local('Maven Pro Regular'), local('MavenProRegular'), url(https://fonts.gstatic.com/s/mavenpro/v7/MG9KbUZFchDs94Tbv9U-pVtXRa8TVwTICgirnJhmVJw.woff2) format('woff2');
}
@font-face {
  font-family: 'Maven Pro';
  font-style: normal;
  font-weight: 500;
  src: local('Maven Pro Medium'), local('MavenProMedium'), url(https://fonts.gstatic.com/s/mavenpro/v7/SQVfzoJBbj9t3aVcmbspRugdm0LZdjqr5-oayXSOefg.woff2) format('woff2');
}
@font-face {
  font-family: 'Maven Pro';
  font-style: normal;
  font-weight: 700;
  src: local('Maven Pro Bold'), local('MavenProBold'), url(https://fonts.gstatic.com/s/mavenpro/v7/uDssvmXgp7Nj3i336k_dSugdm0LZdjqr5-oayXSOefg.woff2) format('woff2');
}
@font-face {
  font-family: 'Maven Pro';
  font-style: normal;
  font-weight: 900;
  src: local('Maven Pro Black'), local('MavenProBlack'), url(https://fonts.gstatic.com/s/mavenpro/v7/-91TwiFzqeL1F7Kh91APwegdm0LZdjqr5-oayXSOefg.woff2) format('woff2');
}
```

It seems to attempt to load the font locally first, but since most users don't have those fonts, it's downloaded from Google instead, making these CSS connections pointless in case you're blocking remote fonts.

On sites that use typekit.net, such as [this page](http://help.webflow.com/site-settings/fonts), uBlock still also let Firefox connect to use.typekit.net and download a CSS file that includes the font encoded in base64, even if you've blocked remote fonts:

![Example screenshot 2](https://cloud.githubusercontent.com/assets/6733770/9563829/2b7e5d92-4e68-11e5-9fd8-09caa05a96e9.png)

Firefox 41 Beta
uBlock 1.0.0.1

**Comment by CrisBRM** [comment] 2015-08-29 23:11
... Is it not working as intended then? Just block CSS requests to a given hostname.

**Comment by anewuser** [comment] 2015-08-30 00:08
@CrisBRM If you read the whole post you'd learn that even if you don't care about downloading useless resources, Typekit CSS files include the fonts built-in, so no, the toggle isn't working at intended.

**Comment by CrisBRM** [comment] 2015-08-30 00:42
Yeah, it's built in. So what? It doesn't connect to a third party hostname to fetch them (since you're already connected to that domain), so you're not any less or any more fingerprintable.
If you don't want it, just block CSS requests to that specific hostname as well.

**Comment by vdcbb** [comment] 2015-08-30 03:40
You have to use a filter to block those. Try this one: https://www.fanboy.co.nz/fanboy-antifonts.txt

**Comment by anewuser** [comment] 2015-08-30 04:53
@vdcbb Thank you, but I've been here since the beginning. I just want gorhill to be aware of this.

The point is that I *do not* want to block them universally, but just for the sites for which I've disabled remote fonts. gorhill will understand what I have in mind.

**Comment by vdcbb** [comment] 2015-08-30 14:49
@anewuser If you want to block them for specific sites, use the matrix.

Here's discussion around the creation of the no-remote-fonts switch: https://github.com/gorhill/uBlock/issues/15

**Comment by gorhill** [comment] 2015-08-30 15:10
@anewuser has a point about inline fonts: the main benefit of blocking remote fonts is security, and not blocking inline fonts bypass the first intent. I expect this can be resolved by injecting a proper content security policy directive.

The other aspect, the loading of CSS files which are strictly for font-purpose only, is more debatable. This would means to take on the task of creating and maintaining a list of such resources, and to add "hacky" code to uBlock to equate these specific resources to font resources so that they are blocked/allowed as per the `no-remote-fonts` switch. I am quite less inclined to agree to this.

**Comment by gorhill** [comment] 2017-09-11 15:50
Some altruistic volunteer will have to step up to create a specific font-blocking lists.

**Closed by gorhill** 2017-09-11 15:50 UTC
Labels: declined
