### ISSUE TITLE
Stoped working on 55.0a1 (2017-04-01) (64 bit)

### ISSUE THREAD

**Issue by camper1x** [gorhill/uBlock#2505] opened 2017-04-02 11:32 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Stoped working on 55.0a1 (2017-04-01) (64 bit)
Icon dissapear and blocker stoppe dworking

### One or more specific URLs where the issue occurs

Every link. It's a major bug

### Screenshot in which the issue can be seen

I've got a icon here:
http://i.imgur.com/M1MuxrR.png
And look how looks customize section:
http://i.imgur.com/umCvitK.png

### Steps for anyone to reproduce the issue

1. Installed newer version via ff updater

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 55.0a1
- uBlock Origin version: 1.11.4 - newest

no way to enter settings:
http://i.imgur.com/E5cga8a.png

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

not related

**Comment by li0nsar3c00l** [comment] 2017-04-02 11:34
duplicate of https://github.com/gorhill/uBlock/issues/2504

**Comment by camper1x** [comment] 2017-04-02 11:35
Yup. But with proper infos.

**Comment by camper1x** [comment] 2017-04-02 11:39
1.11.5rc6 working.
So i think it's related to: #2493

**Comment by gorhill** [comment] 2017-04-02 11:44
People using Nightly will have to use the [latest dev build on AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/beta), at least until I release a new version to AMO.

**Comment by gorhill** [comment] 2017-04-02 11:46
Related bugzilla issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1145470>.

**Comment by mangeurdenuage** [comment] 2017-04-03 03:05
@gorhill 
Thank you for pointing that out
Are you aware that the same problem affect uMatrix too ?

**Comment by gorhill** [comment] 2017-04-03 03:12
uMatrix was also fixed, fix available in dev channel on AMO: <https://addons.mozilla.org/en-US/firefox/addon/umatrix/versions/beta>.

**Comment by mangeurdenuage** [comment] 2017-04-03 03:25
@gorhill 
Thank you :)
I wish you a good continuation.

**Closed** 2017-04-03 10:59 UTC
