### ISSUE TITLE
My Filters element hiding rules break on automatic update

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#3238] opened 2017-11-16 14:24 UTC
I have e.g. this filter in "My filters":

```
www.tumblr.com##.status-indicator
```

And it works fine! That is, as long as ublock origin doesn't automatically update while the browser is running.

I don't seem to have this issue with built-in filter lists, only "My filters" seems to have the issue, and only for element hiding rules. (normal blocking/redirect/exception rules continue working even after automatic reinstall/update.)

I believe this can be fixed with startup hooks: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onInstalled (but I'm not an extension developer)

## Steps

1. Go on tumblr
2. Open some messaging chats with some ppl who are online (who display the online indicator)
3. Enable filters
4. Refresh page
5. Notice the lack of online indicators
6. Let uO update, watch as the online indicators come back

## Full Enabled Filter Lists

```
My filters
uBlock filters​
uBlock filters – Badware risks​
uBlock filters – Experimental​
uBlock filters – Privacy
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
AAK-Cont Filters For uBlock Origin​
Adblock Warning Removal List​
EasyList​
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Fanboy’s Annoyance List​
Fanboy’s Social Blocking List​
Peter Lowe’s Ad and tracking server list​
```

## Full "My filters"

```
! 2017-05-03, 5:43:42 PM https://www.tumblr.com/dashboard
www.tumblr.com##.post[data-is_recommended="1"]

! 2017-08-16, 12:27:28 AM https://www.tumblr.com/dashboard
www.tumblr.com##.chat-status-banner

! 2017-08-16, 12:27:45 AM https://www.tumblr.com/dashboard
www.tumblr.com##.status-indicator

! hide tumblr images by default
||media.tumblr.com^$image,domain=www.tumblr.com,redirect=32x32-transparent.png
! show avatars, tho
@@||media.tumblr.com/avatar*$image,domain=www.tumblr.com
```

## Full "My Rules"

```
no-cosmetic-filtering: www.humblebundle.com true
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
```

## Full "Whitelist"

```
beam.pro
behind-the-scene
bintray.com
chisel.team
chrome-extension-scheme
chrome-scheme
https://edit.yahoo.com/config/edit_account?.lang=en-US&.done=https%3A%2F%2Flogin.yahoo.com%2Faccount%2Fpersonalinfo%3F.intl%3Dus%26.lang%3Den-US%26.done%3Dhttps%3A%2F%2Fus-mg5.mail.yahoo.com%2Fneo%2Flaunch%253f.rand%3D6bunhkhnmeg73%26.src%3Dcdgm&.scrumb=vvwv6DvF/a2&.scrumb2=2QnJWJbcXyI
login.yahoo.com
loopconversation.about-scheme
luaconf.com
mikmod.sourceforge.net
minhaclaro.claro.com.br
opera-scheme
permacultureglobal.org
rodrigoejaqueline.com
ruffles.com.br
s.baku89.com
sarahautumn.tumblr.com
stackoverflow.com
www.acessocard.com.br
www.claro.com.br
www.groupon.com.br
www.linksys.com
www.sebrae.com.br
www.vox90.com
www.webhostface.com
```

## Version information

Firefox 57.0 64-bit
Arch Linux x86_64
uBlock Origin 1.14.19b6 (could this be an issue with the beta? I haven't tested it on normal uO yet)

## Enabled settings

```
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
I am an advanced user (required reading)
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing
```

## Other extensions

Violentmonkey (AAK-Cont Userscript For uBlock Origin)
Multi-Account Containers
Video Speed Controller
Decentraleyes
Firefox Pioneer

## about:config

Anyone knows a good way to dump about:config?

**Comment by gorhill** [comment] 2017-11-16 14:27
> Let uO update

uBO itself or the filter lists?

**Comment by SoniEx2** [comment] 2017-11-16 14:29
uBO itself

**Comment by gorhill** [comment] 2017-11-16 14:35
Duplicate of #3185.

Why create a new issue for the same issue which I labelled as a browser issue? Firefox removes stylesheets injected by an extension when that extension is disabled.

**Comment by SoniEx2** [comment] 2017-11-16 14:36
Then use a startup hook.

**Closed by gorhill** 2017-11-16 14:35 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2017-11-16 14:39
If you think you know how to solve this, add to the existing issue, do not re-open the same one just for the sake of adding five words to it.
