### ISSUE TITLE
FireFox 59 performance degradation

### ISSUE THREAD

**Issue by sarsenyev** [gorhill/uBlock#3484] opened 2018-02-05 15:47 UTC
I've some problem with 59 Beta (Win 32 bit on Win 10x64). 1.15.4 (and 1.14.* too)
On 58 all fine
For example
https://mozilla.github.io/arewefastyet-speedometer/2.0/
FF 58 with uBlockO ~60 points
FF 59 with uBlockO ~ 20-30 points (and its really slowly)
FF 59 without uBlockO ~ 60 points

Same degradation are present not only this site.
Is it only my computer shows this degradation?

**Comment by gorhill** [comment] 2018-02-05 15:56
Duplicate of #2552.

**Closed by gorhill** 2018-02-05 15:56 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2018-02-05 15:58
Also: <https://bugzilla.mozilla.org/show_bug.cgi?id=1418161>.

**Comment by sarsenyev** [comment] 2018-02-06 10:12
Sorry for duplication.

I'm was wrong. Problem neither only in stylo nor 58->59
It's win32 issue. If x64 degradation about 10%, win32  shows 2-3 times.

Thanks.
