### ISSUE TITLE
uBlock breaks Paypal Payments through ebay

### ISSUE THREAD

**Issue by schlaubstar** [gorhill/uBlock#2998] opened 2017-09-10 17:13 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Hello together: I have seen that a similar issue has been posted in the past but at that time it was not uBlock causing the problem but what happens to me is that I can not complete a payment with paypal after checking out on ebay, as long uBlock is enabled.

I have disabled all filters and purged caches (because I first assumed that it's a filter causing the issue): No change

If I disable uBlock itself (as extension in firefox) everything works as assumed.

In Firebug I have tracked down one request that reloads endlessly when uBlock is enabled. This request is being terminated very quickly if uBlock is disabled and then the payment procedure continues.

### One or more specific URLs where the issue occurs

https://pay.ebay.de/xo?action=view&sessionid=72002148xxxx
(Sorry: You can't reproduce it using my session)

### Screenshot in which the issue can be seen

Screenshot 1 : all Filters were disabled and caches purged

![2017-09-10 18_53_25-kaufabwicklung](https://user-images.githubusercontent.com/25862995/30251164-96dd3d74-965a-11e7-873d-faf0d11b3608.png)

Screenshot 2 : this is where it ends up with enabled uBlock
![2017-09-10 18_53_53-kaufabwicklung](https://user-images.githubusercontent.com/25862995/30251177-c9d58808-965a-11e7-9d99-b0e4cee2165d.png)

Screenshot 3 : the request that never terminates when uBlock is enabled
![2017-09-10 18_55_02-firebug - kaufabwicklung](https://user-images.githubusercontent.com/25862995/30251180-d616b74a-965a-11e7-8732-654be911c9cf.png)

### Steps for anyone to reproduce the issue

Go to ebay.de 
Add at least one article to your shopping basket
proceed to checkout 
sign in (if you have not already)
Select PayPal as payment method
Enter Login Data and submit 
(if it should work in an accident: don't worry - you can still cancel the transaction)

It does not work on EBAY.com - At ebay.com you have to enter the paypal credentials in a new tab/window/browser session and not like in germany inline (a div?)

### Your settings
- OS/version: Windows 7 x64
- Browser/version:  Firefox 53.0.3 (64-bit)
- uBlock Origin version: 1.14.4

##### Your filter lists

in my usecase all filters were disabled and caches purged

**Comment by gorhill** [comment] 2017-09-10 17:22
Duplicate of #2967.

**Closed by gorhill** 2017-09-10 17:22 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2017-09-10 17:24
Try these:

- Ensure e10s is turned on

If you can't turn in on because you are using legacy extensions, then disable these legacy extensions.

If this still fail, then you will have to wait for a fix from Firefox devs.
