### ISSUE TITLE
URLs loaded by Firefox's MIME processing system are not treated as first-party pages

### ISSUE THREAD

**Issue by Gitoffthelawn** [gorhill/uBlock#1861] opened 2016-08-05 04:07 UTC
**Bug Report Synopsis:**

URLs loaded by Firefox's MIME processing system are not treated by uBlock Origin as first-party pages.

**Test Environment:**

uBlock Origin version: 1.8.0
Firefox version: 48.0.0 (applies to 32-bit and 64-bit)

**Steps To Reproduce:**
1. Clean install Firefox 48.0.0 (32-bit or 64-bit) or create a new Firefox profile in an existing installation of Firefox 48.0.0.
2. Install uBlock Origin v1.8.0.
3. Create the following static filter: `||google.com^$third-party`
4. Apply the static filter.
5. Load any webpage with a `mailto` link (ex: http://www.webdevelopersnotes.com/html-mailto-attribute-html-tips )
6. Click on a `mailto` link in that page (or if you are viewing this bug report in a web browser, just click [here](mailto:bugreport@ublockoriginbugreport.com))
7. Firefox will prompt for which app to handle the `mailto` link.
8. Select Gmail.

**What Is Expected:**

 Gmail should attempt to create a new message with the `To` field specified by the email address in the `mailto` link.  Because there are no cookies stored for Gmail (see Step 1 above), it should first load the initial Gmail login page.

**What Will Occur:**

 Gmail will not load.

**Why This Is Happening:**

 Firefox is trying to process `mail.google.com` (as specified in the default `mimeTypes.rdf`), but uBlock Origin considers the source of the page to be the page from Step 5, and not `mail.google.com` .  Because of this, the `$third-party` is triggered in the filter created in Steps 3 and 4.  This causes an error within `mail.google.com` and the page never loads.

**Recommendation:**
 When a URL is loaded by Firefox's MIME processing system in response to the user clicking on a link, treat that URL as a first-party URL, similar to how it would be treated if it was entered in the `#urlbar`.

**Comment by gorhill** [comment] 2016-08-05 11:59
I had to put in tracing code since I could not make sense of uBO's logger output. Here is what is occurring internally:

    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 4 "chrome://global/locale/intl.css" frameModule.js:202
    shouldLoad 3 moz-icon://stock/gtk-cancel?size=button frameModule.js:202
    shouldLoad 3 moz-icon://stock/gtk-ok?size=button frameModule.js:202
    http-on-modify-request 3 "https://compose.mail.yahoo.com/favicon.ico" vapi-background.js:2249:9
    http-on-modify-request 3 "https://mail.google.com/favicon.ico" vapi-background.js:2249:9
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    http-on-modify-request 3 "https://ssl.gstatic.com/ui/v1/icons/mail/favicon.ico" vapi-background.js:2223:13
    http-on-modify-request 1 "https://mail.google.com/mail/?extsrc=mailto&url=mailto%3Abugreport%40ublockoriginbugreport.com" vapi-background.js:2249:9
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    http-on-modify-request 1 "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?extsrc%3Dmailto%26url%3Dmailto:bugreport@ublockoriginbugreport.com&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1" vapi-background.js:2223:13
    location change "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?extsrc%3Dmailto%26url%3Dmailto:bugreport@ublockoriginbugreport.com&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1" frameModule.js:493
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "https://www.gstatic.com/images/icons/material/system/1x/arrow_back_grey600_24dp.png" frameModule.js:202
    shouldLoad 3 "https://ssl.gstatic.com/images/icons/ui/common/universal_language_settings-21.png" frameModule.js:202
    shouldLoad 7 "https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-1635060532&timestamp=1470397467321" frameModule.js:202
    http-on-modify-request 7 "https://accounts.youtube.com/accounts/CheckConnection?pmpo=https%3A%2F%2Faccounts.google.com&v=-1635060532&timestamp=1470397467321" vapi-background.js:2249:9
    shouldLoad 7 about:blank frameModule.js:202
    shouldLoad 6 "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?extsrc%3Dmailto%26url%3Dmailto:bugreport@ublockoriginbugreport.com&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1#identifier" frameModule.js:202
    location change "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?extsrc%3Dmailto%26url%3Dmailto:bugreport@ublockoriginbugreport.com&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1#identifier" frameModule.js:493
    shouldLoad 3 "https://ssl.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_112x36dp.png" frameModule.js:202
    shouldLoad 3 "https://ssl.gstatic.com/accounts/ui/avatar_2x.png" frameModule.js:202
    shouldLoad 3 data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAWgAAAAGCAIAAABhDpMcAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3gkeFxks6YflLAAAAKlJREFUWMPt2CEShDAMheGmMCFV1MH9z8MtarC4QKfNiuwwOyxHeJ9r6iJ+ETKz3vu+7/M8D8MQAADetNaO41jXNcYYfUREpZRaK7YDAP9qraUUIvLn6NVg5t77tm2qamZYEwDciEhElmVhZm/H6B8ppZxzCOE8T4QDAB7hmKYp55xS+k48E601VVXV67oQDgB4hIOZRURE/BJKv5kwM1QDAF7bcR84Qggf4ShHovU/ogcAAAAASUVORK5CYII= frameModule.js:202
    shouldLoad 3 "https://ssl.gstatic.com/accounts/ui/wlogostrip_230x17_1x.png" frameModule.js:202
    shouldLoad 14 "https://fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTegdm0LZdjqr5-oayXSOefg.woff2" frameModule.js:202
    http-on-modify-request 14 "https://fonts.gstatic.com/s/opensans/v13/DXI1ORHCpsQm3Vp6mXoaTegdm0LZdjqr5-oayXSOefg.woff2" vapi-background.js:2249:9
    shouldLoad 14 "https://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2" frameModule.js:202
    http-on-modify-request 14 "https://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2" vapi-background.js:2249:9
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "https://mail.google.com/mail/images/cleardot.gif?t=1470397467373" frameModule.js:202
    http-on-modify-request 3 "https://mail.google.com/mail/images/cleardot.gif?t=1470397467373" vapi-background.js:2249:9
    http-on-modify-request 3 "https://accounts.google.com/favicon.ico" vapi-background.js:2249:9
    http-on-modify-request 3 "https://www.google.com/favicon.ico" vapi-background.js:2223:13
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel.png" frameModule.js:202
    shouldLoad 3 "chrome://browser/skin/menuPanel-small.png" frameModule.js:202

The following events specifically shows the issue:

    http-on-modify-request 1 "https://mail.google.com/mail/?extsrc=mailto&url=mailto%3Abugreport%40ublockoriginbugreport.com" vapi-background.js:2249:9
    ...
    http-on-modify-request 1 "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?extsrc%3Dmailto%26url%3Dmailto:bugreport@ublockoriginbugreport.com&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1" vapi-background.js:2223:13
    location change "https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.google.com/mail/?extsrc%3Dmailto%26url%3Dmailto:bugreport@ublockoriginbugreport.com&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1" frameModule.js:49

So the problem is:

- Content policy handler `shouldLoad` is not called for `https://mail.google.com/mail/?extsrc=mailto&...`
-The HTTP request observer is called for `https://mail.google.com/mail/?extsrc=mailto&...`, but with the type `other` instead of `main_frame`.
- Eventually the location change observer is calledm but after the original, wrongly typed resource above has been processed.

_Probably_ all would work fine if the document `https://mail.google.com/mail/?extsrc=mailto&...` was at least called with the proper type in the HTTP observer.

Given the information uBO is given, I don't see any way to fix this. The only thing I can come up with are filters to works around the issue:

    @@||mail.google.com/mail/?extsrc=mailto&url=mailto
    @@||accounts.google.com/ServiceLogin$other

**Comment by Gitoffthelawn** [comment] 2016-08-05 20:38
> - Eventually the location change observer is called, but after the original, wrongly typed resource above has been processed.

> _Probably_ all would work fine if the document `https://mail.google.com/mail/?extsrc=mailto&...` was at least called with the proper type in the HTTP observer.

Is that indicative of a bug in Firefox?

**Comment by gorhill** [comment] 2017-09-09 18:01
No longer an issue with WebExtensions. If the issue still exists with the legacy version of uBO, it's a ` wontfix`.

**Closed by gorhill** 2017-09-09 18:01 UTC
Labels: wontfix
