### ISSUE TITLE
[Suggestion] In logger, add button to hide entries not affected by uBO

### ISSUE THREAD

**Issue by stonecrusher** [gorhill/uBlock#3452] opened 2018-01-21 12:05 UTC
In the network logger (list view) it would be great to have a switch to filter all network requests that weren't affected by uBO. Everything that is not red, green or yellow should be hidden when activated.

It would be the equivalent of writing `|<< || |++ || |-- || |## ` before a searchword into the filter field, which of course is annoying to do manually.
I guess adding `bts` keyword to the string is not necessary, as bts requests always come with either <<, ++ or -- unlike DOM elements? Just not to miss any entries.
Note the trailing space to have the filter field ready to search for domains or something.

uBO 1.14.24

**Comment by gorhill** [comment] 2018-01-21 13:04
Duplicate of #787.

**Closed by gorhill** 2018-01-21 13:04 UTC
Labels: duplicate
