### ISSUE TITLE
Popup window closes after hitting reload button

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#3415] opened 2018-01-08 10:15 UTC
### Describe the issue
Popup window closes after hitting reload button, which is inconvenient.

### One or more specific URLs where the issue occurs
https://www.youtube.com/

### Steps for anyone to reproduce the issue

1. open www.youtube.com
1. block doubleclick.net
1. hit reload
1. popup closes

### Your settings

- OS/version: Windows 10 x64 v1607
- Browser/version: Google Chrome 64.0.3282.71 (Official Build) beta (64-bit)
- uBlock Origin version: 1.14.23.15

##### Your filter lists
```
  "selectedFilterLists": [
    "https://filters.adtidy.org/extension/ublock/filters/4.txt",
    "https://easylist-downloads.adblockplus.org/cntblock.txt",
    "https://easylist-downloads.adblockplus.org/bitblock.txt",
    "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt",
    "https://raw.githubusercontent.com/jspenguin2017/uBlockProtector/master/uBlockProtectorList.txt",
    "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
    "RUS-0",
    "hphosts",
    "fanboy-thirdparty_social",
    "fanboy-annoyance",
    "spam404-0",
    "malware-1",
    "disconnect-malvertising",
    "fanboy-enhanced",
    "easyprivacy",
    "adguard-spyware",
    "easylist",
    "adguard-generic",
    "awrl-0",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-experimental",
    "ublock-badware",
    "ublock-annoyances",
    "ublock-filters",
    "user-filters"
  ],
```

**Comment by mikhaelkh** [comment] 2018-01-08 14:20
Also tried Google Chrome 63.0.3239.132 (same result) and Firefox 58.0b14 (64-bit) (popup stays open). Maybe Chrome and/or Windows - related bug?

**Comment by gorhill** [comment] 2018-01-08 14:34
> Maybe Chrome and/or Windows - related issue?

Maybe. Another extension? Custom flags?

**Comment by mikhaelkh** [comment] 2018-01-08 14:46
63.0.3239.132 (64-bit) and uBlock 1.14.22:
I have few extensions, but I've disabled them all. No flags. uBO default settings + "I am an advanced user".

**Comment by gorhill** [comment] 2018-01-08 15:20
Can't reproduce, so you will have to investigate the cause on your side. If other people can reproduce, then they can share findings.

**Comment by stonecrusher** [comment] 2018-01-21 16:42
I  can reproduce with `uBO 1.14.24`:
`Windows 8.1 x64`  `Chrome  63.0.3239.132 (64-Bit)`

Does **not** happen with
`Windows 7 x32` `Chrome 63.0.3239.132 (32-bit)`
`Windows 7 x32` `FF 57.0.4 (32-Bit)`
`Windows 7 x32` `FF 59.0a1 (2018-01-21) (32-Bit)`
`Windows 8.1 x64` `FF 57.0.4 (64-Bit)`
`Windows 8.1 x64` `FF 59.0a1 (2018-01-21) (64-Bit)`

It's independent from what you block / allow / whatever.
It's independent from what website you are on.
As soon as you press that big refresh button, the popup is closed.

**Comment by gorhill** [comment] 2018-01-25 20:58
Marking as browser issue, report to Chromium devs.

**Closed by gorhill** 2018-01-25 20:58 UTC
Labels: browser bug, unable to reproduce
