### ISSUE TITLE
Slower update for chromium

### ISSUE THREAD

**Issue by alain1965** [gorhill/uBlock#975] opened 2015-11-25 11:23 UTC
Hello, why ublock origin updates slower for chromium and Chrome than for Firefox ? Is it a problem with Chrome web store, with blink or other ? Thank.

**Comment by harshanvn** [comment] 2015-11-25 11:29
a similar ticket exist before <a href="https://github.com/gorhill/uBlock/issues/530">here..</a>

**Comment by gorhill** [comment] 2015-11-25 13:48
Duplicate of #530.

**Closed by gorhill** 2015-11-25 13:48 UTC

**Comment by gorhill** [comment] 2015-11-25 13:53
Also, if you look at the release notes, you will see that there was not much changes for non-Firefox browsers, only [one minor issue](https://github.com/gorhill/uBlock/issues/842) fixed since 1.3.3, so not really worth to update the extension in the Chrome store.
