### ISSUE TITLE
Kaspersky flagging uBlock Origin (Chrome and Firefox) for containing Trojan.Win32.Hosts2.gen

### ISSUE THREAD

**Issue by TheStash** [gorhill/uBlock#199] opened 2015-05-15 15:18 UTC
uBlock Origin 0.9.5.0 Firefox (Download Source: https://addons.mozilla.org/firefox/addon/ublock-origin/)
uBlock Origin 0.9.7.0 Chrome (Download Source: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)

Kaspersky Internet Security 15.0.2.361 (File Anti-Virus & Web Anti-Virus Heurisitics are set at Deep-Scan)... i generally never encountered any issues with this settings with every day usage, as Kaspersky has low false positive rate.

Kaspersky logs screenshot:
![ublockorigin](https://cloud.githubusercontent.com/assets/11326414/7655640/1958f56e-fb25-11e4-9d77-97bf15b096ae.PNG)

**Comment by gorhill** [comment] 2015-05-15 15:21
Duplicate of <https://github.com/chrisaljoudi/uBlock/issues/763>.

**Closed as completed by gorhill** 2015-05-15 15:21 UTC

**Comment by TheStash** [comment] 2015-05-15 15:30
Does deleting or disinfecting the malicious object cause the extension not to function properly?

**Comment by gorhill** [comment] 2015-05-15 15:33
Not sure what Kaspersky deleted.

If it only deletes `assets/thirdparties/someonewhocares.org/hosts/hosts`, it should work fine, unless you select that filter list, in which case it won't load obviously.

**Comment by gorhill** [comment] 2015-05-15 15:34
Actually, if it's on Chrome, you will have issue as Chrome will consider that the extension package has been tampered with and will flag it as such in the _Extensions_ page.

**Comment by TheStash** [comment] 2015-05-15 15:42
Chrome didn't flag it (yet) in the extensions page, and i am not really using this filter, but it is actually a bit scary when Kaspersky flags it, given their reputation and your user base type (people who care about privacy and security)

Thank you for you work :-)
