### ISSUE TITLE
 uBlock Origin 1.11.4 is not working in latest Firefox nighty

### ISSUE THREAD

**Issue by HuMuK** [gorhill/uBlock#2510] opened 2017-04-03 09:02 UTC
After last update (55.0a1 (2017-04-02) (64-bit)) uBlock icon disappeared with all functions. It is still installed, but not working.

The only option is to use uBlock Origin v1.11.5rc7. How soon it will be the main release?

**Comment by gorhill** [comment] 2017-04-03 11:10
Duplicate of #2505.

**Closed by gorhill** 2017-04-03 11:10 UTC
