### ISSUE TITLE
百度点击链接后广告重现且正文消失

### ISSUE THREAD

**Issue by liangshengzero** [gorhill/uBlock#1741] opened 2016-06-21 05:19 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
例如百度搜索chrome，点击chrom官方网址，新标签页打开后，原百度搜索页面右侧广告重现且移到左侧，刷新后正常

### One or more specific URLs where the issue occurs
https://www.baidu.com/s?wd=chrome&rsv_spt=1&rsv_iqid=0xda07fc77000e81dc&issp=1&f=8&rsv_bp=0&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_sug3=2&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=2142&rsv_sug4=2142

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
![ashampoo_snap_2016 06 21_13h10m55s_001_](https://cloud.githubusercontent.com/assets/17328925/16218661/88b7314e-37b2-11e6-9224-427f284df82a.jpg)
![ashampoo_snap_2016 06 21_13h11m24s_003_](https://cloud.githubusercontent.com/assets/17328925/16218660/88b6ebbc-37b2-11e6-9f3b-19f57e3e70f6.jpg)

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: chrome 51.0.2704.103 (64-bit)稳定版
- uBlock Origin version: 1.7.4

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
! 2016/6/2 下午2:02:24 http://www.hltm.tv/
www.hltm.tv##.tophead > .warp

! 2016/6/2 下午2:02:28 http://www.hltm.tv/
www.hltm.tv##.tophead

! 2016/6/2 下午2:03:17 http://www.lrshare.com/
www.lrshare.com###text-4 > .textwidget

! 2016/6/2 下午2:03:21 http://www.lrshare.com/
www.lrshare.com###text-4 > .widget-title

! 2016/6/2 下午2:03:29 http://www.lrshare.com/
www.lrshare.com###text-4

! 2016/6/7 下午1:20:59 https://www.youtube.com/
www.youtube.com###video-masthead

! 2016/6/14 上午9:59:13 http://www.ccav1.com/
www.ccav1.com###widget_250

! 2016/6/14 上午9:59:19 http://www.ccav1.com/
www.ccav1.com###widget_25060ad

! 2016/6/14 上午10:07:29 http://www.miduer.com/vpn
||www.miduer.com/wp-content/uploads/2016/06/zhaoshang858.png$image

! 2016/6/14 上午10:07:37 http://www.miduer.com/vpn
||www.miduer.com/wp-content/uploads/2016/06/zhaoshang.png$image

! 2016/6/14 上午10:07:40 http://www.miduer.com/vpn
||www.miduer.com/wp-content/uploads/2016/06/ctrld.jpg$image

! 2016/6/14 上午10:11:02 http://mail.163.com/js6/main.jsp?sid=RCofLFbkUlsFEbwtDhkkmvbKWRrXwpXS&df=mail163_letter#module=compose.ComposeModule%7C%7B%22type%22%3A%22compose%22%2C%22fullScreen%22%3Atrue%2C%22cid%22%3A%22c%3A1465870231017%22%7D
mail.163.com###\31 465870192603_succ > .sQ1 > .nui-txt-bold.nui-txt-s18.nui-block.nui-assistBlock

! 2016/6/14 下午10:58:49 http://jingyan.baidu.com/article/c910274bfbbf1ecd361d2da6.html
jingyan.baidu.com###aside > .wgt-income-money

! 2016/6/15 下午9:41:07 http://tieba.baidu.com/index.html
tieba.baidu.com###adide_platform

! 2016/6/15 下午9:41:16 http://tieba.baidu.com/index.html
tieba.baidu.com###media_item

! 2016/6/15 下午9:42:35 http://tieba.baidu.com/f?kw=%C1%FA%D7%E5%CA%D6%B4%F2%D7%E9&fr=index
tieba.baidu.com###pagelet_encourage-celebrity\/pagelet\/celebrity > .celebrity.aside_region

! 2016/6/15 下午9:42:49 http://tieba.baidu.com/f?kw=%C1%FA%D7%E5%CA%D6%B4%F2%D7%E9&fr=index
||tb2.bdstatic.com/tb/img/userbar_medal_e524bdf.gif$image

! 2016/6/15 下午9:42:54 http://tieba.baidu.com/f?kw=%C1%FA%D7%E5%CA%D6%B4%F2%D7%E9&fr=index
tieba.baidu.com###com_userbar > ul > .u_joinvip > .u_menu_joinvip.u_menu_item > .j_btn_getmember.vip_red.u_joinvip_wrap

! 2016/6/16 下午1:00:09 http://www.bilibilijj.com/
www.bilibilijj.com##.HomeLinks.Links > a[href^="http://www.huanlj.com/"]

! 2016/6/16 下午1:00:35 http://www.bilibilijj.com/
www.bilibilijj.com##.HomeLinks.Links

! 2016/6/17 上午9:24:09 http://51.ruyo.net/shadowsocks/
||i4.buimg.com/381892319bfca0bc.png$image

! 2016/6/17 上午9:24:18 http://51.ruyo.net/shadowsocks/
51.ruyo.net###text-12 > .textwidget

! 2016/6/17 上午9:24:37 http://51.ruyo.net/shadowsocks/
51.ruyo.net###content > .panel-default.panel:nth-of-type(1) > .adsense.panel-body > .glyphicon-fire.glyphicon.alert-success.alert

! 2016/6/17 上午9:24:41 http://51.ruyo.net/shadowsocks/
51.ruyo.net###content > .panel-default.panel:nth-of-type(1)

! 2016/6/19 上午11:54:03 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-3 > .textwidget

! 2016/6/19 上午11:54:14 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-3 > .widget-title

! 2016/6/19 上午11:54:18 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-3

! 2016/6/19 上午11:54:25 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-9 > .textwidget

! 2016/6/19 上午11:54:29 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-12 > .textwidget

! 2016/6/19 上午11:54:38 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-9

! 2016/6/19 上午11:54:46 http://www.lrshare.com/196.html#comment-28482
www.lrshare.com###text-12

! 2016/6/19 上午11:55:09 http://www.lrshare.com/category/windowssoft
www.lrshare.com###text-10 > .textwidget

! 2016/6/19 上午11:55:26 http://www.lrshare.com/category/windowssoft
www.lrshare.com###text-10

! 2016/6/19 上午11:55:31 http://www.lrshare.com/category/windowssoft
www.lrshare.com###text-13 > .textwidget

! 2016/6/19 上午11:55:41 http://www.lrshare.com/category/windowssoft
www.lrshare.com###text-13

! 2016/6/19 下午8:41:15 http://haojian138.blog.163.com/
haojian138.blog.163.com###topbar_yxpArea > .dlditm

! 2016/6/19 下午8:41:19 http://haojian138.blog.163.com/
||b2.bst.126.net/newpage/images/lofterad/topbar/arrow24.png$image

! 2016/6/19 下午8:41:22 http://haojian138.blog.163.com/
||b2.bst.126.net/newpage/images/lofterad/topbar/arrow24.png$image

! 2016/6/19 下午8:41:31 http://haojian138.blog.163.com/
||b2.bst.126.net/newpage/images/lofterad/topbar/arrow24.png$image

! 2016/6/19 下午9:18:59 https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=%E6%84%9F%E5%86%92&oq=%E7%99%BE%E5%BA%A6%E4%BA%91&rsv_pq=a4610a38000dac4d&rsv_t=a8d3wPcw3G2%2BI8gxDFI35GL4X%2FwYtHdZ8Xae%2BoEOkmj%2FV0yP%2FlE%2FKVM1%2FrQ&rqlang=cn&rsv_enter=1&rsv_sug3=3&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=4019&rsv_sug4=4020
www.baidu.com###content_right

**Comment by liangshengzero** [comment] 2016-06-21 05:27
貌似与这条自定义规则有关，但之前复制失败

! 2016/6/19 下午9:18:59 https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=%E6%84%9F%E5%86%92&oq=%E7%99%BE%E5%BA%A6%E4%BA%91&rsv_pq=a4610a38000dac4d&rsv_t=a8d3wPcw3G2%2BI8gxDFI35GL4X%2FwYtHdZ8Xae%2BoEOkmj%2FV0yP%2FlE%2FKVM1%2FrQ&rqlang=cn&rsv_enter=1&rsv_sug3=3&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=4019&rsv_sug4=4020
www.baidu.com###content_right

**Comment by liangshengzero** [comment] 2016-06-21 05:29
貌似与这条自定义规则有关，但发送自动消失 ，我在里面加了汉字试试

! 2016/6/19 下午9:18:59 ht去掉tps://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&tn=baidu&wd=%E6%84%9F%E5%86%92&oq=%E7%99%BE%E5%BA%A6%E4%BA%91&rsv_pq=a4610a38000dac4d&rsv_t=a8d3wPcw3G2%2BI8gxDFI35GL4X%2FwYtHdZ8Xae%2BoEOkmj%2FV0yP%2FlE%2FKVM1%2FrQ&rqlang=cn&rsv_enter=1&rsv_sug3=3&rsv_sug1=1&rsv_sug7=100&rsv_sug2=0&inputT=4019&rsv_sug4=4020
www.baidu.com###content_right

**Comment by liangshengzero** [comment] 2016-06-21 05:30
[my-ublock-static-filters_2016-6-21_下午12-58-30.txt](https://github.com/gorhill/uBlock/files/324853/my-ublock-static-filters_2016-6-21_.12-58-30.txt)

最后一条，那条规则发送后就被删除

**Comment by gorhill** [comment] 2016-06-21 11:59
I can't figure the reported issue here. If someone can read Chinese, that would help if the gist of the issue can be translated.

**Comment by cobob** [comment] 2016-06-23 03:43
我的1.7.2没有这个问题,建议还是使用直接从Chrome商店下载的版本.

**Comment by hairycactus** [comment] 2016-06-23 08:19
Approximate translation of user's [opening post](https://github.com/gorhill/uBlock/issues/1741#issue-161351393):

###### #1741: After clicking search result link in Baidu.com, side-overlay appears & main text disappears

> 1) For example, search for "chrome" at [Baidu.com](https://www.baidu.com), & click on the oifficial Chrome website link. [[user screenshot]](https://cloud.githubusercontent.com/assets/17328925/16218661/88b7314e-37b2-11e6-9224-427f284df82a.jpg) The result will load in a new tab.

Note: The text for the official Google Chrome URL looks like this: "Chrome 浏览器" (ie. 2nd or 3rd result on the page, appended with _google.cn_ domain). Or simply click any link in the search results. It is not any specific hyperlink that is causing the issue that the user is reporting.

> 2) Return to the previous tab containing the search results.
> 
> 3) The rightmost **"Related Software"** overlay had shifted to the left side of the search-results page, while the rest of the page [including its text] had disappeared. [[user screenshot]](https://cloud.githubusercontent.com/assets/17328925/16218660/88b6ebbc-37b2-11e6-9f3b-19f57e3e70f6.jpg) 
> 
> 4) After a page refresh, the search-results page reverted to normal.
> 

Approximate translation of user's subsequent [comment](https://github.com/gorhill/uBlock/issues/1741#issuecomment-227343932):

> Seems that the issue might be related to the below custom rule, but "之前复制失败"

Not sure what the aforementioned Chinese phrase means. Perhaps user is saying that he is not able to reproduce the same issue every time, OR that removing that custom rule failed to resolve the issue.

> > ! 2016/6/19 9:18:59 pm _[user's search term URL irrelevant to this issue removed]_
> >`www.baidu.com###content_right`

**Comment by hairycactus** [comment] 2016-06-23 08:29
My Test & Observations:-

After clicking any search result at [Baidu.com](https://www.baidu.com), the **"Related Software"** overlay on the right should not shift to the left, & obscure the entire search-results page such that all text disappears.

[Screenshot](https://i.imgur.com/K9mPvrd.png) showing how the original search-results page should presumably look like, after a link is clicked (& loads in a new tab). Compare with user's [screenshot](https://cloud.githubusercontent.com/assets/17328925/16218660/88b6ebbc-37b2-11e6-9f3b-19f57e3e70f6.jpg).

I don't have Google Chrome, so I tested using Firefox + uBO v1.7.0 stable & v1.7.6 stable.

**Comment by gorhill** [comment] 2016-06-23 12:20
I see, thanks for translating.

I can reproduce, but only with OP's custom filters. This also happens with ABP.

Essentially, there is javascript on the page which appears to re-arrange/create DOM elements on the page when a user clicks. It's not a uBO issue, it's just the way the page is designed.

If I add these two filters, the quirk seems to go away, but I can't tell if this breaks the page:

**Comment by gorhill** [comment] 2016-06-23 12:23
Closing, as it is a filter issue.

**Closed by gorhill** 2016-06-23 12:23 UTC
