### ISSUE TITLE
[Feature] Add to filters, unchecked by default, Adblock nonintrusive advertising and AakList

### ISSUE THREAD

**Issue by MarcoSulla** [gorhill/uBlock#3757] opened 2019-05-05 14:00 UTC
I think it's good to let the user choice if they want to not filter unobtrusive ads. Adding it as a separate and unchecked by default filter could be a good idea.

Link: https://easylist-downloads.adblockplus.org/exceptionrules.txt

About AakList, I know it's a dead project since 2016, but it still works. uBlock anyway alerts that the filter is outdated. Adding it as an optional filter, disabled by default, seems to me good.

Link: https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

Yes, I was able to add them as custom filters, but I think it will be good if they are present by default in the application, optional and unchecked  by default.

Thank you in advance.

**Comment by gorhill** [comment] 2019-05-05 14:16
Duplicate of <https://github.com/gorhill/uBlock/issues/395>.

**Closed by gorhill** 2019-05-05 14:16 UTC
Labels: duplicate
