### ISSUE TITLE
'? bytes' in control panel

### ISSUE THREAD

**Issue by jony0008** [gorhill/uBlock#3122] opened 2017-10-11 05:19 UTC
IMO, '- bytes' is better to use than '? bytes'

![skarmbild fran 2017-10-11 07-16-27](https://user-images.githubusercontent.com/23194385/31423312-5558b916-ae54-11e7-9801-38b472159827.png)

**Comment by gwarser** [comment] 2017-10-11 07:56
Duplicate of https://github.com/gorhill/uBlock/issues/2812

**Comment by gorhill** [comment] 2017-10-11 11:53
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-10-11 11:53 UTC
Labels: invalid
