### ISSUE TITLE
Can't save webpages

### ISSUE THREAD

**Issue by kvzhou** [gorhill/uBlock#1447] opened 2016-03-05 20:20 UTC
### Describe the issue

Whenever I try to save a webpage, it gets stuck after a few bytes.

### One or more specific URLs where the issue occurs

This occurs for most urls. Example: wired.com

### Your settings

default settings. Issue occurs even after Chrome reinstall and removal of all other extensions.

- Browser/version: Chrome 49.0.2623.75 m
- uBlock Origin version: 1.6.2

##### Your filter lists

Default filter lists

**Comment by gorhill** [comment] 2016-03-05 20:33
Duplicate of #1185.

**Closed by gorhill** 2016-03-05 20:33 UTC
