### ISSUE TITLE
picker preview doesnt react to xpath filters

### ISSUE THREAD

**Issue by elypter** [gorhill/uBlock#1888] opened 2016-08-11 01:09 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

when pasting this filter containing an xpath into the filter window nothing gets selected in the preview although the filter is valid

example:

ebay-kleinanzeigen.de##:xpath(//*/strong[.//text()=" VB"]/parent::section[1]/parent::article[1])

on

https://www.ebay-kleinanzeigen.de/s-erlangen/preis::0/l6791r50

### Your settings

default settings

- firefox 42.0
- uBlock Origin version 1.8.4 

##### Your filter lists

default

unfortunately the filter doesnt work anymore for me even when pasting it in custom filters which is very weird because the site didnt change. im posting this issue anyway because it is a general problem and it should be possible to get the filter working for testing or use another one. if a new version of ubo has been released today then it could might be a possible reason.

**Comment by gorhill** [comment] 2016-08-11 01:26
Duplicate of #1772.

**Closed by gorhill** 2016-08-11 01:26 UTC
