### ISSUE TITLE
Microsoft Edge and bing.com homepage ads

### ISSUE THREAD

**Issue by richardburt** [gorhill/uBlock#2236] opened 2016-12-13 07:56 UTC
![sketch](https://cloud.githubusercontent.com/assets/24540567/21131874/2ffee976-c122-11e6-8cc9-8f9246c42f0b.png)
Unable to block ads on bing.com homepage when using Microsoft Edge

Using Microsoft Edge go to the Bing homepage. Type in search term (eg test) and look at search results. Bing ads appear down the right hand side of the page.

1. This is also an AdBlock Plus issue: https://adblockplus.org/forum/viewtopic.php?f=27&t=48440
2. Adguard is also unable to block these homepage ads.

uBlock Origin fefault settings only.

Microsoft Edge, version 38.14393.0.0
uBlock Origin version: 1.10.1

Default filter list only.

**Comment by androidland** [comment] 2016-12-13 08:18
https://github.com/nikrolls/uBlock-Edge

**Comment by gorhill** [comment] 2016-12-13 11:51
Duplicate of <https://github.com/nikrolls/uBlock-Edge/issues/30>.

**Closed by gorhill** 2016-12-13 11:51 UTC

**Comment by jihegu** [comment] 2017-02-04 00:59
I still have issue with ad no blocking on bing.com. When fix present?
