### ISSUE TITLE
uBO button options not visible from under menu button

### ISSUE THREAD

**Issue by tomkeen** [gorhill/uBlock#2928] opened 2017-08-30 04:33 UTC
I just started using the development version 1.13.11rc0 with Firefox 55.0.3 on macOS Sierra 10.12.6. This is a relatively minor issue, but when the uBO button is accessed from under the menu button, most of the extension options and settings are cut off and inaccessible:

![screen shot 2017-08-30 at 1 57 30 pm](https://user-images.githubusercontent.com/5132610/29854970-5a92b24e-8d8c-11e7-9634-9e873341ff16.png)

If the uBO button is moved to the toolbar, it works properly:

![screen shot 2017-08-30 at 2 10 53 pm](https://user-images.githubusercontent.com/5132610/29855344-7d2391aa-8d8e-11e7-9750-b97ad1cef300.png)

This occurs using default uBO settings and filters.

Thanks for your work on this.

**Comment by shevegen** [comment] 2017-08-30 06:28
Very oddly looking result. :) It seems as if the functionality itself is working and the expanded widget works too, from the second image but may assume a different width through the menu button..

**Comment by gorhill** [comment] 2017-08-30 11:35
Duplicate of #2809.

Please search existing issues before opening new ones.

**Closed by gorhill** 2017-08-30 11:35 UTC
Labels: duplicate
