### ISSUE TITLE
uBO v1.15.20 - Icon bug causes the dashboard to freeze

### ISSUE THREAD

**Issue by THEtomaso** [gorhill/uBlock#3665] opened 2018-04-02 10:05 UTC
### Describe the issue:
Missing icon:

![ublockorigin-bug-icon1](https://user-images.githubusercontent.com/9382674/38192569-03fed884-365d-11e8-8087-083bb68325a6.jpg)

Right-clicking on the missing icon and selecting "View image" results in this:

![ublockorigin-bug-icon2](https://user-images.githubusercontent.com/9382674/38192597-1d7ee9b6-365d-11e8-821c-f57eec49e2c4.jpg)

Afterwards, when going back to uBO's Dashboard, everything has frozen, and clicking on the settings tabs doesn't work anymore.

--

- OS/version: Win8.1Pro,x64
- Browser/version: Pale Moon v27.8.3,x64
- uBlock Origin version: v1.15.20 (XUL)

**Comment by gorhill** [comment] 2018-04-02 10:18
I can reproduce image missing ().

I cannot reproduce freeze with Pale Moon 27.6.0.

**Comment by THEtomaso** [comment] 2018-04-02 10:22
That's what I ment, sorry for the exaggeration.

**Comment by gorhill** [comment] 2018-04-02 10:31
The image issue can be simply fixed by removing the leading `/` in the image link. I don't know why Pale Moon has a problem with this though, it is obviously able to compute the proper URL to the image, but somehow is unable to fetch at that proper URL.

The dashboard being unresponsive is unrelated to the image issue. You can reproduce the same by loading a new URL in the tab where the dashboard is and then go back using the Back button. THis might have been there since forever for all I know. If somebody can investigate/figure a fix for this quirk that would be good, I don't plan to spend time on this given this has always been there and this is the first time it is being reported.

**Comment by THEtomaso** [comment] 2018-04-02 10:46
uBO v1.15.20 is the first version where I've seen this problem.
Which slash do you refer to by the way?
No matter which one(s) I remove, I can't get it to display the image.

**Comment by gorhill** [comment] 2018-04-02 10:50
I'm just documenting the issue, these are developer notes, you do not have to understand.

**Comment by gorhill** [comment] 2018-04-02 10:52
I can also reproduce the dashboard unresponsiveness issue with the webext version.

**Comment by gorhill** [comment] 2018-04-02 10:58
I will consider the unresponsive dashboard a browser issue: it happens with the Firefox/legacy and the and Firefox/webext version of uBO. It does not happen with the Chromium version of uBO.

**Comment by THEtomaso** [comment] 2018-04-02 10:58
SeaMonkey is also affected.
Although, it doesn't even indicate the existence of a image file at all:

![ublockorigin-bug-icon2 sm](https://user-images.githubusercontent.com/9382674/38194070-d59bb3c4-3664-11e8-965b-181c79a9bb84.jpg)

**Comment by gorhill** [comment] 2018-07-21 22:14
Issue is with Firefox. If opening a remote URL in the dashboard tab, going back does not break tab navigation. This happens when I view the uBO logo however. This does not happen with Chromium.

**Closed by gorhill** 2018-07-21 22:14 UTC
Labels: Firefox, browser bug
