### ISSUE TITLE
Can't block <video> tag

### ISSUE THREAD

**Issue by tntc4** [gorhill/uBlock#868] opened 2015-10-26 23:06 UTC
steps to reproduce:
1. go to http://www.google.com/adsense/start/#?modal_active=none
2. the embeded video in the page is auto start and can't be blocked

I look in to requests logger but can't find any video related urls.
- FireFox 41.0
- uBlock Origin v.1.3.1

**Comment by gorhill** [comment] 2015-10-26 23:31
It's a Firefox issue: the resource for the `video` tag does not go through the HTTP observer. The network request for the video does not show up in the _Network_ pane in the dev console either.

**Comment by vzjrz** [comment] 2015-10-26 23:33
It seems ublock/umatrix is able to block it if a corresponding filter is in place before the site loads but if the video loads it stays in cache? and doesn't appear in any console until a restart is performed.
The video links are:
http://www.google.com/adsense/start/videos/home-hero.ogv
http://www.google.com/adsense/start/videos/home-hero.webm
http://www.google.com/adsense/start/videos/home-hero.mp4

**Comment by gorhill** [comment] 2015-10-26 23:39
> if the video loads it stays in cache?

It's not even in the cache: if you clear the cache, it will still not be seen by the HTTP observer.

**Comment by gorhill** [comment] 2015-10-26 23:42
Correction to my linked issue above, this is the original one: <https://github.com/chrisaljoudi/uBlock/issues/955>.

**Comment by vzjrz** [comment] 2015-10-27 00:10
Weird, I'm able to block it if it doesn't load first.
![ublock123](https://cloud.githubusercontent.com/assets/930620/10746059/1cd3be42-7c15-11e5-8944-d304674cd736.PNG)

**Comment by RoxKilly** [comment] 2015-10-27 00:13
@tntc4 
>  the embeded video in the page is auto start and can't be blocked

This is not directly related to this bug, but because I hate auto-playing videos I wanted to share.  FF has finally fixed its `media.autoplay.enabled` config setting.  Set it to `false` and media will no longer autoplay anywhere.

**Comment by tntc4** [comment] 2015-10-27 10:07
update
1. I empty my FireFox cache
2. add filter ||www.google.com/adsense/start/videos/$important
3. close and open FireFox
4. go to http://www.google.com/adsense/start/#?modal_active=none

the video is no longer loaded and played.
Thanks to vzjrz and RoxKilly and especialy to gorhill for making this awesome addon :)

**Comment by gorhill** [comment] 2015-11-13 16:55
Tested again, back to square one.

I lean toward a FF issue: I tried same scenario with ABP, and same issue: the `media` resource shows once in the blockable elements list, then never again when reloading the page. So even `shouldLoad` is not notified that a resource of type `media` is being loaded.

**Comment by Flashwalker** [comment] 2016-02-05 21:02
Hi, i'm from [https://github.com/gorhill/uBlock/issues/1337](https://github.com/gorhill/uBlock/issues/1337)

I've tested:

* PaleMoon 26.0.0 (x86)
* uBlock 1.5.5
* rules:  
`    ||www.google.com/adsense/start/videos/$important`  
`    ||*.cloudfront.net/assets/videos/earth-1/*$media,domain=minds.com`
* about:config `media.autoplay.enabled;false`
* clear cache, restart browser
* visit http://www.google.com/adsense/start/#?modal_active=none  
    no autoplay http://www.google.com/adsense/start/videos/home-hero.mp4  
    no autoplay http://www.google.com/adsense/start/videos/spice.mp4  
    ![](http://storage3.static.itmages.ru/i/16/0205/h_1454703131_8853537_ff8936d03d.png)
* visit http://minds.com  
    no video (big globe background)  
    __has__ image (big globe background)

And:
* PaleMoon 26.0.0 (x86)
* Adblock Latitude 3.0.3.1
* rules:  
`    ||www.google.com/adsense/start/videos/*$media`  
`    ||*.cloudfront.net/assets/videos/earth-1/*$media,domain=minds.com`
* about:config `media.autoplay.enabled;false`
* clear cache, restart browser
* visit http://www.google.com/adsense/start/#?modal_active=none  
    no autoplay http://www.google.com/adsense/start/videos/home-hero.mp4  
    __has__ autoplay http://www.google.com/adsense/start/videos/spice.mp4 (maybe by scrolling?)    
* visit http://minds.com  
    no video (big globe background)  
    no image (big globe background)  
    ![](http://storage7.static.itmages.ru/i/16/0205/h_1454702155_4514385_05f31d0783.png)

So...

**Comment by gorhill** [comment] 2017-09-22 13:05
I could properly block the video with Firefox 55.0.2, if after creating the block rule, I hold the ctrl key while clicking page reload to force cache bypass.

Conclusion, work as expected using the WebExtensions API. Closing as no longer able to reproduce.

**Closed by gorhill** 2017-09-22 13:05 UTC
Labels: browser bug, unable to reproduce
