### ISSUE TITLE
feature request, a lot keyboard shortcuts ;)

### ISSUE THREAD

**Issue by msagebiel** [gorhill/uBlock#2302] opened 2017-01-11 18:52 UTC
like maybe scriptsafe, per domain allow all e.g.
Bottom of extensions settings in chrome.
Thanks for considering

**Comment by anewuser** [comment] 2017-01-15 20:58
Use this page only to report bugs, i.e. problems that make uBlock Origin stop working. Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by gorhill** [comment] 2017-03-22 13:08
Duplicate of #113.

**Closed by gorhill** 2017-03-22 13:08 UTC
Labels: duplicate
