### ISSUE TITLE
Popup detection mistake

### ISSUE THREAD

**Issue by Matthewus** [gorhill/uBlock#3112] opened 2017-10-09 08:45 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Tabs closing when opening multiple links on ikshow.net while popup blocking is enabled via popup menu.

### One or more specific URLs where the issue occurs
http://ikshow.net/

### Screenshot in which the issue can be seen
-

### Steps for anyone to reproduce the issue
Go to ikshow.net, open multiple links quickly. Quickly is important because if i open the next link after the previous is completly loaded everything is fine.

### Your settings
Default settings, only the popups disabled on http://ikshow.net/

- OS/version: Windows 10 64 bit
- Browser/version:  Firefox 56 64 bit
- uBlock Origin version:  1.14.14

##### Your filter lists
Default

##### Your custom filters (if any)
None

**Comment by gorhill** [comment] 2017-10-09 12:54
You're going to have to come up with much better repro steps, and analysis of the logger. Read carefully 1st paragraph in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment] 2017-10-09 13:02
That site is afflicted by popunders, that I could reproduce. Fixed with a filter in "uBlock filters".

**Comment by Matthewus** [comment] 2017-10-09 13:21
Thanks, the filter works great.
Here is a video of what happened before, when i enabled popup blocking:
https://drive.google.com/open?id=0B4zNZvqz2Gl5bE4ySFZCUGVQXzQ

**Comment by gorhill** [comment] 2017-10-09 13:34
So you are **middle-clicking**? I was trying to reproduce with left-clicking. With middle-clicking, I can reproduce.

**Comment by Matthewus** [comment] 2017-10-09 13:45
Yes middle or CTRL+left clicking. Sorry that i left out an important detail, i thought i wrote it.

**Comment by gorhill** [comment] 2017-10-09 13:52
Dev memo: I suspect the issue is caused by the use of one global "clicked URL" used for all new tabs being created. There should be one "clicked URL" associated with each new tab at creation time. Issue also occurs with Chromium.

**Comment by gorhill** [comment] 2017-10-13 13:33
Fixed with 7713597e3e3ecf5c03c70f56bdb989e7d78956e8.

**Closed by gorhill** 2017-10-13 13:33 UTC
