### ISSUE TITLE
"toggle cosmetic filtering" no longer affects net-blocked element collapsing

### ISSUE THREAD

**Issue by kikaxa** [gorhill/uBlock#1146] opened 2015-12-30 11:12 UTC
Recently since autoupdate to ~v1.5 rules like "no-cosmetic-filtering: 2ch.hk true" or eye icon in popup have no effect for me.

I have images/scripts blocked.
Previously, it showed placeholder/empty block for images, now it always hides them.

Can you see if it happens for you too?

**Comment by gorhill** [comment] 2015-12-30 14:09
It's because the cosmetic filtering switch was not properly implemented, it was causing both cosmetic filters **and** the collapsing of blocked elements through network filtering to be disabled. The purpose of the cosmetic filtering switch is to toggle **only** cosmetic filters, not the collapse of the placeholder of blocked network requests.

One could disable cosmetic filtering globally (`no-cosmetic-filtering: * true`) in order to make uBO even more efficient by forcing uBO to disregard cosmetic filtering everywhere by default (might be a good boost for uBO on mobile devices), while still preserving the collapsing of blocked resources through network filtering.

**Comment by kikaxa** [comment] 2015-12-30 14:37
Thanks for looking into this.
I primarily used this switch to disable collapsing of blocked network resources, e.g. images/frames so i still could use related js/link functionality.
For me personally the old behavior made sense,.
Maybe you could think of some replacement, or add option/flag to restore old behaviour?

**Comment by gorhill** [comment] 2016-01-02 18:05
For future reference for myself, the code change occurred in 9c12ef02bb11a23c5c12231f9f1553b0ca143365.

**Comment by gorhill** [comment] 2016-01-05 14:15
Since a while now, I have been playing with the idea of providing "hidden" settings, settings which do not have a UI counterparts, but can be toggled on/off through the browser's specific UI. The goal is to not clutter the current UI with full of settings which are irrelevant for the majority of users.

Doing so would make it more easy for me to provide the kind of very specific behavior you want here. I think I will go ahead with this idea, as this will also allow me to also provide other customization settings which have been requested by a minority of users, but for which I do not want to provide a UI counterpart (which would require more UI code, localization, documentation, etc.)

**Comment by kikaxa** [comment] 2016-01-06 10:58
Sounds good, i think every project i coded for or used has some form of "advanced"/hidden settings.

**Comment by gorhill** [comment] 2019-07-25 12:34
Closing, this would be far from trivial with no benefits for the wide majority of users justifying the development efforts, increased code complexity and risks of regression.

**Closed by gorhill** 2019-07-25 12:34 UTC
