### ISSUE TITLE
Ublock stopped working with  last update

### ISSUE THREAD

**Issue by s1raz1** [gorhill/uBlock#2942] opened 2017-08-31 13:56 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
After i updated Ublock yesterday/lastnight i opened firefox today and the icon is gone and ads arent being blocked despite Ublock being shown as enabled. Toggling it  enabled/disabled doesnt do anything.

### One or more specific URLs where the issue occurs
https://search.yahoo.com/search?p=pcgamer&fr=ymyy-t-999&fr2=p%3Amy%2Cm%3Asb
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
I just updated it, went to bed, open the browser today and Ublock doesnt block ads anymore.
1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Default settings
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Win 7 x64
- Browser/version: Firefox x64 55.0.3
- uBlock Origin version: 1.13.10

##### Your filter lists
Default lists, 
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by mooninite** [comment] 2017-08-31 14:01
FYI, uBlock Origin works again for me after upgrading to the "Development Channel" on AMO: 1.14.3b0

**Comment by s1raz1** [comment] 2017-08-31 14:04
So i should wait until that update goes live on Firefox? 
Am just an average user and Ublock is my tool to block ads.

**Comment by mooninite** [comment] 2017-08-31 14:11
Go here: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

Go to the bottom of the page where it says Development Channel and then click on "Add to Firefox"...

**Comment by birdy1976** [comment] 2017-08-31 15:36
uBlock worked again after I deleted Ghostery (FF 55.0.2). PS: Thanks for this great add-on :+1:

**Comment by gorhill** [comment] 2017-08-31 15:37
Duplicate of #2909.

**Closed by gorhill** 2017-08-31 15:37 UTC
