### ISSUE TITLE
For info: branch with my additions tracked against this fork

### ISSUE THREAD

**Issue by AlexVallat** [gorhill/uBlock#264] opened 2015-05-30 13:08 UTC
I am aware that you've already stated your decision not to integrate some of the changes I have worked on for the uBlock fork into uBlock₀, so this is not a pull request. However, I wanted to let you know that for my own use I have cherry-picked and merge-reconciled the changes I have made to uBlock to track against uBlock₀ in this branch: https://github.com/gorhill/uBlock/compare/master...AlexVallat:gorhil-master. This is mainly the Legacy Toolbar Button for PaleMoon and Seamonkey support, and the Firefox Developer Tools console context menu blocking commands.

I intend to continue to periodically merge (or rebase) your commits made to uBlock₀ to keep the branch up to date. You are welcome to any use you wish to make of it.

**Comment by Cormak** [comment] 2015-05-30 17:13
Alex, please don't give Chris' repo any more time. Nobody likes Chris and his repo is dead. uBlock Origin is the only way to go moving forward.

**Comment by gorhill** [comment] 2015-05-30 21:08
The first reason I prefer to not import is because I just won't have the time to test/maintain these legacy versions if ever someone reports an issue with these. Looking at the stats in AMO, the proportion of legacy FFs is small compared to FF29+, so adding this to the first reason, I didn't see the point for me to support legacy. So long as people can install one uBlock, they get what first matters, the efficiency.

**Comment by AlexVallat** [comment] 2015-05-30 21:39
I can certainly appreciate that point of view. I don't know how well they would register in the stats, but I've no doubt PaleMoon users, even combined with Seamonkey users, would still be in the small minority of overall users.

**Comment by LeafG** [comment] 2015-05-31 05:09
@gorhill, I can't argue with your point of testing the other types of browsers, or maybe your lack of enthusiasm to deal with browsers you may not use on a daily basis. It's understandable.
But reading this exchange, makes me want to voice the point-of-view of SeaMonkey and Pale Moon users, of which I am one. We're a minority, in a sense.

I can tell you, in regard to the stats on AMO, that the reason for that is (or can be) because uBlock0 was marked as incompatible with SeaMonkey (or FF 24, as Pale Moon is recognized), and the link was disabled for downloading. I checked it just a little while ago. (I wish I remembered which version it was. Maybe as soon as I read <a href="http://www.ghacks.net/2015/04/25/official-ublock-origin-add-on-lands-for-firefox/">this</a> article). 

It is not fair to say that we have "one uBlock" (which I read as "they can use uBlock"). I have used this version from before the split, followed that whole tale of bad vibe from this side of the fork, and have no reason to get a version with less features, even if its GUI is handled better. I believe there are others like me, in this POV.

It's the "story of SeaMonkey" that we always need a special variant of the required addons, because of our lesser % in the "market". I've read such "cries for help" for Ghostery at the time, and other important addons.

Again, it's not my intention to provoke here. I appreciate that you're doing what you love at your free time, and I thank you for this excellent tool.
I just felt the need to express this POV.

**Comment by gorhill** [comment] 2015-06-15 13:22
@AlexVallat 

I would be willing to import:
- https://github.com/gorhill/uBlock/commit/464309bdabe7d5213a22b4cf56e9379ded127c8c
- https://github.com/gorhill/uBlock/commit/35581494ab0be8f4374ae6477d010ec361e44dde
- https://github.com/gorhill/uBlock/commit/e9633d458aec86df1fd2c8b33e9fce937f1d015f
- https://github.com/gorhill/uBlock/commit/620a7d78d146d071f3f7ba09710c6fa332dcc3f0

If:
- You don't mind addressing issues arising specific to legacy UI support.

If so, I would also like to create eventually some kind of mini-virtualization layer for the UI stuff in `vapi-background.js`, one layer for each distinct code path (Fennec, FF 28-, FF29+, FF36+). I am not a fan of huge if-else blocks and special code paths peppered all over the place, and I currently see the UI code like this. It's something I was planning to look into even without the support for legacy UI.

For the inspector stuff I am [thinking of something else](https://github.com/gorhill/uBlock/issues/119#issuecomment-108314557).

**Comment by AlexVallat** [comment] 2015-06-15 22:27
@gorhill That's great! I'm afraid I'm away until next week, so I can't do any merging for the next few days. I agree with you that the organization of the different code paths could certainly be done better, though.

**Comment by LimboSlam** [comment] 2015-06-17 19:54
@gorhill and @AlexVallat, I see both of your points, I do. I'm also a Pale Moon user and I know some what of coding, so I know how difficult and time consuming these issues can be, but why not just work together??? Why not put aside your differences and give it a shot? Your both great at what you do and love what you do, your making a difference in the Mozilla community; giving the users a handy tool. So why not have two eyes than one eye, right? Just a suggestion though, don't mean any offense.

Keep up the great work, both of you guys!!  :+1:   :)

**Comment by inoyakaigor** [comment] 2015-06-17 23:27
I endorse @LimboSlam

**Comment by volcbs** [comment] 2015-06-18 00:31
uBlock 0.9.9.2 (latest dev)
Firefox 40.0a2 Developer Edition (x64)
Windows 8.1 x64

I can't move the legacyUI (via customize) to anywhere I want.
Anyway I use oneliner add-ons if that counts.

**Comment by gorhill** [comment] 2015-06-18 13:36
> I can't move the legacyUI (via customize) to anywhere I want.

I just tried with FF 38 and Nightly and I could move it fine. Provide detailed step by step so that I can reproduce your issue.

**Comment by volcbs** [comment] 2015-06-18 14:04
1. open "about:config"
2. set "extensions.ublock0.forceLegacyToolbarButton" to true
3. restart
4. hamburger menu > customize or view > toolbar > customize
![itxne](https://cloud.githubusercontent.com/assets/12575216/8232944/6dd479c2-15fd-11e5-8eaa-adddd37354aa.png)
If it's move-able, then the legacyUI icon should be inside the line but it isn't.
(Now) I use vanilla firefox dev edition, and I can't still move the legacyUI to anywhere I want.

Also sorry I forgot,
https://addons.mozilla.org/en-us/firefox/addon/prospector-oneLiner/

**Comment by gorhill** [comment] 2015-06-18 15:37
> ![itxne](https://cloud.githubusercontent.com/assets/12575216/8232944/6dd479c2-15fd-11e5-8eaa-adddd37354aa.png)

I've seen this happens too.

Repro steps:
1. `about:config`, filter using `ublock0`
1. set `extensions.ublock0.legacyToolbarButtonAdded` to `false`
1. set `extensions.ublock0.forceLegacyToolbarButton` to `true`
1. restart FF
1. uBlock icon is put aside the hamburger menu icon, and can't be dragged anymore
1. restart FF
1. uBlock icon is now in the tool paletter, and can be dragged, i.e. now customizable

So issue is to fix uBlock icon being put in a non-customizable toolbar at 5.

**Closed as completed** 2015-06-18 16:03 UTC

**Comment by gorhill** [comment] 2015-06-18 16:08
@volcbs Fix is [in `0.9.9.2-dev.4`](https://github.com/gorhill/uBlock/releases).

**Comment by volcbs** [comment] 2015-06-18 17:08
@gorhill Ah nice.. thanks.

**Comment by LimboSlam** [comment] 2015-06-18 20:37
(#1449)

**Comment by gorhill** [comment] 2015-06-18 21:12
@LimboSlam fb25df9f0549b65ccaeae9f4b6f0c0289bce7d97, in [dev.5 build](https://github.com/gorhill/uBlock/releases).

**Comment by LimboSlam** [comment] 2015-06-18 22:06
@gorhill Thanks!! Appreciate it! :+1:

**Comment by LimboSlam** [comment] 2015-06-19 02:15
@gorhill I think I found another issue, the icons in Pale Moon and Firefox are different.   
**Firefox**
![screenshot firefox](https://cloud.githubusercontent.com/assets/10698432/8245978/a33fe48c-15eb-11e5-9bf1-eaa6c815dea2.png)
**Pale Moon**
![screenshot pale moon](https://cloud.githubusercontent.com/assets/10698432/8246028/54b1ccf8-15ec-11e5-8be1-94544ef181bd.png) 

Ublock icon in Pale Moon leaves a more of a gap, you know where the down arrow used to be and Firefoxs is centered, which is how it should be, right? Another thing I noticed is that the door hanger is missing in Pale Moon, but is there in Firefox. Well I don't know if these are bugs or not, but I would like to see these fixed. And if I sound a little OCD and pushy, forgive me.  :) 

Keep up the great work!!  :+1:

**Comment by gorhill** [comment] 2015-06-19 03:07
I don't have PaleMoon, it's not readily available for Linux -- except on SourceForce I believe. Someone else will have to look into this, and for now to me this looks like a PaleMoon issue.

**Comment by LimboSlam** [comment] 2015-06-19 04:35
@gorhill Alright, I'll bring it up in the Pale Moon forums.

**Comment by ozar** [comment] 2015-06-19 14:32
@LimboSlam 
My uBlock-Origin icon for Linux and WinXP (under Pale Moon) look like they should after Gorhill's fix.  However, the uBlock-Origin icon under Win7 still looks elongated horizontally.  It appears that the down-arrow was removed as per the fix, but the button dimensions didn't shrink any.

**Comment by AlexVallat** [comment] 2015-06-23 18:06
Annoyingly, PaleMoon under Linux and Windows use different layouts for the buttons. So, you can force it under windows with:
```
#uBlock0-legacy-button .toolbarbutton-icon {
    -moz-padding-end: 6px !important;
}
```
But under Linux that sticks an extra 6px padding where it isn't wanted! It looks like PaleMoon is quite certain that buttons which show popups should have arrows.

**Comment by ozar** [comment] 2015-06-24 20:34
Thanks for looking into it and reporting back, AlexV.  I've only been using Pale Moon for a few weeks and have found that like all other apps, it comes with its own set of annoyances.
