### ISSUE TITLE
The white list is invalid

### ISSUE THREAD

**Issue by xinggsf** [gorhill/uBlock#997] opened 2015-12-01 11:38 UTC
!--------------FlashBlock----------------------
|http://$object,domain=~youku.com|~tudou.com|~iqiyi.com|~pps.tv|~yatu.tv|~baidu.com
@@upload.swf^$object
@@clipboard.swf|$object

URL:
http://bbs.kafan.cn/static/image/common/swfupload.swf?preventswfcaching=1448969455287

but the URL is block!

**Comment by publicarray** [comment] 2015-12-02 23:53
Hi xinggsf,
First of all please use the markdown syntax: https://guides.github.com/features/mastering-markdown/
using ``` around your code block avoids sending emails to the github users upload and clipboard.

Now to create filters please read: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax
for white lists read: https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site

**Comment by publicarray** [comment] 2015-12-03 01:33
Looking into this further I used http://v.youku.com/v_show/id_XMTQwMTc4NTY1Ng==.html?f=23654673&ev=1&from=y1.3-idx-uhome-1519-20887.205805-205902.1-1
to test

```
! block rule
$object

! allow rules
@@loader.swf| ! works (unblocks swf object)
@@ader.swf|   ! does not work
```
@gorhill is there something I am missing?
I am trying to allow the following resource `http://static.youku.com/v1.0.0581/v/swf/loader.swf`

@xinggsf
P.S. To block both http and https requests you can just use `$object,domain=~youku.com|~tudou.com|~iqiyi.com|~pps.tv|~yatu.tv|~baidu.com`
 i.e. without the `|http://`

**Comment by gorhill** [comment] 2015-12-03 14:15
A more benign  repro case, using [front page of Hacker News](https://news.ycombinator.com/):

    ! block rule
    $image

    ! allow rules
    ! works:
    ! @@grayarrow.gif|
    
    ! does not work (expected)
    ! @@arrow.gif|
    
    ! does not work (I suppose it should...)
    @@*arrow.gif|

**Comment by gorhill** [comment] 2015-12-03 14:56
Ok two issues really, and with the first issue I found one really silly bug which was hiding there since a very long time.

First issue is to properly lookup a token from such filter as:

    @@*arrow.gif|

This is now fixed. Note that `@@arrow.gif|` and `@@*arrow.gif|` will still not work for `https://news.ycombinator.com/grayarrow.gif`, this is by design, because of efficiency and also as a consequence of uBO being able to parse hosts file. In such case, the proper filter should be:

    @@/*arrow.gif|

I think this is acceptable, especially that this does not force sacrificing efficiency.

Now the second issue uncovered is a really silly bug: any filter with a wildcard **and** anchored on the right (using `|`) will not generate a correct filter internally. I scanned EasyList and EasyPrivacy, and I found 7 such filters -- which were not enforced in the end (they could never match):

EasyList:

    ||psgroove.com/images/*.jpg|
    ||static.hd-trailers.net/js/javascript_*.js|
    ||olderhill.com^*.html|
    @@||barafranca.*/banner.php|
    @@||yellupload.com/yell/videoads/*.flv|

EasyPrivacy:

    ||ws.amazon.com/widgets/*=gettrackingid|
    ||u.bb/omni*.swf|

So given how rare those filters are, this might explain why that bug was not causing more problems. This is now fixed.

**Comment by gorhill** [comment] 2015-12-03 15:07
So as per fix, use

    @@/*upload.swf^$object

instead of

    @@upload.swf^$object

**Closed** 2015-12-03 15:06 UTC
Labels: accepted

**Comment by publicarray** [comment] 2015-12-04 14:04
Thanks for the explanation and quick fix. I recommend we add an explanation to the wiki: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax.

**Comment by Mikey1993** [comment] 2015-12-04 15:22
@publicarray Be our guest.

**Comment by publicarray** [comment] 2015-12-05 00:17
@gorhill I added an explanation. Feel free to correct any errors.

**Comment by gorhill** [comment] 2015-12-05 06:33
I realizes the explanation sounded too convoluted, so I just decided to change the code to no longer require the `/` for leading `*`.

**Comment by publicarray** [comment] 2015-12-05 12:16
I agree, It was too complex. Thanks for not requiring the `/` anymore. This makes life simpler :smile:.

**Comment by xinggsf** [comment] 2015-12-19 14:47
I see.
 @publicarray @gorhill  Thank you very much!

**Comment by seanrand** [comment] 2016-01-12 13:29
@gorhill, is this related to this bug? I'm getting a

    FilterContainer.compileFilter("/*playtv"): invalid
        filterµBlock.staticNetFilteringEngine.FilterContainer.compileFilter @ static-net-filtering.js:1975

error when updating the reek anti-adblock killer list. That part of the list hasn't been touched since [June](https://github.com/reek/anti-adblock-killer/commit/b98aea98b9bbf4b39b500203d85b626abac57bc9).

Is this expected (invalid filter) or something to be handled in uBlock?

**Comment by gorhill** [comment] 2016-01-12 13:56
Reek's filter is: `@@||/*playtv$object-subrequest,domain=play.tv|playtv.fr`. That is a non-sensical filter, the leading pipes `||` need to be removed. The [definition for leading double-pipe](https://adblockplus.org/filter-cheatsheet) is:

> The following text must be the domain name of the address.

With the Reek's filter, the following is not a domain name, it's a slash `/`.
