### ISSUE TITLE
Element Picker box does not spawn if no element filters exist

### ISSUE THREAD

**Issue by Tykina** [gorhill/uBlock#3224] opened 2017-11-12 05:54 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

The element picker / element zapper pop up box does not spawn (either from the popup menu, or from the context menu 'block element')

### One or more specific URLs where the issue occurs

All

### Screenshot in which the issue can be seen
n/a

### Steps for anyone to reproduce the issue

(In Chromium or Vivaldi - I did not try other browsers) 

1. Open the dashboard
2. Go to 'third party filters' and **untick** every subscription EXCEPT 'My Filters' - make sure 'Parse and enforce cosmetic filters' is ticked
3. Ensure 'My Filters' is empty (though in testing this, it does not need to be empty - it just needs to contain no cosmetic filters).
4. Visit any webpage, click uBlocks icon, click 'enter element picker mode' (alternatively right click a page and select 'Block Element' from the context menu)
5. The 'element picker' pop up never spawns

(as a workaround, if I ensure at least one cosmetic filter exists in 'My Filters', the pop up spawns correctly)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 

Windows 7 64 bit

- Browser/version: 

Tested in 

Vivaldi 1.13.1008.14 (Official Build) (32-bit)  
Chromium 64.0.3259.0 (Official Build) (64-bit)

- uBlock Origin version: 

1,14,19,2

##### Your filter lists

No subscribed filter lists

##### Your custom filters (if any)

In 'Third Party' filters, I have
    |blob:$script

Under 'My Filters' I have
    no-csp-reports: * true
    * * 3p-frame block
    * * 3p-script block

**Comment by gorhill** [comment] 2017-11-12 12:50
Duplicate of #2963.

**Closed by gorhill** 2017-11-12 12:50 UTC
Labels: duplicate
