### ISSUE TITLE
! Redirect: Special comment does not update filter URL

### ISSUE THREAD

**Issue by randomish** [gorhill/uBlock#2427] opened 2017-03-05 04:39 UTC
### Steps for anyone to reproduce the issue

1. Add this as a custom 3rd-party filter list:
https://raw.githubusercontent.com/randomish/filtertest/master/oldlistwithtitle.txt

### Expected result

I expected the custom filter list to be replaced by the new URL and title changed to _New custom test list_ as soon as the initial update was performed, since the list above uses a special comment to redirect to a new URL. I also tested ABP/FF and Adblock/Chrome and the redirect worked with both of those (see details in README.me pasted below).

### Actual result

This does not work in UBO, unlike the other two extensions I tested. The old list remains in the 3rd party settings, even after a manual update and browser restart. The new list does not appear.

### Settings

- Browser/version: Chrome 56.0.2924.87 (64-bit)
- uBlock Origin version: 1.11.0

#### Question for future reference

Is it OK to test the Chrome extension in the Vivaldi browser, or do I have to test with Chrome if I want to post an issue?

### Describe the issue

This redirect feature is very handy when a filter list maintainer has to change hosting/address for one reason or another. As long as there is some prior warning about the upcoming hosting change so the redirect can be set up, users will not have to do anything and will get the correct new settings via the redirect comment the first time the list is updated after the redirect was added. The old site can be taken down after a while.

I've set up a test repo with some custom filter lists to test redirect to new list URL.  
https://github.com/randomish/filtertest

I think I'll just paste the README.md I just added there below this point.

#### README.md

Quote from https://adblockplus.org/filters#special-comments on how the special comment _! Redirect_ should work:  
> ! Redirect: http://example.com/list.txt
>
>This comment indicates that the filter list has moved to a new download address. Adblock Plus will ignore any file contents beyond that comment and immediately try downloading from the new address. In case of success the address of the filter list will be updated in the settings. This comment is ignored if the new address is the same as the current address, meaning that it can be used to enforce the "canonical" address of the filter list.

In addition to that explanation, I also believe that when a redirect is performed (on list update), the client/extension should check if the new URL already is present in the custom filters, and if it is, just delete the duplicate list (don't leave old or new URL, only leave original entry for new URL in case it was manually disabled by user).

To test, just add https://raw.githubusercontent.com/randomish/filtertest/master/oldlistwithtitle.txt to your custom filters. If the redirect is successful, the entry should be automatically replaced by the new URL and the title changed to _New custom test list_.

2017-03-05:  
Adblock Plus 2.8.2 for Firefox - Redirect to new list works. New list visible in settings immediately.  
Adblock 3.8.8 for Chrome - Redirect to new list works. Have to close and reopen settings tab for changes to be visible.  
uBlock Origin 1.11.0 for Chrome - Redirect to new list does **not** work.

Additional feature request:  
I also wish that if the _! Redirect:_ is followed by just a newline (or whitespace then newline) that the list would be deleted from the extension settings. This way the list creator could signal that the list is dead and should be deleted automatically. This part is just my feature request and not implemented by any extension yet AFAIK. I created an example for this here: https://raw.githubusercontent.com/randomish/filtertest/master/deletelist.txt

**Comment by gorhill** [comment] 2017-03-05 18:05
Duplicate of #1183.

**Closed by gorhill** 2017-03-05 18:05 UTC
