### ISSUE TITLE
chrome://extensions tab opens with options tab

### ISSUE THREAD

**Issue by mikhaelkh** [gorhill/uBlock#330] opened 2015-06-10 15:49 UTC
When I right-click on uBlock icon, then select `options`, two tabs opens - `chrome://extensions` and `dashboard`. I guess it was done because of the Chromium flag `#enable-embedded-extension-options` which is disabled by default.

**Comment by gorhill** [comment] 2015-06-10 16:02
Duplicate of #303.

**Closed as completed by gorhill** 2015-06-10 16:02 UTC
