### ISSUE TITLE
uBlock is blocking Ghostery from accessing network

### ISSUE THREAD

**Issue by KaiHD** [gorhill/uBlock#1349] opened 2016-02-07 09:09 UTC
Chrome keeps posting a message that uBlock keeps redirecting network requests from Ghostery to itself. Tried manually whitelisting Ghostery in uBlock settings, but no good.

**Comment by gorhill** [comment] 2016-02-07 09:54
Duplicate of [#1170](https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068).

**Closed by gorhill** 2016-02-07 09:54 UTC
