### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#560] opened 2015-08-04 07:12 UTC
This morning with Firefox 40 final (http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/40.0-candidates/build1/win32/) I have this UI problem, the third red column for local filter doesn't appear in many web pages but it's still clickable with mouse.
![ublock](https://cloud.githubusercontent.com/assets/13637587/9055208/e40962ec-3a88-11e5-80b5-8d5a1e1469b6.jpg)

The problem is present with uBlock 1.0.0.0 and last dev 1.0.0.1. on XP:
    My filters‎: 
    uBlock filters‎ : 69 used out of 69purge cache
    uBlock filters – Badware risks‎ : 3 used out of 3purge cache
    uBlock filters – Privacy‎ : 3 used out of 4purge cache
    uBlock filters – Unbreak‎ : 63 used out of 63purge cache 
Ads (2)
    Adblock Warning Removal List‎ (forums.lanik.us): 88 used out of 88purge cache 
    EasyList‎ (forums.lanik.us): 61.620 used out of 61.628purge cache
Privacy (1)
    EasyPrivacy‎ 
Malware domains (2)
    Malware Domain List‎ (malwaredomainlist.com) 
    Malware domains‎ (malwaredomains.com) 
Social (2)
    Anti-ThirdpartySocial (see warning inside list)‎ 
    Fanboy’s Social Blocking List‎ (forums.lanik.us)
Regions, languages (1)
    RU AdList 
Custom (1)
    Block-EU-Cookie-Shit-List‎

**Comment by happysurf** [comment] 2015-08-05 06:30
After some test I discover that the problem occurs only when the list is long with scroll bar
otherwise all is OK.

![ublock2](https://cloud.githubusercontent.com/assets/13637587/9079577/02ffd654-3b4c-11e5-9cb7-6be4e662e878.jpg)

**Comment by Piter432** [comment] 2015-08-05 12:53
The problem in first screenshot is caused by `layers.async-pan-zoom.enabled` option in `about:config`, which in Firefox 40 is set to `true` by default (in earlier versions is set to `false` by default).

**Comment by gorhill** [comment] 2015-08-05 13:06
Browser bug, duplicate of #108, bugzilla issue 1157560](https://bugzilla.mozilla.org/show_bug.cgi?id=1157560)

**Closed by gorhill** 2015-08-05 13:06 UTC
