### ISSUE TITLE
uBlock as app Android

### ISSUE THREAD

**Issue by usernatilds** [gorhill/uBlock#3599] opened 2018-03-13 13:37 UTC
Like ad-away using hosts, is possible?

**Comment by uBlock-user** [comment] 2018-03-13 13:50
Duplicate of https://github.com/gorhill/uBlock/issues/1092

**Closed** 2018-03-13 13:49 UTC
Labels: declined

**Comment by jspenguin2017** [comment] 2018-03-14 03:13
If you just need hosts (DNS) based filtering, there are multiple projects for it already: 
https://github.com/blokadaorg/blokada
https://github.com/julian-klode/dns66
