### ISSUE TITLE
bad scrolling with ublock origin

### ISSUE THREAD

**Issue by S3ndG** [gorhill/uBlock#1089] opened 2015-12-19 11:39 UTC
Hi,
I've noticed that when I install ublock origin, the scrolling with mouse wheel is worse than without ublock origin (or even adblock plus).
I'm using firefox 43 64-bit.
Could you improve ublock origin so we can use it without having jerky scrolling?
Thanks.

**Comment by S3ndG** [comment] 2015-12-19 12:38
I've noticed that this bug has come with hardware vsync in firefox. Without hardware vsync (hw vsync can be disabled in firefox 42), it's smoother.

If you want to test scrolling, go to http://www.zdnet.fr or http://fr.audiofanzine.com/forums/  and scroll up and down for 3 minutes to see jerks.

**Comment by gorhill** [comment] 2015-12-19 13:50
Marking as invalid as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

You will have to make a clear and detailed case the issue is with uBO. uBO does not install any listeners for scroll event of mouse events.

**Closed by gorhill** 2015-12-19 13:50 UTC

**Comment by S3ndG** [comment] 2015-12-19 14:16
:-/
I'm gonna try to explain the best I can.
I have firefox 43 64bit and ublock origin  1.4.0.
The settings of ublock origin are :
[mes-donnees-ublock_19_12_2015_15_04_42.txt](https://github.com/gorhill/uBlock/files/67485/mes-donnees-ublock_19_12_2015_15_04_42.txt)

1) do not modify frame rate preferences in about:config
2) Go to http://www.zdnet.fr 
3) scroll quickly down then up then down etc... for 3 minutes
4) observe the jerks that happen while scrolling
5) go to http://fr.audiofanzine.com/forums/
6) scroll quickly then more moderate down then up then down etc... for 3 minutes
7) observe the jerks that happen while scrolling
8) it should be smoother like when ublock origin is disabled.

Is that enough clear? thanks!

**Comment by gorhill** [comment] 2015-12-19 15:05
<https://www.google.ca/search?q=firefox+scroll+jerk&gws_rd=cr,ssl#q=firefox+scroll+jerk&tbs=qdr:y>

**Comment by gorhill** [comment] 2015-12-19 15:28
> for 3 minutes

Be sure your filter lists are all up to date when you run your test, it is not unexpected there could be a jank when uBO download a filter list in the background, compiled it then save it into the SQL database.

**Comment by S3ndG** [comment] 2015-12-19 15:38
I'm unlucky nobody notice that adblockers like ublock origin can create jank in scrolling...
I'm using an Intel hd graphics 4600 card, it may have a bug. I have the latest drivers.

**Comment by gorhill** [comment] 2015-12-19 15:59
> adblockers like ublock origin can create jank in scrolling

This is unsubstantiated. There are also people who also think homeopathy cures illnesses. My point is that people who are not very technical will easily be convinced there are cause-effect links where there may be none.

As said, uBO does not install event listeners on scroll/mouse events (except for the click event), so this makes little sense that whatever jank you get when scrolling is caused by uBO -- which janks I can't reproduce by the way. If you have the preconceived idea that uBO **is** causing your jank, there is nothing I can do against preconception -- aside asking you to substantiate it.

Other people can try your test case too and report here what they experience.

Also, why "3 minutes"? Are you saying this takes a while to reproduce or does it happens immediately? Try again your tests with uBO's logger opened and the `All` entry selected in the drop down list. See if network requests are made when you run your jank tests.

In any case, you should peruse the search page results, as you can see the Firefox-scroll issue is not uncommon, and obviously unrelated to uBO.

**Comment by gorhill** [comment] 2015-12-19 16:15
There, screencast of the issue **not** occurring: <http://www.megafileupload.com/qG6W/ublock-1089.webm>.

**Comment by S3ndG** [comment] 2015-12-19 16:46
This happens randomly, so sometimes i must wait a bit (not long) to see jank.
I try to make my test with uBO's logger and network requests are made when I test (from my kaspersky antivirus). But I disable my antivirus I still have jank.
If I have no adblockers installed I don't have jank.

Please also note that I make my test slower, I could show you if you told me what software you're using to make your screencast :)
Thanks.

**Comment by harshanvn** [comment] 2015-12-19 16:47
> I'm using an Intel hd graphics 4600 card, it may have a bug.

> Could you improve ublock origin so we can use it without having jerky scrolling?

I have tried for around 2 minutes both the sites, and i am **unable** to reproduce the issue.
My system Graphics is same as yours too - W10 64 bit - i5-4200M Processor - HD4600 Graphics (v10.18.15.4256).

My first step would be have only uBlock installed in a new profile, and try to reproduce your issue, and make a screencast of it as Raymond requested.

I highly doubt it is uBlock what is causing the issue. Please try to test as said above?

**Comment by gorhill** [comment] 2015-12-19 16:53
> if you told me what software you're using to make your screencast

[SimpleScreenReader](http://www.maartenbaert.be/simplescreenrecorder/). I know nothing about Windows -- you will have to find for yourself. Be sure to make similar screencasts with both cases, with uBlock and without uBlock, same amount of time, same amount of scrolling in a similar manner.

**Comment by S3ndG** [comment] 2015-12-19 17:00
harshanvn, I don't have Windows 10 but 8.1. And a member of the staff of Mozilla has already made tests and has noticed that there was jank under windows 7 and not under windows 10.

**Comment by S3ndG** [comment] 2015-12-19 17:02
Is someone know a software that can work with windows 8.1? (to make my screencast).
I have snagit but it makes my firefox slower than usual while running...

**Comment by gorhill** [comment] 2015-12-19 17:10
> And a member of the staff of Mozilla has already made tests and has noticed that there was jank under windows 7 and not under windows 10.

With this statement you are confirming this has nothing to do with uBO -- uBO does not care about OS, it's written entirely in JS using a browser's API, with no part of it caring for the underlying OS.

**Comment by gorhill** [comment] 2015-12-19 17:33
uBo will [save every 4 minutes at most](https://github.com/gorhill/uBlock/blob/043825285c7141da2c5e376f093cc68595d2516f/src/js/storage.js#L50) the number of request blocked/allowed for when the counts change.

Could this be what is causing your issue? Maybe, but then uBO merely uses the browser API to do so, and uBO is using the [asynchronous (non-blocking) API](https://developer.mozilla.org/en/docs/Storage#Asynchronously), meaning it's extremely unlikely to be the cause of your issue -- especially that you say _"i must wait a bit (not long)"_ (4 minutes between each jank would be rather a long wait).

Are you having some kind of background task on your computer being triggered each time something is written to the computer storage? The FF doc re. Mozilla doc does mention that [caching is used](https://developer.mozilla.org/en-US/docs/Storage/Performance#Caching) for performance purpose. But I suppose some apps on a computer hooking into I/O OS API could possibly interfere -- only you can investigate why this is occurring on your computer.

**Comment by S3ndG** [comment] 2015-12-19 17:36
The member of mozilla didn't used uBO. Here is what he said : "Windows 10 was fine with or without hardware vsync and with or without adblock plus. Windows 7 was janky with or without hardware vsync and with or without adblock plus."

**Comment by S3ndG** [comment] 2015-12-19 18:13
"Are you having some kind of background task on your computer being triggered each time something is written to the computer storage?"
I don't think so... The only thing running right now is the Windows Maintenance, in the taskbar. Which is not always active and does not create problems...

**Comment by Hrxn** [comment] 2015-12-19 18:38
Did someone say Windows? :-)

For screen records with Windows, I'd recommend ShareX:
https://github.com/ShareX/ShareX
https://getsharex.com/

IMHO the easiest and most straightforward way

Regarding the background tasks:
Please use Process Explorer if you really need to know what is going on in the background:
https://technet.microsoft.com/en-us/sysinternals/bb896653

**Comment by S3ndG** [comment] 2015-12-19 19:05
thanks Hrxn i will try these things tomorrow :)

**Comment by S3ndG** [comment] 2015-12-20 11:13
Hello,
I've installed sharex and in order to record screencast I need ffmpeg.7zip.
And when I start the download of this file it says " can't connect to the server"
How can I make screencast with ShareX? ...

**Comment by Hrxn** [comment] 2015-12-21 03:17
Yeah, right. FFmpeg isn't included, I guess for licensing or copyright reasons, respectively.

You can get Windows builds of FFmpeg here:
https://ffmpeg.zeranoe.com/builds

Download either the 32-bit or the 64-bit Static build, depending on your OS.

In fact, this site is also linked on the ShareX wiki on GitHub.
https://github.com/ShareX/ShareX/wiki/FFmpeg-options

Short introduction how to use it:
https://github.com/ShareX/ShareX/wiki/FFmpeg

The ffmpeg.exe belongs into `..\ShareX\Tools\`
