### ISSUE TITLE
this extension failed to redirect a network request to

### ISSUE THREAD

**Issue by a1exus** [gorhill/uBlock#1619] opened 2016-05-09 16:29 UTC
I'm using `MacBook Pro (Retina, 15-inch, Early 2013)` with `OS X El Capitan 10.11.4 (15E65)`.

I install `uBlock Origin` extension to `Chrome 51.0.2704.36 beta (64-bit)` and I got following `Warning` (under another extension [Disconect](https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo)):

> This extension failed to redirect a network request to about:blank because another extension (uBlock Origin) redirected it to data:application/javascript;base64,X.

Please advise.

**Comment by gorhill** [comment] 2016-05-09 16:45
Duplicate of <https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068>.

**Closed by gorhill** 2016-05-09 16:45 UTC
