### ISSUE TITLE
ABP new filter not working on uBO

### ISSUE THREAD

**Issue by ylzhan** [gorhill/uBlock#2793] opened 2017-07-18 14:09 UTC
Hello,

https://adblockplus.org/development-builds/new-syntax-for-advanced-element-hiding-rules

New filter `-abp-has` doesn't work on uBO.
`
Test : 

https://yggtorrent.com/torrent/filmvid%C3%A9o/s%C3%A9rie-tv/23187-game+of+thrones+s07e01+vostfr+1080p+web+h264-extreme+mkv

Filter : 

`yggtorrent.com#?#TR > TD > TABLE > TBODY > TR:-abp-has(A[href$="/go_vpn"])`

Source : 

https://forums.lanik.us/viewtopic.php?f=91&t=37526

Config :

Chrome + uBO + Default (+ Liste FR)

Thanks.

**Comment by gorhill** [comment] 2017-07-18 14:22
Should be trivial to fix at first glance.

Note: I tried the filter in ABP. On my side, it works if refreshing the test page, however it does not work if opening as a new tab.

**Comment by mapx-** [comment] 2017-07-18 15:46
I filed a new ticket
https://issues.adblockplus.org/ticket/5425#ticket

**Comment by gorhill** [comment] 2017-07-20 23:32
@mapx- Looks like a timing issue: if you just click refresh button, it works; If you shift-click refresh button (thus bypassing the browser cache), it doesn't work.

**Comment by mapx-** [comment] 2017-07-21 06:31
Yes, ..sometimes even F5 still leave the ad unhidden.

**Comment by kasper93** [comment] 2017-07-29 13:05
I've already sent pull request with support for `-abp-has()` filters. https://github.com/gorhill/uBlock/pull/2755

**Comment by gorhill** [comment] 2017-09-28 16:54
Fixed with 8559669e89e8a12f18662d1b01ed7d76edb9c047.

**Comment by gorhill** [comment] 2017-09-30 00:45
I want to do more work on this.

Specifically, I want uBO to normalize the raw filter so that it can properly handle duplicate such as:

    facebook.com##div[id^="hyperfeed_story_id_"]:has(a:has-text(Chartered))

And

    facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a:-abp-contains(Chartered))

uBO will normalize procedural filters to properly discard duplicates -- especially given how procedural cosmetic filters are more CPU intensive. For instance, the above will be normalized to:

    facebook.com##div[id^="hyperfeed_story_id_"]:if(a:has-text(Chartered))

**Comment by joey04** [comment] 2017-10-02 18:09
@gorhill have a question about these new changes.

`tvguide.com##.listings-tab-link.active:matches-css-after(opacity: 1)`

I see atomized as:
![untitled](https://user-images.githubusercontent.com/14959062/31091867-63b197b6-a77a-11e7-8f38-6c5243df14ac.png)

Is the atomized `/1/` by design? It still works fine, but I don't recall seeing it that way in the Logger before. (This is the only procedural rule I have.)

**Comment by gwarser** [comment] 2017-10-02 18:18
https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmatches-cssarg

`/1/` - this is regular expression

**Comment by joey04** [comment] 2017-10-02 20:05
Thanks for the info, gwarser.

But I can confirm it has indeed changed. I forgot earlier I have GChrome with stock uBO rev 1.14.8. This is what my rule compiles to there:

![untitled](https://user-images.githubusercontent.com/14959062/31096856-58b8cbc0-a78b-11e7-84dc-5c4b2faee0de.png)

So why the change to regex `/1/` in the 1.14.11 beta?

**Comment by gwarser** [comment] 2017-10-02 21:11
Apparently part of [normalization](https://github.com/gorhill/uBlock/commit/ca299a394fa905dbb4f2aec6c8f5912ba59418d6#diff-3b15596213ed9ba37fb5b8bb1402a6c2R955)

**Closed** 2017-10-04 17:20 UTC

**Comment by ololoe** [comment] 2017-11-24 05:33
Hello, It doesn't work for me. uBlock Origin v1.14.19rc0 for Firefox. `#?#img` does nothing

**Comment by gorhill** [comment] 2017-11-24 05:43
Just use `##img`.

**Comment by ololoe** [comment] 2017-11-24 07:28
But I want to use -abp-has() feature. Will it work?

**Comment by mapx-** [comment] 2017-11-24 07:34
yes, it works with / without `?`

**Comment by ololoe** [comment] 2017-11-24 07:35
So which syntax do you support? Does ABP support it too?

**Comment by mapx-** [comment] 2017-11-24 07:36
uBo supports ABP and its own syntax, ABP ...doesn't

**Comment by ololoe** [comment] 2017-11-24 07:36
Isn't ABP's syntax `#?#`?

**Comment by mapx-** [comment] 2017-11-24 07:37
yes and uBo is supporting it.

**Comment by ololoe** [comment] 2017-11-24 07:37
you wrote above it doesnt

**Comment by mapx-** [comment] 2017-11-24 07:38
ABP doesn't support uBo implementation.

**Comment by ololoe** [comment] 2017-11-24 07:39
No! I mean
> yes, it works with / without `?`
Means Ublock doesnt support `#?#`?

**Comment by mapx-** [comment] 2017-11-24 07:42
uBo supports the ABP syntax for `:-abp-has / :-abp-contains` with / without `?`
ABP does not support `:has / :has-text`

Just do your tests and report back if you have real doubts

**Comment by ololoe** [comment] 2017-11-24 07:44
So why `#?#img` haven't worked?

**Comment by mapx-** [comment] 2017-11-24 07:46
Provide all the info: page link, what do you want to hide, eventuslly upload a screenshot indicating what do you want to hide, used filter

**Comment by ololoe** [comment] 2017-11-24 07:50
How should #?# work? ##img works but #?#img doesnt.

**Comment by ololoe** [comment] 2017-11-24 08:05
How to chain `:nth-of-type(2)` and `:has-text()`?

**Comment by gorhill** [comment] 2017-11-24 11:52
> Isn't ABP's syntax `#?#`?

My understanding was that this syntax was to be used only for procedural filters. I just tried it with ABP, and you are right, `example.com#?#img` works. So now I have no idea ABP went with `#?#`if it can be used as a replacement of `##`. I am pretty sure however that no filter list maintainer is going to use `#?#img` instead of `##img`. Maybe the fix is required on ABP 's side? I can't read their mind, I don't know why they went with `#?#`.

**Comment by gorhill** [comment] 2017-11-24 11:53
> How to chain `:nth-of-type(2)` and `:has-text()`?
> These filters doesn't work perfect yet.

Can you open a new issue about this? I used regex internally to parse procedural filters and I might have to move on parsing in a more reliable way without having to rely on regexes.

**Comment by Halibut80** [comment] 2017-11-24 16:52
@gorhil, I have a long-standing question, but I'm not sure, this is by design or I should also open issue about this:
These sort of filters is also does not work:
```
example.com##div:if(> div:has-text(Some)) + div
example.com##div:if(> div:has-text(Some)) ~ div
example.com##div:has(> div) + div
```
etc.

**Comment by gorhill** [comment] 2017-11-24 17:03
@Halibut80 Not supported. Open an issue if you wish, though I would work on this if I become convinced there is a real actual need in the wild rather than just a nice-to-have one.

**Comment by Halibut80** [comment] 2017-11-24 17:15
Well, i have some real case for this sort of rules, but they only for... hm, for personal easement (ughm, sorry, I don't have words to clear explain my phrase (my English is very bad)), and they also can be done with xpath, but last example looks like valid css selector and should work, or I'm wrong?

**Comment by gorhill** [comment] 2017-11-24 17:27
The parser for procedural cosmetic filters does not expect trailing stuff past the last parenthesis, so that fails as well even if it's supposed to be a valid CSS4 selector. Really I just went with the simpler implementation at first for what was needed as per what was seen in the wild at the time.

**Comment by Halibut80** [comment] 2017-11-24 17:32
Ok, thank you. This is a very minor problem, and can be done in a different way, so I will not open a new bug and waste your time.

**Comment by ololoe** [comment] 2017-11-24 18:34
> My understanding was that this syntax was to be used only for procedural filters. I just tried it with ABP, and you are right, example.com#?#img works. So now I have no idea ABP went with #?#if it can be used as a replacement of ##. I am pretty sure however that no filter list maintainer is going to use #?#img instead of ##img. Maybe the fix is required on ABP 's side? I can't read their mind, I don't know why they went with #?#.

https://adblockplus.org/filters#elemhide_css
> When writing an element hiding filter that makes use of these extended selectors you must use the #?# syntax, e.g. example.com#?#selector.

So AFAIU new selectors are only supported if you use  #?#, making easier to identify new rules. But more important, subscriptions are written for ABP, so you have to support ABP syntax.

**Comment by gorhill** [comment] 2017-11-24 18:36
> subscriptions are written for ABP, so you have to support ABP syntax

No filter list maintainers will use `#?#` for a normal filter. The fact that it works is incidental. I don't **have** to support something which is never meant to be used this way.

**Comment by ololoe** [comment] 2017-11-24 18:37
But do you support #?# syntax at all??

**Comment by okiehsch** [comment] 2017-11-24 18:38
````
spielaffe.de#?##advertising_billboard
spielaffe.de#?##app_advertising_skyscraper_right
kino.de#?#.banner
````
part of `EasyListGermany`

**Comment by okiehsch** [comment] 2017-11-24 18:41
````
cnet.com#?#.ad-leader-top
cnet.com#?#.ad-mpu-plus-bottom
cnet.com#?#.ad-mpu-plus-middle
cnet.com#?#.ad-mpu-plus-top
cnet.com#?#.ad-nav-ad
cnet.com#?#.ad-replay-wide-top
````
part of `EasyList`

**Comment by gorhill** [comment] 2017-11-24 18:42
Well I have no clue what is going on between ABP and EasyList maintainers. I don't get the point of this new syntax -- aside breaking other blockers client of EasyList.

**Comment by ololoe** [comment] 2017-11-24 18:43
okiehsch
I think too #?# should be only used for rules with advanced selectors, but this syntax has to be supported. 

gorhill 
https://github.com/gorhill/uBlock/issues/2793#issuecomment-346880955

**Comment by okiehsch** [comment] 2017-11-24 18:45
The syntax **is** supported for advanced selectors, I don`t know why EasyList started to use it for "normal"
filters.

**Comment by ololoe** [comment] 2017-11-24 18:47
okiehsch 
Maybe people make a rule with advanced selector, then edit it and see that it work without advanced selector too.

**Comment by gorhill** [comment] 2017-11-24 18:49
Wait, these are properly handled in uBO, I just stepped into the code. I just tried `#?#img` again and it worked fine. So no issue in the end.

**Comment by okiehsch** [comment] 2017-11-24 18:51
@gorhill 
![gdfg](https://user-images.githubusercontent.com/16838044/33221573-c19ac0dc-d150-11e7-9b55-75e0e12872e5.PNG)
seems to work anyway.

**Comment by ololoe** [comment] 2017-11-24 18:52
So why doesn't it work for me? Version here https://github.com/gorhill/uBlock/issues/2793#issuecomment-346746463

**Comment by gorhill** [comment] 2017-11-24 18:53
My mistake, I should have demanded reproducible steps. I can't answer if I can't reproduce exactly what you tried.

**Comment by mapx-** [comment] 2017-11-24 19:04
well, I tested this morning (and works with / without `?`) and already answered to the user and asked a real test example :)
https://github.com/gorhill/uBlock/issues/2793#issuecomment-346760943

**Comment by okiehsch** [comment] 2017-11-24 19:07
Sorry, I missed that.

**Comment by ololoe** [comment] 2017-11-24 19:08
@gorhill 
I wrote above what I've done https://github.com/gorhill/uBlock/issues/2793#issuecomment-346746463

**Comment by mapx-** [comment] 2017-11-24 19:28
@ololoe  if your filter is exactly `#?#img` it does not work because in that syntax ABP expects to have non-generic filters.

You need example.com#?#img

**Comment by ololoe** [comment] 2017-11-24 19:29
@mapx- 
I enter it into ublock's select element window. Tried `github.com#?#img` - still nothing.

**Comment by mapx-** [comment] 2017-11-24 19:35
`github.com#?#img` tested on my github profile, is working fine hiding my avatar

**Comment by ololoe** [comment] 2017-11-24 19:38
@mapx- 
I wrote above several times which software I use https://github.com/gorhill/uBlock/issues/2793#issuecomment-346746463

**Comment by okiehsch** [comment] 2017-11-24 19:45
#?#img will not work if you enter it in uBO's interactive element picker mode.
Why should it? If you are using **uBO**  why would you  use `#?#`.

**Comment by ololoe** [comment] 2017-11-24 19:48
@okiehsch why don't valid selector work in picker window???

**Comment by okiehsch** [comment] 2017-11-24 19:54
Because it is an `Adblock/Plus` specific filter, I still don't know why you would use `#?#` instead of `##` if you are trying to create a filter with **uBlock Origins** element picker.
I think it is sufficient for uBO to properly handle these `Adblock/Plus` specific filters if you add them to your filter list.

**Comment by ololoe** [comment] 2017-11-24 19:56
I'm trying to check if this syntag work. So you think if I enter this rule another way it will work???

**Comment by okiehsch** [comment] 2017-11-24 19:58
Add `github.com#?#img` to your filter list, click apply and then reload this page.

**Comment by mapx-** [comment] 2017-11-24 19:58
@ololoe  I already answered you twice. **Yes, it works**, add the filter in "my filters".

**Comment by ololoe** [comment] 2017-11-24 20:12
If a rule works it the settings and doesn't work in the picker it's a bug!

**Comment by ololoe** [comment] 2017-11-24 21:15
So basically I spent so much time here because of a bug which you even don't accept as a bug?

**Comment by gorhill** [comment] 2017-11-24 21:22
> you even don't accept as a bug?

Right, I don't accept as a bug, because the workaround is: don't use `?` in the element picker, because there is no point.
