### ISSUE TITLE
Ads on NoScript's successfully installed page aren't blocked until the page is refreshed.

### ISSUE THREAD

**Issue by hook54321a** [gorhill/uBlock#3128] opened 2017-10-13 07:06 UTC
I installed NoScript 5.1.1, and then immediately it opens a page (https://noscript.net/?ver=5.1.1) and the ads aren't blocked on it until I refresh the page. I tried this on multiple profiles and on multiple computers. The browser I'm using is Waterfox 55.2.2. I'm pretty sure this is the right place to report this since it's not a filter issue.

**Comment by gwarser** [comment] 2017-10-13 10:27
I don't see ads on this page on Firefox stable and ESR (UBO enabled/disabled), only donation boxes. Can you post screenshot?

**Comment by uBlock-user** [comment] 2017-10-13 10:41
It's by design. Open `advanced-settings.html` page and set `suspendTabsUntilReady`  to `true`.

**Comment by gorhill** [comment] 2017-10-13 11:50
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-10-13 11:50 UTC
Labels: filter issue, invalid

**Comment by hook54321a** [comment] 2017-10-13 20:35
Description of the issue:
Ads on NoScript's successfully installed page aren't blocked until the page is refreshed.

URL where the issue occurs: https://noscript.net/?ver=5.1.1

Steps to reproduce the issue:
1. Install Ublock Origin
2. Install NoScript, then NoScript opens up the successfully installed page, with ads on it.
3. Refresh page and ads aren't there.
(NoScript might not open it's successfully installed page if you have installed it before.)

Default settings.

- OS/version: Windows 7
- Browser/version: Firefox 52.2.1 (32-bit)
- uBlock Origin version: 

Default filter lists.
![noscriptads](https://user-images.githubusercontent.com/7744057/31565329-3c6898cc-b01b-11e7-9506-4dcea875a016.PNG)

**Comment by GuardianMajor** [comment] 2017-10-13 20:52
This has to do with the blocking not being able to trigger while the browser is loading.

He has provided an advanced setting [suspendTabsUntilReady](https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental) to deal with this as best as possible, give that a try and see if it fixes your issue, otherwise, if it is working on reload, then it is working as intended, just a timing issue.

**Comment by gorhill** [comment] 2017-10-13 23:26
> This has to do with the blocking not being able to trigger while the browser is loading.

If this is the issue being reported, then this is a browser bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1378459>.

Beyond this, aside `suspendTabsUntilReady` not absolutely guaranteeing perfect blocking at launch time, there is also the fact that `suspendTabsUntilReady` is also subject to be reset to default (`false`) because of another browser bug with Firefox: <https://bugzilla.mozilla.org/show_bug.cgi?id=1313401>.

**Comment by GuardianMajor** [comment] 2017-10-14 02:21
> If this is the issue being reported, then this is a browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1378459.

Correct, that's why I suggested the best available option provided already, not guaranteed but better than nothing. They said that reloading blocked the ads, that was key for me to think that since the release notes are only loaded when you first install it (or update, if you haven't disabled that option) after restart then that's probably the issue. We haven't heard back, so we can only do our best assumption and provide whatever solution we can.

> Beyond this, aside suspendTabsUntilReady not absolutely guaranteeing perfect blocking at launch time, there is also the fact that suspendTabsUntilReady is also subject to be reset to default (false) because of another browser bug with Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1313401.

True, but best option of the available solutions. As for the reset of `suspendTabsUntilReady` that can be somewhat worked around as I posted here #3085 and steps are in the [comment](https://github.com/gorhill/uBlock/issues/3085#issuecomment-333607563), not the best solution but works until they fix it. It seems that those are somehow kept in the cookies not the localStorage or some bastardized version of it that is clearing out with the cookies, because for me protecting that cookie, solves the reset.

Followup to my last question, didn't hear back, have you considered storing those in the same DB that you store the other settings, maybe that will somehow mitigate it? Just a thought.
