### ISSUE TITLE
Font blinking with Pale Moon

### ISSUE THREAD

**Issue by refriedfood** [gorhill/uBlock#3488] opened 2018-02-07 10:06 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
UBlock (1.13.8) and Pale Moon (27.6.2) causes sites such as Youtbue and newegg to blink their text. Firefox (47.0.2) does not have this issue. This is only with Pale Moon. A screenshot will not work in this case so I've provided video clips.

### One or more specific URLs where the issue occurs
https://www.newegg.com/Product/NewProduct.aspx?Item=N82E16820231301&RandomID=48484675165820180207013813
https://www.youtube.com/results?search_query=G.SKILL+4GB+%282+x+2GB%29+240-Pin+DDR2+SDRAM+800

### Screenshot in which the issue can be seen

https://streamable.com/fp7i4 = Newegg, enabled
https://streamable.com/67w9f = Newegg, disabled
https://streamable.com/ktsy7 = Youtube, enabled
https://streamable.com/e7a5v = Youtube, disabled

### Steps for anyone to reproduce the issue

Download and install Pale Moon (x64 or x86) install Ublock Origin and go to the sites listed above with the filters specified. Do the same with another browser or with Ublock disabled.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7 U x64
- Browser/version: 27.6.2 (tested on x86 version as well)
- uBlock Origin version: 1.13.8

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Auto-update filter lists  
Parse and enforce cosmetic filters
My filters
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
Adblock Warning Removal List
EasyList
EasyPrivacy
Malware Domain List
Malware domains
Peter Lowe’s Ad and tracking server list

##### Your custom filters (if any)

||www.reddit.com/chat/minimize$subdocument
||elephant.fotostrana.ru/get?gid=78&format=iframe&place=728x90$subdocument

||i.imgur.com/zMYrRmh.gif

! 11/6/2017, 2:47:51 AM http://www.veoh.com/
||ll-appserver.veoh.com/images/5.6.0/pages/relatedbar/uparrow-default.png?version=AFrontend.5.7.0.1509$image
www.veoh.com###RelatedVideosContainer
||d37h3y471q0lt2.cloudfront.net/assets/feedback_trans_tab-fa5bd26fde4425fd8102f4380980fc11.png$image

! 11/6/2017, 10:54:24 PM http://www.imdb.com/
imdb.com###sidebar
imdb.com###center_btf
||images-na.ssl-images-amazon.com/images/M/MV5BMjA3NDU3NjI2NV5BMl5BanBnXkFtZTgwODY1MTU2NDM@._V1_SY351_SX624_AL_.jpg$image
www.imdb.com###center_btf
www.imdb.com###maindetails_sidebar_bottom
www.imdb.com##.article > .ab_widget > .ab_ninja

||images-na.ssl-images-amazon.com/images/M/*@._*,*,*,*_UX614_UY460._SY230_SX307_AL_.jpg$image

! 11/7/2017, 5:00:57 PM https://answers.yahoo.com/
||s.yimg.com/dh/ap/default/*/*_*_*.jpg$image

! CLEAR-TYPE FONTS (fontawesome is an ASCII font)
m.media-amazon.com/images/G/01/AUIClients/AmazonUIBaseCSS-amazonember*$font
media-amazon.com/images/G/01/AUIClients/AmazonUIBaseCSS-amazonember*$font
||fonts.gstatic.com/s/*$font
||fonts.googleapis.com/css?family=*
||www.meetup.com/mu_static/en-US/graphik*$stylesheet,domain=www.meetup.com
||secure.meetupstatic.com/s/fonts/402715706936963211631/graphik.css$stylesheet,domain=www.meetup.com
||s.gr-assets.com/assets/*$font
||addons-amo.cdn.mozilla.net/*$font
||dn3yv4xbph5cn.cloudfront.net/assets/*$font
||mozilla.net/media/fonts/*$font
||mozilla.net/static/sumo/fonts/*$font
||www.redditstatic.com/desktop2x/fonts/BentonSans/*$font
||steamstatic.com/public/shared/fonts/MotivaSans*
||steamstatic.com/public/shared/fonts/Motiva-Sans*
||palemoon.org/css/Museo*$font
||palemoon.org/skin/palemoon/Museo*$font

! 11/11/2017, 1:47:06 AM https://www.amazon.com/ top frame
www.amazon.com###nav-upnav

! 11/17/2017, 11:47:36 PM http://www.thesaurus.com
www.thesaurus.com##.editorial-content-feed
www.thesaurus.com##.survey
www.dictionary.com###fly-out
www.dictionary.com##.survey
www.dictionary.com##.left-nav-sticky
www.dictionary.com##.editorial-content-feed

http://35.188.14.213
http://35.188.59.75

reddit.com##.commentsignupbar__link-wrapper.login-required

osdownloader.org##.et-slide:nth-of-type(3) > .clearfix.container > .description

cpm20.com

||b.misslk.com/11622.gif$image

k26fe9xhuzm.com

www.dictionary.com##.others-are-reading-list
www.dictionary.com##.constant-content
www.thesaurus.com###explore-gutter

extratorrent.cd##table:nth-of-type(2) > tbody > tr

reddit.com##.listingsignupbar.infobar
reddit.com###block-homepage

! 12/31/2017, 3:43:22 AM https://groups.yahoo.com/neo
groups.yahoo.com###yset-search-upsell-container

! 1/2/2018, 5:50:54 PM http://www.thesaurus.com/
||static.sfdict.com/editorial-content/*$image

http://clkntrk.com
surveyveal.com

! 1/3/2018, 4:01:34 AM http://www.dailymotion.com/
www.dailymotion.com##.Grid__grid___17BYI.Grid

www.iconarchive.com###fbpop

||shutterstock.com/thumb_large/*$image

! 1/11/2018, 3:01:47 AM http://www.veoh.com/
||www.veoh.com/static/swf/veoh/SPL.swf?version=1515668542$object
www.veoh.com###featuredVideoPlayerContainer

**Comment by anewuser** [comment] 2018-02-07 14:16
Pale Moon is not supported by the developer of uBlock Origin. Post on the PaleMoon forums to see if anyone can help you there.

**Comment by gorhill** [comment] 2018-02-07 15:32
Closing as invalid because:

1. You didn't make the case the issue is with uBO and not a filter one -- especially considering you have lots of custom filters about font blocking, this is most likely your issue.
2. You re using an obsolete version of uBO.

**Closed by gorhill** 2018-02-07 15:32 UTC
Labels: invalid

**Comment by refriedfood** [comment] 2018-02-08 01:42
Sorry, just trying to get help not trash anyone, you dicks.

**Comment by gorhill** [comment] 2018-02-08 10:04
Please stick to narrow to whether this is a filter issue or not, currently you did not make the case this is a uBO issue. If you want help, this is not the place, as pointed out in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).
