### ISSUE TITLE
Question: How do I check if a domain/website is filtered by the extension?

### ISSUE THREAD

**Issue by adrian7** [gorhill/uBlock#183] opened 2015-05-07 08:18 UTC
I have recently received a newsletter from a website I visit often. However when I clicked some of the links in their newsletter, a the new tab opens and then closes instantly. 
The website is not an ad server, also does not hosts advertising.
Usually uBlock lets me know why it blocked a page/domain but this did not happened this time.

Is there a way to check if a URL would be filtered by the extension.

Thanks.

**Comment by CrisBRM** [comment] 2015-05-07 09:00
[Yes](https://github.com/gorhill/uBlock/wiki/The-network-request-logger), use the network request logger.

**Comment by gorhill** [comment] 2015-05-07 12:19
Probably duplicate of #173.

Short answer: force a refresh of EasyList.

**Closed as completed by gorhill** 2015-05-07 12:19 UTC
