### ISSUE TITLE
Delete key frequently not working in zapper mode

### ISSUE THREAD

**Issue by tamlin-mike** [gorhill/uBlock#3631] opened 2018-03-20 23:40 UTC
uBlock Origin: 1.15.18
Firefox 59.0.1 64-bit, Windows. Multiple tabs open.

There is not solid repro. It happens seemingly stochastically.

Entering zapper mode (clicking UO icon, clicking the zapper icon) works.
Moving mouse around on the page displays the zapper is active and working (it "highlights" elements mouse cursor is over).
Clicking anything selected works as expected (it's removed).
Delete key while hovering over something frequently fails.

I don't know if this is a problem with Firefox, failing to send keyboard events to UO, or UO itself for some reason failing to act, but it's become annoying enough I feel the problem needs to be documented, and the source of it fixed.

Behavior I have observed is that once Delete key works once for a page, it keeps working. This lends credibility to my theory it's a matter of keyboard events. On failure, using mouse to make sure the displayed web-page is active, even selecting some text on it, does not help solve the problem.

**Comment by gwarser** [comment] 2018-07-13 18:46
Duplicate of https://github.com/gorhill/uBlock/issues/953
Also https://github.com/gorhill/uBlock/issues/2719

**Comment by gorhill** [comment] 2018-07-13 20:51
Beside the focus issue described in these other issues, it could also be another event listener (from the page or another extension) "eating" key down events.

**Comment by gwarser** [comment] 2018-07-13 21:20
I googled a bit - Firefox have problems with focusing inside iframe. People suggest to wait for frame to be fully loaded 

https://stackoverflow.com/questions/1508348/set-focus-to-iframe-body-content-in-firefox
https://stackoverflow.com/questions/369026/setting-focus-to-iframe-contents
https://stackoverflow.com/questions/14377219/focus-in-an-iframe-in-firefox

**Comment by gwarser** [comment] 2018-08-15 12:32
I cannot reproduce anymore on Nightly 63, beta and stable still affected.

Hovewer:

>There is not solid repro. It happens seemingly stochastically.

**Comment by gorhill** [comment] 2020-10-17 18:00
> OK in Chromium 71, Firefox 64.

Alright then, closing. A new issue should be opened if ever it's being reproduced again.

**Closed by gorhill** 2020-10-17 18:00 UTC
