### ISSUE TITLE
Does this affect uBlocko?

### ISSUE THREAD

**Issue by streetwolf** [gorhill/uBlock#960] opened 2015-11-23 16:56 UTC
Please take a look at my post here... http://forums.mozillazine.org/viewtopic.php?f=23&t=2975063.  Any impact on uBlocko?  I have the patch on Fx45 and things seem OK except I am having problems getting to a couple of sites.  I have to disable uBlocko for them.  Don't now if it's the patch or a coincidence.  One site is http://beta.speedtest.net/server/663.

Fx45 64bit.
uBlocko 1.3.6
Windows 10 with Update 1.

**Comment by gorhill** [comment] 2015-11-23 17:50
> One site is http://beta.speedtest.net/server/663.

What is the problem specifically?

**Comment by streetwolf** [comment] 2015-11-23 18:01
Using the basic filters I could get to the site with no problems.  Recently however when I go here the spinner on the tab keeps spinning and I get a popup notification that something is slowing down Firefox.  It asks if I want to wait or stop.  Wait doesn't help.  If I disable uBo for the site then it works although I get all the ads.

I can't really say it was the patch that is referenced in my post or not but the timing is close to say the least.  I also have this same problem with HBOGO.  I can get to a video but when I start to play it I get the same popup message.  Both sites use Flash btw.


____
Gary

----- Original Message -----

**Comment by gorhill** [comment] 2015-11-23 18:06
The spinning usually means the browser is waiting for an answer to a network request. Open the dev console for the page and see what network request is pending.

Doubt this is related to uBO, I can't think of nothing -- but sometimes depending on what is blocked on a page, the page may misbehave and such symptoms as a never ending spinner is one possible symptom.

**Comment by streetwolf** [comment] 2015-11-23 18:12
Does this mean anything to you.  I got 5 in a row.

Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src 'unsafe-eval' *").


____
Gary

----- Original Message -----

**Comment by gorhill** [comment] 2015-11-23 18:13
> Does this mean anything to you. I got 5 in a row.

You are blocking inline scripts?

**Comment by streetwolf** [comment] 2015-11-23 19:05
I'm talking the default 3rd Party Filters and I'm not blocking anything extra.  One day it worked with filtering the next day it didn't.

I tried adding the line contentaccessible=yes to uBo's chrome.manifest but all that did was make uBo not work.  I suppose it has to do  with the way it is obfuscated.  If you could provide me with a manifest with this parameter I can replace it and see what happens.

____
Gary

----- Original Message -----

**Comment by gorhill** [comment] 2015-11-23 20:34
> I suppose it has to do  with the way it is obfuscated

What does that mean?

**Comment by streetwolf** [comment] 2015-11-23 21:19
Obfuscate means to make the code more difficult to read usually by running everything together in one big line.  Your stuff isn't obfuscated.  I was using notepad to edit it and notepad didn't format it correctly.  I used notepad++ and it looked fine.  I added the parameter to your chrome.manifest but it didn't help.  I don't know if I added it correctly though.  I'm not familiar with all the ./ in your manifest.


____
Gary

----- Original Message -----

**Comment by streetwolf** [comment] 2015-11-24 01:08
I tried a different adblocker (AdGuard) and the sites behaved the same way.


____
Gary

----- Original Message -----

**Comment by RoxKilly** [comment] 2015-11-24 10:02
I am unable to replicate your issue on FF42, uBO 1.3.6, Windows 7.

Given that you don't have custom rules of your own, if a different blocker behaves the same way, the problem is likely coming from a block list that the blockers share. gorhill gave you a good way to start isolating the problem:
> The spinning usually means the browser is waiting for an answer to a network request. Open the dev console for the page and see what network request is pending

You haven't responded directly but this would be a good starting point. You could also open the uBO dynamic filtering options to see which domains are being blocked. They are indicated by minus signs `-` in the UI. For instance checkout the domain `githubapp.com` in my screenshot:
![2](https://cloud.githubusercontent.com/assets/12346501/11363179/2c790a20-9266-11e5-8467-aaf72a343833.png)
Manually allow the domains one at a time by clicking the left-third of the cell that has the minus sign. That cell should turn green.  This will override the default block list.  Once a domain is allowed, refresh the page and see whether the problem persists.  You will eventually figure out which network request is hanging the page.

In my screenshot above, notice for instance that at least one call to `githubapp.com` is blocked. If I find out that this is a problem, I would next open the Logger to find out which block rule, from which block list is to blame.  There is a search field above the log. Enter the blocked domain there to quickly find requests made to it.  Blocked requests have a reddish background.  
![3](https://cloud.githubusercontent.com/assets/12346501/11363412/be652fe4-9267-11e5-93c7-9aaa96bc6415.png)

Once you spot the specific request, click on the 3rd column to bring up the source of the block.  In my example, I find out that a rule from the EasyPrivacy list is causing this block.

![4](https://cloud.githubusercontent.com/assets/12346501/11363426/e31766e0-9267-11e5-96f5-1e4bbdfe187a.png)

**Comment by streetwolf** [comment] 2015-11-24 17:11
For some reason I now have to allow doubleclick.net for speedtest.net.  I didn't need to do this as of a week or so ago.

**Comment by gorhill** [comment] 2015-12-05 16:33
Closing due to failure to make the case there is an actual issue with uBO itself.

**Closed by gorhill** 2015-12-05 16:33 UTC
