### ISSUE TITLE
[Seamonkey] Not activated in all browser windows

### ISSUE THREAD

**Issue by wmchan4** [gorhill/uBlock#210] opened 2015-05-17 08:49 UTC
Hi, I have Seamonkey 2.33, uBlock Origin, Session Manager and a few other extensions installed. 
As the title said, I have some observations:
(1) I have totally 3 windows in my current session. When SM starts, I find that u0 is only enabled 
in the first opened window, but for other 2 windows it's disabled, including the context menu items
and the ad-blocking functions.
I have a workaround of that: go to Addon Manager, reset (disable and enable) u0. Then u0 will be
activated in all 3 windows.
(2) I can consistent see the following messages popping up in the SM Error Console (use 
Shift-Control-J to open it.) 
I think that they should indicate some sort of performance issues but I don't know what 
they are. The messages are pasted below:

---

Timestamp: 16/5/2015 22:06:10
Error: NS_ERROR_NOT_INITIALIZED: 
Source File: chrome://ublock0/content/js/pagestore.js
Line: 203

---

Timestamp: 16/5/2015 22:06:07
Error: NS_ERROR_NOT_INITIALIZED: 
Source File: chrome://ublock0/content/js/async.js
Line: 201

---

Timestamp: 16/5/2015 22:06:26
Error: NS_ERROR_NOT_INITIALIZED: 
Source File: chrome://ublock0/content/js/tab.js
Line: 191

---

**Comment by gorhill** [comment] 2015-05-17 11:15
Duplicate of #49.

**Comment by gorhill** [comment] 2015-05-17 14:44
Alright, I will give it a shot and install SeaMonkey, if it's a trivial fix.

**Comment by gorhill** [comment] 2015-05-17 17:24
I am going to need detailed steps about how to reproduce this. I opened three windows, randomly navigated, and I couldn't see any errors at the console.

**Closed as completed** 2015-06-17 23:09 UTC
Labels: unable to reproduce
