### ISSUE TITLE
Typing an @-symbol opens the logger page

### ISSUE THREAD

**Issue by fv0** [gorhill/uBlock#2724] opened 2017-06-21 11:52 UTC
### Describe the issue

When I try to type an @-symbol on a website with my German keyboard layout (QWERTZ), it opens the logger page. On the German layout you get an <kbd>@</kbd> symbol by pressing the shortcut <kbd>ALT</kbd> + <kbd>L</kbd>. 

### One or more specific URLs where the issue occurs

On every website.

### Screenshot in which the issue can be seen

![kapture 2017-06-21 at 12 39 36](https://user-images.githubusercontent.com/8401092/27382837-70349254-5680-11e7-8164-dd0fb9d7d579.gif)

### Steps for anyone to reproduce the issue

1. Set a German QWERTZ keyboard layout.
2. Type the <kbd>@</kbd>-symbol by pressing <kbd>ALT</kbd> + <kbd>L</kbd>.

### Your settings

- OS/version: macOS Sierra 10.12.4
- Browser/version: Chrome 58.0.3029.110 (Official Build) (64-bit) 
- uBlock Origin version: 1.13.0

##### Your filter lists

Default lists.

##### Your custom filters (if any)

None.

**Comment by bershan2** [comment] 2017-06-21 11:59
You should update to 1.13.2. Please go to chrome://extensions and click "Update extensions now".

**Comment by gorhill** [comment] 2017-06-21 12:18
Duplicate of #2723.

**Closed by gorhill** 2017-06-21 12:18 UTC
Labels: duplicate
