### ISSUE TITLE
One more filter for you

### ISSUE THREAD

**Issue by DarkeningNightofSofia** [gorhill/uBlock#449] opened 2015-07-05 23:39 UTC
https://easylist-downloads.adblockplus.org/adwarefilters.txt

**Comment by anewuser** [comment] 2015-07-06 19:17
Use the search bar and read the [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) file before posting.

Close this because it's a duplicate of #413.

**Comment by gorhill** [comment] 2015-07-06 19:22
Should be added there: https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web.

**Closed as completed by gorhill** 2015-07-06 19:22 UTC
