### ISSUE TITLE
False positive / popup blocked

### ISSUE THREAD

**Issue by smed79** [gorhill/uBlock#372] opened 2015-06-19 04:44 UTC
Hello, 
on [google privacycheckup](https://myaccount.google.com/privacycheckup/5) (2. Improve ad relevance) using **Adblock Plus**, clicking the link [settings/ads](https://www.google.com/settings/ads) open popup to `google.com/ads/preferences/checkgoog?` but the popup is blocked using **uBlock** due to redirection to `googleads.g.doubleclick.net`.

`||googleads.g.doubleclick.net^$popup,third-party`

Regards,
Med

**Comment by harshanvn** [comment] 2015-06-19 10:19
It looks like a 3rd party filter issue. For me this filter is listed under -
<code>Fanboy+Easylist-Merged Ultimate List</code>

Report it to easy list forum..

**Comment by gorhill** [comment] 2015-06-19 11:28
Ok... This does not happen with other blockers. However, AdBlock and Adguard also fails at [popup tests 9 and 10](http://raymondhill.net/ublock/popup.html), which I believe is the same sort of case here.

There is definitely a filter in EasyList to block popups: `||googleads.g.doubleclick.net^$third-party,popup`. So it is unexpected to me as to why is ABP not enforcing that filter. This suggests to me that the popup blocker in ABP would fail some tests.

So I will create an exception filter in uBlock, because I do believe uBlock is doing the right thing by enforcing that popup blocker filter in EasyList.

_However_, after I created the exception filter, the problem persisted. There is another bug lurking in static filtering engine regarding exception filters, and trying to create the exception filter uncovered this bug. This is a rather serious bug, and that it didn't manifest itself more prominently is because it manifest itself only for specific requests. This needs fixing ASAP.

**Closed as completed** 2015-06-19 11:30 UTC

**Comment by gorhill** [comment] 2015-06-19 12:28
Assessing the impact of the regression bug, I found 23 filters in EasyList were affected by it:

    @@||doubleclick.net^*/targeted.optimum/*;sz=968x286;$image,popup,script
    @@||ads.stumbleupon.com^$popup
    @@/redirect.aspx?pid=*&bid=$popup,domain=betbeaver.com
    @@||adfarm.mediaplex.com/ad/ck/$popup,domain=betwonga.com|pcmag.com
    @@||ads.betfair.com/redirect.aspx?pid=$popup,domain=betwonga.com
    @@||ads.flipkart.com/delivery/ck.php?$popup,domain=flipkart.com
    @@||ads.pinterest.com^$popup,~third-party
    @@||ads.reempresa.org^$popup,domain=reempresa.org
    @@||ads.sudpresse.be^$popup,domain=sudinfo.be
    @@||ads.twitter.com^$popup,~third-party
    @@||ads.williamhillcasino.com/redirect.aspx?*=internal&$popup,domain=williamhillcasino.com
    @@||adserving.unibet.com/redirect.aspx?pid=$popup,domain=betwonga.com
    @@||adv.blogupp.com^$popup
    @@||bet365.com/home/?affiliate=$popup,domain=betbeaver.com|betwonga.com|betyper.com
    @@||doubleclick.net/click%$popup,domain=people.com|time.com
    @@||doubleclick.net/clk;$popup,domain=hotukdeals.com|jobamatic.com|play.google.com|santander.co.uk|techrepublic.com
    @@||doubleclick.net/ddm/clk/$popup,domain=couponcodeswap.com
    @@||g.doubleclick.net/aclk?$popup,domain=bodas.com.mx|bodas.net|casamentos.com.br|casamentos.pt|casamiento.com.uy|casamientos.com.ar|mariages.net|matrimonio.com|matrimonio.com.co|matrimonio.com.pe|matrimonios.cl|weddingspot.co.uk|zillow.com
    @@||gsmarena.com/adclick.php?bannerid=$popup
    @@||serving-sys.com/BurstingPipe/adServer.bs?$popup,domain=jobamatic.com
    @@||viroll.com^$popup,domain=imagebam.com|imgbox.com
    @@||imagebam.com/image/$popup
    @@||supportchat.contentabc.com^$popup,domain=brazzerssupport.com

**Comment by Piter432** [comment] 2015-06-19 18:50
Similar problem is with gamersyde.com, while trying to watch the screenshoots from video games. The window with a screenshoot is blocked by uBlock Origin, even I allowed to open pop-ups in gamersyde (the first site-based switch doesn't have "X" on it's icon).

**Comment by gorhill** [comment] 2015-06-19 21:34
> trying to watch the screenshoots from video games

Without a specific URL, I can't do anything.

**Comment by gorhill** [comment] 2015-06-19 21:36
I tried here <http://www.gamersyde.com/game_images_2849_en.html>, and it works all fine with default settings. Check your logger, it will tell your which filter is causing you problem.

**Comment by Piter432** [comment] 2015-06-19 22:25
Unfortunately, I tried to investigate that in the logger and tried dynamic and static URL filtering and tried many combinations with this two URL filtering - effect is always the same as I described earlier.

**Comment by gorhill** [comment] 2015-06-19 22:30
Again, you do not provide a _specific_ case. It's impossible for whoever to provide an answer to your issue. I did provide a specific case, and it worked fine.

**Comment by Piter432** [comment] 2015-06-19 23:02
This happens on all gamersyde pages, that contain at least one screenshot from any video game and after clicking on the picture are opening in gamersyde pop-up window. The example URL to my problem is that you've provided and similar to them like this: http://www.gamersyde.com/news_resident_evil_0_hd_trailer_screens-16608_en.html

**Comment by gorhill** [comment] 2015-06-19 23:04
> http://www.gamersyde.com/news_resident_evil_0_hd_trailer_screens-16608_en.html

It worked fine here. The logger will tell you what request got blocked.

**Comment by Piter432** [comment] 2015-06-19 23:31
Looks like the static filter "pop$popup", which is in "JPN: ABP Japanese filters (日本用フィルタ)" is causing this problem, but I don't want to turn off this filters list.

**Comment by Blutgang** [comment] 2015-06-20 00:20
@Piter432 Hmm...the logger shows the filter as `pop$popup` but the JPN list shows `^pop_$popup` instead. I'm not very good at writing filters. You can try `@@||gamersyde.com/pop_$popup` or `@@^pop_$popup,domain=gamersyde.com`

**Comment by SMed79** [comment] 2015-06-20 02:02
@Piter432 repport this issue to [JPN list](https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt) autor @[k2jp](https://github.com/k2jp).

**Comment by Piter432** [comment] 2015-06-20 14:19
@Blutgang All your propositions didn't help :(

@SMed79 Issue reported. I hope that he can find a fix for that :)

**Comment by gorhill** [comment] 2015-06-20 14:56
> All your propositions didn't help :(

If `gamersyde.com` has no nasty popup, just use `@@||gamersyde.com^$popup`.

**Comment by Piter432** [comment] 2015-06-20 15:18
@gorhill Didn't help :(

**Comment by gorhill** [comment] 2015-06-20 15:24
It works in 0.9.9.2.

**Comment by Piter432** [comment] 2015-06-20 15:39
Eh, I forgot I'm using Chrome now and newest version in their Web Store is 0.9.9.1. Sorry for that :(

I will wait for update to uBlock Origin for Chrome and then I will try. If everything will be ok, I will close this issue.

**Comment by Piter432** [comment] 2015-06-22 13:47
Okay, so the issue is resolved after updating uBlock Origin to version 0.9.9.2. Thanks for help :)

**Comment by ryanbr** [comment] 2015-07-11 23:12
I was trying to reproduce this issue, and the page in question still launches in Adblock Plus fine

**Comment by TeddStriker** [comment] 2015-07-11 23:24
@ryanbr 

The poster above you said that the issue was fixed.
>Okay, so the issue is resolved after updating uBlock Origin to version 0.9.9.2. Thanks for help :)

I don't really see how it launching in ABP is relevant.

**Comment by ryanbr** [comment] 2015-07-11 23:29
Very relevant. If this was to be included into Easylist I need to reproduce this in ABP. If its an issue with uBlock then nothing will done.

**Comment by gorhill** [comment] 2015-07-12 03:10
> If its an issue with uBlock then nothing will be done.

Yes, this was an issue in uBlock (regression), affecting filters with both the `popup` and `third-party` options.
