### ISSUE TITLE
Suggestion: add "generic" checkox for Create button in Element picker 

### ISSUE THREAD

**Issue by bojovyletoun** [gorhill/uBlock#3548] opened 2018-02-25 20:58 UTC
In element picker, there is  annoyance that every cosmetic filter created with _Create_ button is coerced to be specific (bounded to its corresponding domain). (Also noted in [wiki](https://github.com/gorhill/uBlock/wiki/Element-picker)). It would be _time-saving_ if there is option to save that filter generic by one of possible ways

-  checkbox Generic/specific ()
- separate buttons _Create generic_   and _Create  specific_ (most favorable according to  UI criteria)
-  or via Shift+Click on _Create_ btn  (would be hidden for users who are not aware of it = bad UI )

**Typical workflow:** I see annoyance on page, open element picker, tweak selector. I realize this selector is suitable to be generic because of its name or   I have seen that element on more pages before(typically family of sites running by one media agency with  different domains) and now  it started bothering me (for example ###cookie-bar, ###cookie-lista, ###cookie-achtung, ###cookie-attention in various languages ). So I copy it to clipboard ,immediately go to settings and  append it to my filters OR  save that filter and go to settings and stripe the ||current-domain.com prefix from that just created filter. It is repetetive task.

**Comment by gorhill** [comment] 2018-02-25 21:52
Marking as duplicate of #2035.

**Closed by gorhill** 2018-02-25 21:52 UTC
Labels: duplicate
