### ISSUE TITLE
Element picker & zapper does nothing on alluc.ee

### ISSUE THREAD

**Issue by camk16** [gorhill/uBlock#3533] opened 2018-02-21 06:10 UTC
Title.

alluc.ee

Nothing to screenshot; when I click on either the picker or zapper, literally nothing happens.

1. Go to alluc.ee
2. Try using picker/zapper
3. Nothing happens

Set to block pop-ups, cosmetics, and fonts on alluc.ee

I added a bunch of filters (all but the experimental and language ones) recently that were not enabled by default. I hadn't tried using the element tools on alluc.ee before adding them, so I can't say whether or not the additional filters have anything to do with the issue -- though, I can't imagine why they would.

![image](https://user-images.githubusercontent.com/30790283/36465601-1e9f057c-1693-11e8-8845-1e9d8d8b0d5a.png)

- OS/version: Win10 x64
- Browser/version: Chrome/63.0.3239.132 64bit
- uBlock Origin version: 1.15.2

No custom filters.

**Comment by gorhill** [comment] 2018-02-21 12:27
Did you disable cosmetic filtering for that site? Did you look at the logger as asked in CONTRIBUTING?

**Comment by uBlock-user** [comment] 2018-02-21 17:12
Add

```
alluc.ee##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)
alluc.ee##script:inject(abort-on-property-read.js, document.styleSheets)
```

and check if you can use picker/zapper again.

**Comment by gorhill** [comment] 2018-02-21 17:33
@uBlock-user I could not reproduce without these filters. Are you saying you can reproduce the issue? If so, please provide STR, I could not repro with the information provided by OP.

**Comment by uBlock-user** [comment] 2018-02-21 17:40
@gorhill That's because you don't have `piguiqproxy.com` blocked, do you ? I can only reproduce, if I block the aformentioned domain FYI.

I will post the STR anyway.

1) Add ||piguiqproxy.com^
2) Browse to `https://www.alluc.ee/`
3) The entire page will appear white as in broken, right click and click on Block Element, nothing will happen, now open the popup UI and click on the zapper icon and again nothing will happen.

**Comment by gorhill** [comment] 2018-02-21 17:56
Thanks. So marking as a filter issue -- the site sabotage itself when some stuff is blocked.

Form now on I will require that people test with default filter lists before opening a new issue -- there is no way I will spend time replicating everybody's huge amount if filter list selection.

Your suggested filter is the one fixing the fitlering issue:

    alluc.ee##script:inject(abort-on-property-read.js, document.styleSheets)

**Closed by gorhill** 2018-02-21 17:56 UTC
Labels: filter issue, invalid

**Comment by uBlock-user** [comment] 2018-02-21 18:07
`piguiqproxy.com` serves ads, hence the reason behind the blockage. Once the inline script detects connection to the aformentioned domain was not successful, it destroys the CSS.

**Comment by camk16** [comment] 2018-02-21 19:56
@gorhill hill Firstly, thanks for the quick reply!

Gorhill, to answer your question: I did disable cosmetic filtering on alluce.ee. As far as the logger goes, I didn't notice it in issue post outline -- sorry about that. Regardless, after looking at it, I can say that it goes well over my head. I'll post it here, though, for you:

![image](https://user-images.githubusercontent.com/30790283/36502233-8c9c68f8-1706-11e8-8a5a-cc81f900edd7.png)

**Comment by camk16** [comment] 2018-02-21 19:59
@uBlock-user Thanks for the reply!

Just so we're clear, in order to fix my issue I add

`alluc.ee##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)`

and

`alluc.ee##script:inject(abort-on-property-read.js, document.styleSheets)`

Here:

![image](https://user-images.githubusercontent.com/30790283/36502388-024dfd96-1707-11e8-9489-7710cc679f96.png)

& voila?

**Comment by gorhill** [comment] 2018-02-21 20:10
>  I did disable cosmetic filtering on alluce.ee

In that case that would be a duplicate of #3212.

**Comment by uBlock-user** [comment] 2018-02-21 20:36
@camk16 That would have fixed it if you were blocking `piguiqproxy.com` as explained in https://github.com/gorhill/uBlock/issues/3533#issuecomment-367408384 but in your case you had cosmetic filtering disabled, so it's no longer valid for you.
