### ISSUE TITLE
New tab created for Google analytics gif URLs

### ISSUE THREAD

**Issue by mspublic** [gorhill/uBlock#1158] opened 2016-01-01 18:29 UTC
I have noticed that on multiple sites when clicking on certain elements/buttons/etc UBlock will pop up a new tab indicating something was blocked such as: "uBlock Origin has prevented the following page from loading: http://www.google-analytics.com/__utm.gif".

I believe this behavior to be partially incorrect. The blocking aspect was proper but I do not believe UBlock should be opening new tabs for items like the above. A notification at the top of the window IF truly needed would more then suffice. Though in this case I do not believe a notification would even be needed (it should just be added to the uBlock icon number). The issue appears similar to: https://github.com/gorhill/uBlock/issues/744

Environment:
OSX 10.10.5
Chrome 47.0.2526.106 (64-bit)
uBlock Origin v1.5.2

Reproduction Steps:
1. Browse to  http://nitroflare.com/view/6BB34DF8692C454/How_to_Tell_a_File%27s_Format_Five_Open_Source_Tools.part1.rar
2. Click "Slow Download"
3. Close the "Purchase Premium" overlay.
4. Click "Free Download" - the uBlock pop up page should now occur.

Please let me know if I can provide any further information/assistance. Outside of this issue uBlock is amazing - thank you for all your hard work!

 
<img width="580" alt="ublock pop-up" src="https://cloud.githubusercontent.com/assets/1268608/12071774/6b5e906e-b072-11e5-90ee-d0812a695f18.png">

**Comment by gorhill** [comment] 2016-01-01 18:49
>  I do not believe UBlock should be opening new tabs for items like the above. 

uBlock does not open a new tab, the browser did, according to how the link you clicked is designed. Disable uBlock, click the same link, and a new tab will also open.

> A notification at the top of the window

Duplicate of #744.

**Closed by gorhill** 2016-01-01 18:49 UTC

**Comment by mspublic** [comment] 2016-01-01 19:15
Ah I see now. I apologize for creating the new issue. Thanks!

**Comment by carlis8** [comment] 2016-01-19 14:18
Is there any solution for this? I hate being opened that tab all the time

**Comment by harshanvn** [comment] 2016-01-19 14:24
i believe there are some settings in firefox (about:config), where you can configure. Try googling it!
And it is nothing related to uBlock.

**Comment by carlis8** [comment] 2016-01-19 14:32
But how cannot be related to uBlock if: 1- this only happens with uBlock (software I love, by the way) and 2 - The tab says "uBlock Origin has prevented the following page from loading: http://www.google-analytics.com/__utm.gif". ?

**Comment by gorhill** [comment] 2016-01-19 15:05
> this only happens with uBlock

Because other blockers do not prevent the page from loading?
- Other blocker: the tab opens and the content is loaded.
- uBO: the tab opens and the content is prevented from loading.

So just disable strict blocking permanently for your `http://www.google-analytics.com/__utm.gif` blocked page, and you will be able to say "this does not happens only with uBlock".

**Comment by carlis8** [comment] 2016-01-19 16:24
Ok. Then I just shut up and don't get any help. Nice attitude. Thanks and kind regards

**Comment by gorhill** [comment] 2016-01-19 16:28
I just explained to you what is happening -- and the solution -- disable strict blocking for `www.google-analytics.com` -- to get the same behavior as other blockers. I don't know what else to do.

**Comment by harshanvn** [comment] 2016-01-20 10:20
> Then I just shut up and don't get any help. Nice attitude.

Please be civilized.
There was already clear explanation/answer/solution above. 

> Because other blockers do not prevent the page from loading?
> 
>     Other blocker: the tab opens and the content is loaded.
>     uBO: the tab opens and the content is prevented from loading.
> 
> So just disable strict blocking permanently for your http://www.google-analytics.com/__utm.gif
