### ISSUE TITLE
assets/ublock/filters.txt: ##script:contains(uabInject) for spiegel.de etc. doesn't work (Safari OS X)

### ISSUE THREAD

**Issue by JayBrown** [gorhill/uBlock#999] opened 2015-12-01 12:51 UTC
The anti-anti-adblock measure ##script:contains(uabInject) for the domains spiegel.de etc. doesn't seem to work in Safari on OS X. Could the reason be the known problem that Safari can't act before a script loads? Any other way to block these ad images in Safari?

**Comment by JayBrown** [comment] 2015-12-01 13:00
Note: I tried subscribing directly to filters.txt with uBlock (not uBlock Origin), and alternatively manually added the respective blocks to "My Filters". Neither works.

**Comment by gorhill** [comment] 2015-12-01 13:05
I added inline script tag filtering to uBlock Origin after I stopped contributing to uBlock.

**Comment by harshanvn** [comment] 2015-12-01 13:07
These filters are part of a feature called  "inline tag filtering".  Not available in other uBlock.

**Comment by JayBrown** [comment] 2015-12-01 13:27
Thanks for the quick reply. Then there's only one question left: are you guys working on a Safari OS X version of uBlock Origin? ;)

**Comment by gorhill** [comment] 2015-12-01 13:39
I am not aware of anybody working to make uBO work on Safari. I do not have access to a Mac, and anyways, I would be stretching myself too thin if I were to maintain myself a Safari version. This will have to be contributed by a dedicated dev from OSX platform. Even then, [as per chrisaljoudi](https://github.com/chrisaljoudi/uBlock/issues/1544#issuecomment-150397875), there is no point maintaining his own Safari version because apparently the API used by uBlock is going to go away.

**Comment by gorhill** [comment] 2015-12-02 14:49
Closing as duplicate of #64.

**Closed by gorhill** 2015-12-02 14:49 UTC
