### ISSUE TITLE
ublock doesn't apply ABP flter

### ISSUE THREAD

**Issue by Flashwalker** [gorhill/uBlock#1337] opened 2016-02-03 08:52 UTC
I wana block these sources:

    https://d3ae0shxev0cb7.cloudfront.net/assets/videos/earth-1/earth-1.webm
    https://d3ae0shxev0cb7.cloudfront.net/assets/videos/earth-1/earth-1.mp4

I'd tryid:

    ||d3ae0shxev0cb7.cloudfront.net/assets/videos/earth-1/*$media,domain=minds.com
    ||*.cloudfront.net/assets/videos/earth-1/*$media,domain=minds.com
    ||d3ae0shxev0cb7.cloudfront.net/assets/videos/earth-1/*
    ||*.cloudfront.net/assets/videos/earth-1/*

And nothing happens.
But it works with ABP.
WAIDW?

**Comment by gwarser** [comment] 2016-02-03 09:42
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include

**Comment by gorhill** [comment] 2016-02-03 12:56
You did not provide all the information as asked in [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). So I will have to make assumptions.

> Always include a URL, even if "it happens everywhere".

- I will assume the URL of the page with the issue is <https://www.minds.com/>.

> Symptoms of the issue

You did not provide a description of what should happen on the page, want you are trying to accomplish. I will assume you want to prevent the big Earth globe movie from loading.

> The version of uBlock you're having the issue with.

I will assume 1.6.0rc0.

> The browser you're using and its version.

No information. I will assume you are using Firefox 44.0.

You say "works with ABP", but does not provide any version information. I will assume ABP 2.7.1.4134-beta (so I do not have to re-install another version).

Result: same issue with ABP, the video cannot be blocked.

Duplicate of #868.

**Closed by gorhill** 2016-02-03 12:56 UTC
