### ISSUE TITLE
Ublock Origin imposter in Chrome

### ISSUE THREAD

**Issue by ahnkle** [gorhill/uBlock#1476] opened 2016-03-15 09:10 UTC
There is an imposter extension in chrome extensions, called Ublock Origin but not this one.
I hasn't made it to firefox yet.

See https://chrome.google.com/webstore/detail/ublock-origin/ekofnfjhckfjgkdigmghbcbboegjbhja?hl=en-US

**Comment by gorhill** [comment] 2016-03-15 12:48
Duplicate of #1436.

**Closed by gorhill** 2016-03-15 12:48 UTC
