### ISSUE TITLE
Doesn't work with Pushbullet in Canary 49.0.2623.0

### ISSUE THREAD

**Issue by riesza** [gorhill/uBlock#1252] opened 2016-01-18 14:54 UTC
This has been happening for a few days now and it took me a while to narrow it down but it seems that sites don't load at all if Pushbullet and uBO are active at the same time. I get a "waiting for extension uBlock Origin..." in the bottom left whenever I try to open a page and trying to access the options through the extension menu (the button in the top right corner doesn't work at all) leads to this:  ![lmhrox 1](https://cloud.githubusercontent.com/assets/1399263/12393565/ca8c0cba-bdf6-11e5-8f88-e1ff528436b7.png)

I set up Chromium after this and it works fine with both enabled. It didn't occur to me that PB might be the problem so I thought it was just uBO. Anyway I'm not sure how to troubleshoot the cause any further.

**Comment by riesza** [comment] 2016-01-18 15:01
Or maybe it's not related to PB at all, it just stopped working again even with it disabled. This could just be a Canary problem for all I know but I really don't know how to troubleshoot this.

**Comment by gorhill** [comment] 2016-01-18 15:06
I do not understand the report. Make a very detail step-by-step of what is wrong. See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) -- marking as _invalid_ until a better detailed issue is provided. Also, always check "Collect errors" if you do not know how to access an extension's dev console and report errors in it.

**Comment by gorhill** [comment] 2016-01-18 15:11
I tested uBO 1.5.6 with Google Chrome 49.0.2618.8 dev (64-bit) and all is fine.

**Comment by riesza** [comment] 2016-01-18 15:46
Sorry about that. How do I access the error collection logs? 

This whole thing seems incredibly inconsistent but right now it seems to be centered around Pushbullet, RedditEnhancementSuite, Fauxbar Lite + Fauxbar Memory Helper and Tampermonkey. Other than those I have everything else turned off right now. Turning them on and off in different combinations causes it to happen sometimes but not consistently.
Resetting uBO 1.5.6 completely didn't help. Regardless of what other extension seems to cause this incompatibility, turning off uBO will **always** fix it.

Here's an example:
1. uBO on, everything off it works fine.
2. Restart, turn on Tampermonkey, everything fine.
3. Turn on RES, restart, everything fine.
4. Turn on PB, restart, it's broken
5. Turn off PB, restart, still broken.
6. Restart without turning off anything else, it works.
7. Turn on PB, restart, it works.
8. Turn on Fauxbar and the memory helper, restart, it's broken.
9. Turn off Fauxbar again, everything works.
10. Turn it on again, restart, it's broken.
11. Turn it off again, restart, still broken
12. Disable uBO without restarting and the [site](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) loads immediately

Overall I have no clue what to make of it because it's so random but what it has in common is that it always works as soon as I disable uBO.

**Comment by gorhill** [comment] 2016-01-18 15:49
> How do I access the error collection logs?

In the screenshot you posted above, there is a "Collect errors" checkbox. Check it. Then if errors are reported when the issue occur, report these errors here.

**Comment by riesza** [comment] 2016-01-18 15:51
Oh, I had it checked all the while I did that test run and nothing popped up.

**Comment by gorhill** [comment] 2016-01-18 15:52
Try the same with other extensions, probably Pushbullet first.

**Comment by riesza** [comment] 2016-01-18 16:07
Tampemonkey showed this http://pastebin.com/qnHkqYi0
Pushbullet showed http://pastebin.com/9EVVfemx

Not sure if I copied those correctly or if they're of any help to you.

After collecting those I restarted and it worked again. Then I turned off both Fauxbars, restarted and it broke. Restarting again did nothing but turning off uBO afterwards fixed it immediately.

**Comment by riesza** [comment] 2016-01-18 16:16
Just did the following thing three times: I turned on all the extensions and restarted the browser 5-6 times until it worked. Then on the next restart or the one after it stops working again.

**Comment by gorhill** [comment] 2016-01-18 16:25
> Tampemonkey showed ...

There is nothing I can do with this, the type of error and the line at which the error occurred is the most important information, you did not provide it.

**Comment by riesza** [comment] 2016-01-18 16:33
[This](http://pastebin.com/GLDLS7gX) any better?

**Comment by gorhill** [comment] 2016-01-18 16:36
Not really. A screenshot of the reported errors would be much better.

**Comment by riesza** [comment] 2016-01-18 16:41
https://my.mixtape.moe/zizqzk.png
https://my.mixtape.moe/fcnlsx.png
https://my.mixtape.moe/shdmss.png
https://my.mixtape.moe/auzjbu.png
https://my.mixtape.moe/wabkkc.png

Can't seem to make the popup bigger but the errors are in full in the last pastebin in the same order.

**Comment by gorhill** [comment] 2016-01-18 16:48
This is all Tampermonkey errors. So disable Tampermonkey and see if the issue persist -- as said, I deal only with uBO's own issues, not that of other extensions.

**Comment by riesza** [comment] 2016-01-18 17:06
I just got it to break with just uBO and uMatrix on and [recorded it](https://my.mixtape.moe/lsghfx.webm). Shortly after that it also broke the same way with just uBO on at browser start.

**Comment by gorhill** [comment] 2016-01-18 17:27
Ok. All this started with 49.0.2623.0?

**Comment by riesza** [comment] 2016-01-18 17:31
Yup.

**Comment by gorhill** [comment] 2016-01-18 21:08
Ok new rule, I just do not have the time to address issues in dev builds of Chrome/Firefox. So if an issue only occurs in these builds, and not on stable or beta, an issue should not be opened. I update [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). If you can't reproduce the issue here on Chrome stable or beta, please close the issue.

**Closed** 2016-01-18 21:15 UTC
Labels: invalid, unable to reproduce
