### ISSUE TITLE
[Request] Make rule wizard more accessible

### ISSUE THREAD

**Issue by rayman89** [gorhill/uBlock#521] opened 2015-07-23 00:57 UTC
I noticed there is a way to create rules easier using the logger ui but is not intuitive at all how you get to there. I would like to request to make it more intuitive to get to it for example on the UI calling it something like block wizard or keeping the name but having a title like blocking tools and then under that have the picker and the logger then naming the columns of the logger and or do something to let the user know that if you click on that field you will be able to open the wizard and create a rule easier. Also would be nice that the logger auto selects the page you were on while you open it and to load the page separately so that you are not forced to reload to be able to see  the stuff on the logger as it can make you need to re buffer or rewrite stuff also the reload button could be called something like start login or something to let the user know it has to be pressed else they'll be staring at a blank log or maybe if you implement the reload separately to make it automatic when the logger is loaded or when the page is selected from the dropdown menu.

Thanks for you time.

**Comment by gorhill** [comment] 2015-07-23 05:03
> something like [...] or do something [...] called something like [...] or something [...] or maybe [...] or when

Sorry but I prefer to deal with very specific issues which I can reproduce, not re-design ideas, let alone vague re-design ideas.

> would be nice that the logger auto selects the page you were on while you open it

Duplicate of #507.

**Closed by gorhill** 2015-07-23 05:03 UTC

**Comment by rayman89** [comment] 2015-07-23 07:23
First this request was made so that the add-on could be more useful for inexperienced users. I already know how to use this tool. It's on you if you wanna better the add-on in case you consider this a change for good or if you prefer to not do it cause you wanna use your free time on other things.

That aside the request is clear: Make the tool and it's location clear for the user. Takes less time to do a comprehensive read of the text than to be quoting parts of to express the idea "tl;dr"

The rest are suggestions that you may or may not take were said mainly to explain myself more specifically of what things were not clear on the current UI.

 If you are interested and want them on a list clear and easy to read for you comfort let me know.
