### ISSUE TITLE
indian sites blocking ad blocking extension

### ISSUE THREAD

**Issue by ghajini** [gorhill/uBlock#1836] opened 2016-07-25 15:05 UTC
### Describe the issue
websites said to block disable adblocking extension

### One or more specific URLs where the issue occurs
http://www.mid-day.com/articles/2-killed-in-florida-nightclub-shooting/17464173
http://www.businesstoday.in/current/deals/verizon-buys-yahoo-for-usd-4.83-billion-on-monday/story/235392.html
http://www.bhaskar.com/news-ht/INT-florida-nightclub-shooting-news-hindi-5380727-NOR.html

### Steps for anyone to reproduce the issue

1. go to mid-day.com or businesstoday.in or bhaskar.com
1. click any news
1. will say to block adblock
tried https://github.com/reek/anti-adblock-killer steps but not worked
### Your settings

- Browser/version: chrome Version 52.0.2743.82 m (64-bit)

- uBlock Origin version: 1.7.6

##### Your filter lists
default filter lists + youtube pure video experience

##### Your custom filters (if any)
tried https://github.com/reek/anti-adblock-killer steps but not worked

**Comment by gorhill** [comment] 2016-07-25 15:08
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-07-25 15:08 UTC

**Comment by ghajini** [comment] 2016-07-25 15:09
why invalid

**Comment by ghajini** [comment] 2016-07-25 15:12
ohh robotic man ,what invalid in this ........

**Comment by kcschan** [comment] 2016-07-26 01:33
It seems you did not read the guidiance at:
https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
where it says:

For filter-related issues, report on the respective filter list support
site, or at uBlockOrigin/uAssets
<https://github.com/uBlockOrigin/uAssets/issues>.
Submit bugs/issues only.
Verify that the issue is not related to a 3rd-party filter lists.

   - Issues with 3rd-party filter lists are the responsibility of their
   respective maintainers.



ghajini <notifications@github.com>于2016年7月25日周一 下午11:12写道：
