### ISSUE TITLE
pgl.yoyo.org is blacklisted as an active Dridex trojan horse command & control server

### ISSUE THREAD

**Issue by tiguchi** [gorhill/uBlock#2128] opened 2016-11-05 16:03 UTC
## Problem
One of the ad server sources of uBlock Origin is the following URL:
https://pgl.yoyo.org/adservers/serverlist.php

The host name pgl.yoyo.org resolves to the IP address 213.230.210.230, which in turn appears 
blacklisted by the Feodo tracker project over at abuse.ch as an **active trojan command and control server**: https://feodotracker.abuse.ch/host/213.230.210.230/

## Background
My router has an "intrusion prevention" service that alerts me every time uBlock tries to download from that server.

First of all I was thinking that may be a false positive since criminals have repackaged uBlock with malware in the past, and put it out in the wild. I assumed that a bad version of uBlock got some download servers blacklisted as well (as "phone home" servers).

I sent an email to abuse.ch about my assumption that the blacklisting of that server may be a false positive.
I got the following response from the head of abuse.ch, security researcher Roman Hüssy:

> I've investigated your report and confirm that the said IP address is an
> active Dridex botnet command&control server (C&C). This is *not* an FP.

So I guess that's bad news. That server should be considered as compromised. I don't think it's safe to download and use whatever data it returns.

**Comment by seanrand** [comment] 2016-11-05 16:24
#2125
I think at this point, the course of action would be to notify the abuse/webmaster contact in charge of that IP.

**Comment by tiguchi** [comment] 2016-11-05 16:42
I just sent an email to the operator, explaining the situation. I'll report back when I get a response from him.

**Comment by gorhill** [comment] 2016-11-05 17:16
Duplicate of #2125.

**Closed by gorhill** 2016-11-05 17:16 UTC

**Comment by tiguchi** [comment] 2016-11-05 18:48
The operator Peter Lowe told me that he's looking into it
