### ISSUE TITLE
 Facebook links preview doesn't work (only in business page)

### ISSUE THREAD

**Issue by shaygover** [gorhill/uBlock#2047] opened 2016-10-05 03:09 UTC
Read first: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
### Describe the issue

Facebook links preview doesn't work (only in business page).
Facebook is already present in my whitelist. 
### One or more specific URLs where the issue occurs

www.facebook.com
### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
### Steps for anyone to reproduce the issue

Paste or drop links in status box. No preview.
### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]
- Browser/version: chromium 53.0.2785.143 (64-bit)
- uBlock Origin version:  v1.9.10
##### Your filter lists

ISR: EasyList Hebrew‎
MVPS HOSTS
 uBlock filters‎ : 978 used out of 979purge cache
 uBlock filters – Badware risks‎  (github.com): 7 used out of 7
 uBlock filters – Experimental‎  (github.com): 0 used out of ?
 uBlock filters – Privacy‎ : 50 used out of 50
 uBlock filters – Unbreak‎ : 113 used out of 115purge cache
 Adblock Warning Removal List‎ (forums.lanik.us): 243 used out of 256purge cache
 Anti-Adblock Killer | Reek‎  (github.com): 1,966 used out of 2,009purge cache
 EasyList‎ (forums.lanik.us): 67,777 used out of 67,898purge cache
 Peter Lowe’s Ad server list‎ (pgl.yoyo.org): 1,834 used out of 2,365purge cache
 Malvertising filter list by Disconnect‎ : 391 used out of 5,667purge cache
 Malware Domain List‎ (malwaredomainlist.com): 1,250 used out of 1,251purge cache
 Malware domains‎ (www.malwaredomains.com): 14,503 used out of 14,557purge cache
 Malware domains (long-lived)‎ (www.malwaredomains.com): 2,412 used out of 3,206httppurge cache
 Malware filter list by Disconnect‎ : 139 used out of 2,931purge cache
 Spam404‎ (www.spam404.com): 5,595 used out of 5,617purge cache
EasyPrivacy‎ (forums.lanik.us):

**Comment by shaygover** [comment] 2016-10-05 03:16
Update: When I add my business page to the whitelist preview works as expected.

I think we have a whitelist problem...

**Comment by gorhill** [comment] 2016-10-05 09:32
> Facebook links preview doesn't work (only in business page).

What is "Facebook links preview"? What is "business page"?

**Comment by shaygover** [comment] 2016-10-05 15:08
Link preview: https://cdn.tutsplus.com/wp/uploads/legacy/219_Share_Your_Posts_on_Facebook_With_a_Preview_Image_and_a_Description/final-result.jpg

Business page:
https://www.facebook.com/kapotamar.it.news/

**Comment by gorhill** [comment] 2016-10-05 15:16
> Link preview: https://cdn.tutsplus.com/wp/uploads/legacy/219_Share_Your_Posts_on_Facebook_With_a_Preview_Image_and_a_Description/final-result.jpg

That is an image. What is the origin?

**Comment by gorhill** [comment] 2016-10-05 15:17
More to the point, what are the steps-to-reproduce. You gave me none.

**Comment by shaygover** [comment] 2016-10-05 16:54
Ah. 
Just try to post a new link on a facebook business page. You should see a preview but you won't

**Comment by gorhill** [comment] 2016-10-05 19:11
I need specifics steps (see [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#submitting-issues)), I am really not sure what I need to do at this point (and not even sure to understand what the issue is), and I do not want to guess anything, just very precise detailed steps of what I need to do, with a description of the expected result vs. current result.

1. ...
2. ...
3. ...
4. etc.

**Comment by shaygover** [comment] 2016-10-05 21:30
> Also, keep in mind I am not a Facebook user, so I wouldn't know exactly how to "post a new link on a facebook business page".

That basically means you'll have no idea what I write.

So let us try a different approach:
If  I add a site named www.example.com to the whitelist, does it include www.example.com/page1/?
Because it appears it doesn't.

**Comment by gorhill** [comment] 2016-10-05 21:54
> If I add a site named www.example.com to the whitelist, does it include www.example.com/page1/?

Yes. What does the logger report in your case? It reports everything uBO is doing and why it is doing it.

**Comment by shaygover** [comment] 2016-10-05 21:57
Something there I should look for?

**Comment by gorhill** [comment] 2016-10-05 22:13
If the site is whitelisted, then nothing should be reported as blocked for that site.

**Comment by shaygover** [comment] 2016-10-05 23:16
How does a blocked row looks like?

**Comment by Atavic** [comment] 2016-10-06 17:39
@shaygover When I click on _https://www.facebook.com/kapotamar.it.news/_ I see the latest link you posted there. Specifically, I see an image from _opensource.com_.

But the image isn't loaded directly from that external site, but from:

`https://external-mxp1-1.xx.fbcdn.net/safe_image.php`

**Comment by shaygover** [comment] 2016-10-07 11:29
Amp. That doesn't explain why I have no problem when https://www.facebook.com/kapotamar.it.news/ is in my whitelist.

**Comment by uBlock-user** [comment] 2016-10-09 06:52
You put domain name in the whitelist and not anything else. 

Example  - facebook.com
                  fbcdn.net

OR

If you want to add a whitelist Filter - @@||facebook.com^
                                                           @@||fbcdn.net^

**Comment by gorhill** [comment] 2016-11-08 13:04
Closing due to lack of attention. This probably would have helped:

> [Screenshot(s) for visual issues are mandatory]

**Closed by gorhill** 2016-11-08 13:04 UTC
