### ISSUE TITLE
Move pseudo-user stylesheets out of `contentscript.js`

### ISSUE THREAD

**Issue by gorhill** [gorhill/uBlock#2984] opened 2017-09-06 11:02 UTC
Firefox webext and legacy supports real user stylesheets, so these versions should not suffer whatever overhead incurred by _any_ of the code necessary for pseudo-user stylesheets required for browsers which do not support real user stylesheets (Chromium, Edge, Safari).

**Comment by gorhill** [comment] 2017-09-22 17:00
As of writing, with default filter lists:

- Low generic filters (class- or id-based): 18,175
- High generic filters (everything else): 427
- Ratio of high generic filter / all generic filters = 2.3%. This is typical.

For instance, even with Fanboy Annoyance:

- Low generic filters (class- or id-based): 29,382
- High generic filters (everything else): 885
- Ratio of high generic filter / all generic filters = 2.9%.

Given this, I will no longer make uBO distinguish between flavors of high generic filters, they will be all treated by the same code path. This will simplify to fix required here, which I want to get out before Firefox 57 stable is released.

**Comment by gwarser** [comment] 2017-10-22 13:06
`www.wp.pl###home-page-button, #newsfeed-player-column`

from https://raw.githubusercontent.com/azet12/PopupBlocker/master/PPB.txt 

is reported as `www.wp.pl##home-page-button, #newsfeed-player-column` - (missing `#`)
in logger. Can be tested here https://www.wp.pl/ (for the time being - is invalid here)

**Comment by gwarser** [comment] 2017-10-22 13:27
Here https://www.wp.pl/ when scrolling on 1.14.16 I see ads collapsing. On https://github.com/gorhill/uBlock/commit/6112a68faf46d89c58defdd9e14d4342747c9523 I see them loading.

Default filters + POL

![image](https://user-images.githubusercontent.com/886325/31862375-379a9808-b73d-11e7-9b22-9d2b811ee9f8.png)

**Comment by gorhill** [comment] 2017-10-22 14:51
Do you know which specific filter is supposed to be at work there?

**Comment by gwarser** [comment] 2017-10-22 15:24
I think:

```
www.wp.pl##SECTION#section_celebrities > DIV[class]:first-child www.wp.pl##SECTION#section_mototech > DIV[class]:first-child www.wp.pl##SECTION#section_sport > DIV[class]:first-child www.wp.pl##SECTION#section_finances > DIV[class]:first-child www.wp.pl##SECTION#section_lifestyle > DIV[class]:first-child
```

**Comment by kasper93** [comment] 2017-10-22 15:38
I can reproduce, with some of the ads on this page. For me ads flickers, basically they are hidden, after some delay they are shown again and hidden again after delay. Easily viable when scrolling.

**Comment by gorhill** [comment] 2017-10-22 15:41
> `www.wp.pl##SECTION#section_celebrities > DIV[class]:first-child`

Those filters assume the ads will be in the first `div` child. I see differently on my side. I suspect the site has javascript which shuffles the ads to a different position is they are not visible. If I removed `:first-child`, the specific ad in your pic is properly hidden, no flickering (because the site attempt to shuffle them to a different position does not work).

**Comment by gorhill** [comment] 2017-10-22 15:52
Ok I think I understand what is going on. The POL maintainer(s) created this filter:

    www.wp.pl##SECTION[class^="_3"] > DIV[hidden] + DIV[class]

Of course, the web site does not create the `hidden` attribute on their element, this was something added by uBO pre-1.14.16. uBO post 1.14.16 no longer uses the `hidden` internally, as there is no point to do so with real user stylesheet. So the filter depends completely on how a specific uBO implementation which was never designed to be used by filter list maintainers. They need to fix their filters to stop depending on the `hidden` attribute unless it is added by the site itself.

**Comment by gwarser** [comment] 2017-10-22 17:05
>They need to fix their filters to stop depending on the hidden attribute

Reported https://github.com/MajkiIT/polish-ads-filter/issues/4080

**Comment by kasper93** [comment] 2017-10-22 19:24
@gorhill Filter issue is fixed in upstream. wp.pl is one of the biggest polish website (top 7 according to Alexa). Would you please take a look at performance on this site? They update DOM heavily on scroll. The side bar is updated. I too two profiles:

https://perfht.ml/2xXzWdZ 1.14.16
forEachNode takes 240-300ms

https://perfht.ml/2xYevsZ noroundtrip (e1acf6d8)
domFilterer.prototype.commitNow takes around 1,103ms, I got 2.5 seconds per call once, I think without noroundtrip patch.

To make this profile:
1. Go to the site, wait till everything loads.
2. Scroll the page, not so fast to let the right sidebar keep up with loading.

My configuration is the same as we discussed in the other topic. 

Let me know if you need more info. I think this is great page to benchmark, because it has a lot of advertisements, a lot of dynamic content and is one of the top websites in Poland. So a lot of people (uBO users) hit this page everyday.

**Comment by gorhill** [comment] 2017-10-22 19:42
> https://perfht.ml/2xYevsZ noroundtrip (e1acf6d)
domFilterer.prototype.commitNow takes around 1,103ms, I got 2.5 seconds per call once, I think without noroundtrip patch.

It's the `matches-css` filter. I didn't touch procedural selectors, so you should get same performance issue. To implement `matches-css`, uBO needs to call `getComputedStyle`, and it seems this is what is causing the issue. I see servo in the profile data, maybe worth to try without servo.

**Comment by gorhill** [comment] 2017-10-22 19:44
Just to add, specifically I see a `matches-css` with the `width` property. It is known that querying for the computed `width` will cause the browser to for a recalculation of the layout. This is expensive.

**Comment by kasper93** [comment] 2017-10-22 19:53
Indeed it spends time in PSelectorMatchesCSSTask.prototype.exec in both profiles. Could it be that injecting user css causes `matches-css` to be more expensive? You can see profile with 1.14.16 it is a lot faster. 

I will ask list maintainers to try remove `matches-css` filter if possible.

**Comment by gorhill** [comment] 2017-10-22 20:01
I don't see the profile in 1.14.16 to be a lot faster. Processing `matches-css` requires almost 20s in 1.14.16, and 30s in 1.14.17. They are both very expensive, I suspect the difference is merely down to luck: force-recalculation of the layout maybe fall at the best or worst time for the rendering engine, I suspect you would get quite varying results from one profile to another. On my side I got 6s and 10s with/without servo (can't remember which one is which).

There is no way uBO's injected styles are involved, the site's own CSS is quite certainly magnitude larger than what uBO adds. The site itself contributes to its demise by shuffling around DOM elements while the page loads, this probably contributes to the whole issue of `matches-css` being expensive.

**Comment by kasper93** [comment] 2017-10-22 20:03
Thanks for your time. I will resolve this with list maintainers as there is clearly a improvement to be done in filters.

**Comment by gorhill** [comment] 2017-10-22 20:13
I tried to create an exception filter for that `matches-css` filter to see the difference but it's not working. I still have much code review to do following the refactor.

**Comment by gorhill** [comment] 2017-10-22 20:21
So I fixed my exception filter issue, and yes, removing the `matches-css(width: ...)` filter makes a huge difference. The other `matches-css(max-width: ...)` is not nearly as bad -- as I don't think `max-width` force a layout recalculation. There is doc somewhere on the net about which style properties causes layout recalculation.

**Comment by gorhill** [comment] 2017-10-22 20:41
As part of the refactoring I will add code to stop processing the procedural filters which are too expensive.

**Comment by gorhill** [comment] 2017-10-23 11:24
@gwarser I see the site `wp.pl` is using a web worker, I am wondering if they are using this to bypass blockers (see behind-the-scene requests in logger). A filter such as `||wp.pl^$csp=worker-src 'none'` stops the web worker, but I can't tell if this breaks anything. This won't work on Firefox though.

**Comment by gwarser** [comment] 2017-10-23 12:47
I don't think they need workers. They "encrypt" all links server-side, so all looks the same (base64 encoded random(?) bits).
They use worker for web notifications.

**Closed** 2017-10-23 17:14 UTC
