### ISSUE TITLE
Whitelisting filter issue

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#2528] opened 2017-04-11 17:42 UTC
### Describe the issue

A whitelisting filter for `websocket` connections on `speedtest.net` is not applied.

### One or more specific URLs where the issue occurs

http://www.speedtest.net/  OR http://beta.speedtest.net/

### Screenshot in which the issue can be seen

![](https://i.gyazo.com/37daf19759381e2af0d75d34187166bc.png)

![](https://i.gyazo.com/5b56f0010716d14d3b9e418cfb305ee3.png)

### Steps for anyone to reproduce the issue

- Open `My Filters` and add the following filters - `||$websocket` and `@@/ws$websocket,domain=speedtest.net`

- Run the logger tab and browse to `speedtest.net` or `beta.speedtest.net`

- It will get stuck at `Finding Optimal Server....` because all websocket connections are being blocked by `||$websocket` even though a whitelisting filter such as `@@/ws$websocket,domain=speedtest.net` is present.

### Your settings

- OS/version: Windows 10 Pro x64
- Browser/version: Chromium 57
- uBlock Origin version: 1.12.0

##### Your filter lists

Default

##### Your custom filters (if any)

mentioned above

**Comment by gorhill** [comment] 2017-04-11 17:49
By design.

The purpose of `*$websocket` is to inject a content security policy which blanket-block all websocket connection attempts, to ensure that no site can work around the fact that the webRequest API does not relay websocket connection attempts to webRequest listeners.

**Comment by rjkpa** [comment] 2017-04-11 17:52
So we are not supposed to be using `@@/ws$websocket,domain=speedtest.net` filter ?

**Comment by rjkpa** [comment] 2017-04-11 17:54
> no site can work around the fact that the webRequest API does not relay websocket connection attempts to webRequest listeners.

But why does this happen in Chromium 59 too ? It no longer suffers from that bug.

**Comment by gorhill** [comment] 2017-04-11 18:13
If you do not want the blanket-block of websocket connections, use `@@*$websocket,domain=speedtest.net`.

**Comment by gorhill** [comment] 2017-04-11 19:06
> But why does this happen in Chromium 59 too ? It no longer suffers from that bug.

The current behavior will stay, otherwise sites will use shared workers to bypass the blocking of websocket connections.

**Comment by rjkpa** [comment] 2017-04-11 19:24
> otherwise sites will use shared workers to bypass the blocking of websocket connections.

Ah, so that's why you're keeping the strict behavior of CSP policy rather than relaxing a bit, thanks now I understand.

**Comment by gorhill** [comment] 2017-04-11 22:40
On the other hand shared workers can just as well use xhr to pull data, so there doesn't seem to be much of a point in preventing them from using websocket connections. The real solution is to prevent shared workers in the first place when they are an issue. I need to look into all this more thoroughly.

**Comment by uBlock-user** [comment] 2017-04-12 07:50
By shared workers you mean the ones created via `|blob:` URIs ?

**Comment by gorhill** [comment] 2017-05-26 17:08
I can't reproduce the issue on my side with Chrome 60. Can you validate on your side that it is fixed with 1.12.5b_?

**Comment by rjkpa** [comment] 2017-06-30 07:11
Yeah I can no longer reproduce it with Chrome 61, so was it a Chromium bug ?

**Closed** 2017-06-30 07:12 UTC
