### ISSUE TITLE
Ads @ tweaktown.com

### ISSUE THREAD

**Issue by tauxeta** [gorhill/uBlock#1495] opened 2016-03-21 22:36 UTC
I'm seeing ads on tweaktown.com in both Chrome  and Firefox with identical filter lists (No custom filters) 

Browser/version: Chrome 49 - firefox 45
uBlock Origin version: v1.6.4
Manjaro 15.12 (x64)

http://www.tweaktown.com/
http://www.tweaktown.com/news/51179/microsoft-working-total-update-file-explorer/index.html

ads in Chrome, front page and an article:
https://i.imgur.com/haFp0vw.png
https://i.imgur.com/bICB6te.png
https://i.imgur.com/jpAPhek.png
https://i.imgur.com/fcUDP9J.png

ads in Firefox, front page and an article:
https://i.imgur.com/OqFeiDq.png
https://i.imgur.com/EjndW0m.png
https://i.imgur.com/3CqPD0E.png
https://i.imgur.com/EeAXKVE.png

uBlock Origin dashboard:

3rd-party-filters:
https://i.imgur.com/NdsEvg6.png
https://i.imgur.com/CGopa9R.png

Settings:
https://i.imgur.com/XzMzA7m.png

My filters:
https://i.imgur.com/GnRVJNE.png

My rules:
https://i.imgur.com/YnRuHWZ.png

Whitelist:
https://i.imgur.com/9SgGsVS.png

About:
https://i.imgur.com/CElZWBM.png

**Comment by gorhill** [comment] 2016-03-21 23:05
Did you submit the issue to EasyList?

**Comment by tauxeta** [comment] 2016-03-21 23:11
No, i had no idea that I've to submit this issue to Easylist, now that you mention it i will though.

**Comment by tauxeta** [comment] 2016-03-21 23:25
It seems that There are already many reports/threads for the specific website on EasyList forums
https://forums.lanik.us/viewtopic.php?f=62&t=29249
https://forums.lanik.us/viewtopic.php?f=62&t=29135&p=89015&hilit=tweaktown.com
https://forums.lanik.us/viewtopic.php?f=62&t=28589&hilit=tweaktown.com#p86958

**Comment by gorhill** [comment] 2016-03-21 23:28
The [filters suggested by @smed79](https://forums.lanik.us/viewtopic.php?f=62&t=28589#p86967) works for me -- I don't know why they were not included in EasyList. Might be worth reviving the thread.

**Comment by gorhill** [comment] 2016-03-21 23:38
Actually I realize those filters do not work with ABP, so this might be why they were not included in EasyList -- I don't think they will want to add them if they do not work with ABP. Given this, I will find what works best for uBO, it could be different than these filters.

**Comment by tauxeta** [comment] 2016-03-22 00:08
As you said the filters from smed79 work fine on uBO, at least for the moment and till you find a more permanent solution, 
Thanks for your (precious) time to investigate the issue

**Comment by gorhill** [comment] 2016-05-03 15:54
I tried to reproduce just now and I do not see the ads as reported in your opening comment. Can you confirm this is fixed on your side? (possibly by an EasyList filter since then)

**Comment by tauxeta** [comment] 2016-05-09 06:57
Indeed, I don't see ads now, tried in Firefox and Chrome (same settings) and i can confirm that i don't see any ads now.

**Comment by tauxeta** [comment] 2016-05-09 06:59
Indeed, Tried the same pages with Firefox & Chrome (Same settings) and i can confirm that i don't see any ads now.

**Comment by gorhill** [comment] 2016-05-09 13:02
What happened to that thread on EasyList forum? I can't see anymore the filters which were talked about above.

**Comment by gorhill** [comment] 2016-05-09 13:05
Never mind, looks like [filters were added for tweaktown.com](https://hg.adblockplus.org/easylist/rev/b7de728abb43).

**Closed by gorhill** 2016-05-09 13:05 UTC
Labels: filter list issue
