### ISSUE TITLE
Show Global and Local over columns under Request blocked

### ISSUE THREAD

**Issue by gitressa** [gorhill/uBlock#3320] opened 2017-12-05 13:48 UTC
Thanks for a great add-on. Is it possible to show "Global" and "Local" above the two columns under "Request blocked"? Or perhaps show the mouse-over text ("Global rules: this column ...") hovering over any row, not just the top row? (the one after "+all")

![ublock-gui-2](https://user-images.githubusercontent.com/3491208/33610078-a70d0ff4-d9ca-11e7-9130-c95c4c34e467.png)

**Comment by gorhill** [comment] 2017-12-05 14:07
Duplicate of #840.

**Closed by gorhill** 2017-12-05 14:07 UTC
Labels: duplicate

**Comment by uBlock-user** [comment] 2017-12-05 16:14
Just hover your mouse over both the columns and the tool tips will appear, which is enough to realise which is which.

**Comment by gitressa** [comment] 2017-12-05 16:56
Thanks @uBlock-user, but I already know that. Also, tooltip is only in the top row, next to `+ all`. 

Here are my thoughts on @gorhill's points in #840:
- Space is precious in the dynamic filtering panel, I rather use it for something else than labels.
  - No extra space would be taken with my suggestion.
- Once you read the quick guide, remembering what is global/local should not be an issue. If it is for someone, then I argue that "advanced mode" is not suitable for that user.
  - I am not sure by what logic ... I suppose the order is supposed to be memorized?
- If I were to add the header, I suspect the layout would become an issue for some languages (too long strings).
  - Or just make it untranslatable? (Supposing that's an option)
- What @zummuz said: the local column can be easily distinguished by the +/-, so the headers would be redundant information, using precious limited space.
  - Again, I am not sure by what logic.
- If you take the time to use dynamic filtering after the required reading, you will observe that a global rule "bleed" into the local one, while the reverse is not true. This makes it unambiguous as to which one is global and local.
  - Again, I am not sure by what logic.
- There are also tooltips in top cells.
  - Yes, and that's great! How about at least adding it to all rows?

I now see that other users have suggested something similar. It's sad to see these suggestions keep getting rejected... We only suggest it to improve uBlock Origin, not only for ourselves, but also for future users.

**Comment by gorhill** [comment] 2017-12-05 17:10
> Again, I am not sure by what logic

How is that even an argument against the _specific_ arguments you are answering to? If there is no better counter than this, I take as meaning the ones I made can't be argued against.

In any case, for me this has been all argued, and the decision still stand, so I will remove myself from receiving notification from this thread.

**Comment by gitressa** [comment] 2017-12-05 17:38
I read the quick guide, but I still don't remember which is which. I mean, I do right now, but maybe not tomorrow. How +/- should help separate Global/Local I don't see, and the Global bleeding into Local I don't get.

But nevermind, it seems like you have made up your mind about this, and anyway, I am still thankful you maintain the add-on, so thanks for that.

**Comment by uBlock-user** [comment] 2017-12-05 17:54
> tooltip is only in the top row

Yeah which is good enough as you will only need to know which is which once or twice at most. By the time you're a regular user, you should be able to remember on your own if you don't, just keep the tooltip on and hover over `+all` once and you're good to go.

**Comment by zummuz** [comment] 2017-12-06 12:09
> How +/- should help separate Global/Local I don't see

`+/-` signs are placed only in one column, therefore we can make a conclusion: that it shows requests of the current (local) site - because it's useful info, not all (global) sites - because it would not be clear what kind of requests are shown by `+/-`  (accumulated for this session, all the requests since uBO installation?), and what to do with this info. If one `+/-` sign means a digit in the number of requests, how would global requests look for some google-analytics, like `----------------------------------------------`?
Also, if you change the left column - the right one will inherit the change, it makes it obvious that the left one is for global rules. It takes half a second to do this test if you are going to make some changes, but forgot what's where.
Also, user doesn't need to remember all, user just needs to know where to get the info (the top row says what column it is).
Also, turning the dynamic filtering on requires reading, if you can't figure out how the popup interface works you need to read wiki before using it, and the whole wiki cannot be put in the popup interface, let alone in one cell.
>Or perhaps show the mouse-over text ("Global rules: this column ...") hovering over any row, not just the top row? (the one after "+all")

The popup hint hides 3 rows of domain names and the left column. It could always appear at the same place on top, but still it would be irritating, for example:
a user doesn't disable tooltips because he wants to see the names of the buttons to properly address it in some discussions/conversations (the exact sentence of the name is harder to recall, than the purpose), and dynamic filtering is frequently accessed by that "hard mode" user. I can see how the user could be annoyed by the flashing layout (it's like an ad in the uBO interface lol)
