### ISSUE TITLE
The popup in Firefox overflow menu is too wide

### ISSUE THREAD

**Issue by MikkCZ** [gorhill/uBlock#3163] opened 2017-10-23 11:00 UTC
### Describe the issue
When uBO item is in the Firefox overflow menu, the popup is too wide and has a lot of blank space on the right.

### Screenshot in which the issue can be seen
![snimek z 2017-10-23 12-56-32](https://user-images.githubusercontent.com/3941344/31885752-ea4b5334-b7f1-11e7-811c-b0981a2d48bb.png)

### Steps for anyone to reproduce the issue
1. Start Firefox 57 (or later).
1. Install uBO.
1. Move the uBO icon to the overflow menu.
1. Open the overflow menu and click uBO item.
1. The opened popup is much wider than needed.

### Your settings
- OS/version: Fedora 26
- Browser/version: Firefox Nightly 58
- uBlock Origin version: 1.14.16

**Comment by gorhill** [comment] 2017-10-23 11:26
Duplicate of #2809.

**Closed by gorhill** 2017-10-23 11:26 UTC
Labels: duplicate
