### ISSUE TITLE
Adblock Protector List URL still wrong v1.12.5b20

### ISSUE THREAD

**Issue by Daisenki** [gorhill/uBlock#2668] opened 2017-05-31 16:47 UTC
- OS/version: W10 1703
- Browser/version: Firefox 53.0.3 (64-Bit)
- uBlock Origin version: v1.12.5b20

Downloading the filter is not possible because a wrong/old url config.

![snip_20170531184020](https://cloud.githubusercontent.com/assets/22057956/26643873/1556e358-4633-11e7-986a-83c378031e8e.jpg)

Home url goes to: https://github.com/jspenguin2017/uBlockProtector
Info url goes to: https://jspenguin2017.github.io/AdBlockProtector/

chrome://ublock0/content/asset-viewer.html?url=abprotector-0

**Comment by gorhill** [comment] 2017-05-31 17:02
Duplicate of #2665: Read the comment at <https://github.com/gorhill/uBlock/commit/0ae695f8b1ac595e536a9a69dda86240e21d37dc#commitcomment-22306999> please.

Workaround until your `assets.json` is updated is to imported `https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtectorList.txt`.

**Closed by gorhill** 2017-05-31 17:02 UTC

**Comment by gorhill** [comment] 2017-05-31 17:06
Try this: Click _"Purge all caches"_, then click _"Update now"_. I think it should work.

**Comment by Daisenki** [comment] 2017-05-31 17:13
Thanks, it works with clear the caches and load all new, the list now downloads.
