### ISSUE TITLE
HTML Filtering + Back button

### ISSUE THREAD

**Issue by huubert** [gorhill/uBlock#3618] opened 2018-03-17 16:46 UTC
### Describe the issue
uBlock will filter an element using a ^ filter, but after following a link to another page and then coming back to the initial one using the browser's Back button, the element won't be blocked.

### One or more specific URLs where the issue occurs
https://www.reddit.com/r/popular/?geo_filter=GLOBAL

### Screenshot in which the issue can be seen
https://i.imgur.com/GIAbrJu.png

### Steps for anyone to reproduce the issue
1. Add this custom filter: reddit.com##^.listingsignupbar
2. Go to https://www.reddit.com/r/popular/?geo_filter=GLOBAL and make sure you're logged out
3. Click any "comments" link
4. Click the Back button
5. The "Welcome to Reddit" bar is not blocked anymore

### Your settings
https://i.imgur.com/CMLVRLc.png
- OS/version: Windows 7 Ultimate 64-bit
- Browser/version: Firefox Quantum 59.0.1 (64-bit)
- uBlock Origin version: uBlock Origin v1.15.16

##### Your filter lists
https://i.imgur.com/2padiwp.png

##### Your custom filters (if any)
reddit.com##^.listingsignupbar

**Edit:
This doesn't happen when using Private Browsing, so I assume it has something to do with caching.**

**Comment by huubert** [comment] 2018-03-17 17:36
I forgot to mention it doesn't always happen, but if I try it at least 5 times, it will happen.

**Comment by huubert** [comment] 2018-03-19 18:55
Is anyone looking at this? I can help with anything else that would be needed to reproduce this.

**Comment by huubert** [comment] 2018-04-02 16:52
Hello?

**Comment by grenzor** [comment] 2018-04-05 08:49
I also came across this issue when using a HTML filter on a different site a week ago but I remember I couldn't reproduce it every time (happened like 1 out of 10 times from memory). Will post a site with details if I reproduce this again.

**Comment by gwarser** [comment] 2018-05-16 17:03
@huubert @grenzor can you try this dev version https://github.com/gorhill/uBlock/releases/tag/1.16.7b0 ? Should be fixed in https://github.com/uBlockOrigin/uBlock-issues/issues/42

**Comment by gorhill** [comment] 2018-06-09 10:58
Most likely same issue solved in <https://github.com/uBlockOrigin/uBlock-issues/issues/42>.

**Closed by gorhill** 2018-06-09 10:58 UTC
Labels: unable to reproduce
