### ISSUE TITLE
Tradingview does not work, despite an entry in uBlock's whitelist.

### ISSUE THREAD

**Issue by findftp** [gorhill/uBlock#1605] opened 2016-05-02 13:48 UTC
I use www.tradingview.com to view financial charts.
I think something got updated because suddenly the site doesn't give a chart anymore when the plugin is enabled.
I've put the site in the whitelist but it doesn't work. Also pressing the enabled/disabled button doesn't work
Only when I completely disable the plugin the website works.
I'm on chromiumbrowser Version 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)
uBlock version 1.7.0

Few days ago it worked without problems.

**Comment by gorhill** [comment] 2016-05-02 13:59
Duplicate of #1604.

**Closed by gorhill** 2016-05-02 13:59 UTC

**Comment by findftp** [comment] 2016-05-02 14:00
Oh, I'm really sorry!

**Comment by gorhill** [comment] 2016-05-02 14:03
Don't, I am the one who should (I do) feel sorry.
