### ISSUE TITLE
UI cut when in Firefox overflow menu

### ISSUE THREAD

**Issue by rugk** [gorhill/uBlock#3607] opened 2018-03-15 09:55 UTC
### Describe the issue

Similar to https://github.com/gorhill/uBlock/issues/2809, but quite the opposite: When in the overflow menu, uBlock origin has a too big width.

### One or more specific URLs where the issue occurs

Everywhere.

### Screenshot in which the issue can be seen

![grafik](https://user-images.githubusercontent.com/11966684/37456062-d2c9d9b6-283e-11e8-99a2-cd82038608dd.png)

### Steps for anyone to reproduce the issue

0. Enable expert mode or so, the "default" UI is small enough.
1. Move icon into overflow menu.
2. Open it.

### Potential solution

Either:
* Make UI somehow "responsive".

Or:
* Enable horizontal scrollbar, there, so you can scroll, at least.

### Versions

- Browser/version: Firefox 58
- uBlock Origin version: uBlock Origin 1.15.10

##### Your filter lists

do not matter

##### Your custom filters (if any)

do not matter

**Comment by img2tab** [comment] 2018-03-31 16:25
Reproduced in Firefox 59.0.2 on Windows 10, uBlock Origin 1.15.18

**Comment by gorhill** [comment] 2018-04-16 11:01
Duplicate of #2809.

**Closed by gorhill** 2018-04-16 11:01 UTC
Labels: duplicate
