### ISSUE TITLE
How to deal the confliction with Ghostery ?

### ISSUE THREAD

**Issue by eromoe** [gorhill/uBlock#3243] opened 2017-11-18 10:33 UTC
After I install Ghostery, chrome tell me:

```
此扩展程序无法将该网络请求重新定向到 (can not redirect to )
data:application/javascript;base64,dmFyIHV .....

因为其他扩展程序（Ghostery）已将其重新定向到 ( because Ghostery already do it )
data:application/javascript;base64,dmFyIHV .....
```

How do I deal this ?

**Comment by gorhill** [comment] 2017-11-18 11:23
Duplicate of #1170.

**Closed by gorhill** 2017-11-18 11:23 UTC
Labels: duplicate

**Comment by lewisje** [comment] 2017-11-18 22:31
Short answer: Don't use Ghostery.
