### ISSUE TITLE
Firefox Popups can't be closed

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1306] opened 2016-01-27 17:20 UTC
Issue: Firefox will occasionally prevent popups from being blocked by uBO.
Same as here: https://github.com/gorhill/uBlock/issues/1201#issuecomment-170393394

Screenshot: ![](https://cloud.githubusercontent.com/assets/16030872/12620755/d027648e-c51d-11e5-89fb-5df941c11d93.jpg)
Demonstration (NSFW): https://u.pomf.is/efngkf.mp4
Logger: ![](https://cloud.githubusercontent.com/assets/16030872/12621643/bf21d544-c521-11e5-8d5b-62492b06d537.png)

My specs:
Firefox ESR 38.5.2 (fresh profile)
uBO 1.5.5 in standard configuration with updated filter lists
Also tried uBO 1.6.0b8 in standard configuration with updated filter lists
Windows 7

How to reproduce:
1. Install Firefox and uBO and update it's filter lists
2. Open a new tab while keeping the old one open. You should now have two tabs open. In the new tab visit a site like [NSFW] http://javhub.net/play/d122f1105/55c458aa6fb5fc4e25a6ad74/JUX-626-F-of-beauty-milf-play-with-temptation-younger-man-boss-Dirty-cum-Chaoyang-Mizuno
3. Click the play button and recognize a popup being opened
4. Firefox asks if 2 tabs should be closed and hinders the popup from being closed
5. Click any of the two given options since that's all the browser will react to

You may have to try this multiple times with deleting cookies in between since the popup will get blocked correctly sometimes.

Issue does not arise in Chrome or Chromium.

**Comment by gorhill** [comment] 2016-01-27 20:11
I followed the steps carefully, I am unable to reproduce.

Will wait for somebody else to reproduce.

**Comment by happysurf** [comment] 2016-01-29 11:40
No popup here with XP + Firefox 45beta1 + UBO 1.6.0b8 default list + Anti-ThirdpartySocial, Fanboy’s Social Blocking List‎ and Adguard Russian Filter‎.

**Comment by IDKwhattoputhere** [comment] 2016-02-14 20:14
Happens on this site too: https://forums.lanik.us/viewtopic.php?p=86987#p86987

**Comment by gorhill** [comment] 2016-02-14 22:24
Unable to reproduce with this site either (FF-44):

![a](https://cloud.githubusercontent.com/assets/585534/13036801/c0422ccc-d33f-11e5-8930-3037d591b90b.png)

**Comment by IDKwhattoputhere** [comment] 2016-02-14 23:40
Completely new Firefox profile on Windows 7: http://a.pomf.cat/iehvhd.mp4
I even downloaded the English (US) version of FF on the off chance that it might fix the issue.

**Comment by IDKwhattoputhere** [comment] 2016-04-20 12:26
Just to confirm: Still happening [here (NSFW)](http://javhub.net/play/d122f1105/55c458aa6fb5fc4e25a6ad74/JUX-626-F-of-beauty-milf-play-with-temptation-younger-man-boss-Dirty-cum-Chaoyang-Mizuno) in the newest stable version of Firefox and uBO in a fresh profile.

**Comment by gorhill** [comment] 2017-09-11 16:02
Issue is old and was unreproducible, closing due to obsolescence.

**Closed by gorhill** 2017-09-11 16:02 UTC
Labels: unable to reproduce
