### ISSUE TITLE
suggestion for strict blocking

### ISSUE THREAD

**Issue by chrcoluk** [gorhill/uBlock#298] opened 2015-06-05 16:07 UTC
Ok a couple of times today I had a strict blocking warning page, I browsed using the temporary overide and both times was normal news sites.

My suggestion is I hope is simple.

If possible display the name of the block list that the filter is listed in.  This should also serve a purpose to remind the end user that its not ublock that is in control, but them self in using that block list.

As a end user, if I see its a malware list block, I will think twice before overiding.  Hence the suggestion as well.

Hope this suggestion is deemed reasonable.

Chris

**Comment by Snapy** [comment] 2015-06-05 17:09
Duplicate of #58.

**Closed** 2015-06-11 23:33 UTC
