### ISSUE TITLE
Stylesheets still being removed after blocking all scripts

### ISSUE THREAD

**Issue by narcolepticinsomniac** [gorhill/uBlock#2482] opened 2017-03-28 00:07 UTC
Someone complained [here](https://forum.userstyles.org/discussion/54834/why-wont-styles-activate-on-mmo-champion#latest) that stylesheets were being removed from:
http://www.mmo-champion.com/content/
I checked to see if it was an easy fix, by blocking javascript, but it wasn't working. I tried blocking practically everything, 1st + 3rd-party + inline scripts, and it still wasn't working. Going into settings and blocking javascript there worked fine, and stylesheets were no longer removed.

It's very possible this is a simple error on my part, but I'm scratching my head. 

uBlock Origin v1.11.4

Chromium Version 57.0.2987.110 (64-bit)

**Comment by gorhill** [comment] 2017-03-28 01:16
Why should stylesheets be removed when blocking javascript? I have no clue what is the issue here.

Provide exact description of the issue, what is expected vs. what is acutally heppening, and all the _exact_ and detailed repro steps.

**Comment by narcolepticinsomniac** [comment] 2017-03-28 01:22
I mangled the title twice. Typically sites that remove stylesheets can be rectified by blocking their scripts. I tried blocking 1st + 3rd-party + inline-scripts in Ublock, but stylesheets are still removed. Blocking javascript in Chrome settings prevents stylesheets from being removed as expected. Apologies for the lack of clarity.

**Comment by gorhill** [comment] 2017-03-28 01:27
I still do not understand what the issue is. I am not a user of that site -- I know nothing about it. Without better issue report forthcoming, the issue is invalid. This is what I get -- seems all fine:

![a](https://cloud.githubusercontent.com/assets/585534/24384737/13c14506-1334-11e7-8034-bbc97b80936a.png)

Provide all info I asked above please.

**Comment by narcolepticinsomniac** [comment] 2017-03-28 01:57
I don't use the site or know much about it either. All I'm saying is that blocking every type of script possible in ubo doesn't prevent stylesheets from being removed on reload, but blocking javascript for the site through Chrome settings does prevent stylesheets from being removed.

Since these methods of blocking javascript should be essentially work the same AFAIK, I found it odd. I really don't know how to explain it any better, so I made a 2min vid if that helps. The style being removed is for the scrollbar. Otherwise, mark as invalid. NBD, I've done a poor job explaining things here.
[ubo.zip](https://github.com/gorhill/uBlock/files/874263/ubo.zip)

**Comment by gorhill** [comment] 2017-03-28 04:25
> Since these methods of blocking javascript should be essentially work the same AFAIK, I found it odd.

They don't. uBO injects a content security policy as a HTTP header to block inline javascript. The browser disable all javascript on the page internally such that `noscript` tags take effects.

The way to file issue is to following exactly the template when opening a new issue. I can't even make sense of why a site would remove its own stylesheets. Your zipped mp4 does not decode on my side. Marking as _invalid_ until the issue if any is properly explained with all details as per template.

**Closed by gorhill** 2017-03-28 04:25 UTC

**Comment by narcolepticinsomniac** [comment] 2017-03-29 03:27
As bad as my description of this issue was, the problem ended up not having as much to do with uBO in general, but more accurately uBO-Extra. Apparently the site in question was not maliciously removing stylesheets, but is on uBO-Extra's blacklist, which I've been told basically triggers a rewrite of the html. This was preventing userstyles in Stylish or other similar userstyle managers to fail, so styles were not being applied.

I'm using a fork of Stylish, which has now fixed this, and other potential stylesheet removals, by running a check to ensure that styles have been applied. The conflict will still remain an issue for Stylish and likely other similar extensions. 

I'm not suggesting that this should be a huge deal to you, or asking you to fix anything. I just figured I'd follow up and let you know.

**Comment by uBlock-user** [comment] 2017-03-29 13:13
> but is on uBO-Extra's blacklist, which I've been told basically triggers a rewrite of the html.

Because of this, read - https://github.com/uBlockOrigin/uAssets/issues/227

**Comment by gorhill** [comment] 2017-03-29 13:20
> The conflict will still remain an issue for Stylish and likely other similar extensions.

Unfortunately, there is nothing which can be done, this is a case where one has to choose between to cure to a severe issue, and the less severe side-effects of the cure.

This side-effect is not a novelty, the same could/can be experienced when using Reek's user script -- even uBO itself was affected by such an issue when using Reek's user script, there is a closed issue somewhere about this.
