### ISSUE TITLE
uBlock Origin >1.13.8 Does not Work on Android Firefox 56

### ISSUE THREAD

**Issue by joshua-oxley** [gorhill/uBlock#3000] opened 2017-09-11 00:29 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

I have the latest Firefox on my Nexus 6P.  When I received the latest update for uBlock Origin, I noticed my ads were showing up on sites that were previously blocked.  I tried to access the settings page but I could not access it.  I tried to access it through the drop down and then I tried to go through the Add-Ons.  That did not work either.  I downgraded to previous versions until I could access the settings to uBlock Origin.  Incidentally, it works with 1.13.8 which is mentioned in the release notes.

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Android 7.1.2
- Browser/version: Android Firefox 55.0.2
- uBlock Origin version: >1.13.8

**Comment by gorhill** [comment] 2017-09-11 00:42
Duplicate of #2958.

**Closed by gorhill** 2017-09-11 00:42 UTC
