### ISSUE TITLE
Chrome: Waiting for extension uBlock Origin

### ISSUE THREAD

**Issue by drone540** [gorhill/uBlock#2534] opened 2017-04-12 19:16 UTC
I've been noticing lately that my uBlock Origin has been causing my Google Chrome to lock up waiting for ublock origin to respond. I get this happening quite often lately when it used to never be an issue before.

I would like to help figure out why chrome is waiting for uBlock Origin, but I have no idea where to even start once this issue begins.

Also after it does this twice or more. It most likely will no longer work once you reload the extension. You'll have to reopen Google Chrome to get it working again.

Let me know what I can do once google chrome starts waiting for ublock origin.

Note: I use quite a bit of tabs. Around 100 or so. However I've successfully gotten up to 800+ tabs before no problem with this plugin. No idea if it's just Google chrome that's changed or the extension.

**Comment by drone540** [comment] 2017-04-12 20:01
Looks like it has crashed again only 38 minutes after posting this again.

Attached image.
![waitingublock](https://cloud.githubusercontent.com/assets/15643580/24976906/3da4930c-1f99-11e7-961e-2a7c77097040.JPG)

**Comment by harshanvn** [comment] 2017-04-12 20:06
pls. do provide your system info. So, people can test it if possible..

**Comment by drone540** [comment] 2017-04-12 20:19
>systeminfo.exe

Host Name:                 HOSTNAME
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          RegisteredOwnerName
Registered Organization:
Product ID:                00326-10000-00000-AA294
Original Install Date:     9/21/2016, 8:36:29 PM
System Boot Time:          4/5/2017, 4:18:24 PM
System Manufacturer:       To Be Filled By O.E.M.
System Model:              To Be Filled By O.E.M.
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~3301 Mhz
BIOS Version:              American Megatrends Inc. P2.90, 7/11/2013
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,265 MB
Available Physical Memory: 3,464 MB
Virtual Memory: Max Size:  40,692 MB
Virtual Memory: Available: 19,253 MB
Virtual Memory: In Use:    21,439 MB
Page File Location(s):     E:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\SERVER
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB3176935
                           [02]: KB3176936
                           [03]: KB3176937
                           [04]: KB3199209
                           [05]: KB3199986
                           [06]: KB3211320
                           [07]: KB4013418
                           [08]: KB4014329
                           [09]: KB4015438
Network Card(s):           4 NIC(s) Installed.
                           [01]: VMware Virtual Ethernet Adapter for VMnet1
                                 Connection Name: VMware Network Adapter VMnet1
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.184.1
                                 [02]: fe80::d01:972f:682f:cb87
                           [02]: VMware Virtual Ethernet Adapter for VMnet8
                                 Connection Name: VMware Network Adapter VMnet8
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.248.1
                                 [02]: fe80::d4c1:2c73:9296:c8eb
                           [03]: Broadcom NetLink (TM) Gigabit Ethernet
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.101
                                 [02]: fe80::59e2:376c:9ec2:9364
                                 [03]: 2601:c4:4000:5f8e:e9c8:55bd:2a86:a52a
                                 [04]: 2601:c4:4000:5f8e:a8d6:f3db:a53f:e5a5
                                 [05]: 2601:c4:4000:5f8e:a1cf:3cd7:e52f:db4e
                                 [06]: 2601:c4:4000:5f8e:6511:486b:776f:621c
                                 [07]: 2601:c4:4000:5f8e:4de8:7d8:173e:fb2
                                 [08]: 2601:c4:4000:5f8e:35db:4b55:21e9:1b2e
                                 [09]: 2601:c4:4000:5f8e:1065:1297:a942:ad14
                                 [10]: 2601:c4:4000:5f8e:5e7:462b:806e:a81c
                                 [11]: 2601:c4:4000:5f8e:59e2:376c:9ec2:9364
                                 [12]: 2601:c4:4000:5f8e::1154:b3d4
                           [04]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::9c1e:3c6e:6e6c:ec3e
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by harshanvn** [comment] 2017-04-12 20:27
pls scrub network card info..i dont think anyone needs that

**Comment by gorhill** [comment] 2017-04-13 12:55
It says "Waiting for extension Tampermonkey" in your screenshot.

Try with just uBO, disable all other extensions.

**Comment by drone540** [comment] 2017-04-14 00:19
Yes I know, but that's because both are in the same process that run for some reason. Usually if I kill tampermonkey it will change from Waiting for Tampermonkey to Waiting for uBlock Origin. Hence the task manager in the screenshot also. Not really sure but I guess chrome starts combining stuff when lots of tabs are open.

**Comment by OneOfMany07** [comment] 2017-06-09 02:44
Any new info?

I'd look for a log to enable or debug mode to turn on.  Debug mode likely increases resource usage, but it'll also let you see what it was doing.

Also someone on here mentioned having an SQLite database that got huge and likely corrupted.  Don't know if you can clean a local cache from the tool to maybe reset your state.

**Comment by drone540** [comment] 2017-08-30 13:20
I have not yet noticed it happening recently. I'll have to double check my settings to see if anything has changed. I'll report when it happens again. I'll have to maybe put more load on google chrome perhaps and see what happens.

**Comment by gorhill** [comment] 2017-09-10 14:52
Can't reproduce, and appears specific to OP, thus closing. If it still occurs, please investigate fully on your side for the cause, there is no point opening such issue which happens only to you, only you can investigate the cause, otherwise this will just be an open issue which will never be resolvable.

**Closed by gorhill** 2017-09-10 14:52 UTC
Labels: unable to reproduce
