### ISSUE TITLE
Committing a single rule?

### ISSUE THREAD

**Issue by acrobat1** [gorhill/uBlock#1086] opened 2015-12-18 21:47 UTC
Unless I'm missing something obvious (for which I shall apologize in advance) I think there's currently  no quick way to commit just a single rule in the **My Rules** tab: you have to commit all temporary rules at once, therefore to save just one you'll have to cut/paste to a clipboard all the temporary rules you want to keep for the current session, commit and then paste the temporary rules back  again.

I understand  you could do that somehow from the popup interface in advanced mode, but it would be IMHO so much easier if a single rule (or multiple selected rules, come to that) could also be committed from temporary to permanent in the **My Rules** tab.

Sometimes before deciding to block permanently something, you may have already allowed or set  to noop other elements on that page, in that case to permanently block that something you'll have to first undo the other settings and then make that  block rule permanent from the popup interface.

**Comment by gorhill** [comment] 2015-12-18 22:14
Duplicate of #114.

**Closed by gorhill** 2015-12-18 22:14 UTC
