### ISSUE TITLE
Firefox Mobile (Aurora) - Show Dashboard Button missing

### ISSUE THREAD

**Issue by Stefan-Code** [gorhill/uBlock#1379] opened 2016-02-14 11:22 UTC
Using Firefox Mobile (Aurora) `46.0a2 (2016-02-14)` on Android `4.4.4` and the latest ublock from the firefox addons store, the _Show Dashboard_ button in the "Your Addons" section does not appear, please see the screenshot below. Restarting the browser as well as disabling and re-enabling ublock had no effect. Apart from the missing _Show Dashboard_ ublock works fine (i.e. is blocking requests). The link does appear for me on Firefox Mobile `43.0` from F-Droid.
![Screenshot](https://i.imgur.com/sx9Wtuel.png)

**Comment by kowith337** [comment] 2016-02-20 07:19
can you still access uBlock0 popup window from vertical dot menu?
For temporary solution, tap on top of popup that show plugin name and version to go dashboard.

**Comment by Stefan-Code** [comment] 2016-02-20 08:50
Yes, that works.

**Comment by davidhedlund** [comment] 2016-08-10 05:29
I can confirm this issue. I see two blank buttons with no text.

**Comment by TonyTough** [comment] 2016-08-10 21:37
Hm,
I am using Firefox for Android 48 an my smartphone (Android 4.4.2), ublock 1.8.4 and I do not have these problems.

**Comment by davidhedlund** [comment] 2016-08-11 08:57
I had a similar issue with IceCatMobile 38.8.0 and uBO 1.8.4 on Android 4.4.2. The buttons appear but without text.

**Comment by davidhedlund** [comment] 2016-09-22 02:18
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by peterxiyong** [comment] 2017-02-01 16:59
& still extension is broken on firefox android
@gorhill

**Comment by gorhill** [comment] 2017-02-01 17:08
Feel free to contribute a solution.

**Comment by ghajini** [comment] 2017-02-07 14:54
please fix

**Comment by gorhill** [comment] 2017-02-07 15:03
Similar issue with ABP: <https://issues.adblockplus.org/ticket/4867>. This suggests the issue lies with Firefox Mobile (Aurora).

**Comment by kowith337** [comment] 2017-02-09 04:29
Since Firefox android 51 (and above), I cannot see more settings in **any** extensions, but if disabled and re-enable extension again, an extension settings will be return.
But only last for that attempt, if you go back to all extension list and return again, it will gone...

**Comment by gorhill** [comment] 2017-02-09 13:52
Probably related bugzilla entry: <https://bugzilla.mozilla.org/show_bug.cgi?id=1329027>.

**Comment by Maxxee** [comment] 2017-04-17 07:12
There ARE other extensions which have no problems at all showing their options:
- Decentraleyes
- Tap Translate

Maybe the coders can exchange their knowledge, or is this already out / uncool nowadays?

**Comment by gorhill** [comment] 2017-04-17 12:39
Problem is in Firefox, fixed in 53, see bugzilla entries above.

**Closed** 2017-04-17 12:39 UTC
Labels: browser bug

**Comment by BloodyRain2k** [comment] 2017-09-05 05:32
I got Firefox 55.0.2 and I don't see any settings for any add-on at all : (

**Comment by Thorin-Oakenpants** [comment] 2017-09-05 08:05
@BloodyRain2k - FF55 + uBo WE issue is different to OP - try gorhill's suggestion: https://github.com/gorhill/uBlock/issues/2958#issuecomment-326797798 . The problem will fix itself when 56 lands on your smart phone
