### ISSUE TITLE
Page turns blank, doc domain lost, exception for page resets

### ISSUE THREAD

**Issue by gwarser** [gorhill/uBlock#936] opened 2015-11-12 16:48 UTC
http://www.fakt.pl/polska/w-pociagu-katowice-lublin-zaginela-weronika-skrzyniarz,artykuly,590038.html
Page loads, blinks for a moment, turns blank, don't stop loading (spinning indicator)
Only `ocdn.eu` in popup.
3rd-party scripts and 3rd-party frames globally blocked.
When I try to unblock locally or disable filtering (power button), settings resets back.
Need to click inside urlbar + enter to see page again (just blinks) - reloading is less effective.

```
17:32:00.226 TypeError: onetAds.setTarget is not a function
 articleScripts.js:23:21
17:32:01.245 ReferenceError: ApplicationFacade is not defined
 w-pociagu-katowice-lublin-zaginela-weronika-skrzyniarz,artykuly,590038.html:670:1
17:32:01.619 TypeError: can't access dead object cosmetic-logger.js:60:5
17:32:02.084 TypeError: onetAds.addSlot is not a function
Stack trace:
initLoadAds@http://www.fakt.pl/jsb/46100504/bundles_2/articleScripts.js:158:1
window.onload@http://www.fakt.pl/jsb/46100504/bundles_2/articleScripts.js:88:5
 articleScripts.js:164:13
17:32:02.169 TypeError: can't access dead object cosmetic-logger.js:60:5
17:32:02.632 TypeError: container_id is undefined
 articleScripts.js:19:25
17:32:14.817 TypeError: can't access dead object cosmetic-logger.js:60:5
```

`cosmetic-logger.js` -> `chrome://ublock0/content/js/scriptlets/cosmetic-logger.js`

uBO 1.3.4rc0 Fx 43b2 on Mint
...
Works when I hit ESC on time to stop loading and then apply noop on 3rd-party scripts.
...
Reproduced with uBO default settings + 3rd-party scripts and 3rd-party frames globally blocked.

**Comment by gorhill** [comment] 2015-11-12 17:05
I could reproduce. Page just crap itself if blocking some of the stuff. Fixed with:

    ||www.fakt.pl$xmlhttprequest,first-party

But then now I can't reproduce when I remove that filter.

I was not able to reproduce the error message:

> `17:32:14.817 TypeError: can't access dead object cosmetic-logger.js:60:5`

**Comment by gorhill** [comment] 2015-11-12 17:26
uBO's LocationChangeHandler is receiving an event for which the URL is

    "wyciwyg://25/http://www.fakt.pl/prawo/wczesniejszy-powrot-ze-zwolnienia-l4-moze-oznaczac-klopoty,artykuly,590137.html"

So uBO is being told the tab is being navigated to that address...

**Comment by gwarser** [comment] 2015-11-12 17:32
>I was not able to reproduce the error message...

Try with opened uBO logger

**Comment by gorhill** [comment] 2015-11-12 17:56
I got one

`TypeError: can't access dead object` -> `chrome://ublock0/content/js/vapi-client.js 124:1`

But it does not make much sense. I believe the fact that FF is confused with that `wyciwyg://25/http://www.fakt.pl/prawo/wczesniejszy-powrot-ze-zwolnienia-l4-moze-oznaczac-klopoty,artykuly,590137.html` URL is causing all sort of bad side effects to FF and to uBO.

**Comment by gorhill** [comment] 2015-11-12 18:00
Instances of similar issues:

- <https://support.mozilla.org/en-US/questions/699151>
- <https://support.mozilla.org/en-US/questions/939802>
- <https://bugzilla.mozilla.org/show_bug.cgi?id=123140>
- <https://wordpress.org/support/topic/wyciwyg-redirection-issue>

Etc.

**Comment by gorhill** [comment] 2015-11-12 18:06
Ok, it sounds it's a FF issue, I doubt LocationChangeListener should not be called with the above URL, and there has been such similar issue in the past. Maybe worth reporting it to the FF issue tracker, since it's pretty easy to reproduce.

**Comment by gorhill** [comment] 2015-11-12 18:57
I want to keep it open, I am pondering whether uBO should specifically look for the anomalous `wyciwyg://` in LocationChangeListener and discard. I am curious about what FF devs thinks of this.

**Comment by Gittyperson** [comment] 2016-07-01 23:16
I am getting this today on www.gazzetta.gr - it goes blank after a second and seems looping. Pressing "Open with IE" sends this link to IE: wyciwyg://11/http://www.gazzetta.gr/

Using Pale Moon 26.3.3 x86, W10 Pro x64 - when disabling uBO problem goes away. Settings/
[Settings.zip](https://github.com/gorhill/uBlock/files/344286/Settings.zip)
3rd party filters attached.

**Comment by gorhill** [comment] 2016-07-01 23:52
It's a filter list issue, the site needs `static.adman.gr/adman.js`, but EasyList blocks it with `||adman.gr^$third-party`. Report to maintainers of EasyList: <https://forums.lanik.us/viewforum.php?f=64>.

**Comment by gorhill** [comment] 2017-09-09 17:46
This issue is probably now irrelevant with WebExtensions.

**Closed by gorhill** 2017-09-09 17:46 UTC
Labels: browser bug
