### ISSUE TITLE
Content disappear with an anti ad-block website

### ISSUE THREAD

**Issue by LearZhou** [gorhill/uBlock#1562] opened 2016-04-13 23:52 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
This is the website I am talking about: http://www.cnbeta.com/, which introduced some kind of anti ad-block feature. It used to warn that this site needs ads for support, until now, click any sub link on this page, the content will disappear, so is the warning.

### One or more specific URLs where the issue occurs
http://www.cnbeta.com/
For example: http://www.cnbeta.com/articles/492241.htm

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]
https://www.dropbox.com/s/rridyvy6c1bjcsj/Screen%20Shot%202016-04-13%20at%204.48.40%20PM.png?dl=0

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
uBlock Origin 1.6.8, with default settings, added Easylist China as extra filter list.

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: 
Firefox 45.0.2
- uBlock Origin version: 
1.6.8 Release
##### Your filter lists
Default filter lists + Easylist China

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment] 2016-04-13 23:59
Two points:

1. You did not read [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md):

> For **filter-related issues**, report at [uBlockOrigin/uAssets](https://github.com/uBlockOrigin/uAssets/issues).

2. I was not able to reproduce any case of blank page.

**Comment by gorhill** [comment] 2016-04-13 23:59
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-04-13 23:59 UTC
