### ISSUE TITLE
[Feature Request] Youtube channel whitelisting

### ISSUE THREAD

**Issue by gr3ger** [gorhill/uBlock#3368] opened 2017-12-25 14:49 UTC
Something I'd love to have is whitelisting specific channels on youtube to show support towards content creators.

I'm not sure if this is easily implemented since the URL does not contain any info about which channel the video is from, you'd probably have to parse some of the page to get that info so I don't know how feasible this is for uBlock.

**Comment by gorhill** [comment] 2017-12-25 14:56
Duplicate of #47.

There won't be vendor-specific code in uBO. Adding special code for one means having to add special code for any out there.

**Closed by gorhill** 2017-12-25 14:56 UTC
Labels: declined
