### ISSUE TITLE
Slows YouTube

### ISSUE THREAD

**Issue by Li-An** [gorhill/uBlock#812] opened 2015-10-11 09:14 UTC
Firefox 41.01. When Ublock Origin is activated all YouTube videos are very slow to charge. When desactivated, all is "normal".

**Comment by SW1FT** [comment] 2015-10-11 12:52
You might want to lower the amount of lists you have currently active, I suspect it's your connection/pc struggling to keep up.

**Comment by gorhill** [comment] 2015-10-11 13:26
> I suspect it's your connection/pc struggling to keep up.

I doubt this is the issue -- uBlock Origin performs well even with slower PC. Sometimes when stuff get blocked on a page, the page may do things it wouldn't do otherwise, and some of those things may cause delays.

In any case, the issue is pretty much bare of any details, so it's impossible to try to reproduce meanngfully. Marking as invalid for now until [proper **detailed repro steps** are provided](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gorhill** [comment] 2015-10-11 13:28
Videos load nicely here, using default settings.

**Comment by Li-An** [comment] 2015-10-11 14:29
Sorry, I did not see detailed repro steps.
Firefox 41.01, Ublock Origin 1.2.1. I use default activated list + french list

Some french users are complaining (https://forums.mozfr.org/viewtopic.php?f=5&t=126465&p=803111&hilit=ublock#p803111) so  It can be a problem related with some french providers. If I'm the only one for the moment to have this problem, we can imagine it's not the extension the guilty.

**Comment by gorhill** [comment] 2015-10-20 13:30
By the look of it, unrelated to uBO proper, at most a filter list issue.

**Closed by gorhill** 2015-10-20 13:30 UTC
Labels: invalid, unable to reproduce

**Comment by gorhill** [comment] 2015-10-22 23:22
It's always useful to look at the browser console (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>J</kbd>) to find out if the browser has something noteworthy to say when you do a specific action (visiting a Youtube page here).

**Comment by Li-An** [comment] 2015-10-25 17:31
I've tested on another profile - with same extensions activated - and the problem is not showing. So, it's relative to the profile. I will create a new profile and see how it shows.
