### ISSUE TITLE
It is strongly recommended uBlock increase keyboard shortcuts function, can it?

### ISSUE THREAD

**Issue by dnknn** [gorhill/uBlock#1627] opened 2016-05-11 22:38 UTC
Dear uBlock author Hello!
I was a fan from China, because do not understand English, so translation to machine translation can only use Google, I do not know understand not?
It is strongly recommended to join now uBlock Enter element shortcuts support picker mode, okay?
![clipboard1](https://cloud.githubusercontent.com/assets/10995302/15198134/1d70f1a0-1808-11e6-88d7-4a935b9ae2f2.png)

Specifically in Keyboard shortcuts Extensions page added, chrome: // extensions / configureCommands
If so, then the way to support you undo the last selection shortcuts.
![clipboard](https://cloud.githubusercontent.com/assets/10995302/15198141/20e56d34-1808-11e6-9bfb-81755c820d3d.png)
If supported, it will be more convenient, and I know that the page has a context menu, but that is not the most convenient.
Illustration trouble self-testing will understand: Copy Better
https://chrome.google.com/webstore/detail/copy-better/hpihdokfdmmghaclaojfpmbckkhjgebc

Or you can add a more powerful uBlock of Element picker Helper
E.ghttps://chrome.google.com/webstore/detail/ahieappfkblneagblagpodhjmnhcbfdn

At last,I wrote notes document
url shorter:http://goo.gl/O6uCnM

**Comment by foss-** [comment] 2016-05-12 08:47
Is this a dupe of https://github.com/gorhill/uBlock/issues/1307 ?

Still, +1 for adding a keyboard shortcut to trigger the element picker.

**Comment by dnknn** [comment] 2016-05-12 09:36
Different ways of implementation of the proposal, the proposed implementation of the method is relatively simple and direct, direct use of Google Chrome keyboard shortcuts API.

**Comment by dnknn** [comment] 2016-05-12 09:36
Different ways of implementation of the proposal, the proposed implementation of the method is relatively simple and direct, direct use of Google Chrome keyboard shortcuts API.

**Comment by foss-** [comment] 2016-05-12 09:59
well uBlock is cross browser. so having a defaul shortcut like ⌘K (known from AdBlock Plus) would be the best solution, imo.

**Comment by gorhill** [comment] 2016-05-12 11:56
Duplicate of #113.

**Closed by gorhill** 2016-05-12 11:56 UTC

**Comment by Industry** [comment] 2016-06-03 06:47
Would love
