### ISSUE TITLE
uBlock 1.13.10 - Not working

### ISSUE THREAD

**Issue by lKobi** [gorhill/uBlock#2909] opened 2017-08-28 17:04 UTC
### [Please carefully read the [Release notes](https://github.com/gorhill/uBlock/releases/tag/1.13.10), what you need to do is explained in there -- @gorhill]

***

### Describe the issue
uBlock was automatically updated to 1.13.10, and since then it stopped working whatsoever (can't even get access to the options screen), and the icon disappeared (from next to the address bar).

uBlock is still listed as enabled on Extensions and I can see [More] page, beyond that nothing works.

### One or more specific URLs where the issue occurs
All, not working at all I get ads in every website.

### Steps for anyone to reproduce the issue
Leave Firefox to Update the Addon Automatically, no user interaction was done nor beta builds installed.

### Your settings

- OS/version: Windows 10 (x64)
- Browser/version: Firefox 55.0.3 (Latest Stable Build) (x64)
- uBlock Origin version: 1.13.10 (Automatic Update from Firefox)

##### Your filter lists
Don't have access to options panel.

##### Your custom filters (if any)
Don't have access to options panel.

**Comment by monkeymagic29** [comment] 2017-08-28 17:24
Reproducible with Android Firefox 55.0.2. Exact same UBO version. Similar issues.

**Comment by superlex** [comment] 2017-08-28 17:28
I can confirm on macOS 10.12.6, Firefox 55.0.3 (Latest Stable Build) (x64), uBlock Origin 1.13.10.
Updating to 1.13.11rc0 fixes the issue for me.

**Comment by monkeymagic29** [comment] 2017-08-28 17:32
Forgot submission must be done in proper manner.

OS/version: Android 7.0 (ARM v8 64 bit)
Browser/version: Firefox 55.0.2 build from Firefox official page
uBlock Origin version: 1.13.10 webext-hybrid

The only interactable is disable and uninstall. Winter is here.

**Comment by gorhill** [comment] 2017-08-28 17:35
Please report any related errors reported at the browser console (ctrl-shift-j).

**Comment by monkeymagic29** [comment] 2017-08-28 17:38
@gorhill I don't think I can access console with Firefox Android client.

**Comment by gorhill** [comment] 2017-08-28 17:38
Maybe related to <https://github.com/gorhill/uBlock/issues/2799>?

If so, this would be <https://bugzilla.mozilla.org/show_bug.cgi?id=1383064#c2>.

Woraround: re-install uBO over uBO.

**Comment by monkeymagic29** [comment] 2017-08-28 17:45
@gorhill UBO lost the ability to update, and add-on for Android, at least, seems pretty binary; either uninstall or don't. Accessing desktop site definitely doesn't help.

**Comment by corobin** [comment] 2017-08-28 17:45
I can confirm as well on Win10Prox64 and Fx55.0.3(64bit)

Toolbar icon disappeared and no ability to open Options panel.

Tried disabling and re-enabling, doesn't change anything.

But on other computer, installed uBO on 55.0.2 first, which then stopped working as before. But then I upgraded Fx to 55.0.3 and uBO now appears to work.

Installing uBO over uBO again on AMO makes it work right after installation, but it again doesn't work anymore after Fx is restarted.

**Comment by TonyTough** [comment] 2017-08-28 17:50
I can confirm that after closing and starting Firefox ublock 1.13.10 doesn't work again.

**Comment by gorhill** [comment] 2017-08-28 18:02
> I have now reinstalled version 1.13.8 and have deactivated updates for ublock origin in about:addons for the moment.

This will have to be the workaround because all this is pretty much out of my hands, the issue is with Firefox.

Here is a direct link to uBO 1.13.8: <https://addons.mozilla.org/firefox/downloads/file/685614/ublock_origin-1.13.8-an+fx+sm+tb.xpi>.

**Comment by lKobi** [comment] 2017-08-28 18:16
> This will have to be the workaround because all this is pretty much out of my hands, the issue is with Firefox.

Works, will have to do for now.

**Comment by monkeymagic29** [comment] 2017-08-28 18:22
Android users can still disable auto update on add-ons via about:config: extensions.autoupdate.enabled -> false
But it's universal though, unlike the more granular desktop client setup...

**Comment by Matthaiks** [comment] 2017-08-28 19:04
I fixed it by resetting the "Keep [cookies] until" option. Switched from "I close Firefox" to "they expire", restarted Fx, and again set to "I close Firefox".

**Comment by zlatovlas** [comment] 2017-08-28 20:23
Firefox 55.0.3 on Windows 7 x64. Does not work.

**Comment by hubslave** [comment] 2017-08-28 20:27
Had the same issue today. Uninstalling of the addon and then installing again did the trick. It even remembered all the settings and filters.

**Comment by vlakoff** [comment] 2017-08-28 20:27
That was the last straw, switching to Pale Moon.

**Comment by gorhill** [comment] 2017-08-28 20:31
> It even remembered all the settings and filters.

Ah yes, that makes sense given it migrates data from the legacy storage version -- and which legacy storage is never removed. There was no need for me to say "do not uninstall".

**Comment by sensor** [comment] 2017-08-28 20:31
Why would you guys update. This version doesn't work at all. I'm just amazed.

**Comment by HanXHX** [comment] 2017-08-28 22:19
On windows, I confirm reinstalling bypass this bug.

**Comment by cesarb** [comment] 2017-08-29 00:43
As another datapoint: I just had this same issue, Firefox 55.0.2 on Fedora 26, uBlock Origin suddenly disappeared (no icon on toolbar, not blocking anything), extension manager showing it had updated today to webext-hybrid 1.13.10.

However, I managed to fix it in a way not mentioned so far. I had an update to Firefox pending, so I did the "yum update" (with Firefox closed):

```
    Atualizados  firefox-55.0.2-2.fc26.x86_64                     @updates
    Atualizar            55.0.2-3.fc26.x86_64                     @updates
[...]
    Atualizados  nspr-4.15.0-1.fc26.i686                          @updates
    Atualizados  nspr-4.15.0-1.fc26.x86_64                        (unknown)
    Atualizar         4.16.0-1.fc26.i686                          @updates
    Atualizar         4.16.0-1.fc26.x86_64                        @updates
    Atualizados  nspr-devel-4.15.0-1.fc26.x86_64                  @updates
    Atualizar               4.16.0-1.fc26.x86_64                  @updates
    Atualizados  nss-3.31.0-1.1.fc26.i686                         @updates
    Atualizados  nss-3.31.0-1.1.fc26.x86_64                       (unknown)
    Atualizar        3.32.0-1.1.fc26.i686                         @updates
    Atualizar        3.32.0-1.1.fc26.x86_64                       @updates
[...]
```

When I opened Firefox after the update, uBlock Origin was back and seems to be working as expected so far, with all my custom rules intact.

I have a hunch that this is some sort of caching issue, and that when Firefox detected its files had changed outside its control, it threw away and regenerated the relevant caches. That might explain why so many actions (uninstalling and reinstalling things, or even changing a setting) seem to "fix" the problem. The problem might even be timing-dependent, like the unrelated https://bugzilla.mozilla.org/show_bug.cgi?id=1005640

Unfortunately, I didn't think of saving a copy of my profile before trying the "yum update", so I can't compare the before/after to see what has changed.

**Comment by monkeymagic29** [comment] 2017-08-29 03:35
@gorhill If the issue lies with Firefox client, why is UBO the only one that suffers this kind of error upon update? Decentraleyes updated around the same time window, but it went without a hitch. There's a possibility that all Firefox users won't be able to update UBO again if you don't take a keener look at this. I hope you do.

**Comment by Hrxn** [comment] 2017-08-29 03:59
Which version of Decentraleyes?

**Comment by BananasGoMoo** [comment] 2017-08-29 04:30
I also have this problem, and reinstalling uBo did not fix it. When I press the button on the navbar, the UI does not show up. going back to 1.13.8 was the only thing that worked.

**Comment by MarjaE2** [comment] 2017-08-29 04:45
I have to uninstall and reinstall each time I open Firefox. I have a strobe sensitivity, so need animation-blockers.

**Comment by monkeymagic29** [comment] 2017-08-29 05:00
@Hrxn 1.3.10, which they claimed to have complied with webext and do it in hybrid manner as well, because it's still tagged as legacy by Firefox desktop client.

**Comment by gorhill** [comment] 2017-08-29 05:23
> if you don't take a keener look at this

@monkeymagic29 Read the linked issue carefully: https://bugzilla.mozilla.org/show_bug.cgi?id=1383064#c0

I already keenly investigated and the issue is within Firefox as described. The Firefox devs marked the bug as duplicate of <https://bugzilla.mozilla.org/show_bug.cgi?id=1372750>. I've had my share of frustration with Firefox today, no need to pile more please. I've done my share of work here, the _only_ thing you have to do is follow the recommendations in the release notes.

Locking, because I don't see what else can be added.

**Comment by gorhill** [comment] 2017-08-30 18:01
Please report to `https://bugzilla.mozilla.org/`.

**Closed by gorhill** 2017-08-30 18:01 UTC
