### ISSUE TITLE
Fonts on left side of advanced mode popup are too big

### ISSUE THREAD

**Issue by jdorsay-xenu** [gorhill/uBlock#2086] opened 2016-10-19 20:56 UTC
### Describe the issue

Display issue in popup as seen here.

(https://cloud.githubusercontent.com/assets/21200362/19536842/bd943aca-961b-11e6-9e1f-632e9a5b1edc.png)
### One or more specific URLs where the issue occurs

eg http://www.xenu-directory.net/

[Screenshot(s) for visual issues are **mandatory**]

(https://cloud.githubusercontent.com/assets/21200362/19536842/bd943aca-961b-11e6-9e1f-632e9a5b1edc.png)
### Steps for anyone to reproduce the issue

Using FF developer edition on win 10 pro.

go to uB dashboard, enable "I am an advanced user"

go to FF Options->Fonts and colors, set default size: 24
FF Options->Fonts and colors->advanced
set proportional size: 24
set monospace size:24 
set minimum size: 24 

browse

left click the uBlock button to raise the popup

BTW, the same settings do NOT cause a display issue in uMatrix 0.9.3.6
### Your settings

are listed in the preceding section
- Browser/version: 

FF developer edition on win 10 pro
- uBlock Origin version: 

1.9.12
##### Your filter lists

Default

**Comment by gorhill** [comment] 2016-10-20 11:23
Looks like the setting causing the issue is "minimum size", just changing this setting is enough to reproduce the issue.

(By the way, sorry to not have answered your email, I'm just a horrible person when it comes to answer emails.)

**Comment by gorhill** [comment] 2016-11-05 18:49
Fixed with 446d7fad2e5875e0f6d27b03171520d0ecc7a43b.

**Closed by gorhill** 2016-11-05 18:49 UTC
