### ISSUE TITLE
Small issue with  has()

### ISSUE THREAD

**Issue by mikhoul** [gorhill/uBlock#2042] opened 2016-10-03 03:12 UTC
### Describe the issue

I'm trying to make a filter from the element picker "box" with `has()` and it don't work all `li` tags are hidden instead of only the one's that fulfill the condition.

The goal of the filter is to hide all horizontal "line" that have a "lock" icon and keep only the one's without "lock" icon. ---> http://i.imgur.com/c2rhQ5o.png

Here's the filter:  `##li:has(.cadenas)`

[URL(s) for issue on a specific site are **mandatory**]

**http://ici.tou.tv/a-z**

### Screenshot in which the issue can be seen
I'm not absolutely sure about the meaning of the 2 red colors in the background with the element picker. My logical guess  is the darker red is the target element to be hidden and the lighter red is the the condition that must be fulfilled. Could you confirm me the meaning please ?

http://i.imgur.com/FlkBx47.png

So if I'm correct the ##li is the dark red target to be hidden and the lighter are the the target that don't match the condition `:has(.cadenas)`

My expectation is that  all the row that (and only them) match the condition would be hidden but everything is hidden. All the ##li  are hidden.

Here's a screenshot to show which "parts" should be hidden by the filter:

http://i.imgur.com/FhNHuTV.png

All the horizontal row with a lock icon AKA `:has(.cadenas)` should be hidden but everything is hidden.

I tried to put the filter directly in "my filter" but same results, every row is hidden.

### Your settings

- Browser/version:  Firefox 49
- uBlock Origin v1.9.13b0 

##### Your filter lists

Default filter lists + FRA
-=-=-=-=-=-=-=-=-=-=-=-=-

**N.B.:** It could be me that don't understand correctly the `has()` but I've done other filters with `has()`  that work fine as I expected.

Regards :smile_cat:

**Comment by gorhill** [comment] 2016-10-03 03:49
> It could be me that don't understand correctly the `has()`.

That's it. You should first have make the case the issue is with uBO, not with your understanding.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-10-03 03:49 UTC

**Comment by gorhill** [comment] 2016-10-03 03:53
Here:

    <li>
        <ul>
            <li><span class="cadenas">...</span>

Your filter `li:has(.cadenas) matches two `li` above.
