### ISSUE TITLE
RFE: please add possibility do enable/disable uBlock through its menu/shortcut

### ISSUE THREAD

**Issue by yarda** [gorhill/uBlock#766] opened 2015-09-29 17:07 UTC
It would be nice to have button/shortcut to disable/re-enable blocking for all sites/tabs without storing any exception. Currently it seems the only way is to disable the extension which is clumsy. This could be useful for development or e.g. for some shops affiliate programs where I don't have time to investigate the whitelist, just temporally disable the blocker, buy the item and re-enable it. Sometimes whitelisting the domain is not enough due to various 3rd party providers involved in the affiliation program (e.g. site A opening tab with site B, both needs to be without blocker, but if not in transaction I want B to be fully covered by the blocker). I am sure there will be various other use cases.

**Comment by gorhill** [comment] 2015-09-29 17:34
Duplicate of #167.

**Closed by gorhill** 2015-09-29 17:34 UTC
