### ISSUE TITLE
Ability to disable uBlock 

### ISSUE THREAD

**Issue by Matth7878** [gorhill/uBlock#1111] opened 2015-12-25 16:54 UTC
Would it be possible to have a way to completely disable ublock instead of disabling only for current site ? Sometimes you just want to turn off all filtering and there is no other way (at least in firefox) than disabling addon in the add-ons manager.
=> Recently I purchased a monitor but site wasn't playing nice with ublock. I disabled it for the website but payment was on a secure page which was blocked. I had to disable ublock once again for this page but refreshing forced me to begin anew my command.

**Comment by gorhill** [comment] 2015-12-25 17:10
Duplicate of #167.

**Closed by gorhill** 2015-12-25 17:10 UTC
