### ISSUE TITLE
Logger: Popup which shows the used filter is empty

### ISSUE THREAD

**Issue by alexara** [gorhill/uBlock#2179] opened 2016-11-23 17:10 UTC
### Describe the issue

Clicking on an blocked item on the logger page opens an overlay which shows the filter list in question.
After disabling that filter list and reloading the page, you can still click on the logger page on the item which was blocked before the reload.
However, now the overlay is empty.

### Screenshot in which the issue can be seen

![bildschirmfoto_2016-11-23_17-58-23](https://cloud.githubusercontent.com/assets/13819719/20571347/596e8008-b1a7-11e6-98f9-922813d00c55.png)

### Steps for anyone to reproduce the issue

1. Open a page, where at least one item is blocked by uBO
 e.g. `http://www.continental-reifen.de/fahrrad/service/faq/montagehinweise`
2. Go to the logger and see which filter list is responsible for blocking a specific item
3. Disable this filter list
4. Reload the page
5. Go to the logger and click again on the same blocked item: The overlay is now emtpy. 

### Your settings

- Browser/version: FF 50.0
- uBlock Origin version: 1.9.16

##### Your filter lists

Default

##### Suggestion
- Either 
disable the possibility of clicking on an blocked item where's no filter list known
- OR
keep the filter list stored and show them even after a reload

**Comment by uBlock-user** [comment] 2016-11-23 17:12
Duplicate https://github.com/gorhill/uBlock/issues/1691

**Comment by gorhill** [comment] 2016-11-23 17:41
This was fixed in dev build.

**Comment by gwarser** [comment] 2016-11-24 16:08
I can confirm in Fx 52 uBO 1.9.17rc0

With Anti-Adblock Killer | Reek enabled 
![reekon](https://cloud.githubusercontent.com/assets/886325/20604772/70762492-b268-11e6-90f6-ff8cecb6c6d7.png)

and disbled
![reekoff](https://cloud.githubusercontent.com/assets/886325/20604776/745ff524-b268-11e6-8357-5b2242e9e238.png)

**Comment by gorhill** [comment] 2016-11-24 16:33
@gwarser Did you click on an old Reek's-related log entry *after* disabling Reek's?

**Comment by gwarser** [comment] 2016-11-24 16:45
Yes, `wp.pl` entry.

**Comment by gorhill** [comment] 2016-11-24 17:26
Not something that can be fixed -- uBO reverse lookup filters in memory only -- there is no use case for disabling a filter list and investigating the logger for filters no longer in effect.

**Comment by alexara** [comment] 2016-11-27 20:55
> Not something that can be fixed -- uBO reverse lookup filters in memory only -- there is no use case for disabling a filter list and investigating the logger for filters no longer in effect.

Oh, I actually meant that when I created this thread.

Wouldn't it make sense then to remove the possibility to investigate for a filter list, which is no longer in effect? 
OR
instead of showing an empty popup, show "This request was blocked due a filter list which is no longer available" or something like that.

As it is now, it's confusing

**Comment by gorhill** [comment] 2016-11-28 00:57
> Oh, I actually meant that when I created this thread.

I did not read carefully, I missed this, I had assumed it was related to the solved issue.

Yes, a meaningful message could be displayed.

**Comment by gwarser** [comment] 2016-12-18 17:26
Logger overlay is also empty when cosmetic filter starts with dot.
For example for issue title on this page `.com##.js-issue-title`.
It's OK for `github.com##.js-issue-title` or `com##.js-issue-title`.
![image](https://cloud.githubusercontent.com/assets/886325/21295159/5a3bde3e-c54f-11e6-9917-421f7cdf6f22.png)

**Comment by gorhill** [comment] 2016-12-18 18:05
`.com##.js-issue-title` does not appear to be a valid filter, it does not work with ABP. That it works in uBO is just because of the specific implementation in uBO. Using `com##.js-issue-title` would be a valid filter. Two possibility: I discard such invalid filters, or I accept that they can exist and fix the logger.

**Comment by stonecrusher** [comment] 2017-08-27 23:45
It's not only invalid filters. `\5f` is unicode hex for underscore.

`###\5f __plusone_0` from Fanboy's social blocking list works as well as `###___plusone_0` does. 

Not sure why they use hex replacement for underscore. If it is an error in the list (although blocking works) it would be nice to know what list that item is on when it pops up in the logger. However, it looks intentional because if class/ID begins with underscore, it is always replaced by `\5f ` in that list.

First variation shows empty overlay, second works as intended.

**Comment by joey04** [comment] 2017-10-02 21:29
[I made this patch](https://github.com/gorhill/uBlock/files/1350454/diff.txt) that fixes the blank dialog box. (Note the TODO for making it a proper i18n message.)

Clicking on a rule not found shows this:
![untitled](https://user-images.githubusercontent.com/14959062/31100137-5a4da4be-a796-11e7-87c6-87c7cd7fa06d.png)

It's easy to verify - use methods mentioned before or just comment out one of your own rules after loading the relevant page with the logger open (so the rule is logged, of course). I then toggle the rule enable/disable several times, and the dialog box was correct found/not found each time.

**Closed** 2018-07-22 12:15 UTC
