### ISSUE TITLE
[Bug] uMatrix and uBlock CSP Conflict

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#3468] opened 2018-01-28 12:31 UTC
I am getting error messages from both uMatrix and uBlock saying they are having a CSP network request conflict because of the other, one or the other has this error message displayed.

![capture](https://user-images.githubusercontent.com/16563034/35482041-0cfff99e-0427-11e8-8e25-5dfdc8d3030c.JPG)

I am using the newest uMatrix and uBlock in the newest chrome although, this could be happening in Firefox also but its lightly being displayed in the developer console where I missed it, as there’s no visual problems.

Just an idea but, would it help to delay one of the addons till after the other had finished handling requests, so only one is filtering requests at a time for users who have both installed.

Thanks

**Comment by gorhill** [comment] 2018-01-28 12:44
Duplicate of #1170.

**Closed by gorhill** 2018-01-28 12:44 UTC
