### ISSUE TITLE
Apple Extensions for MacOS / iPad OS

### ISSUE THREAD

**Issue by Flynnsworth** [gorhill/uBlock#3856] opened 2021-09-22 23:04 UTC
Please consider a uBlock Origin “Lite” for Safari now iPad has full extension support.

It would be better than the competition and I would pay.

**Comment by olbrew** [comment] 2021-09-24 16:17
As far as I know Safari for iPad only supports the same WebExtension APIs as Safari for MacOS and uBlock Origin can't be run on either of those because a lot of important APIs are missing.

See https://github.com/uBlockOrigin/uBlock-issues/issues/1123#issuecomment-926733561 for more info.
So this is basically a duplicate of #1123.

I'd love for uBlock to be fully supported on Safari but it doesn't look like it's possible at the moment. Let's hope Apple implements the necessary APIs for its next release.

**Comment by gorhill** [comment] 2021-09-24 16:22
That is not the place to open issue, as pointed out prominently in the issue tracker: <https://github.com/gorhill/uBlock/issues/3726>.

**Closed by gorhill** 2021-09-24 16:22 UTC
