### ISSUE TITLE
Firefox 55.0.2 crashing while playing HD video when uBlock is enabled

### ISSUE THREAD

**Issue by boformer** [gorhill/uBlock#2894] opened 2017-08-24 03:05 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Playing HTML5 Videos in high quality crashes Firefox after a few seconds. YouTube and other providers are affected. The browser freezes, then crashes.
It does not happen when uBlock is disabled.

![grafik](https://user-images.githubusercontent.com/2014500/29647577-20d662dc-888a-11e7-94de-643360c41de9.png)

### One or more specific URLs where the issue occurs

http://community.simtropolis.com/forums/topic/73873-giometry-does-rotary-craft-experiments/ 
http://www.tagesschau.de/multimedia/sendung/ts-21419.html

### Steps for anyone to reproduce the issue

1. Open page with video
2. Switch to highest quality
3. Press play

### Your settings

default settings

- OS/version: Win 10 64 bit
- Browser/version: 55.0.2 (32 bit)
- uBlock Origin version: 1.13.8

##### Your filter lists

(defaults)

- uBlock filters​
- ​uBlock filters – Badware risks​
- uBlock filters – Privacy​​​​​
- ​​uBlock filters – Unbreak​​​​​
- EasyList
- EasyPrivacy
- Malware Domain List​​​​​
- Malware domains
- Peter Lowe’s Ad and tracking server list
- DEU: EasyList Germany

##### Your custom filters (if any)

none

**Comment by gorhill** [comment] 2017-08-24 04:06
Unable to reproduce.

uBO is written in javascript. Javascript is not supposed to crash a browser. Please report to Firefox devs, and submit a crash report to them. I failed to see how this could related to uBO.

**Comment by jspenguin2017** [comment] 2017-08-24 22:08
Actually, JavaScript is able to crash a tab: `var a = []; while(1) { a.push(1); }`
Although no one would intentionally do that, if the script is bugged in a wrong way, it can crash a tab.

**Comment by gorhill** [comment] 2017-08-24 22:47
Yes of course.

Now concerning the issue at hand this is what matters: can you reproduce?

If nobody can reproduce, OP needs to report to Firefox, i.e. back top what I said above.

**Comment by gorhill** [comment] 2017-08-30 18:05
Closing due to lack of evidence uBO itself is the issue.

**Closed by gorhill** 2017-08-30 18:05 UTC
Labels: unable to reproduce
