### ISSUE TITLE
Closing the logger asks Firefox if I want it to close all tabs

### ISSUE THREAD

**Issue by SW1FT** [gorhill/uBlock#429] opened 2015-07-02 08:11 UTC
Self-explanatory title, I'm guessing this behavior is not intended.
You need to launch the logger from the uBlock Origin popup panel, not from the Options on about:addons as it will open the logger in a new tab rather than a new window.
I'm running Firefox 40.0a2 and uBlock Origin 0.9.9.3-dev.5 on Windows 7.

**Comment by gwarser** [comment] 2015-07-02 08:39
On Fx 39 FEBE extension show me dialog:
>Backup on shutdown is ready to run

**Comment by Betsy25** [comment] 2015-07-02 10:35
> Self-explanatory title.
I'm running Firefox 40.0a2 and uBlock Origin 0.9.9.3-dev.5 on Windows 7.

Cannot reproduce here on FF 40.0a2 & UblockO 0.9.9.3-dev5 (Win7-x64)

**Comment by SW1FT** [comment] 2015-07-02 11:19
@Betsy25 From where did you launch the logger?

**Comment by gorhill** [comment] 2015-07-02 11:21
> I'm guessing this behavior is not intended

No it's not. I can't reproduce, and I see nothing in the doc related to this. Firefox interpreting the closing if a single window as the user asking to close all windows is weird.

**Comment by SW1FT** [comment] 2015-07-02 11:25
Weird, if you enable the DOM Inspector, when you close the window you don't get the prompt asking if you want to close all tabs.

**Comment by gorhill** [comment] 2015-07-02 11:46
Ok, I could reproduce if:

- I set default web page at start to "Show a blank page"
- I have at least two (unpinned) tabs opened in the main window

In such case, closing the logger will cause the warning to appear. Agreeing to the warning, the logger window close, and the main window is left open -- as expected.

**Comment by SW1FT** [comment] 2015-07-02 11:49
So this is a browser bug rather than a uBlock Origin bug?

**Comment by gorhill** [comment] 2015-07-02 11:50
> So this is a browser bug rather than a uBlock Origin bug?

I would think yes, since clicking _Quit_ at the warning box does not in fact causes the browser to quit.

**Comment by gorhill** [comment] 2015-07-02 11:52
Note that if I manually detach a tab in a separate window, the warning does not occur...

**Comment by gorhill** [comment] 2015-07-02 12:21
Using uBlock's own background window object fixes the issue.

**Comment by SW1FT** [comment] 2015-07-02 14:20
The latest dev version didn't fix it for me.

**Comment by gorhill** [comment] 2015-07-02 14:24
> The latest dev version didn't fix it for me

So this means that my repro steps had nothing to do woth your case. What are your Firefox settings in the _General_ pane?

**Comment by SW1FT** [comment] 2015-07-02 14:32
What the patch did was, instead of the logger launching in a new window, it launches in a new tab again.


Settings are:
- Open new windows in a new tab
- Do not load tabs until selected

Since I have my FF in Portuguese, those settings most likely aren't written exactly that way.

**Comment by gorhill** [comment] 2015-07-02 14:37
What about:

- "When Firefox starts [ ...  ]"
- [ ] "Warn me when closing multiple tabs"

**Comment by SW1FT** [comment] 2015-07-02 14:41
I don't know where that setting is located at. However, if I have multiple tabs open it does warn me when I try to close FF.

**Comment by gorhill** [comment] 2015-07-02 14:49
I had assumed that since I could reproduce with Linux, the fix for Linux would work on Windows, so I had not tested on Windows. But I confirm it does not work for Windows.

**Comment by gorhill** [comment] 2015-07-02 16:28
I added details of the current issue to a Firefox bug which matches the problem here: <https://bugzilla.mozilla.org/show_bug.cgi?id=644224>.

**Comment by SW1FT** [comment] 2015-07-02 21:02
Probably will never be fixed, it was reported 4 years ago and the comment before yours is also from that time.

**Closed as completed** 2017-09-11 15:52 UTC
Labels: external
