### ISSUE TITLE
Sites with a same, new anti-adblocker

### ISSUE THREAD

**Issue by zymase** [gorhill/uBlock#1505] opened 2016-03-25 19:16 UTC
At least 4 sites which have set a new type of anti-adbmlocker, the same in the following list as they are all handled by a javascript at https://greasyfork.org/en/scripts/18230-clubic-6play-anti-adblock-killer :

www.6play.fr
www.clubic.com
www.passeportsante.net
www.telerama.fr

A bit tougher than usual, obviously.

**Comment by gorhill** [comment] 2016-03-26 12:59
I implemented an idea I have been considering since a while regarding those pesky overlay. The sites above are good test cases -- except for `6play.fr` for which I couldn't see an anti-blocker. The new scriptlet can be used for any site which hide its content with an anti-blocker overlay:

    example.com##script:inject(overlay-buster.js)

Such filters have been created for the sites above.

**Comment by zymase** [comment] 2016-03-26 13:22
Many thanks, gorhill, updated uBlock filters and overlay-buster.js does the job, as always!
I've decided to calm down on my enthusiasm, too many thanks :)
Great, now I can remove the javascript above mentioned.

By the way,
Should another site display this nasty overlay (mainly French perhaps as many are presently joining an anti-adblocker newly created association called Geste.fr), that the user could add them himself in his 'My filters' list or must it be performed by you within the uBlock filters?

The beat goes on!

**Comment by gorhill** [comment] 2016-03-26 13:26
> user could add them himself in his 'My filters' list or must it be performed by you within the uBlock filters?

This can be added by the user for any site, for example:

    example.com##script:inject(overlay-buster.js)

If someone finds that the filter works for a specific site, I am open to add the filter to uBO's own filter list so that all can benefit from it.

**Comment by zymase** [comment] 2016-03-26 13:39
Got it. The mood is _smarter than smarts_!
Surfin' WWW

**Comment by Hrxn** [comment] 2016-03-26 13:50
Works for:

https://thescene.com/

**Comment by zymase** [comment] 2016-03-26 14:10
@Hrxn I don't encounter whatever overlay, nasty or not, on thescene.com

**Comment by gorhill** [comment] 2016-03-26 14:21
> Works for: https://thescene.com/

I don't see any overlay, but I do see a message which asks to disable one's blocker.

The overlay buster solution here works (hopefully) only for overlays which cover the whole page.

**Comment by gorhill** [comment] 2016-03-26 14:25
@Hrxn Try

    ||assets.adobedtm.com$script,domain=thescene.com

See if this works. If so, report to EasyList maintainers.

**Comment by zymase** [comment] 2016-03-26 14:40
Normal I don't encounter what appears to be an adobetm.com intrusion since I have
||adobedtm.com^$third-party found in my Fanboy+Easylist-Merged Ultimate List

**Comment by zymase** [comment] 2016-03-26 15:17
http://www.programme.tv/ : using the filter programme.tv##script:inject(overlay-buster.js) prevents an anti-adblock from appearing even though it doesn't seem to be an overlay (or is it?) but a full-screen page asking to disable the adblocker...

**Comment by gorhill** [comment] 2016-03-26 15:47
Can't see any anti-blocker behavior on `programme.tv` using uBO's default settings.

**Comment by zymase** [comment] 2016-03-26 16:11
> Can't see any anti-blocker behavior on programme.tv using uBO's default settings
Well, looks like, in the process of adding to and removing from default uBO filters a gap appears. I'll have to find which one.

Here's a screenshot of programme.tv message appearing 2-3 seconds afyer the site is loaded : http://hpics.li/f47406b

**Comment by gorhill** [comment] 2016-03-26 16:28
> Here's a screenshot of programme.tv

Ok, reproduced, guess I did not wait long enough. Cookies must be cleared to re-reproduce. The overlay is not that bad really: it can be closed with one click -- thus does not prevent accessing content. It offers an interesting approach to support the site: willfully watch one single 30 sec. ad to support site for one month.

I wouldn't want to prevent this message, but I do frown upon requests to disable a blocker. In this case the filter `programme.tv###zpoption-tuto` would get rid of the suggestion to disable a blocker, while keeping the alternative, less drastic suggestion. In any case, closing the overlay gives access to the site's content, and the cookies prevent the overlay from appearing again in the short term.

**Comment by zymase** [comment] 2016-03-26 16:53
> [...]and the cookies prevent the overlay from appearing again in the short term.

I understand and congratulate your approach, gorhill, yet I won't keep a cookie for the sole purpose of avoiding a pro-ad message. Moreover I am far from a tolerant attitude in the face of ads, not that I'd advocate a radical position but rather in consideration of a lengthy though rational consideration of the ad business, be it small, acceptable, wider or intrusive. Other debate, a smoother approach than mine would maybe participate to a smoother relationship with sites' funding but it'll be without me until the ad business decides to take its responsibilities which are not those of the users.

OK for programme.tv###zpoption-tuto, thanks.

**Comment by brunob** [comment] 2016-03-26 20:47
thx a lot for that patch @gorhill :)

**Comment by Hrxn** [comment] 2016-03-27 03:27
Regarding https://thescene.com/ :

Well, what I get (with default settings) is a 'Please disable your ad blocker' message, white text on blue background, that is shown over the video frame. The video is actually behind there, and if I switch to another tab (before scrolling down!), playback starts and I hear the audio. You can also scroll down then, and see the video in a small frame in the upper left corner, similar to sites like CNN when you scroll down an article while playing a video. So I thought that would qualify as an overlay, or is overlay only full-site only, i.e. when it completely overshadows the site?

`thescene.com##script:inject(overlay-buster.js)` fixed this for me.

`||assets.adobedtm.com$script,domain=thescene.com` just works as well..

**Comment by espress0** [comment] 2016-03-28 11:46
The 'inject' command? Interesting.
Webpage VS uBlock war never changes...

What if I add this to apply to *all* webpages?

##script:inject(overlay-buster.js)

**Comment by Boeak** [comment] 2016-03-29 11:32
Adblock detected on http://www.stream-foot.tv/

The Anti-Adblock message appears randomly on the video reader.

**Comment by Kalpit1** [comment] 2016-04-01 09:06
@gorhill

I'm happy to see that uBlock origin is blocking anti adblockers.

Can we accept in future native support for anti ad block killer instead of using a script manager to block them.

**Comment by Hrxn** [comment] 2016-04-01 15:30
That depends on what the script manager (I suppose you mean extensions for user-scripts like Greasemonkey, etc.?) is actually doing here.

If it's basically just the same as `example.com##script:inject(overlay-buster.js)`, then yes, it should be possible.

**Comment by happysurf** [comment] 2016-04-09 15:42
`navigaweb.net##script:inject(overlay-buster.js)` doesn't work on http://www.navigaweb.net/2016/04/portare-chrome-velocita-massima.html
Any idea?

**Comment by zymase** [comment] 2016-04-09 15:52
@happysurf indeed. But blocking inline scripts for www.navigaweb.net does the trick for the time-being.

**Comment by happysurf** [comment] 2016-04-09 16:04
**@zymase**, I thought I had already tried that setting that already I use in other sites.
Thank you very much.

**Comment by gorhill** [comment] 2016-04-09 16:12
@happysurf That is an alert, not a full page overlay. Just open a new issue at uBlockOrigin/uAssets, I should be able to create an alert buster scriptlet as well.

**Comment by cpaixao** [comment] 2016-05-11 14:00
I am here to report a different and new anti-adblocker system is being used by a BIG brazilian news website:
http://www.folha.uol.com.br/ 
If you try to open an link when you're at http://www.folha.uol.com.br/, you will be redirected to http://www1.folha.uol.com.br/paywall/adblock.shtml?_+the web url you were trying to reach_

uBlock Orign is not getting able to avoid this. Can anyone help?

**Comment by zymase** [comment] 2016-05-11 14:20
> uBlock Orign is not getting able to avoid this
It will if Gorhill puts his hands on it. Nothing is impossible for uBlokO :)

**Comment by gorhill** [comment] 2016-05-11 21:53
Doesn't [this solution](https://forums.lanik.us/viewtopic.php?f=62&t=30262#p93275) work?

**Comment by cpaixao** [comment] 2016-05-12 11:32
@gorhill I am not sure because I don't know exactly how to apply that solution :(

**Comment by zymase** [comment] 2016-05-12 11:50
@cpaixao,
1- click on uBlockO's toolbar button,
2- click on the displayed menu's title (_uBlock origin 1.7.0_),
3- at the top of the displayed page click on _My filters_
4- copy paste 
> ||paywall.folha.uol.com.br^

That's all there is to it.

The rule works fine, as akways.

**Comment by TPS** [comment] 2016-05-14 20:26
@gorhill Just as a meta-question: Is this technically out-of-scope for uBlock _itself_?  Shouldn't be handled @ @reek's https://github.com/reek/anti-adblock-killer/issues, rather than @ https://github.com/uBlockOrigin/uAssets/issues?

**Comment by gorhill** [comment] 2016-06-24 11:48
Can you guys confirm that the filter:

    6play.fr,clubic.com,passeportsante.net##script:inject(overlay-buster.js)

Is no longer needed? I disabled _"uBlock filters"_, and there were no overlays. I rather not accumulate unneeded filters.

**Comment by zymase** [comment] 2016-06-24 11:58
After having disabled "uBlock Filters" I've just tested 

> play.fr,clubic.com,passeportsante.net

 and no overlay appeared as well.

**Comment by gorhill** [comment] 2016-06-24 12:06
Thanks.

**Closed by gorhill** 2016-06-24 12:06 UTC

**Comment by zymase** [comment] 2016-06-24 12:16
Sorry for re-opening the thread but I was wondering what happens to filters I've included in _My Filters_ calling _overlay-buster.js_ (or future sites I'd like to be filtered with)
> programme.tvcom,nasdaq.com,bouyguestelecom.fr,downloadcrew.com,justanswer.com,mozilla.org##script:inject(overlay-buster.js)

**Comment by gorhill** [comment] 2016-06-24 12:17
`overlay-buster.js` is there to stay, it's used for other cases.

**Comment by zymase** [comment] 2016-06-24 12:21
OK, I was afraid overlay-buster.js was removed as a whole.
Fine. Thanks
