### ISSUE TITLE
ublock is activating too late

### ISSUE THREAD

**Issue by emadmahdi** [gorhill/uBlock#3579] opened 2018-03-07 01:46 UTC
Thank you for this great work ...

I am not sure if the issue i am reporting is related to Firefox or to your uBlock ... i can describe it as follows ... when i start the browser and then try to access "olpair.com" ... then your add-on works perfectly and filter properly ... but when i access the same url using a desktop shortcut while Firefox is not running ... then the filtering of your uBlock does not work at all ... while if i started Firefox then click on the same desktop shortcut then your uBlock works perfectly ...

It looks like your add-on is staring to work after loading the desktop shortcut which causes the url not to be filtered by your uBlock add-on ... as i said ... i am not sure if this problem is caused by your uBlock being too late activating or from Firefox being too quick in loading the url !!!!

Thanks again ...

**Comment by emadmahdi** [comment] 2018-03-07 03:07
i got a temporary solution ... by using the below shell script to launch Firefox then after 3 seconds will launch the URL "olpair.com" ... please let me know if you have any other ideas ...

start /B C:\"Program Files\Firefox Developer Edition"\firefox.exe
waitfor /T 3 pause
start /B C:\"Program Files\Firefox Developer Edition"\firefox.exe http://olpair.com

**Comment by gorhill** [comment] 2018-03-07 11:32
Duplicate of #1327.

**Closed by gorhill** 2018-03-07 11:32 UTC
