### ISSUE TITLE
Network filtering not working in latest Firefox Nightly (webext)

### ISSUE THREAD

**Issue by HopefullyNotTaken** [gorhill/uBlock#2684] opened 2017-06-06 13:10 UTC
### Describe the issue
With the latest Firefox Nightly, network filters are no longer being applied. Cosmetic filtering, however, appears to be working just fine.

### Steps for anyone to reproduce the issue
1. Download the latest version of Firefox Nightly.

2. Create a new profile.

2. Install any version of uBlock Origin. **Make sure it's the webext**.

3. Go to any site and create a rule to block a resource using the network filter ( || ).

4. Open the Network Monitor on said site and reload. Notice how the resource still shows up in the Network Monitor and visually despite there being a rule in uBlock Origin to block it.

### Your settings
Tried on a clean profile so all settings are at default.

- OS/version: Arch Linux
- Browser/version: 55.0a1 (2017-06-05) (64-bit)
- uBlock Origin version: 1.12.5rc1 but tried older versions as well ( 1.12.5rc0,  1.12.4,  1.12.2,  1.12.1,  1.12.0,  1.11.4,  1.11.2,  1.11.0,  1.10.6)

##### Your filter lists
Default.

##### Your custom filters (if any)
None.

**Comment by gorhill** [comment] 2017-06-06 13:49
> latest Firefox Nightly 

Why report the issue here? If using latest Nightly causes uBO to stop working, then in all likelihood  isn't the issue with Nightly?

**Comment by gorhill** [comment] 2017-06-06 14:07
If I comment out the code adding `ws://*/*` and `wss://*/*` to `onBeforeRequest.addListener`, it seems to "fix" the issue.

This use to cause a warning at the console at most without causing uBO to stop functioning. So something changed in Nightly to cause uBO's onBeforeRequest listener to be completely ignored if declaring `ws`/`wss` URL patterns.

Related: <https://bugzilla.mozilla.org/show_bug.cgi?id=1367478>.

**Comment by gorhill** [comment] 2017-06-06 14:11
For the time being, I'm going to stop building the webext version of uBO, there are too many serious issues now with it. I will resume when things stabilize, it's unclear whether it is expected things will have to change in uBO or whether thing will be fixed in webext.

**Closed by gorhill** 2017-06-06 14:11 UTC

**Comment by shellye5** [comment] 2017-06-06 15:34
Thank you for the explanation and quick workaround :) @gorhill

**Comment by gorhill** [comment] 2017-06-06 15:50
I just recevied a Nightly update which appears to solve the issue reported here. However the issue with uBO's auxiliary pages is not solved, and this quite cripples the webext version of uBO, so for now the webext version won't be build anymore until things improve, as I just do not have the time to deal with all reports and there is no quick fix. Whoever really want the webext version badly despite the problems can just git clone and build it themselves.

**Comment by andymckay** [comment] 2017-06-06 22:26
Is there an issue for the auxiliary pages? Sorry, not sure what that is.

**Comment by gorhill** [comment] 2017-06-06 22:54
Problem which appeared lately, discussed here: <https://bugzilla.mozilla.org/show_bug.cgi?id=1368152#c15>.

I use "auxiliary pages" to refer to the dashboard, logger principally, but also others such as the warning when a document is blocked, advanced settings, asset viewer, or even the popup panel-in-a-tab. With legacy version, these would be like:
- chrome://ublock0/content/dashboard.html
- chrome://ublock0/content/logger-ui.html
- chrome://ublock0/content/advanced-settings.html
- chrome://ublock0/content/asset-viewer.html?url=easyprivacy

Etc.

**Comment by andymckay** [comment] 2017-06-06 23:53
Thanks.

**Comment by gorhill** [comment] 2017-06-24 21:01
I brought back the hybrid-webext build, since it works as expected with Firefox 54.

**Comment by shellye5** [comment] 2017-06-25 11:35
webext version still uses high disk , and slows down startup
seems like this bug is affecting it too.
@gorhill can you look into it? because the performance is low 

https://bugzilla.mozilla.org/show_bug.cgi?id=1371255

**Comment by gorhill** [comment] 2017-07-08 16:34
@andymckay Any thoughts on whether I should just go ahead and push the webext-hybrid to the dev channel on AMO?

**Comment by andymckay** [comment] 2017-07-11 23:04
Sorry, I'm not sure what your requirements are for that and I'm a bit biased on this point, so you probably wouldn't want to take my advice.

**Comment by shellye5** [comment] 2017-08-27 05:47
Just a PSA to stop pushing beta update 1.13.11rc0 to users as it might break their settings


the webext in beta 1.13.11rc0 on AMO
breaks filters/settings if user has a custom  list added

settings

(https://1drv.ms/t/s!AuafaQl91miSbfRJ-rO2gqv4SLI)


Import the attached settings, update lists and check storage size(will be in MBs)
now restart and
just add any filter list and restart -purge-update and storage size is 1kb and settings/lists broken,
delete the added filter apply and works again but with restart before deleting the added filter causes 
the same problem again(Basically cannot use other filters )

try adding 

https://www.kiboke-studio.hr/i-dont-care-about-cookies/abp/

or any other 

https://github.com/collinbarrett/FilterLists

The NON-WEBEXT works fine in Palemoon/ESR

@gorhill can you please add ADGuard's Filter-lists(english/privacy/annoyance/etc) as many of US prefer theirs over more popular ones please.

**Comment by gorhill** [comment] 2017-08-27 09:54
That error is not uBO's code, report to bugzilla please.

**Comment by shellye5** [comment] 2017-08-27 11:30
@gorhill  against what should the bug be filed? 

So till it's fired the webext uBo will be broken?

**Comment by gorhill** [comment] 2017-08-27 12:23
It's not broken for me. The error:

> TypeError: JSON.serialize is not a function ExtensionStorage.jsm:60

Is Firefox's code. I don't get this error, using Nightly 57.0a1 (2017-08-26) (64-bit).

**Comment by shellye5** [comment] 2017-08-27 12:33
@gorhill I mentioned that using 32bit builds will test in today's build,

can you please try with a VM or 32 build with 32bit FF and 2gb of ram?

Also can you file the bug(if you can reproduce the error) as you know the details of FF

**Comment by gorhill** [comment] 2017-08-27 12:39
What is easier to test is for you to un-check all the following lists:

- EasyList
- EasyList without element hiding rules
- EasyPrivacy
- Fanboy’s Enhanced Tracking List
- Fanboy’s Annoyance List
- Fanboy’s Social Blocking List

These are all parts of Fanboy Ultimate, no point enabling them. Even if uBO discards duplicates, it still has to parse/load to find out what is duplicate, and loading all these redundants lists is not cheap CPU- and memory-wise. See if this makes your issue go away.

**Comment by shellye5** [comment] 2017-08-27 12:42
@gorhill okay doing a clean install again and just setting up with a few, what else can be helpful to you for debug?

**Comment by gorhill** [comment] 2017-08-27 12:45
No need to clean install, I just wanted to see if un-checking the above lists solved your issue. If yes, this would have confirmed your issue is related to storage size.

**Comment by shellye5** [comment] 2017-08-27 13:12
@gorhill 
Sorry missed you comment .

DID a clean install and found out 3 more things.

1> This happens only on 32builds of firefox even with default filter, just when the total size of filters or storage reaches around 30-35 mb,
uBo or firefox reverts storage size to 1kb(on () is present in it)
RAM/Disk/CPU usage goes as high as 700-1100mb during this process(have 4gb as page file too) so memory limitaion should not be a problem
but it looks that way? 
please file  a bug as IDK about this.

2> compared to leagcy verion using with Palemoon & Firefox ESR52 this issue never happens,
just for testing went with storage size upto 60-65 mb and no issues.

3> In WebEXT version there is high disk/cpu/ram usage too especially when updating filters

(SQlite in legacy was using chunks? because  data is added in KBs eg total size 5m->new update list->add 500KB update to DB->new size=5.5mb,
but in WEBEXT stores all in ram then writes to disk everytime so for eg:
30mb->uncompressed to ram->write full uncompressed data to disk->new size 40mb->uncompressed to ram->write full uncompressed data to disk->new size 50mb).

This is very inefficient don't you think?
Updating filters in backgroung janks the UI and you can see that in ram/disk/usage under taskmanager, it goes as high as 1.8gb(have 4gb as page file too)
& this is with the default lists + ignore cookies list.

**Comment by gorhill** [comment] 2017-08-27 14:46
I reported your observation here: <https://bugzilla.mozilla.org/show_bug.cgi?id=1371255>.

**Comment by shellye5** [comment] 2017-08-27 15:05
Thank you ! @gorhill Hoping it gets fixed before FF57 lands .

Do any thing else is needed to debug?
Should attachments be added there?

**Comment by gorhill** [comment] 2017-08-28 15:27
I added new comments to <https://bugzilla.mozilla.org/show_bug.cgi?id=1371255>.

Bottom line is that it's quite a serious issue with Firefox 55, and I don't see any workaround for uBO.

**Comment by shellye5** [comment] 2017-08-28 18:23
@gorhill  can you revert and use ublock0.sqlite as storage as recommended in 

https://bugzilla.mozilla.org/show_bug.cgi?id=1371255#c11

> If you want resource efficiency, use IndexedDB. storage.local is not designed for storing huge amounts of data.

like you said

> The issue here is concerning for uBlock Origin, since there is a webext (embedded) version (1.13.10) on the verge of approval on AMO, which means the reported issue here is likely to start to affect a lot of users once it becomes available on AMO.

**Comment by gorhill** [comment] 2017-08-28 18:40
He is not recommending to use sqlite API, that is a legacy API which use will not be allowed in FF57.

He is recommending to use indexedDB. This will have to be the fix, but as said it's not trivial, and it's the 1st time I ever used this API, so I still have to learn how it works.

It quite bothers me to learn just _now_ from bugzilla that one shouldn't use `browser.storage.local` for storing "huge amounts of data" -- nowhere was this ever mentioned, and there is no such issue with Chromium. I [suggested that the limitation should be officially documented](https://bugzilla.mozilla.org/show_bug.cgi?id=1317797#c8).

I will be working to migrate the cache storage to indexedDB. Just keep in mind I am not a paid dev working full time on this project, so I don't know when I will have something ready.

**Comment by shellye5** [comment] 2017-08-28 19:06
@gorhill thank you and as long as the performance of index db is similar too sqlite api the issue should resolved.

please keep up in the loop how things go.

**Comment by gorhill** [comment] 2017-08-28 19:13
Looking at the files generated by Firefox when using indexedDB, I can confirm that the API uses sqlite behind the scene.

**Comment by gorhill** [comment] 2017-08-28 19:20
I just recall @nikrolls using indexedDB to address a storage issue with Edge. If I can reuse this that should help a lot to get something working sooner: <https://github.com/nikrolls/uBlock-Edge/blob/master/platform/edge/vapi-background.js#L70>.

**Comment by andymckay** [comment] 2017-08-28 20:42
We want to get the API in Firefox faster and we'll probably do so by using an indexedDB backend at some point. The amount of data and frequency of data storage is something that surprised us. For example the Chrome docs do say how its "not a big truck". But the simple fact is people are storing a large amount of data there and quite regularly, so we've got to get it faster.

I don't think we'll be able to do that in time for Firefox 57, there's a lot happening and its a risky patch for Firefox.

I'm curious what % of your users you think this might affect. For AdBlock Plus we found it was an edge case where people had a large amount (say 60MB) of filters set up. Wondering if its similar.

**Comment by shellye5** [comment] 2017-08-28 20:45
@gorhill So It's ublock0.sqlite that will be used in dev builds?
so basically it's the legacy version? 

**Mozilla should have documented it.**

_So the performance should be same as legacy version?_

Sorry to bug you so much but this is my way of contributing and making things better

**Comment by gorhill** [comment] 2017-08-29 22:56
@shellye5 You may want to give a try to [1.13.11rc1](https://github.com/gorhill/uBlock/releases/tag/1.13.11rc1), see if this fixes your issue.

**Comment by shellye5** [comment] 2017-08-30 04:19
@gorhill thanks and yes going to test it now!

Can you elaborated on other things asked just before your last comments? please

https://bugzilla.mozilla.org/show_bug.cgi?id=1313401 will affect this 1.13.11rc1?

**Comment by shellye5** [comment] 2017-08-30 05:10
@gorhill Did a quick test and found a few things which you need to know about.**

_extension-data is used as storage in legacy & has only one file(which is compressed)_
_webextensions used browser-extension-data\uBlock Storage.js uncompressed file._

1.13.11rc1 takes a while for migration,
and **the filesize is double of storage.js!!** _let alone the size of legacy version which was fairly small.

eg say 12mb in legacy- 30mb in storage.js- 95mb in new indexedDB,

Now settings are stored in -browser-extension-data\uBlock Storage.js
& filters in storage\default\moz-extension+++6a4e2ef8-e974-4cda-8cb9-e703d0900d68\idb\ ublock.db

But it's not ideal so can they be a single file just like legacy version in extension-data? It's better and simpler, easier to backup(local backup & sharing to multiple pc w/o downloading again).

When starting FF uBo takes a bit more time to initialize and open dashboard is slow and uses high CPU. 
can you look into these_

Rest looks good in the short testing, will test more thoroughly and let you know.

**Comment by shellye5** [comment] 2017-08-30 05:49
@gorhill there seems to be a huge regression in page loading times in webext 1.13.11rc1,

Just open 10-12 bookmarks look at the loading times and now switch tabs..
Seems 1.13.11rc1 is delaying or causing a delay in performance, will test it in FF56 so verify.

**Comment by shellye5** [comment] 2017-08-30 06:51
@gorhill Cpu usage at startup halts the browser for good 30-60 seconds,
Filters start getting updated at random startups even if you update them manually.

Page loading times have gone up significantly and opening multiple pages at once makes it painfully slow.

**Comment by gorhill** [comment] 2017-08-30 12:11
Please, bring your issue to Mozilla, there is nothing I can do, uBO is merely using indexedDB.

Locking this issue because it's better to bring your specific issue to Firefox devs.
