### ISSUE TITLE
'Ctlr-click' text hint in Element picker mode should be 'Cmd-click' for macOS

### ISSUE THREAD

**Issue by z0rc** [gorhill/uBlock#2338] opened 2017-01-25 14:34 UTC
### Describe the issue
Right now hint next to 'Cosmetic filters' says `Click, Ctlr-click`, this is true for Windows and Linux, but on macOS `Ctlr-click` doesn't work as expected, if brings up a Firefox context menu. You actually have to use `Cmd-click` to archive the same result as `Ctrl-click` on Linux.

### One or more specific URLs where the issue occurs
N/A

### Screenshot in which the issue can be seen
![screen shot 2017-01-25 at 16 27 23](https://cloud.githubusercontent.com/assets/787519/22294383/d35390d4-e31b-11e6-97bb-f11bc3d4d6ca.png)

### Steps for anyone to reproduce the issue

1. Switch to element picker mode
2. Select anything
3. Observe 

### Your settings
- Browser/version: Firefox Dev Edition (52.0a2)
- uBlock Origin version: 1.10.4

##### Your filter lists
N/A

##### Your custom filters (if any)
N/A

**Comment by Snapy** [comment] 2017-01-25 16:15
Already [fixed](https://github.com/el1t/uBlock-Safari/releases/tag/1.10.5b9).

**Comment by gorhill** [comment] 2017-01-25 16:52
Fixed for Safari, but not for other browsers on MacOS.

**Comment by gorhill** [comment] 2017-01-25 23:54
Duplicate of #614.

**Comment by uBlock-user** [comment] 2017-01-26 12:32
That fix won't work if the uBlock-Safari repo inherits this repo's changes with every release, so the fix has to be made in the upstream repo itself.

**Comment by sn0wyfall** [comment] 2017-02-15 09:17
@gorhill Why don't you close this issue then?

**Closed** 2017-02-15 13:49 UTC
Labels: duplicate
