### ISSUE TITLE
2 different popup filtering methods

### ISSUE THREAD

**Issue by jo2dan23** [gorhill/uBlock#1561] opened 2016-04-13 16:36 UTC
hi. i just realized yesterday that there is two different methods of blocking popups. i didn't know where to look in the documentation for this. but if i set block all popups from my rules then go to eastbay.com scroll to button and click the pinterest icon it will allow the popup. but if i add $popup,third-party to my filters/static it blocks it

**Comment by anewuser** [comment] 2016-04-13 16:43
Please close this issue and read this carefully before posting here again: [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

> For support/discussions, there is [Mozilla Discourse](https://discourse.mozilla-community.org/t/support-ublock-origin/6746).

**Comment by RoxKilly** [comment] 2016-04-13 18:47
Maybe the OP thought this is the appropriate forum because s/he thinks s/he may have found a bug (s/he expects blocking all popups to do just that, not allow some popups that can be blocked with the `$popup,third-party` filter).

**Comment by anewuser** [comment] 2016-04-13 19:04
@RoxKilly There's a template for reporting bugs. He/she consciously ignored and deleted it, which gives him/her no right to expect an answer from the developer.

**Comment by gorhill** [comment] 2016-04-14 00:03
By design: the no-popups switch is very broad, and in such case it just does not make sense to block popups arising from the user clicking a link -- in such case the popup is deemed legitimate.

**Closed by gorhill** 2016-04-14 00:03 UTC
