### ISSUE TITLE
uBlock 1.13.10 installed - but no activeted

### ISSUE THREAD

**Issue by BogusCurry** [gorhill/uBlock#2940] opened 2017-08-31 05:13 UTC
Hello ;D
Since yesterday is uBlock in my firefox 55.0.3 under Win7 64bit not more activeted. I have no idea what is the problem, no errormessages.

Greetings

Bogus

**Comment by badonkadong** [comment] 2017-08-31 06:19
Same here, Firefox moved to a new Add-on API, more like installing an app in android managing all it's permissions, uBlock needs to update the Add-on to use the new API

**Comment by gwarser** [comment] 2017-08-31 06:26
https://github.com/gorhill/uBlock/releases/tag/1.13.10

**Comment by irule2day** [comment] 2017-08-31 07:56
Update to [Version 1.13.11rc0](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/1.13.11rc0). This should fix the broken problem. I was having trouble with filter lists not saving on Version 1.14.3b0, so I don't recommend that.

**Comment by DeadNumbers** [comment] 2017-08-31 09:14
![_2017-08-31_12-10-49](https://user-images.githubusercontent.com/9416005/29915853-b51123ea-8e45-11e7-9178-bd7eeb65bbbf.png)
And in latest version have no link to settings.

**Comment by ddddavidmartin** [comment] 2017-08-31 10:02
> Read this: https://github.com/gorhill/uBlock/releases/tag/1.13.10

Thanks @gwarser! Those instructions worked for me.

**Comment by BogusCurry** [comment] 2017-08-31 10:54
Thats great, thanks for the fast fix ;D
I will test it ;D

Have a nice Day ;D

**Comment by Chema22R** [comment] 2017-08-31 11:30
Great, it worked for me. Thanks a lot.

**Comment by gorhill** [comment] 2017-08-31 12:16
Duplicate of #2909.

**Closed by gorhill** 2017-08-31 12:16 UTC

**Comment by gorhill** [comment] 2017-08-31 12:19
@irule2day 

> I was having trouble with filter lists not saving on Version 1.14.3b0

Can you be more specific? Did you check _"Always use private browsing mode"_ in Firefox preferences?

**Comment by gorhill** [comment] 2017-08-31 13:37
@irule2day 

That could be your issue: <https://bugzilla.mozilla.org/show_bug.cgi?id=1371255#c21>.

There is nothing I can do. I already spent a good amount of time doing [what I was told I should do](https://bugzilla.mozilla.org/show_bug.cgi?id=1371255#c11).

At this point I can only suggest to people with Firefox 32-bit to stay on 1.13.8, or optionally install `uBlock.firefox.xpi` (legacy version) from [Releases](https://github.com/gorhill/uBlock/releases) section.
