### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [gorhill/uBlock#2079] opened 2016-10-17 18:19 UTC
You should consider signing git commits & releases.
- [onionshare#221 (comment)](https://is.gd/7vU4oK)
- It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
- Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
- And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by gorhill** [comment] 2016-10-17 18:24
Essentially duplicate of #2027.

**Comment by rugk** [comment] 2016-10-17 18:48
No, it's not. Signing files (or git keys) and calculating hashes of files to put them in the release notes, are fundamentally different things.

Thus please reopen this issue.

**Comment by gorhill** [comment] 2016-10-17 19:27
I will have to read about this.

**Comment by Snapy** [comment] 2017-09-19 20:08
@gorhill The issue can be closed since you're doing it since some time.

**Comment by gorhill** [comment] 2017-09-19 20:29
@Snapy That's right, somehow I missed this one. Thanks.

**Closed by gorhill** 2017-09-19 20:29 UTC
