### ISSUE TITLE
extension failed to modify the response header

### ISSUE THREAD

**Issue by haze2422** [gorhill/uBlock#3246] opened 2017-11-18 18:07 UTC
- OS/version: Win7 SP1 x64
- Browser/version: Chromium 64.0.3259.0 (64-bit)
- uBlock Origin version: 1.14.19.7

![bug](https://user-images.githubusercontent.com/15184981/32983366-f494b902-cc9b-11e7-8196-e27d79656769.png)

**Comment by gorhill** [comment] 2017-11-18 19:13
Duplicate of #1170.

**Closed by gorhill** 2017-11-18 19:13 UTC
Labels: duplicate
