### ISSUE TITLE
Advanced uBlock menu clipped in Firefox Menu

### ISSUE THREAD

**Issue by JiDoan** [gorhill/uBlock#3127] opened 2017-10-13 04:40 UTC
### Describe the issue
If "I am an advanced user" is checked and uBlock is in Firefox's addon menu, you cannot access most of the control panel. Attached is a screenshot.

### One or more specific URLs where the issue occurs
No URL / Firefox XUL

### Screenshot in which the issue can be seen
![capture](https://user-images.githubusercontent.com/2526517/31530462-89ff1984-af95-11e7-9473-5ec168df3635.PNG)

### Steps for anyone to reproduce the issue
1. Enable "I am an advanced user"
1. Move uBlock to Firefox's addon menu by right clicking uBlock and clicking "Move to Menu"
1. Attempt to open uBlock

### Your settings
1. "I am an advanced user"
1. uBlock in addon menu

- OS/version: Win 10 / macOS 10.12
- Browser/version: Firefox ESR 52.4.1
- uBlock Origin version: v1.14.14

##### Your filter lists
Default

##### Your custom filters (if any)
N/A

**Comment by Hrxn** [comment] 2017-10-13 05:54
Is this a 3rd-party extension?

**Comment by JiDoan** [comment] 2017-10-13 06:09
Not a third party extension. Just right click any toolbar icon and you should see a "Move to Menu" button. I see this option even in Firefox Safe Mode. You can also use the ["Customize" feature](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars) and drag icons into the menu that appears when in editing mode.

**Comment by Hrxn** [comment] 2017-10-13 06:17
Ah, I see what you mean.
I was a bit confused by the icons displayed in your screenshot, with that custom spacing etc. But you're using Firefox ESR, and this version still includes the Tab Groups, right?

Okay, so this is the normal Firefox Australis main menu. Not sure if this can be fixed in a viable way at all, because I assume that the width of the menu is a hard limit.
Second, with Firefox 57 they changed the design again (Photon), with a completely different main menu.
And I think this new menu does not support any extension-like modifications as you did here.
So, again, this raises the question if this can be fixed at all, or rather if it's worth to address it..

**Comment by JiDoan** [comment] 2017-10-13 06:24
Even with a fresh Firefox 52.4.1 profile, the issue is still there so I do not think it is any customization that I have added.

![untitled](https://user-images.githubusercontent.com/2526517/31532820-50dc3826-afa4-11e7-8e7d-5afbc1951891.png)

**Comment by JiDoan** [comment] 2017-10-13 06:28
The issue also appears on Firefox 57 beta with a fresh profile, so I think if you fix the issue there the issue will be fixed here too. Perhaps just opening up uBlock in a separate window if advanced mode is on?

![screen shot 2017-10-12 at 11 26 32 pm](https://user-images.githubusercontent.com/2526517/31532936-f1ac252c-afa4-11e7-85e1-7734ab904e19.png)

**Comment by gwarser** [comment] 2017-10-13 10:07
Duplicate of https://github.com/gorhill/uBlock/issues/2809

**Closed** 2017-10-13 11:52 UTC
Labels: duplicate
