### ISSUE TITLE
uBlock Origin v1.13.9rc3 broke 'My Filters' list

### ISSUE THREAD

**Issue by BondiBear** [gorhill/uBlock#2883] opened 2017-08-17 13:54 UTC
Going from rc2 to rc3 caused items in 'my filter' to no longer be applied.
Created filter items previously listed are not applied, but re-adding the same items causes the filter to work, despite the old identical item already being there. Very strange.

FF55.0.2 64
uBlock Origin v1.13.9rc3

**Comment by gorhill** [comment] 2017-08-17 13:57
Duplicate of #2882.

**Closed by gorhill** 2017-08-17 13:57 UTC
Labels: duplicate
