### ISSUE TITLE
"Block Element" option on the right click menu doesn't appear when clicked on an iframe

### ISSUE THREAD

**Issue by rjkpa** [gorhill/uBlock#2021] opened 2016-09-23 18:11 UTC
**Issue** - "Block Element" option on the right click menu doesn't appear when clicked on an iframe.

**URL** - http://www.dnaindia.com/money/report-airtel-wards-off-reliance-jio-s-threat-offers-4g-data-at-rs-50-2258090

**Screenshot** - http://i.imgur.com/kd8LRvT.jpg

**Steps To Reproduce** - 1) Visit any url where iframes are loaded. for example - http://www.dnaindia.com/money/report-airtel-wards-off-reliance-jio-s-threat-offers-4g-data-at-rs-50-2258090

2) Scroll down a bit where a blank white space appears, like in the above linked image here - http://i.imgur.com/kd8LRvT.jpg

3) Right click with your mouse on it.

**Expected Behavior** - Block Element option would appear.

**Actual Behavior** - Block Element option does NOT appear.

**Settings**

- Browser/version: Chromium 55 
- uBlock Origin version: 1.9.4

**Filter lists** - Default Only

**Custom filters** (if any) - None

**Comment by gorhill** [comment] 2016-09-23 18:16
Duplicate of #1744.

**Closed by gorhill** 2016-09-23 18:16 UTC

**Comment by rjkpa** [comment] 2016-09-23 18:26
I already have my own work around, what I want to know is that is it going to get fixed anytime soon OR will we have to use workarounds ?
