### ISSUE TITLE
[DUPLICATE+SOLVED] Firefox theme makes element picker mode unusable

### ISSUE THREAD

**Issue by Raijukami** [gorhill/uBlock#1606] opened 2016-05-03 06:50 UTC
### Describe the issue
I have a firefox theme (http://killhellokitty.deviantart.com/art/Cloak-3-20-5-04292016-603341133 the chrome folder from here to be exact). The problem is that when I try to hide an element everything goes black and I can't see anything, so picking an element is hard if not impossible. I do know this is the cause because I created a spare profile for firefox to test it out and it seems that the theme (works without it) is the problem (no other addons were installed on that test profile of course).

### Screenshot in which the issue can be seen
http://tinypic.com/r/2cy1ifm/9

### Steps for anyone to reproduce the issue
1. Have a firefox profile
2. Install that theme or any other.
3. Install ublock.
4. Try to hide an element.

- Browser/version: Firefox 46.0
- uBlock Origin version: 1.7.0

##### My filter lists
The default, I tried on a fresh install after all.

##### A side question
In the settings, at Default behavior why can't you select to stop pop-ups by default? Or is it somewhere else?

**Comment by gorhill** [comment] 2016-05-03 11:58
Duplicate of #826, solution at <https://github.com/chrisaljoudi/uBlock/issues/806#issuecomment-74438771> (solution is in there somewhere). User styles override web pages styles, so you will need to change this on your side, and possibly ask the maintainer of your theme to make it uBO aware.

> why can't you select to stop pop-ups by default?

I didn't really see the need, popups are usually a pest on some sites only, legitimate on others. To block all popups everywhere, you can manually enter the rule `no-popups: * true` in the _My rules_ pane in the dashboard.

**Comment by Raijukami** [comment] 2016-05-03 12:26
Oh, sorry for creating a duplicate. I will see what I can do about this then.
Thank you for the popup rule and for the fast reply to the issue. 

P.S. I really like this addon and it not only replaces Adblock Plus but also Element Hiding Helper for Adblock Plus and Adblock Plus Pop-up Addon (so even less memory usage). Even better, it compliments NoScript. Really glad to have tried it out. Thank you kind sir for your work.

**Closed** 2016-05-03 12:52 UTC
