### ISSUE TITLE
Microsoft Edge browser support missing

### ISSUE THREAD

**Issue by Xemanth** [gorhill/uBlock#1488] opened 2016-03-20 11:10 UTC
Hi,

Edge browser extension support has been opened in the latest (17.3.2016) insider fast ring build 14291 http://changewindows.org/build.php?id=117

Any chance we could get uBlock Origin working in Edge?

**Comment by gorhill** [comment] 2016-03-20 11:21
Duplicate of #1486.

**Closed by gorhill** 2016-03-20 11:21 UTC
