### ISSUE TITLE
Tripwire Enterprise does not work with ublock origin, even if site is whitelisted

### ISSUE THREAD

**Issue by inf0rmix** [gorhill/uBlock#3167] opened 2017-10-24 10:03 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
We have a problem with ublock origin with our tripwire enterprise installation. When ublock is installed and the site is even whitelisted. All created windows do not produce any output. When we disable or uninstall ublock origin, the application works perfectly.

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

Internal site
Enterprise product
utilizes many wondows to its tasks.

### Steps for anyone to reproduce the issue

1. install ublock
2. login to tripwire enterprise
3. Generate a report or try to promote FIM changes

Results:
* no reports get generated (the progessbar just runs endlessly)
* no files get promoted
* no changes can be made - the application runs in endless loop

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Firefox on ubuntu zesty
- Browser/version:  Firefox 56.0 (64-Bit)
- uBlock Origin version: uBlock Origin v1.14.16

##### Your filter lists

default installation of ublock - no lists adjusted

##### Your custom filters (if any)

no custom filters

**Comment by mapx-** [comment] 2017-10-24 10:08
bugs in FF 56. You should install FF 57.

Read: https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext

**Comment by gorhill** [comment] 2017-10-24 10:23
> Internal site
> Enterprise product

Sorry, nothing I can do without a case I can reproduce on my side. You will need to investigate on your side and pinpoint what is failing in uBO exactly.

There are still issues with WebExtensions with FF56 -- see the link posted my @mapx-. For example, try with another blocker such as Adguard or Privacy Badger, and see if you still have the issue. Also,, try with FF57 and see if you still have the issue.

Closing as _Unable to reproduce_ because it's an impossible to investigate issue.

**Closed by gorhill** 2017-10-24 10:23 UTC
