### ISSUE TITLE
Reversing changes made with the Element Picker

### ISSUE THREAD

**Issue by HubJ** [gorhill/uBlock#1630] opened 2016-05-13 23:04 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Sometimes, after using the Element Picker to block an element on a particular site, I return to that site, and decide that I'd now like to have that element made visible. 

How would I do that?

### One or more specific URLs where the issue occurs
All URLs
[URL(s) for issue on a specific site are **mandatory**]
All sites
### Your settings
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Firefox ESR 41.1.1 + all versions of FF ESR 38
- uBlock Origin version: 1.7.0 + all prior versions

##### Your filter lists
Default
[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]
Default
##### Your custom filters (if any)
None

**Comment by IDKwhattoputhere** [comment] 2016-05-13 23:13
> For support/discussions, there is Mozilla Discourse.

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md

> Once you click the Create button, the element picker will add the necessary tokens to ensure the filter apply only to the current web site, **will add it to your custom list of filters** and save it.

https://github.com/gorhill/uBlock/wiki/Element-picker

See "My Filters" in the settings. Alternatively use [the per-site switch](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering).

**Comment by gorhill** [comment] 2016-05-14 06:03
Duplicate of #515.

**Closed by gorhill** 2016-05-14 06:03 UTC

**Comment by HubJ** [comment] 2016-05-14 11:37
Thanks for your help.
