### ISSUE TITLE
UBlock Origin is broken on all sites in my Firefox mobile nightly 44.0a1 (2015-10-19)

### ISSUE THREAD

**Issue by LifeIsStrange** [gorhill/uBlock#843] opened 2015-10-19 13:16 UTC
All is in the title :) 
I can do tests for you, it's on a oneplus one /android 5.1.1 with uBlock Origin 1.3.0rc4
Thanks.

**Comment by gorhill** [comment] 2015-10-19 13:20
Duplicate of #749?

**Comment by LifeIsStrange** [comment] 2015-10-19 13:21
Oh no it was on uBlock Origin 1.3.0rc3 and I have Just now update to rc4 and uBlock rework :)

**Comment by LifeIsStrange** [comment] 2015-10-19 13:23
Yes it was the same problem as https://github.com/gorhill/uBlock/issues/749
But now it seems that the rc4 have detroy the bug so I close the issue

**Closed** 2015-10-19 13:23 UTC
