### ISSUE TITLE
shortcuts stopped working after update to the latest version

### ISSUE THREAD

**Issue by AdKiller** [gorhill/uBlock#2987] opened 2017-09-07 13:15 UTC
shortcuts used to work fine, but they completely stopped working after updating to v1.14.4

I had them set like this:

    extensions.ublock0.shortcuts.launch-element-zapper: alt-Z
    extensions.ublock0.shortcuts.launch-element-picker: alt-X
    extensions.ublock0.shortcuts.launch-logger: alt-C

### Your settings

- OS/version:  Windows 10 Pro 1607 64bit
- Browser/version:  Firefox 52.3.0 64bit
- uBlock Origin version:   v1.14.4

**Comment by gorhill** [comment] 2017-09-07 13:56
Duplicate of #2870.

https://github.com/gorhill/uBlock/issues?q=is%3Aissue+shortcuts+is%3Aclosed

**Closed by gorhill** 2017-09-07 13:56 UTC
Labels: duplicate
