### ISSUE TITLE
ublock load ads when chrome be reopen

### ISSUE THREAD

**Issue by KonoromiHimaries** [gorhill/uBlock#3583] opened 2018-03-08 07:01 UTC
### Describe the issue
https://github.com/MajkiIT/polish-ads-filter/issues/6437

### One or more specific URLs where the issue occurs
example. `http://open.fm` or `https://www.wp.pl/`

### Steps for anyone to reproduce the issue

to reproduct:
- open site `http://open.fm`
- when will you be on site `http://open.fm` close the chrome browser with `X` button
- reopen chrome browser
![2018-03-08-open fm - radio online](https://user-images.githubusercontent.com/5884000/37136445-0439b69e-22a2-11e8-83b9-61598a89f9fa.png)

### Your settings

- OS/version: win10
- Browser/version: 65.0.3325.146
- uBlock Origin version: 1.15.2

##### Your filter lists

default + polish + polish cookies

**Comment by uBlock-user** [comment] 2018-03-08 09:28
https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental

**Comment by gorhill** [comment] 2018-03-08 11:02
Duplicate of #1327.

**Closed by gorhill** 2018-03-08 11:02 UTC
Labels: duplicate
