### ISSUE TITLE
Element picker/zapper don't work if cosmetic filtering is disabled

### ISSUE THREAD

**Issue by cy7yz2rj** [gorhill/uBlock#3212] opened 2017-11-09 19:46 UTC
### Describe the issue
Disabling cosmetic filtering by default will prevent the element picker and zapper from manifesting, when called from either toolbar icon or context menu.

Verified by creating new profile, changing the add-on signature requirement in about:config, installing uBO and toggling the cosmetic filtering setting. No further changes from default Firefox or uBO configuration.

### One or more specific URLs where the issue occurs

https://github.com/gorhill/uBlock/releases

### Steps for anyone to reproduce the issue

1. Open uBO dashboard
2. Under Settings pane, check "Disable cosmetic filtering "
3. Element picker/zapper no longer usable.

### Your settings

- OS/version: Debian 9.2 (stable)
- Browser/version: Firefox ESR (52.4.0)
- uBlock Origin version: 1.14.17 and newer

**Comment by gorhill** [comment] 2017-11-09 20:05
Duplicate of #2963.

**Comment by gorhill** [comment] 2018-02-21 20:10
This is not a duplicate, my mistake.

**Comment by uBlock-user** [comment] 2018-02-21 20:38
I can reproduce it in Chromium 66 too.

**Comment by Kn0p3XX** [comment] 2018-03-09 18:19
The element picker for me does not working at all. Just tested it on a fresh Firefox profile, installed uBlock and it's not working.

**Closed** 2021-07-19 18:54 UTC
