### ISSUE TITLE
Clicking URLs in Chrome Full History bypasses uBlock Origin

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#852] opened 2015-10-22 00:33 UTC
I have discovered what is potentially a major flaw in uBlock Origin.

**If a user clicks on a link from the Full Chrome History page of Google Chrome, most if not all uBlock Origin filters are automatically bypassed.**

**Steps to Reproduce:**

(1). Enable "Nightmare Mode":

`* * 1p-script block`
`* * 3p block`
`* * 3p-frame block`
`* * 3p-script block`
`* * inline-script block`

(2). Open a new tab in Chrome and set the network request log to monitor it

![screen shot 2015-10-21 at 17 25 58](https://cloud.githubusercontent.com/assets/15240200/10653930/2d904d72-7819-11e5-9be7-6b340d055bf8.png)

(3). Visit a website. Let's go with [kottke.org](http://kottke.org)

![screen shot 2015-10-21 at 17 26 26](https://cloud.githubusercontent.com/assets/15240200/10653933/3533a308-7819-11e5-89be-fed5123f0f45.png)

(4). Note that the network request log only shows that the document and first-party images/stylesheets have loaded

![screen shot 2015-10-21 at 17 26 08](https://cloud.githubusercontent.com/assets/15240200/10653935/3b77057a-7819-11e5-89cd-f3b60c27b3eb.png)

(5). View Chrome's "[Full Chrome History](chrome://history/)" page (Cmd + Y on a Mac)

![screen shot 2015-10-21 at 17 26 38](https://cloud.githubusercontent.com/assets/15240200/10653941/425dd44a-7819-11e5-8049-e2f6069f504b.png)

(6). Click on [kottke.org](http://kottke.org)

(7). Observe that the network request log allows connections the following:
	- Document and first-party images/stylesheets
	- Inline and first-party scripts
	- Images from subdomain also.kottke.org
	- Scripts from jquery.com, pinterest.com, weworkremotely.com
	- Stylesheets from typography.com, bootstrapcdn.com
	- And, possibly, fronts via stylesheets (look closely at the screenshots)

![screen shot 2015-10-21 at 17 27 10](https://cloud.githubusercontent.com/assets/15240200/10653948/4cd22ec6-7819-11e5-9924-87a3adce6208.png)

![screen shot 2015-10-21 at 17 27 13](https://cloud.githubusercontent.com/assets/15240200/10653949/51b3a1a4-7819-11e5-8660-56a73cdcc6c2.png)

(8). Hit refresh, and note that the connection logger reports the items listed as approved in Step 6 are now blocked, with only the document and first-party images/stylesheets having been loaded.

I am running the latest version of uBlock Origin in with the latest public versions of Chrome and OS X.

**Comment by gorhill** [comment] 2015-10-22 04:32
I could not reproduce with Chromium 45.0.2454.101.

**Comment by one23** [comment] 2015-10-22 05:46
I can partially reproduce (Chromium 48.0.2543.0 + uBlock Origin 1.3.2b3, both with no modified settings apart from dynamic filtering settings above).  

Only in-line scripts were let through, however; 1st party scripts and all 3rd party resources were blocked.

**Comment by gorhill** [comment] 2015-10-22 12:12
> Only in-line scripts were let through

Yes, this I can reproduce. I believe this is a Chromium corner case, happening because the document is loaded from the memory-based cache (very short term cache). If you try with an older history entry, inline script will be blocked (because disk-based cache or not in cache).

**Comment by gorhill** [comment] 2015-10-22 13:56
This could be related to #854 (which is fixed in latest build). But since I could not reproduce this one here, you will have to verify if it makes a difference.

**Comment by publicarray** [comment] 2015-10-23 00:13
I could reproduce with uBlock Origin v1.2.0 but not with v1.3.2b6

**Comment by gorhill** [comment] 2015-10-23 14:03
I have been studying [OP's picture](https://cloud.githubusercontent.com/assets/15240200/10653948/4cd22ec6-7819-11e5-9924-87a3adce6208.png) (OP left GitHub unfortunately) to understand if what the logger says could be explained by #854, and it definitely can.

For some times at the beginning of the page load, resources are fetched and uBlock is told that the context is whitelisted (it used the History page context to find out whitelisted status, `chrome-scheme`). Eventually, uBO is told (asynchronously) of the context change, and so now starts to use the proper (non-whitelisted) context, `kottke.org` in the current example.

Then I wondered why I could not reproduce. I did not realize I could actually reproduce, just not as much as OP: my inline script rule was not enforced, all the rest was enforced properly. I think it came down to a matter of timing, for some reasons on my side the onNavigation event was fired earlier than on OP's side. onNavigation is an asynchronous event from the browser, and there is just no guarantee it will be fired before resources from a page load -- it's unrelated to the webRequest API (unfortunately).

So I will consider #854 to be a duplicate of this one - and fixes in latest build.

The issue _could_ manifest when navigating from a whitelisted context to a non-whitelisted one, or vice-versa -- with the result of not enough blocking, or too much blocking, respectively.

**Comment by gorhill** [comment] 2015-10-23 14:04
Fixed with afd77a3cef58bc2a047147a43a51e54cb3d10b44.

**Closed by gorhill** 2015-10-23 14:04 UTC
