### ISSUE TITLE
Freezes firefox entirely

### ISSUE THREAD

**Issue by pix64** [gorhill/uBlock#1114] opened 2015-12-26 21:31 UTC
Url: http://www.healthline.com/health/cold-flu/help-sore-throats

**Comment by gorhill** [comment] 2015-12-26 22:29
Unable to reproduce using default settings.

Marking as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

***

Note: the site makes a **lots** of network requests such as:

    https://www.facebook.com/tr/?id=341638689366170&ev=PixelInitialized&dl=http%3A%2F%2Fwww.healthline.com%2Fhealth%2Fcold-flu%2Fhelp-sore-throats%233&rl=http%3A%2F%2Fwww.healthline.com%2Fhealth%2Fcold-flu%2Fhelp-sore-throats%232&if=false&ts=1451168770733

Because of the following EasyPrivacy filter:

    ||facebook.com/tr/?

while scrolling down and up the page. But I did not experienced a freeze.

**Closed by gorhill** 2015-12-26 22:29 UTC
Labels: invalid, unable to reproduce

**Comment by thallada** [comment] 2016-07-26 01:46
I am able to reproduce this in chrome. However, it might be inconsistent because when I clicked on the above link, it didn't crash until I refreshed the page and tried again. Maybe try another article on the site healthline.com (e.g. http://www.healthline.com/health/food-nutrition/is-v8-good-for-you).

There is a scroll handler that is supposed to refresh ads on each paragraph break in the article (and increment the number in the url hash), but with uBlock enabled it seems to spaz out and attempt to do 720 ad refreshes all at once upon the first scroll event...

Sometimes I am able to close the tab with the chrome task manager. Sometimes I have to kill chrome entirely as my computer locks up and my mouse is unresponsive.

Disabling uBlock prevents the site from crashing chrome.

Chrome version: 51.0.2704.103
uBlock Origin: 1.7.6
Pretty sure I have all the default filters on.

**Comment by Hrxn** [comment] 2016-07-26 02:56
> Chrome version: 51.0.2704.103

Outdated as of July 26, 2016

**Comment by gorhill** [comment] 2016-07-26 03:32
The site is flawed, it will fired the network requests to facebook regardless of whether they are blocked or not by uBO. The issue is with the site, report to them: it does not make sense to fire a network request on scroll events.

**Comment by okiehsch** [comment] 2017-03-17 18:22
Every article on this site for example `http://www.healthline.com/health/fall-in-love-with-yourself-again`
freezes both Chrome and Firefox on my end, with Chrome tabs actually crashing after a while.
The issue appears to be the filter `/ga-custom-vars.` in `EasyPrivacy`.
The filter
`@@||healthline.com/resources/base/js/util/ga-custom-vars.js$script,domain=healthline.com`
fixes that issue.
