### ISSUE TITLE
RFE: sync all config using Sync

### ISSUE THREAD

**Issue by jpjp** [gorhill/uBlock#143] opened 2015-04-27 18:53 UTC
Some/most extensions support syncing config (including black/whitelists) across different Firefox installations using Sync. Would be nice.

**Comment by gorhill** [comment] 2015-04-27 19:17
You need to take your time before filing issue. You just filed two issues because you were too speedy, you overlooked proper information. Now this one is a duplicate.

Duplicate of #80.

**Closed as completed by gorhill** 2015-04-27 19:17 UTC
