### ISSUE TITLE
Ads in Youtube's HTML5 player aren't blocked

### ISSUE THREAD

**Issue by 10se1ucgo** [gorhill/uBlock#645] opened 2015-08-26 23:46 UTC
* Chrome 46.0.2490.4 dev-m (64-bit)/uBlock 1.1.0.0
* Default settings for everything

Steps:
1. Open a youtube video url, e.g.: https://www.youtube.com/watch?v=jCKVD9578eQ
2. Ad is not blocked if played in the HTML5 player

**Comment by gorhill** [comment] 2015-08-27 02:47
Unable to reproduce using Chrome 46.0.2490.4 dev, uBlock 1.1.0.0. It's probably just Youtube rolling out to some users some new ad mechanism which is not yet covered by EasyList -- i.e. a filter list issue.

Duplicate of #594.

**Closed by gorhill** 2015-08-27 02:47 UTC

**Comment by 10se1ucgo** [comment] 2015-09-07 16:52
According to [this article](http://www.neowin.net/news/google-chrome-reportedly-bypassing-adblock-forces-users-to-watch-full-length-video-ads) someone posted to Reddit, the YouTube app within chrome, accessible by entering chrome:\\\apps into the address bar, is the cause of full-length video ads while an ad blocker is enabled. Removing it seems to fix the issue.

**Comment by gorhill** [comment] 2015-09-07 16:56
> According to this article

What the article fails to mention is that this solution was originally posted by a user right [here](https://github.com/gorhill/uBlock/issues/675#issuecomment-137957141).

**Comment by 10se1ucgo** [comment] 2015-09-07 16:59
Didn't actually read the article, just the reddit comments with the instructions, my bad.
