### ISSUE TITLE
How to turn disable for all sites without going to Add-Ons

### ISSUE THREAD

**Issue by ackern** [gorhill/uBlock#457] opened 2015-07-07 12:36 UTC
Is there a way to disable uBlock origin for all sites (and re-enable) other than by going to the FF add-ons manager? I often need to disable everywhere for a few minutes and then re-enable. For example Adblock Plus's toolbar button gives you a "Disable everywhere" choice along with "Disable on this site". 

Thank you. Sorry I don't know if this is the right forum. I cant' find any forum specifically for help as such.

**Comment by CrisBRM** [comment] 2015-07-07 12:39
No, and there never will be, as stated by gorhill a myriad of times before.

**Comment by gorhill** [comment] 2015-07-07 13:08
Duplicate of #167.

There are add-ons out there to enable/disable any installed add-ons.

**Closed by gorhill** 2015-07-07 13:08 UTC
