### ISSUE TITLE
"Disable" switch ignores Private Browsing

### ISSUE THREAD

**Issue by Jamie0** [gorhill/uBlock#794] opened 2015-10-07 15:20 UTC
<i>Valid on any version of Firefox + uBlock, with default settings. </i>

<b>Steps to reproduce:</b>
<ol>
<li>Open private browsing, visit a website that requires you to disable your ad-blocker (this could be as simple as online banking or an online store, let's say http://www.youtube.com for the sake of example);</li>
<li>Disable ad blocker/uBlock using the power icon in the menu;</li>
<li>Close private browsing window;</li> 
<li>Visit website again, either in normal browsing or new private window. Notice the persistent setting.</li>
</ol>

As a consequence, some data from private browsing is obviously saved to the disk, which, in some cases, can make private browsing totally useless. A skilled attacker would be able to deduce, from the configuration file, missing parts of browsing history.

**Comment by harshanvn** [comment] 2015-10-07 17:30
unfortunately, i have to disagree with this request..it will be usability catostrophe for most of the users...:(
its like saying when user in private browsing mode, all his bookmarks/passwords saved should not be persistent as soon as his private session ends..
nor any addon works in this way..

**Comment by publicarray** [comment] 2015-10-08 01:19
Duplicate of #104, only 104 OP specifically refers to firefox.

**Comment by gorhill** [comment] 2015-10-08 10:58
Duplicate of #104.

**Closed by gorhill** 2015-10-08 10:58 UTC
