### ISSUE TITLE
Remove Javascript Restrictions Using uBlock

### ISSUE THREAD

**Issue by phone8588** [gorhill/uBlock#969] opened 2015-11-24 19:59 UTC
How can uBlock be used to remove (strip) javascript restrictions from a web page - for example sites that don't let you right click on them or ones that don't let you select/copy text from the web page? Using the blanket option to remove all inline scripts break the web page and renders it useless in most cases.

For example, look at page - http://www.imdb.com/media/rm1140695296/tt1430132?ref_=tt_ov_i

You cannot right click (to copy image) or select the main picture of Wolverine in the webpage - essentially Firefox's select/copy/paste tools are rendered ineffective by the javascript handlers.

Looking for similar functionality as the extension RightToClick (https://addons.mozilla.org/en-US/firefox/addon/righttoclick/) - given uBlock's capability it feels a waste to have a second extension running.

**Comment by vzjrz** [comment] 2015-11-24 20:15
If you're running firefox you can set `dom.event.contextmenu.enabled` to false.

**Comment by Halibut80** [comment] 2015-11-24 20:28
> If you're running firefox you can
also just Ctrl + Shift + RMB on element to see it default context menu.

**Comment by gorhill** [comment] 2015-11-24 20:29
Duplicate of #968.

**Closed by gorhill** 2015-11-24 20:29 UTC

**Comment by gorhill** [comment] 2015-11-24 20:36
To be clear, I decline this feature request.
