### ISSUE TITLE
enable/disable button invisible

### ISSUE THREAD

**Issue by vendforce** [gorhill/uBlock#3485] opened 2018-02-05 20:26 UTC
### Screenshot in which the issue can be seen
(https://imgur.com/a/RjjWq)

- OS/version: ARCH kde
- Browser/version: FIREFOX 58
- uBlock Origin version: 1.15.4

**Comment by gorhill** [comment] 2018-02-05 23:24
Duplicate of #2004.

**Closed by gorhill** 2018-02-05 23:24 UTC
