### ISSUE TITLE
Add Barblock filter list 

### ISSUE THREAD

**Issue by rodalpho** [gorhill/uBlock#2935] opened 2017-08-30 18:14 UTC
Recently an anti-adblocker company DMCA'd EasyList, forcing them to remove its URL.

https://torrentfreak.com/dmca-used-to-remove-ad-server-url-from-easylist-ad-blocklist-170811/
https://blog.getadmiral.com/dmca-easylist-adblock-copyright-access-control-admiral-10-things-to-know/

BarbBlock is a blocklist that specifically targets hosts that force other lists to remove their URLs via DMCA notices. I believe it belongs in the  uBlock Origin block lists, ideally activated by default.

Description: https://ssl.bblck.me/
The blocklist: https://ssl.bblck.me/blacklists/ublock-origin.txt

**Comment by gorhill** [comment] 2017-08-30 18:32
Duplicate of #2864.

**Closed by gorhill** 2017-08-30 18:32 UTC
Labels: duplicate

**Comment by rodalpho** [comment] 2017-08-30 18:37
My apologies, I searched for BarbBlock and nothing came up in open issues.
