### ISSUE TITLE
Reclaim left over space after hiding element

### ISSUE THREAD

**Issue by Spamme1** [gorhill/uBlock#1030] opened 2015-12-08 10:32 UTC
I googled it, but I couldn't find anywhere, how to reclaim the left over space after hiding an element? Some pages are built with width in percentage, this means that after hiding an element, the other elements don't expand in the left over space. For example if you have two DIV elements side by side with css width of 50%, so that you have a two columns layout, and you hide one DIV element, one column, the other DIV element doesn't expand in the left over space of the hidden DIV element.

```html
<DIV id="container">
  <DIV id="column1" style="width:50%;float:left;">...</DIV>
  <DIV id="column2" style="width:50%;float:right;">...</DIV>
</DIV>
```

Is it possible to reclaim the left over space? For example with an overriding css rule? I know that is possible with other extensions like stylish or greasemonkey, but I would prefer to have everything in one place.

**Comment by gorhill** [comment] 2015-12-08 14:21
Duplicate of #781.

**Closed by gorhill** 2015-12-08 14:21 UTC
