### ISSUE TITLE
Update of filters don't work

### ISSUE THREAD

**Issue by bup4gr** [gorhill/uBlock#3398] opened 2018-01-03 12:33 UTC
### Describe the issue
The filter update don't work also if i force the update.
In the filter tab the last ublock filter is not udate and has the date 10.10.2017.
![1](https://user-images.githubusercontent.com/27068733/34520088-236ab2ac-f07f-11e7-83b8-04452aebe6af.png)

So i try to add manually the ublock filter and i see that there are a lot of filter not loaded (394 in the screenshot)
![2](https://user-images.githubusercontent.com/27068733/34520121-43ff41f4-f07f-11e7-8448-15e2789760a8.png)

I also see in the options tab that i can't select (or deselect) some settings and i don't known why
![3](https://user-images.githubusercontent.com/27068733/34520734-ec69c272-f081-11e7-87bc-a806c4427800.png)

### Steps for anyone to reproduce the issue
I think that to reproduce the problem you must only reproduce my settings (see below).
I notice the problem because i invesigated this problem https://github.com/uBlockOrigin/uAssets/issues/1144

### Your settings
- OS/version: Win 10
- Browser/version: Tor browser 7.0.11 (that is firefox ESR 52.5.2 with some privacy changes, note that firefox ESR don't use webext)
- uBlock Origin version: 1.14.22

**Comment by gorhill** [comment] 2018-01-03 12:40
Your filters are showing up to date.

Firefox 52 does not support the privacy API required by uBO webext.

**Comment by bup4gr** [comment] 2018-01-03 14:35
Sorry, but i don't understand because is invalid.
I can see the yellow "out of date"
![5](https://user-images.githubusercontent.com/27068733/34523955-92fbf2c2-f091-11e7-927c-1c07def8760a.png)

but also after the update, the list is always old.
![7](https://user-images.githubusercontent.com/27068733/34524044-eb1a5034-f091-11e7-9c96-20cffb642a11.png)

For ublock filter, you con see that the total number of the filter is always 2568 (also after update), but the correct is 2958 (as you can see in the second screenshot of the first post).

For example with this issue https://github.com/uBlockOrigin/uAssets/issues/1144 the ally.sh filter has changed but i have always the old filter (see screenshot) because the update don't work.
![8](https://user-images.githubusercontent.com/27068733/34524325-17249bca-f093-11e7-9b76-c14035732c89.png)

So for me the filter don't update also if i don't see the yellow "out of date" icon.

**Comment by bup4gr** [comment] 2018-01-03 14:44
I see that this problem is also with my Firefox 56.0.2 (last version before webext).

**Comment by gorhill** [comment] 2018-01-03 14:48
The issue if with Firefox, when _"Always use private browsing mode"_  is checked.

See <https://bugzilla.mozilla.org/show_bug.cgi?id=781982>.

Duplicate of #3071.

**Closed by gorhill** 2018-01-03 14:48 UTC
Labels: browser bug, duplicate
