### ISSUE TITLE
Logger tooltips

### ISSUE THREAD

**Issue by SoniEx2** [gorhill/uBlock#1658] opened 2016-05-24 19:57 UTC
uBlock Origin 1.7.0, both on Firefox Nightly (49) and Thunderbird Stable (45), "advanced user": on + "disable tooltips": off, tooltips don't show up on the logger.

**Comment by gorhill** [comment] 2016-05-24 21:45
Duplicate of #1222.

**Closed by gorhill** 2016-05-24 21:45 UTC
