### ISSUE TITLE
IGN links not working

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#203] opened 2015-05-16 12:42 UTC
Any link in www.ign.com don't work. I have to open them with right mouse "Open link in new tab".

Browser: Chrome Version 42.0.2311.152 m (64-bit)
uBlock 0.9.7.0 Default Settings
Windows 8.1 Pro 64bits
No other extensions

**Comment by gorhill** [comment] 2015-05-16 13:33
Can't reproduce using default settings.

**Comment by gorhill** [comment] 2015-05-22 12:08
Closing due to no feedback. Anyway, certainly a 3rd-party filter list issue.

**Closed as completed by gorhill** 2015-05-22 12:08 UTC
Labels: unable to reproduce
