### ISSUE TITLE
Problem with uBlock Origin and Disconnect together

### ISSUE THREAD

**Issue by sateffen** [gorhill/uBlock#1992] opened 2016-09-14 13:56 UTC
### Describe the issue

If I install [disconnect](https://chrome.google.com/webstore/search/disconnect?hl=de) and ublock origin in chrome, ublock origin throws a warning:

```
Warnung:
Die Erweiterung konnte die Netzwerkanfrage nicht an data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CgkvLwoJdmFyIEdhcSA9IGZ1bmN0aW9uKCkgewoJCTsKCX07CglHYXEucHJvdG90eXBlLk5hID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5PID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5TYSA9IG5vb3BmbjsKCUdhcS5wcm90b3R5cGUuVGEgPSBub29wZm47CglHYXEucHJvdG90eXBlLlZhID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fY3JlYXRlQXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0QXN5bmNUcmFja2VyID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2FxLnByb3RvdHlwZS5wdXNoID0gZnVuY3Rpb24oYSkgewoJCWlmICggdHlwZW9mIGEgPT09ICdmdW5jdGlvbicgKSB7CgkJCWEoKTsKCQl9Cgl9OwoJLy8KCXZhciB0cmFja2VyID0gKGZ1bmN0aW9uKCkgewoJCXZhciBvdXQgPSB7fTsKCQl2YXIgYXBpID0gWwoJCQknX2FkZElnbm9yZWRPcmdhbmljIF9hZGRJZ25vcmVkUmVmIF9hZGRJdGVtIF9hZGRPcmdhbmljJywKCQkJJ19hZGRUcmFucyBfY2xlYXJJZ25vcmVkT3JnYW5pYyBfY2xlYXJJZ25vcmVkUmVmIF9jbGVhck9yZ2FuaWMnLAoJCQknX2Nvb2tpZVBhdGhDb3B5IF9kZWxldGVDdXN0b21WYXIgX2dldE5hbWUgX3NldEFjY291bnQnLAoJCQknX2dldEFjY291bnQgX2dldENsaWVudEluZm8gX2dldERldGVjdEZsYXNoIF9nZXREZXRlY3RUaXRsZScsCgkJCSdfZ2V0TGlua2VyVXJsIF9nZXRMb2NhbEdpZlBhdGggX2dldFNlcnZpY2VNb2RlIF9nZXRWZXJzaW9uJywKCQkJJ19nZXRWaXNpdG9yQ3VzdG9tVmFyIF9pbml0RGF0YSBfbGluayBfbGlua0J5UG9zdCcsCgkJCSdfc2V0QWxsb3dBbmNob3IgX3NldEFsbG93SGFzaCBfc2V0QWxsb3dMaW5rZXIgX3NldENhbXBDb250ZW50S2V5JywKCQkJJ19zZXRDYW1wTWVkaXVtS2V5IF9zZXRDYW1wTmFtZUtleSBfc2V0Q2FtcE5PS2V5IF9zZXRDYW1wU291cmNlS2V5JywKCQkJJ19zZXRDYW1wVGVybUtleSBfc2V0Q2FtcGFpZ25Db29raWVUaW1lb3V0IF9zZXRDYW1wYWlnblRyYWNrIF9zZXRDbGllbnRJbmZvJywKCQkJJ19zZXRDb29raWVQYXRoIF9zZXRDb29raWVQZXJzaXN0ZW5jZSBfc2V0Q29va2llVGltZW91dCBfc2V0Q3VzdG9tVmFyJywKCQkJJ19zZXREZXRlY3RGbGFzaCBfc2V0RGV0ZWN0VGl0bGUgX3NldERvbWFpbk5hbWUgX3NldExvY2FsR2lmUGF0aCcsCgkJCSdfc2V0TG9jYWxSZW1vdGVTZXJ2ZXJNb2RlIF9zZXRMb2NhbFNlcnZlck1vZGUgX3NldFJlZmVycmVyT3ZlcnJpZGUgX3NldFJlbW90ZVNlcnZlck1vZGUnLAoJCQknX3NldFNhbXBsZVJhdGUgX3NldFNlc3Npb25UaW1lb3V0IF9zZXRTaXRlU3BlZWRTYW1wbGVSYXRlIF9zZXRTZXNzaW9uQ29va2llVGltZW91dCcsCgkJCSdfc2V0VmFyIF9zZXRWaXNpdG9yQ29va2llVGltZW91dCBfdHJhY2tFdmVudCBfdHJhY2tQYWdlTG9hZFRpbWUnLAoJCQknX3RyYWNrUGFnZXZpZXcgX3RyYWNrU29jaWFsIF90cmFja1RpbWluZyBfdHJhY2tUcmFucycsCgkJCSdfdmlzaXRDb2RlJwoJCV0uam9pbignICcpLnNwbGl0KC9ccysvKTsKCQl2YXIgaSA9IGFwaS5sZW5ndGg7CgkJd2hpbGUgKCBpLS0gKSB7CgkJCW91dFthcGlbaV1dID0gbm9vcGZuOwoJCX0KCQlvdXQuX2dldExpbmtlclVybCA9IGZ1bmN0aW9uKGEpIHsKCQkJcmV0dXJuIGE7CgkJfTsKCQlyZXR1cm4gb3V0OwoJfSkoKTsKCS8vCgl2YXIgR2F0ID0gZnVuY3Rpb24oKSB7CgkJOwoJfTsKCUdhdC5wcm90b3R5cGUuX2Fub255bWl6ZUlQID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fY3JlYXRlVHJhY2tlciA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuX2ZvcmNlU1NMID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fZ2V0UGx1Z2luID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5fZ2V0VHJhY2tlciA9IGZ1bmN0aW9uKCkgewoJCXJldHVybiB0cmFja2VyOwoJfTsKCUdhdC5wcm90b3R5cGUuX2dldFRyYWNrZXJCeU5hbWUgPSBmdW5jdGlvbigpIHsKCQlyZXR1cm4gdHJhY2tlcjsKCX07CglHYXQucHJvdG90eXBlLl9nZXRUcmFja2VycyA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUuYWEgPSBub29wZm47CglHYXQucHJvdG90eXBlLmFiID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5oYiA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUubGEgPSBub29wZm47CglHYXQucHJvdG90eXBlLm9hID0gbm9vcGZuOwoJR2F0LnByb3RvdHlwZS5wYSA9IG5vb3BmbjsKCUdhdC5wcm90b3R5cGUudSA9IG5vb3BmbjsKCXZhciBnYXQgPSBuZXcgR2F0KCk7Cgl3aW5kb3cuX2dhdCA9IGdhdDsKCS8vCgl2YXIgZ2FxID0gbmV3IEdhcSgpOwoJKGZ1bmN0aW9uKCkgewoJCXZhciBhYSA9IHdpbmRvdy5fZ2FxIHx8IFtdOwoJCWlmICggQXJyYXkuaXNBcnJheShhYSkgKSB7CgkJCXdoaWxlICggYWFbMF0gKSB7CgkJCQlnYXEucHVzaChhYS5zaGlmdCgpKTsKCQkJfQoJCX0KCX0pKCk7Cgl3aW5kb3cuX2dhcSA9IGdhcS5xZiA9IGdhcTsKfSkoKTs= weiterleiten, da eine andere Erweiterung (Disconnect) sie an about:blank weitergeleitet hat.
```

something like: ublock origin wants to redirect a new tab (blank page) to this script (google analytics?), but disconnect stops it doing so.

What is this script? Why do you need it?

I can ignore this, and everything works as usual, no problems. But the browser keeps it's big red warning about the problem.

### One or more specific URLs where the issue occurs

Just surf ~2min, press strg + t for a new tab, and the browser will tell you about the problem. Make sure to install both, ublock origin and disconnect.

### Steps for anyone to reproduce the issue

1. Install ublock origin
1. Install disconnect
1. Open new tab, surf a little with new tabs

### Your settings

- Browser/version:  Chrome 53.0.2785.113 m (64-bit)
- uBlock Origin version: 1.9.4
- Disconnect version: 5.18.23

##### Your filter lists

Default filters + all privacy filters + domains with malware filters + german easylist (DEU: EasyList Germany)

**Comment by gorhill** [comment] 2016-09-14 15:07
Duplicate of #1170.

**Closed by gorhill** 2016-09-14 15:07 UTC
