### ISSUE TITLE
Remove sourceforge.net from Badware risks

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#1437] opened 2016-02-28 22:17 UTC
Sourceforge has stopped bundling their downloads with Adware, thus I guess the SourceForge badware risks filter can be removed.

Check https://sourceforge.net/blog/sourceforge-acquisition-and-future-plans/

I checked the FileZilla download on SourceForge and it seemed to not contain adware.

**Comment by gorhill** [comment] 2016-02-28 22:20
Duplicate of #1409.

**Closed by gorhill** 2016-02-28 22:20 UTC

**Comment by tobbi** [comment] 2016-02-28 22:22
Oh, sorry about this.
