### ISSUE TITLE
SpyHunter identifying uBlock as malware

### ISSUE THREAD

**Issue by marcelo-r-garcia** [gorhill/uBlock#2122] opened 2016-11-03 00:59 UTC
In Google Chrome uBlock is falsely identified as "WorldSearchPro.com" malware and in Firefox as "B1 Toolbar" and "Snap.do".

I've contacted the SpyHunter tech support and asked them to fix that.

Both browsers are up to date on an up to date windows 10 machine.

**Comment by gorhill** [comment] 2016-11-03 03:49
Duplicate of #1009.

**Closed by gorhill** 2016-11-03 03:49 UTC
