### ISSUE TITLE
EasyPrivacy breaks https://my.t-mobile.com/choose-account.html

### ISSUE THREAD

**Issue by jab** [gorhill/uBlock#1169] opened 2016-01-04 19:28 UTC
1. Go to t-mobile.com
1. Under My T-Mobile, click Login
1. Get redirected to https://account.t-mobile.com/oauth2/v1/auth?...
1. Submit correct user/password credentials
1. Redirected to https://my.t-mobile.com/choose-account.html
1. uBlock shows 2 requests blocked (using default filters, no customization)
1. Page shows spinner forever so you can't complete log-in, javascript console reveals errors
1. Disabling uBlock allows the page to load

I see from https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md you don't have time for filter-related issues, so please feel free to close. Still valuable to have this issue documented in the tracker so it turns up in search results, as currently searching turns up nothing.

**Comment by gorhill** [comment] 2016-01-04 22:24
I do not have a T-Mobile account. See if the issue also occurs with ABP + EasyList + EasyPrivacy. If so, that would confirm the issue is with EasyList or EasyPrivacy, in which case you can report to their maintainers. Otherwise, the issue is likely cause by something in Peter Lowe's, which I would fix, but as said I can't because I do not have an account.

I tried to enter random stuff in the fields, but the site behaved correctly, telling me I do not match their records.

**Comment by gorhill** [comment] 2016-01-04 22:25
What are the requests being blocked? (see [logger](https://github.com/gorhill/uBlock/wiki/The-logger)).

**Comment by gorhill** [comment] 2016-01-04 22:27
Also, you could try to whitelist only that one login page, by adding `https://account.t-mobile.com/oauth2/v1/auth?` to the _Whitelist_ pane in the dashboard.

**Comment by gorhill** [comment] 2016-01-04 22:27
Closed by mistake.

**Comment by jab** [comment] 2016-01-05 17:20
I tested with ABP + EasyList+EasyPrivacy and reproduced. (With just EasyList and no EasyPrivacy it didn't.)

In an attempt to report this upstream I found my way to https://easylist.adblockplus.org/en/development and from there to the [EasyList Forums](http://forums.lanik.us/), where I grudgingly registered (why can't I just report this to them on GitHub or BitBucket?!), but then got
> Your account has been created. However, this board requires account activation, an activation key has been sent to the email address you provided. Please check your email for further information.

and still have yet to receive the email.

I'll also note their web site's registration and log in pages don't redirect to https, i.e. they're happy to have you submit your password over http. Another stroke against a project that's supposed to protect its users' privacy.

Since I still haven't been able to get access to post to their forums, if anyone reading this can please report this upstream on my behalf, you'd be doing a service to T-Mobile + EasyPrivacy users everywhere.

**Comment by gorhill** [comment] 2016-01-05 17:46
EasyList forums do use `https`: <https://forums.lanik.us/viewforum.php?f=64>, I don't understand how you ended on `http`, both Chromium and FF redirect to `https`. I can report the issue, but it won't be solved, because they need to reproduce the issue to find out what is the workaround. You should use uBO's logger to at least find out which network requests were blocked, so at least a tentative workaround can be worked out from that result -- the cause is often an issue seen before.

**Comment by jab** [comment] 2016-01-05 17:56
1. Go to https://easylist.adblockplus.org/en/development
1. Click "EasyList forums" link to http://forums.lanik.us/
1. Click "Register" link to http://forums.lanik.us/ucp.php?mode=register&sid=d643867e0cc235eadf7c4a201c3116a1
1. Click "I agree to these terms" link and end up on http://forums.lanik.us/ucp.php?mode=register&sid=f61e297b2d3489c862261f604a793d21
1. Observe the form submits to "./ucp.php?mode=register" over http. Not a single one of the previous requests redirected to https.

Here are screenshots of the offending rules. Hope this helps:

![screen shot 2016-01-05 at 12 54 30](https://cloud.githubusercontent.com/assets/64992/12122863/adc0d9d0-b3ab-11e5-8c56-f9e687a67de2.png)

![screen shot 2016-01-05 at 12 52 27](https://cloud.githubusercontent.com/assets/64992/12122867/b1cacb12-b3ab-11e5-900e-ca12eb5c86a5.png)

**Comment by gorhill** [comment] 2016-01-05 18:52
> Click "EasyList forums" link to http://forums.lanik.us/

What browser/version are you using?

> Here are screenshots of the offending rules. Hope this helps:

I've seen before the blocking of `nexus.ensighten.com` causing breakage -- there are already filter exceptions in EasyPrivacy for it. See if this works:

    @@||ensighten.com^*/Bootstrap.js$script,domain=t-mobile.com

If this does not work, then the other will also need an exception filter.

**Comment by IDKwhattoputhere** [comment] 2016-01-05 19:43
https://forums.lanik.us/viewtopic.php?f=64&t=27622

**Comment by jab** [comment] 2016-01-05 20:50
> What browser/version are you using?

Latest stable Chrome (47.0.2526.106). 

Adding `@@||ensighten.com^*/Bootstrap.js$script,domain=t-mobile.com` under "My filters" looks like it fixes it, thanks!

And thanks @IDKwhattoputhere for posting on the forums.

**Closed** 2016-01-07 22:34 UTC
