### ISSUE TITLE
Some suggestions and issues

### ISSUE THREAD

**Issue by Yaron10** [gorhill/uBlock#861] opened 2015-10-25 23:32 UTC
Hello Raymond,

I installed uBlock Origin a couple of days ago (in Firefox 41), and I'm really impressed.
Thank you for your great work.

Some suggestions:
1) An option to open the Dashboard from uBlock's icon.
2) An option to globally disable uBlock; - either by middle-clicking the icon or by a new command in the popup.
3) IMO, removing the "since install" and "domains connected" sections would make the popup much clearer and cleaner.
4) I usually open FF with a blank page. 
"icon16" is displayed for a second, and then it's replaced with "icon16-off".
Wouldn't it be better to set the default icon to "icon16-off"?

Some issues:
1) My Firefox and uBlock interface is RTL (Hebrew).
The default order of preferred languages is Hebrew and then English.
If I change the preferred lang to English (FF Options -> Content -> Languages),  uBlock's popup and Dashboard are displayed in Hebrew *but in LTR *. It's a bit messed up.
2) [Notepad++ Forum](https://notepad-plus-plus.org/community/)
Toggling "browser.display.use_document_fonts" to "0" or "1", the icon-fonts are [displayed](http://s24.postimg.org/4tzjdx62t/Icon_Fonts.png) properly.
If, however, "browser.display.use_document_fonts" is set to "1" and I click uBlock's font icon (Toggle the blocking of remote fonts for this site) - the icon-fonts are [not](http://s23.postimg.org/sqgrvwf8r/Icon_Fonts_Wrong.png) displayed.
Any way to fix that? (Windows 7).
3) On starting Firefox, the following warning appears in the Error Console:
'enable-background'.  Declaration dropped.
chrome://ublock0/content/img/browsericons/icon16.svg.

And with your permission, one question:
I've unchecked "Enable cloud storage support".
Why do I get the following entries in prefs.js?
```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

Best regards.

**Comment by 5t3f4n** [comment] 2015-10-26 02:16
>Some suggestions:
>2)

Dupe of #167 among others.

**Comment by Yaron10** [comment] 2015-10-26 02:48
@5t3f4n,

Thanks. I appreciate it.

>1) An option to open the Dashboard from uBlock's icon.

Just read in another thread about clicking the extension's name at the top of the popup.

**Comment by gorhill** [comment] 2015-10-26 12:47
> If, however, "browser.display.use_document_fonts" is set to "1" and I click uBlock's font icon (Toggle the blocking of remote fonts for this site) - the icon-fonts are not displayed.

So it works fine then? The point of the per-site font-blocking switch is to not have the font downloaded and used.

**Comment by Yaron10** [comment] 2015-10-26 15:52
@gorhill,

I'm afraid I was not clear enough.

I've disabled Clear Type and Font Smoothing system-wide.
When "browser.display.use_document_fonts" is set to "1" (default), the icon-fonts are displayed but the text is [not displayed properly](http://s17.postimg.org/dlnzcz6xr/image.png).

So, I use a toolbar button to toggle "browser.display.use_document_fonts" to "0".
Prior to FF 41, the text was fine but the icon-fonts *were not* displayed.

In FF 41, [CSS Font Loading API is enabled by default](https://drafts.csswg.org/css-font-loading/).
And now,  toggling "browser.display.use_document_fonts" to "0" - both the text and the icon-fonts are displayed correctly.

The "per-site font-blocking" is a brilliant feature (special thanks), and in many sites it saves me the need to toggle "browser.display.use_document_fonts".

However, *in sites using icon-fonts* I still have to toggle that pref.
If I don't (toggle it) and only use the "per-site font-blocking" feature, the icon-fonts are not displayed.
It would be great if I could use "per-site font-blocking" for those sites as well. 

Thanks for replying and many thanks for you work.

**Comment by gorhill** [comment] 2015-10-26 15:59
> However, in sites using icon-fonts I still have to toggle that pref.

uBO's per-site font blocking switch doesn't care for the purpose of a font, it just outright whatever is a font resource.

**Comment by Yaron10** [comment] 2015-10-26 17:28
I see.
Would it be possible to add a rule for specific sites to set "browser.display.use_document_fonts" to "0"?
(Not necessarily changing the pref, but getting the same result). 
I believe it can be useful to many users.

Thanks.

**Comment by gorhill** [comment] 2015-10-31 16:56
[CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2015-10-31 16:56 UTC
