### ISSUE TITLE
v1.7.6 broke "Block Element" in TBB.

### ISSUE THREAD

**Issue by proxifier** [gorhill/uBlock#1755] opened 2016-06-26 08:00 UTC
1. Update your add-on from v1.7. I'm using TBB.
2. Restart TBB just in case.
3. Visit a webpage and right-click it, click "Block Element".

Before update(v1.7):
A black screen covers all area, and let me choose an area.

After update(v1.7.6):
Nothing happens. No black screen, no style picker, etc.
I can't click any forms(like this comment textarea box) after I click "Block ELement".
Reload this page forcefully using F5 Key unlock the page.

Something is going on here.

**Comment by gorhill** [comment] 2016-06-26 23:02
Unable to reproduce, works fine here on 6.0.2.

**Comment by proxifier** [comment] 2016-06-27 13:10
@gorhill, if you're using firefox nightly, you also want to try TBB's Alpha.

This is what I'm using on Alpha channel.

6.5a1 (based on Mozilla Firefox 45.2.0)

**Comment by gorhill** [comment] 2016-06-27 14:04
> This is what I'm using on Alpha channel

I will let you investigate -- I can't install all sort of un-stable version of browsers out there. Best is to assume there is an issue specific to TBB Alpha, not uBO. Look in dev console, etc.

**Comment by proxifier** [comment] 2016-06-28 07:00
It's completely stable to use. Many people using Experimental build.
https://www.torproject.org/projects/torbrowser.html.en#downloads-alpha

If you can't fix this issue, then the next relase of "stable" user will engage into this problem.
Honestly I want to help you, but when I look at "Browser Console", it records no uBO related errors.

**Comment by gorhill** [comment] 2016-06-28 11:59
I just installed Tor browser 6.5a1, and the element picker works fine on my side. No browser setting were modified prior, I just installed uBO and tested.

**Comment by proxifier** [comment] 2016-06-29 06:11
Try "TorButton" and "TorLauncher" disabled. (some Linux people doing this to use their own proxy)

Weird, I could use picker before upgrading uBO.

**Comment by gorhill** [comment] 2016-06-29 14:12
> Try "TorButton" and "TorLauncher" disabled

How do you do this?

**Comment by gorhill** [comment] 2016-06-29 14:15
> I can't click any forms(like this comment textarea box) after I click "Block ELement".

It's as if uBO's element picker's own style is being overriden. Are you using custom user styles?

**Comment by juhiyu** [comment] 2016-07-01 11:00
I also face this problem TBB 6.0.2 Linux x64....block element works but does not show up. so click anywhere on the page it does not show that any element as highlighted but in the filter textbox the element is shown and can then create filter

**Comment by gorhill** [comment] 2016-07-01 11:07
Definitely looks like uBO's SVG element's styles are being overridden on your side. You will have to find out what is overriding the styles. Custom theme?

**Comment by juhiyu** [comment] 2016-07-01 11:45
Custom theme? you mean within the browser? I am using the default TBB version only change is uBO is installed.

**Comment by gorhill** [comment] 2016-07-01 11:59
As said I can't reproduce. So the best way to contribute is for whoever can reproduce to be proactive and investigate, to seek details about what is happening. Use the browser toolbox to find out if the element picker is on the page, and if so, what are the style of the SVG elements making up the element picker's overlay:

![a](https://cloud.githubusercontent.com/assets/585534/16520972/b36b49fa-3f61-11e6-859d-f195f20ac198.png)

**Comment by juhiyu** [comment] 2016-07-01 12:13
I'm a noob so please bear....SVG looks like it is loaded in the page like so:
<path d="M0 0h859v117h-859zM99.89999389648438 -260.1333312988281h664.2000122070312v372h-664.2000122070312z"></path>
<path d="M99.89999389648438 -260.1333312988281h664.2000122070312v372h-664.2000122070312z"></path>

**Comment by gorhill** [comment] 2016-07-01 12:34
>  2 lines are shown for "path d" ... inherited body does not change

Yes, there are two `path` elements. The styles of these elements should be:

- 1st: black with opacity 75%
- 2nd: reddish with opacity 20%

If you go to `about:config` and filter the list using `svg`, here is what it shows on my side:

![a](https://cloud.githubusercontent.com/assets/585534/16521682/7f185bfc-3f66-11e6-96aa-eb6548904f3b.png)

**Comment by juhiyu** [comment] 2016-07-01 12:38
Mine has some differences:

gfx.font_rendering.opentype_svg.enabled;false (says user-set)
svg.in-content.enabled;false (says user-set)
all else is the same

But I have not changed anything myself

**Comment by gorhill** [comment] 2016-07-01 12:41
If you reset these entries, is the issue still there? (might need to restart browser after changes -- unsure). Since you noted down the settings in above comment, you can restore them easily if you want.

**Comment by gorhill** [comment] 2016-07-01 12:47
> But I have not changed anything myself

What your security level? I read [here](https://www.torproject.org/projects/torbrowser/design/) that if it's high, `svg.in-content.enabled` will be disabled.

**Comment by juhiyu** [comment] 2016-07-01 12:48
Yes, resetting these entries to default now it looks like element picker is working as it should

**Comment by gorhill** [comment] 2016-07-01 12:58
So it's quite probably what was also happening to OP, this matches his "I can't click any forms" after launching the element picker. Closing as "external".

**Closed** 2016-07-01 12:59 UTC
Labels: external

**Comment by fastcopy** [comment] 2016-07-18 12:55
gfx.font_rendering.opentype_svg.enabled
svg.in-content.enabled

both are already 'true' and I can't use this feature. What else should I look in about:config?
