### ISSUE TITLE
websocket's not being filtered by uBo

### ISSUE THREAD

**Issue by ryanbr** [gorhill/uBlock#3546] opened 2018-02-25 04:59 UTC
### Describe the issue

Filtering of websocket url's not working, 

wss://a.bondinra.com/wsm

### One or more specific URLs where the issue occurs

`https://www.blacklistednews.com/` but there are many more.

### Screenshot in which the issue can be seen

We have simplified these websocket rules recently; see; https://github.com/easylist/easylist/commit/2b32ad7f4023de1eab65683b8fc09d2458e5a1a2

||bondinra.com^ should be block by uBo. (but its not)

### Your settings

- OS/version: Windows 10
- Browser/version: Firefox
- uBlock Origin version: 1.15.10

##### Your filter lists

Easylist/Easyprivacy

**Comment by okiehsch** [comment] 2018-02-25 05:17
Works fine with Chrome
![unbenannt](https://user-images.githubusercontent.com/16838044/36638348-fdb045e8-19f2-11e8-9057-fcc2e18c5504.PNG)

With Firefox the filter does not work, because the request labelled as "behind the scene".
![unbenannt22](https://user-images.githubusercontent.com/16838044/36638359-518ec1bc-19f3-11e8-86d1-617f1e7ea703.PNG)

To reproduce you have to disable `uBO-filters`.

**Comment by ryanbr** [comment] 2018-02-25 05:56
How/why does it differ regarding Firefox "Behind the scene" vs Chrome?

**Comment by gorhill** [comment] 2018-02-25 12:01
I don't know why Firefox reports as behind the scene -- maybe this can be fixed by Firefox devs. It's Uponit scripts, and there is a lot of trickery at work here, and it _could_ be related to the use of an `about:blank` frame in some sort of way.

In any case, with Firefox there is more information available for webRequest listeners, and uBO should make use of this information for behind-the-scene network requests:

    details = {
        documentUrl : "https://www.blacklistednews.com/"
        frameId : 0
        ip : null
        method : "GET"
        originUrl : "https://www.blacklistednews.com/"
        parentFrameId : -1
        proxyInfo : null
        requestId : "2676"
        tabId : "-1"
        timeStamp : 1519559704526
        type : "websocket"
        url : "wss://a.bondinra.com/wsm"
    };

`documentUrl` and `originUrl` are not available on Chromium, but they could be used on Firefox to allow the request to be filtered despite being behind-the-scene.

**Comment by uBlock-user** [comment] 2018-02-25 14:29
Does `||bondinra.com^$websocket` work ?

**Closed** 2018-02-26 18:59 UTC
