### ISSUE TITLE
Causes Tumblr "k" shortcut on feed to break

### ISSUE THREAD

**Issue by ZachSaucier** [gorhill/uBlock#1611] opened 2016-05-04 15:28 UTC
If you have a Tumblr account and go to the home page's feed (at https://www.tumblr.com/dashboard), uBlock breaks the "k" shortcut.

Users can usually use "j" and "k" to go to the next and previous post in the feed, respectively. uBlock is currently causing this shortcut to break

I am using Chrome

**Comment by gorhill** [comment] 2016-05-04 15:32
Can this be reproduce without account? If so, which URL?

**Comment by ZachSaucier** [comment] 2016-05-04 15:34
Not that I'm aware of

**Comment by gorhill** [comment] 2016-05-04 15:38
I create an account, and it works fine here using default settings. How are your settings differing from the default ones?

**Comment by ZachSaucier** [comment] 2016-05-04 15:40
They're the default as far as I'm aware of

**Comment by Hrxn** [comment] 2016-05-04 15:41
I have a tumblr account, thank god...

Navigation with `j` and `k` still works for me on the dashboard.

```
Windows 7
Chrome x64 latest stable
uBO 1.7.2.
```

**Comment by gorhill** [comment] 2016-05-04 15:42
You said [here](https://github.com/chrisaljoudi/uBlock/issues/1606):

> I tried and it loads fine with uBlock Origin.

?

**Comment by ZachSaucier** [comment] 2016-05-04 15:43
Sorry, I copy and pasted that response from another forum after finding out it was broken. It is an issue with this, uBlock Origin, not the other

**Comment by gorhill** [comment] 2016-05-04 15:44
You will have to disclose all your settings -- as said, I can't reproduce. You say:

> uBlock is currently causing this shortcut to break

How did you come to this conclusion?

**Comment by ZachSaucier** [comment] 2016-05-04 15:46
I can disable uBlock Origin and the "k" shortcut will work again. If Origin is enabled it breaks again, only scrolling up about 15 pixels, not to the previous post as is intended

The settings enabled are the default:
- Hide placeholders of blocked elements
- Show the number of blocked requests on the icon
- Make use of context menu where appropriate
- Disable pre-fetching (to prevent any connection for blocked network requests)
- Disable hyperlink auditing/beacon

No others are enabled

**Comment by gorhill** [comment] 2016-05-04 15:47
What about filter lists? Custom filters? Rules?

**Comment by Hrxn** [comment] 2016-05-04 15:47
Scratch my last comment..

I think I can reproduce now. Just visited the Dashboard again, just to be sure, if loading from cache makes any difference.

And indeed, using `j` jumps to the next post on the board, while `k` doesn't work as before, it does not jump back up completely, it just scrolls up, for maybe 10 pixels or so..

**Comment by ZachSaucier** [comment] 2016-05-04 15:50
I just updated the filters list and it seems to fix the issue... Interesting.

Any idea why a filter could cause a shortcut to break?

**Comment by ZachSaucier** [comment] 2016-05-04 15:53
Filters are the default and just updated. Enabled ones listed here:

- uBlock filters‎ : 499 used out of 499
- uBlock filters – Badware risks‎ (github.com): 4 used out of 4
- uBlock filters – Privacy‎ : 25 used out of 25
- uBlock filters – Unbreak‎ : 96 used out of 97
- EasyList‎ (forums.lanik.us): 63,887 used out of 63,926
- Peter Lowe’s Ad server list‎ (pgl.yoyo.org): 2,411 used out of 2,411
- EasyPrivacy‎ (forums.lanik.us): 11,428 used out of 11,464
- Malware Domain List‎ (malwaredomainlist.com): 1,571 used out of 1,571
- Malware domains‎ (www.malwaredomains.com): 21,562 used out of 21,922

No custom filters

**Comment by gorhill** [comment] 2016-05-04 15:56
>  just updated the filters list and it seems to fix the issue

I was trying to find out if changes to tumblr-related filters have been occurring recently, I see this is the case:

- https://hg.adblockplus.org/easylist/rev/7382abc34819
- https://hg.adblockplus.org/easylist/rev/0699751ba1c2
- https://hg.adblockplus.org/easylist/rev/415d34bab3e4

So possibly the fix was in there. Were EasyList or EasyPrivacy marked as "obsolete" in iBO's dashboard?

**Comment by Hrxn** [comment] 2016-05-04 15:57
Boy, this is getting better every minute..

It seems to work again.
Here is what I did:
- Open the Tumblr Dashboard link in a new tab
- No interaction with the page
- Used `j` to scroll down to the posts, and `k` now scrolls back correctly again.

Will see if I can it reproduce again..

**Comment by ZachSaucier** [comment] 2016-05-04 15:59
Disabling EasyList‎ seems to fix the issue

**Comment by gorhill** [comment] 2016-05-04 16:00
Any error message in the dev console of that page when the issue occurs?

**Comment by ZachSaucier** [comment] 2016-05-04 16:01
Not when attempting to use the "k" shortcut, no

**Comment by gorhill** [comment] 2016-05-04 16:06
If you [disable cosmetic filtering](https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering) for the site instead of disabling EasyList, does that fix the issue?

**Comment by ZachSaucier** [comment] 2016-05-04 16:09
https://github.com/gorhill/uBlock/issues/1611#issuecomment-216913983

Yes, so long as I refresh the page

**Comment by gorhill** [comment] 2016-05-04 16:19
So this probably mean one of the cosmetic filter on the page is causing this. On my side, using the logger, I see only `##.ytp-ad-progress-list` which is from EasyList, but I do not experience the issue. If you turn back on cosmetic filtering, are there any cosmetic filter enforced aside the one mentioned here?

**Comment by ZachSaucier** [comment] 2016-05-04 16:22
I believe that `##.standalone-ad-container` is one, though I'm not familiar with the logger

**Comment by gorhill** [comment] 2016-05-04 16:32
I can't get `##.standalone-ad-container` on my side, looks like I am not served ads.

If you use custom filter `tumblr.com#@#.standalone-ad-container`, does it fix the issue? If so, than you need to report to EasyList maintainers.

**Comment by ZachSaucier** [comment] 2016-05-04 16:35
Yes, that filter seems to work. I'll post on their forums

**Closed** 2016-07-28 14:31 UTC
Labels: filter list issue
