### ISSUE TITLE
[feature request] devtools.netmonitor context menu integration

### ISSUE THREAD

**Issue by 360up** [gorhill/uBlock#1057] opened 2015-12-13 07:37 UTC
In the browser-built-in network monitor it would be nice to have a "create filter" option in the context menu that comes up when right-clicking on a network request. It then would open the popup dialogue with filter pre-selection (like the one you get when clicking the 4th column of a request in the logger)

network monitor --> right click on network request --> create filter

Background:
I use both uM and uBO. Unfortunately it's impossible to determine by uBOs logger what has already been filtered by uM (w/o consulting uM rules as well).
It's much quicker to find remaining junk through the netmonitor, so it'll be wonderful to be able to clean it from there directly.

**Comment by AlexVallat** [comment] 2015-12-14 08:20
Code for that available in [my fork](https://github.com/AlexVallat/uBlockOrigin) if that helps.

**Comment by gorhill** [comment] 2016-01-03 00:34
Duplicate of #119.

**Closed by gorhill** 2016-01-03 00:34 UTC
