### ISSUE TITLE
Causes http auth to always crash on Firefox Android

### ISSUE THREAD

**Issue by fastcat** [gorhill/uBlock#3171] opened 2017-10-25 05:30 UTC
Using v1.14.16 on Firefox 56 on Android on Nexus 6P and Pixel C.

Any page that triggers http auth dialog crashes Firefox when the auth dialog is to pop up.  If master password dialog is to go first, that happens ok, crash happens at the moment when http auth dialog should show.

Happens on any page using http auth AFAICT.

Filter list is just easy list.  No custom filters enabled.

Disabling the addon "fixes" the problem, no app restart needed.

Seen also by others (what led me to suspect ublock): https://github.com/pfn/passifox/issues/612

**Comment by gorhill** [comment] 2017-10-25 11:09
Duplicate of #3087.

**Closed by gorhill** 2017-10-25 11:09 UTC
Labels: browser bug, duplicate

**Comment by gorhill** [comment] 2017-10-25 11:11
A crash is always a browser issue, uBO is JS/HTML/CSS, it's not supposed to crash a browser.

**Comment by gorhill** [comment] 2017-10-25 11:36
Well apparently this won't be fixed for Firefox 57:
https://bugzilla.mozilla.org/show_bug.cgi?id=1396395
