### ISSUE TITLE
Some key combinations are used to enter national characters and they are intercepted by uBlock

### ISSUE THREAD

**Issue by jasiek** [gorhill/uBlock#2783] opened 2017-07-12 10:15 UTC
### Describe the issue

There are a number of key combinations that are used to enter diacritics (ą, ę,...) that are hijacked by uBlock. The one bothering me the most is right-alt + l. I would recommend adding an option to disable all key shortcuts to the configuration.

### One or more specific URLs where the issue occurs

Not URL-dependent.

### Screenshot in which the issue can be seen

See below.

### Steps for anyone to reproduce the issue

1. Go to any page.
2. Press Alt-l.

### Your settings

- OS/version: macOS Sierra
- Browser/version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- uBlock Origin version: 1.13.2

##### Your filter lists

Irrelevant.

**Comment by gwarser** [comment] 2017-07-12 11:10
https://github.com/gorhill/uBlock/releases/tag/1.13.2

**Comment by gorhill** [comment] 2017-07-12 12:23
Duplicate of #2723.

**Closed by gorhill** 2017-07-12 12:23 UTC
