### ISSUE TITLE
uBlock Origin reports itself as disabled for all sites

### ISSUE THREAD

**Issue by rcmero** [gorhill/uBlock#3471] opened 2018-01-28 23:29 UTC
uBlock Origin does work as intended, but when I check the control panel it always reports itself as disabled. When I click the button to enable it nothing happens.

![captura de ecra 1](https://user-images.githubusercontent.com/5708421/35488554-edd18db0-0482-11e8-85fd-edb6991ada6b.png)

Running uBlock Origin 1.14.24 on Pale Moon 27.6.2, on Windows 10 1709.

**Comment by gorhill** [comment] 2018-01-28 23:38
Marking as "available": whoever is using Pale Moon is welcomed to investigate the cause of the reported issue.

**Comment by kowith337** [comment] 2018-01-29 11:35
Cannot reproduce, it's still normal here with new profile...
![image](https://user-images.githubusercontent.com/16535467/35508473-102465a4-0523-11e8-8618-3b7995b86513.png)

**Comment by gorhill** [comment] 2018-01-29 12:25
By the look of uBO's popup panel, it _sees_ the URL of the current tab as a whitelisted URL. First thing I would suspect is another extension or custom browser config -- so try in a new profile with only uBO.

**Comment by jordanbs** [comment] 2018-02-01 00:15
I'm hitting this too on Safari on a Mac, but only for specific sites - https://www.nytimes.com earlier today (but working as expected now), but currently https://arstechnica.com.

Perhaps this is a new adblock-blocking technique?

**Comment by kowith337** [comment] 2018-02-02 10:17
Still cannot reproduce, either...

I think the opener is accesing YouTube site (guess by upload button icon that see in cropped screenshot), here's my reproduced result, but I've got Pale Moon updated to 27.7.2 today.
![image](https://user-images.githubusercontent.com/16535467/35727915-632ee780-083c-11e8-8f57-d36052db5bf2.png)

New York Times
![image](https://user-images.githubusercontent.com/16535467/35727951-89699f4e-083c-11e8-91c0-c02874019e23.png)

Ars Technica
![image](https://user-images.githubusercontent.com/16535467/35727999-b643d412-083c-11e8-8dfd-80e262296afd.png)

**Comment by i30817** [comment] 2018-02-02 15:40
Happened to me here in firefox and reddit. First the icon disappeared from the toolbar and the horrible 'promoted' reddit stickies started appearing then i restarted firefox and the icon appeared again but the nasty stuff kept appearing.

**Comment by luarum** [comment] 2018-02-02 22:26
This is a cosmetic error I sometimes have happen if my browser or computer crashed. I think it has something to do with uBlock not shutting down properly. Either way, it's functioning normally on the backend. I usually have it correct itself after opening/closing my browser window correctly a few times. Re-installing uBlock may also help.

**Comment by gorhill** [comment] 2018-04-20 15:59
This issue is stale: unable to reproduce, affects uBO/legacy, and there is not enough investigation done by OP to narrow down the cause of the issue he experienced.

**Closed by gorhill** 2018-04-20 15:59 UTC
Labels: unable to reproduce
