### ISSUE TITLE
Options page doesn't open with material extensions page enabled

### ISSUE THREAD

**Issue by Couchy** [gorhill/uBlock#1723] opened 2016-06-15 17:42 UTC
-Chrome Version 51.0.2704.84 m (64-bit)
-uBlock Origin v1.7.2
-Go to chrome://flags -> Enable Material Design extensions

There is no options link shown in the material extensions page for uBlock Origin, and right-clicking it in the extension bar and selecting "options" doesn't work either. I noticed that even without the material theme enabled, the options link for uBlock is different from other extensions. (Seems to be a JavaScript link - not underlined and no URL preview on mouseover)

**Comment by yechao25038** [comment] 2016-06-16 03:29
i have the same problem. when i open the Material Design of the extensions，the options link will not be shown

**Comment by gorhill** [comment] 2016-08-15 16:53
Any extension I tried I could not open their options page. Can you provide me with a screenshot of where I need to click for the option page to open in the re-designed extensions page?

**Comment by Couchy** [comment] 2016-08-15 17:53
Indeed, it looks like it's still undergoing redesign and is broken in Chrome 52.0.2743.116. I think you're supposed to click "DETAILS", then the gear icon, but it doesn't work for any extension. The issue with uBlock is that it's apparently dependent on the design of the extensions page - if you right-click the icon in the extension bar and click "Options", it first opens the extensions page and then tries to open uBlock options from there, whereas most extensions go directly to the options page. The gear icon on the uBlock dropdown still works, though and goes directly to the options page.

**Comment by gorhill** [comment] 2016-08-15 21:15
>  The issue with uBlock is that it's apparently dependent on the design of the extensions page

That's all Chromium's fault, extensions have to move to the new way to implement options. See <https://developer.chrome.com/extensions/optionsV2>. Problem with the new way is that it assumes that all extensions will have options which fit in a small iframe in `chrome://extensions`. This can't work for uBO, so the document loaded in the `iframe` automatically open the real uBO dashboard.

**Comment by gorhill** [comment] 2017-09-21 13:47
I tested again, and there is a link now, "Extension options", and clicking on it correctly open uBO's dashboard.

So marking as unable to reproduce with Chromium 60.

**Closed by gorhill** 2017-09-21 13:47 UTC
Labels: unable to reproduce

**Comment by Couchy** [comment] 2017-09-21 13:58
Just curious, has the "old" method of opening the options page actually been deprecated? I still see many extensions with options that bypass the extensions page.
