### ISSUE TITLE
Ublock Origin 1.14.18 on Firefox 57 for Android

### ISSUE THREAD

**Issue by bkc2** [gorhill/uBlock#3237] opened 2017-11-16 12:29 UTC
Hello,

I have recently updated to Firefox 57 on my SM-A320 (Galaxy A-320) running Android 7.0. I have also updated to Ublock Origin version 1.14.18. Before Firefox 57 I was using version 1.13.8, the last version before changes to extensions API. The issue I'm seeing is that the counter of blocked elements for the first tab is not showing how many elements were blocked. If I open second, third or any other tab, then the counter is showing. It looks like cosmetic filtering is not working for the first tab, where the counter is not visible. Cosmetic filtering looks to be working on the second tab. I have a second device running Android 5.0.2 (Lenovo Tab 2) and the issue is also there.

The issue for me occurs on page www.dobreprogramy.pl Notice the word 'reklama' at the top present in 1st screenshot, not present on 2nd screenshot.

![01 01](https://user-images.githubusercontent.com/33721044/32890964-357ed7b2-cad1-11e7-8919-8001e1ae8847.png)
![01 02](https://user-images.githubusercontent.com/33721044/32890965-35a6c4f2-cad1-11e7-9f2b-05d66467eaf7.png)
![02 01](https://user-images.githubusercontent.com/33721044/32890966-35cbaace-cad1-11e7-8e17-96d41e96b554.png)
![02 02](https://user-images.githubusercontent.com/33721044/32890967-35f170ec-cad1-11e7-92bb-20bdddc75f2a.png)

Steps to reproduce the issue:

1. Open firefox and browse to provided page, check ublock counter status
2. Open new tab, browse to the same page, check ublock status

My settings settings:

- OS/version: Android 7.0 (Samsung Stock), Android 5.0.2 (Lenovo Stock)
- Browser/version: Firefox 57 for Android
- uBlock Origin version: 1.14.18

My filter lists:

Ublock filters except experimental, all adguard filters, easylist anly for ads, All Malware lists, hpHosts, Regional PL

No custom filters.

**Comment by gorhill** [comment] 2017-11-16 12:51
> The issue I'm seeing is that the counter of blocked elements for the first tab is not showing how many elements were blocked.

Duplicate of #3148.

**Closed by gorhill** 2017-11-16 12:51 UTC

**Comment by bkc2** [comment] 2017-11-16 13:00
Yes, the counter is not showing number of blocked elements, but also the page has word 'reklama' when the counter is not active, while this word is hidden when the counter is active on the second tab. Not sure is this is really a problem, if not, please close the issue. This behaviour was not present for me on FF55/56 and UBO 1.13.8 (kept the legacy extension due to issues with new extension API).

**Comment by bkc2** [comment] 2017-11-16 17:24
Thank you.
