### ISSUE TITLE
[Enhancement] Shortcut in popup UI to turn off uBlock completely

### ISSUE THREAD

**Issue by explorer1492** [gorhill/uBlock#401] opened 2015-06-25 13:50 UTC
First off, I'd like to thank everyone involved in this project for doing such great work - uBlock makes life easier for a lot of people out there.

As a former user of ABP and Adguard I'd like to propose an enhancement for the uBlock popup UI. So far it's missing a shortcut to turn off uBlock completely. 

The user has the possibility to whitelist the current page or site through the power button. But the only way to fully disable uBlock is through the extensions menu of Chrome itself (which causes the uBlock icon next to the address bar to diasppear - requiring the user to repeat the same steps to enable uBlock again).

Both ABP and Adguard offer the proposed feature already, which is useful if you want to disable the ad-blocker just for a short period of time without creating a whitelist-entry for the site you're currently visiting (e.g. to check if a certain behaviour of the page, or a glitch in the layout is caused by the ad-blocker).

**Comment by gorhill** [comment] 2015-06-25 14:25
Duplicate of #384.

**Closed as completed by gorhill** 2015-06-25 14:25 UTC

**Comment by explorer1492** [comment] 2015-06-25 14:47
Sorry, didn't know this idea was already dismissed. Keep up the great work.
