### ISSUE TITLE
[Suggestion] Add Adguard Social filter to default list. 

### ISSUE THREAD

**Issue by happysurf** [gorhill/uBlock#3214] opened 2017-11-10 08:29 UTC
Will be great add the good [Adguard Social filter](https://filters.adtidy.org/extension/ublock/filters/4.txt) to Annoyances  group as alternative to Fanboy’s Social Blocking List.

**Comment by superlex** [comment] 2017-11-11 16:45
I agree. With Fanboy’s Social Blocking List enabled, Social media filter list has about 3500 rules used.

**Comment by xDarkARG** [comment] 2017-11-12 14:51
I agree. With

**Comment by ryanbr** [comment] 2017-12-02 04:22
Not the most efficient list I've seen, how does it differ from the Fanboy Social list?

**Comment by superlex** [comment] 2017-12-14 01:08
Hi ryanbr.
For example, ##[href^="//twitter.com/share"] is present only in AdGuard Social list.
I don't know how it differ form Fanboy Social list exactly, simply I found it's better, in my case, to use AdGuard Social list + Fanboy Social list.

**Comment by ryanbr** [comment] 2017-12-14 08:19
The issue is there is far too much duplicates if a user decided to use both lists, I do understand Adguard trying to keep their lists inhouse, but ideally it should really be a subset of the social list (with Adguard specific rules?). 

There is currently 14,000 rules in the current FB list vs 4,000 in Adguard Social. Its nowhere complete.  

I'm happy to merge social fixes from Adguard not covered in the main Fanboy social list. In regards to the specific **##[href^="//twitter.com/share"]** is there a sample site where its used and not blocked by other exisiting filters?

**Comment by superlex** [comment] 2017-12-14 11:57
AdGuard team translated their lists for uBlock Origin. There are some duplicates, but according to me the problem is that are duplicates with little differences, e.g.
##[href^="https://www.facebook.com/sharer/sharer.php?u="] (Fanboy)
##[href^="https://www.facebook.com/sharer/sharer.php"] (Adguard)
so Ublock can't recognize it as duplicate. It's only my supposition.

As regards ##[href^="//twitter.com/share"] I found it here:
http://www.hdmotori.it/2017/12/14/Toyota-Hilux-Invincible50-limited-edition/
but it's only an example.

If you want merge social fixes for me it's ok, thank you for your willingness.

**Comment by gorhill** [comment] 2017-12-14 12:01
> I do understand Adguard trying to keep their lists inhouse

I can't speak for them but I believe having something fixed ASAP when a users report filter issues might be the top motivation (aside supporting filter syntax not supported by ABP for long) to have their own list -- I can relate.

**Comment by snhv** [comment] 2017-12-20 08:11
Hi @gorhill , so can we expect this to happen?
I can vouch with my personal experience that Adguard Social list has higher quality than Fanboy's list.

**Comment by ryanbr** [comment] 2017-12-20 08:15
What? "higher quality" What does that mean?

**Comment by snhv** [comment] 2017-12-20 08:22
It means social icons, banners etc. are blocked but 'Log in with GG', 'Log in with FB' are still there and I can still conveniently log in sites with my GG, FB credentials. Maybe the purposes of the 2 lists are different but for me, Adguard list just works.

**Comment by ryanbr** [comment] 2017-12-20 08:51
There is more generic filters in the list, overall it is a more complete list. Just look at the current size of it, and even do a text/file compare and see.

Earlier on when I started the original Fanboy List, we were competing against Easylist we promoted the list as a lite/optimised in comparison. But trying to keep the original Fanboy Adblock list small and lite, meant limiting adding filters to the point people wouldn't use it because you're not blocking or hiding enough.  "Why can't you block X and Y, when another list will do the same?"

Browsers have matured, as has browser extensions. Both ABP and uBo are efficient at loading large lists, and this has become less of an issue. So using the "Lite" social list argument, just means we can't/won't cover your websites.

I'm happy to fix issues (or missing social stuff), but Adguard Social list doesn't really offer anything new over this list.

**Comment by happysurf** [comment] 2017-12-20 12:54
The filter lists are efficient in relation to internet browsing that the user does, for me the Adguard Social is a lite alternative but for my use very efficient.

**Comment by TerrakionSmash** [comment] 2018-01-17 14:11
Adguard's has less false positives.

**Comment by Ravizz** [comment] 2018-02-08 21:44
@jspenguin2017 , @yourduskquibbles,  as for paraphrasing https://github.com/gorhill/uBlock/issues/3489 & https://github.com/NanoAdblocker/NanoCore/issues/116

Why add Adguard Social filter? Just take a look at this comment: https://github.com/gorhill/uBlock/issues/3489#issuecomment-363965921

Let's apply and paraphrase @anewuser 's "logic" here, just change it a bit from "can have 2, can't have 3" to "can have 1, can't have 2"
> @anewuser:
> uBlock Origin already has one extensive third-party list for social (Fanboy). Enable them (AdGuard) in your settings.
> 
> If you find any missing case, report it to https://github.com/ryanbr/fanboy-adblock/issues.
> 

But wait..take a look here too: https://github.com/gorhill/uBlock/issues/3214#issue-272856170 

And lets apply and paraphrase another guy's "logic", @happysurf :

> @happysurf
> Will be great add the good [Web Annoyances Ultralist](https://github.com/yourduskquibbles/webannoyances) filter to Annoyances group as alternative to Fanboy’s Annoyances List and AdGuard's Annoyances List

**Comment by gorhill** [comment] 2019-01-11 14:48
Fixed with <https://github.com/gorhill/uBlock/commit/3e41939e4160c1d441ac4c53b1d6020e43814a61>.

**Closed by gorhill** 2019-01-11 14:48 UTC
