### ISSUE TITLE
Can't type ADD sign with german keyboard. Opens Logger UI

### ISSUE THREAD

**Issue by gobijan** [gorhill/uBlock#2727] opened 2017-06-23 11:55 UTC
On a German Mac Keyboard ALT+ L (small l actually; in capital here for readability) inputs the add sign. Some genius put the uBlock open LOGGER-UI  on this mapping... What to do?

**Comment by gwarser** [comment] 2017-06-23 13:09
https://github.com/gorhill/uBlock/issues/2724

**Comment by bershan2** [comment] 2017-06-23 13:47
This is actually issue #2723, because `#2724` is a duplicate of `#2723`.

@gobijan The author of this extension [explained how to fix it here](https://github.com/gorhill/uBlock/issues/2723#issuecomment-310111651).

**Comment by gorhill** [comment] 2017-06-24 02:03
> Some genius [...]

You could contribute by testing the beta builds so that such issues are found before release. You shouldn't complain if you are not willing to contribute through using the beta build.

**Closed by gorhill** 2017-06-24 02:03 UTC
