### ISSUE TITLE
Shortcuts don't work on Firefox 58

### ISSUE THREAD

**Issue by nbros** [gorhill/uBlock#3502] opened 2018-02-11 08:26 UTC
### Describe the issue
Cannot assign a shortcut to element zapper

### Steps for anyone to reproduce the issue
1. Go to about:config
1. Set **extensions.ublock0.shortcuts.launch-element-zapper** = **alt-Z**
1. Restart the browser
1. Open any webpage
1. Hit alt+Z

=> nothing happens

Expected: element zapper to be activated

### Your settings
- OS/version: Windows 10
- Browser/version: Firefox 58.0.2
- uBlock Origin version: 1.15.4

**Comment by gorhill** [comment] 2018-02-11 12:33
Duplicate of #2870.

**Closed by gorhill** 2018-02-11 12:33 UTC
Labels: browser bug, duplicate
