### ISSUE TITLE
@-Symbol on mac osx

### ISSUE THREAD

**Issue by Timmitou** [gorhill/uBlock#2761] opened 2017-07-06 00:09 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Pretty simple but annoying issue: I'm on mac osx and if I want to type the @-symbol I therefore have to press ALT + L. This is, however, also the keyboard shortcut to open the logger on ublock origin. In other words: While origin is running, I cannot type the @-symbol... Is there any way to change the shortcut that opens the logger? Because this issue is driving me mad whenever I'm trying to enter my e-mail address anywhere...

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: 
- Browser/version: 
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment] 2017-07-06 00:11
Duplicate of #2723.

**Closed by gorhill** 2017-07-06 00:11 UTC
