### ISSUE TITLE
FF39, logger behind the scene log all content

### ISSUE THREAD

**Issue by androidland** [gorhill/uBlock#474] opened 2015-07-10 01:39 UTC
With FF Version 39 on Win 7 ublock0 0.9.9.4, logger behind the scene still log all content

![ublock](https://cloud.githubusercontent.com/assets/9499540/8610643/11a3acd4-26df-11e5-872b-3254599126fc.png)

**Comment by Betsy25** [comment] 2015-07-10 02:00
Cannot reproduce this with FF42 (nightly channel) on Win7, v0.9.9.4
works just fine here.

**Comment by gorhill** [comment] 2015-07-10 02:05
Which 0.9.9.4? This was fixed in the last one, dev.7.

**Comment by androidland** [comment] 2015-07-10 02:18
@gorhil, ok, that was fixed, i just install the last version dev 7 now, thanks

**Closed** 2015-07-10 02:18 UTC
