### ISSUE TITLE
Cloud storage not working

### ISSUE THREAD

**Issue by rihadik** [gorhill/uBlock#2083] opened 2016-10-18 13:32 UTC
Hi, I can upload settings using FF on one machine, but I can't download them on another. Device names are auto-generated and include different host names. I can set the second machine's device name to be the same as the first machine's, but it doesn't change anything. Each machine can only upload/download its own settings.
- Browser/version:  49.0.1
- uBlock Origin version: 1.9.12

**Comment by gorhill** [comment] 2016-10-18 13:35
Are you logging in your Sync account? If so, is this the same Sync account on the other computer?

**Comment by rihadik** [comment] 2016-10-18 13:43
Yes, I'm logged in to both using the same email address. I've checked only two of the boxes in FF sync settings: bookmarks, add-ons.

**Comment by gorhill** [comment] 2016-10-18 13:46
Please mind the other points, i.e. leaving the time for each Firefox instances to push/pull data from the central server. Also, once you are confident the changes have been pushed/pulled, then and only then open uBO's dashboard.

**Comment by Piter432** [comment] 2016-10-20 22:41
Similar problem is in Chromium-based browsers or at least in Chrome. I'm not sure if you remember the reported bug, @gorhill, but if not, I can remind you (and explain btw. to the rest of uBO's users): 
If I have too many selected filters lists/custom filters/custom dynamic rules/custom sites in whitelist, I can't sync them with Google account on Chrome (I can only download and download with combining them). However, the same number of selected filters lists/custom filters/custom dynamic rules/custom sites in whitelist are syncing properly in Firefox (I can upload, download and download with combining them). I don't know is it a problem by the OS I'm using (Windows XP with SP3) or Chrome version (47.0.2526.106) or maybe it's the problem in all 32bit versions of Chrome. I don't believe in first case and especially I don't believe in the second one, but the third one maybe causes my problem, but I can't test this for now :slightly_frowning_face:

**Comment by Snowman-25** [comment] 2016-11-03 13:01
I experience the same problem.
Using the lates Firefox Beta Version on PC and Android (Galaxy S5).

I upload my data from the dashboard on the PC and make sure to manually sync.
After the sync completes, I sync my mobile device. Then opening the uBlock Dashboard on the mobile device, It won't detect any files in the sync-account.

If I choose to upload data from the mobile client, sync all devices multiple times and check the dashboard, the Desktop-PC similarly doesn't see the latest file uploaded from the mobile client.

**Comment by gorhill** [comment] 2016-11-03 14:33
> Then opening the uBlock Dashboard on the mobile device, It won't detect any files in the sync-account.

[Wiki: Cloud storage](https://github.com/gorhill/uBlock/wiki/Cloud-storage):

> It appears Firefox for Android can't sync extensions settings

**Comment by rubaboo** [comment] 2017-02-01 10:25
For this to work, do I need to check "Add-ons" under **Sync across all devices**? I don't have it checked, and have the same issue. Upload appears successful, but nothing gets downloaded on th other side. Signed in to the same account.

**Comment by rubaboo** [comment] 2017-02-01 10:37
Played with it on both sides, they appear to be stored independently. On the same machine, it works. Export to cloud, clear (delete everything), then Import from Cloud - everything that I exported appears back. Wonder if **Device Name** needs to be the same??? Afraid to test that theory, might screw up things.

**Comment by alexolog** [comment] 2017-06-05 15:25
Any news about it?
The sync does not appear to work from FF on Android.

**Comment by gorhill** [comment] 2017-09-10 15:13
Closing: Unable to reproduce, and obsolete.

**Closed by gorhill** 2017-09-10 15:13 UTC
Labels: unable to reproduce
