### ISSUE TITLE
1.7.7b0 does not hide the dom elements

### ISSUE THREAD

**Issue by tleepa** [gorhill/uBlock#1767] opened 2016-06-29 12:42 UTC
Same uBlock settings, Firefox Nightly v50a1.
1.7.6 works fine
1.7.7b0 does not hide anything defined by element hiding rules
The log does not show anything from the dom category (yellow background).

**Comment by gorhill** [comment] 2016-06-29 13:22
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-06-29 13:22 UTC

**Comment by tleepa** [comment] 2016-06-30 05:56
Updated the issue with more details. BTW- 1.7.7b5 is broken too.
Would it still be invalid as it is experienced on Nightly?

**Comment by gorhill** [comment] 2016-06-30 13:17
Still unable to reproduce -- all is working fine here. Be sure you did not disable cosmetic filtering for the site.
