### ISSUE TITLE
[Feature Request] Ability To Open The Logger In The Sidebar Like uMatrix

### ISSUE THREAD

**Issue by zero77** [gorhill/uBlock#3400] opened 2018-01-04 17:04 UTC
Can you please add the ability to open the logger in the sidebar like uMatrix has.
Thanks

**Comment by gorhill** [comment] 2018-01-04 17:12
Duplicate of #2854.

https://github.com/gorhill/uBlock/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sidebar

**Closed by gorhill** 2018-01-04 17:12 UTC
Labels: duplicate
