### ISSUE TITLE
The fix for `elem > :operator` seems to be not right

### ISSUE THREAD

**Issue by jspenguin2017** [gorhill/uBlock#3382] opened 2017-12-31 16:42 UTC
### Describe the issue

The fix here: https://github.com/gorhill/uBlock/commit/37fde84a45ae5b96128c4a272f012223356d8134#diff-1c951eedcd0be2e11c02da8fabcc46b5R336
seems to be not right, as the 3 cases have different behavior. 
Simply adding `*` will cause the selector to behave differently. 

### One or more specific URLs where the issue occurs

`http://example.com/`

### Screenshot in which the issue can be seen

![image](https://user-images.githubusercontent.com/7283682/34463044-5ee6c69a-ee0e-11e7-9bd0-9c80f59ba823.png)

### Steps for anyone to reproduce the issue

1. Enter test link
2. Execute the 3 selectors
3. Observe different result

### Your settings

All default

- OS/version: Win10
- Browser/version: Chrome 
- uBlock Origin version: N/A

##### Your filter lists

All default

##### Your custom filters (if any)

Nothing

**Comment by gorhill** [comment] 2017-12-31 17:03
Transcribed from pic for convenience:

    document.querySelectorAll('body > div > :not(p)');
    document.querySelectorAll('body > div :not(p)');
    document.querySelectorAll('body > div > * :not(p)');

I don't get the issue: these cosmetic filters are not procedural filters, while the commit you point at is strictly for procedural filters.

So this issue currently is just speculated, there is no real repro steps to make the case appending `*` is wrong. But let's assume `:not` is procedural: I don't see any discrepancy in results when appending `*` to a dangling selector:

Same results:
- `NodeList [h1]`
    - `document.querySelectorAll('body > div > :not(p)');`
    - `document.querySelectorAll('body > div > *:not(p)');`
- `NodeList(2) [h1, a]`
    - `document.querySelectorAll('body > div :not(p)');`
    - `document.querySelectorAll('body > div *:not(p)');`
- `NodeList [a]`
    - `document.querySelectorAll('body > div > * :not(p)');`
    - `document.querySelectorAll('body > div > * *:not(p)');`

**Comment by jspenguin2017** [comment] 2017-12-31 17:11
As seen in the image of that post: 
https://user-images.githubusercontent.com/7283682/34429143-5c4ecc10-ec11-11e7-94a3-413008b0ff36.png

If you simply add `*`, it will be duplicate of the rule below, however, ameshkov stated that it is not a duplicate: https://github.com/NanoAdblocker/NanoCore/issues/1#issuecomment-354469939

**Comment by gorhill** [comment] 2017-12-31 17:18
> the two rules indeed behave differently

What two rules? Can you please transcribe these rules here? I posted pairs of rules above to show that appending `*` to make it explicit does not change the behavior of the selector. You can conveniently copy/paste these rules to your console and see the result.

**Comment by gorhill** [comment] 2017-12-31 17:22
Looking at the pic, you were actually right that the two rules could become one:

    dobreprogramy.pl##body > .page_form :matches-css(...)

Replaces both:

    dobreprogramy.pl##body > .page_form > :matches-css(...)
    dobreprogramy.pl##body > .page_form > * :matches-css(...)

**Comment by jspenguin2017** [comment] 2017-12-31 17:35
Oh, true, I missed that part, however, `dobreprogramy.pl##body > .page_form > :matches-css(...)` is not a *duplicate* of `dobreprogramy.pl##body > .page_form > * :matches-css(...)` because one matches only immediate children of `.page_form` and other matches only children of immediate children of `.page_form`. 

Sure they *can* be combined into one filter that matches all children of `.page_form`, but that's only this specific case. What if you only have one of the two filters? Then it'll be different.

**Comment by gorhill** [comment] 2017-12-31 17:44
> because one matches only immediate children of `.page_form  and other matches only children of immediate children of `.page_form`

Sure, I understood that part, I never argued against this. I am merely still trying to understand why you think the fix in the commit is wrong -- and somehow you brought the the case above as being relevant to the issue reported here.

Why do you believe:

    document.querySelectorAll('body > div > :not(p)');

Is not the same as:

    document.querySelectorAll('body > div > *:not(p)');

The second form is what the fix does: add an explicit `*` when the selector is "dangling".

**Comment by jspenguin2017** [comment] 2017-12-31 17:53
I believe it's different because Chrome spit out different node list, and you said: 

> Pseudo operators are meant to mimick what could be a valid CSS selector

**Comment by gorhill** [comment] 2017-12-31 18:56
> it's different because Chrome spit out different node list

Please be loquace, it's starting to feel like pulling teeth. What exactly are **the two selectors** causing two different node lists?

**Comment by jspenguin2017** [comment] 2017-12-31 19:24
OK fine, I'll fix it myself.

**Comment by gorhill** [comment] 2017-12-31 19:51
You are asking me to read your mind.

Look at what I had to go through in order to have _a case_ for me to try, to no avail.

I took the time to provide you [cases demonstrating that there is no issue](https://github.com/gorhill/uBlock/issues/3382#issuecomment-354614554).

For some reasons you have been unwilling to show make the _exact_ issue, including closing the issue here with no further constructive comment, as if me asking you **only the two single selectors** showing the purported issue unambiguously was asking too much.

**Comment by jspenguin2017** [comment] 2017-12-31 19:55
It's really simple: 
- `body > div > :not(p)` is not equivalent to `body > div > * :not(p)`
- `dobreprogramy.pl##body > .page_form > :matches-css(...)` is not equivalent to `dobreprogramy.pl##body > .page_form > * :matches-css(...)`
- The new patch treat `dobreprogramy.pl##body > .page_form > :matches-css(...)` to be the same as `dobreprogramy.pl##body > .page_form > * :matches-css(...)`

I have all explained in posts before, I don't know what is not clear.

**Comment by gorhill** [comment] 2017-12-31 19:58
> `body > div > :not(p)` is not equivalent to `body > div > * :not(p)`

Of course it's not -- I never ever thought it was. The fix does not cause such discrepancy. The fix just add a `*` to a dangling selector. With the fix, the following selector:

    body > div > :not(p)

Become:

    body > div > *:not(p)

Not:

    body > div > * :not(p)

A single `*` is appended, not a `*` followed by a space.

**Comment by jspenguin2017** [comment] 2017-12-31 20:13
OK, so with your fix, 
```
example.com##div > :has(a)
```
is equivalent to 
```
example.com##div > *:has(a)
```

![image](https://user-images.githubusercontent.com/7283682/34463995-d193702c-ee2b-11e7-82cc-61464852be2d.png)
![image](https://user-images.githubusercontent.com/7283682/34464003-1e882012-ee2c-11e7-84f1-0c1a28cace9a.png)
![image](https://user-images.githubusercontent.com/7283682/34464004-23f3d1ae-ee2c-11e7-89f2-25a2460a320a.png)

**Comment by gorhill** [comment] 2017-12-31 20:50
I can reproduce. However the element isn't removed because an exception is thrown. For some reasons the prefix selector is an object rather than a string.

**Comment by jspenguin2017** [comment] 2017-12-31 20:51
Really... Eh, I guess I read the code wrong. 
Well, I only got a theoretical case and not a real one, you said last time you don't want theoretical issues so I didn't post it before. 
Well, should've check the console... My bad.

**Comment by gorhill** [comment] 2017-12-31 20:53
Ok, it's because I modified `:has()` to behave like `:if()`, because uBO was rejecting many filters from Adguard lists which were using `:has` with procedural selectors as args, while uBO wouldn't allow this.

**Closed** 2017-12-31 21:05 UTC

**Comment by gorhill** [comment] 2017-12-31 21:19
I really need a test page that would at least test most filters at once and this would allow me to quickly assess whether something is broken. The breakage was bad here, essentially all `:has` filters were broken, but I ended up focusing strictly on the parsing, and I did not pay attention to the end result.
