### ISSUE TITLE
Can you add a simple button to disable Ublock everywhere?

### ISSUE THREAD

**Issue by bottleblue** [gorhill/uBlock#1080] opened 2015-12-16 20:57 UTC
I read the wiki on how to disable ublock globally (https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere) but I feel it's more tedious than it should be. The advanced user option has to be enabled in order to access the dynamic rules list to disable ublock. I don't consider myself an advanced user so I don't have the advanced user option checked by default. So I would need to go into Ublock's option to enable it and then mark the rules list and then when I want to enable Ublock again I have unmark the rules list and disable advanced users option.

I would probably leave advanced users option on if the tooltips still worked because I don't have the icon functions memorized.

It would probably be easier to go into Addon Manager and just disable the extension but I still have to open a tab for it and scroll down and search for the addon name which is annoying. Isn't the point of having a toolbar icon is so we can conveniently access everything we need to?

Why not just add another icon next to the power icon? Maybe an icon of a globe with the power symbol over it?

**Comment by gorhill** [comment] 2015-12-16 21:03
Duplicate of #167,

**Closed by gorhill** 2015-12-16 21:03 UTC
