### ISSUE TITLE
ui anomalies

### ISSUE THREAD

**Issue by weakptr** [gorhill/uBlock#455] opened 2015-07-07 04:31 UTC
Both issues pertain to Firefox 39 with build 0.9.9.4 i.e. since introduction of DOM inspector.

1. Have home page set as about:home. Launch Firefox then click on uBlock0's icon and the popup will display incorrectly. (Close and reopen the popup and it displays correctly.)
![pop](https://cloud.githubusercontent.com/assets/11945341/8538662/4761b3f8-24b3-11e5-82e8-f36d36bfa06d.jpg)

2. Scrolled content in the logger can extend upwards beyond the logger's options (erase, filter etc).
![log_scroll](https://cloud.githubusercontent.com/assets/11945341/8538717/26ba735a-24b4-11e5-928e-8e38bcc75a1a.JPG)

**Comment by CrisBRM** [comment] 2015-07-07 05:27
Could you try uninstalling uBlock, closing the browser, and then installing it again? I had a similar issue with the DOM inspector and uninstalling it fixed it.

**Comment by weakptr** [comment] 2015-07-07 05:37
@CrisBRM

Both issues have been reproduced with multiple uBlock installations on clean FireFox profiles in an XP sp3 VM as well as in Cyberfox on Win 7x64.

**Comment by CrisBRM** [comment] 2015-07-07 05:41
Well, I have just tried it on a clean FF stable/dev profile (Funtoo/Windows 8.1) and failed to reproduce the issue.
Good luck!

**Comment by quilloss** [comment] 2015-07-07 08:20
I can reproduce on Firefox 40.0b1 Windows 7 x64 with a clean profile.
As observed by weakptr it only occurs for the first launch of the popup.
I can reproduce even after navigating from the homepage to ```about:blank``` and ```about:addons```.
Navigating to Google however results in a proper popup.

**Comment by gorhill** [comment] 2015-07-07 11:42
I've seen this.

**Comment by gorhill** [comment] 2015-07-07 13:12
> 2. Scrolled content in the logger can extend upwards beyond the logger's options (erase, filter etc).

By design. There is no harm to have the toolbar float over the logged entries.

**Comment by gorhill** [comment] 2015-07-08 12:50
> Close and reopen the popup and it displays correctly

It looks like it's more of a delay thing. If I wait ~8 seconds to open the popup, it will look fine. If I open early, it's not fine. And this happens only for `about:[...]` pages, after launch.

**Closed** 2015-07-08 13:56 UTC
