### ISSUE TITLE
uBlock blocks https direct image URLs (page won't load)

### ISSUE THREAD

**Issue by jurok04** [gorhill/uBlock#2931] opened 2017-08-30 10:51 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Some short time ago (2-5 days) those URL won't open with uBlock is Enabled in Mozilla FF (55.0.3 x86). Whitelistening is working correct, as shown in uBlock network log, but image won't don't load - only white screen apeears. ONLy when uBlock is Disabled, page will load correctly. Tested with uBlock versions  1.13.10 and 1.13.11rc0 from Mozilla browser extensions page. 

### One or more specific URLs where the issue occurs
https://nik.bot.nu/o2744589.png
OR
anr image from this page opens with blank screen when uBlock is set to ENABLED in Mozilla extensions page.
https://nik.bot.nu/browse.fu?f=0&e=20&g=2&a=999&d=0&h=5&j=0&k=0&l=&m=&n=&o=0&q=0&b=0
for example this
https://nik.bot.nu/o2750291.jpg
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
Situation is similar to this iisue, only differency is HTTPS protocol in my case:
also this link won't not load:
http://i.imgur.com/LLfAiSh.png

[Screenshot(s) for visual issues are **mandatory**]
https://user-images.githubusercontent.com/22996586/29866972-cad896ae-8d82-11e7-9090-e2f880ed4a48.gif

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 7 Home. SP1 x64
- Browser/version: Mozilla Firefox (55.0.3 x86 RUS). 
- uBlock Origin version: 1.13.10 and 1.13.11rc0

##### Your filter lists
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Unbreak​​​​​
EasyPrivacy
Malware Domain List
Malware domains
LVA: Latvian List
RUS: BitBlock List 
RUS: RU AdList 
facebook annoyances blocker
​​facebook news feed annoyances blocker​​
​​​​​Youtube: Other Annoyances​​
​​​[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
! YANDEX
yandex.ru##.popup__content.distr-popup__content
yandex.ru##.popup_visibility_visible.popup_js_inited.dist_js_inited.i-bem.dist_theme_default-popup.dist_modal_yes.dist_action_landing.dist_kind_popup.dist.popup_adaptive_no.popup_theme_ffffff.popup_autoclosable_no.popup_position_fixed.popup_animate_yes.popup_type_modal.popup > .popup__content > .dist__title
yandex.ru##.popup_visibility_visible.popup_js_inited.dist_js_inited.i-bem.dist_theme_default-popup.dist_modal_yes.dist_action_landing.dist_kind_popup.dist.popup_adaptive_no.popup_theme_ffffff.popup_autoclosable_no.popup_position_fixed.popup_animate_yes.popup_type_modal.popup > .popup__content > .dist__button_kind_popup.dist__button_action_landing.dist__button > .button2_js_inited.i-bem.button2_type_link.button2_theme_action.button2_size_m.button2
! GOOGLE
www.google.lv##.gb_g.gb_ga
mail.google.com###f2tLgc
||mail.google.com/mail/u/0/?ui=2&view=dim&iv=amo1tqfqsw2s&it=ic$image
mail.google.com##body > div:nth-of-type(7) > .nH > .nH > .aiw.w-asV.nH > .nH:nth-of-type(5) > .no > .nn.nH:nth-of-type(2) > .oy8Mbf.nH:nth-of-type(2) > .w-atd.w-asK > .J-J5-Ji
mail.google.com##body > div:nth-of-type(7) > .nH > .nH > .aiw.w-asV.nH > .nH:nth-of-type(5) > .no > .nn.nH:nth-of-type(2) > .oy8Mbf.nH:nth-of-type(2) > .w-atd.w-asK
! GOROD.lv/
||gorod.tunt.lv/red/_201604/90-084026-1120x100_tomtailor.jpg$image
||gorod.tunt.lv/*.*$image
! HABRAHABR-RU Geektimes
habrahabr.ru##div.xyz_wrapper
habrahabr.ru##div.html_banner_wrap
habrahabr.ru##.default-block
habrahabr.ru##.article_preview.article
habrahabr.ru##.promo-block_freelansim-tasks.promo-block
geektimes.ru##.promo-block_freelansim-tasks.promo-block
geektimes.ru##.default-block
! LATTELECOM.lv/
||mans.lattelecom.lv/images/modules/banners/1462265499lv.png$image
! ARTLEBEDEV.ru/ and tema.livejournal.com
www.artlebedev.ru##.e__hc__popup.hc__authorization.hcc > .hc__authorization__wrap.hcc > .hc__authorization__box.hcc
www.artlebedev.ru##.e__hc__popup.hc__authorization.hcc > .hc__authorization__wrap.hcc > .hc__authorization__box.hcc
||lj-toys.com/?mode=aviasales_flights_hotels&api=d030aa5d579c91ed88dcb35df4dc4061$subdocument
||lj-toys.com/?mode=aviasales_flights&api=bfbbf3e748af38e77a35f7eb822158b1$subdocument
! FACEBOOK.com/ Blocks Registration Alert
www.facebook.com###pagelet_growth_expanding_cta
www.facebook.com###u_0_0
www.facebook.com###u_0_1
www.facebook.com###u_0_2
www.facebook.com###u_0_3
www.facebook.com###u_0_4
www.facebook.com###u_0_5
www.facebook.com###u_0_6
www.facebook.com###u_0_7
www.facebook.com###u_0_8
ru-ru.facebook.com###u_0_0
ru-ru.facebook.com###u_0_1
ru-ru.facebook.com###u_0_2
ru-ru.facebook.com###u_0_3
ru-ru.facebook.com###u_0_4
ru-ru.facebook.com###u_0_5
ru-ru.facebook.com###u_0_6
! INBOX.lv
www.inbox.lv###content-center
||pform.net/w/img/*/*/*-*.jpg$image
www.inbox.lv##.slick-active.slick-current.slick-slide > div > .initial_slide.carousel-slide-1.carousel-slide > .col-widget-1.carousel_inner.col-xs-12 > .row > .col-lg-12.col-sm-6.col-xs-12.small_news
www.inbox.lv##.slick-active.slick-current.slick-slide > div > .initial_slide.carousel-slide-1.carousel-slide > .col-widget-1.carousel_inner.col-xs-12 > .row > .col-lg-12.col-sm-6.col-xs-12.main_news_wrapper
!  http://www.nasha.lv/
www.nasha.lv##.share-window-wrapper
www.nasha.lv##.share-window
! DELFI.lv
rus.delfi.lv##.*.notification-widget
rus.delfi.lv##..notification-widget
rus.delfi.lv##.notification-container
rus.delfi.lv##.notification-button
rus.delfi.lv##.fairPlay.notification-widget
www.delfi.lv##.notification-widget
www.delfi.lv##.notification-container
www.delfi.lv##.notification-button
! VARIOUS bad sites!!! 
*.olybet.com
*swissguardpro.com
||www.server-kino.ru//download-icon2.png$image
! 24.03.2017, 15:58:08 http://www.grani.lv/
||www.grani.lv/uploads/banners/*.*$image
! 24.03.2017, 15:58:31 http://www.grani.lv/
||www.grani.lv/uploads/banners/*.gif$image
! 06.04.2017, 14:45:15 http://www.kurpirkt.lv/
||files.mcloudglobal.com/creatives/richmedia/2711490282970.html$subdocument
! Hint: https://github.com/pafnuty/onlineConsultantBlocker
||cloudleadia.com^$third-party
||code.jivosite.com/script/$third-party
||leadiacloud.com^$third-party
||leadobur.com/widget/$third-party
||lediacloud.com^$third-party
||leetero.ru^$third-party
||cloud.lexprofit.ru^$third-party
||cs15.livetex.ru/js/$third-party
||clients.streamwood.ru^$third-party
||uptocall.com/widget/$third-party
||uptolike.com/widgets/$third-party
pravoved.ru## div.leadAside
! 27.04.2017, 12:35:30 https://habrahabr.ru/feed/page2/
habrahabr.ru##.promo-block_vacancies.promo-block

**Comment by gorhill** [comment] 2017-08-30 11:29
Anything at the browser console (ctrl-shift-j)?

Is your Firefox 64- or 32-bit?

**Comment by gorhill** [comment] 2017-08-30 11:31
Duplicate of #2930/

**Closed by gorhill** 2017-08-30 11:31 UTC
Labels: duplicate, unable to reproduce
