### ISSUE TITLE
Ublock origin 1.14.4 is slower than Adblock plus 2.9.1

### ISSUE THREAD

**Issue by S3ndG** [gorhill/uBlock#2956] opened 2017-09-02 11:36 UTC
- I compared Ublock origin 1.14.4 to Adblock plus 2.9.1 and I noticed that Firefox' browsing is slower with Ublock than with adblock. 
While Ublock origin became a Webextension, I noticed It became also slower during browsing the web.

- my settings : 

- OS/version:  windows 8.1 64 bit
- Browser/version:  firefox 55.0.3 64 bit
- uBlock Origin version: 1.14.4

- my filter lists : 
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Unbreak

Adblock Warning Removal List
EasyList

FRA: EasyList Liste FR

- my custom filters : 
! 28/05/2016 à 14:12:29 http://www.clubic.com/mag/transports/article-806692-1-roolin-smart-velo-electrique.html
www.clubic.com##.content-wrapper > .iRYCpKze

! 30/05/2016 à 11:45:40 http://www.clubic.com/carte-graphique/carte-graphique-nvidia/article-807190-1-test-nvidia-geforce-gtx-1070.html
||img.clubic.com/46036218-undo-few-DBI9CM4K-headhunter-clair-ghost-value-yokes.jpg$image

! 17/06/2016 à 08:54:46 http://forum.doctissimo.fr/forum1f.php?config=psychologie.inc&owntopic=1&new=0&nojs=0
forum.doctissimo.fr###best_forum_rated_post_list

! 25/06/2016 à 17:59:47 http://forum.doctissimo.fr/psychologie/liste_categorie.htm
forum.doctissimo.fr###keylink-video > .row.keyling-bloc-content > .video-bloc.col-md-6.col-xs-12

! 04/07/2016 à 18:21:46 http://www.metrolyrics.com/be-here-now-lyrics-oasis.html
||www.metrolyrics.com/iframes/vadioplayer/$subdocument

! 09/09/2016 à 11:53:52 http://forum.doctissimo.fr/
forum.doctissimo.fr##body > div:nth-of-type(1)

! 10/09/2016 à 10:44:04 http://www.doctissimo.fr/html/sexualite/dossiers/reves-erotiques/8897-reves-erotiques-traduction.htm
www.doctissimo.fr##body > div:nth-of-type(1)

! 12/09/2016 à 17:35:22 https://zimbra.free.fr/logout.pl
||passback.free.fr/webmails/html/generated/actu.html$subdocument

! 25/11/2016 à 13:31:46 https://www.freenews.fr/
www.freenews.fr###insidepic_widget

! 09/05/2017 à 13:47:18 http://www.metrolyrics.com/7475-lyrics-connells.html
||www.metrolyrics.com/iframes/canplayer/56840/1$subdocument

@@||i-cms.journaldunet.com/image_cms/$image

! 21/08/2017 à 19:30:39 http://tpb.proxyduck.info/visit.php?u=https%3A%2F%2Fthepiratebay.org%2Ftorrent%2F6277305%2FShakespeare_in_Love_%281998%29_720p_BrRip_mkv_-_600MB_-_YIFY&b=0
||tpb.proxyduck.info/visit.php?u=https%3A%2F%2Fthepiratebay.org%2Fstatic%2Fads%2Fexo_na%2Fsky1.html&b=0&f=frame$subdocument

**Comment by gorhill** [comment] 2017-09-02 11:51
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-09-02 11:51 UTC
Labels: invalid

**Comment by gorhill** [comment] 2017-09-02 12:08
> _speculated_ performance issues will be marked as invalid and closed if they do not come with **actual profiling data + analysis** supporting the claim

You have your work cut out, given that ABP still relies on synchronous `shouldLoad` to do its job, while uBO has not been using `shouldLoad` for months now -- using synchronous `shouldLoad` is a performance killer. In any case, respect the rule above, I won't look at anything else than **valid** profiling data.

**Comment by S3ndG** [comment] 2017-09-03 08:13
In fact, I just notice than the Ublock origin webextension is slower than the legacy version.
About that, I'm not a developer so I don't know how to do a valid profiling. Should I use Geckoprofiler extension, or the in-built firefox profiler?
Thanks.

**Comment by gwarser** [comment] 2017-09-03 10:14
Firefox ESR 52.3.0
`https://www.washingtonpost.com/`
1.13.8
Average (valid): 3972.33 ms (11/17 iterations)  Last reload: 3550.66 ms
1.14.7rc0 legacy
Average (valid): 4509.93 ms (11/17 iterations)  Last reload: 5113.02 ms

**Comment by gorhill** [comment] 2017-09-03 10:38
Gecko profiler is the way to go, it's the best tool to profile performance issues -- it's one of the tool I wish Chromium also had, and the result can easily be shared with others a simple URL.

Keep in mind that uBO/webext is pretty much the same code as uBO/webext, except for the Firefox API used.

Now if your claim is that  uBlock Origin 1.14.4 is slower than legacy version, that's is a much more sensible claim, the webext API framework _may_ add overhead that was not present in the legacy version -- but then again, only profiling can tell. Regardless, the new webext API is the way to go, it's wholly asynchronous, so that no API call can block the whole browser, as opposed to the old framework.

@gwarser The webext framework in Firefox 52 ESR was in its early development, I think at this point it's worth to profile using FF56 or FF57, these are the versions for which Firefox devs can still do something about it.

I personally use FF57, a lot of performance improvements has gone in it, and I am still assuming that more will be made. Additionally, I use uBO out-of-process, and as the only extension so it ends up in its own dedicated process, my experience is that it works pretty well performance-wise so far, Nightly has become my main browser as a result, I now use Chromium only for testing purpose.

**Comment by gwarser** [comment] 2017-09-03 11:05
Nightly looks like this:
1.13.8 - legacy enabled, not sure it works - missing UBO interface
Average (valid): 3376.66 ms (11/13 iterations)  Last reload: 3334.63 ms
1.14.5rc1 - little hiccup? 
Average (valid): 4057.34 ms (11/16 iterations)  Last reload: 4119.23 ms
1.14.7rc0
Average (valid): 3210.93 ms (11/15 iterations)  Last reload: 2966.09 ms

**Comment by gorhill** [comment] 2017-09-03 11:38
Code change between [1.14.5rc1 and 1.14.7rc0](https://github.com/gorhill/uBlock/compare/1.14.5rc1...master) can't explain the difference. Note that the page load speed tool can be affected by external factors, like network latency, cache usage, other extensions, etc.

**Comment by S3ndG** [comment] 2017-09-03 13:04
I have tested ublock origin 1.14.4 and 1.14.7rc0 with gecko profiler and cache usage disabled but I cannot download the version 1.13.8 from AMO despite the fact I have set the pref **extensions.legacy.enabled** to true
Do you know how can I install the 1.13.8 in Nightly 57?
thank you.

**Comment by gorhill** [comment] 2017-09-03 13:10
Just download `uBlock0.firefox.xpi` from the [releases section](https://github.com/gorhill/uBlock/releases) (right-click and "Save Link as..."). It does not have to be 1.13.8, I still build the legacy version for each release. You will have to toggle the setting `xpinstall.signatures.required` to `false`.

**Comment by S3ndG** [comment] 2017-09-03 13:24
Mmmh... I have installed the version 1.14.7rc0 (legacy) but it doesn't work in nightly 57. The ads are still displayed and the button/icon is not visible.
If you have any idea so I could test a legacy version... (with the built-in profiler? I never used it yet)

**Comment by gorhill** [comment] 2017-09-03 14:18
Ok, it seems legacy is no longer working in FF57 -- it worked when Nightly became 57, but it was planned that Firefox devs would start to remove stuff which would break legacy extensions. So profiling for legacy will have to be done with FF56 or FF55.

**Comment by S3ndG** [comment] 2017-09-03 14:37
Okay so I have made some tests with firefox 55.0.3 64 bit. Here are the profiles links:
**http://www.zdnet.fr/**

_ublock origin 1.14.4 webext:_
https://perf-html.io/public/ca3a9544fbfc670e3fd10618883d2959fe632b0d/calltree/?hiddenThreads=&thread=2&threadOrder=0-2-3-1-4

_ublock origin 1.13.8 legacy:_
https://perf-html.io/public/b3dd37e9f32acdceec7928a71a03423b9003d9aa/calltree/?hiddenThreads=&thread=2&threadOrder=0-2-3-1-4

**Comment by gorhill** [comment] 2017-09-03 15:17
Thanks for profile results.

Now to isolate uBO's own contribution to CPU usage, I filter using `ublock0` for the legacy profiling, and `moz-` for the webext profiling (assuming only uBO is installed).

- I selected the area where it appears the page load occurred.
    - I selected the main thread in both and compare the timings: FF56=99ms, FF57=87ms.
    - I selected the content thread in both and compare the timings FF56=59ms, FF57=81ms.

So I didn't see any meaningful timing difference between both profiles for uBO's own code.

I don't see that much of a difference on Firefox's code side, this could be all down to noise. Best is if you think the profiling result demonstrate a significant performance regression, just open an issue on bugzilla and share these results, they are best placed than me to judge whether there is anything concerning in there.
