### ISSUE TITLE
Disable media device fingerprinting

### ISSUE THREAD

**Issue by RoxKilly** [gorhill/uBlock#2378] opened 2017-02-14 20:13 UTC
### Describe the issue
Since Firefox 39, it may be possible for Javascript to fingerprint hardware media devices (microphones, cameras, etc...) through the `MediaDevices API` - in particular [MediaDevices.enumerateDevices()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices)

This can be disabled by setting the user preference `media.navigator.enabled = false` (source: search for the preference [on this page](http://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings/)

Since `uBlock Origin` has a privacy section in its settings, I wondered whether you would be interested in adding this option.

**Comment by gorhill** [comment] 2017-02-14 20:18
Duplicate of #1647 and many other such requests: counter-fingerprinting is a huge undertaking, worthy of being its own extension. People will have to find another developer, I can't volunteer for even more stuff.

**Closed by gorhill** 2017-02-14 20:18 UTC

**Comment by Atavic** [comment] 2017-02-14 20:22
You can modify [user.js](http://www.ghacks.net/2017/02/12/ghacks-net-firefox-user-js-config-0-11-is-out/) against privacy leaks, then use ublock for specific page elements.
