### ISSUE TITLE
Ublock forbid the Firefox devtools CSS editor to enumerate CSS files

### ISSUE THREAD

**Issue by mikhoul** [gorhill/uBlock#2169] opened 2016-11-21 19:37 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

Ublock forbid the Firefox devtools CSS editor to enumerate CSS files in the left pane.

### One or more specific URLs where the issue occurs

https://www.google.ca/search?q=Best+Kodi+airmouse&gws_rd=ssl

### Screenshot in which the issue can be seen

Screencast to show the issue: http://screencast-o-matic.com/watch/cDXrq1QfyI

### Steps for anyone to reproduce the issue

1. Enable UBO
2. Copy this link in the Clipboard: https://www.google.ca/search?q=Best+Kodi+airmouse&gws_rd=ssl
3. Paste the link in the URL Bar
4. Open Devtools go to CSS Editor
5. Spinning Animated Wheel stay forever in the left pane without any CSS listing.
6. Close Devtools
7. Disable UBO
8. Paste again the URL in the URLbar
9. Open Devtools go to CSS Editor
10. The CSS sheet are listed in the left pane (when UBO is disabled)

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version:  Firefox 50
- uBlock Origin version:  1.9.17b7

##### Your filter lists
![GitHub Logo](http://i.imgur.com/datTMdF.png)
http://i.imgur.com/datTMdF.png

**Comment by gorhill** [comment] 2016-11-21 20:54
Can't reproduce using default settings + EasyList France.

Did you look what the logger says?

**Comment by mikhoul** [comment] 2016-11-21 21:11
Hi @gorhill 

Here's the logger screenshot: http://i.imgur.com/GHgFxy0.png

And also I found another thing that can help you, in the Browser console there is nothing special that happen **till**  I close the devtool. 

As soon the devtools are closed it return this message in the console:
```

 16:01:30,638 Error: Connection closed, pending request to server1.conn14.child1/styleSheetsActor8, type getStyleSheets failed

Request stack:
Front<.request@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/protocol.js:1221:7
generateRequestMethods/</frontProto[name]@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/protocol.js:1359:14
StyleEditorUI.prototype._onNewDocument@resource://devtools/client/styleeditor/StyleEditorUI.jsm:234:5
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/event-emitter.js:191:13
TabTarget.prototype._setupRemoteListeners/this._onTabNavigated@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/framework/target.js:507:9
eventSource/aProto.emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js:131:9
DebuggerClient.prototype.onPacket@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/client/main.js:1006:7
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/transport/transport.js:569:13
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14

Trace de la pile :
Front<.destroy@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/protocol.js:1168:23
StyleEditorPanel.prototype.destroy@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/client/styleeditor/styleeditor-panel.js:138:7
Toolbox.prototype.destroy@resource://gre/modules/commonjs/toolkit/loader.js -> 
```


It's like if UBO stop some request to be fulfilled  ?  But I really don't know enough to be able to decipher why it happen.


Regards ! :octocat:

**Comment by gorhill** [comment] 2016-11-21 21:14
> Here's the logger screenshot

Please, I prefer you _investigate_ the logger output rather than just screenshot it partly like you did. Use the _All_ entry in the logger to investigate, this will show _all_ network requests, including those from behind-the-scene. I suspect you are blocking them through your own (undisclosed) settings. Report what you find.

**Comment by mikhoul** [comment] 2016-11-21 21:44
Nothing undisclosed here @gorhill 

Here's the logger with the ALL entry: http://i.imgur.com/vuhOBPd.png

They are the same entry blocked as previously.

If I made an exception with the dynamic filter "https://www.google.ca/gen_204"  the CSS is listed again.

Here's the logger with the dynamic exception filter: http://i.imgur.com/cGcDBC9.png

But why UBO when it blocking Google stuffs block also the devtools from listing all the CSS sheets ?

**Comment by gorhill** [comment] 2016-11-21 22:02
![a](https://cloud.githubusercontent.com/assets/585534/20502513/54181138-b00c-11e6-85f9-db7fea149015.png)

**Comment by gorhill** [comment] 2016-11-21 22:32
Unless I can reproduce on my side, you will have to investigate why this happens on your side. I cannot really make sense of why force-allowing images from `https://www.google.ca/gen_204` would make a difference. However I see you are also force-allowing a frame from `clients5.google.com`, something that does not show up on my side. Could this be the one entry related to the issue?

**Comment by mikhoul** [comment] 2016-11-22 03:12
Yes you are right it is the `clients5.google.com` but I don't understand more why it influence the CSS listing in the FF Devtools ? 

![](http://i.imgur.com/KKya234.png)

Regards :octocat:

**Comment by gorhill** [comment] 2016-11-22 05:55
Ok, I can reproduce. Looking at your log I figure you might have been logged in into your Google account. Doing so on my side, I now get the issue. I will try to investigate tomorrow morning.

**Comment by gorhill** [comment] 2016-11-22 13:18
I get the same issue with ABP.

**Comment by gorhill** [comment] 2016-11-22 13:48
I lean toward a Firefox issue. If I manually delete the problematic `iframe` element (which appears right before the closing `body` tag), close the inspector, re-open the inspector, the style pane display properly thereafter.

**Comment by gorhill** [comment] 2016-11-22 14:48
Browser issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1222991

**Closed by gorhill** 2016-11-22 14:48 UTC

**Comment by mikhoul** [comment] 2016-11-23 01:57
Thanks a lot @gorhill  I will follow the bug on bugzilla ! :octocat:
