### ISSUE TITLE
Seamonkey Support?

### ISSUE THREAD

**Issue by Xylemon** [gorhill/uBlock#174] opened 2015-05-05 16:47 UTC
Currently uBlock0 works but there are some major problems. For one, the "3rd part filters" tab will not list any filters the next time you restart after install the extension. And there is no button (see https://github.com/chrisaljoudi/uBlock/issues/550).

**Comment by gorhill** [comment] 2015-05-05 17:07
Duplicate of [#49](https://github.com/gorhill/uBlock/issues/49#issuecomment-96404549).

Please search existing issues before filing a new one.

**Closed as completed by gorhill** 2015-05-05 17:07 UTC

**Comment by Xylemon** [comment] 2015-05-05 17:12
Didn't see it but I suppose I'll switch over to Chris' version, it seems that there is actually experimental supports for these types of browsers anyway.
