### ISSUE TITLE
chromium browser - ublock bug

### ISSUE THREAD

**Issue by mat41997** [gorhill/uBlock#3199] opened 2017-11-04 20:49 UTC
https://github.com/MajkiIT/polish-ads-filter/issues/4225#issuecomment-341928320

**Comment by gorhill** [comment] 2017-11-04 21:03
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by gwarser** [comment] 2017-11-04 23:03
Using UBO 1.14.12 on Chromium 62.0.3202.75

 - UBO default setting without regional filters
 - add `dobreprogramy.pl##.gamescarousel` to My filters
 - go to https://www.dobreprogramy.pl/
 - this element is not blocked:




![image](https://user-images.githubusercontent.com/886325/32410251-47929c0e-c1bc-11e7-96ed-fd147c91704a.png)




 - use UBO dev 1.14.17.100
 - add this filter `###cookiesPanel:not(body):not(html)`
 - cookie message on top of page is not blocked:



![image](https://user-images.githubusercontent.com/886325/32410261-90a0c3bc-c1bc-11e7-990a-9712eda466a7.png)


 - works again if `:not(body):not(html)` part is removed from filter

**Comment by gorhill** [comment] 2017-11-05 03:49
For case 1, the site is removing uBO's injected CSS rules. This is unfortunately a Chrome issue, it does not support user styles. uBO tries its best to deal with this by adding `display: none !important` as inline style, but it does so only if it sees it's needed when it detects an element's inline style was tampered with -- the usual way sites would work around blockers is to add inline style `display: block !important`. This site just removes uBO's style, and this does not trigger uBO's tampering detection code.

This does not happen with uBO dev build because I changed the way I insert the CSS rules, but it's just a matter of time before the site figure this and add code to deal with the new code. With such cases, I just advise people to use Firefox, it supports user styles and sites cannot remove uBO's injected styles. There is  also quite less of an overhead with Firefox in dealing with cosmetic filtering as uBO does not have to constantly keep an eye on the visibility of elements it's supposed to hide -- something it has to do with Chrome, and with no guarantee of results as seen here

For case 2, I can reproduce, this is a regression as a result of all the changes.

**Closed** 2017-11-05 04:09 UTC
