### ISSUE TITLE
Farbsehschwäche/color vision deficiency is more logical than color blind

### ISSUE THREAD

**Issue by ghost** [gorhill/uBlock#893] opened 2015-11-01 18:04 UTC
Please just delete this issue. It just causes useless debate.

**Comment by rafuse** [comment] 2015-11-01 18:19
Ridiculous.

**Comment by gorhill** [comment] 2015-11-01 18:34
For any issue with the German translation, this needs to be taken to [Crowdin](https://crowdin.com/project/ublock) with other German translators/proofreaders -- I don't know German, so I can't be the one deciding on behalf of whoever.

For the English version, [Wikipedia says](https://en.wikipedia.org/wiki/Color_blindness):

> Color blindness, or color vision deficiency, is the inability or decreased ability to see color [...]

The [National Eye Institute says](https://nei.nih.gov/health/color_blindness/facts_about):

> Facts About Color Blindness

So looks like there is nothing wrong using "color blind".

**Comment by DjogaRo** [comment] 2015-11-01 19:23
I'd say that's political correctness backfiring. What I find really insulting is to deny "Farbenblinden" their relevance. There are those for whom being "farbenblind" means not being able to distinguish colors at all. And as far as I know that comes in a package of really fucked up vision. So there are no distinguishable colors. And if measures for those who need it desperately are also beneficial to people who have a color vision deficiency, nice side effect.

Stop being insulting, please.

**Comment by maelh** [comment] 2015-11-01 19:30
The official medical term is "Farbsehschwäche" in Germany.

Besides, obviously if you apply basic logic as a programmer, you would know it is obviously not about blindness. But stay ignorant and arrogant.

**Comment by CrisBRM** [comment] 2015-11-01 19:39
@maelh Stop wasting programmer time with your trivial issues.

**Comment by maelh** [comment] 2015-11-01 19:42
"Color blindness, or color vision deficiency, is the inability or decreased ability to see color, or perceive color differences, under normal lighting conditions. "
Both terms are used. Just use the appropriate one.

**Comment by CrisBRM** [comment] 2015-11-01 19:45
Are you being intentionally obtuse? Political correctness is cancer. Gorhill has already told you to take it up with the German translators at crowdin.

>For any issue with the German translation, this needs to be taken to Crowdin with other German translators/proofreaders -- I don't know German, so I can't be the one deciding on behalf of whoever.

**Comment by maelh** [comment] 2015-11-01 19:46
@CrisBRM Look, I am not interested in a personal fight with you or anyone. Stop your ad hominem attacks, if you will please. I am talking about the general term and mindest, because it annoys me that color vision deficiency is an afterthought in programming. Got that?

**Comment by gorhill** [comment] 2015-11-01 20:21
> I am not interested in a personal fight with you or anyone.

Why do you insist I use "Color vision deficiency" when I showed you that either expression is accepted? If the National Eye Institute primarily uses "color blindness" in its documentation, this means there is no good reasons to change.

**Comment by maelh** [comment] 2015-11-01 21:03
This is a longer reply, so I may explain a few points. But it's not "political" or "arguing" I hope.

To answer your question: I insist because clear terminology improves understanding and thereby design. I see a lot of people who think color blind means you cannot distinguish colors, and thereby just remove them or replace them with other colors. However, for most people it is about shades of colors. For example: while someone might have trouble discerning green and red, this usually only applies to some shades of those colors, not red and green in general.

That's for example the reason why red lights have a specific green (that's blue green or green whitish) and brighter red to avoid this problem.

Also there are people, though admittedly less, who have problems discerning blue and yellow. So color blind really does not describe the situation well, and is a question of perspective. Because it's a much bigger range the fuzzier term color vision deficiency describes it better.
But admittedly even then, depending on age, light, screen etc. people might have trouble discerning colors. So wouldn't even search for such a term or the options wouldn't help, because it might be a brightness or contrast problem.

But high contrast colors, limiting the range of shades and the number of colors automatically reduces the potential for problems.

If this is not an option, choosing colors based on what actually happens would be more informative:
For example having a combobox labeled: "colors": with the options "blue and yellow", "red and green", and possibly others.

This makes it more objective and less up to interpretation what change will actually happen.

The problem with seeing color vision deficiency as blindness is that often the result is just removing colors, instead of increasing contrast, or avoiding designs that use a lot of different shades.

For example you might be used to the meaning of red and green, and intuitively react to this and interpret it right. Choosing yellow and blue means you need to relearn the meaning, and the advantage of quickly assessing a situation does not work anymore. This is a trivial example, but I hope it explains what I am aiming at.

Many graphs and representations are harder to read because of fashion changes in colors, and require a lot of effort to "fix" or look at precisely while it really would not be necessary and less effort if the first focus was on usability. That's why it matters, and is not about political correctness or similar topics.

It's just a detail in your software. Thanks for your great work! I appreciate it.

**Comment by gorhill** [comment] 2015-11-01 23:49
The choices of colors for color-blind mode was chosen based on this work: <https://github.com/chrisaljoudi/uBlock/issues/467#issuecomment-95177219>.

Currently the label is "Color blind mode". How would you re-label it for "Color vision deficiency"?

**Comment by maelh** [comment] 2015-11-02 00:04
Maybe just have a label "color palette" (instead of "color blind mode") or possibly "color settings".
Then as options you could have radio buttons or a combobox. The combobox could either have textual descriptions such as "red/green", "blue/yellow", etc., or you could have selectable pictures of the palettes as in your link above.

That would also allow to have an option "Custom colors". (I don't want to over complicate this, just showing it would allow a flexible/extensible design).

This solves the problem of making categories (what kind of color vision deficiency does user x have and what is the best color choice -- not everyone agrees here) that may or may not fit the individual needs.

**Comment by gitarra** [comment] 2015-11-02 08:40
I guess you dont realise colour blindness is a term used by the majority of languages and people on this planet?

**Comment by TETYYS** [comment] 2015-11-02 14:17
if i'd see "Color vision deficiency" i definitely won't think it's color blindness

why does uBlock even have color blindness option?

**Comment by maelh** [comment] 2015-11-02 14:24
I made a constructive suggestion just in my last comment. Did you read it?
"I guess you dont realise colour blindness is a term used by the majority of languages and people on this planet?"
And this is relevant to my specific suggestion in my last comment how? Also, I explained why this term is not accurate, and you are aware if you read that this is one term that is used, not the only one. 

Additionally, most software does not have any option termed like this, but color settings, the rationale for this is outlined in my last comment.

**Comment by Hrxn** [comment] 2015-11-02 17:39
If I might chime in, since German is my native language...

>maelh commented 22 hours ago

> The official medical term is "Farbsehschwäche"/color vision deficiency in Germany and it describes better what is going on.

This is definitely not correct. There is no 'official' medical term in German. Farbenblind (color blind) is the generic term used in colloquial language, nothing wrong here, that is the common hypernym.

If we want to talk about medical classification that assertion is still wrong.
The official classification in German is ICD-10-GM-2015.
Section H53 is 'Sehstörungen', and H53.5 explicitly mentions 'Farbenblindheit'.

I don't think that this is the right place for a discussion about causes and effect of achromatopia/achromatopsy, this is definitely out of scope for a browser extension. Or for basically any software project in general.

Enough time wasted here...

**Comment by TETYYS** [comment] 2015-11-02 17:42
> @gitarra and @TETYYS I made a constructive suggestion just in my last comment. Did you read it?
yes, it's alright to be wrong, don't worry

**Comment by maelh** [comment] 2015-11-02 17:44
Seriously? What is your issue with the color setting option?

Unbelievable!

**Comment by TETYYS** [comment] 2015-11-02 17:45
there's no issues with it, that's the current your problem

**Comment by maelh** [comment] 2015-11-02 17:46
So what about this very simple problem:
Color blind sets colors to blue and yellow. What is for people who have problems distinguishing those colors?
Is that label useful for them?

Is it that hard to understand that simple logic?

**Comment by maelh** [comment] 2015-11-02 17:52
@Hrxn:
Enough time wasted with people who can't read and make it a language topic!
Stop wasting my time and read suggestion I made!

And obviously usability is a topic for *every* software project.

**Comment by TETYYS** [comment] 2015-11-02 17:58
but your issue is language based

**Comment by maelh** [comment] 2015-11-02 17:59
Should I draw a picture to make the difference clear? Honestly?

**Comment by TETYYS** [comment] 2015-11-02 18:00
yeah sure why not

**Comment by maelh** [comment] 2015-11-02 18:06
Make a combobox that lets you select one of those options you see in the pictures: https://github.com/chrisaljoudi/uBlock/issues/467#issuecomment-95177219

Simple enough to understand?

**Comment by TETYYS** [comment] 2015-11-02 18:10
Why would an ad blocking program need that?

**Comment by maelh** [comment] 2015-11-02 18:11
The option is there already. I suggest how to make it useful, and not just a random checkbox.
But you aren't really interested in understanding.

**Comment by TETYYS** [comment] 2015-11-02 18:14
I don't really know, color blind people probably already has their settings set for whole monitor, I suggest removing option for color blind

**Comment by maelh** [comment] 2015-11-02 18:15
I suggest you stop trolling.

**Comment by gorhill** [comment] 2015-11-02 18:16
> Make a combobox that lets you select one of those options you see in the pictures:
> https://github.com/chrisaljoudi/uBlock/issues/467#issuecomment-95177219

**Comment by maelh** [comment] 2015-11-02 23:41
Thanks.

**Comment by Hrxn** [comment] 2015-11-03 04:42
I did read the whole thing. That's why I called it a waste of time.
This was a complaint made to myself, mostly, so feel free to ignore that.


Let's get this straight, you just made a feature request. That's perfectly fine, nothing wrong about it..

But, somehow, you decided that the issue needed to be dressed up a bit, so you added some "gravitas" to your request by insinuating that someone, like the author of the software, made somehow a (offensive) mistake somewhere. And for reasons I fail to understand you even tried to spin the issue by trying to make it appear that the 'infraction' at hand is even worse in German, which is definitely not the case.

You then backed up your claim by implying that there is some kind of official language rule for usage,
It took me literally five seconds to google this, showing that is not the case and that your claim is false.

And stop citing Wikipedia here, they are not an official authority on anything.
If you have problems with the terminology, please direct your complaints [here](http://www.dimdi.de/static/en/index.html) (Again, 5 seconds with Google).
Others don't seem to have that problem, so maybe you should do some soul-searching on your own behalf, if you feel so strongly about this issue.

And please explain why this is an usability issue to have a specific color option in a browser extension, even when the browser itself does not have said option, or even the OS..

And stop calling other people here trolls, because based on your initial comment, which you have edited in the meantime, you are the one who is trolling here.

Quoting your comment:
> Please change this insulting and factually wrong description.

But having the gall of accusing others of trolling, unbelievable..

**Comment by maelh** [comment] 2015-11-03 13:47
So you think you have the right to insult others and use common usage of words as argument?
What is your ICD Störung? What is your ICD retardation? What do you call this lack of clear thinking?

You are wrong here buddy and just keep arguing based on terminology to win the argument while totally disregarding the problem and having a sense of entitlement about what is right or not while it doesn't even concern you.

Instead of being productive while an agreement was met, you have to keep attacking. What is your agenda.

I am German too, btw, so you have no autorithy over what is proper use of German over me. I think I have much more experience in this domain that you.

If you have nothing to contribute, why do you join a thread that wasn't addressed at you? That behavior of your is the highest form of ignorance and arrogance.

**Comment by maelh** [comment] 2015-11-03 15:08
@gorhill:
Please just delete this issue. It just causes useless debate.

**Comment by gorhill** [comment] 2015-11-03 15:14
> It just causes useless debate

Nobody is forcing anybody else to answer one or all comments.

As far as I am concerned, I accept the idea of some kind of drop down with color schemes. I will create a section "Accessibility" in the _Settings_  pane and put a "color scheme" entry in there as you suggested. Eventually if someone comes with a monochromatic color scheme (there has been a demand for this in the past), I will be able to add it -- something I can't currently do.

**Comment by maelh** [comment] 2015-11-03 17:50
Ok, thanks, good luck with the implementation.

**Comment by Hrxn** [comment] 2015-11-04 23:26
A ghost...

Oh well. Come on, having a discussion is never a good reason to run away, don't take something like that too personal.

I apologize if I came off as too rude..

I think the idea is good, a menu presenting different color schemes to select. Sounds good, I don't think that anyone is against this per se.

**Comment by vipril** [comment] 2015-12-23 15:02
This is exactly the feature I was looking for, like for text editors that let you pick colors for syntax highlighting.

May I suggest to rename this feature though? I have no color vision problems so it took me quite some browsing to discover this "accessibility" feature is basically what I want.

I expected to find it under "colors" or "color settings" like what most software or operating systems do. Kubuntu or Windows let you choose from color schemas that have example pictures of the schemas or let you pick individual colors. So this looks pretty close to what was suggested here.

**Closed** 2023-01-02 16:17 UTC
Labels: accepted
