### ISSUE TITLE
uBlock keeps ignoring my filters, no matter what.

### ISSUE THREAD

**Issue by tsjnachos117** [gorhill/uBlock#3602] opened 2018-03-14 01:59 UTC
I feel like I should mention this isn't a problem related to one specific filter. So don't worry, I'm not here to complain about EasyList or whatever.

I'm having 4 different problems with uBlock. Since they all appeared at the same time, I'm assuming they're somehow related, and therefore I think it might be helpful to post them together.

First off, I can't seem to get any cosmetic filters to work on any website, even though cosmetic filtering is enabled. (I've checked the "Parse and enforce cosmedic filters" setting in "Third Party Filters", and I've checked cosmetic filtering icon for multiple individual websites.) Non-cosmetic filters seem to work OK... sometimes (see the third issue below :arrow_down:).

Second off, I can't update any of my filters. Even the built-in uBlock filters are giving me problems. When I go into the and click "Update Now", my CPU usage goes thorough the roof (although this CPU is pretty slow, so that's pretty much normal), and the spinning-progress-indicator-thinggies next to each list just spin forever, without ever timing out. I have checked my internet connection, and I can indeed visit websites (I just tested with ghacks.net).

Third off, since I can't update any filter lists at all, I naturally can't add any new filters, since I can't actually load filters. As for existing filters, I can only continue to use the outdated copies that are currently loaded. However, as I mentioned in the first issue, cosmetic filters refuse to work regardless.

Fourth off, I don't think uBlock is honoring any of my custom filters (namely those in "My Filters"), although I think it seems to be honoring those in the "Rules" settings. In the "3rd-part filters" page, it says "my filters" is using 0 out of 0 filters, even though I do  have filters.

- OS/version:  Ubuntu GNU/Linux 16.04 (32-bit version)
- Browser/version: Tor Browser Bundle 7.5.1 (based on Firefox ESR 52.7.0)
- uBlock Origin version: I'm running 1.15.10, although these problems seem to affect all of the WebExt versions (the older 1.13.x versions seem to work fine for now).

In order to prevent this report from becoming even longer than already it is, rather than list my all of my filters, settings, etc., I'm going to export my settings and attach them. Hope that's cool. :D
[my-ublock-backup_2018-03-14_01.33.57.txt](https://github.com/gorhill/uBlock/files/1809299/my-ublock-backup_2018-03-14_01.33.57.txt)

PS: I realize the contributing guidelines require me to give at least one example website, so here's one: ghacks.net. I am unable to permanently remove the annoying "We use cookies" message at the bottom of the page, even with the element picker. However, this also affects literally every other website since the filters aren't even being loaded.

BTW, I have multiple computers, each with the latest version of the TOR Browser, but for some reason this issue only affect one of them. :man_shrugging:

**Comment by tsjnachos117** [comment] 2018-03-14 02:18
On a whip I just decided to reset uBlock's settings back to default and reload the default filters. It didn't help. :-(

**Comment by uBlock-user** [comment] 2018-03-14 07:43
Sounds like a [TOR](https://github.com/gorhill/uBlock/issues/3393) issue.

**Comment by tsjnachos117** [comment] 2018-03-15 02:56
@uBlock-user:

I don't think the problem is with TOR. Like I said, the downloads don't time out, nor do they give that "broken link" icon. Also, my own custom filters are being ignored.

As for that other issue you linked to, it sounds like it might be similar to mine, although I've only glanced over it. I'll read it a little more when I have time.

**Comment by uBlock-user** [comment] 2018-03-15 05:41
TOR as in the browser, not the network. All of the issues you mentioned here are not happening on Chromium or Firefox or Opera for that matter, so the only variable left here is TOR and your problems appear very similar to how other users of TOR are struggling, that's why I mentioned TOR in the first place.

**Comment by tsjnachos117** [comment] 2018-03-18 00:47
OK, in the bug report posed by nbmrjuhneibkr, there is a link to a Mozillazine forum post, which mentions creating a cookie exception for uBlock Origin. Apparently, if Firefox (or in this case, the TOR Browser Bundle) is willing to let uBlock make cookies, it is also willing to let uBlock update itself.

So, I've done that, but uBlock is still being stubborn with \*some\* filters. I'll keep fighting with it and post whatever I find out.

**Comment by OpenBSD-Neurotik** [comment] 2018-03-22 01:38
By your CPU usage going through the roof we can establish that a memory leak had occured and that is mostly uBlock inability to not do what it wants which means it might be hampered by TOR itself or became corrupted.

TOR updates their browser in a very specific and often weird way that can cause breakage of none included addons, it is part of their hardening process. Make a backup of your rules and delete qBlock Origin, then install the addon from a fresh addon install. This might even require a fresh TOR install rather then a updated version.

**Comment by adisib** [comment] 2018-03-22 01:58
The CPU usage is likely related to #3577 ; there is no reason to think a memory leak is at all involved...

**Comment by Thorin-Oakenpants** [comment] 2018-03-22 05:34
@tsjnachos117 

- TBB uses PB mode - the pref is default true `browser.privatebrowsing.autostart` in TBB
- PB mode does not allow IDB - still doesn't, something to do with not being able to clear it re persistent data (I can dig up several bugzillas if needed)
   * PB mode may be the cause of stuff not sticking across sessions
- TBB is currently based on ESR52. The WebExt uBO (and uMatrix) use IDB, so this is problematic
- I think gorhill did some sort of work-around to fall back to local storage: not sure if [Window.localStorage](https://developer.mozilla.org/docs/Web/API/Window/localStorage) or [storage.local](https://developer.mozilla.org/Add-ons/WebExtensions/API/storage/local)
- Cookie exceptions for Extensions that use local storage and/or IDB was fixed in FF59 (well, at least the IDB part, I need to check the local storage bit) - see [this wiki entry](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1.1-Setting-Extension-Permission-Exceptions)
- Use legacy uBO on TBB, although we're only 1 release away from TBB being based on ESR60

Not sure if all of that is relevant, but hope it helps. I know you said in OP that legacy versions work fine, so that's the answer. We're 7 releases further in and too much has changed. Hang in there .. 1 more release :)

**Comment by tsjnachos117** [comment] 2018-03-22 06:08
@Thorin-Oakenpants: I'm pretty sure Firefox 59 is toning to be the next ESR, not 60. (Of course, the TOR Browser will probably be based off of 52 for a little while longer while the devs test their FF 60 mods.)

In case, I've already downgraded to the latest non-WebExtensions version, so I guess the problem is solved... kind of.

**Comment by uBlock-user** [comment] 2018-03-22 06:11
It's gonna be 60. It was already planned to skip 59 purposefully.

https://www.mozilla.org/media/img/firefox/organizations/release-overview-high-res.59a6d563be98.png

**Comment by tsjnachos117** [comment] 2018-03-22 06:18
@uBlock-user You're right. My bad.

**Comment by krystian3w** [comment] 2018-03-24 19:50
> http://www.largrizzly.net/firefox.html 

and try lastest

> https://github.com/gorhill/uBlock/releases/download/1.15.18/uBlock0.firefox.xpi

**Comment by tsjnachos117** [comment] 2018-03-25 05:31
@krystian3w: IDK if this version is meant to be a temporary workaround or a test build, but it seems be to working OK. However, when I installed it, I couldn't get to the dashboard to update my filters. Everytime I clicked on the toolbar button, it partially drew the menu before seeming to freeze (I could click on any other part of my screen to make it go away). Restarting the browser after installation seemed to fix the problem, and soon I was updating my filters. I tested this version on ghacks.net, and it seems to work perfectly.

Is this a non-WebExtensions version?

**Comment by tsjnachos117** [comment] 2018-03-25 05:40
BTW, there's a setting in the TOR browser, which seems to be part of the problem. If one goes into `about:preferences#privacy`, there's a setting called "Change details that distinguish you from other Tor Browser users", which I guess uBlock doesn't like. Disabling that seems to make the filters update, but uBlock sill ignores them. However, that may be due to the fact that I keep turning this setting on after I update my filters (I do like being anonymous, which is why I use TOR).

**Comment by krystian3w** [comment] 2018-03-25 23:53
Yes this is version compile to XUL (no signed - you should disable with javascript config file in Firefox 52 ESR / TOR Browser).

**Comment by tsjnachos117** [comment] 2018-03-26 02:08
Actually, in the TOR Browser, you only need to set `xpinstall.signatures.required` to false. The link you provided states that that's *all* you need to do for Firefox 52.

**Closed** 2018-04-16 15:28 UTC
Labels: invalid
