### ISSUE TITLE
[Thunderbird] Export from dashboard is not possible

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1635] opened 2016-05-15 15:04 UTC
It's not possible to export uBO backup-files from dashboard in Thunderbird. Any ideas?

Thunderbird 45.1.0 (de) with uBlock Origin 1.7.5b2 on Windows 10 Pro x64 (de).

Thank you for any infos in advance!

**Comment by Alpengreis** [comment] 2016-08-30 21:39
Still the case in TB 45.3.0 ...

**Comment by gorhill** [comment] 2016-08-30 21:49
Is it really necessary to point out I should spend a whole lot more time than I already do on this project?

**Comment by Alpengreis** [comment] 2016-08-31 15:05
No, it's not necessary, I had a bad day and was too eagerly. SORRY.

**Comment by gorhill** [comment] 2017-09-19 19:41
Duplicate of #117.

**Closed by gorhill** 2017-09-19 19:41 UTC
Labels: duplicate
