### ISSUE TITLE
Ads Showing up on a site where they were previously blocked.

### ISSUE THREAD

**Issue by CrowdMeme** [gorhill/uBlock#1916] opened 2016-08-20 04:27 UTC
### Describe the issue
Ads Show up on Snopes.com even though they were previously blocked, I have visited snopes before the 1.8.4, probably way back still on the 1.7 version of uBo and the ads did not show up through uBo before but now they do.

I never delved into the logger before when the ads were blocked so I'm not sure what service is serving the ads on the page

I tried clearing browser History and Cache fully, closing chrome running CCleaner, reopening to the same page via the favorites bar that I had saved it to, so I could test the issue, and the ads were still present.

The issue was also present on the latest version of the android FireFox browser when  in the Desktop viewing mode with uBo installed (Running Android 5.1.1 and uBo 1.8.4 on the latest firefox version.
### One or more specific URLs where the issue occurs
http://www.snopes.com/pierson-obama-half-breed/
http://www.snopes.com/medical/myths/jeanhilliard.asp

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
[Screenshot](http://i.imgur.com/WNw7YQQ.png)
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be running Chrome (Version 52.0.2743.116 m 64-bit) 
2. Have uBo running
3. Have advanced user selected
4 Have all these items enabled:
   Disable pre-fetching (to prevent any connection for blocked network requests) 
   Disable hyperlink auditing/beacon 
   Prevent WebRTC from leaking local IP addresses 
5. Go to Snopes.com or any page on snopes and see ads

### Your settings
- Browser/version: Chrome 52.0.2743.116 m (64-bit)
- uBlock Origin version: 1.8.4
- Win 7 Ultimate 64 Bit

Also tested on Mobile FireFox browser on Android 5.1.1 Lollipop with request desktop site and the ads showed up there aswell. (latest FireFox version AND 1.8.4 uBo) No screenshots available though.
##### Your filter lists
Default + All ublock filters, All Ad Filters, all privacy Filters, All malware domain filters, All social filters, and all multipurpose filters.
##### Your custom filters (if any)
No custom filters at all.

**Comment by lewisje** [comment] 2016-08-20 05:26
Websites have this strange tendency to change how they embed ads, to get around common ad-blocker filter-lists; I've already reported about this issue in the place where filter-list issues ought to be reported (that is, the forum for the filter-list itself), having used the logger to figure out where the problem is (something you should have done): https://forums.lanik.us/viewtopic.php?p=100929#p100929

Now if there's a problem specific to the first-party lists in uBlock Origin (like Unbreak, or Experimental), that's what the uAssets repository is for.

**Comment by gorhill** [comment] 2016-08-20 12:26
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-08-20 12:26 UTC
Labels: invalid
