### ISSUE TITLE
coexisting with other extensions

### ISSUE THREAD

**Issue by bboti86** [gorhill/uBlock#2422] opened 2017-03-02 19:29 UTC
Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
Hi!
Chrome keeps telling me that the extensions are not working together well. 
I'm getting these kinds of errors always:

This extension failed to redirect a network request to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJdmFyIG5vb3BmbiA9IGZ1bmN0aW9uKCkgewoJCTsKCX07Cgl3aW5kb3cuYWRkdGhpcyA9IHsKCQlhZGRFdmVudExpc3RlbmVyOiBub29wZm4sCgkJYnV0dG9uOiBub29wZm4sCgkJaW5pdDogbm9vcGZuLAoJCWxheWVyczogbm9vcGZuLAoJCXJlYWR5OiBub29wZm4sCgkJdG9vbGJveDogbm9vcGZuLAoJCXVwZGF0ZTogbm9vcGZuCgl9Owp9KSgpOw== because another extension (Ghostery) redirected it to data:application/javascript;base64,dmFyIGFkZHRoaXM9e2luaXQ6ZnVuY3Rpb24oKXt9LCBsYXllcnM6ZnVuY3Rpb24oKXt9LCB0b29sYm94OmZ1bmN0aW9uKCl7fSwgYnV0dG9uOmZ1bmN0aW9uKCl7fSwgY291bnRlcjpmdW5jdGlvbigpe319Ow==.

I'm also contacting them as well.
B

### One or more specific URLs where the issue occurs

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- Browser/version: Chrome
- uBlock Origin version: 

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment] 2017-03-02 19:38
Duplicate of #1170.

**Closed by gorhill** 2017-03-02 19:38 UTC
