### ISSUE TITLE
Filterlists not updated when Firefox is using automatic Private Browsing as default

### ISSUE THREAD

**Issue by borque** [gorhill/uBlock#3573] opened 2018-03-05 13:20 UTC
Hello!
With the current release of ublock origin filterlists get no updates when Firefox is instructed to alsways use private browsing or to never record any history.

Steps to reproduce: 
ublock: 1.15.10, Firefox 57 and 58 (tested on Mac and Win)
Upon first installation ublock comes with Easylist and Easylist privacy dated to 03rd February 2018.

Wrong behaviour / Error:
When Firefox is instructed in the security and privacy settings to always use private browsing (checkbox) or to never record any history (pull down menu) and you select update filter lists within ublock the update process seems to run and finish normally (i.e. the exclamation mark indicating old lists is replaced by the clock symbol for a recent update), but the lists do not change (and remain on 3rd February 2018 in my case). Upon next restart the lists are flagged outdated again.

Expected correct behaviour:
When Firefox is allowed to record history or not in automatic private browsing mode the lists are updated as expected to the current release (04th March 2018 when I last tested it).

Side aspect:
When you switch Firefox to private browsing after a succesfull update (i.e. the list shows a curent date) and then switch to private browsing the list is reverted to the version released with ublock upon installation (03rd February 2018 in my case).

Thanks!
Borque

**Comment by gorhill** [comment] 2018-03-05 13:54
Duplicate of #3071.

**Closed by gorhill** 2018-03-05 13:54 UTC
Labels: duplicate

**Comment by Raaviz** [comment] 2018-03-05 14:05
And of https://github.com/gorhill/uBlock/issues/3398 as well.
