### ISSUE TITLE
[Firefox] v.1.6.2 Upgrade Problem

### ISSUE THREAD

**Issue by mpred04** [gorhill/uBlock#1419] opened 2016-02-24 09:16 UTC
I was not able to upgrade uBlock Origin to its latest version (from 1.6.1 to 1.6.2). My version of Firefox is the latest release one out at the moment, which is 44.0.2 (x64).

The issue occurs both while trying to update the addon:
![2 jpg](https://cloud.githubusercontent.com/assets/7307115/13280208/a2e5ffe0-daed-11e5-9312-1406ed7ae9db.jpg)

And reinstall it (https://addons.mozilla.org/ru/firefox/addon/ublock-origin/?src=search):
![2-1 jpg](https://cloud.githubusercontent.com/assets/7307115/13280209/a2e907c6-daed-11e5-8643-17659a2b2d61.jpg)

Do not see any difficulties worth describing in order to recreate the issue, however, don't see many reports of it either. The only one I was able to find is the recent review on the Mozilla Add-ons page (https://addons.mozilla.org/ru/firefox/addon/ublock-origin/reviews/781433/). Interestingly enough, it's in Russian, which is my native language as well, which makes me think that it might be some sort of a regional problem, though my guess is as good as anybody's.

**Comment by krlk89** [comment] 2016-02-24 10:14
Can confirm, same problem.

**Comment by 5t3f4n** [comment] 2016-02-24 11:26
#1413 
#1414
#1373

**Comment by gorhill** [comment] 2016-02-24 13:40
Question: do you have "advanced user" mode enabled and did you remove `behind-the-scene` from the _Whitelist_ pane in the dashboard?

**Comment by krlk89** [comment] 2016-02-24 14:06
I tried with and without advanced user/behind-the-scene (all on/off variants). Still can't update.

**Comment by gorhill** [comment] 2016-02-24 14:08
Ok, just wanted to be sure this was not a result of behind-the-scene network requests being blocked.

**Comment by mpred04** [comment] 2016-02-24 14:56
@gorhill Did not use "advanced user" either, behind-the-scene is also there
May be an AMO issue again, I guess? (btw, my apologies for not looking through this forum properly, presence of 3 more inquiries of basically the same issue make it seem like my search for reports went really poorly, and it did)

**Comment by gorhill** [comment] 2016-02-24 15:05
The issue should bring it to [Mozilla Discourse](https://discourse.mozilla-community.org/c/add-ons/addons-mozilla-org), the AMO people are better placed than me to investigate this.

**Comment by gorhill** [comment] 2016-02-24 21:24
Duplicate of #1373.

**Closed by gorhill** 2016-02-24 21:24 UTC
