### ISSUE TITLE
1.13.10 Update Completely Broken

### ISSUE THREAD

**Issue by GuardianMajor** [gorhill/uBlock#2911] opened 2017-08-29 06:03 UTC
I was going to add my information to the Issue #2909 which is already open but you closed it off so there is no way to provide additional information, so I have to open a new ticket, which is highly inefficient and puts the information to sort this mess out all over the place, but your choice.

It updated to 1.13.10 and nothing works, in fact other than showing up under the extensions list, there is no sign that it even exists. It updated in the middle of my session and I began noticing that I can't access a bunch of URLs or they won't load or behave right and the console kept showing vAPI undefined error which clearly was a regression (I see on the RC). Nothing was working right and the icon suddenly shifted from where it was to the far right (how I knew it updated).

So, I restarted the browser given the bad state it was in, to allow it to properly reload and refresh itself on the next boot, then the problem got permanent.

1. The toolbar icon going missing was the most obvious.
2. When not showing up under the customize panel despite being enabled was another.
3. Disabled it, restarted.
4. Enabled it, nothing changes.

I would go back to the older version or remove and install the new version but the problem is that the way it broke everything, I have no way to recover all my settings, filters, rules and everything. Basically I have to start all over again from scratch and this is just bad. Unless, you have a magical way to get everything back while rolling back and/or installing the new version without an actual backup?

FX: 55.0.3 (32-bit)
OS: Windows 10 (64-bit)

Now, under the `profile directory\browser-extension-data\` we have a `uBlock0@raymondhill.net\storage.js` which begins with `"legacyStorageMigrated":true,"webrtcIPAddressHidden":true,"version":"1.13.10"` which clearly got pooched somewhere and did not migrate despite what it says.

Then there is a `extension-data` folder containing a single `ublock0.sqlite` and that's that; suppose this is what it considers a successful migration with nothing working anymore.

Then we have a `uBlock0@raymondhill.net.xpi` under the `extensions` folder. And that's all she wrote. So I don't see anywhere that I can get my configurations back and this botched update seems to have permanently broken the install, so what to do now?

EDIT: To clarify and add, what should go without saying, that I did already try the "workaround" of installing .8 back on top of it and it did nothing and that's why I needed to mention all this but it forced me to open another issue. At this point, roll back doesn't work, and remove is not an option because I don't have my settings and I don't want to lose them by removing it. I am basically stuck.

**Comment by ShizCalev** [comment] 2017-08-29 07:24
Just curious, have you tried out the current dev version / release candidate of ublock for firefox? I was having the same issue as everyone else and switching to it seems to have stopped my issues for the rest of the night (it's been about 12 hours now without the issue returning.)

Others have also stated the same for it.

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

You can install it by expanding the development channel drop down at the bottom of this page.

FF: 56.0b6
OS: W10 - 64x

**Comment by emberflare** [comment] 2017-08-29 08:06
@ShizCalev This resolved the issue for me. All my settings and filters from before updating to .10 are back.

**Comment by gorhill** [comment] 2017-08-29 10:53
> To clarify and add, what should go without saying, that I did already try the "workaround" of installing .8 back on top of it and it did nothing

Did you try to un-install before re-installing, as stated?

**Comment by GuardianMajor** [comment] 2017-08-29 18:23
@ShizCalev yes I did try that when it first started showing the undefined error in the console, it resolved that from showing up but then left the whole install in the unstable condition it is now.

**Comment by GuardianMajor** [comment] 2017-08-29 18:30
@gorhill no I did not do an uninstall for reasons I already mentioned and per your OWN instructions in the other issue, you crossed it out and said it was not necessary to make it work, so pick an instruction and stick with it, flip flopping like this isn't helping anyone. 

> @gorhill : Woraround: re-install uBO over uBO (do not uninstall). Un-install then re-install -- maybe.

>Ah yes, that makes sense given it migrates data from the legacy storage version -- and which legacy storage is never removed. There was no need for me to say "do not uninstall".

Again, you seem to be allergic to reading the issue despite giving people shit about not doing the same, clearly I tried the roll back option, as you even quoted me saying that I did, so what the hell?

And you close this and mark it as duplicate which it is but you forced this because you chose to restrict input by preventing posting to the other topic. You still haven't resolved the issue but feel it is appropriate to arbitrarily close it. Why is that? Just because some random actions have helped some, doesn't mean you haven't created a situation from which not everyone can recover the same.

**Comment by gorhill** [comment] 2017-08-29 18:55
Ok, you're pissed off.

If you think your issue is not a duplicate of #2909, then contribute something by investigating and findings hints on your side about your issue, like browser console, stepping into debugger, etc. Walls of text accomplish nothing.

**Comment by gorhill** [comment] 2017-08-29 19:06
There, I reopened for you. I will assign the issue to you, please investigate the source of your issue and once you do, please provide me guideline as to how to fix it. Thanks.

**Comment by GuardianMajor** [comment] 2017-08-29 20:59
@gorhill You misunderstand me, which seems to be more often these days than in the past, perhaps because you come to everything with a preconceived bias to dismiss it because you can't possibly be wrong about anything, right? I don't get pissed off, disappointed - yes, but not pissed off because I am a professional who respects the process; as should you.

What DOES disappoint is your response and the apparent tantrum in response to people letting you know, as the developer, that an update has broken things. What did you want them to do? Not say anything? You are the one who arbitrarily limit people's access to a running and existing issue and force them to have to voice it elsewhere and then get upset that they did - perhaps try being more inclusive and less elitist.

Then they are letting you know that the workaround, which amount to nothing more than a band-aid, doesn't work to fix all conditions created; that's honest and should be helpful feedback to narrow down what went wrong. But instead of asking for information that will highlight WHY it didn't work for everyone, you simply berate their concerns and rudely dismiss them.

Stomping your feet and saying, I broke it, don't know why and you go figure out how to fix it is highly immature for a regarded and respected developer - perhaps that has made you complacent or gone to your head that you are infallible and don't need feedback? How can you expect anyone to investigate and try to provide a solution when you dismiss that they are ever valid without providing any basis for it?

I will happily try and figure out what went wrong and why many, like myself, cannot resolve this problem with a workaround that only highlights this update was not thoroughly tested or thoughtfully pushed out to prepare for what issues it might cause. Could it be an edge case, sure it can, does it mean it is not important, absolutely not, unless you are developing for the law of averages only.

You could have just as simply asked for debug information and what might help you fix things rather than simply be dismissive and hasty in discounting anything that doesn't fit the narrative you have established. Without specific requests, anything I or anyone else does to try and figure out what went wrong will often be redundant, wasteful and not lead to anything useful because there is nothing specific being solicited to resolve the issue. 

If I already had something in the error console or something that I could let you know, I would have included it in the report like everything else that I presented to give you a picture of where I am with this issue. The assumption that you are the only competent person and that anyone who asks or reports an issue is automatically some noob moron who is not worth your time is a problem. Of course you may not care but that's how great projects lose credibility and respect.

So if you can think of something specific to ask me to provide to help, let me know because at this point, I have to just abandon this profile and start all over again, thanks to what has happened, and no that's not ok - until I can figure out how to fix what is now irreparably broken and you don't seem to care. Balance your ego and temperament with what you are trying to achieve, if you actually care about what you are doing beyond a pet project. As someone who has been part of the NoScript team for what is nearing 2 decades, I can tell you, only being genuine, humble and dedicated makes you last and survive the test of time. Take it for what it's worth, I imagine you are rolling your eyes and fuming already but hopefully a small part of you takes it as it is, a friend trying to give you context.

**Comment by GuardianMajor** [comment] 2017-08-29 21:10
> There, I reopened for you. I will assign the issue to you, please investigate the source of your issue and once you do, please provide me guideline as to how to fix it. Thanks.

Sorry for the "wall of text" - although I don't know how else people can speak to present the problem. If the extension actually did anything beyond show up in the addons page with no access to any of its "back" pages, I would happily provide console logs and debug it but since it doesn't and throws nothing in there - because it is not actually working.

Can you please enlighten my ignorance, which you are presuming, and tell me how in this condition would I go about providing that information to you, which of course still be a wall of text, but perhaps you would find it more useful. How to debug an extension that is so broken that it won't assert itself ANYWHERE, maybe I don't know something you can teach me. Maybe after more than 25 years of developing complex enterprise level applications, I am missing something about how to debug something all but non-existent in an environment that itself is limited (the browser). Simply point the way, I will figure out the rest. Thank you.

**Comment by DrunkenSasquatch** [comment] 2017-08-30 05:26
@GuardianMajor
![a9c](https://user-images.githubusercontent.com/16097892/29856622-7b6ee6ee-8d97-11e7-93af-35750bcb9e78.png)

**Comment by monkeymagic29** [comment] 2017-08-30 10:38
@gorhill , I need to emphasize that while every  Firefox desktop client I tried could successfully migrate .10 -> .8 -> .11.rc0, none of the Android Firefox client I tried could. I heard you the first time that this will all go away after stable goes to 56, but this discrepancy between desktop and Android client certainly poses uncertainty of that claim (may be true for desktop client only).

Because, like I said, control on extension auto-update on Android client are not granular at all, and apparently you currently had your share of problem with Firefox and cannot immediately resolve it, I propose that you roll back the stable version on AMO to 1.13.8 instead. Seems like it's an easier fix for both desktop and Android at the moment, because users gotta pick either .8 or 11.rc.0 anyway at the moment.

By the way, I want to test 11.rc1 on Android but I don't know how to install it because it's not officially signed by Mozilla. Any about:config entry I should know about to make it possible? I noticed there are a ton load of new entries that aren't covered by [http://kb.mozillazine.org/Firefox_:_FAQs_:_About:config_Entries](url).

**Comment by gorhill** [comment] 2017-08-30 13:13
Something which may work:

- Uninstall uBO
- Quit Firefox
- Launch Firefox
- Quit Firefox
- Launch Firefox
- Install uBO

As [already stated above](https://github.com/gorhill/uBlock/issues/2911#issuecomment-325761336), the browser console is the thing to look at.

I had to run tests on legacy. Even after I uninstalled uBO webext-hybrid, the browser console still reported something about uBO failing after I quit/relaunched Firefox -- _despite_ uBO having been removed from Firefox. Quitting Firefox again then re-launching, the browser console _finally_ reported nothing about uBO in the browser console. I could then re-install legacy version successfully. After this, I could install webext-hybrid fine.

**Comment by Peac** [comment] 2017-08-30 13:53
Got the same problem, that solved it for me.
Thank you

**Comment by curiosity-seeker** [comment] 2017-08-30 17:14
@GuardianMajor : I understand that it can be frustrating if something doesn't work as expected. However, please try to understand 3 things:

1. gorhill does all the work in his free time (and with an incredible energy if I may add this)
2. gorhill does it all for free and doesn't even accept any donations (contrary to G. Maone - since you mentioned that you're part of the Noscript team)
3. Hence, if gorhill decides tomorrow that he's sick and tired of continuing his work, nobody - I repeat: _nobody_ - would have the right to complain about such a decision.

Considering all this, your demanding attitude is absolutely inacceptable - and raises the probability that point 3. above might happen sooner or later. Think about it!

**Comment by gorhill** [comment] 2017-08-30 18:01
Report to `https://bugzilla.mozilla.org/`.

**Closed by gorhill** 2017-08-30 18:01 UTC
Labels: duplicate

**Comment by GuardianMajor** [comment] 2017-08-30 18:28
@curiosity-seeker While I appreciate that your reply is most mature of all the other fanboy hate posts which only shows lack of character and cult mentality; I fully understand all of that and stating them is moot. I do not expect anything other than that or disagree with anything you said in the holier than thou talk down that it was intended.

But it is worth noting that 1) he chose to do it, and no one forced him to do it; in line with that it doesn't earn someone excuse because they are doing it for free or in their spare time. By the simple act of doing it, you are owning responsibility for it, simple as that. 2) again not accepting donation is another choice that is irrelevant to how you develop and support something. 3) I never said if he wants to quit anyone has a right to complain but until that day comes, he is responsible for what he puts out there.

I did not demand shit other than to explain the problem and that since it was created by an update that was pushed by the developer, and it is a valid expectation that he knows what he is doing, to ask that he at least acknowledge something went wrong and try and provide a solution. That is neither an unreasonable demand nor did it come with any attitude until the lack of reply and the unacceptably unprofessional conduct that followed. So, don't presume to pass judgement for what you don't know. You think about that. Clearly this a cult of fanboys and a hobby that began from forking someone else's work and clearly has no interest in being anything other than that, as evident by the childish and immature posts made by everyone before you and to some extend even your condescending and judgemental tone that has no basis in fact.

You guys are welcome to lay on your knees, I have no interest in defending what was a proper report of a problem that devolved into utter nonsense by lack of maturity on everyone's part who decided to "respond" to it. It shows lack of character to attack people because you think you are anonymous and it excuses being malicious trolls equating the responses above with an actual valid bug report. Your actions may seem to you as defending Ray, but in fact you are just showing that he has no character by allowing his proxies to do whatever they want while he hides behind them. And the lack of character on the part of trolls who posted above reflects on the kind of people he cultivates around him. Again, he is welcome to taint his reputation with the vitriol spewed by his fanboys, but he will have to own it as he allows it and feeds it with his actions.

Frankly I am done trying to be the only professional in the room and trying to help a project that clearly has no interest in being honest and sincere and led by nothing more than ego. As an someone who has known you for a long time, I will just say one last thing, shame on you Ray for thinking civility and rule of ethical conduct towards others don't apply to you. Good luck but I suspect in time, the very shallow fanboys that now defend you will turn on you, happens to all dictators.

**Comment by gorhill** [comment] 2017-08-30 18:43
There are things worth to worry about in (real) life. The opinion one internet person has of me will never be one of these.
