### ISSUE TITLE
Images shown with Block media elements enabled

### ISSUE THREAD

**Issue by sogen** [gorhill/uBlock#2181] opened 2016-11-23 23:53 UTC
### Describe the issue
Some images show even if I have enabled "block media elements larger than" 50kb

### One or more specific URLs where the issue occurs
http://enigma.io
http://www.sevenleague.co
http://www.leadpages.net/features
(on last one scroll to the bottom)

### Screenshot in which the issue can be seen
Sorry can't attach more images, ATM I'm on tethered internet, will try to paste a couple ASAP.
![imayaa](https://cloud.githubusercontent.com/assets/2784323/20582294/798c871a-b1a5-11e6-9ae3-c5c3317f7b94.png)

### Steps for anyone to reproduce the issue
Using Opera Turbo, browse to any of the URLs listed

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings
Macbook Pro OS X 10.10.5 64-bit (Yosemite), 16GB RAM

- Browser/version: Opera Version:	41.0.2353.56 - Stable
Enabled **Opera Turbo** in case that helps
Zero plugins or add-ons installed, new install with only Ublock origin installed.

- uBlock Origin version: 1.9.16

##### Your filter lists
MAIN page
Disable cosmetic filtering Checked
Ignore generic cosmetic filters NOT Checked
Block remote fonts Checked
Block media elements larger than 50 kB Checked 

FILTERS page
Parse and enforce cosmetic filters Checked
uBlock filters‎ 
uBlock filters – Badware
uBlock filters – Privacy‎ 
uBlock filters – Unbreak‎ 
EasyList
EasyPrivacy‎ 
Malware domains‎

**Comment by migueldemoura** [comment] 2017-01-08 22:17
I can reproduce this on:

Opera 42
uBlock 1.10.2
*buntu 16.10
VPN Mode

Disabling VPN Mode fixes it. Does it mess with the Headers?

**Comment by gorhill** [comment] 2017-09-11 15:31
Closing, I could not reproduce. OP will have to verify whether the `Content-Length` header is present. If it is not present, then this is not a uBO issue.

**Closed by gorhill** 2017-09-11 15:31 UTC
Labels: unable to reproduce
