### ISSUE TITLE
Chromium OSX: ALT-L opens Logger and prevents input of @ char in any form element

### ISSUE THREAD

**Issue by COLABORATI** [gorhill/uBlock#2764] opened 2017-07-06 11:47 UTC
On Chromium (freesmug edition) on mac OSX I can not input the @ char in any form element because that keyboard shortcut is hijacked by ublock origin and the logger window opens instead.

Also I can not find any option to disable or change this shortcut.

Thanks for your attention, great tool otherwise.

**Comment by gorhill** [comment] 2017-07-06 11:52
Duplicate of #2723.

**Closed by gorhill** 2017-07-06 11:52 UTC
