### ISSUE TITLE
Not blocking ads in the background

### ISSUE THREAD

**Issue by RiceDie** [gorhill/uBlock#1575] opened 2016-04-19 06:43 UTC
OS Windows 10 x64
Browser **Waterfox** 44.0.3** x64 Firefox based**
**uBlock 1.6.8** + **186 126** network filters ＋ **98 269** cosmetic filters (I use all the filters except  **EasyList without element hiding rules**) Updated as of **19.04.2016**

**site** www.4pda.ru
**adverts** http://4pda.ru/ad/www/delivery/ck.php?n=4269948&zoneid=22&bid=2078
 http://s.4pda.to/lMq621BGnZaLdh7OkF4XaTz1p5SIlsC9QPFlrMKWZRLOXrclWoz0wZNL64.gif

**Comment by IDKwhattoputhere** [comment] 2016-04-19 09:23
Does any of this work: https://forums.lanik.us/search.php?keywords=4pda.ru?

**Comment by gorhill** [comment] 2016-04-19 12:47
uBO's element picker needs to be able to extract the `source` tag information from within the `video` tag.

**Comment by gorhill** [comment] 2016-04-19 13:11
Correction: the specific issue mentioned here is a duplicate of #1202. Element picker of uBO 1.6.9b can handle this, except that I needed a minor code review to ensure that uBO's preview mode works as expected (needed to mind `!important` in CSS styles).

**Comment by gorhill** [comment] 2016-04-19 13:16
Duplicate of #1202, which is fixed in 1.6.9b2. The specific issue I found here is fixed in 1.6.9b3.

To be clear, uBO can block background images, #1202 is about offering the choice of blocking background images from the element picker.

**Closed by gorhill** 2016-04-19 13:16 UTC

**Comment by RiceDie** [comment] 2016-04-19 17:48
I updated too uBlock 1.6.9b2 and added this to my filters:

! 19.04.2016, 19:20:09 http://4pda.ru/
4pda.ru###rMy1nwmf > .post > .visual > .rIvz1Bnx.r3UWP0www

! 19.04.2016, 19:20:25 http://4pda.ru/
||s.4pda.to/lMq63EGypLxLtsPz0SYnDDOrWkKdfctz2NqR5rmaz1qWKhcDDBQRwMjiVtz2.jpg$image

! 19.04.2016, 19:21:08 http://4pda.ru/
||s.4pda.to/lMq6USyxn2TAxQyqTxYaQ5QJ9r.jpg$image

! 19.04.2016, 19:27:24 http://4pda.ru/
4pda.ru###zvu41f1q1cb8

! 19.04.2016, 19:27:32 http://4pda.ru/
||s.4pda.to/lMq621BGnZaLdh7OkF4XaTz1p5SIlsC9QPFlrMKWZRLOXrclWoz0wZNL64.gif$image

! 19.04.2016, 19:32:14 http://4pda.ru/
||s.4pda.to/lMq64Tb4yaqqpoa5fZEqEOWjnWWDycmCwRT41BvxhYlJMxz2AJkK8Lmz2h.jpg$image

! 19.04.2016, 19:32:24 http://4pda.ru/
||s.4pda.to/lMq6Vx2Y8tuhJRBlQT98WdORUn1GrJWIWR1hL6awISmBVxnnvF76EAMi.jpg$image

! 19.04.2016, 19:32:42 http://4pda.ru/
||s.4pda.to/lMq6HZCW1wUlz2QRTZifJQ6g1z0z1ajl55SZjVjTSyxOm0s665XHBDN5uh9.jpg$image

! 19.04.2016, 19:33:52 http://4pda.ru/
||s.4pda.to/lMq6NpAz2mPK7hD4rDz1Aq3JwNp4OMH40dlGwMr5DkTsk7FnWwBo2FPkCL.gif$image

Now its blocking those pesky ads. I will learn into the link that was given by **DKwhattoputhere** I did take a quick glance but will have to study more thoroughly through the subject. Thanks!
