### ISSUE TITLE
uBlock button sometimes cuts half of the GUI

### ISSUE THREAD

**Issue by grenzor** [gorhill/uBlock#1713] opened 2016-06-12 06:26 UTC
I've noticed since Firefox 46 that every once in a while when you click the UO button on the panel it only displays half of the GUI (which shows requests blocked, since install etc.).

I'm not completely sure how to reproduce it since it doesn't always happen but try closing your browser fully and clicking the UO button.

**Comment by gorhill** [comment] 2016-06-12 13:39
I haven't ever seen any such behavior. You will have to investigate on your side and make the case the issue is really with uBO. I will re-open if and once you provide evidence your problem is caused by uBO and not something specific on your side.

**Comment by grenzor** [comment] 2016-06-19 19:54
I'm not sure what else could have caused this, maybe something to do with new GT K support on Firefox but I don't know.

I see it is reproducible right after you open Firefox. So close browser, open, and click the icon. Also another way that may also reproduce is close Firefox, open again, open a new private browse window and the click the icon. Please let me know if you can see it reproduced

**Comment by gorhill** [comment] 2016-06-19 20:07
Any uBO-related error in the browser console when this happens?

**Comment by grenzor** [comment] 2016-06-19 20:27
There isn't any uBO related errors when I click the icon after startup.

**Comment by gorhill** [comment] 2016-06-19 20:40
> when I click the icon after startup

What is the web page when you click uBO's icon?

**Comment by grenzor** [comment] 2016-06-19 20:52
about:blank

**Comment by gorhill** [comment] 2016-06-19 20:59
What is the value of `extensions.ublock0.forceLegacyToolbarButton` in `about:config`?

**Comment by grenzor** [comment] 2016-06-19 21:00
false

**Comment by gorhill** [comment] 2016-06-19 22:11
If you build uBO yourself, probably best that you add logging code to find out what is happening in [resizePopup](https://github.com/gorhill/uBlock/blob/fa1dafafbe68e8eda73aaf21d854ef8a13fe5db4/platform/firefox/vapi-background.js#L2588).

**Comment by grenzor** [comment] 2016-06-19 23:15
Unfortunately I don't build myself, but I'll try to see if there is anything else causing this.

**Comment by gorhill** [comment] 2016-08-25 11:42
Another instance of broken UI yesterday. Browser console:

    Error: Script terminated by timeout at:
    vAPI.setTimeout</<@chrome://ublock0/content/js/vapi-common.js:44:37
    setTimeout handler*vAPI.setTimeout<@chrome://ublock0/content/js/vapi-common.js:44:12
    TabContext.prototype.onTab@chrome://ublock0/content/js/tab.js:222:28
    vAPI.tabs.get@chrome://ublock0/content/js/vapi-background.js:901:5
    TabContext.prototype.onGC@chrome://ublock0/content/js/tab.js:233:9
    vAPI.setTimeout</<@chrome://ublock0/content/js/vapi-common.js:44:37
    setTimeout handler*vAPI.setTimeout<@chrome://ublock0/content/js/vapi-common.js:44:12
    TabContext.prototype.onTab@chrome://ublock0/content/js/tab.js:222:28
    vAPI.tabs.get@chrome://ublock0/content/js/vapi-background.js:901:5
    TabContext.prototype.onGC@chrome://ublock0/content/js/tab.js:233:9
    vAPI.setTimeout</<@chrome://ublock0/content/js/vapi-common.js:44:37
    setTimeout handler*vAPI.setTimeout<@chrome://ublock0/content/js/vapi-common.js:44:12
    TabContext.prototype.onTab@chrome://ublock0/content/js/tab.js:222:28
    vAPI.tabs.get@chrome://ublock0/content/js/vapi-background.js:901:5
    TabContext.prototype.onGC@chrome://ublock0/content/js/tab.js:233:9
    vAPI.setTimeout</<@chrome://ublock0/content/js/vapi-common.js:44:37
    setTimeout handler*vAPI.setTimeout<@chrome://ublock0/content/js/vapi-common.js:44:12
    TabContext.prototype.onTab@chrome://ublock0/content/js/tab.js:222:28
    vAPI.tabs.get@chrome://ublock0/content/js/vapi-background.js:901:5
    TabContext.prototype.onGC@chrome://ublock0/content/js/tab.js:233:9
    vAPI.setTimeout</<@chrome://ublock0/content/js/vapi-common.js:44:37
    setTimeout handler*vAPI.setTimeout<@chrome://ublock0/content/js/vapi-common.js:44:12
    TabContext.prototype.autodestroy@chrome://ublock0/content/js/tab.js:272:24
    push@chrome://ublock0/content/js/tab.js:339:13
    commit@chrome://ublock0/content/js/tab.js:386:21
    vAPI.tabs.onNavigation@chrome://ublock0/content/js/tab.js:455:22
    vAPI.net.registerListeners/locationChangedListener@chrome://ublock0/content/js/vapi-background.js:2455:9

This stack trace is abnormal: it shows that when uBO calls `setTimeout`, Firefox invokes the callback function immediately, on the spot, instead of after the specified delay. Nowhere can I find documentation for such behavior, so I have to assume that Firefox's javascript engine become misbehaving for some reasons.

**Comment by gorhill** [comment] 2017-09-09 18:05
Closing this issue due to obsolescence.

**Closed by gorhill** 2017-09-09 18:05 UTC
