### ISSUE TITLE
Firefox: Icons in uBlock menu are broken when disabled "Allow pages to choose their own fonts, ..."

### ISSUE THREAD

**Issue by fict10n** [gorhill/uBlock#687] opened 2015-09-06 10:42 UTC
If option "Allow pages to choose their own fonts, instead of my selections above" is not enabled in Firefox settings, than uBlock Origin has completely broken UI. Option gfx.downloadable_fonts.enabled is set to true. Either it is a bug in Firefox, or in the addon, or both.

![firefox-fonts-settings_ublock-origin-problem](https://cloud.githubusercontent.com/assets/14146739/9703950/f02caa3c-5493-11e5-80ec-30d9ecebf3fa.png)
![gfx downloadable_fonts enabled_true](https://cloud.githubusercontent.com/assets/14146739/9703952/f54b77be-5493-11e5-8e13-986e5c386b1f.png)

**Comment by gorhill** [comment] 2015-09-06 11:51
Duplicate of #605.

**Closed by gorhill** 2015-09-06 11:51 UTC
