### ISSUE TITLE
Blocking Ads Seems To Not Work First Load - Intemittently

### ISSUE THREAD

**Issue by sciguyryan** [gorhill/uBlock#2683] opened 2017-06-05 19:23 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue

After upgrading to the latest Firefox nightly build I've noticed that ads within Youtube videos are appearing intermittently on the first opening. A force refresh of the page displays the video without it.

### One or more specific URLs where the issue occurs

https://www.youtube.com/watch?v=OOaxPn5uV08 (Random example where I saw this today_

### Screenshot in which the issue can be seen
N/A

### Steps for anyone to reproduce the issue

1. Visit the URL above.
2. The video will sometimes render with an ad.
3. Forcibly refreshing should display the video without an ad.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10 Professional 64-bit
- Browser/version: Firefox 64-bit Nightly (build as of 5/6/16)
- uBlock Origin version: 1.12.5rc1

##### Your filter lists
Default lists, no additions.

##### Your custom filters (if any)
None.

**Comment by gorhill** [comment] 2017-06-05 19:57
Duplicate of #1327.

**Closed by gorhill** 2017-06-05 19:57 UTC
Labels: duplicate
