### ISSUE TITLE
uBlock loses tab/scope when separating a tab

### ISSUE THREAD

**Issue by luxoflux** [gorhill/uBlock#2699] opened 2017-06-13 00:25 UTC
uBo 1.12.5rc3 / Firefox 53 / Win 10

When you separate a tab from the main browser window, uBlock appears to lose the tab and defaults to global 3p settings. For me the page disconnects completely because I block everything by default.

The clearest and easiest way to test this I've found is by playing a [YouTube video](https://www.youtube.com/watch?v=iNJdPyoqt8U), then immediately dragging the tab out into its own window. The video will stop downloading/playing (besides cached content). You have to manually reload the page. There's nothing obvious reported in the browser console.

Settings to reproduce:

* Block 3p and 3p-scripts globally, noop YouTube. No other special settings.

```
* * 3p block
* * 3p-script block
www.youtube.com ggpht.com * noop
www.youtube.com googlevideo.com * noop
www.youtube.com gstatic.com * noop
www.youtube.com youtube.com * noop
www.youtube.com ytimg.com * noop
```

Thanks.

**Comment by gorhill** [comment] 2017-06-13 02:52
Duplicate of #1120.

**Closed by gorhill** 2017-06-13 02:52 UTC
