### ISSUE TITLE
Ublock broken in Tails 3.3

### ISSUE THREAD

**Issue by moonshineisdelicious** [gorhill/uBlock#3235] opened 2017-11-16 06:57 UTC
ublock is broken in Tails 3.3 is this an Issue with Tor Browser 7.0.10 / Firefox 52.5.0 or is it Tails fault?
Reinstalling does not fix it going to chrome://ublock0/content/dashboard.html show everything blanked  out no checkmarks no blocking lists yet websites blocking ad blockers get triggered by  it and block me from accessing them

**Comment by hchr** [comment] 2017-11-16 10:39
Tor 7.0.10 with uBlock Origin v1.14.0 works as intended.
If I upgrade uBlock to v1.14.8 it doesn't.
It doesn't remember my settings on tab settings.
I can't switch to any other tab, it just color the background of the link line yellow, for a short moment and stay on settings tab.
 Like @moonshineisdelicious websites blocking ad blockers get triggered by it and block me from accessing them
However I can pick something to block and input the filter to block that and it removes the blocking.
If I restart Tor browser, uBlock remember that one filter.

**Comment by hchr** [comment] 2017-11-16 11:03
If I make a new empty profile in Firefox 56.0.2  and only install uBlock Origin v1.14.18, import a backup of ublock, everything works as intended.
So it most be another add-on that effects uBlock.

**Comment by hchr** [comment] 2017-11-16 11:21
This add-on breaks uBlock:
Clean Links 2.7.1. 
Remove and uBlock Origin fly again

**Comment by gorhill** [comment] 2017-11-16 13:00
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-11-16 13:00 UTC
Labels: invalid
