### ISSUE TITLE
"uBlock filters – Experimental‎" is no more active after restore settings from file

### ISSUE THREAD

**Issue by Alpengreis** [gorhill/uBlock#1871] opened 2016-08-06 15:04 UTC
"uBlock filters – Experimental‎" is no more active after restore settings from file. I had to activate manually.

uBlock Origin v1.8.3b0, Firefox 48.0 x64 (de) (release), Win 10 Pro x64 1607 (14393.10)

**Comment by gorhill** [comment] 2016-08-06 15:15
Duplicate of #344.

**Closed by gorhill** 2016-08-06 15:15 UTC

**Comment by Alpengreis** [comment] 2017-02-02 19:36
Unfortunately that Is not fixed with the patch from [#344](https://github.com/gorhill/uBlock/issues/344) ... It's even more worse now because some other filters are inactivate too after restore (only the custom filters are fixed).

**Comment by gorhill** [comment] 2017-02-02 19:50
> some other filters are inactivate too after restore

Can you be more detailed?

**Comment by gorhill** [comment] 2017-02-02 19:58
> Unfortunately that Is not fixed with the patch from #344

Just tried and it works fine here with 1.10.7rc3:

- Go to dashboard/_"3rd-party filters"_
- Select _"uBlock filters - Experimental"_
- Click _"Apply changes"_
- Go to dashboard/_"Settings"
- Click _"Back up to file"_
- Click _"Restore from file..."_

Result:

- _"uBlock filters - Experimental"_ is properly selected.

**Comment by Alpengreis** [comment] 2017-02-02 23:42
Browser and OS: Fx v51.0.1 x64 on my Win 10 Pro x64 (v6.3.14393)
uBlock Origin: v1.10.7rc3:

**Step 1:**
I open a new Tab in Browser

**Step 2:**
I check the current setting of filter, which is ...
![ubo filter before restoring current 1-2](https://cloud.githubusercontent.com/assets/11355601/22573358/ec290ede-e9a8-11e6-8554-b48901d5fd5d.PNG)
![ubo filter before restoring current 2-2](https://cloud.githubusercontent.com/assets/11355601/22573361/ef961d6e-e9a8-11e6-90f8-4b962d91e0f5.PNG)

**Step 3:**
I export uBlock settings

**Step 4:**
I reset the uBlock settings, and check it ...
![ubo filter after set to default 1-2](https://cloud.githubusercontent.com/assets/11355601/22573427/38273ebe-e9a9-11e6-89ea-a02f7e533e6e.PNG)
![ubo filter after set to default 2-2](https://cloud.githubusercontent.com/assets/11355601/22573430/3a1e8d3a-e9a9-11e6-9c6b-fe5d672a2e5a.PNG)

**Step 5:**
I restore the uBlock settings via Backup-File, then check the results ...
![ubo filter after restoring 1-2](https://cloud.githubusercontent.com/assets/11355601/22573479/70ff21c0-e9a9-11e6-9e2e-994a09871f73.PNG)
![ubo filter after restoring 2-2](https://cloud.githubusercontent.com/assets/11355601/22573483/7297e33c-e9a9-11e6-91ce-3614112cbbec.PNG)

As you can see it's almost the same as right after setting back to default, EXCEPT the custom filters, which are now there but unselected ...

Note: you will not find the DEU Filter list in the screenshots (which is correct selected always)

**Comment by okiehsch** [comment] 2017-02-03 00:09
I can reproduce up to Step 5, but after
**Step6:**
Restart Firefox
The correct filterlists are selected on my end.

**Comment by gorhill** [comment] 2017-02-03 04:10
Still unable to reproduce.

**Comment by gorhill** [comment] 2017-02-03 05:04
Any error at the browser console?

**Comment by okiehsch** [comment] 2017-02-03 05:56
No error at the browser console.
The only way for me to get the correct filterlists selected is to restart Firefox right after I
restore the settings. If I change the filterlists or even just update them before restarting, the restart doesn't solve the issue.

**Comment by gorhill** [comment] 2017-02-03 13:15
Since I can't reproduce, I can just guess of what the issue might be. I am guessing that not waiting for the write operation to complete before restarting uBO might be the issue.

@okiehsch Are you building your own uBO from master branch? If so, is it possible for you to test whether the last commit helps?

**Comment by okiehsch** [comment] 2017-02-03 14:38
> Are you building your own uBO from master branch?

Sorry I do not.

**Comment by gorhill** [comment] 2017-02-03 14:47
I will create a temporary release just for testing purpose. If ever the issue is confirmed as fixed, I will then create an rc4 release.

**Comment by gorhill** [comment] 2017-02-03 14:50
New version with latest commits: https://github.com/gorhill/uBlock/releases/tag/1.10.7dev

**Comment by Alpengreis** [comment] 2017-02-03 15:52
Here even a Fx restart does NOT help.

I would test the 1.10.7dev but can't since Firefox does only allow AddOns from https://addons.mozilla.org/ for the normal Fx version ...

**Comment by okiehsch** [comment] 2017-02-03 18:04
@gorhill I tested with `Firefox 53`  and 1.10.7dev and the correct filterlists are selected,
so the problem is fixed on my end.

**Comment by gorhill** [comment] 2017-02-03 18:09
@okiehsch Thanks for testing.

So apparently uBO can't count on the sql database last statement to be committed if the connection is closed then opened shortly afterward, at least for some environments -- I had made the assumption this was the case.

I will push rc4.

**Comment by Alpengreis** [comment] 2017-02-03 18:26
Thanks both!
