### ISSUE TITLE
uBO unable to block certain background requests

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1328] opened 2016-02-01 20:08 UTC
I'm probably missing something here but I thought I'd still open an issue in case this can be fixed.

Chrome 48.0.2564.97
uBlock Origin v1.5.6

I enabled Advanced User Mode and removed the whitelist for background requests so now Google Analytics on GitHub is being blocked completely. However certain requests my extensions make don't show up in the logger. I can see the list update requests of uBO but I can't see any requests when I'm clicking the update button in Ghostery, when I update my scripts in Tampermonkey or when I use Bookmark Checker New to check which of my bookmarks throw an error (it sends a request to all bookmarks' URLs to see which time out or similar).

**Comment by TheGift73** [comment] 2016-02-01 21:47
Hi,

Having an issue when trying to block an ad on this website which will, then redirect you to another page after the ad has finished playing. The page (which directs to a CoinDesk article) was linked via a user on Twitter who runs the 4BC.co site. The link will direct to the article in question and then to the 4bc.com site, leaving little time to read the article. In short, annoying.

I am running uBlock Origin 1.5.6 on Chrome version 48.0.2564.97 m. on Windows 7 Ultimate.

Sequence of events as requested in submission guide:

1. Clicked on [this link](https://t.co/7JuePAFwlz) in a Twitter post from [this users comment](https://twitter.com/cryptlocal/status/694258466790092801).

2. [Directed to the article](http://iframe.4bc.co/split.html?http://www.coindesk.com/japans-bank-tokyo-mitsubishi-mufg-coin/?utm_source=dlvr.it&utm_medium=twitter) in question, but with iframe split in URL.

3. Once the ad (located at the top of the page of the URL in point No.2 above) has finished played, the user will be directed to the following referral page for 4bc.co

Extensions that are enabled in Chrome when issue is present:

- Application Launcher for Drive (by Google) 3.2
- Block Yourself from Analytics 2.3.0
- Data Saver 2.0.1
- Google Mail Checker 4.4.0
- Image Downloader 2.2.3
- Imagus 0.9.8.34
- imgur Extension by Metronomik 2.1.0
- ImprovedTube - YouTube Extension 0.7.22
- MightyText - SMS from PC & Text from Computer 17.1
- Open Tweet Filter 2.4.4
- reddit companion 1.1.2
- Reddit Enhancement Suite 4.6.0
- Save to Google Drive 2.1.1
- Search by Image (by Google) 1.5.1
- Silver Bird 1.9.10.2
- uBlock Origin 1.5.6
- WebRTC Block 2.0.1
- WebRTC Network Limiter 0.2.1.3

The issue remains when all other extensions except uBlock Origin are disabled.

Please note that I did try to right-click on the ad in question to kill it, but the 'cross' that appears (changed the appearance of your cursor so that you can target the ad) does nothing when used.

Hope that helps, more info if requested.

**Comment by gorhill** [comment] 2016-02-01 21:56
Duplicate of #686.

Summary: no longer possible to see another extension's network requests, ability was removed by the Chromium devs.

**Closed by gorhill** 2016-02-01 21:56 UTC
