### ISSUE TITLE
uBlock and Pentadactyl

### ISSUE THREAD

**Issue by vanzef** [gorhill/uBlock#1588] opened 2016-04-24 09:10 UTC
### Describe the issue

It's impossible to open uBlock (and uMatrix) window with Pentadactyl addon and Toolbar (Firefox ui element) disabled. If Toolbar is enabled everything work.

### Screenshot in which the issue can be seen

https://imgur.com/a/t8XXc

### Steps for anyone to reproduce the issue
1. Install Pentadactyl from http://5digits.org/pentadactyl/ (nightly build, because others doesn't support modern Firefox versions)
2. Disable Toolbar: Press ":" and then type "set guioptions-=T"
3. Try to open uBlock or uMatrix window (by clocking on their icons)

### Your settings
 * Prevent WebRTC from leaking local IP addresses 
 * I am an advanced user

- Browser/version: Firefox Nightly 45.0.2
- uBlock Origin version: 1.6.8

##### Your filter lists

Default filter lists + uBlock filters – Experimental‎ +  RUS: RU AdList

**Comment by gorhill** [comment] 2016-04-24 12:13
Duplicate of #610.

**Closed by gorhill** 2016-04-24 12:13 UTC
