### ISSUE TITLE
[Suggestion] Support the legacy Firefox toolbar

### ISSUE THREAD

**Issue by ParticleMon** [gorhill/uBlock#151] opened 2015-04-29 12:19 UTC
Support the legacy toolbar in Firefox versions/variants that do not support Australis (CustomizableUI), such as Pale Moon.

See the Legacy Toolbar Button Test builds here: https://github.com/AlexVallat/uBlock/releases/.

**Comment by 5t3f4n** [comment] 2015-04-29 13:59
Millionth dupe of this.
#40 
>See chrisaljoudi#518. I do not intend to spend time any more time on this. I did provide ability to access the popup UI from the request log, that's as far as I am willing to go. It's volunteered work, so in my opinion another developer should step up for addressing whatever needs to be worked on for Palemoon support if they think it's worth it.

#49
>Ok, AlexVallat's work on https://github.com/chrisaljoudi/uBlock addresses all the issues of supporting legacy Firefox-based browsers. I decided I won't be importing his fixes, he is the best placed developer to provide follow-up support on whatever issue may arise relative to his work. So for those who wish a fully workable uBlock on legacy Firefox-based browser, https://github.com/chrisaljoudi/uBlock is the version to install.

Your options seem to be to switch to the fork you linked or use the button in the Network request log.

**Closed as completed** 2015-04-29 14:55 UTC

**Comment by gorhill** [comment] 2015-06-17 18:21
@AlexVallat's [work for Firefox legacy support](https://github.com/gorhill/uBlock/issues/264) has been imported in uBlock Origin. Currently available in dev build: <https://github.com/gorhill/uBlock/releases>.
