### ISSUE TITLE
[Palemoon] 1.3.4 removed all settings & built in 3rd party filters

### ISSUE THREAD

**Issue by Tharn** [gorhill/uBlock#948] opened 2015-11-19 18:10 UTC
After updating uBlock from the previous version to 1.3.4, all my custom settings are gone and the 3rd party filter page looks like this: http://i.imgur.com/iudHGm5.png

I've deleted the ublock0.sqlite file and restarted but it didn't change anything.

**Comment by gorhill** [comment] 2015-11-19 18:18
I tested on Pale Moon 26.0.0b1 (linux) and all was fine.

Any error message in browser console?

**Comment by Tharn** [comment] 2015-11-19 18:24
Weird.. when I installed 1.3.4 again to test it, it worked fine this time around. Can be closed, I guess?

**Comment by Tharn** [comment] 2015-11-19 18:27
It appeared to have updated fine when I tried it again, but one I restarted the browser, I get the same issue. All settings are gone. The error console reads: http://i.imgur.com/IyAYaBu.png

**Comment by gorhill** [comment] 2015-11-19 18:49
What version of Pale Moon are you using?

**Comment by Tharn** [comment] 2015-11-19 18:53
25.8.0, 64-bit on Windows 8.1.

**Comment by gorhill** [comment] 2015-11-19 21:54
> 25.8.0, 64-bit on Windows 8.1.

Works fine for me with 25.8.0 (linux) and 25.8.0 (Windows 7 in VM).

According to your dev console, the cause is one of the two first errors, the two following errors are a consequence of one of the first two. The boostrap code was changed in 1.3.4 relative to 1.3.3 -- in order to fix Nightly for Android not working. Since I can't reproduce the error, I can't investigate, someone with dev skills will have to pitch in. One thing would be to look at the call stack for the first error -- however I don't know how this can be done, there is no _Debug_ button for uBO on Pale Moon.

**Comment by gorhill** [comment] 2015-11-19 22:53
This is what I get so far. Somewhere in uBO's code there is a look-up of `browser.currentURI` property. In Pale Moo and SeaMonkey 31, this maps internally to:

    return this.webNavigation.currentURI;

In more recent Firefox 42, SeaMonkey 38, this maps to:

    if (this.webNavigation) {
            return this.webNavigation.currentURI;
          }
          return null;

So apparently `this.webNavigation` can be `null`, and older FF versions did not check for this. Now the key is to find where in uBO the call to `browser.currentURI` fails internally. Need the call stack.

**Comment by gorhill** [comment] 2015-11-19 23:15
Can you try the [latest dev build](https://github.com/gorhill/uMatrix/releases) and see if this fix your issue?

**Comment by Tharn** [comment] 2015-11-19 23:31
Seems to be fixed in the dev build. Cheers!

**Comment by gorhill** [comment] 2015-11-19 23:58
I need to know what the browser console report.

**Comment by Tharn** [comment] 2015-11-19 23:59
Sorry, updated my reply. The error console shows the exact same errors.

**Comment by gorhill** [comment] 2015-11-20 00:06
Is there no Pale Moon users who were using the dev build of uBO? I waited so long before releasing 1.3.4 I was pretty sure it would be issue-less. Now since I can reproduce the issue, I can't investigate the source. One dev able to repro the issue would need to add code which place in uBO the call to `browser.currentURI` throws an exception.

**Comment by Tharn** [comment] 2015-11-20 00:12
I'll bring it up on the forum. Most of the people I know that use PM & uBO are indeed just users since officially the browser team is maintaining an ABP fork.

**Comment by gorhill** [comment] 2015-11-20 00:17
Ok I manually updated a new build dev just for the sake of tracking this issue. I added `console.trace` call for places where `currentURI` is called. See what the browser console says.

**Comment by gorhill** [comment] 2015-11-20 00:29
> I just tried it and ironically the 1.3.5b0 refuses to break on me

Even if it doesn't break, the console may likely contains important information for me since you could reproduce the issue at will.

**Comment by Tharn** [comment] 2015-11-20 00:42
[01:34:02.619] Could not read chrome manifest 'file:///C:/Program%20Files/Pale%20Moon/chrome.manifest'.
[01:34:02.663] CtPpe: PluginContent is undefined
[01:34:02.687] Could not read chrome manifest 'file:///C:/Program%20Files/Pale%20Moon/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
[01:34:02.688] While creating services from category 'profile-after-change', could not create service for entry 'Disk Space Watcher Service', contract ID '@mozilla.org/toolkit/disk-space-watcher;1'
[01:34:02.917] chrome://ublock0/content/js/vapi-background.js :: optionsObserver.register :: 3300
chrome://ublock0/content/js/vapi-background.js :: null :: 3334
chrome://ublock0/content/js/vapi-background.js :: null :: 29
[01:34:02.933] this.docShell is null @ chrome://global/content/bindings/browser.xml:384
[01:34:02.967] Use of Mutation Events is deprecated. Use MutationObserver instead. @ chrome://browser/content/browser.xul
[01:34:02.979] Updating timestamp of 08affa60a8d990d5cfebeffc072217d9.png
[01:34:03.291] S4EDownloadService using DownloadManagerHandler backend
[01:34:03.532] Unknown property 'enable-background'.  Declaration dropped. @ chrome://ublock0/content/img/browsericons/icon16.svg
[01:34:03.566] chrome://ublock0/content/js/vapi-background.js :: vAPI.net.registerListeners/locationChangedListener :: 2260
[01:34:03.592] Unknown property 'enable-background'.  Declaration dropped. @ chrome://ublock0/content/img/browsericons/icon16-off.svg
[01:34:05.321] chrome://ublock0/content/js/vapi-background.js :: vAPI.net.registerListeners/locationChangedListener :: 2260

**Comment by gorhill** [comment] 2015-11-20 00:46
Thanks. I suspected this could happen for `optionsObserver`. Will try to fix asap.

**Comment by gorhill** [comment] 2015-11-20 01:00
I just overwrote the build dev with a new `xpi` -- I will wait for your feedback about whether the issue is fixed.

**Comment by Tharn** [comment] 2015-11-20 01:04
I'm not seeing any mention of uBlock in the browser console with that latest .xpi. Settings are working for me.

**Comment by gorhill** [comment] 2015-11-20 01:09
Ok thanks. I would prefer another confirmation from Freezing Moon before officially releasing the fix. (I registered to the forum today, but my posts have not appeared, so not point for me to post there until I can freely post).

**Comment by gorhill** [comment] 2015-11-20 05:13
Closing as per feedback on Pale Moon forum.

**Closed by gorhill** 2015-11-20 05:13 UTC

**Comment by 5t3f4n** [comment] 2015-11-20 11:27
@gorhill can you provide some assurance here?
First off, does this affect Firefox at all or is it specific to Pale Moon?

Here's my situation:
Was on Firefox 42.0 and uBlock Origin 1.3.2 (I think)
It updated to 1.3.4 automatically overnight
When I woke up in the morning I updated manually to 1.3.5
I have not restarted Firefox during all this – is it safe for me to quit/restart Firefox now?

**Comment by Goderw** [comment] 2015-11-20 13:35
1. This might affect older Versions of Firefox as well.
2. Since uBo needs no restart of FF to update or install completely -> no problem if it was updated twice in one session.
3. You can restart now... you don't have to quit. ;)
