### ISSUE TITLE
Full page download hangs when uBlock Origin is active

### ISSUE THREAD

**Issue by butonic** [gorhill/uBlock#1185] opened 2016-01-07 08:11 UTC
## How to reproduce

1. Go to http://www.heise.de/newsticker/meldung/US-Psychologe-Brainstorming-funktioniert-nicht-3058339.html or the main page http://www.heise.de/
2. right click and choose "save as ..."
3. Save the full page to the local disk.

The download hangs at "3/42 B". Disabling uBlock Origin allows the download to complete fine. But I don't really want to archive ads ...

## Logger
The logger only contains:

08:59:23		||optimizely.com^$third-party	--	object	http://cdn.optimizely.com/js/2310910166.js
08:59:23				object	http://www.heise.de/js/plugins/jquery-ui-1.8.18_cycle.custom.min.js
08:59:23				object	http://www.heise.de/js/jquery/jquery-1.7.1.min.js
08:59:23				object	http://www.heise.de/js/mobile-deflect.min.js

or for the main page:

09:03:08		||yieldlab.net^	--	object	http://ad.yieldlab.net/yp/66424,66430,66442,66444,66446?ts=20160107090259
09:03:08				object	http://script.ioam.de/iam.js
09:03:08				object	http://www.heise.de/js/ho/link_inline_images.min.js
09:03:08				object	http://www.heise.de/support/lib/teaser_linking.js
09:03:08				object	http://www.heise.de/js/plugins/jquery.equalheights.min.js
09:03:08				object	http://www.heise.de/js/plugins/jquery-ui-1.8.18_cycle.custom.min.js
09:03:08				object	http://www.heise.de/js/jquery/jquery-1.7.1.min.js
09:03:08				object	http://www.heise.de/js/mobile-deflect.min.js

So it seems to just hang on the first blocked request.

## Configuration changes
I just deinstalled uBlock and installed uBlock Origin, no changes to the settings were done. uBlock has the same issue. Did net even activate Easylist Germany.

## Versions
uBlock Origin 1.5.2
Google Chrome 49.0.2613.0 canary (64-bit)
Windows 10

## Other extensions
Google Docs 0.9
Google Docs Offline 1.1

**Comment by gorhill** [comment] 2016-01-07 13:39
I can't reproduce with Chromium 47.

However I can reproduce with Google Chrome 49. It stops downloading right after a network request has been blocked. Same issue if using ABP. So it's seems to be a browser-specific behavior, and I don't see how this can be worked around other than by whitelisting the site before using _"Save as..."_.

**Comment by offhub** [comment] 2016-04-02 14:28
This is fixed in latest beta/dev. (50.0.2661.57/51.0.2693.2)

**Closed** 2016-04-03 00:16 UTC
Labels: browser bug

**Comment by Safari77** [comment] 2016-04-08 10:16
also fixed in stable 49.0.2623.112
https://chromium.googlesource.com/chromium/src/+log/49.0.2623.110..49.0.2623.112?pretty=fuller&n=10000
