### ISSUE TITLE
Video Ad @chip.de

### ISSUE THREAD

**Issue by akks1981** [gorhill/uBlock#1359] opened 2016-02-09 11:28 UTC
issue with Firefox 45b3 and uBlock Origin 1.6.0rc1

look @ chip.de:
http://www.chip.de/news/Microsoft-Patchday-Sechs-Updates-fuer-kritische-Luecken-in-Windows_89413635.html

http://www.chip.de/news/Microsoft-warnt-Cortana-nicht-sexuell-belaestigen_89403344.html

Video works, but with ad!

greetings

**Comment by gorhill** [comment] 2016-02-09 13:57
_"uBlock filters" should be marked as in need of an update, force an update.

**Comment by akks1981** [comment] 2016-02-09 15:10
Hi bro,

fix not work!

**Comment by gorhill** [comment] 2016-02-09 15:38
Works from here. Try clearing cache, cookies, restart the browser.

**Comment by akks1981** [comment] 2016-02-09 16:04
![video ad](https://cloud.githubusercontent.com/assets/12896716/12921799/1ac0d2ec-cf4f-11e5-8ebd-e297ffdb1a20.png)

dont work for me with firefox 45b3, later i make a cleam istall from firefox!

**Comment by IDKwhattoputhere** [comment] 2016-02-09 16:17
I'm also getting a video ad 2 seconds into both videos on Firefox ESR 38.6.0 with uBO 1.5.5 and 1.6.0 on a fresh profile with updated filters. [Logger](https://cloud.githubusercontent.com/assets/16030872/12922247/eac80d4c-cf50-11e5-98cd-56ca42075d15.png) if of interest.

**Comment by gorhill** [comment] 2016-02-09 22:09
It does not look like `hd-main.js` was redirected in your log. Was it?

![a](https://cloud.githubusercontent.com/assets/585534/12932237/c9bf9602-cf4f-11e5-9ae1-36df7be34ee6.png)

**Comment by IDKwhattoputhere** [comment] 2016-02-09 22:37
No, [it doesn't look like it.](https://cloud.githubusercontent.com/assets/16030872/12932826/3337bcc4-cf85-11e5-8c27-efbfcaef1dd5.png) Nothing with `<<` shows up in the logger. Also `uBlock filters – Block-then-redirect‎` doesn't show up for me in 1.6.0rc1 but maybe it's supposed to be like that?

**Comment by gorhill** [comment] 2016-02-09 22:39
Then your filters are not up to date. Purge the cache for _uBlock filters_ -- this is where the redirect filter is.

**Comment by IDKwhattoputhere** [comment] 2016-02-09 22:45
Already did that a couple of times. The filter even shows up: https://cloud.githubusercontent.com/assets/16030872/12933185/193734c4-cf87-11e5-84ef-1994addbbf3a.png

**Comment by gorhill** [comment] 2016-02-09 22:51
Does un-selecting block-then-redirect list fixes things?

**Comment by IDKwhattoputhere** [comment] 2016-02-09 22:57
No, no change happening.

**Comment by gorhill** [comment] 2016-02-09 23:29
I can now reproduce, it is as if something changed after I fixed the issue.

**Closed** 2016-02-09 23:53 UTC

**Comment by gorhill** [comment] 2016-02-10 00:02
Fixed in 1.6.0rc2.

**Comment by akks1981** [comment] 2016-02-10 07:32
BIG thx now it works with rc2! 

greetings

**Comment by IDKwhattoputhere** [comment] 2016-03-15 13:34
Videa ads back. I think it's because `hd-main.js` was moved to a new CDN.
