### ISSUE TITLE
[Firefox] uBlock's menu doesn't show if uBlock's icon is placed in the window title and the navigation bar is hidden

### ISSUE THREAD

**Issue by oakkitten** [gorhill/uBlock#1585] opened 2016-04-24 00:57 UTC
### Describe the issue

If uBlock's icon is placed in the window title (see screenshot) and the navigation bar is hidden, the menu does not appear on click. other similar menus (triple dots, downloads, as seen on the screenshot) appear just fine.

### Screenshot in which the issue can be seen
![ub](https://cloud.githubusercontent.com/assets/1710718/14764828/114ee73e-09cf-11e6-9504-3e33321d6e37.png)
(nevermind the icon color, changed throuh userchrome.css)

### Steps for anyone to reproduce the issue

1. start a clean Firefox profile, install uBlock Origin
2. move uBlock's icon to the window title
3. Remove navigation toolbar using pentadactyl or the extension that removes it, or otherwise
4. click icon, nothing happens

### Your settings

- Browser/version: 45.0.2 (win10)
- uBlock Origin version: 1.6.8

**Comment by gorhill** [comment] 2016-04-24 05:49
Duplicate of #610.

**Closed by gorhill** 2016-04-24 05:49 UTC
