### ISSUE TITLE
(Advanced Settings) modified userResourcesLocation reverts back to unset

### ISSUE THREAD

**Issue by ChronoVlad** [gorhill/uBlock#3472] opened 2018-01-29 05:23 UTC
### Describe the issue

After changing userResourcesLocation "unset" to "https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt" (instructed here: https://jspenguin2017.github.io/uBlockProtector/) it'll revert back to "unset" if i close my browser then start it up again.

### Steps for anyone to reproduce the issue

1.     Go to advanced settings.
2.     userResourcesLocation unset to userResourcesLocation https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt
3.     Restart Waterfox.
4.     Go to advanced settings and userResourcesLocation has reverted back to unset.

### Your settings

- Windows 7 (64bit) Home Premium
- Waterfox 56.0.3
- uBlock Origin version:  1.14.24

**Comment by Ravizz** [comment] 2018-01-29 07:03
I cannot reproduce, but it has happened to me once too, several days ago.

FF 58 & uBO 1.14.25.101 & ND 13.28

**Comment by FatOrangutan** [comment] 2018-01-29 07:43
Duplicate of https://github.com/gorhill/uBlock/issues/3387

**Closed** 2018-01-29 12:20 UTC
Labels: duplicate
