### ISSUE TITLE
[Suggestion] Microsoft Edge version

### ISSUE THREAD

**Issue by PalZer0** [gorhill/uBlock#1492] opened 2016-03-21 10:35 UTC
With the release of Windows 10 insider build 14291, extensions are now available in Microsoft Edge.

I'd like to see uBlock Origin made available for Microsoft Edge.

**Comment by harshanvn** [comment] 2016-03-21 10:40
Duplicate of #1486 

Unfortunately, this will not be available unless some one comes up with a fork and maintains it :(

**Closed** 2016-03-21 12:48 UTC
