### ISSUE TITLE
Cloudflare Issue; Filterlist won't update

### ISSUE THREAD

**Issue by troysjanda** [gorhill/uBlock#3261] opened 2017-11-21 21:58 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
For some reason I am being bombbarded with Cloudflare captcha crap. I have to the best of my ability preformed the troubleshooting solutions outlined at the cloudflare site I have,
cleared cache/cookies
ran malwarebytes and bitdefender scans can results are negitive
rebooted
if trying to update filters all filters show triangle and broken link icons and don't update

### One or more specific URLs where the issue occurs
adguard.com everyother site protected by loudflare
[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen
not able to screen shot
[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue
1 clear cache
2 update filters

### Your settings
default ublock settings with default filter lists, ff57 default settings
[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Windows 10
- Browser/version: FF57
- uBlock Origin version: uBlock Origin 1.14.19b9

##### Your filter lists
default list

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

##### Your custom filters (if any)
none

####note####
have saught support from Cloudflare without any reply or success.  I am not blacklisted anywhere, and have been whitelisted at projecthoneypot site not behind a proxy, or VPN have statis IP

**Comment by Eeems** [comment] 2017-11-21 22:11
This is not a uBlock issue. As you yourself said, this is CloudFlare blocking your IP.

**Comment by gorhill** [comment] 2017-11-21 22:12
You are not making the case there is an issue with uBO itself. You are making the case you have issue with your network blocking `adguard.com`.

This is not a general support forum, this is an issue tracker which must be used solely to report issues with uBO proper, along with all the evidence supporting the issue is with uBO itself.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-11-21 22:12 UTC
Labels: invalid

**Comment by troysjanda** [comment] 2017-11-21 22:16
Thank you sir
