### ISSUE TITLE
Yahoo Mail login error

### ISSUE THREAD

**Issue by mspin** [gorhill/uBlock#2733] opened 2017-06-24 20:57 UTC
Yahoo Mail Issue with UBlock: "Network connection timed out. Please try again."
When UBlock is disabled, I can login. No other issues with Ublock. 

This occurs whenever I attempt to login to my email with UBlock on. Started occuring about two weeks ago. Browser and Ublock plugin have current updates applied. 

URL: https://login.yahoo.com/?.src=ym&.intl=us&.lang=en-US&.done=https%3A%2F%2Fmail.yahoo.com&authMechanism=primary&yid=&done=https%3A%2F%2Fmail.yahoo.com%2F&eid=100&as=1&login=mspin8&crumb=u0b5F7oL2OJ

Steps: 
Access Yahoo Mail login page
Enter Username

Settings files are attached. and Screenshot of log attached below: 
![ublock yahoomail](https://user-images.githubusercontent.com/29681221/27511893-f7310132-58e4-11e7-82a8-79d3cd04e941.png)

No other modifications
Windows 7 SP1 All non telemetry updates applied
- uBlock Origin version:  1.13.0
Firefox 53.0.3

Default Filter Lists

**Comment by gorhill** [comment] 2017-06-24 21:02
How did you rule out that the issue is not a filter issue?

**Comment by gorhill** [comment] 2017-06-24 21:09
I can login just fine. You have a filter `||login.yahoo.ca^', that is not part of any default filter lists. The issue is on your side.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-06-24 21:09 UTC
Labels: filter issue, invalid

**Comment by gorhill** [comment] 2017-06-26 13:48
http://www.malwaredomains.com/?p=4082

**Comment by bershan2** [comment] 2017-06-26 14:00
For the record: this URL is available over HTTPS (but does not default to HTTPS):
<https://www.malwaredomains.com/?p=4082>
