### ISSUE TITLE
uBO treats previous site as current first part site.

### ISSUE THREAD

**Issue by ThurahT** [gorhill/uBlock#1515] opened 2016-03-29 14:00 UTC
When browsing normally the previous site lingers on to the next site and makes that one 3-part which I has set to block.

A picture describes it best: http://i.imgur.com/L6ocsYk.png

yr.no was the previous site I visited while smhi.se is the new site and it gets blocked since uBO still has yr.no as primary site. I guess uBO doesn't update the list somehow?

Closing the tab solves the issue.

uBO 2.6.6
Seamonkey 2.38

**Comment by gibwar** [comment] 2016-03-29 14:23
I've run in to this problem as well. Downgrading the Firefox extension from 1.6.6 to 1.6.4 resolved the issue, so it was definitely introduced between those versions. Happens with the advanced mode like the screenshot above indicated.

**Comment by gorhill** [comment] 2016-03-29 15:02
Is this something you can reproduce easily?

**Comment by gorhill** [comment] 2016-03-29 15:43
Duplicate of #1514.

This has been reported by a few people now, but it seems a rare occurrence.

Since such issue was non-existent with 1.6.4, I have modified the code to be closer to what was in 1.6.4 -- build available on AMO as dev version 1.6.7b0. For those who can reproduce at will, it would be nice if you could try the latest dev build to see if this solves the issue.

**Closed by gorhill** 2016-03-29 15:43 UTC
Labels: need feedback

**Comment by ThurahT** [comment] 2016-03-29 17:46
Ah, sorry for duplicate, I should have looked closer. Yes I can reproduce it with the sites in my screen shot. Testing 1.6.7b and the bug is still there. I can actually populate the list if I continue to surf to different sites. The blocked sites just adds up. It doesn't matter if the sites are white listed or not.

**Comment by gorhill** [comment] 2016-03-29 18:50
After installing 1.6.7b0, did you restart Firefox? (and ensure no Firefox process are still in memory) This is important to be sure the old instance of frame scripts are flushed from memory.

**Comment by ThurahT** [comment] 2016-03-29 19:18
I did. And I did again just now to be sure. It is still reproduceable. I should mention again though that I am on SeaMonkey 2.38. Maybe it has to do with blocking all third party requests and having allowed sites set to noop?

With PaleMoon 26.1.1 I can't reproduce. But that browser is mostly used as a dummy adblocker and has no rules except  * * * noop.

**Comment by ThurahT** [comment] 2016-03-29 21:03
Issue for my part resolved. See #1514 for details.
@gibwar make sure all process instances are closed and try again.

**Comment by gibwar** [comment] 2016-03-30 14:12
I can confirm that 1.6.7b0 fixed it for me as well, running Firefox 45.0.1 with a ton of rules.
