### ISSUE TITLE
Removing/noop'ing a class

### ISSUE THREAD

**Issue by Zopieux** [gorhill/uBlock#1109] opened 2015-12-25 01:28 UTC
Many websites use big modal dialogs to display nasty ads or other nasty announcements. They usually come as two things:

1. the dialog itself, usual a `<div>` with a big `z-index`;
2. a `<body>`-wide class that is used to apply a black overlay on the whole website, disable scrolling, and the like.

At the moment uBlock can be used to hide the dialog (1.) but AFAICT there is no way to remove or replace the class (2.) making the website unusable. Would it be possible to implement such a feature?

**Comment by gorhill** [comment] 2015-12-25 01:30
> there is no way to remove or replace the class (2.)

How come? I usually can remove that overlay without any issue. Can you give me an example of a case (URL)?

**Comment by lewisje** [comment] 2015-12-25 04:14
It sounds like something that is out of scope and best suggested for Reek's anti-adblock UserScript.

**Comment by RoxKilly** [comment] 2015-12-25 13:52
@Zopieux , open the uBO panel and select the eyedropper tool, then hover the mouse over the body-wide overlay (it will be highlighted in pink) and click it.  A menu will open of possible cosmetic filtering rules that could be used to hide the overlay.  Usually, the first option (the most specific) is the best.  Select it, click `Create` button at the bottom of the menu and the overlay will be filtered.

**Comment by Zopieux** [comment] 2015-12-25 14:58
@gorhill @RoxKilly The overlay is not really a problem. The real issue I'm having is eg. this CSS:
```css
.noscroll { overflow: hidden; }
```
then
```html
<body class="noscroll"> <!-- class added with Javascript -->
```
This prevent from scrolling. Removing the class or replacing the `noscroll` CSS would solve that but as @lewisje said, it may be out of the scope of uBlock.

**Comment by gorhill** [comment] 2015-12-31 16:35
Duplicate of #781 (if ever I decide to implement the feature).

**Closed by gorhill** 2015-12-31 16:35 UTC

**Comment by sqren** [comment] 2016-05-13 05:47
This is becoming increasingly important. Many sites today detect adblockers, and will do exactly as @Zopieux describes. 
What I'd like is either:
1) a way to remove a css class from an element, or
2) a way to modify a specific css class

Without the above, I'll have to rely on other greasemonkey-like extensions, or have to adhere to the websites, and disable ublock (which I'd really like to avoid).

**Comment by RoxKilly** [comment] 2016-05-16 02:12
You can use dev tools in your browser to add/remove CSS classes. in Firefox, press CTRL+SHIFT+C to open the Inspector.  Select the `<body>` tag. On the right, select the "Rules" tab to see which rules are in effect.  You can manually remove rules. So just look for `.noscroll { overflow: hidden; }` and uncheck `overflow:hidden`

![2](https://cloud.githubusercontent.com/assets/12346501/15278676/ef8308de-1ae9-11e6-8bb8-d953481a957f.png)

You can also edit the body tag directly within the Inspector.  Double-click it, and you may see something like `<body class="noscroll">`   Just delete `noscroll` from the class string.

So far no one on this thread has provided a specific test case for us to look at.

**Comment by sqren** [comment] 2016-05-16 07:57
@RoxKilly I'm using [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) to automate this, and it works pretty well. 

**Test case**
 - Enable uBlock and open http://politiken.dk/ 
 - You'll see an overlay (black background, and white message box with the text)

The uBlock rule I'm using to block the overlay is:
```
! 5/13/2016, 7:39:53 AM http://politiken.dk/
politiken.dk##body>div:first-child
```

The Stylish rule I'm using to enable scrolling is:
```
body.dit-modal-open {
    overflow: visible;
}
```

![screen shot 2016-05-16 at 08 51 10](https://cloud.githubusercontent.com/assets/209966/15283574/7790b0d8-1b43-11e6-892f-ecf588316a8b.png)

**Comment by RoxKilly** [comment] 2016-05-16 10:41
Interesting.  Thanks for the tip about Stylish.

I block 1st-party Javascript by default and allow it on a per-domain basis with uBO advanced settings. For this reason I avoid many of the problems reported here.  In this case, the overlay seems to depend on some Javascript because I didn't see it (and I had no trouble scrolling) until I enabled JS.

**Comment by gorhill** [comment] 2016-05-16 11:22
>     body.dit-modal-open {
>         overflow: visible;
>     }

I have been contemplating forcing this style on a `body` and `html` element in the overlay-buster scriptlet -- I find it is common for sites to also remove the scrollbars when they display a DOM overlay.
