### ISSUE TITLE
Some active cosmetic filters are not indicated in the menu or logger.

### ISSUE THREAD

**Issue by sumyungguy** [gorhill/uBlock#2749] opened 2017-06-30 17:41 UTC
### Describe the issue
A filter in a list has the form:
wetteronline.de##[style="width: 100%;"]
The filter breaks the page, but there is no indication in the logger, DOM inspector, or the cosmetic filtering indicator on the menu, that any cosmetic filter is present. I had to resort to much trial-and-error and manual searching through the filter lists, to find the rule and override it.

I'm not sure if the filter is an error or malformed in some way, but even if it is, there should be an indication in the logger that it's being applied.

### One or more specific URLs where the issue occurs

http://www.wetteronline.de/regenradar/hessen?gid=10637

### Screenshot in which the issue can be seen

Note that the animation controller slider is far too wide for its container, and spills out to the right:
![screenshot_225](https://user-images.githubusercontent.com/5410893/27746483-a863124c-5dc7-11e7-8123-675276b0af76.png)

It should look like this:
![screenshot_226](https://user-images.githubusercontent.com/5410893/27746607-2a9fa2ca-5dc8-11e7-8bd4-4d897bcc37c3.png)

### Steps for anyone to reproduce the issue

1. Install "Easy List Germany", and visit the above URL, note the breakage.
2. Click the "toggle cosmetic filtering for this site" and note the breakage is fixed. Toggle again.
3. Open the logger and/or DOM inspector, and note that there are 3 cosmetic filters listed.
4. Override those filters in "My filters" with:
```
www.wetteronline.de#@##woRect
www.wetteronline.de#@##topcontainer
www.wetteronline.de#@##rightcontainer
```
5. Reload and note that the page is still broken.
6. Note that there are no longer any cosmetic filters indicated in the logger, DOM inspector, or on the "toggle cosmetic filtering for this site" button in the menu.
7. Click "toggle cosmetic filtering for this site" anyway, and note that the page is no longer broken.
8. Manually search the filter lists and find the rules:
```
wetteronline.de##[style="top: -252.5px; left: 0px; position: absolute;"]
wetteronline.de##[style="width: 100%;"]
```
9. Override the second one in "My filters" with `wetteronline.de#@#[style="width: 100%;"]`
10. The breakage is fixed.
11. Now you can delete the first three overrides.

### Your settings

- OS/version: macOS 10.12.5
- Browser/version: Firefox 54.0.1
- uBlock Origin version: 1.13.4

##### Your filter lists

Default filter lists + DEU

##### Your custom filters (if any)

Various...

**Comment by okiehsch** [comment] 2017-06-30 17:49
Filter list issues have to be opened [here](https://github.com/uBlockOrigin/uAssets). This issue will be closed as invalid.

**Comment by gorhill** [comment] 2017-06-30 19:52
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by sumyungguy** [comment] 2017-07-01 16:16
I respectfully submit that this issue was not a complaint about a filter issue, but about an issue with uBlock user interface. [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md) states "Use the logger to diagnose/confirm filter-related issues." But that is impossible with a filter of this form since the filter does not show up in the logger, DOM inspector, or  "toggle cosmetic filtering for this site" button count, even though it's active.

**Comment by gorhill** [comment] 2017-11-16 06:03
I can't reproduce the issue. There is no more element matching `[style="width: 100%;"]`, so I used `wetteronline.de##[style="width: 192px;"]`, which matches the slider, and the filter is correctly reported in the logger.

I tried to understand what was happening, and I believe this was caused by the way the logging of cosmetic filters was working. The element targeted by the original filter was probably added _after_ the filter was injected, and after the detection of cosmetic filters used by the page was executed. Specific cosmetic filters are injected early during page load, meaning it was possible the cosmetic filter logging code was executed before a DOM modification triggering a match.

The cosmetic logger code was refactored when #2984 was fixed, and this quite probably fixed the case reported here, because now DOM changes will also trigger cosmetic filter detection when the logger is opened -- this was not the case before.

Thus, marking as fixed by <https://github.com/gorhill/uBlock/commit/6112a68faf46d89c58defdd9e14d4342747c9523#diff-fe57879eb27e2bdc0b78a77743617201>.

**Closed by gorhill** 2017-11-16 06:03 UTC
