### ISSUE TITLE
uBlock Origin High Memory Usage

### ISSUE THREAD

**Issue by n-o-o-b** [gorhill/uBlock#1680] opened 2016-06-01 23:01 UTC
### Describe the issue
I'm getting really high memory usage with uBlock Origin and Firefox. I'm surprised because uBlock Origin is supposed to have lower CPU and memory usage than Adblock Plus, which is what I was using before. However, with ABP I was getting roughly 400MB memory usage, whereas now I am getting roughly 900MB. I can't remember what my CPU usage was like with Adblock. The first picture was taken a few days ago, I had 12 tabs open. The second one is today, the tabs you see are the only ones I had open. Then I disabled restarted Firefox, and disabled uBlock Origin, to see what the memory usage would be like then. The final image is when I re-enabled uBlock.

### Screenshot in which the issue can be seen

1. 26/5/16, 12 tabs open

![printscreen 2](https://cloud.githubusercontent.com/assets/19697175/15727628/cb33042a-284f-11e6-9df6-92d8b070917a.png)

2. Today, 9 tabs open.

![ublock enabled](https://cloud.githubusercontent.com/assets/19697175/15727949/7654cbbc-2851-11e6-863c-a5e41683465f.png)

3. Today, after restarting Firefox with uBlock disabled

![ublock disabled after restart](https://cloud.githubusercontent.com/assets/19697175/15728286/7e15cd68-2853-11e6-969b-9b3206c06588.png)

4. Today, after restarting Firefox, uBlock re-enabled

![ublock enabled after restart](https://cloud.githubusercontent.com/assets/19697175/15728353/d5aff5e4-2853-11e6-8260-5ab40af3fa7e.png)

### Steps for anyone to reproduce the issue

I apologise in advance because I do not have a lot of technical knowledge. I do not know how one could reproduce this issue.
### Your settings
I am using uBlock with all default settings

- Browser/version: Firefox 46.0.1
- uBlock Origin version: 1.7.0

##### Your filter lists

Default filter lists

**Comment by CrisBRM** [comment] 2016-06-01 23:28
Try checking about:memory instead. I remember there being more than one entry to check in order to properly determine uBlock's memory footprint, but I'm certain gorhill knows anyway.

Looks quite normal though? At least in my opinion, the only relevant screenshots are the last 2, and the amplitude is a mere 30 megabytes. The reason for that is that, because you measured the memory footprint after a restart, you allowed GC to kick in, and those are the only screenshots which properly compare uBlock off vs on.

**Comment by gorhill** [comment] 2016-06-02 03:42
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2016-06-02 03:42 UTC

**Comment by n-o-o-b** [comment] 2016-06-02 12:49
I don't understand why this has been closed, but it doesn't matter now as I can't reproduce the issue. (It seems the developer is quick to close a lot of issues...) I think the issue was that I had a large amount of tabs open, and I was comparing to ABP with less tabs, this is most likely.

@CrisBRM How do I use about:memory? I don't have a lot of technical knowledge so I don't know what all the buttons mean (I can work out what the first four from the left mean, that's about it). Also, what does GC stand for? Is it 'garbage collection'? If so what does that mean?

**Comment by IDKwhattoputhere** [comment] 2016-06-02 12:57
I suppose it was closed because it's impossible to reproduce like this and there are millions of reasons which could be the cause for your results. Like you showed yourself:

> I had a large amount of tabs open, and I was comparing to ABP with less tabs

**Comment by n-o-o-b** [comment] 2016-06-02 13:40
@IDKwhattoputhere True, but that was only a guess. I was pretty sure that I was getting higher memory usage, otherwise I wouldn't have gone through the effort of creating this thread. However, now I'm satisfied that I'm not getting higher memory usage, so I've left it at that. The point about issues being closed was because having looked at the closed issues section, it seems like the developer is closing a lot of threads without responding, simply because they do not adhere to the strict guidelines (e.g. including urls), even if it is a legitimate issue.

**Comment by IDKwhattoputhere** [comment] 2016-06-02 14:34
> strict guidelines (e.g. including urls)

This is the issue right there. Is it really too much work to include some info? You don't have to be into coding (I'm not either) to do this. How do you expect something to get fixed if you don't even give the possibility to reproduce? It's not possible and such issues just waste time and don't help anyone. Besides: Most issues are not with uBO itself but with a filter list like EasyList or with the user not using the software properly (recently https://github.com/gorhill/uBlock/issues/1682, https://github.com/gorhill/uBlock/issues/1679). Another huge part of issues are support requests which don't belong here.
There are currently more than 100 open issues and there's only one person doing the vast majority of the work so they have to be strict or else they will end up with an issue page like [this](https://github.com/qbittorrent/qBittorrent/issues).

**Comment by n-o-o-b** [comment] 2016-06-02 14:52
What I should have said was "including urls even when it doesn't happen on a particular website". But you're right. I guess I could have included my most visited sites.

I suppose this is the best way to do it without having a ton of vague and pointless issues in the 'open' section.
