### ISSUE TITLE
"uBlock filters – Privacy‎" filter collides with disconnect on dict.cc

### ISSUE THREAD

**Issue by thinking-aloud** [gorhill/uBlock#1236] opened 2016-01-15 13:23 UTC
The Filter list "uBlock filters – Privacy" collides with the Disconnect Chrome Extension on the page https://www.dict.cc/ . The error is displayed by disconnect. Disabling the filter solves the error.
I do not know if the error occurs on more pages. 

error message:
Warning:
This extension failed to redirect a network request to about:blank because another extension (uBlock Origin) redirected it to data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0...[very long ID]...=.

Link to the issue at disconnect: https://github.com/disconnectme/disconnect/issues/356

**Comment by gorhill** [comment] 2016-01-15 13:28
Duplicate of #1170. See <https://github.com/gorhill/uBlock/issues/1170#issuecomment-168989068>.

**Closed by gorhill** 2016-01-15 13:28 UTC
Labels: duplicate

**Comment by SouthernBelle1** [comment] 2017-07-03 03:27
heyal, i may be wrong but, in each of these cases where the conflict arises, could it be because users are using multiple browsers at one time, they are open at the same time using  Chrome and Firefox, ok and Maxthon? 
Southern Belle
thanks just wondering!
