### ISSUE TITLE
bad hide after update 05.07

### ISSUE THREAD

**Issue by 230v** [gorhill/uBlock#445] opened 2015-07-05 13:07 UTC
Only hide banner image. Example 
![_2015-07-05_16-06-59](https://cloud.githubusercontent.com/assets/9416005/8511843/f356a680-232f-11e5-92bd-a2642b905968.png)

FF 39, uBlock 0.9.9.3

**Comment by gorhill** [comment] 2015-07-05 13:15
Unable to reproduce using uBlock 0.9.9.3 + default settings + RU AdList + Chromium (has inferred from the picture).

**Comment by gorhill** [comment] 2015-07-05 13:16
Marking as invalid until the lack of details provided is addressed.

**Comment by TeddStriker** [comment] 2015-07-05 13:31
@gorhill The original post mentioned he used firefox 39. That said, I cannot reproduce it as well, using a clean profile and default uBlock + RU Adlist (both old and updated) which rules out a list issues if I am not mistaken.

@230v Do you maybe have `Hide placeholders of blocked elements ` unchecked by mistake? You need to share any settings that differ from default, and possibly, any other extensions you have on your firefox.

**Comment by gorhill** [comment] 2015-07-12 16:25
Closing: unable to reproduce using provided details; provided screenshot does not match "FF 39"; no feedback for more than 7 days.

**Closed by gorhill** 2015-07-12 16:25 UTC
Labels: invalid, unable to reproduce
