### ISSUE TITLE
Complex URL - Uncaught Error: uBlock Origin: aborting content scripts

### ISSUE THREAD

**Issue by OzoneGrif** [gorhill/uBlock#2051] opened 2016-10-06 15:27 UTC
I disabled µBlock for localhost with the toolbar button. Then I also whitelisted localhost and 127.0.0.1.
Yet, µBlock still crashes and prevents the browser from loading this webservice URL. 
I had to disable the whole extension (in Chrome) to get my URL to work.

The URL looks like this :

`http://localhost:8080/stvapplication/call/6e61a31c540a916015af2b3b541e8930@12.151.69.121:5510/entities/54d319e55750b65401576c8858e9000f/audios/54d319e55750b65401576c8858e9000f`

And the error :

![image](https://cloud.githubusercontent.com/assets/10961896/19158501/4264b820-8be9-11e6-817e-8544624c66bb.png)

Just copy/paste the URL in your Chrome browser with µBlock.
It won't even try to load it and crash right away.

The wanted behavior :
Since it is supposed to be disabled and whitelisted, it shouldn't prevent the URL to load.

### Your settings

Chrome 53.0.2785.143
µBlock 1.9.10
The settings are all defaults except for the whitelist.

Default filter lists + FRA
No custom filters

**Comment by gorhill** [comment] 2016-10-06 16:28
Nothing is prevented from loading, that's not what the error message says.

Duplicate of #2029.

**Closed by gorhill** 2016-10-06 16:28 UTC
