### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by Connor37** [gorhill/uBlock#1622] opened 2016-05-10 12:08 UTC
Only two months from now to the official release of the extension feature for Edge. I don't know if you have any plans to provide support for this browser. Since, Microsoft already said that they will provide tools to convert extension from Chrome easily.

**Comment by harshanvn** [comment] 2016-05-10 12:13
Duplicate of #1486.

**Closed** 2016-05-10 12:19 UTC
