### ISSUE TITLE
[Feature] sanitizing blocked URL

### ISSUE THREAD

**Issue by keppi5** [gorhill/uBlock#3376] opened 2017-12-27 14:39 UTC
### Describe the issue

Since many sites add known GET parameters which track user it would be nice to go to sanitized version of that URL instead of showing blocked page.

### One or more specific URLs where the issue occurs

Happens, for example with JP list and any url with utm parameters

### Screenshot in which the issue can be seen

![examppel](https://user-images.githubusercontent.com/28823955/34384247-b1616076-eb23-11e7-8a40-ffb84f645147.PNG)

### Steps for anyone to reproduce the issue

1. Visit the URL

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- 64-bit Win 7 / Linux 
- Firefox
- uBlock Origin 1.13.8

##### Your filter lists

![examppellist](https://user-images.githubusercontent.com/28823955/34384352-507225d8-eb24-11e7-9e3f-851808c7f039.PNG)

**Comment by gorhill** [comment] 2017-12-27 18:20
Duplicate of #867: declined.

**Closed by gorhill** 2017-12-27 18:20 UTC
Labels: duplicate, invalid
