### ISSUE TITLE
ALT+L on macOs opens loggin tab, prevents to write the character @

### ISSUE THREAD

**Issue by morritza** [gorhill/uBlock#3529] opened 2018-02-20 16:50 UTC
### Describe the issue
When typing a "@"-char the log-tab opens

### One or more specific URLs where the issue occurs
On every page, except the url bar which could not be handled by the extension

### Steps for anyone to reproduce the issue

1. Activate uBlock
2. Push alt+l for at-Char

### Your settings
- OS: MacOS 10.12
- Chrome: 64.0.3282.140
- German keyboard layout
- uBlock Origin version: 1.15.2

**Comment by gorhill** [comment] 2018-02-20 17:10
Duplicate of #2723.

**Closed by gorhill** 2018-02-20 17:10 UTC
Labels: duplicate
