### ISSUE TITLE
Disabling JavaScript globally in IceCat breaks uBO Preferences interface

### ISSUE THREAD

**Issue by t33rex** [gorhill/uBlock#3712] opened 2018-04-13 17:18 UTC
### Describe the issue

Setting `javascript.enabled = false` in about:config in IceCat breaks uBO Preferences interface

### Screenshot in which the issue can be seen

![screenshot](https://user-images.githubusercontent.com/26042694/38748391-9402b1ce-3f56-11e8-87bf-6573d2ab4cc2.png)

### Steps for anyone to reproduce the issue

1. Download IceCat from https://ftp.gnu.org/gnu/gnuzilla/52.6.0/
2. Start with an empty profile and use https://github.com/pyllyukko/user.js
3. Install uBO
4. Set `javascript.enabled = false` in about:config
5. Restart
6. Open Add-ons -> uBO -> Preferences

### Your settings

- OS/version: openSUSE Leap 42.3
- Browser/version: IceCat 52.6 x64
- uBlock Origin version: 1.15.24

##### Your filter lists

All 3rd-party lists except the ones which are duplicated in uMatrix:

Malware Domain List​​​​​​​​​
Malware domains​
​​​​​​​​Dan Pollock’s hosts file​
​​​​​​​​hpHosts’ Ad and tracking servers​
MVPS HOSTS​​​​​​
Peter Lowe’s Ad and tracking server list​
​​​​​​​​
##### Additional info

Disabling JS globally in Firefox and Chromium doesn't break the preferences UI.

**Comment by gorhill** [comment] 2018-04-13 18:09
I would like to understand the reason for not searching issues first.

<https://github.com/gorhill/uBlock/issues?q=is%3Aissue+javascript.enabled+is%3Aclosed>

See [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Comment by t33rex** [comment] 2018-04-13 18:56
I have searched but none of the older issues mention IceCat specifically and the fact that it behaves differently from latest stable Firefox.

Also it looked strange because in IceCat I also have uMatrix installed (unfortunately only 1.0.0 can be installed there) and it doesn't break when JS is globally disabled. So I thought it is something which you may probably look at.

**Comment by gorhill** [comment] 2018-04-16 10:42
Duplicate of #3083.

**Closed by gorhill** 2018-04-16 10:42 UTC
Labels: duplicate
