### ISSUE TITLE
Global uBlock extension execution enable/disable toggle switch

### ISSUE THREAD

**Issue by CollinChaffin** [gorhill/uBlock#2391] opened 2017-02-19 16:28 UTC
I searched and did not find any open enhancement request and have been a uBlock user for years and use the site-specific toggle (and temporary Ctrl-click toggle) all the time and love the (sometimes necessary) ability to override per site. <img alt="ghe-emoji" title=":_happy_clap:" src="https://cloud.githubusercontent.com/assets/136959/13559405/7991f398-e3d9-11e5-9794-325ace005cad.gif">    However, there are times that for whatever reason a website element is not working properly etc. and because of uBlock's power, inevitably the user must be able to temporarily disable all uBlock extension execution globally with the full intent of re-enabling a short time later :worried:.    I am aware of no such "global disable toggle" and would like to request it as other extensions commonly have this functionality (think grease/tampermonkey etc.) as a perfect example of a global disable switch. <img alt="ghe-emoji" title=":_golf_clap:" src="https://cloud.githubusercontent.com/assets/136959/13512573/13c07d34-e161-11e5-9223-5de7f68b69b8.gif">  

Currently the user must navigate the multiple levels into Chrome's settings to disable this extension and then repeat the process  again (usually minutes later) to re-enable the extension<img alt="ghe-emoji" title=":_cry:" src="https://cloud.githubusercontent.com/assets/136959/13512303/638c0a7e-e15f-11e5-83ab-bb898da7d97d.gif">.    This request is for a global enable/disable switch, either on the drop-down menu from the Chrome extension button and/or on the uBlock unfold operation window where all other site-specific functions are currently located, perhaps a red/green slider/toggle etc. <img alt="ghe-emoji" title=":_idea:" src="https://cloud.githubusercontent.com/assets/136959/13512480/891c5f86-e160-11e5-97f6-5bc7071ac364.gif">

**Comment by toshiya44** [comment] 2017-02-19 18:27
there's a  disable button in firefox
![image](https://cloud.githubusercontent.com/assets/20046789/23105059/1528fae6-f6a7-11e6-89d3-ccfd984ae642.png)

**Comment by gorhill** [comment] 2017-02-19 18:48
Duplicate of #167.

**Comment by CollinChaffin** [comment] 2017-02-19 19:44
Yes, that button in chrome is several clicks in which I thought I made obvious in my request so I apologize for not being clearer.  Every other plugin has a quick way to disable it would be nice if this did as well.

You should really listen to your users you just pointed me at an issue you quickly closed YEARS ago one of many requests for this exact enhancement.  Surely a slider to enable/disable cannot be so unheard of and to say the 3 clicks, then scroll through a huge list of extensions to find uBlock, to take the fourth click shown above......to then perform the same 1-2 MINUTE routine just minutes later is somehow convenient, and what every other extension developer expects of their users.  If this were the case, why would the majority of page-action based extensions have exactly what this request consists of to enable/disable their perspective plugins/extensions?

All I'm asking is perhaps leave it open and acknowledge that the current process to disable/re-enable relying on the current Chrome default extension menuing system, leaves much room for convenience improvement for uBlock users.

**Comment by toshiya44** [comment] 2017-02-19 20:07
I'm sorry if it takes you 1-2 minute to click two buttons.

**Comment by gorhill** [comment] 2017-02-19 20:41
> then scroll through a huge list of extensions ... 1-2 MINUTE routine

Right-clicking "Manage extensions" brings you directly to the extension, no need to scroll.

These exaggerations are accomplishing the opposite of convincing me this is a needed feature -- they are rather confirming that it's not really needed by the vast majority of users if the handful trying to argue for it have this urge to use wildly exaggerated arguments.

**Comment by uBlock-user** [comment] 2017-02-19 21:41
What you propose would take 2 clicks atleast vs, the 3 clicks proposed solution, 1 additional click is not gonna save you anything. Or better yet, the websites you deem worthy of not running uBO should be added to whitelist, which is to be done once only, that will save you the enable/disable drama.

If you're into enabling and disabling uBO when random websites poke you to surrender for any reason, then this will not workout for you as that behaviour specifically works well for ABP users, so you should use ABP rather.

**Comment by neroux** [comment] 2017-02-19 23:31
> These exaggerations are accomplishing the opposite of convincing me this is a needed feature -- they are rather confirming that it's not really needed by the vast majority of users if the handful trying to argue for it have this urge to use wildly exaggerated arguments.

You appear to have a strong opinion on this subject. May I ask what the reason would be?

**Comment by nick75e** [comment] 2017-02-20 01:27
Hi!

If I may chime in, the current method works but is very inconvenient.
Where I live (France), when you order something online, the site will redirect you to a bank to verify that you're the owner of the debit card you used.
So even if you whitelisted the website where you checked out, you can't whitelist the bank's website because you don't know it beforehand then you have to check out again. And the second time, the URL may not be the same!

Like @CollinChaffin I think this would be a pro-user feature.

**Closed** 2017-02-20 04:32 UTC
