### ISSUE TITLE
It is strongly recommended to add two highly efficient and practical and convenient features!

### ISSUE THREAD

**Issue by dnknn** [gorhill/uBlock#1307] opened 2016-01-27 21:31 UTC
# 

Because here not upload screenshots, so please click on the link to view feature page.

Original link:
http://note.youdao.com/share/?id=db4b4e8043caf47ceb1c5ff3ab863754&type=note

url shorter:
[edit: removed shortened URLs, unnecessary here, there is no space constraints --gorhill]

It is strongly recommended to add two highly efficient and practical and convenient features!

Do not know English, so translation can only be replaced with Google, 
( https://translate.google.com )
you do not know can specifically understand?

It is strongly recommended to add two highly efficient and practical and convenient features! 
I do not know can be achieved? ? ?

I liked uBlock this browser plugin, 
but there are two fatal deficiencies, wonder if we can develop it?

First, Block element does not support shortcuts, very inconvenient, 
click the mouse to choose would be more tired.
It is strongly recommended to add custom support shortcut keys.

You can refer to this plug-in :
AdBlock+ Element Hiding Helper V1.3.4.CRX
https://chrome.google.com/webstore/detail/adblock%2B%E9%A1%B5%E9%9D%A2%E5%85%83%E7%B4%A0%E9%9A%90%E8%97%8F%E5%8A%A9%E6%89%8B/ahieappfkblneagblagpodhjmnhcbfdn

You can also refer to this plug-in :
LastPass
https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd

Second, the possibility of increasing the functionality of the last Block elemen Undo button menu?
1, adding an Undo Last Block elemen buttons.
2. When you click the Enter element picker mode button, 
they can choose to cancel wherein the shield element.

Third, in short, is to increase support for keyboard shortcuts, easy to operate quickly and efficiently, and thus do not have to manually mouse or right to a choice.
Then, add a convenient undo, so do not go to My filters to delete.

由于这里无法上传截图，所以我请点击链接查看专题页面。

不懂得英语，所以只能用谷歌翻译来替代了，不知能具体理解吗？
强烈建议增加两个高效实用的便捷功能！不知可以实现吗？？？

非常喜欢uBlock这个浏览器插件，但是有两处致命的不足，不知可不可以开发出来？

第一，Block element没有快捷键的支持，非常不方便，鼠标选择点击会比较累。
所以强烈建议增加快捷键的自定义支持。

可以参考这个插件，
AdBlock+ Element Hiding Helper V1.3.4.CRX
https://chrome.google.com/webstore/detail/adblock%2B%E9%A1%B5%E9%9D%A2%E5%85%83%E7%B4%A0%E9%9A%90%E8%97%8F%E5%8A%A9%E6%89%8B/ahieappfkblneagblagpodhjmnhcbfdn

也可以参考这个插件LastPass
https://chrome.google.com/webstore/detail/lastpass-free-password-ma/hdokiejnpimakedhajhdlcegeplioahd

第二，可否增加最近一次Block elemen的撤销按钮菜单的功能？
1，增加一个撤销最近一次Block elemen的按钮。
2，当点击了 Enter element picker mode的按钮时候，可以选择取消其中屏蔽元素。

第三，总之就是增加键盘快捷键的支持，方便迅速高效操作，从而不用手动的鼠标或者右键去一个个选择。
然后，再增加便捷的撤销操作，从而不用跑到My filters去删除。

**Comment by anewuser** [comment] 2016-01-27 22:03
This project generally does not accept feature requests. It is also very hard to understand automatically translated Chinese. 

Please try to read this: [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md). If you can't read the rules, contact @YFdyh000 or another bilingual Chinese contributor privately.

>adding an Undo Last Block elemen buttons.

Duplicate: #515 

>When you click the Enter element picker mode button, they can choose to cancel wherein the shield element.

I'm not sure what you mean, but you can close the element picker mode with the <kbd>ESC</kbd> key.

>increase support for keyboard shortcuts,

It takes a lot of time to add new features, and the programmer works on it as a hobby.  Please do not post feature requests. The programmer is very experienced and can think of things like that by himself. If this was a "fatal deficiency" in his opinion, he would have added keyboard shortcuts already, or it is already in his plans.

**Comment by dnknn** [comment] 2016-01-28 19:35
I certainly know how to drag and drop to upload, but it does not upload successfully, suggesting that failure, may be the reason the network proxy it.
In addition, those links are very safe formal, without any suspicious, the links are from China, NetEase's a Notes application products.
我当然懂得拖拽上传，但是确实无法上传成功，提示失败，可能是网络代理的原因吧。
另外，那些链接都是非常安全正规的，没有任何的可疑，那个链接是来自中国的网易公司的一个笔记应用产品。

**Comment by gorhill** [comment] 2016-01-28 20:16
> Block element does not support shortcuts, very inconvenient

Originally requested in <https://github.com/chrisaljoudi/uBlock/issues/256>, but request was never reopened here.

> adding an Undo Last Block elemen buttons.

Duplicate of #515.

**Comment by dnknn** [comment] 2016-01-28 20:36
@gorhill Excuse me: 
1, can develop Block element of keyboard shortcuts? 
2, can be developed to cancel the last Block element shortcuts or right-click menu? 
请问：
1，可以开发出Block element的键盘快捷键吗？
2，可以开发出撤销最近一次Block element的快捷键或者右键菜单吗？

**Comment by Hrxn** [comment] 2016-01-31 06:30
You can set up keyboard shortcuts in your extensions page, like this:

http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121

At least that's what I am interpreting in your question..

**Comment by foss-** [comment] 2016-03-22 13:36
This report is fairly chaotic. And as of the sane bug rule one issue per bug, it might be good to file 2 separate bugs for what the report is requesting.

+1 for a keyboard shortcut to trigger the element-picker.

**Comment by gorhill** [comment] 2017-03-22 13:09
Duplicate of #113.

**Closed by gorhill** 2017-03-22 13:09 UTC
