### ISSUE TITLE
Separate Window Request log triggers Session Manager when closing in Firefox

### ISSUE THREAD

**Issue by Ketrel** [gorhill/uBlock#464] opened 2015-07-09 05:39 UTC
If you use the session manager addon in Firefox and have it set to prompt you to save sessions when you close the last open window, and you open the request log in a separate window with shift, when you close that window, it triggers the prompt from session manager as if it was the last open window.

(It does not actually close Firefox)

**Comment by CrisBRM** [comment] 2015-07-09 05:57
Duplicate of https://github.com/gorhill/uBlock/issues/429 caused by https://bugzilla.mozilla.org/show_bug.cgi?id=644224

**Comment by gorhill** [comment] 2015-07-09 12:36
Closing as duplicate of #429.

**Closed by gorhill** 2015-07-09 12:36 UTC
