### ISSUE TITLE
Firefox Stylish

### ISSUE THREAD

**Issue by bandaid** [gorhill/uBlock#2390] opened 2017-02-19 13:02 UTC
uBlock Origin seems to have trouble with it's translucent overlay when editing a page with element picker.

I use Stylish for Firefox to change the color scheme of the about:blank page from bright to dark. 
```
@-moz-document url-prefix(about:blank) {
  *{background-color:#000000 !important;}
}
```

![2017-02-19 06_51_45-cern _ accelerating science](https://cloud.githubusercontent.com/assets/8212255/23102580/4b03b24a-f671-11e6-8d46-6e72a8e070cd.png)
![2017-02-19 06_52_08-cern _ accelerating science](https://cloud.githubusercontent.com/assets/8212255/23102584/4dc16248-f671-11e6-8edd-5d4a749af0c3.png)

If changing to {background-color:#000000 !important;} asterisks removed, the about:blank page stays white and uBlock Origin element picker works normal. Though, I would prefer that about:blank stay dark.

Changing *{background-color:#000000 !important;} to body{background-color:#000000 !important;} also conflicts with uBlock Origin element picker. I'm sure this issue reports the same with other browsers utilizing Stylish.

**Comment by Halibut80** [comment] 2017-02-19 14:29
Use ```body:empty``` as selector.

**Comment by gorhill** [comment] 2017-02-19 14:48
Duplicate of #826.

**Closed by gorhill** 2017-02-19 14:48 UTC

**Comment by bandaid** [comment] 2017-02-19 15:38
Thanks.
