### ISSUE TITLE
Empty buttons (no labels) in about:addons

### ISSUE THREAD

**Issue by Korodny** [gorhill/uBlock#481] opened 2015-07-11 14:04 UTC
Using the German translation of uBlock 0.9.1.0.1, I get empty/unlabeled buttons in about:addons. They do work (one takes me to the dashboard, the other one to chrome://ublock/content/devtools.html), though I would expect the former to be round and feature a cog graphic.

![ublock2](https://cloud.githubusercontent.com/assets/2822120/8633987/0782ae1e-27e6-11e5-9d5e-0e4728f9a00d.png)

**Comment by alejandrolemus** [comment] 2015-07-11 14:11
You reported to the wrong repository, your addon is [uBlock](https://github.com/chrisaljoudi/uBlock) , not uBlock Origin (this one). Look at the URL in your screenshot.

**Comment by gorhill** [comment] 2015-07-11 14:18
Duplicate of #128.

**Closed by gorhill** 2015-07-11 14:18 UTC

**Comment by gorhill** [comment] 2015-07-11 14:23
> not sure why it still says https://github.com/gorhill in homepage

He is using a very old version, which does not have [this fix](https://github.com/chrisaljoudi/uBlock/commit/237af0dd42701b86ef50eccddc1c2403aa0be8d6).
