### ISSUE TITLE
uBO 1.14.18 Strange bug with cosmetic filters on dropmefiles.com

### ISSUE THREAD

**Issue by TheFinalCut83** [gorhill/uBlock#3240] opened 2017-11-17 11:22 UTC
### Describe the issue
Seems like uBO 1.14.18 onwards cannot handle properly with some filters. When I opened specified link, I saw dropmefiles like on a 1st screenshot - download link was hidden. I installed uBO 1.14.16 and the link began to look like the second screenshot - absolutely normal. Filters and browser are exactly the same, I just changed uBO version. With Adguard addon and same filters all is ok. 
There is a way to display this page correctly with 1.14.18 - to add 2 exceptions:
dropmefiles.com#@#.bnr 
dropmefiles.com#@#noindex .download_btn
But they don't need with 1.14.16, so that's not a filter issue, am I right?

### One or more specific URLs where the issue occurs

http://dropmefiles.com/G2pJj

### Screenshot in which the issue can be seen
1 - https://i.imgur.com/GuNY8mc.jpg
2 - https://i.imgur.com/ZTlTVjJ.jpg

### Steps for anyone to reproduce the issue

1. Go to dropmefiles.com/G2pJj with uBO 1.14.18 or 1.14.19 betas and specific filters
1. See page as on screenshot 1
1. Go to dropmefiles.com/G2pJj with uBO 1.14.16
1. See page as on screenshot 2

### Your settings

- OS/version: Win 7 x64
- Browser/version: Firefox 56.0.2, 57
- uBlock Origin version: 1.14.18, 1.14.19 betas

##### Your filter lists

uBO filter lists except Experimental
+
Adblock Warning Removal List
EasyList
Adguard Spyware Filters
EasyPrivacy‎
Malvertising filter list by Disconnect‎
Malware domains‎
Peter Lowe’s Ad and tracking server list
RUS: Adguard Russian Filter
RUS: RU AdList
RU AdList: BitBlock​

**Comment by gorhill** [comment] 2017-11-17 12:11
Looks like a filter issue to me.

There is this filter in [_RUS: Adguard Russian Filter_](https://filters.adtidy.org/extension/chromium/filters/1.txt): `~i9k.ru##.bnr ` which means:

"hide elements with class `bnr` everywhere except on pages from `i9k.ru`"

For some reasons Adguard is not enforcing that filter on `dropmefiles.com` (paging @ameshkov).

**Comment by gorhill** [comment] 2017-11-17 12:15
I will be investigating why the filter is not applied with 1.14.16.

**Comment by gorhill** [comment] 2017-11-17 12:27
Ok it's actually an issue in 1.14.16, uBO should have hidden that element but it was not. If you had reported the issue with 1.14.16, I would have marked it as duplicate of #1885. It's an issue where timing is key, and somehow with 1.14.18 the timing is that the issue does not manifest itself, making the false positive now standout -- so this confirms a filter issue.

**Comment by ameshkov** [comment] 2017-11-17 12:34
> For some reasons Adguard is not enforcing that filter on dropmefiles.com (paging @ameshkov).

Thx for mentioning me!

This one is resolved in the English filter: 
```
dropmefiles.com#@#.bnr
dropmefiles.com#@#noindex .download_btn
```

**Comment by gorhill** [comment] 2017-11-17 12:46
> This one is resolved in the English filter

Shouldn't the exception be added to Adguard Russian given this is where the almost generic `~i9k.ru##.bnr` is defined? (I couldn't find any generic `##.bnr` in Adguard English.)

**Comment by gorhill** [comment] 2017-11-17 12:49
@TheFinalCut83 

So I guess you should just enabled _Adguard Base Filters_, that will fix the filter issue.

**Closed by gorhill** 2017-11-17 12:49 UTC
Labels: filter issue

**Comment by ameshkov** [comment] 2017-11-17 14:34
> Shouldn't the exception be added to Adguard Russian given this is where the almost generic ~i9k.ru##.bnr is defined? (I couldn't find any generic ##.bnr in Adguard English.)

Yeah, you're right: https://github.com/AdguardTeam/AdguardFilters/commit/cdeac3a82d491ed1312d22421ad8c176994cc38c
