### ISSUE TITLE
Rules getting deleted

### ISSUE THREAD

**Issue by IDKwhattoputhere** [gorhill/uBlock#1162] opened 2016-01-02 18:33 UTC
Whenever I try to modify one of my rules it just gets deleted by uBO.
https://u.pomf.is/eynnbk.mp4
I can't tell if I'm doing something wrong or if this is a bug.

**Comment by gorhill** [comment] 2016-01-02 18:38
Duplicate of #1039. Please search the issues/doc next time.

**Closed by gorhill** 2016-01-02 18:38 UTC
