### ISSUE TITLE
Tabs That Open With Firefox Nightly Launch Don't Have Filtering

### ISSUE THREAD

**Issue by Jgr9** [gorhill/uBlock#3426] opened 2018-01-11 00:23 UTC
### Describe the issue
This has been since the recent of transition of Firefox/Nightly, but I'm currently on 59.  Tabs that load when launching Firefox/Nightly (sessionstore?) don't get filtering, even with cache being cleared.  Actually, uBlock doesn't seem to work at all until everything fully loads, I guess.  Is it possible for this to ever be fixed after Firefox made its big changes to add-ons/Extensions?

### One or more specific URLs where the issue occurs
Any website.

### Steps for anyone to reproduce the issue

1. Have pages load on Firefox/Nightly launch, or have browser.showQuitWarning set to true.
Not sure if there's another part of this I'm missing.
2. Close Firefox/Nightly with multiple tabs loaded that have filters applied to them and choose to save the tabs for the next time it starts.  
3. Open Firefox/Nightly again.  Filters will not be applied to the immediately loaded tabs, and will only work again with a refresh after Firefox/Nightly is fully loaded.

### Your settings
browser.showQuitWarning;true
Not sure if there's something else.  But I have my cache set to clear when Firefox/Nightly is closed.

- OS/version: Windows 10
- Browser/version: Firefox Nightly 59
- uBlock Origin version: 1.14.23b17

##### Your filter lists
Occurs with all filters.

**Comment by gorhill** [comment] 2018-01-11 00:30
Duplicate of #1327.

https://bugzilla.mozilla.org/show_bug.cgi?id=1378459

**Closed by gorhill** 2018-01-11 00:30 UTC
Labels: browser bug, duplicate
