### ISSUE TITLE
ublock doesn't hide an advert banner on music.yandex.ru

### ISSUE THREAD

**Issue by egoroof** [gorhill/uBlock#1704] opened 2016-06-10 08:07 UTC
### Describe the issue

Recently I've seen that ublock doesn't hide advert on https://music.yandex.ru/. Then I've add the banner manually and its't gone. But when I refresh the page I see the same advert banner again (with the same blocking rule). Maybe it's some kind of protection?

### One or more specific URLs where the issue occurs

https://music.yandex.ru/

### Screenshot in which the issue can be seen

![2](https://cloud.githubusercontent.com/assets/2605831/15957566/849ffc6e-2f22-11e6-968c-234608a2f308.png)

![1](https://cloud.githubusercontent.com/assets/2605831/15957570/89356912-2f22-11e6-8f89-5b09e705204c.png)

### Steps for anyone to reproduce the issue

1. go to https://music.yandex.ru/
2. you will see an advert banner on the right part of page (like in the screenshot)
3. add it to custom filter
4. refresh the page
5. you'll see the advert banner again

### Your settings

![3](https://cloud.githubusercontent.com/assets/2605831/15957828/3d332944-2f24-11e6-8131-21448aafaa9e.png)

- Browser/version: Google Chrome 51.0.2704.84 m (64-bit)
- uBlock Origin version: 1.7.2
- OS: Windows 10 x64

##### Your filter lists

Default filter lists + all RUS

##### Your custom filters (if any)

```
music.yandex.ru##.page-root > .centerblock-wrapper > .sidebar__placeholder > .sidebar > .sidebar__under > .smalladv_side.smalladv
```

**Comment by mapx-** [comment] 2016-06-10 09:16
You could use
music.yandex.ru##.page-root > .centerblock-wrapper > .sidebar__placeholder > .sidebar > .sidebar__under

or

music.yandex.ru##.sidebar__under

**Comment by egoroof** [comment] 2016-06-10 10:02
@mapx- thanks, it works

**Comment by IDKwhattoputhere** [comment] 2016-06-10 10:46
Best to report it here so it can be fixed: https://forums.lanik.us/viewforum.php?f=102

**Comment by IDKwhattoputhere** [comment] 2016-06-10 11:00
Best to report it here so it can be fixed: https://forums.lanik.us/viewtopic.php?f=102&t=24051
This is the place for filter list issues btw: https://github.com/uBlockOrigin/uAssets

**Comment by IDKwhattoputhere** [comment] 2016-06-10 11:03
Best to report it here so it can be fixed: https://forums.lanik.us/viewtopic.php?f=102&t=24051
This is the place for filter list issues btw in case you didn't see it in [CONTRIBUTING.md](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md): https://github.com/uBlockOrigin/uAssets

**Comment by gorhill** [comment] 2016-06-10 12:12
Duplicate of #963.

**Comment by gorhill** [comment] 2016-06-10 12:31
> This is the place for filter list issues btw in case you didn't see

However here the author correctly made the case that there is an issue with uBO, i.e. a perfectly valid filter is not resulting in the matching DOM element being hidden.

**Comment by gorhill** [comment] 2016-06-10 12:41
Although the same class of issues as the one raised in #963, the site here does it differently: it blanks the content of uBO's injected style tags. Whereas some sites try to remove uBO's style tags themselves (there is a fixed issue somewhere about this), in the current case the style tags are left in the DOM, but their text nodes are removed, resulting in all uBO's style tags being removed.

This can be worked around for Chromium-based browsers<sup>[1]</sup> when a cosmetic filter immediately matches DOM elements at page load time.

Need to think of how best to fix this.

***

[1] This will also work for Firefox is `dom.webcomponents.enabled` is set to true in `about:config`.

**Comment by gorhill** [comment] 2016-06-28 01:35
Could you test with the latest 1.7.7b0 version and see if the issue still exist?

**Comment by gorhill** [comment] 2016-07-28 14:19
Closing, as I can't reproduce with 1.7.7.

**Closed by gorhill** 2016-07-28 14:19 UTC

**Comment by egoroof** [comment] 2016-11-26 05:19
Thanks a lot!
