### ISSUE TITLE
Firefox 55.0.2: uBlock button gone and not blocking ads anymore

### ISSUE THREAD

**Issue by tomuta** [gorhill/uBlock#2937] opened 2017-08-30 18:23 UTC
### Describe the issue
Since upgrading to Firefox 55.0.2 (Ubuntu 17.04), the uBlock plugin is still installed but appears to not be working.  I see ads everywhere and the uBlock button isn't where it used to be.  But the addon is still installed and not disabled.

- OS/version: Ubuntu 17.04
- Browser/version: Firefox 55.0.2
- uBlock Origin version: uBlock Origin/webext-hybrid 1.13.10 (last updated Aug 29, 2017)

##### Your filter lists

Don't remember, can't check it because the uBlock button is gone.

**Comment by ebnerbenoit** [comment] 2017-08-30 18:29
Same things here.

**Comment by gorhill** [comment] 2017-08-30 18:34
Duplicate of #2909.

**Closed by gorhill** 2017-08-30 18:34 UTC
Labels: duplicate
