### ISSUE TITLE
[strict blocking] Consider parsing the URL from the tracking URL's get / post parameters

### ISSUE THREAD

**Issue by tobbi** [gorhill/uBlock#752] opened 2015-09-27 10:05 UTC
Some (if not most) trackers contain the target URL in its GET or POST request parameters. It would be good if uBlock could try to parse any URLs from those trackers and offer direct links on the page.

**Comment by Snapy** [comment] 2015-09-27 12:14
Available in [1.1.1](/gorhill/uBlock/tree/1.1.1) (issues #691 and #712).

**Comment by tobbi** [comment] 2015-09-27 12:18
Yes, of course. Closing.

**Comment by gorhill** [comment] 2015-09-27 12:19
Currently the payload of `POST` requests is not parsed. I have to think about this.

**Comment by gorhill** [comment] 2019-07-25 12:26
Closing this, because I do not have an actual case which I can reproduce for `POST`.

**Closed by gorhill** 2019-07-25 12:26 UTC
