### ISSUE TITLE
[Feature Request] Use uBlock in different language

### ISSUE THREAD

**Issue by RedDragonx** [gorhill/uBlock#1640] opened 2016-05-17 05:47 UTC
I'd like to use English as a default language instead of my native language, but uBlock has no option to do that, it only change to English if I change my browser language to English. This is very inconvenient.

**Comment by gorhill** [comment] 2016-05-17 13:34
Duplicate of #1319.

**Closed by gorhill** 2016-05-17 13:34 UTC

**Comment by RedDragonx** [comment] 2016-05-17 15:10
But the Vietnamese translation has some very poor line and I'll understand uBlock better if it's in English.

**Comment by gorhill** [comment] 2016-05-17 16:36
You can contribute to improve the Vietnamese translation: <https://crowdin.com/project/ublock/vi#>.

**Comment by RedDragonx** [comment] 2016-05-18 13:49
So unless I change my browser language to English, there's no way I can use uBlock in English?

**Comment by gorhill** [comment] 2016-05-18 14:13
@RedDragonx That is correct.
