### ISSUE TITLE
uBLock Origin interferes with Firefox back button behavior

### ISSUE THREAD

**Issue by wenqingj** [gorhill/uBlock#3211] opened 2017-11-09 16:46 UTC
Filter issues **MUST NOT** be reported here. Read first: <https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md>

### Describe the issue
In the latest Firefox browser beta (version 57), install the latest uBlock Origin (web extension),
then browse www.marketwatch.com, click a link in the front page to read the article, then click the back button, and the page remains (won't go back), click the back button again, the browser goes back to home page.

Now disable the uBlock Origin plugin, then do the same, and the page will go back at the first click of the back button.

### One or more specific URLs where the issue occurs
quite many links within the page of www.marketwatch.com

[URL(s) for issue on a specific site are **mandatory**]

### Screenshot in which the issue can be seen

[Screenshot(s) for visual issues are **mandatory**]

### Steps for anyone to reproduce the issue

1. Be as detailed as possible:
1. Because we are not looking over your shoulder and
1. Keep in mind: Nobody can read your mind.

### Your settings

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: WIndows 10 prof
- Browser/version: Firefox 57 (latest beta)
- uBlock Origin version: 1.14.14 or 1.14.18

##### Your filter lists

[Example: "Default filter lists + FRA", or "Default filter lists minus uBlock -- Badware risks"]

**Comment by gorhill** [comment] 2017-11-09 16:51
Unable to reproduce, neither on FF56 or FF58.

**Comment by wenqingj** [comment] 2017-11-09 16:56
FF56 is good.  Some earlier versions did not work -
https://bugzilla.mozilla.org/show_bug.cgi?id=1022643

Currently I only know of FF57 not working and thought it was FF problem -
https://bugzilla.mozilla.org/show_bug.cgi?id=1410480
but FF team pointed out that it works once uBlock Origin was taken out.

**Comment by gorhill** [comment] 2017-11-09 17:19
Can you reproduce the issue if ...

- Disable uBO for `www.marketwatch.com`?
- Un-check all filter lists and disable advanced user mode?
- With another blocker similarly configured such as [AdGuard](https://addons.mozilla.org/en-US/firefox/addon/adguard-adblocker/)? [Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/)?

**Comment by wenqingj** [comment] 2017-11-09 17:52
With FF57 and uBO the issue can be reproduced (in Win10pro).  Disable uBO (without restarting FF) and the issue go away.  So far this is just www.marketwatch.com.  I've not noticed that other web sites I visited have the same issue.
I'm not sure how to uncheck filter lists or advanced user mode.  Let me try that out and report back later.  I'll try out Adblock Plus too.

**Comment by wenqingj** [comment] 2017-11-09 18:01
Something interesting found -
I disabled the filters in the "3rd-party filters" tab one by one, and found that if "EasyList" is disabled (unchecked), the issue goes away.  Please advise if that's good enough or you'd like me to try advanced user or Adblock Plus.  Thanks.

**Comment by gorhill** [comment] 2017-11-09 18:03
When you say _"Disable uBO (without restarting FF) and the issue go away"_, do you mean disabled through the large blue button in the popup panel?

**Comment by gorhill** [comment] 2017-11-09 18:04
Is your EasyList up to date?

ABP also uses EasyList, so that would help if you can see whether ABP also causes the issue.

**Comment by wenqingj** [comment] 2017-11-09 18:05
No, it's uncheck the EasyList and apply the change.  uBO is kept running (large blue button remains blue).  All other filters' check/unckeck status are kept as is.  The uBO is up-to-date (1.14.18).

**Comment by wenqingj** [comment] 2017-11-09 18:09
I clicked "update now" button and noticed that the EasyList got updated (among others).  But the subsequent tests showed the same result - issue remains if EasyList is checked, and issue was gone if EasyList is unchecked.

**Comment by wenqingj** [comment] 2017-11-09 18:13
Just removed uBO and installed ABP, restart FF37, and could not reproduce the issue (checked EasyList is active in ABP, and updated "minutes ago").  Quite puzzling ...

**Comment by wenqingj** [comment] 2017-11-09 18:15
Sorry I mean restart FF57 in the previous comment (not FF37).
I'm not sure if you can reproduce at your end?  Search for Firefox beta and you should be able to find FF57 (current version is 56).

**Comment by wenqingj** [comment] 2017-11-09 18:23
If you're not able to reproduce it on FF57, then it's probably something peculiar in my laptop.  In that case please close the ticket.  I'll just disable the EasyList to avoid the issue.  Thanks.

**Comment by okiehsch** [comment] 2017-11-09 18:24
I can reproduce with Firefox 57.

**Comment by wenqingj** [comment] 2017-11-09 18:35
Thanks for confirming.
Another finding - as I had reported, when EasyList is unchecked the issue goes away.  But if I check "Prevent WebRTC from leaking local IP address" (and keeps EasyList unckecked), the issue comes back.

**Comment by gorhill** [comment] 2017-11-09 18:40
I'm downloading FF57 from Firefox ftp server. I will investigate.

**Comment by Remu-rin** [comment] 2017-11-09 18:44
I can reproduce with the latest Nightly. And without EasyList.
First click on the back button isn't working, second click is ok.

> Disable uBO for www.marketwatch.com?

Can't reproduce.

> Un-check all filter lists and disable advanced user mode?

Can't too.

**Comment by okiehsch** [comment] 2017-11-09 18:48
Disabling EasyList makes no difference on my end, I still have to click twice before the back button works.

**Comment by wenqingj** [comment] 2017-11-09 18:50
Sorry, I mean FF57 (not FF37).  :-(

**Comment by gorhill** [comment] 2017-11-09 19:00
Looks to me this is a filter issue, influence how the page behave. There last two items in the history stack are the same URL, so this gives the impression that the back button does not work, but it does work, it's just cause the page to navigate to the same URL.

**Comment by wenqingj** [comment] 2017-11-09 19:24
Tested Google Chrome and it does not have the issue.  Chrome version 62, uBO v1.14.16.

**Comment by gorhill** [comment] 2017-11-09 19:27
I get the same result with Adblock Plus + EasyList minus Acceptable ads, or Adguard. Sometimes I can't reproduce with uBO. This is a filter issue, the site behaves this way because of some filtering which I have yet to identify. Closing as filter issue, this will have to be resolved as such by EasyList maintainers or as an issue at uAssets.

**Closed by gorhill** 2017-11-09 19:27 UTC
Labels: filter issue, invalid

**Comment by gorhill** [comment] 2017-11-09 19:30
Not sure but blocking `livefyre.com` seems to help. Bottomline is that there is something in there messing up with the browser history.

**Comment by okiehsch** [comment] 2017-11-09 19:41
I can't reliably reproduce which filterlist and which filter is causing the issue with uBO, so finding a filter solution will be tricky, but it obviously is a filter issue.

**Comment by wenqingj** [comment] 2017-11-09 20:13
Thanks for all the efforts!
