### ISSUE TITLE
Breaks on some pages of paypal.com

### ISSUE THREAD

**Issue by kiernangs** [gorhill/uBlock#423] opened 2015-06-30 16:15 UTC
Paypal.com homepage fails to load - as well as their new shipping system.

**Comment by SW1FT** [comment] 2015-06-30 16:32
Not happening to me. Please explain which errors occur, what's your uBlock Origin version, OS, Browser and filters.

**Comment by CrisBRM** [comment] 2015-06-30 17:32
Can't replicate it either -- I mean, don't get me wrong, their servers _are_ rubbish and did take a WHILE to load, but they did load in the end.

**Comment by gorhill** [comment] 2015-06-30 17:34
Could not reproduce either. Also marked as _invalid_ given that no details other than one domain name was given.

**Comment by gorhill** [comment] 2015-07-08 13:59
Closing: un-reproducible issue abandoned by OP.

**Closed as completed by gorhill** 2015-07-08 13:59 UTC
Labels: invalid, unable to reproduce
