### ISSUE TITLE
Option to enable/disable by default

### ISSUE THREAD

**Issue by mac-pro** [gorhill/uBlock#3202] opened 2017-11-07 05:15 UTC
### Describe the issue

I've installed fresh version. And the extension is _on_ by default for _all_ sites.

Could you please add option to set On/Off by default for all sites? I just want to turn it on for some sites. I don't want to manually turn it off for every site I visit.

Thank you,

**Comment by adisib** [comment] 2017-11-07 06:20
Read these.

https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md
https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-turn-off-uBlock-everywhere-except

**Comment by gorhill** [comment] 2017-11-07 12:08
Duplicate of #1623.

**Closed by gorhill** 2017-11-07 12:08 UTC
Labels: duplicate
