### ISSUE TITLE
Cannot block ads on large media site

### ISSUE THREAD

**Issue by cheilbut** [gorhill/uBlock#1274] opened 2016-01-22 03:47 UTC
I can't seem to block the large ads on CP24.com, one of the largest news websites in Canada.

Here is an image showing the problem: http://i.imgur.com/g99fn0F.png

![unspecified](https://cloud.githubusercontent.com/assets/16830188/12501904/c9b39078-c090-11e5-8c47-d93bb8649359.png)

The advertising images are not selectable user the element picker tool.

**Comment by gorhill** [comment] 2016-01-22 06:23
Also, duplicate of #1202.

**Closed by gorhill** 2016-01-22 06:23 UTC
Labels: 3rd-party filter list issue
