### ISSUE TITLE
Can't install on firefox dev edition. 

### ISSUE THREAD

**Issue by alphameese** [gorhill/uBlock#444] opened 2015-07-05 08:27 UTC
When I try to install on firefox developer edition a pop up bubble say "uBlock Origin could not be install because Firefox Developer Edition cannot modify the needed file". I tried installing from the mozilla addon, and from github. I also tried an older and a new version of uBlock.

This is on the latest version of Firefox dev edition.

**Comment by gwarser** [comment] 2015-07-05 09:00
Broken Firefox profile. https://duckduckgo.com/?q=cannot+modify+the+needed+file

**Comment by gorhill** [comment] 2015-07-05 11:47
@alphameese I will let you investigate your issue, use the search results provided by @gwarser, there seems to be a lot of useful info in there, quite probably an issue unrelated to uBlock itself.

**Comment by gwarser** [comment] 2015-07-05 18:03
In my case (long ago), problem was caused by `dom.indexedDB.enabled` set to __false__.

**Comment by gorhill** [comment] 2015-07-05 18:31
@gwarser Was this ever a problem for uBlock, since it uses SQlite? I know ABP had [this problem](https://adblockplus.org/forum/viewtopic.php?f=1&t=27375), but I don't recall this flag affecting uBlock.

**Comment by gwarser** [comment] 2015-07-05 20:28
>Was this ever a problem for uBlock...?

Probably not. And should be fixed for over six months https://bugzilla.mozilla.org/show_bug.cgi?id=1079355#c37

**Comment by TRowbotham** [comment] 2015-07-06 01:38
I ran into this problem just yesterday when updating uBlock, although it has nothing to do with uBlock itself.  In my case, Firefox was trying to remove an old file from the ADB Helper add-on, which is used by WebIDE to debug on Android, but it couldn't remove the file because adb.exe was still running in the background.  My solution was to kill adb.exe and then the installing uBlock worked as expected.

**Comment by CrisBRM** [comment] 2015-07-06 03:31
Using dev edition on Windows and it's always worked fine here.

**Closed as completed** 2015-07-12 16:27 UTC
