### ISSUE TITLE
Needs to be verified in Firefox 43

### ISSUE THREAD

**Issue by TankMasterRL** [gorhill/uBlock#1077] opened 2015-12-15 22:47 UTC
Stumbled upon that the addon can't be loaded in Firefox version 43 because it needs to be verified. https://support.mozilla.org/1/firefox/43.0/WINNT/en-US/unsigned-addons There is a workaround listed here, but seems insecure to enable.

**Comment by zymase** [comment] 2015-12-15 22:50
// override signed add-ons requirement (FF42:warnings | FF43:block unless this override | 44:no override]
user_pref("xpinstall.signatures.required", false);

**Comment by gorhill** [comment] 2015-12-15 22:56
Duplicate of #1075.

**Closed by gorhill** 2015-12-15 22:56 UTC
