### ISSUE TITLE
Add the I don't care about cookies filter to Regions, languages?

### ISSUE THREAD

**Issue by Xarvz** [gorhill/uBlock#909] opened 2015-11-05 01:03 UTC
http://www.kiboke-studio.hr/i-dont-care-about-cookies/
Found it in Miscellaneous section of https://adblockplus.org/subscriptions
I don't know much about filters, but it has allot more then prebake. I'm guessing more is better ^_^

**Comment by gorhill** [comment] 2015-11-05 01:37
That list is quite suboptimal for uBO to say the least, it prefixes all generic cosmetic filters with `body [#.]`, which prevents uBO from optimizing their use. Unless somebody replaces all `body ` for filters matching `/^##body [#.]/`, I would advise strongly against using it with uBO.

**Comment by kiboke** [comment] 2015-11-05 06:32
Hi, am am the author/developer of that list.

I can't optimize it as suggested, there is a reason why I built it this way. There are quite a few websites that put IDs and classnames (related to cookie warnings) on the <body> itself. If I do as suggested, all of them would appear blank and would need a filter exception. Would entries like #some_id:not(body):not(html) be more acceptable?

**Comment by gorhill** [comment] 2015-11-05 13:00
> There are quite a few websites that put IDs and classnames (related to cookie warnings) on the body tag itself

What you are talking about concerns only one entry in your list:

    ##body.cookieBox #alertBox

What I am talking about concerns almost all generic cosmetic filter in the list. An example of an entry -- the 1st one:

    ##body #sliding-popup

This means that the target element is a descendant of the `body` element, not that the `id` is on the `body` element itself. By order of efficiency, uBO is optimised to deal with cosmetic filters as follow:

- Specific cosmetic filters (example: `theguardian.com##.identity-noticebar-content`):
    - These are just injected blindly whenever landing on the specific site.
- Generic cosmetic filters: injected on a per-need basis -- uBO surveys the DOM.
    - For ABP/AB/Adguard, it makes no difference, they are all injected unconditionally anyway.
    - _Low_ generic cosmetic filters: no hostname, but starts with `#` or `.`. These are dealt with efficiently.
    - _High-low_ generic cosmetic filters: of the form `[alt="..."]` or `[title="..."]`
    - _High-medium_ generic cosmetic filters: of the them `[href^="..."]`
    - _High-high_ generic cosmetic filters: everything which does not feed previous category.

The `##body #something` or `body .something` filters end up falling in the high-high generic category.

The only reason I could think the filters were designed this way was that you wanted to augment their specificity maybe to ensure the CSS rule has precedence over a page's own rule. For uBO this is _generally_ not an issue because the filters are inject after the DOM is fully loaded -- so the last CSS rule, which is uBO's one -- wins.

When I saw your list yesterday, I thought maybe I could remove the unnecessary `body` prefix at pre-compile time, but I haven't decided yet.

**Comment by kiboke** [comment] 2015-11-05 13:19
It is not unnecessary.

I think you didn't understand me. There are websites with, ie. body id="one-of generic-selectors" or html id="one-of generic-selectors" and then again inside body they have div id="one-of-generic-selectors". If i remove "body " part from the rule, the page will appear blank. And there are different websites which do that with different generic selectors.

How can i avoid these websites from turning blank without targeting elements only inside the body?

**Comment by gorhill** [comment] 2015-11-05 13:30
> If i remove "body " part from the rule, the page will appear blank.

Ugh, ok I see. Surely your suggestion of using:

    #some_id:not(body|html)
    .some_class:not(body|html)

Would work well for uBO, while probably making no difference for ABP and al.. For uBO, this would move all those high-high generics into the efficiently-handled low generic category.

**Comment by gorhill** [comment] 2015-11-05 14:09
@kiboke 

If the form `##body #[...]` or `##body .[...]` was more commonly used, another solution is to have uBO translate such filter at compile time to use the `:not`-based form -- but currently I can't find any other filter list using that form. This would not require adding any overhead, as that code would be executed only for when the filter is found to be high-high generic, a minority of filters. Let me know what is your decision.

**Comment by kiboke** [comment] 2015-11-05 16:01
I can rewrite rules like "body .something" to ".something:not(body):not(html)". Would that be ok then?
I am aware it is not the prettiest code ever but... what can we do...

**Comment by gorhill** [comment] 2015-11-05 16:15
> Would that be ok then?

Yes that would work for uBO, all these filters would become low-generic, i.e. efficiently handled. Keep in mind this is **not** required for cosmetic filters which are to be applied to specific hostnames (.e. `example.com##body .toto`).

Incidentally, I notice you already have some generic filters in there with the form `:not(body):not(html)`.

**Comment by kiboke** [comment] 2015-11-05 16:19
i do, because some websites put a div directly into html tag, outside of body, lol.
i'll do it and reply when it's done.

**Comment by rafuse** [comment] 2015-11-18 22:08
@kiboke Any news?

**Comment by kiboke** [comment] 2015-11-19 05:53
i prepared it, it will be available in a week probably along with the new "I don't care about cookies" extension version. I'll let you know.

**Comment by gorhill** [comment] 2015-11-19 13:29
I had what I think is a good idea for making uBO classifies these cosmetic filters as low generic, and this is probably a better approach, as this removes what may appear as an arbitrary restriction for a filter list maintainer. So it's up to you, you may prefer to not go ahead with the change if I can provide a more generic solution in uBO.

**Comment by kiboke** [comment] 2015-11-19 13:36
I have already prepared what was needed to be done, it's just not published yet.

**Comment by LifeIsStrange** [comment] 2015-11-19 18:24
Why it exist 3 lists (maybe more)  for block cookies related messages ? 
There is the I don't care about cookies list but also this https://github.com/r4vi/block-the-eu-cookie-shit-list
And this https://raw.github.com/liamja/Prebake/master/README.md
We should all benefit if this three list was merged for be more used and for share the work ;)

**Comment by kiboke** [comment] 2015-11-19 18:47
I agree.

I created my own because people asked me to do it. And if I see correctly, my list is waaay better than these two.

**Comment by LifeIsStrange** [comment] 2015-11-19 21:28
So you could speak at the developpers of the two others lists for merge and share work :) 
It's the free software magic, because you have the same finality you can cooperate instead of compete and create doublons. 
But you are the owner of your list, so as you wish ;)

**Comment by gorhill** [comment] 2015-11-21 00:50
In any case, v1.3.6 (dev build available) can now load that filter lists without the performance hit of causing thousands of high generic cosmetic filters being created. The fix was just to make uBO works a little bit harder to find a class- or id-based part in a whole CSS selector at compile time. This addresses the concern I had here for that specific filter list without the need to change the list.

**Comment by kiboke** [comment] 2015-11-21 08:22
It would be even better if uBlock (and others) would filter out possible blocking of body and html, so i don't have to put :not(body):not(html) everywhere.

Someone may put, ie, id="Banner728x90" on body itself, god knows why. With uBlock or ABP, the whole page becomes hidden when it really shouldn't be, right?

**Comment by dungsaga** [comment] 2015-11-24 07:51
@kiboke : Your idea could be useful for other list maintainers. I like it.

**Comment by kiboke** [comment] 2015-11-27 08:53
gorhill, i published the new version. your update certainly helps because some rules still have to have "body > " or "html > " prefix for some special reasons, although most of them have lost it.

**Comment by IDKwhattoputhere** [comment] 2015-12-01 11:25
I tried the filter list a few days ago because it seemed more thorough than Prebake. I can confirm it is very thorough. Broke like every 3rd site for me. I guess it's new and may get some fixes but at the moment it seems unusable.

**Comment by kiboke** [comment] 2015-12-01 11:43
what's exactly broken?

**Comment by IDKwhattoputhere** [comment] 2015-12-01 12:41
A few days ago it completely hid vpnbook.com (like the entire site except the background color). Seems to work now (that's why I had deleted my response since I tested again and now don't have any problems anymore).

**Comment by Ronnie91** [comment] 2015-12-26 18:13
Hi, 
how come you have not added the subscriptions "I don't care about cookies"?

I'm not finding any problem, indeed.

Best regards and Happy Holidays!

**Comment by gorhill** [comment] 2015-12-30 16:16
Given that the author of the list prefers that users use the list through his extension rather than through a blocker<sup>[1]</sup>, I will decline adding it to uBO. I added the list to the ["Filter lists from around the web"](https://github.com/gorhill/uBlock/wiki/Filter-lists-from-around-the-web) wiki page though.

[1] http://forum.palemoon.org/viewtopic.php?f=46&t=10585#p73651

**Closed by gorhill** 2015-12-30 16:16 UTC

**Comment by kiboke** [comment] 2015-12-30 16:32
gorhill, it's only logical to use the extension instead of the filterlist (when possible) because the extension should do the task better. the extension is not available for all platforms, that's where the list becomes handy.
