### ISSUE TITLE
document-blocked.html should show filter's origin

### ISSUE THREAD

**Issue by yfdyh000** [gorhill/uBlock#120] opened 2015-04-25 07:06 UTC
See https://github.com/chrisaljoudi/uBlock/issues/1203.

Example: `chrome://ublock0/content/document-blocked.html?details=eyJ1cmwiOiJodHRwOi8vbHVja3loZWFsaW5nc3RvcmUucnUvIiwiaG4iOiJsdWNreWhlYWxpbmdzdG9yZS5ydSIsImRuIjoibHVja3loZWFsaW5nc3RvcmUucnUiLCJ3aHkiOiJzYjp8fGx1Y2t5aGVhbGluZ3N0b3JlLnJ1XiJ9`

The rule in `chrome://ublock0/content/asset-viewer.html?url=assets/thirdparties/mirror1.malwaredomains.com/files/justdomains`, I need to manually, one by one to find it.

**Comment by gorhill** [comment] 2015-04-25 13:52
Duplicate of #58.

**Closed as completed by gorhill** 2015-04-25 13:52 UTC
