### ISSUE TITLE
SB and uB

### ISSUE THREAD

**Issue by silat** [gorhill/uBlock#929] opened 2015-11-11 21:59 UTC
Since upgrading to 133 uB I cannot get the popup (uB icon click
![2015-11-11_135841](https://cloud.githubusercontent.com/assets/7036902/11104253/5ea04ff2-887c-11e5-8f7a-49ad0a941b2a.jpg)

) to appear when I use Chrome in Sandboxie.

**Comment by gorhill** [comment] 2015-11-11 22:12
> when I use Chrome in Sandboxie

Sandboxie is the issue?

**Comment by silat** [comment] 2015-11-11 22:18
:) Maybe. I cannot stop using SB.

**Comment by gorhill** [comment] 2015-11-11 22:22
I cannot investigate for you the issue, you will have to confirm whether Sandboxie is the issue, and if confirmed find the fix.

**Comment by gorhill** [comment] 2015-11-11 22:27
Look in [uBO's dev console](https://cloud.githubusercontent.com/assets/585534/10864111/0a9cf23c-7fb9-11e5-83c0-97bc3f143849.png), chances is that there is an error message in there.

**Comment by silat** [comment] 2015-11-12 01:33
Maybe I am doing it wrong?

> On 11/11/2015 2:27:48 PM, Raymond Hill (notifications@github.com) wrote: 
> > Look in [uBO's dev
console](https://cloud.githubusercontent.com/assets/585534/10864111/0a9cf23c
-7fb9-11e5-83c0-97bc3f143849.png), chances is that there is an error message
in there.

**Comment by RoxKilly** [comment] 2015-11-19 05:02
I use Sandboxie 5.06 and Firefox 42 and uBlock Origin 1.3.2 and there is no conflict.

@silat  I'd like to test uB 1.3.3 but the latest version on Mozilla is 1.3.2 and the github version is not signed by Mozilla.  You can quickly test whether a conflict with Sandboxie is the issue by opening the browser outside of Sandboxie and seeing whether the uB panel opens normally.

@gorhill  what made you suspect Sandboxie? I've been using both software in conjunction since I installed uB, then later uB Origin earlier in the year.

**Comment by gorhill** [comment] 2015-11-19 12:46
> what made you suspect Sandboxie

I did not suspect it was Sandboxie, I asked to rule out that it was Sandboxie.

**Comment by gorhill** [comment] 2015-12-06 00:03
Closing until the case is made there is an issue with uBO -- seems there is something specific causing the problem on OP's side, as the popup is controlled by the browser in the first place, uBO merely provides the HTML document for the browser to fill the popup.

**Closed by gorhill** 2015-12-06 00:03 UTC
