### ISSUE TITLE
uBlock uses the same shortcut as Mac for the @

### ISSUE THREAD

**Issue by forty-four** [gorhill/uBlock#2739] opened 2017-06-27 12:23 UTC
Its no more possible to write an @ on Mac OSX since one of the last updates!!!
Your Log-Shortcut Alt+L blocks the common shortcut for writing an @!

Please change this shortcut!

- OS/version: OSX 10.11.6
- Browser/version: 58.0.3029.110 (64-bit)
- uBlock Origin version: 1.13.2

**Comment by gorhill** [comment] 2017-06-27 12:30
Duplicate of #2723.

**Comment by gorhill** [comment] 2017-06-27 12:31
See [Release notes for 1.13.2](https://github.com/gorhill/uBlock/releases/tag/1.13.2) for the fix.

**Closed by gorhill** 2017-06-27 12:30 UTC
