### ISSUE TITLE
Turkish Filter

### ISSUE THREAD

**Issue by bkrcrc** [gorhill/uBlock#952] opened 2015-11-20 13:37 UTC
Hello,
Can you please address this filter for Turkish users? The filter source is open to everyone to use.
Please add this as third party filter just like other countries filters. It has special rules for Turkish sites.
https://adguard.com/ru/filter-rules.html?id=13

If you accept to add this filter, then can you please enable this when a Turkish user installed uBlock Origin. uBlock can detect browser language to enable this rule?
Please tell me what you think.

**Comment by bkrcrc** [comment] 2015-11-23 15:38
BUMP!

**Comment by gorhill** [comment] 2015-11-23 15:56
It contains Adguard-specific filter syntax, consider the result undetermined when loading this filter list into uBO.

**Comment by bkrcrc** [comment] 2015-11-23 20:45
Yes, I realized that rules are not working on uBO. But other many rules works fine.
Is not it worth to add into uBO ?

**Comment by bkrcrc** [comment] 2015-11-27 15:23
Thank you for your interest!
I will close the topic.

**Comment by bkrcrc** [comment] 2015-11-30 16:16
Hey gorhill,
 Again me. What about this filter? I created this one for your needs!
https://github.com/bkrcrc/turkish-adblocklist

Please reply, I do not want to wait an answer for days.
Thanks

**Comment by gorhill** [comment] 2015-11-30 18:15
After looking at the details of [Adguard-specific syntax](https://adguard.com/en/filterrules.html), I decided that I will make uBO be able to import Adguard filter lists, **but** all unsupported Adguard-specific syntax will be discarded by uBO.

There is one instance of Adguard-specific filter which could be translated into a uBO-specific filter, but this will be implemented *maybe* at some point in the future. For now I prefer to limit the amount of changes.

**Comment by bkrcrc** [comment] 2015-11-30 22:04
Thank you, what about my list?

**Comment by gorhill** [comment] 2015-11-30 23:06
There is still an Adguard-specific filter in your list -- that's why I decided to foolproof uBO for when importing filter lists with Adguard-specific filters.

**Comment by bkrcrc** [comment] 2015-12-01 11:48
Can you please tell me which strings are they? I can remove them to make you add this filter :smile:

**Comment by gorhill** [comment] 2015-12-01 13:25
https://github.com/bkrcrc/turkish-adblocklist/blob/d041f71f61e97989add3123c40d21ffa3fab7577/turkish-adblocklist.txt#L14

Any filter with an occurrence of `#$#`, `#@$#`, `#%#`, `#@%#`, and `$$` will be rejected by uBO.

**Comment by bkrcrc** [comment] 2015-12-01 13:54
Only this rule broke the rule. Now, I updated the list and I searched for other rejected items.
Can you please check again?
Thank you by the way.

**Comment by bkrcrc** [comment] 2015-12-02 18:37
I saw that in changelog, we can use Adguard Turkish list. So there is no need for my filter.
Just another question again? Can uBo enable this filter after installation of uBlock on Turkish browsers?
Thanks.

**Comment by gorhill** [comment] 2015-12-02 19:03
> Can uBo enable this filter after installation of uBlock on Turkish browsers?

This would be a duplicate of #747.

Also, I can't add the Turkish filter list in uBO's set of filter lists until I am confident everybody is using a version which can deal with Adguard filter lists.

**Closed** 2015-12-30 16:09 UTC
