### ISSUE TITLE
uBlock with Ghostery

### ISSUE THREAD

**Issue by peterbandi** [gorhill/uBlock#2897] opened 2017-08-25 13:39 UTC
### Describe the issue

I  am using Ghostery 7.3.2.5 and uBlock Origin 1.13.8 together. Recently  the combination of the two extensions causes the browser to slow down  beyond being usable by causing 100% CPU usage. (On a single core.) This  is particularly prevalent when using GMail.

With  either Ghostery or uBlock disabled the browser works just fine. First I contacted Ghostery. According to them "uBlock intercepts and redirects their requests".

I am using uBlock and Ghostery together for a long time. These are the two most important add-ons of Firefox.  I would like to keep using them together. Please fix the problem if possible.

### One or more specific URLs where the issue occurs

https://www.google.com/gmail/

### Steps for anyone to reproduce the issue

The high CPU usage occurs faster if there are several pages open where both Ghostery and uBlock is active.

0. Install Ghostery and uBlock together to Firefox.
1. Open a bunch of pages:
https://www.theverge.com/2017/8/25/16201444/xbox-one-x-hands-on-analysis-gamescom-2017
https://arstechnica.com/gaming/2017/08/final-fantasy-15-pc-gameworks-hajime-tabata-interview/
https://arstechnica.com/gaming/2017/08/half-life-3-plot-marc-laidlaw/
https://arstechnica.com/gadgets/2017/08/with-the-uss-mccain-collision-even-navy-tech-cant-overcome-human-shortcomings/
http://www.anandtech.com/show/11758/kingston-datatraveler-vault-privacy-and-edge-diskgo-secure-pro-secure-usb-thumb-drives-review
http://www.anandtech.com/show/11764/silicon-motion-roadmap-lots-of-nvme-ssd-controllers
https://www.techspot.com/news/70720-half-life-writer-reveals-plot-could-have-seen.html
https://www.theverge.com/2017/8/23/16194366/exxon-mobil-knew-climate-change-misinformation-harvard-study
https://www.theverge.com/2017/8/23/16193236/google-depression-questionnaire-mental-health
https://www.google.com/gmail/

2. Interact with the pages, e.g. GMail. Open emails, browse inbox.
3. See at the processor usage builds up to 100% (on a single core) and Firefox gets unresponsive.

### Your settings

- OS/version: Windows 10 Pro version 1703 build 15063.540
- Browser/version: Firefox 54.0.1 (64-bit)
- uBlock Origin version: 1.13.8
- Ghostery version: 7.3.2.5

##### Your filter lists

uBlock filters​​​​​
uBlock filters – Badware risks​​​
uBlock filters – Privacy
​​uBlock filters – Unbreak​​​​​
EasyList
EasyPrivacy
Malware Domain List
​​Malware domains
Peter Lowe’s Ad and tracking server list

**Comment by gorhill** [comment] 2017-08-25 13:51
Please use the [Gecko profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) to create profiling results, and share these so that I can look at them.

**Comment by gorhill** [comment] 2017-08-25 15:01
Any reasons why you are still using Firefox 54? Current stable is Firefox 55.

An important bug affecting Gmail, Youtube, etc. was solved in Firefox 55. The bug was causing web pages from Gmail, Youtube to hang forever: ["gmail is slow or stops responding"](https://bugzilla.mozilla.org/show_bug.cgi?id=1380896).

**Comment by Atavic** [comment] 2017-08-25 18:02
According to [AMO](https://addons.mozilla.org/en-US/firefox/addon/ghostery/) reviews, current version of Ghostery has issues.

**Comment by shevegen** [comment] 2017-08-25 19:37
It's not directly related to the issue here but I used to use ghostery back when I was using adblock plus, mostly because I was curious how much off-site tracks are made. It's quite interesting how some sites seem to be just proxy-gates towards other sites, looking at how much ghostery tracks and blocks. But I eventually gave up on ghostery largely because it seemed to be too complex (for me) and also because I have a slight suspicion that it slows down browsing behaviour a little. After I switched to ublock origin I did not have a real need for ghostery but basic information of how sites send information to other sites is still quite interesting to see. (Many of these requests were e. g. facebook button, google button and what not buttons...)

**Comment by robjarsen** [comment] 2017-08-25 20:31
@shevegen 

I wouldn't touch Ghostery with a 12 foot pole.

**Comment by Atavic** [comment] 2017-08-25 21:53
Does Ghostery provide unique lists? Don't think so, by the way you can 3rd party lists into uBo.

>I wouldn't touch Ghostery with a 12 foot pole.
Yep, Ghostery tracks its users.

**Comment by Atavic** [comment] 2017-08-26 16:14
Does Ghostery provide unique lists? Don't think so, by the way you can 3rd party lists into uBo.

>I wouldn't touch Ghostery with a 12 foot pole.

Yep, Ghostery tracks its users.

**Comment by 0xCHERRY** [comment] 2017-08-26 18:48
(((Ghostery)))

**Comment by gorhill** [comment] 2017-08-26 20:07
This issue is going nowhere. The only thing I am interested in now is evidence that uBO specifically is causing an issue. Profiling from OP (or someone who can reproduce) would be such evidence.

**Comment by gorhill** [comment] 2017-08-30 18:04
Closing due to no feedback. There is a new rule on CONTRIBUTING: speculated performance issue are not longer allowed. You will need to profile and details what in the profiling data makes the case that there is an issue with uBO _itself_.

**Closed by gorhill** 2017-08-30 18:04 UTC
