### ISSUE TITLE
[Chrome] no-popups: * true rule issue

### ISSUE THREAD

**Issue by harshanvn** [gorhill/uBlock#2277] opened 2016-12-29 04:07 UTC
### Describe the issue

Having `no-popups: * true` rule, and opening a link (through left-click) causes previously opened tab to close itself..

### One or more specific URLs where the issue occurs

**_Sample URL_**: https://github.com/gorhill/uBlock/issues 

### Screenshot in which the issue can be seen

**_N/A_**

### Steps for anyone to reproduce the issue

1. Open/Navigate to https://github.com/gorhill/uBlock/issues in new Window
2. Right-click on any issue and select **_open link in new tab_**, for example do it for  (#2276) issue.
3. At this point, you have 2 tabs opened.
4. Now, on the 1st tab, open any issue **_by left-click_**
5. You will see that **2nd tab is closed** because of `no-popups: * true`, which should not be the case.

### Your settings

- Browser/version: Chrome v55.0.2883.87 m (64-bit), W10
- uBlock Origin version: 1.10.4

##### Your filter lists

uBlock Filters + Malware Domains ( Option 1 & 2 ) + Social ( Option 2 ) + Multipurpose ( Option 5 )

##### Your custom filters (if any)
no-popups: * true ( i have many, i don't think it matters here )

**Comment by uBlock-user** [comment] 2016-12-29 08:05
> 2nd tab is closed 

Can't reproduce that. The tab stays open in my case, nothing happens.

**Comment by okiehsch** [comment] 2016-12-29 17:35
I can reproduce.
1. Right-click https://github.com/gorhill/uBlock/issues/2276
2. Left-click   https://gist.github.com/
3. Result
![popup](https://cloud.githubusercontent.com/assets/16838044/21549841/68ae423c-cdf5-11e6-92b6-a7c939d0f3d2.PNG)

**Comment by gorhill** [comment] 2016-12-29 19:52
I can reproduce. There is a 10-second span within which uBO will keep evaluating whether the popup must be closed or not.

Fix for this is not trivial, I need to investigate.

**Comment by uBlock-user** [comment] 2016-12-30 08:21
okiehsch, with your steps, I can reproduce.

**Comment by gorhill** [comment] 2017-10-13 13:34
Fixed with 7713597e3e3ecf5c03c70f56bdb989e7d78956e8.

**Closed by gorhill** 2017-10-13 13:34 UTC
