### ISSUE TITLE
Pressing Esc does not exit Zapper mode.

### ISSUE THREAD

**Issue by ev88** [gorhill/uBlock#2719] opened 2017-06-21 06:20 UTC
### Describe the issue
When entering 'Zapper' mode, pressing Esc does not exit you from the mode.  You must refresh the page in order to leave it.  I have disabled my other add-ons and still have the issue.

### Steps for anyone to reproduce the issue
1. Enter Zapper mode.
1. Press Esc to exit mode.
1. It will not exit Zapper mode.  Refresh page to exit.

### Your settings
- OS/version: Win7 64bit
- Browser/version: 54.0
- uBlock Origin version: 1.13.0

**Comment by gwarser** [comment] 2017-06-21 07:46
Vivaldi 1.10.867.38 (Stable channel) (64-bit) 
UBO 1.13.0

All shortcuts not work, but when in element zapper mode, then right click, I can hit ESC twice to exit.

**Comment by uBlock-user** [comment] 2017-06-21 08:13
Can't reproduce on Chromium v61. It escapes as expected.

**Comment by FX54** [comment] 2017-06-21 08:50
>  Describe the issue
> 
> When entering 'Zapper' mode, pressing Esc does not exit you from the mode. You must refresh the page in order to leave it. I have disabled my other add-ons and still have the issue.
> Steps for anyone to reproduce the issue
> 
>     Enter Zapper mode.
>     Press Esc to exit mode.
>     It will not exit Zapper mode. Refresh page to exit.
> 
> Your settings
> 
>     OS/version: Win7 64bit
>     Browser/version: 54.0
>     uBlock Origin version: 1.13.0
> 
Delete also do not work.

---
**Works after delete element with  pressed Shift.**

_Win7 64bit, Firefox 54.0 (x64),    uBO 1.13.0_

**Comment by gorhill** [comment] 2017-06-21 11:09
Duplicate of #953.

**Closed by gorhill** 2017-06-21 11:09 UTC
Labels: duplicate

**Comment by FX54** [comment] 2017-06-22 09:18
[CTR](https://github.com/Aris-t2/ClassicThemeRestorer) confilict with Zapper (block working key correct working).

**Comment by FX54** [comment] 2017-06-23 10:27
> The webext version of uBO suffers the same issue -- this will need to be fixed by Firefox.

Bug with electrolysis + addons à la CTR.
