### ISSUE TITLE
Popup UI not opening

### ISSUE THREAD

**Issue by walderich** [gorhill/uBlock#2007] opened 2016-09-19 21:56 UTC
### Describe the issue
When the uBO button is moved to the Firefox tab bar and the navigation bar is hidden, the popup UI is not displayed anymore. When making the navigation bar visible again, the popup UI opens from the tab bar as expected.

It seems that the popup UI depends on the navigation bar to be visible to work correctly.

### One or more specific URLs where the issue occurs
As this issue is not site-specific it occurs on every page, even special pages like addons or downloads.

### Screenshot in which the issue can be seen
![ubo_popup](https://cloud.githubusercontent.com/assets/241444/18649825/e1793e02-7ec1-11e6-8248-74c28f949d48.png)

### Steps for anyone to reproduce the issue
1. Customize Firefox
2. Drag uBO button to tab bar
4. Exit customization (the button still works now)
3. Hide navigation bar
 - I am using Vimperator extension for this: `:set gui+=nonavigation`
4. Try clicking on the uBO button

### Your settings
- Browser/version: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
  - Addon Vimperator for navigation hiding
- uBlock Origin version: 1.9.6

##### Your filter lists
Only the default list from the installation.

##### Your custom filters (if any)
None

**Comment by gorhill** [comment] 2016-09-19 22:08
Duplicate of #610.

**Closed by gorhill** 2016-09-19 22:08 UTC
