### ISSUE TITLE
uBlock affecting Tor Browser default screen size

### ISSUE THREAD

**Issue by bendover22** [gorhill/uBlock#2216] opened 2016-12-05 01:16 UTC
Following up on <https://github.com/gorhill/uBlock/issues/714>
uBlocko affecting Tor Browser default screen size in Windows.
In last few Tor Browser - TBB - versions, still in TBB 6.0.6, 6.0.7 - uBlocko is definitely affecting the default screen size on startup.  Disable uBo and the issue goes away.  Re-enable it & issue returns.  

Haven't used uBo that long in TBB.  Issue began immediately on installing uBo 1.9.16, now updated to 1.10.
I use default uBlock settings & default filter lists.
Only default setting changed - checked "I'm an advanced user."  (and read Advanced User Features couple of times).

I'm not using uMatrix along with uBlock, as Ghost said in issue #714.  I use NoScript (default in TBB), but tried uBlock alone w/ all  default TBB addons disabled  - same issue.  uBlocko is the only non-standard addon installed.

Perhaps this depends on specific user prefs choices - ones generally accepted as OK to change in TBB?
Like the security level slider setting - under Tor Button (green onion) > Privacy & Security Settings.
Or whether NoScript is set to block all scripts, or using the default to allow all scripts?

When 1st start TBB, the overall height is much taller than the standard size - by 2 inches or more.  Screen width seems the same.  I did check dimensions w/ screen capture prgm, & at a couple of fingerprinting test sites.
After opening TBB, if select "New Identity" - once - from the TBB onion button, it restarts at the correct default screen size - every time.  Odd.  After one new identity, opening & closing tabs has no affect, but close & restart TBB consistently causes incorrect screen size.

Thanks.

**Comment by dqgls** [comment] 2017-01-04 23:47
Same problem here:

 - uBlock0 with default settings
 - Tor Browser with default settings, the only add-on is uBlock0
 - Linux

This problem has been present ever since I've started using uBlock0 in Tor Browser a few months ago. If uBlock0's toolbar button is placed on the toolbar then window is resized to full height on every start up of Tor Browser, and fixed on restarting the browsing session ("New Identity") which seems to restart the Firefox instance. If the toolbar button is removed (i.e. placed within Firefox's "Customize" view) then the window is resized to full height more rarely.

---

The problem is "solved" by commenting out this piece of code in `js/popup.js` starting at line 55:
```
    /*var rpane = document.querySelector('#panes > div:nth-of-type(1)');
    if ( typeof rpane.offsetHeight === 'number' ) {
        document.querySelector('#panes > div:nth-of-type(2)').style.setProperty(
            'height',
            rpane.offsetHeight + 'px'
        );
    }*/
```
This is from the version of uBlock0 that is on Mozilla's official add-on site/repository.

If anyone wants to test this as well, then you need to modify `js/popup.js` in `uBlock0@raymondhill.net.xpi` which is located in `<your Tor Browser directory>/Browser/TorBrowser/Data/Browser/profile.default/extensions/`. The `.xpi` file can be opened and modified with an archive manager. If the modified add-on isn't allowed to run then go to `about:config` and change `xpinstall.signatures.required` to `false`.

I haven't tested yet the version in this github repo, which is a bit different, but the relevant code seems to be at [line 525](https://github.com/gorhill/uBlock/blob/1a92fff6418884edad2991ecd49a305a18b8612f/src/js/popup.js#L525):
```
    lpane.style.setProperty('height', rpane.offsetHeight + 'px');
```

**Comment by gorhill** [comment] 2017-01-05 13:28
The key missing part in this issue and #714 is the following: there is absolutely no step provided as to how the browser size was determined. So on my side I just found a web site which report the size as seen by javascript executed in the loaded page. This is what I get:

![a](https://cloud.githubusercontent.com/assets/585534/21682125/cf0e878c-d320-11e6-824c-a973752aa661.png)

**Comment by dqgls** [comment] 2017-01-05 19:09
1. unpack a fresh latest stable version of Tor Browser (6.0.8 at this moment)

2. start it and go to whatsmy.browsersize.com: the reported size is something like 1000x900 or 1000x700, depending on your screen size (Tor Browser picks the largest possible out of its limited selection, in order to make you less trackable), in my case 1000x700:
![without-ublock0](https://cloud.githubusercontent.com/assets/24620467/21693630/8e5a9664-d379-11e6-8c50-18fb5f78d3e4.png)

3. go to `about:addons` page and install "uBlock Origin" from the search bar (at this moment version 1.10.4 is in Mozilla's repo)

4. close down Tor Browser

5. start Tor Browser again: the window is now maximized vertically. go to whatsmy.browsersize.com: reported size is your screen height, minus whatever panels you have, and minus browser's own window borders, toolbars, etc., in my case 1000x775:
![ublock0-initial-full-height](https://cloud.githubusercontent.com/assets/24620467/21693480/0738af4a-d379-11e6-8440-ee8443a53b32.png)

7. click on Tor button and select "New Identity", then go to whatsmy.browsersize.com: the window is now back to Tor Browser's standard size, in my case 1000x700:
![ublock0-after-new-identity](https://cloud.githubusercontent.com/assets/24620467/21693497/1161883e-d379-11e6-89a6-e443ec07ea74.png)

**Comment by dqgls** [comment] 2017-01-05 20:31
> So on my side I just found a web site which reports the size as seen by javascript executed in the loaded page. This is what I get:

I see that your Tor Browser window is 900 in height. This makes me think that the issue maybe appears only on screens that have less than 900 pixels of available vertical space for windows. So the problem could be that when uBlock0 initially loads, before the browser window itself is fully initialized, some part of it uses more than 700 vertical pixels at some point in its initialization, which disrupts Tor Browser's attempt at setting window size.  Can you test on a smaller screen? Or you could try lowering your resolution and test it then.

---

I experimented a bit with the current github version (latest commit is 1a92fff at the time of writing), and I can't really find what exactly is the source of the problem.

The window is _not_ maximized vertically if:

- I remove the `renderOnce();` call in the `getPopupData` function in `popup.js`

- I remove the whole `<div id="panes">...</div>` in `popup.html` and `<script src="js/popup.js"></script>`

The window is _sometimes but not always_ maximized vertically if:

- I remove pane height code in the `renderOnce` function in `popup.js`, or even comment out the whole contents of the `renderOnce` function

The window _is_ maximized vertically even if:

- I remove `<script src="js/popup.js"></script>` in `popup.html`

It seems that while removing some parts of javascript can prevent the problem from appearing, the actual cause is elsewhere (maybe in `popup.css`?), because even without the `popup.js` reference the presence of the popup panes is consistently correlative with vertical maximizing of the window.

**Comment by gorhill** [comment] 2017-01-05 20:46
You seem to focus a lot on the popup panel. Note that `popup.js` is **only** loaded through the `popup.html` document, and the `popup.html` document is added to the browser **if and only if** the `popupshowing` event is fired by the browser -- i.e. when one click the toolbar icon. I think you need to also look elsewhere, I fail to make sense of why the code in `popup.js` would have any effect on the browser size -- it's never executed unless one click uBO's icon.

**Comment by gorhill** [comment] 2017-01-05 20:53
> Or you could try lowering your resolution and test it then.

I lowered my resolution to 1280x720, and now I can reproduce the issue. So I can now investigate.

**Comment by gorhill** [comment] 2017-01-05 21:47
After poking around various places, I found that if I change `tryDelay` to `10000` in `bootstrap.js`, the issue seems to vanish:

    // https://github.com/gorhill/uBlock/issues/749
    // Poll until the proper environment is set up -- or give up eventually.
    // We poll frequently early on but relax poll delay as time pass.

    let tryDelay = 10000;

<https://github.com/gorhill/uBlock/blob/8c632db4369e887acf073247c4c3211e66f41adf/platform/firefox/bootstrap.js#L106>.

Of course setting a 10s delay before uBO can do any work is not the proper solution, thus next step is to figure out why this works, then it will be possible to figure out what is the proper solution.

**Comment by bendover22** [comment] 2017-01-05 23:05
> I lowered my resolution to 1280x720, and now I can reproduce the issue.
Mine is 1920 x 1080 & the problem exists - for me in Vista x64.  Don't know if the OS brand & exact version could affect this also.

I previously  had Windows' DPI increased (for older eyes) from default 96 to 110 DPI (115% of default).  TBB still "forced" my  width to 1000 px, but the height was NOT an increment of 100.   The height not being rounded when Windows' DPI is a non-default value is a TBB devs' issue. 

To test this uBo issue, I reset Vista's DPI to default 96.  Now, on TBB's 1st start it's **still 1000 wide** x 928 H.  
**After a new TBB identity**, three test sites show a screen size 1000 W x 900 H. 
[[IMG]http://i67.tinypic.com/sb3794.jpg[/IMG]](url)

[[IMG]http://i68.tinypic.com/2gsmwd0.jpg[/IMG]](url)

FYI:  browserspy.dk or https://panopticlick.eff.org/  show screen size & many other fingerprinting data. 

Now that you mention it, when TBB 1st starts, it opens to one size - for a fraction of a second, then appears to resize.  It happens very fast, but I'm guessing it winds up a little larger than when it 1st opens.

**Comment by bendover22** [comment] 2017-01-05 23:13
Sorry, clicking "Comment" in previous post didn't submit it (after waiting).  Mistakenly hit "close & comment."  40 lashes.

**Comment by bendover22** [comment] 2017-01-06 01:03
Gorhill, by

> I can't reproduce the issue when I click "New Window" in the hamburger menu, so this suggests a timing issue
Did you really mean the **New Window** icon from the customize menu?  Or was that comment in **addition** to our instructions of clicking "New identity" in the green onion icon (Tor Button)?
Just  clarifying.

**Comment by dqgls** [comment] 2017-01-06 02:03
> Did you really mean the New Window icon from the customize menu? Or was that comment in addition to our instructions of clicking "New identity" in the green onion icon (Tor Button)?

The thing is that after starting Tor Browser _any_ new window will have the proper size, doesn't matter whether it's created from within the initial "identity" session, or created by starting a "new identity". So this suggests there's a very short-term timing clash between uBlock0's initialization and whatever Tor Browser does to ensure uniform window sizes on window creation.

Once uBlock0 is already initialized there won't be any clashing with window creation. And conversely, rebooting uBlock0 via browser's addon page (disable & enable) while a window is already opened won't make the issue appear either.

That it's a timing issue makes it really hard to inspect what's going on because any change or removal of some piece of code can make the issue disappear sporadically since it changes timing of the execution. 

I'm now experimenting with "Firefox >= 36" section of `vapi-background.js` and I can't find anything specific that would be clearly connected to the issue.

**Comment by gorhill** [comment] 2017-01-06 19:28
I intended to look into this just now but turns out I am unable to reproduce at the moment -- tried to launch probably 30 times, window size was fine every time.

**Comment by dqgls** [comment] 2017-01-07 17:45
It seems the issue appears consistently if:

- vertical space is sufficiently low (somewhere below 900 pixels)
 
- uBlock0 icon is placed on the toolbar

If I remove the icon from the toolbar the issue appears only occasionally, if I had to guess I'd say once per 20 launches.

**Comment by bendover22** [comment] 2017-01-08 04:31
@dqgls, gorhill,
I think the "**content-sizer.js**" file, in \chrome\content folder, in the TorButton addon is how TBB currently (attempts) to round "usable" screen size to multiples of 100.  Doesn't work 100% for all users (but this uBo issue is different than TBB's screen size rounding issues).  
However, maybe TorButton's resizing code could give some clues, like comment on timing:

> "listenForTrueResize(window, timeoutMs)__.
> // Task.jsm function. Call `yield listenForTrueResize(window)` to
> // wait until the window changes its outer dimensions. Ignores
> // resize events where window dimensions are unchanged."

* Note:  In 15 TBB restarts (w/ uBo's icon removed), it opened at correct height 4/15 times.  I'm not a coder, but removing my uBo icon doesn't produce the results dqgls saw.
FWIW, I've got a fast machine w/ plenty of free RAM & CPU resources.

* The starts where TBB ends up way too long, it initially opens to (roughly) 800-ish px for fraction of a sec., then extends below / behind the taskbar.  
When it does this, the initial height for fraction of a sec. (bottom edge of TBB screen) "seems" closer to the 800 value **it should be**, than when uBo does NOT affect the height.  When uBo isn't installed, TorButton? always puts the height at 729 when it should be 800.

(side issue): TBB's code doesn't round HEIGHT to nearest 100 correctly for me & some others.  Don't know why it rounds my width OK (to 1000) - with a non-default system DPI, but not the height.  I've asked & filed / contributed to several bugs on the same issue - no one's saying.  The last time it rounded mine correctly (1000x800) was v3.6.6 - over 2 yrs ago.  At v4.0 it started showing height=729 & still is in v6.08.  If I could find a firefox pref that hard codes the height, I'd do that.

TorButton adds 2 prefs for MAX window height & width in about:config, but not hard height & width values.  extensions.torbutton.window.maxHeight;1000 and extensions.torbutton.window.maxWidth;1000

**Comment by bendover22** [comment] 2017-01-11 06:32
@dqgls - do you mean "_no more (sizing) clashing with uBo_" - in the **6.5a versions**?
Cause I still have the problem in v6.08.
In those, are they rounding to multiples of 200 x 100, 200 x 200 or 100 x 100?  They've been undecided on which ratio to use.   Other than ancient 4:3 monitors that they don't want to look a lot different, not sure why they don't make it wider on WS monitors.  A 1000x900 isn't a very big browser screen.  Maybe some countries still have lots of old monitors.

> set extensions.torbutton.resize_windows to true
When I 1st looked at that pref it = **true** by default (not "user set" and not bolded), in my TBB Win v6.08.  But, TBB wasn't resizing correctly.  If I had set it to true, it'd show "user set" & be bold font.???  So, restarted to see if it helped.  When it restarted, the pref was back to false & showed "default."  Huh? (The pref's not in a user.js file). 

Anyway, changed it back to True & restarted.  As you said, this time it sized the height correctly with uBo enabled.  Only tried about 5 more starts, but so far they all worked.
I'll test more tmrw.
My only guess is, for some OSes or some monitors, that pref doesn't work (in 6.08), so they disabled it for all.  Surely, they wouldn't "forget" to enable the pref?

> One thing to note is that window is still being resized to full height on launch in **stable** version, but it's immediately resized back to proper height, so this feature works only as an "after-fix" in this version.

Don't follow that last statement.  In my  v6.08, it's NOT being resized to proper height, if uBo is installed, unless get a new identity.  Or... did you mean it resizes correctly in the stable version with uBo enabled, **IF you change the "resize_windows" pref?**    There's only one stable version - 6.08.  Did you mean it's resizing to proper height in the UNstable versions?

**Comment by dqgls** [comment] 2017-01-11 14:52
>> One thing to note is that window is still being resized to full height on launch in stable version, but it's immediately resized back to proper height, so this feature works only as an "after-fix" in this version.
>
> Don't follow that last statement.

I mean that _enabling `resize_windows` in the current stable version (6.0.8) with uBlock0 installed_ doesn't actually prevent the vertical maximization ("uBlock0 clash"), it just immediatelly corrects it. From user's perspective: you launch a Tor Browser 6.0.8 with uBlock0, window opens vertically maximized, but gets instantly resized to proper size.

On the other hand in the current experimental version (6.5a6) with uBlock0 installed you don't get any vertical maximization ("uBlock0 clash") at all anymore, not even momentarily, _not even with `resize_windows` disabled_.

In other words: `resize_windows` is not an actual fix of the issue, it's just something that neutralizes it: with this feature enabled the user doesn't have to manually choose to correct the size anymore by clicking on "new identity" or opening a "new window", the feature automatically corrects the window size for the user instead.

So the actual fix is in something else that is implemented or enabled in the experimental (6.5a6) version and isn't yet in the stable (6.0.8) version. There's a possibility that the next major stable release (6.5) will also contain this fix, whatever it is. I think they usually release stable ones about half a year after alphas, but this time they're taking a bit longer, so I couldn't say.

---

> In those, are they rounding to multiples of 200 x 100, 200 x 200 or 100 x 100?

100 x 100 is what I'm currently seeing in both stable version (with `resize_windows` manually enabled) and experimental version (`resize_windows` already enabled by default). If you have the feature enabled then you can see for yourself by resizing your window, it will automatically correct it to a closest possible multiple of 100 x 100.

> My only guess is, for some OSes or some monitors, that pref doesn't work (in 6.08), so they disabled it for all. Surely, they wouldn't "forget" to enable the pref?

I think it generally works but it has some unwanted side effects in certain situations, so for now it's intentionally set to false in stable versions. They discuss these issues here: https://trac.torproject.org/projects/tor/ticket/14429

---

> BTW, did you notice on http://browserspy.dk/date.php, it detects your computer's EXACT clock time & of course, time zone? I posted on tor-talk & Georg K. replied - a pretty new bug

Thanks for the heads up. For me those fields get filled only at medium-low security, and it reports (hardware's?) UTC time instead of system's local time, but the reported difference in seconds between my computer's and their server's time _is_ potentially trackable, even though it's fluctuating a bit. I didn't see that torproject ticket mentioning the latter so I will warn them about that as well.

**Comment by dqgls** [comment] 2017-01-25 12:50
@gorhill I think you can close this issue now that Tor Browser 6.5 stable was released which doesn't clash whatsoever with uBlock0 anymore.

@bendover22 can you confirm this as solved on your side as well?

(Also, nice to see uBlock0 included in the new Tails release, which also comes with TBB 6.5! More uBlock0 users, more uniformity.)

**Comment by bendover22** [comment] 2017-01-25 19:40
Downloaded TBB 6.5 but not yet tested.  They made other improvements in 
screen sizing, which could help the uBlock issue.
If I still see problems, I'll post back.

Ben D.

**Comment by gorhill** [comment] 2017-01-25 23:51
>  I think you can close this issue now that Tor Browser 6.5 stable was released which doesn't clash whatsoever with uBlock0 anymore.

Ok happy to hear this as I still had no clue where to look to resolve this issue.

**Closed by gorhill** 2017-01-25 23:51 UTC
